upcoming: [M3-7455] - Add child account access column and disable button when account has child accounts
linode/manager pull request #10012
Opened 2023-12-20 16:39 UTC by tyler-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- Add child account access column
- Disable button when account has child accounts

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps 
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2023-12-27 20:41 UTC, tyler-akamai commented on packages/manager/src/features/Account/CloseAccountSetting.tsx
> +  const closeAccountDisabled = flags.parentChildAccountAccess
If the current account has child accounts, disable the 'Close Account' button

2023-12-27 20:42 UTC, tyler-akamai commented on packages/manager/src/features/Account/CloseAccountSetting.tsx
> +              <Notice spacingBottom={20} variant="info">
This was not in the mocks but we should tell the user why the button is disabled. I can run this by the UI team.

I tried to keep this consistent with the 'Backup Auto-enroll' Section:
![Screenshot 2023-12-27 at 3 42 03 PM](https://github.com/linode/manager/assets/139489745/ccd01041-1435-424c-9f36-4c7836029152)

2023-12-29 20:48 UTC, mjac0bs reviewed
Nice! Just some minor things here. If there's any outstanding feedback you don't get to, I can pick this up.

✅  Unit tests are passing 🎉 
✅  Ensured there is an additional 'Child Account Access' column with accurate labels ('Enabled' and 'Disabled')
✅ Ensured the Close Account button is disabled since the current account has a child account, and ensure there is a notice explaining why it is disabled.
✅  Ensured the Close Account button is enabled if the current account does not have any child accounts. 
Ensure the parent/child feature flag works as expected
- See the comment in UserRow.tsx for a crash fix.

2023-12-29 20:48 UTC, mjac0bs commented on packages/manager/src/features/Users/UserRow.test.tsx
Optional: One thing that could make this test a little more precise is to look for text within its specific column (e.g. rather than just checking that the text "Enabled" or "Disabled" exists, checking that it exists within the Child Account Access column) - thinking about how, if data is extended in the future, "Enabled/Disabled" might not be unique to the Child Account Access column.

2023-12-29 20:48 UTC, mjac0bs commented on packages/manager/src/features/Users/UserRow.tsx
> +          {grants?.global.child_account_access ? 'Enabled' : 'Disabled'}
```suggestion
          {grants?.global?.child_account_access ? 'Enabled' : 'Disabled'}
```
With the feature flag on and mocks OFF, we ended up with an Oh Snap crash on this page:
![image](https://github.com/linode/manager/assets/114685994/7cafb810-8f59-4639-82da-dd09e8c0b1c0)

2023-12-29 20:48 UTC, mjac0bs commented on packages/manager/src/features/Account/CloseAccountSetting.test.tsx
> +      'Remove child accounts before closing the account.'
```suggestion
      'Remove child accounts before closing your account.'
```
Wondering if this is slightly clearer.

2023-12-29 20:48 UTC, mjac0bs commented on packages/manager/src/features/Account/CloseAccountSetting.test.tsx
> +    const button = getByTestId('close-account-button');
Nit: switch the order of these two lines so that consts and expects are grouped together. It's a bit easier to read.

2023-12-29 20:48 UTC, mjac0bs commented on packages/manager/src/features/Users/UserRow.test.tsx
> +  it('renders "Disabled" if the user does not have Account Access', () => {
```suggestion
  it('renders "Disabled" if the user does not have Child Account Access', () => {
```

2024-01-01 15:20 UTC, jaalah-akamai requested changes

2024-01-01 15:20 UTC, jaalah-akamai commented on packages/manager/src/features/Account/CloseAccountSetting.tsx
> +  const closeAccountDisabled = flags.parentChildAccountAccess
We should be able to simplify this: 
```const closeAccountDisabled = flags.parentChildAccountAccess && Boolean(childAccounts?.data?.length);```

2024-01-01 15:20 UTC, jaalah-akamai commented on packages/manager/src/features/Account/CloseAccountSetting.tsx
> +              <Notice spacingBottom={20} variant="info">
Agreed, good callout

2024-01-01 15:20 UTC, jaalah-akamai commented on packages/manager/src/features/Users/UserRow.tsx
> +      {flags.parentChildAccountAccess && (
We should provide a better check here as opposed to just relying on the feature flag, since that will disappear in the future and this entire column will be conditionally rendered.

2024-01-01 15:20 UTC, jaalah-akamai commented on packages/manager/src/features/Users/UsersLanding.tsx
> +            {flags.parentChildAccountAccess && (
Same here, need a better check than just the feature flag

2024-01-02 16:03 UTC, jaalah-akamai commented on packages/manager/src/features/Account/CloseAccountSetting.test.tsx
> +      'Remove child accounts before closing the account.'
This should change to `Remove indirect customers before closing the account.`

2024-01-03 15:21 UTC, closed without merging