feat: [M3-7459] - Improve Accessibility of Button Component
linode/manager pull request #10028
Opened 2024-01-03 20:47 UTC by jaalah-akamai

## Description 📝

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps 
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-01-03 22:42 UTC, jaalah-akamai commented
May be some broken E2E tests I'll need to fix with this

2024-01-04 03:53 UTC, jaalah-akamai commented on packages/manager/src/components/ActionMenu/ActionMenu.tsx
> +  id?: string;
Optional because I'm just using it for react keys and test-id's.

2024-01-04 03:55 UTC, jaalah-akamai commented on packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
> +      {...rest}
Added to pass data-attributes to button component.

2024-01-04 17:15 UTC, jdamore-linode commented
> Need to update unit tests and some broken E2E tests

For the e2e tests, I'm thinking it may be a good idea to override the Chai `enabled` and `disabled` assertions to account for `aria-disabled` so that we don't have to explicitly check for it in each test.

Adding this to line 26 of `cypress/support/e2e.ts` seems to resolve a lot of the failures, but I'm seeing TypeScript issues reported in my editor -- I'm guessing Cypress is using a different version of Chai than what's in our `node_modules` dir but I didn't investigate:

```typescript
chai.use(function (chai, utils) {
  utils.overwriteProperty(chai.Assertion.prototype, 'disabled', function() {
    return function() {
      const obj = utils.flag(this, 'object');
      const isDisabled = Cypress.$(obj).is(':disabled');
      const isAriaDisabled = (Cypress.$(obj).attr('aria-disabled') === 'true');

      this.assert(
        isDisabled || isAriaDisabled,
        'expected #{this} to be disabled',
        'expected #{this} not to be disabled',
      );
    }
  });

  utils.overwriteProperty(chai.Assertion.prototype, 'enabled', function() {
    return function() {
      const obj = utils.flag(this, 'object');
      const isDisabled = Cypress.$(obj).is(':disabled');
      const isAriaDisabled = (Cypress.$(obj).attr('aria-disabled') === 'true');

      this.assert(
        !isDisabled && !isAriaDisabled,
        'expected #{this} to be disabled',
        'expected #{this} not to be disabled',
      );
    }
  });
});
```

(Something similar may be possible for the unit tests too)

2024-01-04 17:21 UTC, jdamore-linode requested changes
This is really cool, nice work @jaalah-akamai! Observing one issue but other than that this is looking good to me. Tested keyboard navigation, tested VoiceOver on Chrome, but haven't tested mobile yet.

Wrote the comment below earlier, but later confirmed it's an issue -- can be reproduced on the OAuth page (and probably other places):

1. Navigate to `/profile/clients`
2. Click "Edit" next to any of the listed OAuth clients
3. Observe that the "Save Changes" button visually appears disabled, has the `aria-disabled` attribute, etc.
4. Observe that clicking "Save Changes" submits the form even when the button appears disabled

2024-01-04 19:10 UTC, jaalah-akamai commented on packages/manager/src/components/Button/Button.tsx
> +        onClick={disabled ? undefined : rest.onClick}
Ahh yes that should do it - thanks @jdamore-linode

2024-01-05 14:46 UTC, abailly-akamai reviewed
Great PR! happy to see this coming. Left a few comments to improve a few things.

Also, something slightly bothers me about the nomenclature. We are using the `disabled?` prop to now describe a "only visually disabled" element. This creates a shift  in the way we are describing a button state and the way any test out there (jest, ci) is treating a `disabled` assertion. 

Tho I am not convinced myself, I would argue that we may want to rename `disabled` to what is really is (`ariaDisabled` or `visuallyDisabled`) so that it matches assertions and nomenclature in general.

2024-01-05 14:46 UTC, abailly-akamai commented on packages/manager/src/components/Button/Button.test.tsx
Can we actually add coverage for the accessibility enhancements this PR brings up?

`loading` => disabled attribute, tabIndex -1, no click even handler
`disabled` => aria-disabled, tanIndex 0, click handlers
`tooltipText` => tooltip content on hover

2024-01-05 14:46 UTC, abailly-akamai commented on packages/manager/src/components/Button/Button.tsx
> +        onClick={disabled ? (e) => e.preventDefault() : rest.onClick}
This would have to be confirmed, but i think we want to handle `onKeyPress` similarly.

This may add another level of accessibility compliance.

2024-01-05 14:46 UTC, abailly-akamai commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
> +        <Typography component="div" style={{ fontSize: '0.875rem' }}>
Might as well use `sx` here instead of style since we're touching it.

2024-01-05 14:46 UTC, abailly-akamai commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
>            <ul style={{ margin: '5px 0px 0px', paddingLeft: '15px' }}>
nitpick: unrelated to PR but this should use our JSX `<List>` and `<ListItem>`

2024-01-05 14:55 UTC, jdamore-linode commented on packages/manager/src/components/Button/Button.tsx
> +        onClick={disabled ? (e) => e.preventDefault() : rest.onClick}
Just double checked this and wasn't able to trigger a focused `disabled` button using keyboard 👍 (a test to make sure this stays true would be really good though)

2024-01-05 15:00 UTC, jdamore-linode approved these changes
Nice! Approved pending the last few e2e test fixes.

Also circled back and confirmed the tooltip works as expected on mobile. I had to press and hold on iOS to get the tooltip to appear which took me a second to figure out, curious if others have seen this interaction before.

The last few e2e failures are all in `resize-linode.spec.ts`, and can be fixed by doing a find and replace of `cy.get('[data-qa-resize="true"]').click();` with `cy.get('[data-qa-resize="true"]').should('be.enabled').click();` (there are 4 or 5 instances). Before, Cypress would implicitly wait for a button to become enabled before clicking it, but this isn't true anymore with these changes so we just have to explicitly add the `enabled` assertion.

2024-01-05 15:15 UTC, abailly-akamai commented on packages/manager/src/components/Button/Button.tsx
> +        onClick={disabled ? (e) => e.preventDefault() : rest.onClick}
It may be an edge case when someone adds a custom onKeyDown handler, but worth covering IMO

2024-01-05 15:29 UTC, jdamore-linode commented on packages/manager/src/components/Button/Button.tsx
> +        onClick={disabled ? (e) => e.preventDefault() : rest.onClick}
Ohh, I misunderstood -- I totally see what you're saying now. Great catch and agreed

2024-01-05 16:35 UTC, jaalah-akamai commented
Thanks for the reviews @jdamore-linode and @abailly-akamai 
| Tests |
| ----|
|<img width="658" alt="Screenshot 2024-01-05 at 11 19 13 AM" src="https://github.com/linode/manager/assets/125309814/814843b9-b9c1-4d4d-bff8-f8e342a6577f">|
|<img width="570" alt="Screenshot 2024-01-05 at 11 33 17 AM" src="https://github.com/linode/manager/assets/125309814/a0f82b37-b296-49dc-9119-5798870d21e8">|

2024-01-05 16:37 UTC, jaalah-akamai commented
> Tho I am not convinced myself, I would argue that we may want to rename disabled to what is really is (ariaDisabled or visuallyDisabled) so that it matches assertions and nomenclature in general.

Yea this is a fair point... let me see what I can do.

2024-01-05 16:41 UTC, abailly-akamai approved these changes
> Tho I am not convinced myself, I would argue that we may want to rename disabled to what is really is (ariaDisabled or visuallyDisabled) so that it matches assertions and nomenclature in general.
> 
> Yea this is a fair point... let me see what I can do.
> 
> Edit: This would require a significant amount of changes if we went down this route - whereas keeping it as disabled we keep the intent of what the developer wants to do... which is to make it disabled.

Yeah that's fine. It's not something i feel strong about.

2024-01-05 17:21 UTC, jdamore-linode commented on packages/manager/src/components/Button/Button.tsx
> +        data-testid="Button"
I think this may be the cause of the unit test failures -- I'm guessing we have instances of `<Button />` throughout the app with their own `data-testid`s that this is overriding

2024-01-05 17:21 UTC, jaalah-akamai commented on packages/manager/src/components/Button/Button.tsx
> +        data-testid="Button"
Haha yea

2024-01-05 18:10 UTC, merged