upcoming: [M3-7294] - AGLB Full Create Flow - Add Rule Support to Routes
linode/manager pull request #10035
Opened 2024-01-05 15:35 UTC by bnussman-akamai

## Description 📝

- Adds rule support for AGLB routes in the full create flow

## Changes  🔄

> [!warning]
> Work in progress

## Preview 📷

> [!warning]
> Work in progress

## How to test 🧪

> [!warning]
> Work in progress

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-01-17 19:24 UTC, SanPilot requested changes
Noticing some UI bugs but otherwise this PR expertly implements some really complex functionality. Extremely impressive work 🎉

2024-01-17 19:24 UTC, SanPilot commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
Feeling kinda ambivalent about the Execution order labels. Mixing "First"/"Last" with the numbers in between seems less intuitive than "First", "Second", "Third", etc.

Although doing so might involve some complicated implementation/long arrays so as a middle ground, I propose the less formal "1st", "2nd", "3rd", "4th".

2024-01-17 19:24 UTC, SanPilot commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
>  export const LoadBalancerCreate = () => {
Clicking "Review Load Balancer" is not doing anything for me (nor showing an error as far as I can see). Getting the following response from API (400 Status Code):

```
{
    "errors": [
        {
            "reason": "Control Plane Error when creating service target: {\"timestamp\":\"2024-01-17T19:11:55.272237695Z\",\"refId\":\"60febb8a-e992-4431-a09a-3d535e725fac\",\"message\":\"Validation errors\",\"errors\":[\"healthCheckPath: must not be blank\"]}"
        }
    ]
}
```

This is despite putting in a value in the Health Check Path field of the service target (which is labelled as optional):


https://github.com/linode/manager/assets/11482841/606eb2ee-ef0a-46e1-aaf8-4ee46b37114e

2024-01-17 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/RuleDrawer.tsx
> +                />
Good catch. This will be fixable when the POST payload shape changes.

2024-01-17 19:35 UTC, bnussman-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx
>  export const LoadBalancerCreate = () => {
This whole flow is still very much a work in progress. Full creation should't work yet.

2024-01-17 19:36 UTC, bnussman-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx
John had similar feedback. I will bring this idea to UX.

2024-01-29 20:16 UTC, jaalah-akamai commented
✅ Payload looks good
✅ Can create, edit, and delete routes
❓ Re-arranging seems off, but action buttons work

https://github.com/linode/manager/assets/125309814/16800d42-b08b-4ae0-9e87-e3f8cb337f28

2024-01-29 20:17 UTC, jaalah-akamai approved these changes

2024-01-29 20:20 UTC, jaalah-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
> +        <Box maxWidth="99%">
What's this for?

2024-01-29 20:23 UTC, bnussman-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
> +        <Box maxWidth="99%">
When I remove this, the rules tables causes a scrollbar to show that I could not figure out how to get rid of. 😰

2024-01-29 21:05 UTC, jaalah-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
> +        <Box maxWidth="99%">
Good ole Safari

2024-01-29 22:01 UTC, cpathipa commented
@bnussman Couple files are conflicting with develop.

2024-01-29 22:06 UTC, cpathipa commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/Routes.tsx
> +        <Box maxWidth="99%">
@bnussman I think the `CollapsibleTable` component's `component={Paper}` prop is what's causing the horizontal scrollbar issue. I did quick test by removing it and didn't notice any visual differences. It is being used in the VPC subnets table and the Route table. I would recommend removing this in the current PR and addressing it in a separate PR. We can handle this either by lifting `component={Paper}` with custom styles to replace it or by finding another suitable component. This way, we can avoid unwanted scrollbars that might occur accidentally with the usage of `CollapsibleTable`.

2024-01-29 22:15 UTC, mjac0bs reviewed
✅  I can create, edit, and delete an ACLB Route rule in the create flow.

Is it a known issue that I can't edit a **route** label while it has at least one rule? I think that's what I was seeing here, without any user feedback:

https://github.com/linode/manager/assets/114685994/2fd7e397-7f90-47d1-a35d-6d02715c7843

2024-01-29 22:51 UTC, hkhalil-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerCreate/RuleDrawer.tsx
> +                    }
@bnussman can I imply this is expected for now given it was marked as resolved?

2024-01-29 22:53 UTC, hkhalil-akamai approved these changes
Nice work -- let's get this in develop! Approved pending @cpathipa's [recommendation](https://github.com/linode/manager/pull/10035#discussion_r1470283175) and merge conflicts.

2024-01-30 01:12 UTC, merged