upcoming: [M3-7425] - OBJ MultiCluster - Add regions field in Create Access Key Drawer
linode/manager pull request #10034
Opened 2024-01-05 05:02 UTC by cpathipa

## Description 📝
Add's regions field in Create Access Key Drawer.

| Before  | After   |
| ------- | ------- |
| ![image](https://github.com/linode/manager/assets/119517080/9e266ce0-a347-4244-b2f2-3917fcd6f038)| ![image](https://github.com/linode/manager/assets/119517080/6dbaf9aa-d188-46aa-aa0a-91e715baca39)|

## How to test 🧪

### Prerequisites
(How to setup test environment)
- Turn on feature flag 
- Navigate to http://localhost:3000/object-storage/access-keys

### Verification steps 
(How to verify changes)

**Turn off feature flag and verify** 
- Create Access Key
- Update Access Key
- Remove Access key
- Make sure no regressions in Creating Access key flow.

**Turn on feature flag and verify** 
- Create Access Key Flow
- Access Key Drawer in Accordance with Mockups
- Ensure the Regions Multi-Select Field Is Functioning as Expected.

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-01-11 17:33 UTC, jdamore-linode commented
@cpathipa Just pushed some quick Cypress test fixes by mocking the OBJ feature flag to be disabled -- we'll add new tests to cover the on state soon. The remaining VPC test failures can be fixed by merging in the latest changes from `develop`

2024-01-16 15:13 UTC, jdamore-linode reviewed
Great work @cpathipa! Noticed a couple styling issues and issues with the permissions table. Happy to take another look soon!

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
> +                setShowBucketsTable(true);
Similarly, if you select a region that does not have any buckets, and if the table is not already present, the table does not appear:

<img width="690" alt="Screenshot 2024-01-16 at 9 57 38 AM" src="https://github.com/linode/manager/assets/97627410/fa26e2d3-bdb4-4b69-b1d6-7d03bc94a26b">

I think this conditional rendering of the table is really confusing from a UX perspective. Can we always show the table, and just include a message in the table if no regions are selected or if the selected region(s) have no buckets?

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
Interestingly, if I update the mocks so that there are no OBJ buckets on my account, the drawer renders with a narrow layout:

<img width="469" alt="Screenshot 2024-01-16 at 10 03 44 AM" src="https://github.com/linode/manager/assets/97627410/c97d6f06-e132-44e3-9da0-695f77156f89">

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
When the table is being rendered without any data shown, the margins on the column headings ("Read/Write" specifically) get a little wonky. Not clear if the table is supposed to be shown in these cases, so feel free to disregard if not

<img width="652" alt="Screenshot 2024-01-16 at 10 05 16 AM" src="https://github.com/linode/manager/assets/97627410/c9cf4efa-4d9f-4de5-b31a-e1b017b0302f">

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
> +                (region) => `s3 Endpoint: ${region.id}: ${region.s3_endpoint}`
```suggestion
                (region) => `S3 Endpoint: ${region.id}: ${region.s3_endpoint}`
```

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
> +                  (region) => `s3 Endpoint: ${region.id}: ${region.s3_endpoint}`
```suggestion
                  (region) => `S3 Endpoint: ${region.id}: ${region.s3_endpoint}`
```

2024-01-16 15:13 UTC, jdamore-linode commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAll.tsx
The styling of this component looks a little out of place on the dark theme:

<img width="598" alt="Screenshot 2024-01-16 at 10 08 10 AM" src="https://github.com/linode/manager/assets/97627410/5b074d89-8ccc-44c1-9265-e502e1cc3f60">

2024-01-16 15:16 UTC, abailly-akamai requested changes
@cpathipa - ⚠️ The region multiselect implementation should be broken down in a separate PR (new component touching and extending a core one). this will allow to:

- prevent potential regressions with existing RegionSelect styles
- be tested properly. You are adding an untested component and untested utils!
- add a story for it (no story here)
- help your reviewers with smaller change sets

2024-01-16 17:29 UTC, cpathipa commented
> @cpathipa - ⚠️ The region multiselect implementation should be broken down in a separate PR (new component touching and extending a core one). this will allow to:
> 
> * prevent potential regressions with existing RegionSelect styles
> * be tested properly. You are adding an untested component and untested utils!
> * add a story for it (no story here)
> * help your reviewers with smaller change sets

@abailly-akamai I agree. I will decouple the Region multi-select into a separate PR.

2024-01-16 22:27 UTC, dwiley-akamai commented on packages/validation/src/objectStorageKeys.schema.ts
> +});
The API spec says `regions` can be completely omitted from the request (p. 21). If that's the case, I don't think we need a temporary schema here, we can just add `regions` to `createObjectStorageKeySchema` -- I have a PR up which does it: https://github.com/linode/manager/pull/10063/files

I do see that the UX mocks don't seem to be in alignment with `regions` not being required though 🤔 If we're ignoring that aspect for UX purposes, it might be better to enforce it via custom logic in `OMC_AccessKeyDrawer.tsx` as opposed to in the schema (to keep the schema aligned with what the API accepts).

2024-01-17 16:25 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
> +                (region) => `s3 Endpoint: ${region.id}: ${region.s3_endpoint}`
Addressed in [be4d543](https://github.com/linode/manager/pull/10034/commits/be4d543d6f57eefd2e13cc5c5145587b35a6b018)

2024-01-17 16:26 UTC, cpathipa commented on packages/manager/src/components/RegionSelect/RegionsMultiSelect.tsx
Good catch, addressed in [be4d543](https://github.com/linode/manager/pull/10034/commits/be4d543d6f57eefd2e13cc5c5145587b35a6b018)

2024-01-18 01:14 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
We have removed the conditional rendering of the table (UX approved), so there won't be any layout changes.
749189d

2024-01-18 01:16 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
> +                setShowBucketsTable(true);
Good call @jdamore-linode! We have UX approval to always display the table, along with a relevant message in case of no data. [749189d](https://github.com/linode/manager/pull/10034/commits/749189df3a23ef33a4466a24c5c67a3d3a0a0f1d)

2024-01-18 01:17 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
Addressed in [749189d](https://github.com/linode/manager/pull/10034/commits/749189df3a23ef33a4466a24c5c67a3d3a0a0f1d)

2024-01-18 03:51 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/CopyAll.tsx
Addressed the styling issues in 749189d. However, the copy icon color is inconsistent due to the CopyableTextField component. To reduce regression testing efforts, a separate [PR](https://github.com/linode/manager/pull/10073) has been created to address this issue.

2024-01-18 03:52 UTC, cpathipa commented on packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
> +                  (region) => `s3 Endpoint: ${region.id}: ${region.s3_endpoint}`
Addressed in [749189d](https://github.com/linode/manager/pull/10034/commits/749189df3a23ef33a4466a24c5c67a3d3a0a0f1d)

2024-01-18 16:18 UTC, cpathipa commented on packages/validation/src/objectStorageKeys.schema.ts
> +});
@dwiley-akamai Yeah, you're right. We could rely on createObjectStorageKeySchema instead of the temporary schema. I'll pull the change once your PR merges.

2024-01-19 15:04 UTC, jdamore-linode approved these changes
Thanks @cpathipa!

I agree with @abailly-akamai's points about the new `RegionsMultiSelect` component, so approved pending that other work (storybook docs, unit tests, etc.) being done either here or in a separate PR

Edit: Just saw the new region select PR! Thanks again @cpathipa!

2024-01-22 21:54 UTC, cpathipa commented on packages/manager/src/components/RegionSelect/RegionsMultiSelect.tsx
> +};
This is taken care in Multi Select Regions [PR](https://github.com/linode/manager/pull/10084/commits/135a8ddb09e6da7b9615213459664a479d7ec595#diff-164f68a99c70aa2b0e21bac41921d21537b25aeaf84ed3fb2bf7bb2ac442925a)

2024-01-23 14:50 UTC, abailly-akamai commented
@cpathipa what's your plan here? wait for https://github.com/linode/manager/pull/10084 to be merged and update this one?

2024-01-23 17:25 UTC, cpathipa commented
@abailly-akamai Yes Please hold on the review until this https://github.com/linode/manager/pull/10084 PR merges, waiting for one more approval.

2024-01-23 21:48 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
> +          <TableCell data-qa-perm-rw>Read/Write</TableCell>
@jdamore-linode applied the fix to Read/Write column 

![image](https://github.com/linode/manager/assets/119517080/0cbff904-8ece-4b64-ace8-c5e7c45fd428)

2024-01-23 21:49 UTC, cpathipa commented
PR - Ready for re review.

2024-01-24 14:51 UTC, abailly-akamai approved these changes
Looks good, thanks for handling all those changes!

Couple things i wanted to point out. The PR description mentions testing editing and deleting access keys but it does not look like MSW is configured to handle that? Getting 404 for PUT and DELETE

![Screenshot 2024-01-24 at 09 34 41](https://github.com/linode/manager/assets/130582365/b5afe0b0-efdb-4a85-8312-1a13aad277fc)
![Screenshot 2024-01-24 at 09 35 06](https://github.com/linode/manager/assets/130582365/9f5b167c-f216-4491-930a-86decc0a1b0b)

I think the UX for the multiselect is really awkward (not an issue with your implementation, just the way the component behaves)

It's kinda weird to have the permission table being pushed down as you are adding regions. I'll bring this to the cafe as well (I already see an item for it)
<video src="https://github.com/linode/manager/assets/130582365/fd55f201-8152-476c-be77-ebef59818f5d" />

2024-01-24 15:29 UTC, cpathipa commented
@abailly-akamai Thank you. MSW for the update and delete actions will be handled as part of ticket M3-7555. I agree on UX part. I will also circle back with UX.

2024-01-24 16:59 UTC, dwiley-akamai reviewed
Not sure if there's a follow-up PR planned that would address some of these points but just wanted to note them in case there isn't --

The drawer title for the "Edit Access Key" drawer needs updating:

<details>
<summary>Still includes "Label" at the end</summary>

![Screenshot 2024-01-24 at 11 28 26 AM](https://github.com/linode/manager/assets/114682940/aab87f6a-7e55-48db-b846-0562bfc42488)
</details>

If you go into the Edit drawer and add regions, the "Save Changes" button stays disabled:

<details>
<summary>"Save Changes" button remains disabled despite regions being added</summary>

https://github.com/linode/manager/assets/114682940/794f915d-99bf-4827-92c8-f8d034da222b
</details>

Some of the validation in the "Create Access Key" drawer feels odd. I think we've been discussing real-time validation within the app but we're ending up with a situation where, for example, you enter a label, click to the side of that field, and an error pops up for the "Regions" field. (it also stays once you add regions)

If someone adds all regions when creating a key, the Secret Key modal requires scrolling before you can see your Access Key and Secret Key. I wonder if there's a concern those items are too easy for users to overlook in that scenario.

2024-01-24 16:59 UTC, dwiley-akamai commented on packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
> +  const isObjMultiClusterFlagEnabled = isFeatureEnabled(
I would rename this to something like "isObjMultiClusterEnabled" since it isn't determined solely by the flag (ditto to the other instances of it used elsewhere)

2024-01-24 16:59 UTC, dwiley-akamai commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/BucketPermissionsTable.tsx
> +        {!bucket_access?.length ? (
Could we go with `bucket_access.length === 0` here? 

Don't L61-63 cover the case where `bucket_access` could be null? (so no need to safe access this?)

2024-01-24 17:46 UTC, cpathipa commented
@dwiley-akamai 

- Copy updated are in the radar and we have place holder ticket to cover it M3-7694. Still waiting for the other final copy updates.
- I will put a separate PR to fix the` save button` disabled and making regions field real time validation (M3-7696).
- I will circle back with UX on concern of Secret Key modal (M3-7697).

2024-01-24 17:52 UTC, dwiley-akamai approved these changes

2024-01-25 11:19 UTC, merged