test: [M3-7482] - Add cypress tests to add users on "Users & Grants" page
linode/manager pull request #10065
Opened 2024-01-15 18:36 UTC by cliu-akamai

## Description 📝
Add regression tests for adding users on `Users & Grants` page.

## Major Changes 🔄
- Add regression tests to add users on `Users & Grants` page.

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/account/user-permissions.spec.ts"
```

2024-01-16 15:08 UTC, bnussman-akamai approved these changes

2024-01-16 16:22 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +    mockGetUser(mockUser).as('getUser');
```suggestion
    mockGetUser(mockUser);
```
It doesn't look like we're `wait`ing on this anywhere.

2024-01-16 16:24 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +    mockGetUser(mockUser).as('getUser');
```suggestion
    mockGetUser(mockUser);
```
It doesn't look like we're `wait`ing on this anywhere.

2024-01-16 16:43 UTC, jdamore-linode requested changes
Nice work Cassie! I think we'll want to replace the intercept util with a mock util, and I made a couple other really minor suggestions, but otherwise this is looking really good!

2024-01-16 16:43 UTC, jdamore-linode commented on packages/manager/cypress/support/intercepts/account.ts
> +
I think we need to replace this with a mock util, e.g. `mockAddUser`, which mocks a response containing the created user object.

Because this is only intercepting the request, this test actually creates new users when it runs. We want to make sure this response is mocked so we don't leave behind any leftover users here -- your assertions on the request body `restricted` property should continue to work 👍

2024-01-16 16:43 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +import { randomHex, randomLabel } from 'support/util/random';
```suggestion
import { randomLabel } from 'support/util/random';
```

2024-01-16 16:43 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +  it('can add full-access users with no redirect occurs', () => {
```suggestion
  it('can add users with full access', () => {
```
No need to mention the redirect in the test title, similar case for the test below. Only suggesting we change it because if we ever change the redirect behavior, we'll have to change the test titles too and that'll mess up our metrics for the test (test length, flakiness, etc.)

2024-01-16 16:43 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +  it('can add non full-access users with redirecting to the new user\'s "User Permission" page', () => {
```suggestion
  it('can add users with limited access', () => {
```
(Similar to above)

2024-01-16 17:35 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +  it('can add non full-access users with redirecting to the new user\'s "User Permission" page', () => {
@mjac0bs Thanks! `restricted` was what I was going for but for some reason `limited` came to mind and my brain was like "yeah, sounds right 👍😎". Updated my suggestion

2024-01-18 21:34 UTC, mjac0bs approved these changes
Thanks for the changes; looks good to me! 🚢

2024-01-18 22:05 UTC, jdamore-linode approved these changes
Looks great, thanks @cliu-akamai!

2024-01-18 22:55 UTC, merged