upcoming: [M3-7610] - Placement Groups Detail
linode/manager pull request #10096
Opened 2024-01-22 22:13 UTC by abailly-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps 
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-01-23 17:22 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
> +            onOpenEdit: () => setIsEditingLabel(true),
This piece of state is necessary to keep track of the label to be edited (the label itself) and the label to be displayed (label + readable `affinity_type` label)

2024-01-23 19:50 UTC, hkhalil-akamai requested changes
Looking good, tested all functionality. Left one technical suggestion.

2024-01-23 19:50 UTC, hkhalil-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
> +              : `${label} (${affinityLabel})`,
Suggestion: instead of storing `isEditingLabel` in this component, the `editableTextTitle` prop can accept an optional function (i.e., it would have type `editableTextTitle: string | (isEditinglabel: boolean) => string`), which avoids duplicating state that is already tracked in the `EditableText` component as `isEditing`.

```suggestion
            editableTextTitle: (isEditingLabel) => isEditingLabel
              ? label
              : `${label} (${affinityLabel})`,
```

2024-01-23 20:36 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
> +            {label} ({affinityLabel}) &nbsp;
I added a margin instead. it's to handle the spacing in case of the "Non-compliant" label. We don't want that spacing on the left of the "Non-compliant" typography cause when/if it wraps underneath it displays poorly

2024-01-23 20:39 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
> +              : `${label} (${affinityLabel})`,
Yeah that's fair, though the solution above isn't too much of an improvement because of how the initial state of this component is managed in the first place.

I went the route of adding a new prop instead which bypasses relying on state all together. See https://github.com/linode/manager/pull/10096/commits/31c2f92e4d05dde774b66d749ef0aff55ae98b05

2024-01-24 14:22 UTC, abailly-akamai commented on packages/manager/src/components/EditableText/EditableText.tsx
> +          aria-label="Cancel"
improving accessibility while I am here. We shouldn't have buttons with only icons as children without an aria label

2024-01-24 15:51 UTC, jdamore-linode commented on packages/manager/src/components/EditableText/EditableText.tsx
> +      title={`${text} ${textSuffix || ''}`}
It looks like the space character between `text` and `textSuffix` is causing the DBaaS test failures.

```suggestion
      title={`${text}${textSuffix ? ` ${textSuffix}` : ''}`}
```
Confirmed that this gets the tests passing, even though the nested string literal is kinda nasty

2024-01-24 16:04 UTC, abailly-akamai commented on packages/manager/src/components/EditableText/EditableText.tsx
> +      title={`${text} ${textSuffix || ''}`}
Oh good catch actually we don't want a whitespace at all. (should be handled in the `textSuffix` as needed by the developer). Fixed in https://github.com/linode/manager/pull/10096/commits/f1e65fc052908b711ad1f3c1ae7b43e2133eac84

2024-01-25 18:30 UTC, carrillo-erik approved these changes

2024-01-25 18:33 UTC, carrillo-erik commented on packages/manager/src/components/EditableText/EditableText.tsx
> +          aria-label="Cancel"
Nice catch, I'll make sure to keep an eye for this type of detail.

2024-01-26 16:18 UTC, hkhalil-akamai approved these changes
Thanks for resolving my concerns with the breadcrumb state. Re-tested and looks good; approved pending consideration of some minor changes.

2024-01-26 16:18 UTC, hkhalil-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
> +        breadcrumbProps={{
To remove the hyphen:
![image](https://github.com/linode/manager/assets/122488130/65af46f2-23cc-419f-9c4c-111de9e96b16)

```suggestion
        breadcrumbProps={{
          crumbOverrides: [
            {
              label: 'Placement Groups',
              position: 1,
            },
          ],
```

2024-01-26 17:18 UTC, abailly-akamai commented on packages/manager/src/components/EditableText/EditableText.tsx
> +      title={`${text}${textSuffix ? textSuffix : ''}`}
sure thing. done!

2024-01-26 17:19 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
> +        breadcrumbProps={{
ah yes good call - done as well!

2024-01-26 17:39 UTC, merged