change: [M3-7660] - Cleanup files to use `profile` to get `user_type`
linode/manager pull request #10102
Opened 2024-01-24 03:04 UTC by jaalah-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps 
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-01-24 14:22 UTC, bnussman-akamai requested changes

2024-01-24 14:22 UTC, bnussman-akamai commented on packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
> +        return res(ctx.json(profileFactory.build({ user_type: 'proxy' })));
I believe this should be reverted. We want to make sure we respond with `accountUserFactory` data for the `*/account/users/*` endpoint

2024-01-26 15:42 UTC, jaalah-akamai commented on packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
> +        return res(ctx.json(profileFactory.build({ user_type: 'proxy' })));
Actually I had to update the endpoint, but good catch

2024-01-26 17:19 UTC, bnussman-akamai commented on packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx
> +      return res(ctx.json(profileFactory.build({ user_type: 'parent' })));
Same thing here!

2024-01-29 20:24 UTC, cpathipa commented on packages/manager/src/features/Account/AccountLanding.tsx
> +        isProxyUser={profile?.user_type === 'proxy'}
nitpicky :Can we move the check `profile?.user_type === 'proxy'` to a constant and reference it, since we are using it in couple of places?

2024-01-29 20:24 UTC, cpathipa commented on packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
> +  const isProxyUser = profile?.user_type === 'proxy';
Looks like we have similar checks for user_type at the feature level. Any thoughts on having utility functions for user types? 

Something like this
`export const isParentUser = (profile) => profile?.user_type === 'parent';`
`export const isProxyUser = (profile) => profile?.user_type === 'proxy';`

2024-01-30 04:13 UTC, jaalah-akamai commented on packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
> +  const isProxyUser = profile?.user_type === 'proxy';
Moving it to a const was a good idea in that other file - I think we have too many utils and this is pretty clear as to what it's doing. I infer the type from the other user types if there were `child`

2024-01-30 16:33 UTC, bnussman-akamai requested changes
One more change and should be good to go

2024-01-30 16:33 UTC, bnussman-akamai commented on packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx
> +      rest.get('*/account/profile/*', (req, res, ctx) => {
```suggestion
      rest.get('*/profile', (req, res, ctx) => {
```

2024-01-30 17:04 UTC, jaalah-akamai commented
Weird that those don't cause tests to fail 🤔

2024-01-31 17:36 UTC, mjac0bs approved these changes
Pushed a fix for `ChildAccountList.test.tsx` that was *not* failing when I ran it locally, but was failing in CI. Unit tests are passing as of that last run.

LGTM now. Confirmed that the user menu and Switch Account button (in both menu and Account Landing) is only visible for the expected parent and proxy users. Confirmed that the Child Account Access PAT is visible only for parent users and that there are no regressions when creating a PAT.

2024-01-31 20:10 UTC, bnussman-akamai approved these changes

2024-02-01 14:36 UTC, jaalah-akamai commented
✅  Confirmed E2E tests pass with latest develop changes

2024-02-01 14:36 UTC, merged