upcoming: [M3-7693] - Rename `Akamai Global Load Balancer` to `Akamai Cloud Load Balancer`
linode/manager pull request #10115
Opened 2024-01-26 17:11 UTC by bnussman-akamai

## Description 📝

- Goes all in on the `Akamai Global Load Balancer` to `Akamai Cloud Load Balancer` rename ✏️
- The only thing that shouldn't change as part of this PR is API URLs and Docs links URLs to prevent breaking dev for internal testers. We will do a separate PR for this change.
- Yes, I even created new feature flags 🚩 and deprecated the old ones. This probably is very extra of me, but I figured now would just be a good time to get it over with

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-01-26 at 12 07 09 PM](https://github.com/linode/manager/assets/115251059/4d8abfd7-18dc-40d7-bd33-233267328d2d) | ![Screenshot 2024-01-26 at 12 06 48 PM](https://github.com/linode/manager/assets/115251059/cfca7460-e174-44e3-9d06-bbfd0773d0bf) |

## How to test 🧪

### Prerequisites
- You can test with the MSW **or** use `dev-test-aglb` with the dev API

### Verification steps 
- Verify you see  to `Akamai Cloud Load Balancer` instead of `Akamai Global Load Balancer` in the UI
- Look at the diff and check my find-and-replace work

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-01-26 21:35 UTC, hkhalil-akamai approved these changes
☁️

2024-01-29 19:46 UTC, jaalah-akamai approved these changes
☁️ 🚀

2024-01-29 19:57 UTC, cpathipa commented
@bnussman couple files are conflicting with dev branch.

2024-01-29 20:47 UTC, cpathipa requested changes
Should we also consider making the folder name aglb to aclb in this PR ? 

```
src/factories/aglb -->  src/factories/aclb
src/queries/aglb --> src/queries/aclb
api-v4/src/aglb --> api-v4/src/aclb 

```

2024-01-29 20:47 UTC, cpathipa commented on packages/manager/src/mocks/serverHandlers.ts
Should we consider renaming line [316](https://github.com/linode/manager/blob/17b9b750ae67cd27d83906396dd88de6d5f6fc7a/packages/manager/src/mocks/serverHandlers.ts#L316)

2024-01-29 20:50 UTC, bnussman-akamai commented
Going to save those changes until we switch the API endpoints over from `aglb` to `aclb` @cpathipa

2024-01-29 23:16 UTC, merged