test: [M3-7698] - Add test to check proxy user disabled username/email field
linode/manager pull request #10139
Opened 2024-02-01 18:14 UTC by cliu-akamai

## Description 📝
Add regression tests for checking proxy user disabled username/email field

## Major Changes 🔄
- Add regression tests to check proxy user disabled username/email field
## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/account/change-username.spec.ts"
```

2024-02-01 18:48 UTC, jdamore-linode reviewed
Nice work @cliu-akamai!

A couple suggestions:

- In addition to confirming the buttons are disabled, we also want to confirm that a tooltip appears explaining why the user can't update the username/email:
  <img width="223" alt="Screenshot 2024-02-01 at 1 39 18 PM" src="https://github.com/linode/manager/assets/97627410/e7d5ac0b-df02-437c-968f-f2bd2ac85ec2">
  This is pretty easy to do -- you just have to click the button and then use our new [tooltip UI helper](https://github.com/linode/manager/blob/develop/packages/manager/cypress/support/ui/tooltip.ts#L8):
  ```typescript
  // Click the button first, then confirm the tooltip is shown:
  ui.tooltip.findByText('This account type cannot update this field.').should('be.visible');
  ```
  (We use this in `billing/restricted-user-billing.spec.ts` if you want to see a working example)

- Since this page is under `/profile/display`, I'm not sure we should put this test under `user-permissions.spec.ts`. If it isn't too much work, maybe this would make more sense if it were moved to the `change-username.spec.ts` file? (Even that doesn't seem like a perfect fit)

2024-02-01 20:37 UTC, jdamore-linode approved these changes
Thanks @cliu-akamai! The only other thing is the missing changeset (you can run `yarn changeset` to generate and commit one), but approving this in the meantime. Nice work!

2024-02-01 22:39 UTC, mjac0bs requested changes
Thanks, Cassie! I left some thoughts in comments.

2024-02-01 22:39 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/change-username.spec.ts
> +    });
```suggestion
    const mockRestrictedProxyProfile = profileFactory.build({
      username: 'restricted-proxy-user',
      user_type: 'proxy',
      restricted: true
    });
```

I don't think we need to mock the account users endpoint here at all, nor grants. We [disable the buttons and display the tooltips](https://github.com/linode/manager/blob/develop/packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx#L107-L114) based on whether the user is restricted or a proxy user. We can use `restricted` and `user_type` from `*/profile` for that.

2024-02-01 22:39 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/change-username.spec.ts
> +  it('disables username/email fields for proxy user', () => {
If we want to cover all test cases here, it would be good to test the following:

- disables username and email fields for restricted proxy user (what we currently have)
- disables username and email fields for unrestricted proxy user (`restricted: false` in `*/profile`)
- disables username and email fields for a regular restricted user (`user_type: null` and `restricted: true` in `*/profile`)

I also wonder a little about the usefulness of some [unit](https://github.com/linode/manager/pull/10103/files#diff-b2a93542dd7bc1466f1b288b00d9fca34e0dfa33ee3f5fa478eba32bd2c4c05c) and Cypress test overlap. We're testing some of the same things. At what point does duplication become detrimental? (That's more of a larger question - cc @jdamore-linode.)

2024-02-06 18:55 UTC, cliu-akamai commented on packages/manager/cypress/e2e/core/account/change-username.spec.ts
> +  it('disables username/email fields for proxy user', () => {
@mjac0bs Not sure if it's a bug, the email field is not disabled for the regular restricted user.

2024-02-07 14:25 UTC, jaalah-akamai commented on packages/manager/cypress/e2e/core/account/change-username.spec.ts
> +  it('disables username/email fields for proxy user', () => {
Nope that's correct, restricted users can still edit email - just not proxy users

2024-02-07 20:44 UTC, mjac0bs approved these changes
Thanks for the updates. Looks good locally and in CI! The test failure in CI is the billing-contact.spec which is fixed in develop now, so you should be good to go here.

![image](https://github.com/linode/manager/assets/114685994/bf2d1022-5d1e-4d53-a9e9-af51ac2af86f)

2024-02-08 17:18 UTC, merged