test: [M3-7497] - Add tests for child user verification banner
linode/manager pull request #10204
Opened 2024-02-16 21:03 UTC by cliu-akamai

## Description 📝
Add regression tests for checking child user verification banner

## Major Changes 🔄
- Add regression tests to check child user verification banner

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/account/user-verification-banner.spec.ts"
```

2024-02-17 02:18 UTC, jaalah-akamai requested changes
@cliu-akamai I think we need one more test to ensure that the banner shows when we have security questions but not a phone number. Otherwise, this is looking good.

2024-02-21 15:15 UTC, mjac0bs reviewed
Other than Jaalah's ask, we'll also need a changeset before this is good to go.

2024-02-28 17:10 UTC, carrillo-erik commented
@cliu-akamai I was able to run this locally and after running the tests I did not see the test failing. I re-started the end-to-end test in the Jenkins UI and hopefully that resolves the issue. Everything else looks good.

2024-02-28 17:10 UTC, carrillo-erik approved these changes

2024-03-01 15:48 UTC, mjac0bs approved these changes
Thanks for the changes! For completeness, we _could_ test if the banner appears with only questions defined. 

Confirmed this spec runs locally and tests: banner with only phone number defined, banner with neither phone number or question defined, and no banner when both phone number and questions are defined.

![Screenshot 2024-03-01 at 7 31 55 AM](https://github.com/linode/manager/assets/114685994/14033f04-4607-4b91-878c-b3e2fe8e6a8e)

Approving pending we clean up a few comments/test descriptions with typos or a slightly inaccurate description of the test. It would also be good to cover that final test.

I'm going to dismiss Jaalah's requested changes since his feedback has been addressed. Rerequesting your reviewers is another thing you can do in the future after addressing feedback - it's helpful for reviewers, especially when someone blocks changes on your PR.

2024-03-01 15:48 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
> +   * - Confirms that a banner is present the child users do not have a phone number or security questions.
```suggestion
   * - Confirms that a banner is present when child users do not have a phone number or security questions.
```

2024-03-01 15:48 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
> +   * - Confirms that a banner is present the child users set up security questions but not have a phone number.
```suggestion
   * - Confirms that a banner is present when child users set up security questions but not a phone number.
```

2024-03-01 15:48 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
> +  it('does not show up when a child user adds a phone number or set up security questions', () => {
```suggestion
  it('does not show up when a child user adds a phone number and sets up security questions', () => {
```
Phone number *and* questions need to be set up in order for the banner to go away. We're testing this correctly! Description is just inaccurate.

2024-03-01 15:48 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
> +   * - Confirms that a banner is not shown when the child user sets up security questions.
```suggestion
   * - Confirms that a banner is not shown when the child user sets up both phone number and security questions.
```
Same comment as above.

2024-03-01 15:48 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts
> +    mockGetUsers([mockRestrictedProxyUser]).as('getUsers');
Nit: if we're not using the aliases in a `cy.wait` call, we could remove them here. (Related: I don't know if not waiting for feature flags could potentially cause any flakiness, which is why we generally do it, or if we are confident it will happen fast enough that it's not very necessary in the first place.)

```suggestion
    mockAppendFeatureFlags({
      parentChildAccountAccess: makeFeatureFlagData(true),
    });
    mockGetFeatureFlagClientstream();

    mockGetUsers([mockRestrictedProxyUser]);
```

2024-03-04 22:05 UTC, merged