chore: [M3-7803] - Clean up `Chip` component
linode/manager pull request #10223
Opened 2024-02-22 21:17 UTC by bnussman-akamai

## Description 📝

After talking about Chips in our cafe meeting, I looked at the Chip component and I couldn't un-see some of this code 😩😤

This PR simplifies our override of MUI's `<Chip />` and removes some _styled components_ that went way too far

## Preview 📷

> [!note]
> The goal of this PR is to clean up Chip related code, but **not change to how it looks** 👁️  

| Before | After |
|--------|-------|
|   ![Screenshot 2024-02-22 at 4 06 20 PM](https://github.com/linode/manager/assets/115251059/7bc17bc5-07ab-4e15-baf3-53b96a517887)     |  ![Screenshot 2024-02-22 at 4 06 48 PM](https://github.com/linode/manager/assets/115251059/5653ef45-606a-4edc-8a5a-17bea045e892)     |
|     ![Screenshot 2024-02-22 at 4 07 56 PM](https://github.com/linode/manager/assets/115251059/e51f5f4b-59c3-468b-8dd6-86292e7bb365)   |     ![Screenshot 2024-02-22 at 4 08 19 PM](https://github.com/linode/manager/assets/115251059/53c68b57-5956-46d8-915a-0aaaf6eab6e6)  |
| ![Screenshot 2024-02-22 at 4 09 56 PM](https://github.com/linode/manager/assets/115251059/030f791c-e1c1-4304-bf0e-0dbafb142375) | ![Screenshot 2024-02-22 at 4 09 33 PM](https://github.com/linode/manager/assets/115251059/91d1601b-5c64-40b0-9f95-b9359e5d9073)  |

## How to test 🧪

- Check out this PR
- Check that the Chip works as expected in Storybook
- Some examples of Chips you could check are:
  - Kubernetes HA chip (visible on Kubernetes landing and details page) 💻 
  - Database HA chip (visible on the Database landing page) 💾 
  - Verify the Linode Status on a Linode's details page looks and works as expected 🟢 (This use to be a chip, now it is just a status icon and text)
  - Check the VPC subnet IPs chip
- Check any other instance of `Chip` you can think of in Cloud Manager

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-02-22 22:12 UTC, jaalah-akamai approved these changes
Nice cleanup 🧹

2024-02-23 16:53 UTC, dwiley-akamai requested changes
The cleanup looks good mostly but I noticed a couple of instances where chips were adversely impacted

2024-02-23 16:53 UTC, dwiley-akamai commented on packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
> +            )}
The "Upgrade" chip was adversely impacted by some of the styling changes:

| Prod  | This branch |
| ------------- | ------------- |
| ![Screenshot 2024-02-23 at 11 42 11 AM](https://github.com/linode/manager/assets/114682940/28290c45-6bd7-495d-8840-d7700090dbca) | ![Screenshot 2024-02-23 at 11 42 07 AM](https://github.com/linode/manager/assets/114682940/63d5ec31-b93a-46de-abc6-7f3bde71b8e4) |

2024-02-23 16:53 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
>          )}
Similar to the K8S "Upgrade" chip situation:

| Prod | This branch |
| ------------- | ------------- |
| ![Screenshot 2024-02-23 at 11 45 59 AM](https://github.com/linode/manager/assets/114682940/a3b02645-4248-4065-91c2-9b55f5d8d2be) | ![Screenshot 2024-02-23 at 11 45 56 AM](https://github.com/linode/manager/assets/114682940/855fbace-89a2-4265-bce4-63b52870fefa) |

2024-02-23 17:16 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
> +            )}
Fixed in 63bb02e35a

 Thank you for catching this!

| Before Fix  | Fixed |
|--------|-------|
|   ![Screenshot 2024-02-23 at 12 12 27 PM](https://github.com/linode/manager/assets/115251059/072afbfc-742f-4570-a048-27d611c60eca)     |  ![Screenshot 2024-02-23 at 12 12 20 PM](https://github.com/linode/manager/assets/115251059/d170c391-3544-45ef-a8a7-30b4690f9a09)     |

2024-02-23 17:18 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
>          )}
Fixed in 63bb02e

2024-02-23 22:42 UTC, dwiley-akamai approved these changes

2024-02-26 13:33 UTC, merged