test: [M3-7500] - Add tests for Parent/Child Users & Grants page enhancements
linode/manager pull request #10240
Opened 2024-02-29 20:19 UTC by cliu-akamai

## Description 📝
Add regression tests to check enhancements in users landing page.

## Major Changes 🔄
- Add new tests to check the Users & Grants page.
- Move some existing test from user permission spec.

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/account/users-landing-page.spec.ts"
```

2024-03-01 16:17 UTC, mjac0bs requested changes
Cassie, thanks for tackling this and moving some of the tests around.

I realized our ticket for M3-7500 was not completely accurate, which means we'll need some changes for how we're checking the Child Account Access column. Comments inline, but let me know if you have any questions!

2024-03-01 16:17 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +    mockGetUser(mockUser).as('getUser');
```suggestion
    mockGetUser(mockUser);
```
Can we clean up the aliases whenever they're not used? - looks like we've got several unused throughout this file.

2024-03-01 16:17 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +   */
I think these last two tests (checking no "Profile" tab and checking Billing Access)  belong in `user-permissions.spec.ts`. Can we remove them from this test case and add them there?

2024-03-01 16:17 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +      });
Ending this test on L220 and testing the rest of it in user-permissions.spec.ts would help us keep our tests organized and scoped to their different files testing respective pages, so I would move it unless you see any issues with doing so!

2024-03-20 19:00 UTC, mjac0bs reviewed
I took another pass at this. Our mocks and test cases aren't reflective of what should happen in CM yet, and part of that was likely my misleading comment about the test cases we should cover. My review comments are an attempt to clarify where we have issues now and outline exactly what test cases we need. Lmk if I can help any further, or if something is still confusing -- happy to help.

2024-03-20 19:00 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +  it('shows "Child account access" column for restricted parent users child_account_access grant set to false', () => {
I think we could combine these into one test that just checks whether the Child Account Access column is present for restricted parent users, because currently we're not showing/hiding this based on the grant. We [display that column header for all parent users](https://github.com/linode/manager/blob/bd8054ffe337ed64097bb8e8bc4b2ebc77d6fd0c/packages/manager/src/features/Users/UsersLanding.tsx#L72-L74). (Though cc @jaalah-akamai - in case we want to hide the column header of the empty state table for restricted parent users without the grant?)

2024-03-20 19:00 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +  it('shows "Child account access" column for unrestricted parent users', () => {
```suggestion
  it('shows "Child account access" column for unrestricted parent users with restricted parent users who have the correct grant status', () => {
```

2024-03-20 19:00 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +  it('shows "Child account access" column for restricted parent users child_account_access grant set to false', () => {
```suggestion
  it('shows "Child account access" column for restricted parent users child_account_access grant set to true', () => {
```

2024-03-22 16:26 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/account/users-landing-page.spec.ts
> +  it('shows "Child account access" column for restricted parent users child_account_access grant set to false', () => {
See #10305.

2024-04-15 14:28 UTC, bnussman-akamai commented
Can we merge in develop / rebase this PR with develop? I think the Notistack/Snackbar changes might affect these tests

2024-04-15 22:26 UTC, mjac0bs reviewed
Thanks for addressing feedback. These test cases look accurate now and all are passing on my local runs! I didn't notice any snackbar impact, so I don't think the Notistack update affected things here, but @bnussman-akamai knows more about that than me.

Remaining changes:
- Can we add the test cases that were removed (because they didn't belong on the user landing test spec, since they were part of the user permissions page) to the `user-permissions.spec.ts`? I left my earlier comments that were about this unresolved and resolved everything else that has been addressed.
- Clean up for couple of minor comment updates for clarity/typo fixes

![Screenshot 2024-04-15 at 3 17 38 PM](https://github.com/linode/manager/assets/114685994/a731fec0-f83b-4b1b-a415-07882173ba1c)

2024-04-15 22:58 UTC, bnussman-akamai approved these changes

2024-04-24 21:02 UTC, mjac0bs approved these changes
I did some clean up in [21fe358](https://github.com/linode/manager/pull/10240/commits/21fe358081c6b34a3bed802770b3b3ff07d71b52) to further separate our testing in the Users & Grants landing and User Permissions pages, and avoid duplicating test coverage.

This looks good to me now; both tests passed locally, so as long as all looks good with CI, we can merge this.

2024-04-25 14:53 UTC, jdamore-linode approved these changes
Thanks @cliu-akamai and @mjac0bs!

2024-04-25 15:02 UTC, merged