upcoming: [M3-7798] - Update Buckets landing page to use regions instead of clusters.
linode/manager pull request #10244
Opened 2024-03-01 15:36 UTC by cpathipa

## Description 📝

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
No Visual changes
## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-03-04 18:59 UTC, mjac0bs reviewed
This was looking good from my testing, though typecheck is currently failing:

![image](https://github.com/linode/manager/assets/114685994/cc51311e-f6a1-4fa0-bcd9-7c06c8cfa428)


- [x] Validated buckets landing is fetched with regions instead of clusters (e.g. GET `object-storage/buckets/us-iad?page_size=500`)
Note: I'm not very familiar with the Object-MultiCluster feature or the mock data, but in addition to the GET requests for buckets that use regions, I was also seeing requests that include the cluster. Wasn't certain if that was still expected.
![Screenshot 2024-03-04 at 10 32 58 AM](https://github.com/linode/manager/assets/114685994/ca4917f2-3bf3-4365-88cc-9889d1b0ef37)

- [x] Validated bucket access is fetched (endpoint) with regions instead of clusters (e.g. GET `object-storage/buckets/us-iad/obj-bucket-1/access`)
- [x] Verified the bucket access PUT request has updated with region instead of clusters (e.g. PUT `object-storage/buckets/us-iad/obj-bucket-1/access`)
- [x] With the feature flag off, tested Buckets landing and Details CRUD flows for regressions

2024-03-04 18:59 UTC, mjac0bs commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
> +                )}
Can we move the conditional enabled check to the `to` prop rather than conditionally rendering the entire link component?

```suggestion
                  <StyledBucketLabelLink
                    to={`/object-storage/buckets/${isObjMultiClusterEnabled ? region : cluster }/${label}`}
                  >
                    {label}{' '}
                  </StyledBucketLabelLink>
```

2024-03-04 20:05 UTC, dwiley-akamai commented on packages/api-v4/src/object-storage/buckets.ts
Added a changeset for it

2024-03-05 20:31 UTC, carrillo-erik approved these changes

2024-03-12 16:32 UTC, cpathipa commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
> +              : clusterRegion?.label ?? cluster}
Good catch @DevDW addressed this in 53f796d
![image](https://github.com/linode/manager/assets/119517080/bb838673-98dd-4252-b699-aa61261a221b)

2024-03-12 17:01 UTC, cpathipa commented
> I was able to verify that the buckets are fetched with regions instead of clusters and that bucket access is fetched with regions endpoint instead of clusters. Functionality appears to be working as expected.
> 
> One minor visual regression I noticed is with the carat (^) symbol in the dropdown menu. In other places in the app, when the user engages with the dropdown the carat symbol is inverted and the color changes from gray to blue, denoting it's active. That is not the case with this PR, please take a look at the photos below.
> 
> #### Current Behavior:
> ![Screenshot 2024-03-05 at 12 26 00 PM](https://private-user-images.githubusercontent.com/119514965/310269131-df5a7e9e-70af-4c51-95d3-141367e96d10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjE1NTgsIm5iZiI6MTcxMDI2MTI1OCwicGF0aCI6Ii8xMTk1MTQ5NjUvMzEwMjY5MTMxLWRmNWE3ZTllLTcwYWYtNGM1MS05NWQzLTE0MTM2N2U5NmQxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDZiOTJjMDI0ZTg3YmNlMmU4ZDcxZGNlNWIzNTA3MzgyOWM4MDkxYTc1OWJkZmI3NGE1Y2FhZGRhYjE5YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QSM87GywEPhG32HQLg3I_gOcB2kPA8gqu-s_4ddXwGc)
> 
> #### Expected Behavior:
> ![Screenshot 2024-03-05 at 12 26 35 PM](https://private-user-images.githubusercontent.com/119514965/310269253-7a8d5e99-1d22-4d1c-912a-3b35be7810f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjE1NTgsIm5iZiI6MTcxMDI2MTI1OCwicGF0aCI6Ii8xMTk1MTQ5NjUvMzEwMjY5MjUzLTdhOGQ1ZTk5LTFkMjItNGQxYy05MTJhLTNiMzViZTc4MTBmMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDFmYzdlZGU3YjRhYjU3YTY5NTUwYmFlODIxNjVjYTc4ZTI5YzhmMGZhOTE1YThmZGRhN2I5NGU5YzYwNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1767-WsDB5hLtMI28Xyn2o91VHaQKhj4WQoU5ECjLUU)

@carrillo-erik Good find. It looks like the same behavior is present in production as well, not introduced by this PR. I'm not sure what's causing this issue. Considering the scope of this ticket, I've created a separate bug ticket (M3-7864) to address this issue.
![image](https://github.com/linode/manager/assets/119517080/3764d8fd-cd47-4430-807d-3edee1b6d4c8)

2024-03-12 17:51 UTC, cpathipa commented
> This was looking good from my testing, though typecheck is currently failing:
> 
> ![image](https://private-user-images.githubusercontent.com/114685994/309870187-cc51311e-f6a1-4fa0-bcd9-7c06c8cfa428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjMyNTksIm5iZiI6MTcxMDI2Mjk1OSwicGF0aCI6Ii8xMTQ2ODU5OTQvMzA5ODcwMTg3LWNjNTEzMTFlLWY2YTEtNGZhMC1iY2Q5LTdjMDZjOGNmYTQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNzAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWEzOTAyM2FkMmQxMDk5NDBhMjQwMjJkMTY5Mjc5OTU5ZTI0NDA1MmY2MTc1N2FmNDYwOTU3NTc3NjU1YTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sx5EHCy9NbmOlzH9-s7Jp57dagIlRAuOYqN4Q9yjeDA)
> 
> * [x]  Validated buckets landing is fetched with regions instead of clusters (e.g. GET `object-storage/buckets/us-iad?page_size=500`)
>   Note: I'm not very familiar with the Object-MultiCluster feature or the mock data, but in addition to the GET requests for buckets that use regions, I was also seeing requests that include the cluster. Wasn't certain if that was still expected.
>   ![Screenshot 2024-03-04 at 10 32 58 AM](https://private-user-images.githubusercontent.com/114685994/309864236-ca4917f2-3bf3-4365-88cc-9889d1b0ef37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjMyNTksIm5iZiI6MTcxMDI2Mjk1OSwicGF0aCI6Ii8xMTQ2ODU5OTQvMzA5ODY0MjM2LWNhNDkxN2YyLTNiZjMtNDM2NS04OGNjLTk4ODlkMWIwZWYzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNzAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTYyN2JkNTdlODI0N2E3NjZjOGIzNDQ3Y2E2MGU1MjgxZTc2ZjYzYmM5YTBkNTg4NjgwNWE0OWRiN2I2ZTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7D7SGUK6NKXWQAsN6G6pO_sj-wSy3L3sqmK97n4NGiQ)
> * [x]  Validated bucket access is fetched (endpoint) with regions instead of clusters (e.g. GET `object-storage/buckets/us-iad/obj-bucket-1/access`)
> * [x]  Verified the bucket access PUT request has updated with region instead of clusters (e.g. PUT `object-storage/buckets/us-iad/obj-bucket-1/access`)
> * [x]  With the feature flag off, tested Buckets landing and Details CRUD flows for regressions

@mjac0bs Thank you for testing the testing.

- Addressed the typecheck in 53f796d
- There are a couple of places in CM where we are fetching buckets with clusters, such as SearchBar.tsx, SearchLanding.tsx, and PrimaryNav.tsx. Considering current PR size, scope and testing efforts, I will create a follow-up PR as part of M3-7536 to address this.

2024-03-12 17:54 UTC, cpathipa commented
Looking into the failed object-storage.smoke.spec test

2024-03-12 17:56 UTC, dwiley-akamai approved these changes

2024-03-12 19:48 UTC, mjac0bs approved these changes
Thanks for addressing the feedback! Confirmed that other than the test failure, this all looks good.

2024-03-13 13:12 UTC, jdamore-linode requested changes
Just want to call out an issue with the recent change to the e2e file before it gets merged! Happy to help work out this test issue

2024-03-13 16:58 UTC, jdamore-linode approved these changes
Thanks @cpathipa, looks good!

2024-03-13 17:09 UTC, merged