change: [UIE-7308] - notification for resizing database
linode/manager pull request #10262
Opened 2024-03-06 16:19 UTC by mpolotsk-akamai

## Description 📝
Bell icon / Alert changes:
System notify users when database resizing starts, display a progress bar which disappears upon completion, update status from 'Active' to 'Resizing', show resizing progress in percentage, and revert to 'Active' status when finished.
Option to switch between dedicated and shared plans, with the exception of switching from dedicated plan to a shared plan of the same size.

## Changes  🔄
List any change relevant to the reviewer.
- Notification / Event of resizing Start
- Notification progress bar in Bell icon Alert 
- Notification complete – bar disappears 
- Shared to dedicated and back plan change 
- Status Changes from Active to Resizing
- Rendering progress % numbers in UI 
- Changing back to Active when done. - no Api change / UI change status reflected automatically when done

## How to test 🧪
Open application, navigate to /databases, select the database cluster. Go to the Resize tab, choose a plan, and click the 'Resize Database Cluster' button. In the popup window, confirm the resizing by entering the name of the database cluster, then click 'Resize Cluster' button. You can monitor the resizing status in the Summary and Resize tabs, as well as in a table on the Databases page. Additionally, notification about scheduled resizing and a progress bar which disappears upon completion in bell icon dropdown.

2024-03-06 17:15 UTC, carrillo-erik commented
Could you please share any insight with the following..

When an action is successful we denote the toast notifications with green color.
![Screenshot 2024-03-06 at 9 08 55 AM](https://github.com/linode/manager/assets/119514965/8910b037-e6e9-4c2c-b33d-8953d5315aa0)

Here is an example for `volume` being resized.
![Screenshot 2024-03-06 at 9 12 18 AM](https://github.com/linode/manager/assets/119514965/40854234-d848-42ac-8a57-8955b00d7a48)

2024-03-07 12:41 UTC, mpolotsk-akamai commented
> Could you please share any insight with the following..
> 
> When an action is successful we denote the toast notifications with green color. ![Screenshot 2024-03-06 at 9 08 55 AM](https://private-user-images.githubusercontent.com/119514965/310590390-8910b037-e6e9-4c2c-b33d-8953d5315aa0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE1MTYsIm5iZiI6MTcwOTgwMTIxNiwicGF0aCI6Ii8xMTk1MTQ5NjUvMzEwNTkwMzkwLTg5MTBiMDM3LWU2ZTktNGMyYy1iMzNkLTg5NTNkNTMxNWFhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODE0YjljMjc4YmViYTBkYWE0NTU1MzExNmIzOTMwY2ZlMzQ0ZTBlYjNjYjMyZDU1ZGQ4ZDQyZDA0MGUyZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ULOqDi8V2IsD2KJ1y49FBsq5rZUptG5_jCO2ZbaZv8)
> 
> Here is an example for `volume` being resized. ![Screenshot 2024-03-06 at 9 12 18 AM](https://private-user-images.githubusercontent.com/119514965/310591670-40854234-d848-42ac-8a57-8955b00d7a48.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE1MTYsIm5iZiI6MTcwOTgwMTIxNiwicGF0aCI6Ii8xMTk1MTQ5NjUvMzEwNTkxNjcwLTQwODU0MjM0LWQ4NDgtNDJhYy04YTU3LTg5NTViMDBkN2E0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Njk0OTBmNTQ3ZTI5YjEyMmExODUwYWY3OGIzZDUxMzZmOTAxN2I1ODU4OWI3Yzc2NzJhNjQ3YjRjYTZjZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6B5ReGHSDZL3ugtPTwE0uaELg9blq3FbH-X1-qI_i0)
> 
> Also, there is a discrepancy with the copy of the toast notification. Normally, only notifications for `account` or `profile` actions will start the message with `Your ...`

We have a blue notification (info) indicating that the database cluster will be resized, similar to the behavior of Linode Resize.
A green notification (success) means, for example, that the database was successfully resized, indication successful completion, while red notification indicates that the action was not successful.

![Screenshot 2024-03-07 at 11 16 34 AM](https://github.com/linode/manager/assets/157619599/d5bf5900-261d-4213-aaf5-f83539855e11)
![Screenshot 2024-03-07 at 12 38 31 PM](https://github.com/linode/manager/assets/157619599/dfda803d-fb17-416f-95e9-c223c77544d6)


Regarding the text in the notification I will update it to "Database cluster {cluster name} is being resized."

2024-03-07 14:41 UTC, abailly-akamai reviewed
Thanks for the solid PR!

a few things overall:
- make sure to use strict equality
- You have unit test failures (run `yarn test` or look at GH action report
- this is lacking coverage (unit test in this PR, and is there any plan to add e2e coverage?)
- You need to rebase this PR to get the latest changes from develop
- Make sure to add screenshots about what I am expected to see in the UI in your PR description
Am not seeing the progress bar. Is it only in alpha? If so, please add that the PR needs to be tested with alpha
![Screenshot 2024-03-07 at 09 37 01](https://github.com/linode/manager/assets/130582365/fcf46df6-33ad-4e89-b737-6804b6ad5b13)

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/.changeset/pr-10262-changed-1709742412767.md
> +bell icon / alert changes : display a progress bar which disappears after resize complete, update status from Active to Resizing, show resizing progress in percentage, and revert to Active status whe
```suggestion
Notifications for database resize events ([#10262](https://github.com/linode/manager/pull/10262))
```

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +  );
```suggestion
      (currentPlan?.class === 'dedicated' && type.disk === currentPlan?.disk)
  );
```

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
> +                (progress != undefined ? ' (' + progress + '%)' : '')}
```suggestion
                (progress !== undefined ? ' (' + progress + '%)' : '')}
```

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
> +  }
Keep you code DRY and make this a tested util

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
> +        disabledTypes?.find((element) => element === plan) != undefined;
```suggestion
        disabledTypes?.find((element) => element === plan) !== undefined;
```

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
> +) => {
add return types

2024-03-07 14:41 UTC, abailly-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +          disabledTypes={disabledPlans}
The naming convention `disabledTypes` isn't very clear in its intent. Maybe `disabledPlanTypes`?

2024-03-13 14:04 UTC, abailly-akamai reviewed
Thanks @mpolotsk-akamai the PR is looking good. 

- **Please add to the description that this needs to be tested on DEV/ALPHA** (I imagine this is not going live for a while and still behind a feature flag?
- Left some code clean up comments

Was able to confirm the events and the progress bar however, I am getting an error in the console about an unknown API event received, which seems to be directly related to the resize event. Can you look into it?

![Screenshot 2024-03-13 at 09 46 11](https://github.com/linode/manager/assets/130582365/1800f9cc-545a-4756-a2c8-c6c74bde86e6)

2024-03-13 19:09 UTC, abailly-akamai approved these changes

2024-03-14 15:56 UTC, carrillo-erik requested changes

2024-03-14 20:05 UTC, hana-linode reviewed
Can we extend the width of the loading bar to match the container?

![image](https://github.com/linode/manager/assets/115299789/c4eae747-95f9-4977-95ac-ea20b767fc24)

example from the MSW
![image](https://github.com/linode/manager/assets/115299789/632826cc-25af-4260-ac7d-7efb93a7e380)

Generally, settings are positioned as the last tab content instead of the middle. Can we move the Resize tab next to Backups instead of at the end?
![image](https://github.com/linode/manager/assets/115299789/c5bf4eca-d2ca-4164-80b9-b9088df3f007)

examples
![image](https://github.com/linode/manager/assets/115299789/0958f659-a1f1-4eab-ae21-75b08ac74a0a)
![image](https://github.com/linode/manager/assets/115299789/97ca4150-36da-40e3-96cd-8453329e6e5b)

2024-03-18 18:28 UTC, hana-linode commented
@mpolotsk-akamai looks like there are merge conflicts that need to be addressed

2024-03-18 20:53 UTC, mpolotsk-akamai commented
@hana-linode , merge conflicts have been resolved

2024-03-19 16:04 UTC, hana-linode approved these changes

2024-03-20 12:55 UTC, carrillo-erik commented
Thanks for making the changes.

2024-03-20 12:56 UTC, carrillo-erik approved these changes

2024-03-21 16:40 UTC, merged