upcoming: [M3-7842] - Update Assign Linode Drawer and tighten queries
linode/manager pull request #10263
Opened 2024-03-06 16:35 UTC by abailly-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-03-06 19:31 UTC, bnussman-akamai requested changes

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
> +    expect(container).toBeEmptyDOMElement;
```suggestion
    expect(container).toBeEmptyDOMElement();
```

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
The first time this drawer opens, the open animation does not happen.

https://github.com/linode/manager/assets/115251059/167342e3-0156-45a8-b26b-490ba3bc4e75

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
>        <Grid>
Can we remove this `<Grid />`?

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/hooks/usePlacementGroupsData.ts
> +      '+or': placementGroup?.linodes.filter(({ linode }) => linode),
I think this is the filter we want here

```suggestion
      '+or': placementGroup?.linodes.map((linodeItem) => ({
        id: linodeItem.linode,
      })),
```

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
>            region: selectedPlacementGroup?.region,
Can we remove the `+or` from this filter. We don't need an `or` if there is only one condition.

2024-03-06 19:31 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
> +    );
Optional: We could use an API filter to filter out the Linodes already in the placement group. Might be an over-optimization, but we could if you want.

2024-03-07 15:35 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx
> +    expect(container).toBeEmptyDOMElement;
🤦

2024-03-07 15:35 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
fixed by not skipping the query in the drawer. this drawer/modal/query business is unsavory at best

2024-03-07 15:35 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx
> +    );
I'll make a not of that one as a follow up to do when we are against a real API

2024-03-07 15:35 UTC, abailly-akamai commented on packages/manager/src/hooks/usePlacementGroupsData.ts
> +      '+or': placementGroup?.linodes.filter(({ linode }) => linode),
yup that seems about right - not for later - optimize queries when working with real data

2024-03-07 16:10 UTC, bnussman-akamai approved these changes

2024-03-07 17:52 UTC, jaalah-akamai approved these changes
Looks good and clean

2024-03-07 17:52 UTC, jaalah-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
> +    +linodeId ?? -1,
Nit: As we come across these in the code, we should just make this more readable using `Number()` like we've been doing for booleans. I dislike this as much as the `!!` operator. (my two cents lol)

2024-03-08 03:31 UTC, merged