upcoming: [M3-7940]
linode/manager pull request #10328
Opened 2024-03-29 02:25 UTC by abailly-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-04-01 15:23 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
> +
this block is the more consequential of this PR.

The landing page table contains table rows with linode counts and a tooltip with the linode labels, therefore we need to fetch linodes... 

Previously we would query for each row - this was ok but as the feature grow and people may have many PGs, this is less than ideal to send 10+ different queries (they are x-filtering linode Ids on each row) which may never be invalidated during the session.

Instead, I've updated this page to gather all linode IDs assigned to all placement groups, query all those once, then dispatch them to each row with the `getPlacementGroupLinodes` util.

2024-04-01 15:23 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
> +  const isLinodeReadOnly = useIsResourceRestricted({
this fixes a false positive check introduced in https://github.com/linode/manager/pull/10257

2024-04-01 19:51 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
> +        setSelectedPlacementGroup(placementGroup);
Can we remove the `selectedPlacementGroup`  state and just derive it from the param and API data? It would allow us to eliminate the useEffect, the`setSelectedPlacementGroup` calls, and the `onExited`. 

```typescript
 const selectedPlacementGroup = placementGroups?.data.find(
    (pg) => pg.id === Number(id)
  );
```

2024-04-01 19:51 UTC, bnussman-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
> +    selectedPlacementGroup
I see the thought here, but I'm not sure how I feel about needing the useEffect to hold extra state along with the useQuery. I wonder if there is clean way we can just rely on the `useQuery`. Maybe we could use the `initialData` react query option?

2024-04-01 20:24 UTC, cpathipa commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
> +    history.replace(
Agree with @hkhalil-akamai unless we don't want it to be in the browser history.

2024-04-01 20:35 UTC, bnussman-akamai requested changes

2024-04-01 20:35 UTC, bnussman-akamai commented on packages/manager/src/queries/placementGroups.ts
> +    onSuccess: (_, ctx) => {
Can `ctx` be renamed to `variables`? Context is technically the 3ed parameter of an onSuccess function and this might cause confusion

2024-04-02 14:05 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
> +        setSelectedPlacementGroup(placementGroup);
Regarding this comment and others, i had added states to prevent the drawer to be emptied out before closing, which causes a flash of content. That being said I agree this is cleaner, and better than over-optimizing for something barely noticeable. Made that change 👍

2024-04-02 14:06 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
> +    selectedPlacementGroup
yup, used a useMemo as suggested by @hkhalil-akamai which makes things cleaner

2024-04-02 14:09 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx
> +    history.replace(
I added this change too, and used `history.push` for all methods. The only drawback is to `history -1` on the delete modal (since you would go back to an empty modal, but it is handled with `<NotFound />` and this is the proper, expected behavior 👍

2024-04-02 14:10 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx
> +
yup, good suggestion. had to modify slightly to handle `open` and have a proper dependency array, but i like this pattern!

2024-04-02 14:10 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx
> +  }, [id, placementGroups]);
done!

2024-04-02 14:11 UTC, abailly-akamai commented on packages/manager/src/queries/placementGroups.ts
> +    onSuccess: (_, ctx) => {
Oh yes thx for pointing this out. Named arguments would be nicer ... 😢

2024-04-02 14:15 UTC, abailly-akamai commented on packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
> +  hasEncounteredError?: boolean;
I don't really see the point of what you are describing here (tracking each individual error). This seems over complicated. Here we have one unassignment error at a time, reset after each error encountered (the boolean is based on mutation error, which we can only execute one at a time, so yes, the parent component be responsible for resetting this prop after each error). I confirmed the pattern working well without bells and whistles. 
Perhaps the naming convention is what creates confusion?

2024-04-02 14:19 UTC, abailly-akamai commented on packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx
> +  hasEncounteredError?: boolean;
i improved the naming convention and description

2024-04-02 14:32 UTC, abailly-akamai commented on packages/manager/src/queries/placementGroups.ts
> +      ]);
Why do you want to invalidate those? there's no placement group info displayed in the linode/detail UI

2024-04-02 14:51 UTC, abailly-akamai commented on packages/manager/src/queries/placementGroups.ts
> +      ]);
We invalidate this linode so that it won't be available to be assigned to another placement group,  but now that I am looking at it we actually populate the linode select via looking at all placement group linodes already assigned so this may not be needed at all. 
**However**, I dislike the idea of having a cache not reflecting API data. Do you think it matters?

2024-04-02 15:41 UTC, bnussman-akamai commented on packages/manager/src/queries/placementGroups.ts
> +      ]);
Yeah, I think we should perform invalidations with the goal to keep the cache reflecting the API

2024-04-02 18:42 UTC, cpathipa approved these changes
Overall LGTM! 

Confirming on the below.
- [x] Create PG
- [x] Editing PG
- [x] Delete PG
- [x] Assign Linode drawer
- [x] Unassign Modal

### Observations: 
Since the validation says min 3 chars, is it expected to consider  space as a character when creating a PG? 
![Edit Placement Group a (Anti-affinity)](https://github.com/linode/manager/assets/119517080/b4216d2d-9764-4824-9015-15d6f1bcf2e0)

2024-04-02 19:15 UTC, abailly-akamai commented
thanks @cpathipa 

if the API allows it, then so do we. I agree it's odd, i'll bring it up to them and we'll see if they want to modify the behavior

2024-04-02 19:16 UTC, merged