upcoming: [M3-7902] - Add PG region limit help text
linode/manager pull request #10355
Opened 2024-04-05 09:36 UTC by carrillo-erik

## Description 📝
Simple change UI change in the `PlacementGroupsCreateDrawer` to inform the user of the Placement Group limits base on selected region.

## Changes  🔄
List any change relevant to the reviewer.
- Conditional logic to render the Placement Group limits.

## Target release date 🗓️
04/15/2024

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![a1a1](https://github.com/linode/manager/assets/119514965/730bf53b-3dda-436b-a2e8-5043e425a915) | ![a2a2](https://github.com/linode/manager/assets/119514965/24c658f2-a9ef-46b5-a762-f2aa2b90a8a7) |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Verification steps
(How to verify changes)
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-04-05 15:19 UTC, dwiley-akamai approved these changes
Newly-opened drawer doesn't display region limit copy until a region is selected ✅

Copy is rendered upon selecting a region from the dropdown in the PlacementGroupsCreateDrawer component ✅

2024-04-05 15:29 UTC, abailly-akamai requested changes

2024-04-05 15:29 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +          )}
why adding a piece of state here? `selectedRegion` is already available

2024-04-05 15:33 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +          )}
Also, shouldn't this be the regionSelect helper text rather than an extra typography below it?

2024-04-05 16:26 UTC, carrillo-erik commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +          )}
@abailly-akamai 
> `selectedRegion` is already available

There's two pathways to the `PlacementGroupCreateDrawer`, one is from the Create Linode flow and the other is from the Placement Groups Landing Page. In the first case, the `selectedRegion` will be available, however, in the second case it would not be. In any event, there is some additional work needed on my part and your comment helped me identify it.


> shouldn't this be the regionSelect helper text rather than an extra typography below it?

The `helperText` prop is used to store the text for the tool tip.

2024-04-05 17:39 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +          )}
@carrillo-erik I see - helpText is usually the `Autocomplete` proper helper text and I can see it is [wrongly used in this component](https://github.com/linode/manager/blob/develop/packages/manager/src/components/RegionSelect/RegionSelect.tsx#L144).

We need to:
- add a new `tooltipText` prop and replace all wrong instances (there shouldn't be too many, TS will help you find them if you temporarily remove this prop)
- pass a new `helpText` in the regionSelect autocomplete instance and assign it the `helpText` prop

2024-04-05 21:22 UTC, hkhalil-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
>    );
I'm noticing that we have two sources of truth for the selected region, one is the formik `values.region` and the other is `regionSelected`. This means that they both have to be updated separately (e.g., on lines 60 and 61).

We could make the formik `values.region` the single source of truth as below (you would have to move this useMemo to below the formik declaration):

```suggestion
  const selectedRegion = React.useMemo(
    () => regions?.find((region) => region.id == values.region),
    [regions, values.region]
  );
```

Then use `selectedRegion` in place of `regionSelected` and `selectedRegionFromProps`.

2024-04-05 21:22 UTC, hkhalil-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +    setRegionSelected(selectedRegion);
If you make the changes above, you can delete these two lines.

2024-04-08 20:17 UTC, carrillo-erik commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +          )}
Took your suggestions and included them with my recent changes. I found the `tooltipText` and `helperText` prop clean up to be minimal. Let me know if I missed something on that front.

2024-04-08 20:19 UTC, carrillo-erik commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
>    );
@hkhalil-akamai Thank you for the suggestion, I went ahead and ran with it and things seem to be working fine and code is more maintainable this way.

2024-04-08 20:19 UTC, carrillo-erik commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +    setRegionSelected(selectedRegion);
Done.

2024-04-09 13:17 UTC, abailly-akamai reviewed
You still have some work to do on the prop switch

Also, i noticed something we can improve here:
![Screenshot 2024-04-09 at 09 08 31](https://github.com/linode/manager/assets/130582365/946c5c20-284d-40c5-a6b9-71706eeb9b94)

We should disabled the region in the region select if we reached the limit, similarly on how we're doing it on the PG select in the Linode create flow for assignment: 

![Screenshot 2024-04-09 at 09 16 48](https://github.com/linode/manager/assets/130582365/06572f9d-b982-4a09-bcfd-041b7a3d6708)

2024-04-09 13:17 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +  const displayRegionHeaderText = location.pathname.includes('/linodes/create');
Is there a reason you don't want to display this helper text in the Linode create flow?

2024-04-09 13:17 UTC, abailly-akamai commented on packages/manager/src/components/RegionSelect/RegionSelect.types.ts
> +  tooltipText?: string;
what about the existing instances of RegionSelect that were already using helperText to display a tooltip?? you will break them without updating their prop, which may be why you have failing  tests

2024-04-09 18:42 UTC, abailly-akamai commented on packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
> +  const displayRegionHeaderText = location.pathname.includes('/linodes/create');
this has been confirmed already. since the region select isn't displayed in the linode create flow, we need another way to convey that information, which will be handled in another ticket

2024-04-09 21:24 UTC, hkhalil-akamai approved these changes
Thanks for addressing several rounds of feedback. Approving this pending the `helperText` -> `tooltipText` migration for existing components @abailly-akamai pointed out.

2024-04-10 15:44 UTC, abailly-akamai approved these changes
Confirmed no other instance of RegtionSelect was affected by the prop change.

All good to go 👍

2024-04-10 15:44 UTC, abailly-akamai commented
@carrillo-erik you still need to resolve conflicts however

2024-04-11 20:33 UTC, merged