upcoming: [M3-7924] - Linode Create Refactor - VPC - Part 10
linode/manager pull request #10354
Opened 2024-04-05 00:01 UTC by bnussman-akamai

## Description 📝

- Adds a VPC section to the new Linode Create flow ✨ 

## Changes  🔄
- Builds **new** VPC panel that uses react hook from tooling 🔧
- Adds a VPC Select

## Preview 📷

![Screenshot 2024-04-04 at 8 00 07 PM](https://github.com/linode/manager/assets/115251059/515032eb-928a-438b-b120-14634f69c750)

## How to test 🧪

### Prerequisites
- Turn on the `Linode Create v2` feature flag 🎏 

### Verification steps
- Test the new VPC selction 🧪 
- Compare functionality to the existing Linode Create flow 🔍 

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-04-08 20:39 UTC, bnussman-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +  const { data, isFetching } = useVPCsQuery({}, filter ?? {});
I will come back and update this to use `useAllVPCsQuery` or an infinite query after https://github.com/linode/manager/pull/10322 gets merged

2024-04-08 20:43 UTC, bnussman-akamai commented on packages/manager/src/hooks/useCreateVPC.ts
> +    enableReinitialize: true,
Had to add this so that `region` updates when the region is changed on the Linode Create flow. This was not an issue with the existing create flow because the drawer was re-mounted when it was opened (causing the VPC create drawer to not animate)

2024-04-09 14:44 UTC, abailly-akamai reviewed
I'll spend more time with it in the UI once we get more reviews from folks more familiar than me with the feature. 

All together this looks great, concise, well thought & put together

Left some initial comments to look at a couple areas that could be improved

2024-04-09 15:05 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +              </LinkButton>
I agree with this. I did it this way to match the existing create flow. Should I make this change now or make a todo to do it after this refactor?

2024-04-09 15:10 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +                          field.onChange(checked ? null : '')
`null` / `undefined` in the payload will make the VPC Auto-assign an IPv4. A string will tell the API that we are specifying an explicit IPv4. 

So, the logic is
- If the "Auto-assign" Checkbox is checked, set the value to `null` so that an IP get auto-assigned
- If the "Auto-assign" Checkbox is unchecked, set the value to an empty string so that the text field shows and a user can type in an IPv4

2024-04-09 15:10 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
> +  return undefined;
Will add some comments here

2024-04-09 15:12 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx
> +        <LinkButton onClick={() => append('')}>Add IPv4 Range</LinkButton>
This adds an empty string to the `ip_ranges` array on the VPC interface. Appending an empty string item to the array will cause a new empty TextField to render so that the user can add a new IP range.

2024-04-09 15:12 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +                          field.onChange(checked ? null : '')
I'll look into adding some comments to clarify how this works

2024-04-09 15:17 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx
> +        <LinkButton onClick={() => append('')}>Add IPv4 Range</LinkButton>
Yeah, i am getting to understand that part. i think even doing 

// Adding an empty string to the array will render to new empty field
`const newRangeField = ''`

=> `append(newRangeField)`

or something like that could help with readability

2024-04-09 15:21 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +              </LinkButton>
It's really up to you. Not a blocker for this PR for sure since we're at parity, but perhaps a cafe item cause there's been friction on my end with UX not always agreeing on doing this consistently

2024-04-09 21:39 UTC, dwiley-akamai reviewed
I'm still testing and combing through the code, but it's looking good overall so far. A few comments:

<details>
<summary>Points with screenshots</summary>

1. Can we keep the "X" vertically centered in relation to the input field when there's an error? I think this has come up as an issue in other contexts, maybe there's a related/similar ticket in the backlog somewhere
![Screenshot 2024-04-09 at 4 31 38 PM](https://github.com/linode/manager/assets/114682940/00a4694c-0af3-4a42-9d41-c5066690024a)

2. Can we keep both dropdowns the same width to match prod?
![Screenshot 2024-04-09 at 5 00 44 PM](https://github.com/linode/manager/assets/114682940/46322120-6afc-485f-aa83-018b87b73d85)

3. Can we make some width adjustments so if you click far away from the Auto-assign & Assign checkboxes, they don't get toggled?

https://github.com/linode/manager/assets/114682940/89e4a897-c217-427e-8f23-25f5ad66cef9

4. There were some concerns during the initial IPv4 range work a couple of months ago about large header text like this (doesn't make the section hierarchy as clear) instead of the more understated one currently used in prod

![Screenshot 2024-04-09 at 5 36 55 PM](https://github.com/linode/manager/assets/114682940/7ccff7cf-3c7d-41e4-bd09-25c8b0b570a1)
</details>

2024-04-09 22:31 UTC, hkhalil-akamai approved these changes
Tested and verified parity with existing VPC flow, code review looks clean too -- excellent work as always!

Also, thanks for including comprehensive unit tests!

2024-04-09 22:31 UTC, hkhalil-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx
> +                />
The width of this textfield is shorter (166.5px vs 362.41px) than the original. Personally I prefer the shorter width since it more closely matches the expected length of the subnet value but just wanted to point it out.

2024-04-10 13:50 UTC, bnussman-akamai commented
I fixed point 1, 3, and 4. @dwiley-akamai 

I personally don't agree with 4. I was thinking an `h3` would be fine if every other header on the page is an `h2`. I've made the change regardless. 

I'm declaring point 2 out of scope because I told myself I wouldn't write one-off styling in this project 😖 I think the issue would have to be fixed at the Autocomplete component level if we want it to work that way globally.

2024-04-10 13:52 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx
> +                />
Yeah, it does look slightly odd. I wasn't able to easily fix it without writing one-off styles, so I'd prefer to leave it be

2024-04-10 13:57 UTC, abailly-akamai requested changes
Took a second pass at the UI and found regressions/improvements to be made to the UX. See comments for details

2024-04-10 13:57 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +          Assign this Linode to an existing VPC.{' '}
Production has "Allow Linode to communicate in an isolated environment." is this intentional?

2024-04-10 13:57 UTC, abailly-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +      {...rest}
We need to reset the VPC panel on region change. Repro:

- select an available region (ex: chicago)
- select a VPC
- change to a non-available region. ex: Newark
- see screenshot below

![Screenshot 2024-04-10 at 09 37 10](https://github.com/linode/manager/assets/130582365/70f0fd42-b532-4e7c-aece-8654a110a822)

You can basically keep interacting with the whole VPC form as the previous valus is still selected

2024-04-10 13:57 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +      />
It looks to me like the VPC drawer gets unmounted after the first close. Subsequent openings break transition and we can notice a weird delay when it opens

https://github.com/linode/manager/assets/130582365/2d589bb9-c7cc-485e-8346-c02c5ae2c7f0

2024-04-10 13:57 UTC, abailly-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +};
Also, this is at parity with current behavior, but it would be nice to have consistency there.

For firewalls, we can either select a firewall and clear the field which will set it back to "None"

in VPC, "None" is an option, which i feel is unecessary.

Either way would be nice to have consistency and maybe ask UX what should be the default.

2024-04-10 13:57 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +                  <VPCRanges />
Same thing here. I expect my subnet IPv4 ranges to be reset when clearing the field or selecting a new subnet

https://github.com/linode/manager/assets/130582365/125b5566-713c-4b96-b777-d2862f2d74db

2024-04-10 14:06 UTC, bnussman-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +      {...rest}
This is expected for now. I am saving "side effect" state update for later in this project.

2024-04-10 14:07 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +                  <VPCRanges />
Will handle these "side-effect" state updates in a later PR.

2024-04-10 14:09 UTC, abailly-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +      {...rest}
This is a local side effect, not a global one tho. You gotta point those out in your PR description

2024-04-10 14:15 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +      />
I'm unable to reproduce this.

2024-04-10 14:16 UTC, bnussman-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +};
Yeah, I thought using an option for "None" was pretty crazy.  

I went ahead an fixed this both here and in the Firewall section to use a placeholder instead of "None" placeholder option. 

This does break parity slightly, but it is a no-brainer change imo.

2024-04-10 14:24 UTC, abailly-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +      {...rest}
Got it. Would still be helpful for reviewers to know what's not supposed to work. I remembered default values being one, not those (tho they are clearly related).

2024-04-10 14:32 UTC, bnussman-akamai commented on packages/manager/src/components/VPCSelect.tsx
> +      {...rest}
I have a running list so I assure you these will be fixed! I will do my best to call these out in the future

2024-04-10 14:33 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +      />
hmm it's on FF only. Let's welcome new unfixable behaviors 😓 

Resolving this, not worth going into

2024-04-10 14:40 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +          Assign this Linode to an existing VPC.{' '}
Note for UX: 
![Screenshot 2024-04-10 at 10 39 30](https://github.com/linode/manager/assets/130582365/1fb6164e-530e-48a1-af5e-97b6be2e10ce)

It's a tiny bit unclear for the user you need to select a region to be able to select a VPC. Again, this is parity but something to think about. Weird it never came up 🤷

2024-04-10 14:44 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +          Assign this Linode to an existing VPC.{' '}
Agreed. I'll make an effort to circle back around to all of the weird UX things after this refactor happens

2024-04-10 16:20 UTC, dwiley-akamai approved these changes
The core functionality LGTM, nice work as the code patterns are pretty clean 🧽

I do think the remaining visual inconsistencies and regressions have to be addressed, but that can be in a follow-up or at least a circle-back before the Linode Create refactor is wrapped up.

<details>
<summary>Other quirks with IPv4 ranges</summary>

When there's an error, the field it belongs to gets horizontally widened, which makes me favor retaining the wider field width that we currently have in prod.

![Screenshot 2024-04-10 at 11 22 13 AM](https://github.com/linode/manager/assets/114682940/002988e8-ebba-4d9c-a237-b8885f026281)

The vertical distance between the fields is now greatly compressed compared to prod. I think that should be adjusted.

This isn't an issue per se, but I noticed that compared to prod, you now have to input something into the most recent field before clicking "Add IPv4 Range" adds a new input field.
</details>

Also, were you going to address the leftover changes from https://github.com/linode/manager/pull/10342#issuecomment-2037686354 in this PR?

2024-04-10 16:20 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +      : 'Assign this Linode to an existing VPC.';
minor: We lost some parity here -- a fresh form in prod shows `Allow Linode to communicate in an isolated environment.` but this branch shows `Assign this Linode to an existing VPC.`

2024-04-10 17:10 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
> +      : 'Assign this Linode to an existing VPC.';
Good catch. I believe the logic should now match the prod flow.

2024-04-10 21:14 UTC, merged