upcoming: [DI-18311] - Adding CloudPulse section to Cloud Manager
linode/manager pull request #10393
Opened 2024-04-22 12:49 UTC by santoshp210

## Description 📝
Added cloudpulse section to cloud manager
Added feature flag control for cloudpulse section
Added an empty paper component in the cloudpulse section

## Changes  🔄
List any change relevant to the reviewer.
-Added cloudpulse section cloud manager
-Added feature flag control for cloudpulse section
-Added empty paper component in the cloudpulse section

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-04-22 at 18 04 10](https://github.com/linode/manager/assets/159890961/5e3bb1df-f768-42f0-a1a8-fe04ae24a77b)| ![Screenshot 2024-04-22 at 18 05 00](https://github.com/linode/manager/assets/159890961/3f95601f-b37b-4a75-b8ca-0fbfa9c91f87)|

## How to test 🧪

### Prerequisites
(How to setup test environment)
- Follow cloud manager standard procedures

### Reproduction steps
(How to reproduce the issue, if applicable)
- N/A

### Verification steps
(How to verify changes)
- Navigate to cloud manager and once feature flag of CloudPulse is enabled then navigate to the Monitor section in the sidebar for the CloudPulse section.
## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-04-22 14:37 UTC, cpathipa commented on packages/manager/src/features/CloudPulse/CloudPulseLanding.tsx
> +      <Paper></Paper>
What is purpose of empty `Paper` here ?

2024-04-22 14:37 UTC, cpathipa commented on packages/manager/src/assets/icons/cloudpulse.svg
Looks like we have a similar icon for Longview. Is it different from that one?

2024-04-24 19:59 UTC, gitkcosby reviewed
If you're just stubbing this in, it's fine.  If not, there are some issues, such as the left nav saying "Monitor" and the page title saying "Akamai Cloud Pulse".

2024-04-25 07:08 UTC, santoshp210 commented
> If you're just stubbing this in, it's fine. If not, there are some issues, such as the left nav saying "Monitor" and the page title saying "Akamai Cloud Pulse".

The nav saying "Monitor" and page saying "Akamai Cloud Pulse" is intentional as per our Product Manager and UI mockups.

2024-04-25 14:47 UTC, gitkcosby approved these changes

2024-04-26 15:17 UTC, mjac0bs requested changes
Thanks for the new additions @santoshp210.

I confirmed the feature flag is present in the dev tools and the new landing primary nav entry routes to the new landing page. We'll need to fix the primary nav so the Monitor menu item respects the dev tools feature flag toggle. I also left some questions about the flag.

I'm not sure what your e2e testing plan is for building this feature out, but we will ask for test coverage of the overall flow. To start, that can be something as simple as testing the page navigation works and can be built out as the feature develops. (Example: [`loadbalancer-landing-page.spec.ts`](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts#L27-L33))

2024-04-26 15:17 UTC, mjac0bs commented on packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
> +  const showCloudPulse = Boolean(flags.cloudView);
We'll also want to include `showCloudPulse` in the dependency array of `useMemo`. Currently, I'm seeing Monitor in the primary nav regardless of whether the feature flag is toggled.

https://github.com/linode/manager/assets/114685994/973328a8-6c69-41ec-8b14-574ea1d1c1cd

2024-04-28 15:09 UTC, kmuddapo commented on packages/manager/src/dev-tools/FeatureFlagTool.tsx
> +  { flag: 'cloudView', label: 'CloudPulse' },
> Is CloudPulse replacing the CloudView name? If so, can we change the name of the feature flag to `cloudPulse` in Launch Darkly for consistency while we have the chance (i.e. it's only used in the two open PRs)? I'm happy to make that LD change; you'll just have to update the code references.

Sure, Could you please help change the LD feature flag from cloudView to cloudPulse? so that the name is consistent everywhere.

2024-04-30 04:13 UTC, kmuddapo commented on packages/manager/src/dev-tools/FeatureFlagTool.tsx
> +  { flag: 'cloudView', label: 'CloudPulse' },
Thanks!!.  @santoshp210 Let's update in the code base and push the changes with the same.

2024-05-07 08:37 UTC, kmuddapo commented on packages/manager/src/featureFlags.ts
> +  cloudView: boolean;
Yes!! we do planned to go with beta period, @santoshp210  Lets update with JSON so that it helps later.

2024-05-08 13:46 UTC, mjac0bs commented on packages/manager/src/featureFlags.ts
> +  cloudView: boolean;
@kmuddapo @santoshp210 I updated the flag in LD in accordance with M3-8084. The `aclp` flag is now serving JSON and is enabled in the development environment. You'll want to update `featureFlags.ts` to include an `aclpFlag` interface similar to the `PlacementGroupsFlag`, and the enabled state can be accessed via `flags.aclp?.enabled`.

2024-05-08 14:10 UTC, kmuddapo commented on packages/manager/src/featureFlags.ts
> +  cloudView: boolean;
Thanks!!

2024-05-15 16:39 UTC, mjac0bs reviewed
Thanks for the updates - this looks really close to being ready to merge. I'll approve this once merge conflicts are resolved and I left a couple of small suggestions about using the flag value to determine the visibility of the beta chip in the primary nav.

2024-05-15 16:39 UTC, mjac0bs commented on packages/manager/src/featureFlags.ts
> +
```suggestion
interface AclpFlag {
  beta: boolean;
  enabled: boolean;
}

```

Since we've recreated the flag to return a JSON object, we can include a beta boolean to be able to toggle UI changes when the feature is in beta. See the PrimaryNav comment for an example.

2024-05-15 16:39 UTC, mjac0bs commented on packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
> +          isBeta: false,
```suggestion
          isBeta: flags.aclp?.beta,
```

Using the feature flag here will allow us to toggle the visibility of the beta chip via feature flag, so a future code change will not be needed. 
![Screenshot 2024-05-15 at 9 35 48 AM](https://github.com/linode/manager/assets/114685994/52cb91c1-8363-494d-b836-306205065d85)

2024-05-15 16:53 UTC, santoshp210 commented on packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
> +          isBeta: false,
Yeah, pushing the changes now. Thank you!

2024-05-16 14:49 UTC, mjac0bs commented
@santoshp210 Please merge in the latest from `develop` (you'll have to resolve the conflicts in MainContent, PrimaryNav, and featureFlags) and then CI should run and we can confirm this is good to go.

2024-05-17 06:27 UTC, santoshp210 commented
Hi @mjac0bs , resolved the commits for those files.

2024-05-17 07:25 UTC, mjac0bs approved these changes

2024-05-20 14:22 UTC, bnussman-akamai approved these changes

2024-05-24 13:18 UTC, merged