feat:[LKEAPIFW-258] Enabling LKE events in CM
linode/manager pull request #10443
Opened 2024-05-07 03:20 UTC by talmai

## Description 📝
Enables LKE events (from apinext) to become highlighted as valid events on CM.

## Changes  🔄
Added new messages

## Target release date 🗓️
This should only be rolled out after respective nimbus/apinext PR is merged. See: https://bits.linode.com/LinodeAPI/apinext/pull/6249

## Preview 📷
![image](https://github.com/linode/manager/assets/2300553/fe517662-9e71-421a-b77c-20ef8f19b9e4)

## How to test 🧪

Either spin up a dev CPC and wire everything in devenv, or wire devenv to alpha's apinext. Then execute actions related to LKE clusters.

### Prerequisites
See how to test

### Verification steps
See how to test

## As an Author I have considered 🤔

*Check all that apply*

- [~] 👀 Doing a self review
- [~] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [~] 🤏 Splitting feature into small PRs
- [X] ➕ Adding a changeset
- [X] 🧪 Providing/Improving test coverage
- [~] 🔐 Removing all sensitive information from the code and PR description
- [N/A] 🚩 Using a feature flag to protect the release
- [~] 👣 Providing comprehensive reproduction steps
- [X] 📑 Providing or updating our documentation
- [ANYTIME!] 🕛 Scheduling a pair reviewing session
- [N/A] 📱 Providing mobile support
- [N/A] ♿  Providing accessibility support

2024-05-08 13:55 UTC, cpathipa commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +      `The node for Kubernetes Cluster ${e.entity!.label} has been recycled.`,
Can we use optional chaining with default values instead of a null assertion?
e.entity?.label ?? '' We could follow the same approach in other places as well.

2024-05-08 21:47 UTC, talmai commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +      `The node for Kubernetes Cluster ${e.entity!.label} has been recycled.`,
✅

2024-05-15 06:49 UTC, mjurosz requested changes

2024-05-15 06:49 UTC, mjurosz commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +  lke_pool_recyle: {
Typo
```suggestion
  lke_pool_recycle: {
```

2024-05-15 20:34 UTC, talmai commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +  lke_pool_recyle: {
✅

2024-05-16 12:39 UTC, mjurosz approved these changes

2024-05-16 13:30 UTC, jdamore-linode requested changes
Thanks @talmai! I think you'll need to also update our API library's `EventAction` type to include these new LKE event actions:

https://github.com/linode/manager/blob/develop/packages/api-v4/src/account/types.ts#L280

Other than that, this is looking great!

2024-05-16 17:35 UTC, bnussman-akamai approved these changes

2024-05-16 18:06 UTC, jdamore-linode approved these changes
Thanks again @talmai!

(Just to follow up from our discussion, here's a quick screenshot of the commands/output used to generate the changeset files -- then I just committed and pushed the files generated by the command 👍)

<img width="715" alt="Screenshot 2024-05-16 at 2 06 01 PM" src="https://github.com/linode/manager/assets/97627410/3e11e0c9-e20a-4b90-a048-5420e714c5d4">

2024-05-17 13:29 UTC, merged