upcoming: [M3-7874] - Linode Create Refactor - More Marketplace Progress
linode/manager pull request #10488
Opened 2024-05-20 17:02 UTC by bnussman-akamai

## Description 📝

Makes more progress on the Marketplace tab of Linode Create v2 🔧 

## Changes  🔄
- Introduces `oneClickAppsv2.ts` so that there is one source of truth (previously both `oneClickAppsv.ts` and `stackScriptUtils.ts` would have to be referenced)
- Makes new `AppDetailsDrawer` that accepts a `stackscriptId` instead of a label. I'm not sure why we were using labels...

## Preview 📷

| Before  | After   |
| ------- | ------- |
| Notice how there are duplicate apps and broken icons | Notice how expected apps are rendered |
| ![Screenshot 2024-05-20 at 12 58 48 PM](https://github.com/linode/manager/assets/115251059/00d313f9-85be-4024-865d-9e1605664b29) | ![Screenshot 2024-05-20 at 12 58 39 PM](https://github.com/linode/manager/assets/115251059/6348bd82-69e1-4fde-96ca-64ede6dcf96a) |

## How to test 🧪

### Prerequisites
- Enable Linode Create v2 feature flag 🇺🇸

### Verification steps
- Verify you can now view app details
- Verify that the apps rendered match the apps rendered in production

## As an Author I have considered 🤔

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-05-20 21:43 UTC, hkhalil-akamai approved these changes
Looking clean and verified parity with prod.

2024-05-20 21:45 UTC, hkhalil-akamai requested changes
I forgot to switch on the flag 🤦🏽‍♂️

It appears that app icons don't display when using the preview link:

![Screenshot 2024-05-20 at 5 45 31 PM](https://github.com/linode/manager/assets/122488130/9a1e8899-a747-4f8e-8046-3f5fccc3e217)

2024-05-20 22:46 UTC, bnussman-akamai commented
Good catch @hkhalil-akamai

Fixed in 1c7d215

2024-05-20 22:48 UTC, bnussman-akamai commented on packages/manager/src/features/OneClickApps/oneClickApps.ts
I have no idea 😞 

I think the new format (`oneClickAppsv2`) will make things considerably more simple. If you think of anything cleaner, let me know! I'm open to anything! Now is the time to fix all of this stuff

2024-05-20 22:54 UTC, bnussman-akamai commented on packages/manager/src/features/OneClickApps/oneClickApps.ts
For additional context, here's what I'm hoping for.

**The old setup sources data from**: StackScripts API, flags.oneClickApps, flags.oneClickAppsDocsOverride, `stackScriptUtils.ts`, and `oneClickApps.ts`

**The new setup will source data from**: StackScripts API, `oneClickAppsv2.ts`

We could keep a feature flag around for emergencies if we need to append to `oneClickAppsv2.ts`, but maybe we can go without it at first. cc @hana-linode

2024-05-21 14:13 UTC, jaalah-akamai reviewed
Do we have a plan to filter the apps by `New apps`, `Popular apps`, `All apps`?

2024-05-21 14:19 UTC, jaalah-akamai commented
Are we sunsetting the logo and information icon when an app is selected? The new design omits the both.
 
<img width="507" alt="Screenshot 2024-05-21 at 10 15 14 AM" src="https://github.com/linode/manager/assets/125309814/f4ca2055-197f-4516-943b-0ebd43df2cb1">

2024-05-21 14:24 UTC, bnussman-akamai commented
@jaalah-akamai All of that will come! I'm trying to do things in small PRs

2024-05-21 16:36 UTC, hkhalil-akamai approved these changes
Confirmed app icons are displaying. Nice work, Marketplace is coming along really well!

2024-05-21 21:19 UTC, jaalah-akamai approved these changes
✅ Confirmed new experience fixes issues listed
✅ Confirmed other implementation details will soon follow

2024-05-22 14:17 UTC, merged