feat: [M3-8054] - Create Linode - Create Using Command Line (DX Tools Additions)
linode/manager pull request #10547
Opened 2024-06-05 14:46 UTC by cpathipa

## Description 📝
This PR introduces Integrations tab and SDK's tab to ApiAwarenessModal, it generates code snippets for Terraform, Ansible, Go and Python.  

Note: Interfaces are not added to go snippets as it is getting more complex in generating the code snippet, this involves in defining the go variable and using within generated snippets. This will be tackled in a separate ticket. 

## Changes  🔄
List any change relevant to the reviewer.
- Add new tabs to ApiAwarenessModal
- New utils to generate code snippets
- Refactored ApiAwarenessModal. 

## Target release date 🗓️
7/08

## Preview 📷
| Integrations - Ansible  | Integrations - Terraform  |
| ------- | ------- |
|![image](https://github.com/linode/manager/assets/119517080/42cca325-86ba-423b-b294-3d6de4b604d0)| ![image](https://github.com/linode/manager/assets/119517080/12dcd26b-e85b-4c94-88f8-a8f4b668fde2)|

| SDK - GO  | SDK - Python  |
| ------- | ------- |
|![image](https://github.com/linode/manager/assets/119517080/030ff0fc-2dcf-442e-b37d-802f27b148cb)|![image](https://github.com/linode/manager/assets/119517080/660e03ad-8e31-4556-b9a2-db185f6d0dcf)|

## How to test 🧪
### Verification steps
(How to verify changes)
- Navigate to Linode create flow, click on "View Code Snippets" and turn on feature flag. 
- Verify the new tabs in ApiAwarenessModal.
- Verify the UX, copy changes, and links.
- Verify the copy and pate functionality of each code snippet generated.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-06-12 16:27 UTC, cpathipa commented on packages/manager/src/featureFlags.ts
> +  apicliDxToolsAdditions: boolean;
New flag added.

2024-06-12 16:27 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +          {isFeatureEnabled ? (
Decoupled into respective tab panel components.

2024-06-12 16:27 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/SDKTabPanel.test.tsx
> +import { fireEvent, screen } from '@testing-library/react';
Test coverage for new panel.

2024-06-12 16:27 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/IntegrationsTabPanel.test.tsx
> +import { fireEvent, screen } from '@testing-library/react';
Test coverage for new panel.

2024-06-18 16:02 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +          )}
We can just map over `tabs` to generate all these.

2024-06-18 16:02 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +          )}
We can just map over `tabs` to generate all these too

2024-06-18 16:39 UTC, jdamore-linode commented
@cpathipa Any chance you could add some E2E tests for when this feature flag is enabled?

2024-06-19 15:05 UTC, bnussman-akamai reviewed
Functionality looks solid. Going to keep reviewing 👀

2024-06-19 15:05 UTC, bnussman-akamai commented on packages/manager/src/utilities/codesnippets/generate-goSDKSnippet.ts
Are things like `interfaces`, `disk_encryption`, and `metadata`  going to be added?

2024-06-19 15:05 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/IntegrationsTabPanel.tsx
> +        onChange={(_, option) => handleIntegrationChange(option!)}
If the text field is clearable, we should probably not use a non-null assertion here

2024-06-19 15:05 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/CurlTabPanel.tsx
> +  tabs: { title: string; type: string }[];
Feels a bit odd to me to pass the tabs to each panel. Is this necessary?

2024-06-20 20:32 UTC, hana-linode commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +  const isFeatureEnabled = flags?.apicliDxToolsAdditions;
Can we rename this to something more specific like `isDxAdditionsFeatureEnabled`?

2024-06-20 20:32 UTC, hana-linode commented on packages/manager/src/utilities/codesnippets/generate-goSDKSnippet.ts
And `VPC`?

2024-06-25 15:45 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +  const tabs = isFeatureEnabled
Addressed in [3598644](https://github.com/linode/manager/pull/10547/commits/3598644164707032c11c30614cdfe14c1be886e8)

2024-06-25 15:46 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +          )}
Addressed in [3598644](https://github.com/linode/manager/pull/10547/commits/3598644164707032c11c30614cdfe14c1be886e8)

2024-06-25 15:46 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +          )}
Addressed in [3598644](https://github.com/linode/manager/pull/10547/commits/3598644164707032c11c30614cdfe14c1be886e8)

2024-06-25 15:47 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
> +  const isFeatureEnabled = flags?.apicliDxToolsAdditions;
Thanks @hana-linode addressed in Addressed in [3598644](https://github.com/linode/manager/pull/10547/commits/3598644164707032c11c30614cdfe14c1be886e8)

2024-06-25 16:07 UTC, jaalah-akamai approved these changes

2024-06-26 13:51 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/CurlTabPanel.tsx
> +  tabs: { title: string; type: string }[];
Agree, addressed in [3598644](https://github.com/linode/manager/pull/10547/commits/3598644164707032c11c30614cdfe14c1be886e8)

2024-06-26 16:28 UTC, cpathipa commented on packages/manager/src/utilities/codesnippets/generate-goSDKSnippet.ts
@bnussman-akamai @hana-linode I tried to add interfaces (which has VPC)  and metadata. Currently facing  go lang type errors for these fields like SubnetID    *[int](https://pkg.go.dev/builtin#int). Will address adding interfaces in a followup ticket.  
Looks like disk_encryption options is not defined in [InstanceCreateOptions](https://github.com/linode/linodego/blob/v1.36.0/instances.go#L127)  throwing unknow field type error when added.

2024-07-01 13:05 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
> +  const isFeatureEnabled = flags?.apicliDxToolsAdditions;
Can we use a more descriptive name here?

maybe something like
```suggestion
  const isDxToolsAdditionsEnabled = flags?.apicliDxToolsAdditions;
```

2024-07-01 15:10 UTC, cpathipa commented
> @cpathipa Any chance you could add some E2E tests for when this feature flag is enabled?

@jdamore-linode cypress tests are covered in this PR https://github.com/linode/manager/pull/10626

2024-07-01 15:14 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
> +  const isFeatureEnabled = flags?.apicliDxToolsAdditions;
Looks like i missed this file in initial name change... update in b651370

2024-07-01 15:54 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/SDKTabPanel.tsx
> +        label="Software Developer Kits(SDK)"
Missing a space here I think

```suggestion
        label="Software Developer Kits (SDK)"
```

2024-07-01 20:30 UTC, jaalah-akamai commented
@cpathipa This is looking good, just a few question:

- Should we get one of the DX team members to confirm the snippets?
- I see changes to Create v1 but the modal open/close functionality doesn't seem to be implemented, should it be there?

2024-07-02 00:09 UTC, cpathipa commented
@jaalah-akamai Good call I will work with DX team to get their approvals on these snippets. 
Modal open / close is an existing behavior which is working as expected from my end.

https://github.com/linode/manager/assets/119517080/75c3a205-5aab-4631-8135-996fc40348b0

2024-07-22 19:45 UTC, cpathipa commented
**Update on this PR** : Zhiwei from DX team is going to run all the tools with the generated snippets. Once we get the approval I think we should be good to move forward on this.

2024-07-29 18:36 UTC, zliang-akamai commented
I think this PR is good to go now.

Only issue remains is in the Ansible Collection that `authorized_users` parameter is not supported by the Ansible Collection, which will be fixed from the DX side.

2024-07-29 18:44 UTC, cpathipa commented
@jdamore @Jaalah @bnussman @hxu When you get a chance, could you review this PR? We received approval from the DX team for the generated code snippets.

2024-07-30 13:59 UTC, bnussman-akamai approved these changes

2024-07-30 16:44 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
> +    it(`view code snippets in create linode flow`, () => {
Still have more to look at, but wanted to suggest making this an integration test using mock API data since there isn't really anything going on with the API where we'd benefit from having this be end-to-end (we're not actually creating a Linode here, for example).

2024-07-30 16:45 UTC, jdamore-linode commented on packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/GoSDKResources.tsx
> +    text: 'Linodgo Documentation',
```suggestion
    text: 'Linodego Documentation',
```

2024-07-30 16:45 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
> +          cy.contains('a', 'Linodgo Documentation').should('be.visible');
```suggestion
          cy.contains('a', 'Linodego Documentation').should('be.visible');
```

2024-07-31 15:28 UTC, cpathipa commented on packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
> +    it(`view code snippets in create linode flow`, () => {
@jdamore-linode Updated to integration test instead of e2e.

2024-07-31 19:39 UTC, jdamore-linode requested changes
I'm sorry @cpathipa, I think we want to undo the changes made to the `linode-view-code-snippet` spec because all these added mocks etc. aren't necessary and really hurt the test's readability -- I think the previous iteration of the test was much closer to where we want to be, just with the E2E-specific elements removed.

I'm sorry about this because I could've been more specific with my ask yesterday -- I'll hold off cutting the release so we can make sure this gets in, and don't hesitate to reach out on Slack if you need a hand making any of these changes 👍

Otherwise this is looking good to me and I'll be ready to give this an approval

2024-07-31 19:39 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/smoke-linode-view-code-snippet.spec.ts
I don't think it's necessary to pull in all of these mocks or change this spec's name -- we just want to get rid of the call to `authenticate` (since it's used for authenticating real API requests to e.g. create test resources before a test runs), the unneeded intercepts `interceptCreateLinode` and `interceptGetProfile`, and the comments that refer to this test as an end-to-end test

2024-07-31 19:39 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/smoke-linode-view-code-snippet.spec.ts
> +          );
We have a lot of assertions here for the contents of this dialog, but nothing confirming that the user's inputs are correctly inserted into the code snippets (see our [legacy CLI create test](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts#L228-L234) for an example of what I mean)

2024-07-31 20:20 UTC, jdamore-linode approved these changes
Thanks @cpathipa -- one little test title change but otherwise looking good!

2024-07-31 20:20 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
> +  describe('Create Linode flow with apicliDxToolsAdditions enabled', () => {
```suggestion
  describe('Create Linode flow with apicliDxToolsAdditions disabled', () => {
```
😅 my bad again for missing this before

2024-07-31 20:26 UTC, cpathipa commented on packages/manager/cypress/e2e/core/linodes/smoke-linode-view-code-snippet.spec.ts
> +          );
@jdamore-linode Created a follow-up ticket (M3-8410) to enhance these tests. Also, we have solid unit test coverage for the generated snippets for the supporting tools.

2024-07-31 20:42 UTC, merged