upcoming: [DI-19328] - Added capability to save & retrieve user preferences
linode/manager pull request #10625
Opened 2024-07-01 10:42 UTC by nikhagra

## Description 📝
Added a feature to save the users global filter selection to preferences & load it back when user revisit the page.

## Changes  🔄
Added UserPreference utility file to handle all the preferences related operations
Modified all the global filter components to by default get selected with preferences value, if any present.

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-07-01 14:51 UTC, mjac0bs commented
@nikhagra Before we review this PR, can we get a complete PR description? Unless there are no visual changes, the **Preview** section is helpful to see the UI differences at a glance. Including steps in **How to test** allows us to verify we can reproduce your changes as expected and edge cases have been accounted for.

2024-07-01 15:20 UTC, nikhagra commented
> @nikhagra Before we review this PR, can we get a complete PR description? Unless there are no visual changes, the **Preview** section is helpful to see the UI differences at a glance. Including steps in **How to test** allows us to verify we can reproduce your changes as expected and edge cases have been accounted for.

Yes working on it

2024-07-02 11:56 UTC, kmuddapo approved these changes

2024-07-02 11:57 UTC, venkymano approved these changes
LGTM

2024-07-02 16:06 UTC, bnussman-akamai reviewed
I worry that `/v4/profile/preferences` won't be a good long term solution for storing this stuff.

2024-07-02 16:06 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
We should be able to use our React Query data layer for anything related to user preferences. (`packages/manager/src/queries/profile/preferences.ts`). We try to use that instead of interfacing with `@linode/api-v4` functions directly

2024-07-02 22:03 UTC, mjac0bs requested changes
Thanks for the PR, @nikhagra. Left some comments throughout, and I do agree with Banks in thinking that a user's profile preferences doesn't feel like the best place to store CloudPulse prefs... were there other options discussed? 

As far as the UI: I am seeing disabled fields for the dashboard, region, and resources. Should I be testing this with additional configurations on my account? I can interact with the fields if I turn on the Mock Service Worker via our dev tools, but that won't save the user's values.

![Screenshot 2024-07-02 at 11 15 53 AM](https://github.com/linode/manager/assets/114685994/a49b6b88-2662-4f70-84f4-01ef92dce404)

2024-07-03 03:45 UTC, nikhagra commented
> Thanks for the PR, @nikhagra. Left some comments throughout, and I do agree with Banks in thinking that a user's profile preferences doesn't feel like the best place to store CloudPulse prefs... were there other options discussed?
> 
> As far as the UI: I am seeing disabled fields for the dashboard, region, and resources. Should I be testing this with additional configurations on my account? I can interact with the fields if I turn on the Mock Service Worker via our dev tools, but that won't save the user's values.
> 
> ![Screenshot 2024-07-02 at 11 15 53 AM](https://private-user-images.githubusercontent.com/114685994/345206268-a49b6b88-2662-4f70-84f4-01ef92dce404.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzgzOTEsIm5iZiI6MTcxOTk3ODA5MSwicGF0aCI6Ii8xMTQ2ODU5OTQvMzQ1MjA2MjY4LWE0OWI2Yjg4LTI2NjItNGY3MC04NGY0LTAxZWY5MmRjZTQwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMzQxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzhhNzdjMzE3YmNlZGE2NjA4MmFlYzMwYzQ3Njc0MGI2YjNlNTBkZDIwNDU4M2E4MzYyNDA0YWNlNTgxNWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5grovUX3hpnoKlluQtNQYxsfrGZnnOC18ymNcSGygbA)

Currently the endpoint for Dashboard component is not yet ready to use, that's why we have to use mock data for now.

2024-07-03 04:23 UTC, kmuddapo commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
Thanks!! for the suggestion.  We will take this up as part of enhancements later to use React Query Data layer.

2024-07-03 08:42 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/types.ts
> +  time_granularity: TimeGranularity;
No Specific reason, I've updated

2024-07-03 12:39 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
Changed the case of file name to camel case because in future more util files will be added for different functionalities

2024-07-03 12:40 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +        />
done

2024-07-03 12:40 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    }
done

2024-07-03 12:50 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseConstants.ts
done

2024-07-03 12:50 UTC, nikhagra commented on packages/api-v4/.changeset/pr-10625-upcoming-features-1719830627087.md
> +upcoming: [DI-19328] - Added capability to save & retrieve user preferences ([#10625](https://github.com/linode/manager/pull/10625))
done

2024-07-03 12:50 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
done

2024-07-03 12:51 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +        />
done, removed all the select components

2024-07-03 14:32 UTC, jcallahan-akamai commented
> Currently the endpoint for Dashboard component is not yet ready to use, that's why we have to use mock data for now.

@nikhagra I have the same question as @mjac0bs. The first testing instruction you have provided is: "Select values from global filter drop-downs."

Yet all I see is disabled fields:
![Screenshot 2024-07-03 at 10 31 36 AM](https://github.com/linode/manager/assets/114753608/5873e266-fe08-47b2-b66a-1a020c4c8d16)

In your comment above you acknowledge that we must use mock data. If that is the case, please include steps to configure mock data appropriately in your testing instructions.

2024-07-04 10:23 UTC, nikhagra commented
> > Currently the endpoint for Dashboard component is not yet ready to use, that's why we have to use mock data for now.
> 
> @nikhagra I have the same question as @mjac0bs. The first testing instruction you have provided is: "Select values from global filter drop-downs."
> 
> Yet all I see is disabled fields: ![Screenshot 2024-07-03 at 10 31 36 AM](https://private-user-images.githubusercontent.com/114753608/345464058-5873e266-fe08-47b2-b66a-1a020c4c8d16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODU5MDIsIm5iZiI6MTcyMDA4NTYwMiwicGF0aCI6Ii8xMTQ3NTM2MDgvMzQ1NDY0MDU4LTU4NzNlMjY2LWZlMDgtNDdiMi1iNjZhLTFhMDIwYzRjOGQxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwOTMzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTgwZmQyOGIyNmQ5ODZiMjdjNWE5M2IzM2VkODMxNmQ2OGNkM2NmMTg2MzRmOWIxMjlkMmNjZWFlYTEzNGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZRIiJNYxG2KA0hCVdNPOpDnF9YnVkR0-csS18ZKP7E)
> 
> In your comment above you acknowledge that we must use mock data. If that is the case, please include steps to configure mock data appropriately in your testing instructions.

@jcallahan-akamai I've updated the testing instructions in the description. Since we can only test now as mock user, so preferences won't be saved for mock user but we can verify the same from network tab for preferences API call on value change.

2024-07-05 17:06 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
@kmuddapo Use of React Query is something we'd need to see in this PR to get it merged, rather than later. Using direct api-v4 functions is rare in our codebase, and it may be acceptable on a one-off basis, but our best practice is to use RQ almost all the time -- this offers caching benefits, helps us manage states (loading, errors), as well as provides overall consistency in code. (See [here](https://linode.github.io/manager/development-guide/05-fetching-data.html#when-to-use-react-query-or-an-api-v4-method-directly) for our section of documentation on this.) In this PR, even with debouncing, we'd be making several requests to `/profile/preferences` and we should be leveraging the RQ cache.

@nikhagra Please update to use React Query here in place of the api-v4 functions, and let us know if you run into any questions on implementing that switch.

2024-07-05 17:28 UTC, nikhagra commented
> Thanks for addressing some initial feedback @nikhagra. Testing instructions are looking good now - appreciate the update. I confirmed the network requests and responses upon updating `/profile/preferences`.
> 
> Two more bits of feedback:
> 
> 1. Please see my comment about React Query.
> 2. I am still somewhat concerned about storing these preferences in a user's profile preferences, rather than that information being returned from an `aclp` endpoint. Do we anticipate there being  additional data stored in user preferences for CloudPulse?
> 
> As is, it feels out of place. For context, `/profile/preferences` is generally used to store things like what theme (light/dark/system) colors to use, or whether banners have been dismissed.

@mjac0bs 
1. Sure will check.
2. More additional data will be stored in user preference for CloudPulse as we are going to add more features moving forward.

2024-07-09 13:16 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +        onChange={(e, region) => {
Here, we can remove the unused `e` variable with the following: `onChange={(_, region)`

2024-07-09 13:25 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const [selectedResources, setSelectedResources] = React.useState<any>();
Can we get avoid using `any`, I think the type you need here is `CloudPulseResources` which is defined in line 12.

2024-07-09 13:25 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const getResourcesList = (): any[] => {
Same as comment above.

2024-07-09 13:56 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const getResourcesList = (): any[] => {
done

2024-07-09 13:56 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const [selectedResources, setSelectedResources] = React.useState<any>();
done

2024-07-09 13:56 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +        onChange={(e, region) => {
done

2024-07-09 16:09 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +            [RESOURCES]: resourceSelections.map((resource: { id: any }) =>
```suggestion
            [RESOURCES]: resourceSelections.map((resource: { id: string }) =>
```
As a best practice, we want to avoid `any`, because it isn't type safe. We'd expect the `id` to be a `string` here, so we can type it as such.

2024-07-09 16:10 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +        data-testid="Resource-select"
```suggestion
        data-testid="resource-select"
```
Nit: consistency with capitalization

2024-07-09 19:08 UTC, carrillo-erik approved these changes

2024-07-10 05:42 UTC, VenkatMano approved these changes

2024-07-10 09:07 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +        data-testid="Resource-select"
done

2024-07-10 09:09 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +            [RESOURCES]: resourceSelections.map((resource: { id: any }) =>
done

2024-07-10 09:09 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
>  import { CloudPulseTimeRangeSelect } from '../shared/CloudPulseTimeRangeSelect';
done

2024-07-10 09:10 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +export const loadUserPreferences = () => {
done

2024-07-10 09:10 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +/* eslint-disable react-hooks/rules-of-hooks */
done

2024-07-10 19:06 UTC, mjac0bs commented
Confirmed the only test failure is on `linodes/clone-linode.spec.ts`, which has been flaky and unrelated to this PR. Going to merge.

2024-07-10 19:07 UTC, merged