upcoming: [DI-19610] - Added CloudPulse widget to show graph for different metrices
linode/manager pull request #10676
Opened 2024-07-15 13:21 UTC by nikhagra

## Description 📝
Added Cloud Pulse widgets to visualize the graphs for different metrices for the selected service type

## Changes  🔄
List any change relevant to the reviewer.
1. Dashboard Component is added to fetch the metric definitions data & load widgets for all the metric definitions available.
2. CloudPulse Widget component is added to load the graphs & various filters available for each metrics.
3. Aggregate Function component is added to show widget data based on different aggregate functions.
4. Interval component is added to show widget data at selected time interval.
5. Zoomer component is added to zoom-in or zoom-out individual widgets.
6. Added logic to update widget data to preferences 
7. A refresh button is added in global filters to manually refresh the metrics data. (Functionality will be added in future PRs).

## Target release date 🗓️
Target Release date: 22nd July 2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-07-15 at 5 27 28 PM](https://github.com/user-attachments/assets/5c775018-af9d-4089-b8fb-1a76d24749dc) | ![Screenshot 2024-07-15 at 5 35 33 PM](https://github.com/user-attachments/assets/26706ea0-4739-4cb0-bf3c-348df77c147f) |
|![Screenshot 2024-07-19 at 12 44 42 PM](https://github.com/user-attachments/assets/36efb566-fa4b-4f8d-b448-8155446c7ed4)|![Screenshot 2024-07-19 at 12 43 41 PM](https://github.com/user-attachments/assets/f86a0cf4-b582-41c3-b43f-9e7602dc6d79)|
|![Screenshot 2024-07-19 at 12 43 58 PM](https://github.com/user-attachments/assets/3933af4a-682f-4f37-88f4-f378bf942f4f)|![Screenshot 2024-07-19 at 12 44 21 PM](https://github.com/user-attachments/assets/460f258a-c8fc-4c86-b817-999077506251)|

## How to test 🧪

1. Enable mock services as some endpoints are not ready to use.
2. Since the PR has only structural view of the widgets & not its actual functionality to load the data. You can play around with different drop down & zoom-in /zoom-out icon to check the working.
3. Preferences are also added to update widget changes, so you can verify from network tab that on any drop down change or zoom-icon click, it'll do a network call to preferences api.

Note: Currently a dummy graph is added to showcase how complete widget will look like & actual graph implementation will be added in future PRs

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a changeset
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-07-16 14:03 UTC, gitkcosby commented
@nikhagra there are a number of UX issues, mostly related to alignment. Are you roughing in these features for now and then going back and fixing UX issues?

2024-07-16 14:15 UTC, nikhagra commented
> @nikhagra there are a number of UX issues, mostly related to alignment. Are you roughing in these features for now and then going back and fixing UX issues?

Yes @gitkcosby, first we are prioritizing features as we have very tight deadline for beta release. And based on the bandwidth available either we try to fix them parallely or after we are dome with atleasy minimum features required for beta.

2024-07-16 19:53 UTC, jaalah-akamai requested changes
I strongly recommend breaking down large PRs like this into smaller, more manageable ones in the future. Doing so will help reviewers better understand the changes and likely expedite the review process. This PR is particularly large and complex, so unfortunately, it won't make it into the 22nd release in its current state.

I did not get a chance to review, but I'll probably have to do another entire review of this again:
- `CloudPulseIntervalSelect.tsx`
- `Zoomer.tsx`
- `serverHandlers.ts`
- `/shared/` directory
- `/queries/cloudpulse/` directory

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard && dashboard.service_type ? true : false,
```suggestion
    Boolean(dashboard?.service_type),
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard.service_type : undefined!,
```suggestion
    dashboard?.service_type,
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard!.service_type : undefined!,
```suggestion
    dashboard?.service_type,
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard && dashboard!.service_type !== undefined ? true : false
```suggestion
    Boolean(dashboard?.service_type)
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    resources && dashboard ? true : false
```suggestion
    Boolean(resources)
```
Resources is dependent on dashboard so that's all we really need to check I believe.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard.service_type! : undefined!,
```suggestion
    dashboard?.service_type,
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +      <Paper style={{ height: '100%' }}>
use `sx` prop instead

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  if (dashboard && dashboard.service_type && isLoading) {
I would rename `isLoading` to `isLoading: isMetricLoading` in the query and that's all we need here because the query is dependent on `dashboard`.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  }
I don't understand why this is needed, It's the exact same condition as above.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  };
⚠️ I would suggest you start fresh with this entire `RenderWidgets` function. It's quite convoluted and really needs to be simplified. You can do this without all the nesting you're doing. Deal with the base cases first (the conditional checks) and then end with the result.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    flex: 'auto',
Just add this to the `sx` prop of `Placeholder` if it's just one style.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +        <StyledPlaceholder icon={CloudPulseIcon} subtitle={subtitle} title="" />
Is `title` required here?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +  const onFilterChange = React.useCallback((_filters: FiltersObject) => {}, []);
Placeholder?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +          <div style={{ width: '100%' }}>
Avoid `div` and use either `Box`, `Stack`, or `Grid` to accomplish this

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +      />
Placeholder code?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +        <Grid sx={{ marginLeft: -4, marginRight: 3 }}>
Without building this, the margins on the grid seem odd to me - is that necessary?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +    color: 'green',
Nit: Can we utilize a theme color here?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +
There's a lot of type casting here... also this seems overly complicated, couldn't we simplify?
```
export const updateWidgetPreference = (label: string, data: Partial<AclpWidget>) => {
  userPreference.widgets[label] = {
    ...userPreference.widgets[label],
    label,
    ...data,
  };
  debounce(userPreference);
};
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +  return nonFormattedString;
```suggestion
return nonFormattedString
    .split(' ')
    .map(text => text.charAt(0).toUpperCase() + text.slice(1))
    .join(' ');
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const removeObjectReference = (object: any) => {
```suggestion
export const removeObjectReference = <T>(object: T): T | null => {
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +}
Can we add some jsdoc comments to these interface properties? Here's a good example: https://github.com/linode/manager/blob/develop/packages/api-v4/src/images/types.ts#L25-L115

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +}));
If this is a new file, I would actually use `styled` instead of `makeStyles`.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  }, []);
Do we need dependencies here?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    if (props.savePref) {
Deconstruct all props at top of component please

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    []
Same here about dependency array?

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          <div
Let's avoid `divs` and use `Box`, `Stack`, or `Grid` where it makes sense.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +              <Typography className={classes.title}>
Turn this into a styled component or use `sx` prop.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +                  0 && (
```suggestion
              {props.availableMetrics?.available_aggregate_functions?.length > 0 && (
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +              zoomIn={widget?.size == 12 ? true : false}
```suggestion
              zoomIn={widget?.size === 12}
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +  availableAggregateFunctions: Array<string>;
```suggestion
  availableAggregateFunctions: string[];
```

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +    const available_aggregate_func = props.availableAggregateFunctions?.map(
What's with the transition to snakeCase in this file? Please camelCase these and you may not need the nullish operator for `availableAggregateFunctions` since it's required, but thats ok.

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +    }
```suggestion
    const defaultAggregateFunc = availableAggregateFuncOptions.find(
      (option) => option.label === defaultAggregateFunction
    ) || availableAggregateFuncOptions[0];

    const defaultAggUnavailable = !availableAggregateFunctions.includes(defaultAggregateFunction || '');
```
This is cleaner granted that you fix the snakeCase

2024-07-16 19:53 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +        }}
Update `div`

2024-07-17 06:38 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/dashboards.ts
> +        `${API_ROOT}/monitor/dashboards/${encodeURIComponent(dashboardId!)}`
updated the logic

2024-07-17 06:40 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/services.ts
> +    setURL(`${API_ROOT}/monitor/services/${serviceType}/metric-definitions`),
done

2024-07-17 06:45 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/types.ts
> +  available_aggregate_functions: Array<string>;
done

2024-07-17 06:47 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    } as JWETokenPayLoad;
done

2024-07-17 07:03 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    const graphProp: CloudPulseWidgetProperties = {} as CloudPulseWidgetProperties;
modified

2024-07-17 07:14 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  };
updated

2024-07-17 07:18 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    props.savePref
done

2024-07-17 07:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard && dashboard.service_type ? true : false,
done

2024-07-17 07:36 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard.service_type : undefined!,
done

2024-07-17 07:39 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard!.service_type : undefined!,
done

2024-07-17 07:39 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard && dashboard!.service_type !== undefined ? true : false
done

2024-07-17 07:42 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    resources && dashboard ? true : false
updated

2024-07-17 07:42 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    dashboard ? dashboard.service_type! : undefined!,
done

2024-07-17 07:46 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  }
mistakenly wrong condition added, it should be checking error instead of loading. Updated

2024-07-17 07:49 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +        <StyledPlaceholder icon={CloudPulseIcon} subtitle={subtitle} title="" />
yes title is required field

2024-07-17 07:55 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    flex: 'auto',
removed, not required

2024-07-17 07:59 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +          <div style={{ width: '100%' }}>
updated

2024-07-17 08:00 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +      />
Placeholder will be added in the next PR when logic to render components conditionally will be added.

2024-07-17 08:04 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +        <Grid sx={{ marginLeft: -4, marginRight: 3 }}>
not necessary, but since this PR is large that is why will fix the styling for global filters in the next PR after this.

2024-07-17 08:04 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +    color: 'green',
done

2024-07-17 08:16 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +
thanks for simplified suggestion

2024-07-17 08:23 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +  return nonFormattedString;
done

2024-07-17 08:28 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const removeObjectReference = (object: any) => {
thanks, done

2024-07-17 08:32 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +}));
no longer in use, updated it

2024-07-17 08:34 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  }, []);
no dependencies needed, empty dependency list is added with useCallBack to avoid re-creation of function on re-rendering

2024-07-17 08:45 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    if (props.savePref) {
done

2024-07-17 08:46 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    []
no dependencies needed, empty dependency list is added with useCallBack to avoid re-creation of function on re-rendering

2024-07-17 08:46 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          <div
done

2024-07-17 08:47 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +              <Typography className={classes.title}>
no longer needed

2024-07-17 08:53 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +                  0 && (
updated

2024-07-17 08:53 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +              zoomIn={widget?.size == 12 ? true : false}
done

2024-07-17 08:54 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +  availableAggregateFunctions: Array<string>;
done

2024-07-17 09:34 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +    const available_aggregate_func = props.availableAggregateFunctions?.map(
updated, thanks for pointing it

2024-07-17 09:39 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +    }
done

2024-07-17 09:52 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +      <Paper style={{ height: '100%' }}>
updated

2024-07-17 10:41 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +}
thanks

2024-07-18 20:40 UTC, hana-linode requested changes

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +  const { isLoading } = useLoadUserPreferences();
Why do we have a wrapper function when we can just use the query directly?

```suggestion
  const { isLoading } = usePreferences();
```

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const removeObjectReference = <T>(object: T): T | null => {
This function name doesn't make sense as it's making a copy, not removing anything

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +  }
Since we're returning early we can unnest these ifs

```suggestion
  if (interval.endsWith('s')) {
    return Number(interval.slice(0, -1));
  }
  if (interval.endsWith('m')) {
    return Number(interval.slice(0, -1)) * 60;
  }
  if (interval.endsWith('h')) {
    return Number(interval.slice(0, -1)) * 3600;
  }
  if (interval.endsWith('d')) {
    return Number(interval.slice(0, -1)) * 86400;
  }
```

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +          <p style={{ color: 'rgb(210 165 28)', fontSize: 'smaller' }}>
We should not be making up new colors. Let's use the colors we already have like `theme.color.orange`

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +    const newDashboard: Dashboard = removeObjectReference(dashboard)!;
Why are we maintaining a copy?

2024-07-18 20:40 UTC, hana-linode commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +            return <React.Fragment key={index}></React.Fragment>;
Do we need this empty fragment? Also, React keys should be more unique and not index

2024-07-19 07:18 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/services.ts
> +// import { API_ROOT } from '../constants';
done

2024-07-19 07:44 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +  const setPrefferedWidgetPlan = (widgetObj: Widgets) => {
done, thanks

2024-07-19 07:44 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +  const { isLoading } = useLoadUserPreferences();
done, thanks

2024-07-19 07:45 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +  }
updated, thanks

2024-07-19 07:56 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +      setPrefferedWidgetPlan(graphProp.widget);
updated

2024-07-19 07:57 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +          <p style={{ color: 'rgb(210 165 28)', fontSize: 'smaller' }}>
updated

2024-07-19 08:01 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +            return <React.Fragment key={index}></React.Fragment>;
no, it is not required, removed it.

2024-07-19 08:05 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +  const { isLoading } = useLoadUserPreferences();
We are using a separate utils file to maintain the preferences retrieve & update logics. There we are also maintaining a copy of fetched data that we are using in different components to fetch preferences instead of calling query in every component.

2024-07-19 08:11 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const removeObjectReference = <T>(object: T): T | null => {
renamed.

2024-07-22 12:54 UTC, jaalah-akamai approved these changes

2024-07-22 14:25 UTC, hana-linode commented
Please address the failing unit tests in a follow up PR

2024-07-22 14:26 UTC, hana-linode approved these changes

2024-07-22 16:53 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/services.ts
> +  token: (key: string, serviceType: string | undefined) => ({
What is `key` for? Because it is not passed to `getJWEToken` I have doubts that it is necessary.

2024-07-22 16:53 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/services.ts
> +    contextQueries: {
Does this need to be in `contextQueries`?

2024-07-22 16:53 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/dashboards.ts
> +  dashboardById: (dashboardId: number, key: boolean | undefined) => ({
What is `key`? If it is not passed to `getDashboardById` it probably shouldn't exist

2024-07-22 16:53 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
>  let timerId: ReturnType<typeof setTimeout>;
I still think `usePreferences` and `useMutatePreferences` should be used directly. We shouldn't be storing preferences and mutation functions as global variables.

2024-07-23 12:14 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/services.ts
> +    contextQueries: {
removed

2024-07-23 12:16 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/dashboards.ts
> +  dashboardById: (dashboardId: number, key: boolean | undefined) => ({
remove, not required.

2024-07-23 12:19 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
>  let timerId: ReturnType<typeof setTimeout>;
But we are using preferences fetch & update in each component and instead of duplicating same logic to every component we can have them separately in a file. And by keeping the preference data in the variable, we can use the updated data if some dependent component needs it otherwise we have to do network call everytime to fetch it

2024-07-23 13:27 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
>  let timerId: ReturnType<typeof setTimeout>;
There is no need to keep preference data in a variable. React Query has a cache that updates optimistically. 

A simple React Hook that wraps our existing preference tooling would be the most straightforward solution. 

This is a simplified example of what I'm thinking:
```typescript
const useACLPPreferences = () => {
  const { data: preferences } = usePreferences();

  const { mutateAsync: updatePreferences } = useMutatePreferences();

  const updateCloudPulsePreference = (updatedData: AclpConfig) => {
    updatePreferences({ aclpPreference: updatedData });
  };

  return {
    preferences: preferences?.aclpPreference,
    updateCloudPulsePreference,
  };
};
```

Currently, we don't debounce, but I don't think CloudPulse should be incharge of implementing debouncing of user preferences. We can make that a global change if needed in the future.

2024-07-23 13:38 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
>  let timerId: ReturnType<typeof setTimeout>;
Ok, we'll update those in upcoming PRs as this one is already grown big and we have more features to push urgently

2024-07-23 15:57 UTC, merged