refactor: [M3-6901, M3-6914] - Replace Select with Autocomplete in: kubernetes
linode/manager pull request #10673
Opened 2024-07-11 15:09 UTC by pmakode-akamai

## Description 📝
We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries.

## Changes  🔄
- Replaced `Select` with Autocomplete in `CreateCluster` component. 
- The `Item` type previously imported from `EnhancedSelect/Select` has been added to `Autocomplete/Autocomplete`
    - It simplifies imports and improves code maintainability.
- Added `disableClearable` prop condition to `Autocomplete` to prevent uncontrolled behavior with an initial empty value.

## Target release date 🗓️
22nd July, 2024

## How to test 🧪

### Verification steps
(How to verify changes)
- Navigate to http://localhost:3000/kubernetes/create 
- Verify 'Kubernetes Version' dropdown functionality remains unchanged when using `Autocomplete`. 
- Verify that the `disableClearable` prop condition is correctly applied to `Autocomplete` to prevent uncontrolled behavior when the initial value is empty.

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-07-11 21:03 UTC, dwiley-akamai approved these changes
`Kubernetes Version` dropdown functioning as expected ✅
Cannot clear `Kubernetes Version` dropdown ✅

I observed this console error:

![Screenshot 2024-07-11 at 4 50 08 PM](https://github.com/linode/manager/assets/114682940/f577b9c2-9e1e-43d7-90b0-0a95cd1590a0)

To get rid of that, you should be able to add something like 

```
isOptionEqualToValue={(option, value) => option.value === value.value}
```

as a prop when `Autocomplete` is used in `CreateCluster.tsx`. See [this comment](https://github.com/linode/manager/pull/10089#discussion_r1465562047) for more context, and you can search the codebase for other instances of `isOptionEqualToValue` for examples

2024-07-15 05:16 UTC, pmakode-akamai commented
Addressed this console warning in the commit 0cbf020fae4843ee122a73a3e96ed697a39a7851

2024-07-15 05:21 UTC, pmakode-akamai commented on packages/manager/.changeset/pr-10673-tech-stories-1720710990405.md
> +Replace Select with Autocomplete in: kubernetes ([#10673](https://github.com/linode/manager/pull/10673))
Addressed the console warning issue in the commit 0cbf020fae4843ee122a73a3e96ed697a39a7851

2024-07-15 12:56 UTC, bnussman-akamai requested changes

2024-07-15 12:56 UTC, bnussman-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +}
We don't want to keep this type around. It is not very type-safe and MUI's autocomplete allows for the type to be inferred. 

```suggestion
```

2024-07-15 12:56 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +            value={version ?? null}
We should drive `value` from our array of `versions`

```suggestion
            value={versions.find((v) => v.value === version) ?? null}
```

By doing this we can remove `isOptionEqualToValue`.

2024-07-15 12:56 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +            onChange={(_, selected: Item<string>) => {
We don't need an explicit type here. The type of `selected` will be inferred based on the given `options` and `value`

```suggestion
            onChange={(_, selected) => {
```

2024-07-15 14:15 UTC, pmakode-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +}
Removed this Item type and keeping version of <string | undefined> instead of <Item<string> | undefined>

2024-07-15 19:42 UTC, bnussman-akamai approved these changes

2024-07-15 19:42 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +    const k8s_version = version ?? undefined;
This line can be removed `version` is already of type `string | undefined`

2024-07-16 08:48 UTC, merged