upcoming: [DI-19818] - Added a filter builder component for ACLP that builds the filters per service type
linode/manager pull request #10718
Opened 2024-07-26 09:44 UTC by venkymano

## Description 📝
The CloudPulseDashboardFilterBuilder component builds the required mandatory global filters from a JSON config based on service types like linode, dbass etc.,

## Changes  🔄
List any change relevant to the reviewer.
- Added a new CloudPulseDashboardFilterBuilder that will build the global filters based on FilterConfig.ts per service type
- Added a new CloudPulseComponentRenderer component that builds the react element based on filterKey
- Added UT's for both of the component
- For now, I have integrated this with existing GlobalFilters.tsx as a test purpose, this will be fully revamped in upcoming PR's

## Target release date 🗓️
2nd August 2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 
![Screenshot 2024-07-26 at 3 01 29 PM](https://github.com/user-attachments/assets/ae78a2e4-cd23-43c5-8337-397f33b0e764)
 | 
![Screenshot 2024-07-26 at 3 01 45 PM](https://github.com/user-attachments/assets/aaac4212-0db0-47cd-bbaa-80d980d3560f)
 | 
![Screenshot 2024-07-26 at 3 01 21 PM](https://github.com/user-attachments/assets/065cd145-5e1f-45fc-8207-0ba934a37c0d)
 |

## How to test 🧪

1. Enable mock service as some endpoints are not ready to use
2. Go the Monitor Landing Page
3. I have added the filter builder along with existing Global filters which will be  completely revamped with this filter builder soon.
4. Select a Dashboard from dashboard selection dropdown
5. You will be able to see the filters build below the existing global filters

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-07-26 10:09 UTC, nikhagra approved these changes
looks good

2024-07-26 20:42 UTC, jaalah-akamai reviewed
Looks good overall, just some cleanup 👍

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    for (const filter of filters) {
Nit: We could potentially save some iterations here by using `.find`:
```
const filter = filters.find(
  (filter) =>
    filter?.configuration.filterKey === filterKey &&
    filter.configuration.dependency
);

if (filter) {
  // ... other stuff
}
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +   * we need to dashboard here, as we can infer serviceType and other required properties from it.
```suggestion
   * We need the dashboard here, as we can infer serviceType and other required properties from it.
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    const getProps = (config: CloudPulseServiceTypeFilters) => {
Do we think this should be wrapped in a `useCallback`?

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        </Grid>
We should consider wrapping the <Grid> component with the showFilter condition to handle cases where FILTER_CONFIG.get is undefined. Additionally, I recommend moving this logic outside of the JSX for better readability. It might also be beneficial to memoize these computations, as there are several seemingly expensive operations in this file.

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    !newProps.isServiceAnalyticsIntegration
```suggestion
    oldProps.dashboard?.id === newProps.dashboard?.id &&
    !newProps.isServiceAnalyticsIntegration
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +        : false,
```suggestion
        ? !props.disabled 
        : Boolean(props.region && props.resourceType);
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        )}
```suggestion
        <Button onClick={toggleShowFilter} sx={{ marginTop: 2 }}>
          {showFilter ? <KeyboardArrowDownIcon /> : <KeyboardArrowRightIcon />}
          <Typography>Filters</Typography>
        </Button>
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +                    config.configuration.neededInServicePage === true)
```suggestion
                  (!isServiceAnalyticsIntegration && !config.configuration.neededInServicePage) ||
                  (isServiceAnalyticsIntegration && config.configuration.neededInServicePage)
```

2024-07-26 20:42 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    const [, setDependentFilters] = React.useState<{
Nit: Our convention is to destructure the props `const { ... } = props;`

2024-07-29 09:23 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +        : false,
done

2024-07-29 09:23 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    !newProps.isServiceAnalyticsIntegration
done

2024-07-29 09:24 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        </Grid>
I have moved the part where we render the component after getting filters into a new function and handled the undefined error case of filters as well

2024-07-29 09:25 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        )}
done

2024-07-29 09:25 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    const getProps = (config: CloudPulseServiceTypeFilters) => {
Thanks, I have wrapped this  method as well most of the methods in this component around callback now, and everything works fine

2024-07-29 09:26 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    const [, setDependentFilters] = React.useState<{
destructured and used

2024-07-29 09:26 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +   * we need to dashboard here, as we can infer serviceType and other required properties from it.
done

2024-07-29 09:26 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    for (const filter of filters) {
done

2024-07-29 15:32 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  xFilter?: { [key: string]: any } | undefined;
Seeing a ton of `any`s in this PR. If this is going to use standard API filter, we have a type for API filtering called `Filter`.

2024-07-29 17:03 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  xFilter?: { [key: string]: any } | undefined;
Hi @bnussman-akamai , I removed most of the any's in the PR now as I could, I also build a logic to build and pass xFilter here as Filter object as per your suggestion

2024-07-31 16:24 UTC, jaalah-akamai commented
@bnussman-akamai and @carrillo-erik  this should be good for another pass 👍

2024-08-01 14:51 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +      <Grid item key={'region'} sx={{ marginLeft: 2 }} xs>
Why just a random `key`?

2024-08-01 14:51 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        ></ErrorState>
If there are no children, can we use a self-closing tag?

```suggestion
        <ErrorState
          CustomIcon={InfoIcon}
          CustomIconStyles={{ height: '10%', width: '10%' }}
          errorText={'Please pass valid dashboard to render the filters'}
        />
```

2024-08-01 14:51 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/models.ts
Would be nice to see some jsdoc style comments explaining what there types and properties mean

2024-08-01 14:51 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +      ></CloudPulseDashboardFilterBuilder>
Can we do this because there are no children?

```suggestion
      <CloudPulseDashboardFilterBuilder // this simple integration is for test purpose, the functionality integration will be done in upcoming PR by driving all filters through filterbuilder
        dashboard={selectedDashboard!}
        emitFilterChange={() => {}}
        isServiceAnalyticsIntegration={false}
      />
```

2024-08-01 15:00 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +  serviceType: 'dbass',
```suggestion
  serviceType: 'dbaas',
```
(See also the comment suggesting changing the type for `serviceType` to avoid these types of mistakes)

2024-08-01 15:00 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +  ['dbass', DBASS_CONFIG],
```suggestion
  ['dbaas', DBAAS_CONFIG],
```

2024-08-01 15:05 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +    });
```suggestion
  });
  
  it('it should render provided resource filter in props', () => {
    const resourceProps = linodeFilterConfig?.filters.find(
      (filter) => filter.configuration.filterKey == 'resource_id'
    );

    const mockDashboard = {
      created: new Date().toDateString(),
      id: 1,
      label: DASHBOARD,
      service_type: 'linode',
      time_duration: { unit: 'min', value: 30 },
      updated: new Date().toDateString(),
      widgets: [],
    };

    const { getByPlaceholderText } = renderWithTheme(
      <Grid item key={'resources'} sx={{ marginLeft: 2 }} xs>
        {RenderComponent({
          componentKey: 'resource_id',
          componentProps: {
            ...getResourcesProperties(
              resourceProps!,
              vi.fn(),
              mockDashboard,
              false,
              { region: 'us-east' }
            ),
          },
        })}
      </Grid>
    );

    expect(getByPlaceholderText('Select Resources')).toBeDefined();
  });
```

2024-08-01 15:24 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +};
@jdamore-linode , the UT's should be covered as a part of component level UT's, so we didn't explicitly added here

2024-08-01 15:24 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> +  serviceType: string;
As of now, we have linode and dbaas, and it will keep growing, so went for a string type

2024-08-01 15:24 UTC, VenkatMano commented on packages/manager/.changeset/pr-10718-upcoming-features-1721988074945.md
> +The CloudPulseDashboardFilterBuilder component builds the required mandatory global filters from a JSON config based on service types like linode, dbass etc., ([#10718](https://github.com/linode/mana
changed

2024-08-01 15:25 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +  serviceType: 'dbass',
changed the name

2024-08-01 15:25 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +  ['dbass', DBASS_CONFIG],
changed the name

2024-08-01 15:25 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +    });
Changed

2024-08-01 15:26 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +      <Grid item key={'region'} sx={{ marginLeft: 2 }} xs>
removed, we don't need

2024-08-01 15:26 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +      ></CloudPulseDashboardFilterBuilder>
done

2024-08-01 15:36 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> +  serviceType: string;
If we need to update the code each time a new type is added anyway (e.g. `FILTER_CONFIG` const in `FilterConfig.ts`) then updating this type each time as well is trivial. Using a string literal type will catch typos that could cause real bugs for our customers.

2024-08-01 15:38 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +  RESOURCES,
This values is being imported but not being consumed, can we please remove it.

2024-08-01 15:41 UTC, carrillo-erik requested changes

2024-08-01 15:41 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +import type { Props } from './CloudPulseTimeRangeSelect';
Looks like you're trying to import this type but you did not export it in the corresponding file.

2024-08-01 15:43 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +      <Grid item key={'region'} sx={{ marginLeft: 2 }} xs>
removed

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        ></ErrorState>
done

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +      ></CloudPulseDashboardFilterBuilder>
done

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +      ></CloudPulseDashboardFilterBuilder>
done

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        ></ErrorState>
done

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +};
The util functions must be covered by component level UT's

2024-08-01 15:44 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +export const DBASS_CONFIG: CloudPulseServiceTypeFilterMap = {
done

2024-08-01 15:45 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> +  serviceType: string;
Changed to supported linode | dbaas

2024-08-01 15:45 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +  serviceType: 'dbass',
changed

2024-08-01 15:45 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +  RESOURCES,
removed

2024-08-01 15:47 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +import type { Props } from './CloudPulseTimeRangeSelect';
missed to commit that file, pushed the export changes

2024-08-01 17:33 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +};
That doesn't seem sufficient -- can you explain how the tests for `CloudPulseDashboardFilterBuilder` and `CloudPulseComponentRenderer` confirms that `checkIfWeNeedToDisableFilterByFilterKey` behaves correctly in case I'm missing something?

We strive to unit test our utilities and I'd be happy to share numerous examples if it'd be of any assistance.

2024-08-02 12:37 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +};
@jdamore-linode , I added the UT's for the filterbuilder and also documented the util

2024-08-02 19:40 UTC, jdamore-linode approved these changes

2024-08-02 21:12 UTC, carrillo-erik requested changes
The code looks much better, we appreciate you making the effort to meet the project's coding standards. The UI does require some attention, in particular the tablet and mobile views do not scale appropriately. Even without comparing to the mock ups, one can easily notice visual regressions. For example, each of the select components are different widths and the `Filters` dropdown is floating right for no apparent reason. Please refer to images below:

**Mobile View:**
![cp-mobile-view](https://github.com/user-attachments/assets/5804f741-2e19-435e-a27b-ad4c55f28858)

**Tablet View:**
![cp-tablet-view](https://github.com/user-attachments/assets/8ed3c9ed-dd5d-4880-9927-97f2cc8500b2)

**Desktop View:**
![cp-desktop-view](https://github.com/user-attachments/assets/bb279c3b-03d0-4221-955e-31a973d3578a)

2024-08-05 04:50 UTC, venkymano commented
Hi @carrillo-erik ,

This is just a test and functionality integration of the filterbuilder component in GlobalFilters.tsx, we have changes in our mock ups , that we we will kill some of the existing filters itself in the GlobalFilters.tsx component and fully drive the filters through our newly designed filter builder component like below screenshot

![image](https://github.com/user-attachments/assets/2bf42e6d-076b-4d3a-bf89-8ee2d1471ad5)

Once those changes comes in the upcoming PR's, the style issues will be corrected along with our updated mock up styles and we will be adding respective screenshots for mobile, tablet and desktop views. Hope this solves the case

2024-08-05 15:30 UTC, venkymano commented
Hi @carrillo-erik , Can this be merged now?, since we will create additional PR with the changes requested as per the above attached screenshot (latest mockups)

2024-08-05 15:41 UTC, jdamore-linode commented
@venkymano Can you follow up with us in Slack with a link to the ticket whose PR will contain these UI fixes?

The issues @carrillo-erik pointed out are pretty severe so we'd just like to ensure that the requirements to address this are captured and won't be backlogged since this really isn't in a state to release to customers as-is.

2024-08-05 15:49 UTC, venkymano commented
@jdamore-linode , https://track.akamai.com/jira/browse/DI-19816 -  As stated in the previous comments, we already have the CSS fix ready in our local integrated branch according to our latest mockups, but if we introduce that this PR will become a big PR, hence broken down the functionalities and created a small PR.

2024-08-05 16:11 UTC, abailly-akamai requested changes
I only scratch the surface but this PR needs a lot of work to be able to be merged.

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +import type { Props } from './CloudPulseTimeRangeSelect';
It can't be just named `Props` - name your interfaces/type declarations better when exported so they are easily recognizable.

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +  return <Box></Box>;
?

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        if (config.configuration.filterKey == REGION) {
Please always use strict equality

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +          CustomIconStyles={{ height: '10%', width: '10%' }}
I don't think you'd ever want to set width/height in percentages

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +          errorText={'Please pass valid dashboard to render the filters'}
Do you have copy validation on those messages?

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    }, [resources, props.region, props.resourceType, props.xFilter]);
destructure your props

2024-08-05 16:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +
If you have more than 2 arguments in your function, please do not make them ordered. Use named arguments and write interfaces for their types, which can be shared within those utils.

2024-08-05 16:30 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +        dashboard={selectedDashboard!}
@abailly-akamai , Some missing thing in the comments, This integration remains the same, in the upcoming changes as well, we will remove the existing filters like Region and Resource selection from global filters and drive the full integration, whereas this remains the same..

2024-08-06 04:26 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    xFilter: buildXFilter(config, dependentFilters),
destructed config and used

2024-08-06 04:27 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +};
made the serviceType and filters readonly in the model.ts, since we will use this only for configuration purposes

2024-08-06 04:27 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> + */
made the comments like JSdocs comments

2024-08-06 04:28 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        if (config.configuration.filterKey == REGION) {
done

2024-08-06 04:28 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    }, [resources, props.region, props.resourceType, props.xFilter]);
done

2024-08-06 04:29 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +  return <Box></Box>;
We can return null in this case, I have done the changes now

2024-08-06 04:57 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    savePreferences: !isServiceAnalyticsIntegration,
@abailly-akamai , I have created a interface called CloudPulseFilterProperties and used in the functions and kept a max of two arguments

2024-08-06 04:58 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +
@abailly-akamai , I have created a interface called CloudPulseFilterProperties that has common properties and used in the functions and kept a max of two arguments

2024-08-06 05:00 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +          errorText={'Please pass valid dashboard to render the filters'}
We have written UT's to validate the error message

2024-08-06 05:04 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +          CustomIconStyles={{ height: '10%', width: '10%' }}
removed percentages

2024-08-07 13:23 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +        dashboard={selectedDashboard!}
@abailly-akamai , we have fixed and completed the proper integration of builder filter now, please check

2024-08-07 13:27 UTC, venkymano commented
> The code looks much better, we appreciate you making the effort to meet the project's coding standards. The UI does require some attention, in particular the tablet and mobile views do not scale appropriately. Even without comparing to the mock ups, one can easily notice visual regressions. For example, each of the select components are different widths and the `Filters` dropdown is floating right for no apparent reason. Please refer to images below:
> 
> **Mobile View:** ![cp-mobile-view](https://private-user-images.githubusercontent.com/119514965/354725074-5804f741-2e19-435e-a27b-ad4c55f28858.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzc0NTEsIm5iZiI6MTcyMzAzNzE1MSwicGF0aCI6Ii8xMTk1MTQ5NjUvMzU0NzI1MDc0LTU4MDRmNzQxLTJlMTktNDM1ZS1hMjdiLWFkNGM1NWYyODg1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTFkNDJiMmIwMGJmNGY0MjgwZTE4ZjA2MDEzZGMyOGRkNjFjNDUzODM2ZmU4OWRjZjYwNGMzMDk5YjYzNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vLa-yLy09hakQALxNz0fdxrdXnGpsQGYxuIGddlP40s)
> 
> **Tablet View:** ![cp-tablet-view](https://private-user-images.githubusercontent.com/119514965/354725051-8ed3c9ed-dd5d-4880-9927-97f2cc8500b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzc0NTEsIm5iZiI6MTcyMzAzNzE1MSwicGF0aCI6Ii8xMTk1MTQ5NjUvMzU0NzI1MDUxLThlZDNjOWVkLWRkNWQtNDg4MC05OTI3LTk3ZjJjYzg1MDBiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjcxMjQyNDlhOGIxYzRjM2E5YjYxMzhjZGExNzdiNTE1NDIxNzY3ZWVkYTM3ZjJhZmUzNjYyNzdlZWI0NTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VJ_OYww8dhh6OdsxLGtTnwftJOQRPrhHc77fX8PFvjU)
> 
> **Desktop View:** ![cp-desktop-view](https://private-user-images.githubusercontent.com/119514965/354725008-bb279c3b-03d0-4221-955e-31a973d3578a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzc0NTEsIm5iZiI6MTcyMzAzNzE1MSwicGF0aCI6Ii8xMTk1MTQ5NjUvMzU0NzI1MDA4LWJiMjc5YzNiLTAzZDAtNDIyMS05NTVlLTMxYTk3M2QzNTc4YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmYwNGY4NTM2ZGQ4ZDAxOWY3YjhlYTllNjE1NjU0ZmJiZTJlNDRjNzExNmEwMzBlZjg3Zjk3YTY4ZmZkNTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xftVUQScsEWzIE2ojGF_VGZ16z_g7MGT492rkxO9Q2s)

@carrillo-erik , we have pushed the changes which had fixed this, I have added the screenshots for different devices at the top

2024-08-07 13:59 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  ): undefined | void;
```suggestion
  ):  void;
```
undefined is not required as it is not going to return anything

2024-08-07 13:59 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  handleTimeDurationChange(timeDuration: TimeDuration): undefined | void;
```suggestion
  handleDashboardChange(dashboard: Dashboard | undefined): void;
  handleTimeDurationChange(timeDuration: TimeDuration): void;
```

2024-08-07 13:59 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +  if (dashboard && dashboard.service_type) {
```suggestion
  if (dashboard?.service_type) {
```

2024-08-07 16:06 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  ): undefined | void;
done

2024-08-07 16:07 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  handleTimeDurationChange(timeDuration: TimeDuration): undefined | void;
done

2024-08-07 16:07 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +  if (dashboard && dashboard.service_type) {
done

2024-08-08 01:42 UTC, abailly-akamai requested changes
Thanks for addressing comments and improving best practices. In general the code quality is still pretty rough for having been reviewed several times by your team and ours. Notably, when pointing at a code issue, I would expect the author to check the PR for similar defects, not just addressed the ones we pointed at. If not, the back and forth 
takes too much time out of everyone. There's frankly a lot more to pick at than I reviewed, but tried to only address the biggest concerns.

Apart from code review comments, please address the issues below.

You're updating state during re-render, which points to issues in your lifecycle methods.  This needs to be addressed before merging

![Screenshot 2024-08-08 at 09 32 20](https://github.com/user-attachments/assets/d4f74e72-9f8a-4cd9-8ef0-afb2cb6e4751)

---

UI looks improved minus a few issues:
![Screenshot 2024-08-08 at 09 43 09](https://github.com/user-attachments/assets/4743f223-a2ba-4885-a4d9-d962b3728f86)

![Screenshot 2024-08-08 at 10 25 22](https://github.com/user-attachments/assets/d4d1fe7e-4fd7-4806-b609-f78e4cda6daf)

![Screenshot 2024-08-08 at 10 26 27](https://github.com/user-attachments/assets/8c9ba275-24a0-4d4e-b579-9075e2d5ac54)

![Screenshot 2024-08-08 at 10 36 38](https://github.com/user-attachments/assets/7c9d04ef-883b-421e-be91-eb50a40cc9d0)

These rendering flickers are problematic and point to issues with the code, perhaps when updating preferences

https://github.com/user-attachments/assets/565f0566-3fad-464e-9d12-5d3e835e431f

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> +   * @type {string}
You don't really need to add the JSDoc `@type` here since we are in typescript. Those are redundant

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +    };
Is there no factory for a dashboard? There should be one. This isn't typed at all.

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  region?: string | undefined;
either 

`region: string | undefined;`
or 
`region?: string`

not both

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +      disabled != undefined ? !disabled : Boolean(region && resourceType),
strict equality please

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
This is just strange. why not handling just one required prop?? You can just pass a single region in an array. This just complicates code.

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  );
this is a bit smelly. may be trouble in the long term.

You should optimize this to future proof implementation

Pseudo/Kinda functional code

```Typescript
const compareProps = (
  prevProps: CloudPulseResourcesSelectProps,
  nextProps: CloudPulseResourcesSelectProps
): boolean => {
  const keysToCompare: (keyof CloudPulseResourcesSelectProps)[] = [
    'region',
    'resourceType',
    'disabled',
    'placeholder',
    'savePreferences'
  ];

  for (const key of keysToCompare) {
    if (prevProps[key] !== nextProps[key]) {
      return false;
    }
  }

  // Deep comparison for xFilter
  if (!deepEqual(prevProps.xFilter, nextProps.xFilter)) {
    return false;
  }

  // Ignore function props in comparison
  return true;
};
```

It's easier to add or remove properties to compare as the component evolves. It short-circuits on the first difference found, potentially saving unnecessary comparisons.
Also, using `keyof CloudPulseResourcesSelectProps` ensures type safety if prop names change and still uses deepEqual for the xFilter prop, which might be an object.

Test it well, tho, it may need tweaking

2024-08-08 01:42 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +        label=""
This is not accessible without a label or aria equivalent

2024-08-08 02:01 UTC, abailly-akamai commented
@venkymano considering the quality of the PR, and looking at your changelog, we need smaller PRs in the future and big PRs will be asked to be broken down:

- Added a new CloudPulseDashboardFilterBuilder that will build the global filters based on FilterConfig.ts per service type
- Added a new CloudPulseComponentRenderer component that builds the react element based on filterKey
- Complete integration of the CloudPulseDashboardFilterBuilder in the GlobalFilters.tsx
- Added logic in the CloudPulseDashboardLanding component to pass the filters selected to the dashboard component
- Changes for moving CloudPulseTimeRangeSelect from select to Autocomplete
- CSS changes making the filters compatible with different screens like desktop, tablet and mobile.

almost all of those changes should be its own PR.

2024-08-08 02:02 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +        if (config.configuration.filterKey == REGION) {
you need to check through the whole PR when pointed at a code consistency issue, not just what the reviewer points at

2024-08-08 02:03 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +          errorText={'Please pass valid dashboard to render the filters'}
I meant copy validation from the product team

2024-08-08 08:58 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +  );
Thanks for the suggestion, Since we update the preference on every filter change and the preference update will make the cloudpulsedashboard to re-render, it is better to use with callback functionality itself

2024-08-08 09:03 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
> +      config: resourceSelectionConfig!,
@abailly-akamai , Thanks for the suggestion, if you see the line number 90 we check

`expect(resourceSelectionConfig).toBeDefined();`

So if the resourceSelectionConfig is really undefined , it will not even reach the below lines and test case fails, since we made sure that resourceSelectionConfig is never undefined here, added a non-nullish assertion. Please Let me know if we still need this to be handled

2024-08-08 09:03 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/models.ts
> +   * @type {string}
This seems redundant, I have removed those

2024-08-08 09:04 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  region?: string | undefined;
This is really great suggestion, i have made use region?: string

2024-08-08 09:06 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +  );
Since we compare only region and resourceType that is required for re rendering, I updated the code with the suggested function for props region, resourceType and xFilter alone and it works fine

2024-08-08 09:09 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +        duration={timeDuration!}
Thanks, we don't need for dashboardId, but if you see the if condition above the return statement, we are already checking for timeDuration is defined or not in the function checkIfAllMandatoryFiltersAreSelected, if this is false, we will not reach the statement, so we are sure here timeDuration is not undefined, but I have added one more check and removed these.

2024-08-08 09:10 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +      disabled != undefined ? !disabled : Boolean(region && resourceType),
done, checked elsewhere as well for the files changed in the PR

2024-08-08 09:12 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
The instances fetch API of linode returns region where as instances fetch API of aclb returns regions, to achieve this we need to introduce intercept logic that will take care of converting to one region, that is also a complex thing, so we are maintaining it like this.

2024-08-08 09:17 UTC, venkymano commented
@abailly-akamai 

Here are some style issue fixes according to the screenshot we made

1. Fixed the console issue
2. Fixed the alignment issue of manual refresh button
3. Removed the border in the globalfilters, since we don't need it.
4. Made the error clear after selecting some values

2024-08-08 11:41 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
> +    };
Thanks, I created a simple dashboard factory and reused it in the test files in this PR, we will enhance the factory based on requirements moving forward

2024-08-08 12:37 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +};
done

2024-08-08 13:40 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +        duration={timeDuration!}
@venkymano That may be correct for the code in its current state, but using the non-nullish assertion here creates a maintenance risk where changes to the code (e.g. changing or removing `checkIfAllMandatoryFiltersAreSelected`) could result in `timeDuration` being `null`, and TypeScript won't catch it thanks to the non-nullish assertion.

Things like non-nullish assertions and `any` should be treated as escape hatches to circumvent TypeScript's safety checks when it is absolutely necessary _only_. I don't think any of the non-nullish assertions that @abailly-akamai pointed out meet that bar.

2024-08-08 13:49 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +        duration={timeDuration!}
@jdamore-linode , i have fixed these now, removed nonnullish assertions

2024-08-08 14:46 UTC, abailly-akamai requested changes

2024-08-08 14:46 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
> +};
quite partially...

2024-08-08 14:46 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +        label=""
@venkymano you'd think it's required for a reason 😄 ? Passing an empty string is breaking accessibility and going around the problem. You have to take in consideration users using assistive technology and an input without a label makes identifying an input quite hard to for a screen reader for instance.

In this case, (and all other instances of Autocomplete in CloudPulse), pass a proper label and add `hideLabel` to its `inputProps` to visually hide it but keep it in the markup.

2024-08-08 14:48 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
This does not make sense to me

2024-08-08 14:55 UTC, abailly-akamai commented
@venkymano the rendering flickers as shown here and pointed at in the previous review need to be fixed as well

https://github.com/user-attachments/assets/002341e3-68c0-4076-a395-abdc8d19226e

2024-08-08 15:04 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
@abailly-akamai could you please suggest an alternative to it

2024-08-08 15:11 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
@nikhagra for one, ACLB has been sunsetted, so I doubt you need to support it. 

And if you really need to support multiple regions, then it should be the only prop.

2024-08-08 15:40 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
@abailly-akamai  I understand, but as we are building a configuration based filter & it is not limited only to ACLB or linodes but any service type could be integrated to it and we don't have confirmed information whether all the service types ( existing or will come in future ) that'll be integrated to it will have single region or multiple regions

2024-08-08 16:56 UTC, jaalah-akamai commented
@abailly-akamai I made a few of the changes you requested. The flickering is a comment I mentioned [in previous PRs](https://github.com/linode/manager/pull/10710#issuecomment-2255879162) too. They have a ticket to address this when the endpoints are in. Anything else that needs to be looked at?

2024-08-08 17:10 UTC, nikhagra commented
> @abailly-akamai I made a few of the changes you requested. The flickering is a comment I mentioned [in previous PRs](https://github.com/linode/manager/pull/10710#issuecomment-2255879162) too. They have a ticket to address this when the endpoints are in. Anything else that needs to be looked at?

Thanks @jaalah to fix few styling. Here is the ticket to handle flickering issue. Will take care of it.

https://track.akamai.com/jira/browse/DI-20169

2024-08-08 17:56 UTC, jaalah-akamai commented
@nikhagra Let's resolve the conflict so we can kick off another CI run in preparation to merge 👍

2024-08-08 22:46 UTC, venkymano commented
@jaalah-akamai , I have resolved the conflicts now

2024-08-08 22:52 UTC, jaalah-akamai approved these changes

2024-08-08 22:55 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +        label=""
Should be all set.

2024-08-08 22:58 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
Not to prolong this discussion but an alternative could be something like `regionOrRegions?: string | string[];` and then do some type narrowing where needed. Just something to think about!

2024-08-09 00:39 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>    regions?: string[]; // aclb are associated with multiple regions
@jaalah / @abailly-akamai , since we don't need the regions prop as of now and we have not used in this component, we will enhance the component when we integrate with the service where this use case comes

2024-08-09 04:08 UTC, abailly-akamai approved these changes

2024-08-09 15:53 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
> +const buildComponent = (props: CloudPulseComponentRendererProps) => {
In the future, remember to use PascalCase for component names and aim for named exports over default exports.

2024-08-09 15:53 UTC, carrillo-erik approved these changes

2024-08-09 15:53 UTC, merged