upcoming: [DI-19818] - Added line graph to CloudPulse widgets for different metrics
linode/manager pull request #10710
Opened 2024-07-25 09:49 UTC by nikhagra

## Description 📝
Line graph component is added in cloud pulse widget to showcase data for different metrics.

## Changes  🔄
List any change relevant to the reviewer.
1. CloudPulseLineGraph is added in the cloud pulse widget for metrics
2. LineGraph component is modified for full width legends as it was restricting to 85% width
3. Widget color palette is added for predefined colors in graph
4. Necessary type definitions are added to support metrics data
Note: We are working 

## Target release date 🗓️
2nd August 2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
|![Screenshot 2024-07-25 at 3 17 07 PM](https://github.com/user-attachments/assets/8a2195b1-d29c-4ec1-9534-bbf632db40f2)|![Screenshot 2024-07-25 at 3 05 37 PM](https://github.com/user-attachments/assets/55f1b75c-0fc7-42fc-9c46-67dfc98e4c66)|
|![Screenshot 2024-07-25 at 3 05 44 PM](https://github.com/user-attachments/assets/1e7a4073-a5a1-410f-a6ad-68c213b0c89c)|![Screenshot 2024-07-25 at 3 05 56 PM](https://github.com/user-attachments/assets/f1acfd5e-b626-4975-8584-11ea180d918b)|

## How to test 🧪

1. Enable mock services as some endpoints are not ready to use.
2. Graph will be populated with dummy data so you can see the visualization & tool tips.

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-07-25 13:30 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetColorPalette.ts
> +export const RED = [
Just FYI, these palettes are subject to be updated based on UX suggestions

2024-07-25 13:33 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  }, [status, metricsList]);
Can you check if we followed and fixed problems related to eslint plugin

2024-07-25 13:34 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +      let index = 0;
lets rename this to colorPalatteInfoIndex

2024-07-25 13:35 UTC, VenkatMano commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          {isLoading && !Boolean(error) && <CircleProgress />}
If possible, please add a screenshot for error state as well

2024-07-25 13:39 UTC, VenkatMano commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +      refetchInterval: 6000000,
Please reduce the refetchInterval to 120000 (2 min) instead of 6000000

2024-07-25 13:52 UTC, nikhagra commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +import type {
yes it is being used inside the component

2024-07-25 13:52 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +      let index = 0;
done

2024-07-25 13:53 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +      refetchInterval: 6000000,
done

2024-07-25 14:03 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          {isLoading && !Boolean(error) && <CircleProgress />}
done

2024-07-25 14:05 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  }, [status, metricsList]);
it is giving warning for dependencies which are not required

2024-07-25 15:03 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +        x: Number(element[0]),
You have some data type errors with `element[0]` in this codeblock.

2024-07-25 15:09 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +  if (timeDuration.unit == 'hr') {
Whenever a comparison is made, please use strict equality operator `===`. In this specific case, a `switch` statement could also work.

2024-07-25 15:12 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [data, setData] = React.useState<Array<any>>([]);
Please refrain from using `any`.

2024-07-25 15:12 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [legendRows, setLegendRows] = React.useState<any[]>([]);
Same as above.

2024-07-25 15:19 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [today, setToday] = React.useState<boolean>(false); // Temporarily disabled eslint for this line. Will be removed in future PRs
It appears this has been addressed now, please remove both the disable eslint and explanation comments.

2024-07-25 15:39 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
I'm concerned with the size of this widget component.

2024-07-25 15:40 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  }, [status, metricsList]);
There is a lot of logic going on inside this effect.

2024-07-25 15:42 UTC, carrillo-erik requested changes
Left some initial feedback to be addressed. I'll continue to review but this should give you a starting point. Reach out if you have questions.

2024-07-25 15:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetColorPalette.ts
> +export const RED = [
@nikhagra We have theme colors for the graphs which you can pull from using `theme.graphs.{type}` https://github.com/linode/manager/blob/develop/packages/manager/src/foundations/themes/light.ts#L1473-L1533. I would remove all these since we're moving away from hard-coded colors and transitioning to Design Tokens.

2024-07-25 15:45 UTC, nikhagra commented
> Left some initial feedback to be addressed. I'll continue to review but this should give you a starting point. Reach out if you have questions.

Sure thanks for comments, I'll addressed them and also put bigger logic into a util file and reduce the component size

2024-07-26 05:34 UTC, kmuddapo commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetColorPalette.ts
> +export const RED = [
@jaalah-akamai our ACLP use case here the graph will have dynamic dimensions/lables, so we cant have a static map of colors per lable/dimension. Also we might receive the custom color theme from a  widget config itself.

2024-07-26 09:27 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +        x: Number(element[0]),
updated

2024-07-26 09:28 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +  if (timeDuration.unit == 'hr') {
udpated

2024-07-26 09:28 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [data, setData] = React.useState<Array<any>>([]);
done

2024-07-26 09:28 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [legendRows, setLegendRows] = React.useState<any[]>([]);
done

2024-07-26 09:29 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const [today, setToday] = React.useState<boolean>(false); // Temporarily disabled eslint for this line. Will be removed in future PRs
done

2024-07-26 09:30 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
I've the logical code to a separate utils file. Only component related functionality is there

2024-07-26 12:47 UTC, venkymano approved these changes
LGTM

2024-07-26 14:16 UTC, carrillo-erik requested changes

2024-07-26 14:16 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +        x: Number(element[0]),
Not quite the solution for in this case. The editor can offer you some insight, see message in the screenshot I took.

![ts-datatype-error](https://github.com/user-attachments/assets/451e7938-d3e3-4b48-8a32-4c68d2a83680)

2024-07-26 16:52 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +        x: Number(element[0]),
updated

2024-07-26 19:19 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    );
Nit: Just something to think about, but when functions contain more than 2 params, it may be good to think about turning the function params into an object for better for extensibility and readability. Same goes for the `useCloudPulseMetricsQuery`

2024-07-26 19:19 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +                  : undefined
```suggestion
                status === 'error' ? error?.[0]?.reason || 'Error while rendering widget' : undefined
```

2024-07-26 19:19 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
> +      thisSeries.data.every((thisPoint) => thisPoint[1] === null)
Nit: It just reads easier when you destructure a little
```suggestion
    ({ data: seriesData }) =>
      // If we've padded the data, every y value will be null
      seriesData.length === 0 || seriesData.every(([_, y]) => y === null)
```

2024-07-26 19:19 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +};
Nit: This is an easy thing to turn into a map and then return something like:
```
return timeDurations[label] || { unit: 'min', value: 30 };
```

2024-07-26 19:19 UTC, jaalah-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +    () =>
Something to think about: For all the queries, we've transitioned to using query key factories for better type safety and management. There's lots of PRs to reference, but here's one: https://github.com/linode/manager/pull/10679/files

2024-07-29 13:02 UTC, jaalah-akamai commented
There seems to be a lot of jankiness when you change values for the charts, I'm not sure if that's because we're dealing with mocks or if it's due to multiple re-renderings. It's just something to keep an eye on as development progresses 👍

2024-07-29 13:29 UTC, nikhagra commented on packages/api-v4/src/cloudpulse/types.ts
> +}
forgot to remove the comments

2024-07-29 13:33 UTC, nikhagra commented on packages/manager/src/featureFlags.ts
> +export interface CloudPulseResourceTypeMap {
yes, it'll be used, because in the next PR we're going to add formatting logics for graph data. We have not added in this PR to avoid bigger size.

2024-07-29 13:39 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  if (status === 'success' && Boolean(metricsList?.data.result.length)) {
### 
![Screenshot 2024-07-29 at 7 08 31 PM](https://github.com/user-attachments/assets/6a8baef0-1cea-4a1a-91d7-febb642d5017)
I tried removing it but it is throwing undefined warning on IDE

2024-07-29 13:43 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  }
done

2024-07-29 13:43 UTC, nikhagra commented on packages/manager/src/featureFlags.ts
> +  aclpResourceTypeMap: CloudPulseResourceTypeMap[];
done

2024-07-29 13:48 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +      today = today || isToday(startEnd.start, startEnd.end);
done

2024-07-29 13:50 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +    resource_id: [],
changes

2024-07-29 13:54 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          },
no, because we receive a label prop as well when we fetch from widget configuration & that label prop we do not want to pass in the request.

2024-07-29 13:59 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +};
done

2024-07-29 14:01 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +    });
changed

2024-07-29 14:07 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +    );
thanks for suggestion

2024-07-29 14:09 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +                  : undefined
thanks

2024-07-29 14:11 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +};
simplified

2024-07-29 15:39 UTC, bnussman-akamai requested changes

2024-07-29 15:39 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +  getMetrics: (
Please use one query key factory per product. CloudPulse should only have a single `createQueryKeys`.

2024-07-29 15:39 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +    key: string
What is `key`? Looks like it does nothing

2024-07-29 15:39 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +          !queryClient.isFetching(['jwe-token', serviceType])
I don't think you need to check `queryClient.isFetching`. I'm pretty sure React Query already handles this.  You can pass `cancelRefetch` to `invalidateQueries` if you want it to cancel existing requests

2024-07-29 15:39 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +        const currentJWEtokenCache: any = queryClient.getQueryData([
Please fix the `any`.

2024-07-29 16:28 UTC, nikhagra commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +              maxWidth: isLegendsFullSize ? '100%' : '600px',
@jaalah-akamai  graph was looking fine but legends was not looking in full size, I've attached a screenshot by reverting this change.
![Screenshot 2024-07-29 at 9 58 37 PM](https://github.com/user-attachments/assets/bc834a35-bbae-4d9a-a952-a6472b2a148c)

2024-07-29 20:25 UTC, jaalah-akamai approved these changes

2024-07-29 20:26 UTC, jaalah-akamai commented
Approving pending changes request from Banks

2024-07-30 10:28 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +  getMetrics: (
done

2024-07-30 10:29 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +    key: string
removed the key

2024-07-30 10:29 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +        const currentJWEtokenCache: any = queryClient.getQueryData([
changed

2024-07-31 16:22 UTC, jaalah-akamai commented
Looks like you have a test failure for `objectStorage/access-key.e2e.spec.ts` try running `yarn cy:run -s  cypress/e2e/core/objectStorage/access-key.e2e.spec.ts`

2024-07-31 16:23 UTC, jaalah-akamai commented
@carrillo-erik this should be ready for another pass 👍

2024-07-31 16:55 UTC, nikhagra commented
> Looks like you have a test failure for `objectStorage/access-key.e2e.spec.ts` try running `yarn cy:run -s cypress/e2e/core/objectStorage/access-key.e2e.spec.ts`

@jaalah-akamai it seems some other test is failing as it doesn't belong to ACLP

2024-07-31 17:26 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const seriesDataFormatter = (
Just some food for thought. This works, the initial implementation you had included a `CloudPulseMetricValues[]` type. The problems was that you were using a `forEach()` loop and when accessing the elements in the array you were not specifying which property of the element you wanted to work with. If I recall that was the reason for the type error.

2024-07-31 17:34 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
For your consideration, normally we name components using `PascalCase` and other files using `camelCase`.

2024-07-31 17:48 UTC, carrillo-erik commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          {!isLoading && !Boolean(error) && (
I don't believe these `Boolean()` constructors are necessary. Feel free to use your IDE to search the project for instances where `<CircleProgress />` is used for examples of how it's typically used.

2024-07-31 17:53 UTC, carrillo-erik approved these changes

2024-08-01 09:49 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
sure

2024-08-01 09:57 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +export const seriesDataFormatter = (
yes correct,  because the type we defined is not matched with the structure of data being returned from the api response. That's why I've changed it to align that structure and it eventually fixed the IDE error.

2024-08-01 10:11 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +          {!isLoading && !Boolean(error) && (
I've updated. That error check is not required for circle progress.

2024-08-01 13:14 UTC, bnussman-akamai requested changes

2024-08-01 13:14 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  React.useEffect(() => {
Do we need the data, legendRows, and today state? We should be able to delete the  `useEffect` here and those extra states and just get the data directly from React Query. 

Using `useEffect` that depends on data returned from React Query is very bad practice.

2024-08-01 13:14 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
> +  legendRows?: any[];
Do not use `any`

2024-08-01 13:14 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +          | undefined = queryClient.getQueryData(['jwe-token', serviceType]);
This query key does not even exist. You should be referencing the query key factory and not hard-coding query keys here.

2024-08-01 13:14 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/aclpQueryFacotry.ts
Can we name this `queries.ts` to be consistent with all other products

2024-08-01 13:26 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/aclpQueryFacotry.ts
done

2024-08-01 13:39 UTC, bnussman-akamai commented
I highly recommend that the CloudPulse use `recharts` instead of `chart.js`

2024-08-01 13:57 UTC, nikhagra commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +          | undefined = queryClient.getQueryData(['jwe-token', serviceType]);
updated

2024-08-01 13:57 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
> +  legendRows?: any[];
updated

2024-08-01 13:58 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  React.useEffect(() => {
updated. Thanks for suggestion

2024-08-01 14:40 UTC, jdamore-linode commented
@nikhagra Could you merge in the latest changes from `develop`? That should resolve the test failures

2024-08-01 15:08 UTC, nikhagra commented
> @nikhagra Could you merge in the latest changes from `develop`? That should resolve the test failures

@jdamore-linode updated from latest dev branch

2024-08-01 20:31 UTC, bnussman-akamai commented
I'm aware of that Slack discussion, but I don't agree with the outcome. It's just creating more work for us later. @nikhagra

2024-08-02 04:06 UTC, kmuddapo commented
> I highly recommend that the CloudPulse use `recharts` instead of `chart.js`

Its in the radar, we will be migrating it post beta asap. Thanks!!

2024-08-02 15:37 UTC, kmuddapo commented
Thanks!! @bnussman-akamai  for the approvals.  Can this request be merged now please?

2024-08-02 16:40 UTC, nikhagra commented
@jaalah-akamai @jdamore-linode @bnussman-akamai I've marked marked all the conversations as resolved but still it says merging blocked because of requested changes. Could you please check and merge

2024-08-02 18:04 UTC, bnussman-akamai approved these changes

2024-08-02 19:52 UTC, merged