Update placement group policy text copy
linode/manager pull request #10727
Opened 2024-07-30 15:47 UTC by carrillo-erik

## Description 📝
This PR changes the text copy found in the Placement Group create drawer, under the "Placement Group Policy" radio buttons descriptions.

## Changes  🔄
The text copy updates are as follows:
- Strict
  - **Old**: You can’t assign Linodes if the preferred container defined by your Affinity Type lacks capacity or is unavailable (best practice).
  - **New**: Allows the addition of more compute instances to the group as long as the placement group remains compliant.
- Flexible
  - **Old**: You can assign Linodes, even if they’re not in the preferred container defined by your Affinity Type, but your placement group will be non-compliant.
  - **New**: Allows the addition of more compute instances to the group even if it breaks the placement group’s compliance.

## Target release date 🗓️
08/05/2024

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![old-pg-copy](https://github.com/user-attachments/assets/16e78608-af82-424f-88f1-5fcd090e4549) | ![new-pg-copy](https://github.com/user-attachments/assets/d648e77f-b86e-4121-a67f-db7882f6fbc2) |

## How to test 🧪
### Prerequisites
(How to setup test environment)
- Pull this branch and run it on your local machine.
- Visit the Placement Groups create drawer by using the `Create` dropdown menu or the Placement Groups landing page and clicking the `Create Placement Group` button.

### Verification steps
(How to verify changes)
- Verify that the copy updates reflected in these changes match the description found in the `Changes` section above.

## As an Author I have considered 🤔
*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-07-30 16:49 UTC, dwiley-akamai approved these changes
Confirmed copy changes ✅

Should we have a changeset for this?

2024-07-30 16:51 UTC, carrillo-erik commented
> Confirmed copy changes ✅
> 
> Should we have a changeset for this?

I just pushed it, I had checked the checkbox but got sidetracked and hadn't included it.

2024-07-31 13:59 UTC, AzureLatte approved these changes

2024-07-31 19:18 UTC, jdamore-linode commented
@carrillo-erik Merging in the latest changes from `develop` should resolve the Volumes failures, and the Linode delete failure can be disregarded because it's been flaky for a while, but I'm hoping to get to the bottom of those failures in the Linode Create w/ Firewall tests

2024-08-01 14:25 UTC, jdamore-linode requested changes
Looks like the changes in `create-linode-with-firewall.spec.ts` are causing the test failures in CI. Calling `mockAppendFeatureFlags()` in the test body overrides the call to `mockAppendFeatureFlags()` in the before hook, causing the tests to fail in any LD environment where the Linode Create refactor is not actually enabled.

Normally in a case like this, the solution would be to consolidate the calls to `mockAppendFeatureFlags()`, but in this case we'll just remove all of these changes since the `gecko2` feature flag override isn't necessary since the related PR was reverted.

2024-08-01 14:25 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
> +
```suggestion
```

2024-08-01 14:25 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
> +    }).as('getFeatureFlags');
```suggestion
```

2024-08-01 14:25 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
```suggestion
```

2024-08-01 14:25 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
```suggestion
```

2024-08-01 14:25 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
```suggestion
```

2024-08-01 15:13 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
> +
Removed.

2024-08-01 15:13 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
> +    }).as('getFeatureFlags');
Removed.

2024-08-01 15:13 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
Removed.

2024-08-01 15:14 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
Removed.

2024-08-01 15:14 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
> +
Removed.

2024-08-01 15:16 UTC, carrillo-erik commented
> Looks like the changes in `create-linode-with-firewall.spec.ts` are causing the test failures in CI. Calling `mockAppendFeatureFlags()` in the test body overrides the call to `mockAppendFeatureFlags()` in the before hook, causing the tests to fail in any LD environment where the Linode Create refactor is not actually enabled.
> 
> Normally in a case like this, the solution would be to consolidate the calls to `mockAppendFeatureFlags()`, but in this case we'll just remove all of these changes since the `gecko2` feature flag override isn't necessary since the related PR was reverted.

@jdamore-linode That's good info, thanks for sharing. It's also interesting because I recognized that I was repeating the same operation for each test, so I had consolidated the calls as you described and the tests failed. In any event, I've merged the latest from developed and removed the previous changes as requested.

2024-08-01 15:23 UTC, jdamore-linode approved these changes
Thanks @carrillo-erik! Approved pending CI passing (and I'll follow up if there are failures since there are a couple unrelated flaky tests atm)

> I had consolidated the calls as you described and the tests failed

Hm -- wish I had an explanation for you as to why that didn't work!

2024-08-01 15:56 UTC, merged