[change]: Update Appwrite Marketplace logo
linode/manager pull request #10729
Opened 2024-07-30 19:16 UTC by hmorris3293

## Description 📝
Update Appwrite to include new logo and colors
## Changes  🔄
upload appwrites new logo

## Target release date 🗓️
as soon as possible (no rush, but if we can fit it in next release that would make the partner happy :))

2024-07-30 19:19 UTC, hkhalil-akamai requested changes

2024-07-30 19:19 UTC, hkhalil-akamai commented on packages/manager/.env.example
Whoops 😅

2024-07-30 19:52 UTC, hmorris3293 commented
Before:
![Screenshot 2024-07-30 at 3 51 26 PM](https://github.com/user-attachments/assets/6c64006a-894d-4664-a15a-5d2a17f2ef8e)
After:
![Screenshot 2024-07-30 at 3 52 20 PM](https://github.com/user-attachments/assets/098b7fbb-fff5-4ddb-838a-32dcad0a82bc)

2024-07-30 19:57 UTC, hkhalil-akamai commented
> After: ![Screenshot 2024-07-30 at 3 52 20 PM](https://private-user-images.githubusercontent.com/28785076/353596635-098b7fbb-fff5-4ddb-838a-32dcad0a82bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjk0NzIsIm5iZiI6MTcyMjM2OTE3MiwicGF0aCI6Ii8yODc4NTA3Ni8zNTM1OTY2MzUtMDk4YjdmYmItZmZmNS00ZGRiLTgzOGEtMzJkY2FkMGE4MmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5NTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYmNiZTVkODlmMzVkMzFlMWRkODAwYzBlOTUyZWM4YzU1Yzk4MjdhZTE1NTBmNWYzNzJlYWZiZjkyNDU1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2mhc5SU7sAGeSt3kxNeTs_eSh5UpWKoIY-xq8wGFMqc)

The way the wider aspect ratio causes the logo text to become illegible is not great -- I wonder if we could include just the circular icon and leave out the text?

2024-07-31 14:34 UTC, hmorris3293 commented
![Screenshot 2024-07-31 at 10 33 46 AM](https://github.com/user-attachments/assets/78c51d78-1546-4b3a-a058-a84e93c799ae)
Updated screenshot with new logo

2024-07-31 14:52 UTC, jdamore-linode approved these changes
Thanks @hmorris3293!

2024-07-31 14:54 UTC, hana-linode approved these changes

2024-07-31 16:27 UTC, hkhalil-akamai approved these changes
Thanks for making the changes!

2024-07-31 17:02 UTC, merged