upcoming: [DI-20050] - Added Data Rollup logic for graph data
linode/manager pull request #10747
Opened 2024-08-05 14:23 UTC by nikhagra

## Description 📝
Added data rollup logic to convert the graph data  to highest possible unit based on the base unit of data we receive from widget configuration.

## Changes  🔄
List any change relevant to the reviewer.
1. Added a unit conversion utility file to handle data rollup & conversion logic
2. Modified utils.ts to add a logic to generate label name for graph.
3. Modified JWE token payload from resource_id to resource_ids based on api specs
4. Updated position of message for empty data in the graph.

## Target release date 🗓️
15th August 2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
|![Screenshot 2024-08-05 at 7 49 36 PM](https://github.com/user-attachments/assets/96aeb377-09e6-4e48-89fa-8cdd36eeac10)|![Screenshot 2024-08-05 at 7 37 01 PM](https://github.com/user-attachments/assets/cf1659ae-e1a2-4b8b-8197-c93bd35dd58a)|
|![Screenshot 2024-08-05 at 7 37 46 PM](https://github.com/user-attachments/assets/84663504-8133-4645-a672-75f100522d9c)|![Screenshot 2024-08-05 at 7 36 52 PM](https://github.com/user-attachments/assets/074c8121-9fb1-4bd0-b6c2-b479f32e5a29)|

## How to test 🧪

1. Enable mock services as some endpoints are not ready to use
2. As their is not much visual change in the UI you can simulate the unit conversion logic by passing different values & units

Note: You may notice some flickering because of continuous re-rendering but that will be resolved once global filter change handler is implement.

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-08-05 14:37 UTC, venkymano approved these changes
LGTM, this is the same changes we have in our integrated branch

2024-08-05 19:50 UTC, jaalah-akamai requested changes

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  });
If we're only using the dimensions for index purposes, we can probably omit that and map over `legendRowsData`, something like
```
const maxValue = Math.max(
    0,
    ...legendRowsData.map((row) => row?.data.max ?? 0)
  );
```

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +    return labelObject.label + ' (' + labelObject.unit + ')';
```suggestion
    return `${labelObject.label} (${labelObject.unit})`;
```

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  const flag = results?.length ? results[0] : undefined;
```suggestion
  const flag = labelObject.flags?.aclpResourceTypeMap?.find(
    (obj: CloudPulseResourceTypeMapFlag) => obj.serviceType === labelObject.serviceType
  );
```

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +    }
Nit: What you have works, but don't we need to return the value? We can make it more readable by using `.entries()` and doing the join outside of the loop for all non-empty strings. You can decide if the boolean is necessary, but I would imagine we want to remove empty strings
```suggestion
 return Object.entries(metric)
    .map(([key, value]) => {
      if (key === flag?.dimensionKey) {
        const mappedName = mapResourceIdToName(value, resources);
        return mappedName || '';
      }
      return value || '';
    })
    .filter(Boolean)
    .join('_');
```

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  return index != -1 ? resources[index].label : id;
Nit: You're choice to add or not - Nothing wrong with approach, just could slightly readability 👍 
```suggestion
  const resource = resources.find((resourceObj) => resourceObj.id === id);
  return resource ? resource.label : id;
```

2024-08-05 19:50 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Utils/unitConversion.test.ts
> +});
We should add a test for `generateUnitByBaseUnit`

2024-08-06 07:51 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +    }
Thanks for the suggestions. Yes we have to remove the empty strings.

2024-08-06 07:53 UTC, nikhagra commented
@jaalah-akamai  thanks for the suggestions. I've updated those & added test cases

2024-08-06 14:01 UTC, jaalah-akamai commented
Please take note of this issue and address it in an upcoming PR (or this one): The Grid item containing the refresh icon has styles that cause the button to overlap with the dropdown menus at smaller breakpoints. These styles should be removed to prevent this overlap.

<img width="438" alt="Screenshot 2024-08-06 at 9 57 36 AM" src="https://github.com/user-attachments/assets/910f7c23-f6b9-42e2-abf4-b1dc95691788">

2024-08-06 14:01 UTC, jaalah-akamai approved these changes

2024-08-06 14:02 UTC, jaalah-akamai commented
@mjac0bs / @DevDW (Added because @cpathipa is OOO) - Feel free to review when you can

2024-08-06 14:07 UTC, nikhagra commented
> Please take note of this issue and address it in an upcoming PR (or this one): The Grid item containing the refresh icon has styles that cause the button to overlap with the dropdown menus at smaller breakpoints. These styles should be removed to prevent this overlap.
> 
> <img alt="Screenshot 2024-08-06 at 9 57 36 AM" width="438" src="https://private-user-images.githubusercontent.com/125309814/355478605-910f7c23-f6b9-42e2-abf4-b1dc95691788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTMyMTMsIm5iZiI6MTcyMjk1MjkxMywicGF0aCI6Ii8xMjUzMDk4MTQvMzU1NDc4NjA1LTkxMGY3YzIzLWY2YjktNDJlMi1hYmY0LWIxZGM5NTY5MTc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNDAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzNiZDA0MTM1NzY3NmYxOTc2ZGYyMWMyYWUxYjQ1NzFkMDI1YzhkNjhjZmY2YWZiZTQyZTQ3YmZjMjU5ZjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.adVlgPqVmgz7nE54hCHqTGddn53IQWCMazFjotjOjGw">

@jaalah-akamai, yes this is being addressed in the separate PR which @venkymano is working on with configured global filters.

2024-08-06 23:07 UTC, mjac0bs reviewed
Left some feedback on initial pass through and will re-review once that feedback has been addressed.

2024-08-06 23:07 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  },
This would be cleaner with [interfaces](https://linode.github.io/manager/development-guide/02-component-structure.html#types-and-interfaces).

At least a `Widget` interface would improve readability, and potentially reusability if that is ever the case
e.g.
```
interface Widget {
  label: string;
  serviceType: string;
  status: string | undefined;
  unit: string;
  widgetColor: string | undefined;
}
```

2024-08-06 23:07 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  },
Same comment about interfaces as with `generateGraphData` and the widgetObject.

2024-08-06 23:07 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +
```suggestion
```

2024-08-07 12:54 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
>              <ErrorState errorText={error![0].reason} />
I removed that check from widget component & moved as early return in Line Graph component.

2024-08-07 12:57 UTC, nikhagra commented
@mjac0bs Thanks for the comments. I've addressed them and also created new changesets with upcoming-feature tag

2024-08-07 21:34 UTC, dwiley-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +            nativeLegend={true}
If it'll always be `true`, we should be able to just do:

```suggestion
            nativeLegend
```

2024-08-07 21:34 UTC, dwiley-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> + * @param flags flags associated with metriclist
```suggestion
 * @param flags flags associated with metricsList
```

2024-08-07 21:34 UTC, dwiley-akamai commented on packages/manager/src/features/CloudPulse/Utils/unitConversion.ts
minor: can we get rid of the colons in `@param XYZ :` and `@returns :` instances to maintain consistency?

2024-08-07 23:14 UTC, mjac0bs reviewed
Thanks for addressing feedback @nikhagra. Error and loading states look cleaner and comments for documentation help everyone.

I've provided more detail (and hopefully more clearly) in comments about what we'd like to see for util functions with several parameters. Once those are cleaned up, this is looking in better shape to be merged.

A note to address in a future PR: there is a typo in the cloudpulse query params so they read: `Clousepulse`. (We also generally lowercase these, so `cloudpulse` would be standard here.)

![image](https://github.com/user-attachments/assets/ce0dd15f-0b18-448f-9a9c-08aa77ca3f66)

2024-08-07 23:14 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
> +      {isDataEmpty(props.data) && (
Let's also fully destructure props in this file, so: `const { ariaLabel, data, error, legendRows, loading, ...rest } = props;`. We shouldn't be calling `props.`anything as a best practice for improved readability.

2024-08-07 23:14 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +            ariaLabel={props.ariaLabel ? props.ariaLabel : ''}
Same comment as below - please destructure your props.
```suggestion
            ariaLabel={ariaLabel ??  : ''}
```

2024-08-07 23:14 UTC, mjac0bs commented on packages/manager/src/features/CloudPulse/Utils/unitConversion.test.ts
> +    it('should generated maximum unit based on the base unit & value', () => {
```suggestion
    it('should generate maximum unit based on the base unit & value', () => {
```

2024-08-08 07:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/unitConversion.ts
I never noticed that it automatically adds a hyphen. Thanks for suggestion

2024-08-08 07:29 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
>      metricsList!.data.result.forEach(
Even though we checked for undefined, ide was still showing it as error. I've modified the code to remove assertion

2024-08-08 07:35 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx
> +      {isDataEmpty(props.data) && (
yes we have implementation of the same function in our code. I've moved it to a utils

2024-08-08 12:43 UTC, nikhagra commented
@mjac0bs @dwiley-akamai  I've addressed comments & enhanced jsDocs. Please check & approve if all good

2024-08-08 15:07 UTC, mjac0bs approved these changes
Approving since most of feedback clean up has been addressed, but left some final bits of feedback for you, @nikhagra. 👍🏼

2024-08-08 15:16 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +  };
I've not created additional interface for LabelObject as it was function specific parameter. Instead of creating a new interface I'll destructure it as it is not necessary to keep them inside labelObject key

2024-08-08 15:17 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          resources,
Sure will update

2024-08-08 15:34 UTC, nikhagra commented
@mjac0bs  thanks for the approval, I've updated the interface structure. @jaalah-akamai @mjac0bs  @dwiley-akamai  we've received required approval, please merge.

2024-08-08 16:55 UTC, dwiley-akamai approved these changes
Code review ✅
Mocked graphs ✅

2024-08-08 16:55 UTC, dwiley-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +            ariaLabel={ariaLabel ? ariaLabel : ''}
could use a nullish coalescing operator here

```suggestion
            ariaLabel={ariaLabel ?? ''}
```

2024-08-08 18:00 UTC, mjac0bs commented
The only CI failure was on `smoke-community-stackscrips.spec.ts` which is a result of this branch not being up to date with `develop`, where this was [fixed](https://github.com/linode/manager/pull/10757) earlier this week.

I'm going to merge this PR now.

2024-08-08 18:00 UTC, merged