feat: [M3-7666] - Remove Animation from Search Results and Animate Icon Instead
linode/manager pull request #10754
Opened 2024-08-06 12:34 UTC by pmakode-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-08-07 15:58 UTC, pmakode-akamai commented on packages/manager/src/features/Search/SearchLanding.tsx
> -
No need to split the word as we are removing any animation on the search query text.

2024-08-07 16:03 UTC, pmakode-akamai commented on packages/manager/src/features/Search/SearchLanding.tsx
> -const splitWord = (word: any) => {
No need to split the word as we are removing any animation on the search query text.

2024-08-07 16:46 UTC, hkhalil-akamai approved these changes
Thanks for handling this and nice work on the SVG animation, cute!

2024-08-07 16:46 UTC, hkhalil-akamai commented on packages/manager/src/features/Search/SearchLanding.styles.ts
> +  }
Both `transform` values are identical -- is this intentional?

2024-08-07 17:04 UTC, pmakode-akamai commented on packages/manager/src/features/Search/SearchLanding.styles.ts
> +  }
Let me refactor this a bit.

2024-08-07 17:13 UTC, bnussman-akamai approved these changes
Nice!

2024-08-07 19:32 UTC, jdamore-linode requested changes
Thanks for the improvement @pmakode-akamai! Looks like we're getting a couple test failures in CI that we'll want to fix before merging this (and otherwise have no reason to be alarmed by), but otherwise this all looks great!

Don't hesitate to reach out on Slack if you have any questions!

2024-08-07 19:32 UTC, jdamore-linode commented on packages/manager/src/features/Search/SearchLanding.tsx
> +              Sorry, no results for this one.
Looks like this improvement is causing test failures in one of our Cypress UI specs 😅

You should be able to fix it by making the same change here:
https://github.com/linode/manager/blob/3a6584c/packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts#L23

2024-08-07 20:18 UTC, pmakode-akamai commented on packages/manager/src/features/Search/SearchLanding.tsx
> +              Sorry, no results for this one.
@jdamore-linode Fixed in 268046f48bb34bf214a4901d4e94bcd4614e6d1f

2024-08-08 13:03 UTC, jdamore-linode approved these changes
Thanks @pmakode-akamai!

2024-08-09 05:51 UTC, merged