Feature/m3 8146
linode/manager pull request #10765
Opened 2024-08-08 21:24 UTC by cliu-akamai

## Description 📝
Refactor Cypress test to the flow of creating Linode through CLI.

## Major Changes 🔄
- Refactor Cypress test that creates Linode through CLI.

## How to test 🧪
```
yarn cy:run -s "cypress/e2e/core/linodes/legacy-create-linode.spec.ts"
```

2024-08-09 21:22 UTC, mjac0bs requested changes
This test failed in CI, but it does run and pass locally (5+ times), and I can't quite follow what happened in the CI run.

It looks like we're testing the wrong flow here, though! See my comment on the `legacy-create-linode.spec.ts`.

2024-08-09 21:22 UTC, mjac0bs commented on yarn.lock
How did this get in here?

2024-08-09 21:22 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
I may be misunderstanding the point of this ticket, but based on the comment on L4-L5 of this file:

```
// TODO Delete this test file when `linodeCreateRefactor` feature flag is retired.
// Move out any tests (e.g. region select test) for flows that aren't covered by new tests in the meantime.
```

It sounds like we wouldn't want to make updates in this file, but rather write a new test file that tests CLI in the **refactored** (v2) flow. Since this test suite mocks the linode create feature flag [false](https://github.com/linode/manager/pull/10765/files#diff-e9a1b9cf41bab377cfc730b07faf7f55fa53eaa24f08d821fa2625fd6fd3bdfdL95), we don't seem to be doing that here.

2024-08-09 21:22 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
> +      cy.findByText('Provisioning', { exact: false }).should('be.visible');
Not quite what the acceptance criteria requested here: `Confirm Cloud Manager behavior to automatically redirect to created Linode after CLI command is executed`. Isn't the redirect to the Linode's details page?

2024-08-12 17:15 UTC, hkhalil-akamai commented on packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
> +      cy.exec(curlRequest).then((res) => {
The CI error is being caused by executing the curl command. It seems like the jenkins instance doesn't have curl installed on it.

```
Stderr:
/usr/bin/bash: line 1: curl: command not found
```

@jdamore-linode can we update the jenkins docker config to install cURL if we want to go ahead with this approach?

2024-08-12 18:16 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
> +      cy.exec(curlRequest).then((res) => {
@cliu-akamai (cc @hkhalil-akamai) we probably _shouldn't_ be doing this E2E, and instead should mock the relevant events to trigger/test the redirect behavior, even though this is really, really cool as it is.

(I'm only reluctant to do this because we wouldn't have the normal security guardrails available, like ensuring that the created Linode can't connect to the internet, etc. -- basically none of the protections that were added by #10538 and #10633 would apply to this cURL call)

2024-08-28 18:03 UTC, hkhalil-akamai commented
Here's the code that detects the event and triggers the redirect:

https://github.com/linode/manager/blob/14b02430623d770ddb6c60ac91957aec4863ed88/packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx#L64-L69

We can try mocking this instead of manually executing the curl command.

@cliu-akamai

2024-08-29 16:32 UTC, cliu-akamai commented on packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
> +      cy.findByText('Provisioning', { exact: false }).should('be.visible');
No, it doesn't redirect after sending the CLI.

2025-02-25 16:19 UTC, closed without merging