feat: [UIE-8002] - DBaaS 2.0 Landing Page
linode/manager pull request #10823
Opened 2024-08-23 15:43 UTC by mpolotsk-akamai

## Description 📝
DBaaS 2.0 Landing Page and Empty Landing Page

## Changes  🔄
- Added Tabs to the Landing Page: Two tabs for Beta customers, labeled "Legacy Databases" and "New Databases."
- Added Logo(including dark theme): Displayed on the Empty Landing Page, in the "New Databases" tab, and in the "New Databases" single table view.
- Single Table Landing Page: Added for Beta customers without "Legacy Databases" but with "New Databases," and for new customers with only "New Databases."
- New "Plan" Column: Added to the "New Databases" table.
- Added Info Banner: Included on the landing page.

## Target release date 🗓️
9/9/24

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-08-23 at 2 21 42 PM](https://github.com/user-attachments/assets/2ae8e205-fcf9-4841-98f5-6c17c6c067bc) | ![Screenshot 2024-08-23 at 2 20 46 PM](https://github.com/user-attachments/assets/bfe1e9c5-aa01-4835-bdda-cfb490feb9bb) |
|![Screenshot 2024-08-23 at 2 17 50 PM](https://github.com/user-attachments/assets/72aae648-bdf3-42e9-a25d-6e742c8db589) | ![Screenshot 2024-08-23 at 2 18 05 PM](https://github.com/user-attachments/assets/0338b717-5d38-4257-b5f9-f8b024ba8bc1)|
| |![Screenshot 2024-08-23 at 5 40 13 PM](https://github.com/user-attachments/assets/ffa7c3b4-4947-46d7-b3b0-286d8f22caa9)|
| |![Screenshot 2024-08-23 at 2 22 56 PM](https://github.com/user-attachments/assets/571ba607-dd92-4efa-9b15-e955cc38f5b3)|

## 
How to test 🧪

### Prerequisites
(How to setup test environment)
Enable DatabaseV2Beta flag

### Verification steps
(How to verify changes)

1. Navigate to the Databases section.
2. For new customers (with no legacy or new databases), the Landing Page will display an Empty Landing Page with a Logo.
3. For customers with Legacy Databases, the Landing Page will show tabs for "Legacy Databases" and "New Databases," along with an info banner.
4. When "New Databases" tab is selected, the page will display a table with an additional "Plan" column and a logo below the table. The "Configuration" column will be renamed to "Nodes." The table will be empty if no new databases are present.
5. For customers without Legacy Databases but with New Databases, the Landing Page will show a single table with a "Plan" column and the "Configuration" column renamed to "Nodes," an info banner, and a Logo below the table.
6. If the DatabaseV2Beta flag is disabled, the Landing Page will display a single table with no changes.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-08-23 17:15 UTC, jaalah-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
> +}));
I would avoid makeStyles here and either use `sx` or make a styled component

2024-08-23 17:15 UTC, jaalah-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
> +}));
Also for the hard-coded colors, can we something from our theme?

2024-08-23 17:15 UTC, jaalah-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx
> +    <DatabaseLogo style={{ marginBottom: '20px', marginTop: '-10px' }} />
Can we rename this prop to be `sx`? I don't want someone to confuse this with the actual style attribute

2024-08-23 17:58 UTC, mjac0bs commented
@mpolotsk-akamai I just merged in #10786 so we'll want to rebase this PR on `develop`.

2024-08-26 11:47 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
> +}));
Thanks for the review.
I updated DatabaseLogo.tsx

2024-08-26 11:48 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx
> +    <DatabaseLogo style={{ marginBottom: '20px', marginTop: '-10px' }} />
updated

2024-08-26 11:55 UTC, mpolotsk-akamai commented
> @mpolotsk-akamai I just merged in #10786 so we'll want to rebase this PR on `develop`.

@mjac0bs , thanks, I've rebased the PR

2024-08-26 14:40 UTC, bnussman-akamai requested changes

2024-08-26 14:40 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +  });
Doing client side filtering like this will probably make pagination work unexpectedly.  Can we use an [X-Filter](https://techdocs.akamai.com/linode-api/reference/filtering-and-sorting) for this?


That will allow us to move `useDatabasesQuery` into `DatabaseLandingTable` and conditionally apply the X-Filter depending on whether or not we want legacy or new databases

2024-08-26 16:41 UTC, harsh-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
> +  it('should render tabs with legace and new databases ', async () => {
```suggestion
  it('should render tabs with legacy and new databases ', async () => {
```

2024-08-27 16:40 UTC, corya-akamai commented on packages/api-v4/src/databases/types.ts
> -  id: number;
This will stay an integer per BE

2024-08-27 16:41 UTC, corya-akamai commented on packages/manager/src/factories/databases.ts
> +    id: Factory.each((i) => (i % 2 ? i.toString() : `a${i}`)),
Can be reverted, will stay integer

2024-08-28 16:48 UTC, mjac0bs commented on packages/manager/src/features/GlobalNotifications/DatabaseClusterInfoBanner.tsx
> +              can always remove unwanted clusters.
```suggestion
              clusters later on, you’ll be charged according to the new payment.
              You can always remove unwanted clusters.
```
Run-on sentence

2024-08-28 16:48 UTC, mjac0bs commented on packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksTypes.ts
> +  dbLogo?: React.ReactNode;
`ResourceHeaders` props are shared across all our empty-state landing pages. Could we name this more generically, here and in `ResourcesSection.tsx`, in case other landing pages make use of this prop in the future? `branding` was more generic - was there a reason for that change?

```suggestion
  logo?: React.ReactNode;
```

2024-08-28 16:48 UTC, mjac0bs commented on packages/manager/.changeset/pr-10823-added-1724427890426.md
> +Add Landing Page for V2 ([#10823](https://github.com/linode/manager/pull/10823))
```suggestion
Add Landing Page and update Empty-State Landing page for DBaaS V2 ([#10823](https://github.com/linode/manager/pull/10823))
```
Thanks for the changeset! We recently published some [best practices] as a team on how to write these. In this case, can we make this an [`Upcoming Feature`](https://linode.github.io/manager/CONTRIBUTING.html#writing-a-changeset) entry instead of 'Added'?

> Use the Upcoming Features section for ongoing project work that is behind a feature flag. If additional changes are being made that are not feature flagged, add another changeset to describe that work.

2024-08-28 16:48 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
Thanks for the test coverage - can we also cover all states the flag can be in (helping us catch any potential regressions), by mocking the `flags: { dbaasV2: { beta: false, enabled: false } }` and testing that we are *not* seeing the new database clusters tab or logo?

2024-08-28 16:48 UTC, mjac0bs commented on packages/manager/src/features/GlobalNotifications/DatabaseClusterInfoBanner.tsx
> +              always remove unwanted clusters.
```suggestion
              You won’t be charged for Aiven database clusters created during
              duration of the Beta phase. If you decide to keep the new clusters
              later on, you’ll be charged according to the new payment. You can
              always remove unwanted clusters.
```
Run-on sentence

2024-08-28 17:56 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
@mjac0bs , thank you for the code review. I've added test for flags: { dbaasV2: { beta: false, enabled: false } }

2024-08-30 05:40 UTC, mjac0bs approved these changes
Thanks for addressing feedback, @mpolotsk-akamai -  I just left a couple of minor notes on my final pass through.

CI was struggling to run the full e2e suite but I'll make sure DBaaS is all passing before this gets merged.

2024-08-30 05:40 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
I do find the `a` and `b` database naming scheme a bit difficult to read versus something like `new` and `legacy`.  Was this chosen to be intentionally generic?

2024-08-30 05:40 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +  types?: DatabaseType[] | undefined;
Nit: we could rely on `useDatabaseTypesQuery` hook again to avoid passing `types` down as props here and in `DatabaseLandingTable.tsx`. The query will already be in the React Query cache from when it was first called.

2024-08-30 16:37 UTC, mjac0bs commented
@mpolotsk-akamai Just noticed that typecheck is was [failing](https://github.com/linode/manager/actions/runs/10618824097/job/29448517719?pr=10823) - using the optional chaining operator to access databases`?.data` should fix that where there are errors.

2024-09-04 11:14 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
@mjac0bs, yes, it was chosen to be generic.

2024-09-04 14:41 UTC, bnussman-akamai reviewed
This is shaping up nicely! Will continue to review, but left a few more small comments in the meantime

2024-09-04 14:41 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +  isADatabases?: boolean;
I'm not sure what `isADatabases` means. Can we make the name more descriptive? Maybe something like `isAivenDatabase`?

```suggestion
  isAivenDatabase?: boolean;
```

2024-09-04 14:41 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +  types?: DatabaseType[] | undefined;
Agree!

2024-09-04 14:41 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +  const dbPlatformType = isADatabases ? 'a' : 'b';
Can we use something more descriptive than `a` and `b`?

2024-09-04 14:41 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
I agree with @mjac0bs. 

I understand that being generic is intentional, but could we at least do something like `Aiven` and `legacy`, `new` and `legacy`, `new` and `old`, or `v1` and `v2`

2024-09-05 08:27 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Renamed to new/legacy.

2024-09-05 08:29 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +  isADatabases?: boolean;
Renamed to 'isNewDatabase'

2024-09-06 14:02 UTC, bnussman-akamai reviewed
I'm seeing extra spacing here compared to production that we should fix

![Screenshot 2024-09-06 at 10 01 34 AM](https://github.com/user-attachments/assets/0aeba785-61a2-4edc-b691-482d92c1246d)

2024-09-06 14:02 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Now that we have two queries on this page, it is making 2 API requests to `https://api.linode.com/v4beta/databases/instances` when the feature flag is off. 

We should make sure DBaaS v1 does not make 2 API requests.

Also, I recommend breaking this file up into more components. We could make a new `DatabaseLandingTable` component that contains the query and takes in props that determines whether it will show v1 or v2 Database instances.  See `packages/manager/src/features/Account/Maintenance/MaintenanceLanding.tsx` as a rough example of what I mean

Let me know if you need me to explain further!

2024-09-09 12:58 UTC, bnussman-akamai approved these changes

2024-09-11 13:45 UTC, jdamore-linode requested changes
Just want to call out the failing Cypress tests in `create-database.spec.ts` so we don't accidentally merge this before they're fixed.

It looks like the tests are failing because no regions are appearing in the region select drop-down -- that's probably caused by something not being mocked

2024-09-12 15:22 UTC, mpolotsk-akamai commented
> Just want to call out the failing Cypress tests in `create-database.spec.ts` so we don't accidentally merge this before they're fixed.
> 
> It looks like the tests are failing because no regions are appearing in the region select drop-down -- that's probably caused by something not being mocked

@jdamore-linode, I've fixed the issue.

2024-09-12 19:58 UTC, jdamore-linode approved these changes
Thanks again @mpolotsk-akamai!

2024-09-12 20:14 UTC, mjac0bs requested changes

2024-09-12 20:14 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    ['platform']: 'rdbms-default',
Was hoping to merge this PR but did a final check and am seeing an error on the Databases landing page that  is being caused by platform filtering. 

It looks like API doesn't currently support filtering on the current platforms we're providing in prod or dev. I see we changed the platforms in [this commit](https://github.com/linode/manager/pull/10823/commits/92369fb04f5871172f6bc65b81533998e198e972#diff-349dd5a79240217f5ce2a4fc0d535400e419f95244211a4000333385d012ebd7R53-R87). What's the plan for these?

![Screenshot 2024-09-12 at 1 02 18 PM](https://github.com/user-attachments/assets/0f5c6215-332b-469e-9010-252cab1fdecd)

2024-09-13 15:12 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    ['platform']: 'rdbms-default',
@mpolotsk-akamai it's working for V2 beta users so we just need to make it conditional for non-beta users
`  
const newDatabasesFilter: Record<string, string> = {
    ['+order']: newDatabaseOrder,
    ['+order_by']: newDatabaseOrderBy,
  };

  if (isDatabasesV2Enabled) {
    newDatabasesFilter['platform'] = 'rdbms-default';
  } 

const legacyDatabasesFilter: Record<string, string> = {
    ['+order']: legacyDatabaseOrder,
    ['+order_by']: legacyDatabaseOrderBy,
  };

  if (isDatabasesV2Enabled) {
    legacyDatabasesFilter['platform'] = 'rdbms-legacy';
  } 
  `

2024-09-13 16:34 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    ['platform']: 'rdbms-default',
Fixed
Thanks @corya-akamai

2024-09-13 16:39 UTC, mjac0bs approved these changes
Thanks @mpolotsk-akamai and @corya-akamai - looking good now. I'll merge this as soon as CI finishes.

2024-09-13 17:31 UTC, merged