upcoming: [DI-20357] - Changes for ACLP single reusable component
linode/manager pull request #10845
Opened 2024-08-28 06:49 UTC by venkymano

## Description 📝
Added a new CloudPulseDashboardWithFilters component which has the capability to build the filters needed in service provider page as well as the dashboard. This component will be integrated in the service provider pages.

## Changes  🔄

1. Added new CloudPulseDashboardWithFilters component that has the capability to build the filters needed in service provider page as well as the dashboard. This will be integrated only in the service provider pages.
2. Modified the dbaas config to introduce a new filter nodeType

## Target release date 🗓️
03-09-2024

## Preview 📷
| Before  | After   |
| ------- | ------- |
|![Screenshot 2024-08-28 at 11 40 04 AM](https://github.com/user-attachments/assets/ff356cfc-8dd6-44ad-bb7e-f565a49e56b5)|![Screenshot 2024-08-28 at 11 40 29 AM](https://github.com/user-attachments/assets/01fed9ef-ddad-46f2-bdb2-7b7df044659f)|
|![Screenshot 2024-08-28 at 11 40 38 AM](https://github.com/user-attachments/assets/ecd7582f-d271-472e-a2b0-1d991bd16cd0)||
|![Screenshot 2024-08-28 at 11 41 19 AM](https://github.com/user-attachments/assets/d8a1c9ca-077c-4c66-9556-0da4a5248f37)|![Screenshot 2024-08-28 at 11 41 12 AM](https://github.com/user-attachments/assets/c4672c4b-443f-498d-9b90-49c9adcee4ad)|

## How to test 🧪
To test this, we need to integrate the CloudPulseDashboardWithFilters in a service Provider page. The below commit shows we have integrated this component in database details index page 

https://github.com/venkymano/manager/commit/e0f3598630fa4c66e493d76b07dea515c1334f0c

1. Copy the code in the commit in the same file mentioned in the commit
2. Start the cloud manager UI application
3. Login and enable mock user as some API endpoints are not available still.
4. Navigate to any database instance details page, and navigate to the monitor tab.
5. You will see filters needed in service provide page as well as a mock dashboard rendered.

**Note** - We support only linode and dbaas, so the sample integration revolves around Managed Databases

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-08-28 09:26 UTC, nikhagra requested changes

2024-08-28 09:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +    const StyledPlaceholder = styled(Placeholder, {
as this is only one style passed, we can add it directly in sx prop

2024-08-28 09:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +}
```suggestion

```
I don't think this compare function required as props contains only these two values  & memo will take care to check these two literals

2024-08-28 09:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +    }, []);
```suggestion
    const renderPlaceHolder = (subtitle: string) => {
        return (
            <Paper>
                <StyledPlaceholder
                    icon={CloudPulseIcon}
                    isEntity
                    subtitle={subtitle}
                    title=""
                />
            </Paper>
        );
    };
```
we can remove callback from here as this function is not going to be passed as props to other component

2024-08-28 09:26 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +  };
```suggestion
  return {
    additionalFilters: constructDimensionFilters({
      dashboardObj,
      filterValue,
      resource,
    }),
    dashboardId: dashboardObj.id,
    duration: timeDuration ??  { unit: 'min', value: 30 },
    resources: [String(resource)],
    savePref: false,
  };
```
we can directly pass the default value instead of storing in the object

2024-08-28 09:53 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +    const StyledPlaceholder = styled(Placeholder, {
There is no inbuilt sx or style tag support for placeholder, so using this

2024-08-28 10:03 UTC, nikhagra approved these changes

2024-08-30 03:17 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +        </Grid>
There's so many grid components here, do we need all these for some future additions or something? 
This can all be done with a single Box essentially
```
<>
        <Paper>
          <Box
            sx={{
              justifyContent: {
                sm: 'flex-start',
                xs: 'center',
              },
            }}
            display="flex"
            paddingX={2}
            paddingY={1}
          >
            <CloudPulseTimeRangeSelect
              disabled={!dashboard}
              handleStatsChange={handleTimeRangeChange}
              savePreferences={true}
            />
          </Box>
          <Divider />
          {isFilterBuilderNeeded && (
            <CloudPulseDashboardFilterBuilder
              dashboard={dashboard}
              emitFilterChange={onFilterChange}
              isServiceAnalyticsIntegration={true}
            />
          )}
          <Divider />
        </Paper>
        {isMandatoryFiltersSelected ? (
          <CloudPulseDashboard
            {...getDashboardProperties({
              dashboardObj: dashboard,
              filterValue,
              resource,
              timeDuration,
            })}
          />
        ) : (
          renderPlaceHolder('Mandatory Filters not Selected')
        )}
      </>
```

2024-08-30 04:47 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +        </Grid>
@jaalah-akamai , in future we might add elements like TimeRangeSelect that are common for all service providers. I also agree we don't need this much Grids. I update the code to have a single Grid Container, and placed the TimeRangeSelect inside it, so in future if we add elements, it works according to our expectations of having three filters in a row

2024-08-30 04:47 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
> +    const StyledPlaceholder = styled(Placeholder, {
done

2024-09-02 04:12 UTC, kmuddapo approved these changes

2024-09-03 17:18 UTC, jaalah-akamai approved these changes

2024-09-03 18:08 UTC, coliu-akamai reviewed
I feel like there might be a way to simplify a few of the methods in `ReusableDashboardFilterUtils.ts` in addition to what I commented on - will think on this a bit and get back to you!

2024-09-03 18:08 UTC, coliu-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +  }
We don't need this since we're checking whether serviceTypeConfig is truthy at line 69/70. We can either keep this check or lines 69/70, but we don't need both

2024-09-03 18:08 UTC, coliu-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +    }
do we need this check? Doesn't seem like filter will ever be undefined/null: 
![image](https://github.com/user-attachments/assets/373a0b71-86ba-4e54-aef4-ebd27aa5bf7e)

2024-09-03 18:17 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +  }
Yeah, here kept this and removed line 69 and 70

2024-09-03 18:17 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +    }
don't need, removed

2024-09-03 18:17 UTC, venkymano-akamai commented
@coliu-akamai , I have addressed those you have given

2024-09-04 00:42 UTC, venkymano-akamai commented
@coliu-akamai , Addressed the comments, can you please check if this is good now?

2024-09-04 00:43 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
> +export const checkIfFilterNeededInMetricsCall = (
Lets, have the readability one for now

2024-09-04 00:43 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.test.ts
> +  expect(result).toBe(false);
Added as individual test cases

2024-09-04 13:08 UTC, coliu-akamai approved these changes
Thanks for the changes!

✅ confirmed mocked dashboard for dbaas instances

2024-09-04 20:06 UTC, merged