upcoming: [DI-20360] - Updated preferences logic to remove flickering issue
linode/manager pull request #10853
Opened 2024-08-29 13:31 UTC by nikhagra

## Description 📝
Changed the current implementation of UserPreference to avoid flickering issue in widget component

## Changes  🔄
List any change relevant to the reviewer.
1. Created a custom hook useAclpPreference in UserPreference.ts file
2. Removed useEffect from CloudPulseWidget component
3. Updated CloudPulseDashboard component to use default time_granularity if preference is not present

## Target release date 🗓️
5th September 2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
|![Screenshot 2024-08-29 at 6 58 16 PM](https://github.com/user-attachments/assets/d451815e-71af-4331-a6e9-8d2222e24de1)|![Screenshot 2024-08-29 at 6 58 47 PM](https://github.com/user-attachments/assets/6a3c4ddb-9b16-4318-b1d2-d44e1a8c9949)|
|![Screenshot 2024-08-29 at 6 58 57 PM](https://github.com/user-attachments/assets/e6b9d6c3-4b9a-44ef-bfaf-f9e1aa59c6cb)|![Screenshot 2024-08-29 at 6 58 05 PM](https://github.com/user-attachments/assets/9d387b0a-5d92-4cce-aed2-9a30cc469a06)|

## How to test 🧪
1. Switch to mock user as APIs are not live.
2. Change global filters value & you can check if UI is flickering or not because of component re-renderings

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-09-03 13:57 UTC, nikhagra-akamai commented
Hi @jaalah-akamai / @bnussman-akamai  / @abailly-akamai, I've updated the logics to reduce re-renderings. Please start reviewing the PR

2024-09-04 14:24 UTC, bnussman-akamai reviewed
My two main pieces of feedback are:

- `useRef` in `UserPreference.ts` **should not be necessary**. If it is necessary to make CloudPulse work, is indicative of a larger issues. 
- I see `preferences` and `updatePreferences` getting passed down via props to **a ton** of components. Rather than passing it down via props, you can just use the hooks in the component itself. Doing this will allow us to minimize the number of props and could help with the number of components re-rendering

2024-09-04 14:34 UTC, nikhagra-akamai commented
> My two main pieces of feedback are:
> 
> * `useRef` in `UserPreference.ts` **should not be necessary**. If it is necessary to make CloudPulse work, is indicative of a larger issues.
> * I see `preferences` and `updatePreferences` getting passed down via props to **a ton** of components. Rather than passing it down via props, you can just use the hooks in the component itself. Doing this will allow us to minimize the number of props and could help with the number of components re-rendering

Yes refs are needed because we are passing preference when the component initially renders and then we only allow component to render externally when major props change. If we remove refs then we have to call user preference in every component instead of props in this way we can completely remove internal state variable but my only concern is re-renderings will increase compare to what it is now

2024-09-05 16:37 UTC, jaalah-akamai commented
As discussed async - The plan is to move forward with removing the `preferences` and `updatePreferences` from being passed down via props and call the hook directly in the components that use preferences where it makes sense. For the components that only rely on preferences on initial load, we can just pass down the specific value they need instead of the entire preferences object which should help with re-rendering (since they're memoized components).

2024-09-09 13:57 UTC, nikhagra-akamai commented
> As discussed async - The plan is to move forward with removing the `preferences` and `updatePreferences` from being passed down via props and call the hook directly in the components that use preferences where it makes sense. For the components that only rely on preferences on initial load, we can just pass down the specific value they need instead of the entire preferences object which should help with re-rendering (since they're memoized components).

2024-09-10 05:36 UTC, venkymano-akamai commented on packages/api-v4/src/cloudpulse/types.ts
> +export type FilterValue =
we don't need this export, and no changes in this file, the types remain the same

2024-09-10 05:40 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +    if (!dashboardObj) {
We don't need this, because it will be disabled when there is no dashboard selected

2024-09-10 05:40 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +            savePreferences={true}
Just use, savePreferences

2024-09-10 05:42 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    preferences,
we can just pass defaultValue from preferences object here because we know we are building props for resource selection component

2024-09-10 05:43 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
> +    preferences,
same as above

2024-09-10 05:46 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +        value={{ ...selectedInterval }}
```suggestion
        value={selectedInterval}
```

2024-09-10 05:51 UTC, venkymano-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +      'Authentication-type': 'jwe',
we can revert this file to whatever develop branch has

2024-09-10 13:49 UTC, abailly-akamai commented
@nikhagra-akamai this PR is too far behind develop. Please rebase it to get some important updates merged recently and keep it up to date when working on it.

2024-09-10 14:10 UTC, nikhagra-akamai commented
> @nikhagra-akamai this PR is too far behind develop. Please rebase it to get some important updates merged recently and keep it up to date when working on it.

@abailly-akamai  I've synced it with developer

2024-09-11 00:43 UTC, jaalah-akamai requested changes
This appears much better in flickering and rendering. I would love to see if we can prevent the widget title from flickering when changing dropdown values.

I'm not sure I caught everything here, but hopefully it's a little better off.

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +  ) => oldProps.selectedDashboard?.id === newProps.selectedDashboard?.id
Nit: Types are inferred
```suggestion
    prevProps,
    nextProps
  ) => prevProps.selectedDashboard?.id === nextProps.selectedDashboard?.id
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
>            handleRegionChange(region);
Nit: While I was reviewing in here, we might as clean this up eventually
```
if (regions && savePreferences) {
  const defaultRegion = preferences?.region;
  const region = defaultRegion
    ? regions.find((obj) => obj.id === defaultRegion)?.id
    : undefined;
  
  setSelectedRegion(region);
  handleRegionChange(region);
}
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
>          onChange={(_: any, resourceSelections: CloudPulseResources[]) => {
I'd rather not use it and have it correctly infer than do `any`
```suggestion
        onChange={(e, resourceSelections: CloudPulseResources[]) => {
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +      setSelectedTimeRange(item);
I don't think there's a need to have two `setSelectedTimeRange` in this handler

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
>          onChange={(_: any, value: Item<Labels, Labels>) => {
```suggestion
        onChange={(e, value: Item<Labels, Labels>) => {
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
>          onChange={(_: any, dashboard: Dashboard) => {
```suggestion
        onChange={(e, dashboard: Dashboard) => {
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +          handleDashboardChange(undefined);
Nit:
```
const dashboard = defaultValue
  ? dashboardsList.find((obj: Dashboard) => obj.id === defaultValue)
  : undefined;
setSelectedDashboard(dashboard);
handleDashboardChange(dashboard);
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +      if (
For L65 did we want to spread the options to avoid mutating it? `[...options].sort` Just something to look into here

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
> +          savePreferences={true}
```suggestion
          savePreferences
```

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    updatePreferenceData?: {}
Note: In a future PR, I'd love to see `emitFilterChange` become object params for clarity and extensibility

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
>      const [, setDependentFilters] = React.useState<{
What's the purpose of this? Could it be removed?

2024-09-11 00:43 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelectUtils.ts
> +  savePreferences?: boolean;
Let's create a shared interface to avoid the duplication here and then just extend it:
``` 
interface CloudPulseCustomSelect {
  filterKey: string;
  handleSelectionChange: (
    filterKey: string,
    value: FilterValueType,
    savePref?: boolean,
    updatedPreferenceData?: Partial<AclpConfig>
  ) => void;
  preferences?: AclpConfig;
  savePreferences?: boolean;
}
```

2024-09-11 11:28 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
>            handleRegionChange(region);
updated

2024-09-11 11:44 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +      setSelectedTimeRange(item);
missed that, thanks for pointing out

2024-09-11 11:49 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +      if (
updated, but still I'll check whether we actually need to create the copy or mutating the original object will not create impace

2024-09-11 11:50 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
> +    updatePreferenceData?: {}
sure, I'll update it

2024-09-11 13:23 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
>      const [, setDependentFilters] = React.useState<{
@jaalah-akamai , this is needed as we need to trigger a state update so that the components gets re-rendered, on a dependent filter, for example

The resource selection is dependent on region selection

2024-09-11 13:38 UTC, nikhagra-akamai commented on packages/api-v4/src/cloudpulse/types.ts
> +export type FilterValue =
used that value as type of defaultValue prop

2024-09-11 13:40 UTC, nikhagra-akamai commented
@jaalah-akamai  I've pushed changes according to comments. Please re-review

2024-09-12 19:06 UTC, abailly-akamai reviewed
Some improvement to be made in UI and code. Besides my comments you also have to fix failing tests.

unrelated to this PR, noticing some styling issues on responsive sizes
![Screenshot 2024-09-12 at 14 09 59](https://github.com/user-attachments/assets/dccb3f22-6874-42ff-9d4e-3ea4b645baaa)

2024-09-16 08:50 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> -  }
@abailly-akamai a loading pattern is there unless the graph data is not loaded. May be it is happening because of mock data & causing a flickering effect because data loaded instantaneously and which making it seems like flickering. I've added a recording to fetch data from a local endpoint instead of mock data.

https://github.com/user-attachments/assets/b6d989c9-b449-4ec9-beb6-f5bdd40dd50d

2024-09-16 11:53 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    }, [resources]);
updated

2024-09-16 14:06 UTC, nikhagra-akamai commented on packages/manager/src/queries/cloudpulse/metrics.ts
> +    .catch((error) => Promise.reject(error.response?.data?.errors));
If one of the error is undefined then we are showing a default error message 'Error while rendering graph'

2024-09-16 14:25 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +    let default_value =
updated

2024-09-16 14:25 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +  };
updated

2024-09-16 14:33 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +        },
`widgetPreferences is of any type which i'd like to see improved`

it is not of any type but handled by typescript 
![Uploading Screenshot 2024-09-16 at 8.02.32 PM.jpg…]()

2024-09-16 15:16 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
> +        },
updated time granularity and added a optional label field

2024-09-16 15:18 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  }, []);
Working on tests

2024-09-16 15:20 UTC, nikhagra-akamai commented
@abailly-akamai  / @jaalah-akamai updated the review comments, please re-review and approve it all good

2024-09-16 18:00 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> -  }
I still see a lot of flickering in this video (the selects above each chart)

2024-09-17 00:51 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
>      const [, setDependentFilters] = React.useState<{
Ok thanks, that wasn't clear at all because it doesn't follow the React pattern of using state to drive UI updates. 

Instead of discarding the state value, you could use it directly `const [dependentFilters, setDependentFilters] = React.useState<{ [key: string]: FilterValueType; }>({});` and use that value instead of the ref `dependentFilterReference.current`?

2024-09-18 11:05 UTC, nikhagra-akamai commented
marking this as draft as we found out couple of bugs to fix with it

2024-09-23 13:24 UTC, nikhagra-akamai commented
@jaalah-akamai  / @bnussman-akamai  / @abailly-akamai 

I've made the changes according to our last discussion and making the PR for review so that you can start reviewing by then I'm working on fixing failing test cases / conflicts

These are the some major modification after our last discussion
1. Use ref in UserPreference so that we can have latest changes without making component to re-render
2. Added a cloudpulse widget render to render the widgets so that we can avoid widget re-renders because dashboard component re-renders forcefully on preference state changes. In this way we have reduced flickering fully from graph components

2024-09-23 18:46 UTC, coliu-akamai reviewed
in addition to the test failures/conflicts you mentioned, there are a few errors and values not used that will need to be addressed:
![image](https://github.com/user-attachments/assets/4077284f-dd53-45bb-bfe8-093e4fd61310)

I'm still seeing some flickering in the graph title units, not sure how big an issue this is:

https://github.com/user-attachments/assets/3b343068-ec96-4473-998a-3d1b84ded7f8

2024-09-24 02:04 UTC, venkymano-akamai commented on packages/api-v4/src/cloudpulse/services.ts
> +      `${API_ROOT}/monitor/services/${encodeURIComponent(
This file has no changes at all, we can revert this to existing state in dev branch

2024-09-24 02:07 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
> +    if (
Instead of clubbing multiple deepEqual like this in single if statement, we can use the same logic in our resourceselection component.

2024-09-24 02:09 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
> +  (prevProps, nextProps) => prevProps.zoomIn === nextProps.zoomIn
since we are not passing any properties regarding preferences here, whether it is even needed here?

2024-09-24 02:10 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +    prevProps.handleDashboardChange === newProps.handleDashboardChange
This is should not be needed according to our current logic, please remove

2024-09-24 02:10 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +    prevProps.selectedDashboard?.id === nextProps.selectedDashboard?.id
Please check, whether it is needed as well

2024-09-24 02:11 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    'handleResourcesSelection',
we can remove this as well

2024-09-24 02:11 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +    prevProps.handleStatsChange === newProps.handleStatsChange &&
remove this as well

2024-09-24 08:18 UTC, nikhagra-akamai commented
> in addition to the test failures/conflicts you mentioned, there are a few errors and values not used that will need to be addressed: ![image](https://private-user-images.githubusercontent.com/139280159/370006806-4077284f-dd53-45bb-bfe8-093e4fd61310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjU5NDMsIm5iZiI6MTcyNzE2NTY0MywicGF0aCI6Ii8xMzkyODAxNTkvMzcwMDA2ODA2LTQwNzcyODRmLWRkNTMtNDViYi1iZmU4LTA5M2U0ZmQ2MTMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTQzYzgzZTlkMDA5MzA5ZDIwYjRjOWRmNDVhYTY5YzE3ZWQ0ZjNkOWE0YTQ2NWExMjUzZmE3MGI5ZWMzMzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XEOMKR6rcHcktEKb-ETx6igrZsy1wgyT2_YHqul_GMI)
> 
> I'm still seeing some flickering in the graph title units, not sure how big an issue this is:
> 
>  title.unit.flickering.mov

sure I'm working on those lint errors.

Also the flickering issue was fixed in other PR by @venkymano-akamai  & it is merged in develop which I've synced in this PR. This flickering is resolved now. 


https://github.com/user-attachments/assets/06492bf1-43ce-4e10-8991-f01f6c7afb55

2024-09-24 10:16 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
> +    prevProps.selectedDashboard?.id === nextProps.selectedDashboard?.id
it'll be needed to render this component when dashboard Id changes

2024-09-24 10:20 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
> +  (prevProps, nextProps) => prevProps.zoomIn === nextProps.zoomIn
updated

2024-09-24 14:28 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +      </Paper>
sure I'll separate them

2024-09-24 14:28 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +const RenderDashboard = React.memo(
thanks for suggestions

2024-09-24 16:48 UTC, nikhagra-akamai commented
@cpathipa I've modulaized the code as per the suggestions please re-review

2024-09-24 17:22 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +import deepEqual from 'fast-deep-equal';
I have already suggested not doing a deepEqual, and you team already implemented my suggestion to do a prop based compare for the select here:
https://github.com/linode/manager/blob/develop/packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx#L229-L252

You can export that to a util and re-use it. Please keep track of the utils in your own feature and find the solutions we already solved before requesting reviews and/or alternatives to review comments.

2024-09-24 17:44 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +import deepEqual from 'fast-deep-equal';
In that case, we have to implement ka custom deep equal because if you see that function, it is also using once instance of deepEqual

2024-09-24 17:54 UTC, abailly-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +import deepEqual from 'fast-deep-equal';
That's what I meant - this was requested before. Using a sub-dependency is no good since it's dependency of a `launchdarkly` and this could make our path to update it a breaking change.

I don't know think a deep equal is needed at all. If you're following immutability principles, this simpler comparison should be sufficient and more performant. Your coverage will determine that. 

If you really need a deep Equal you could install `lodash.isEqual` but I'd rather avoid that too if the code below solves your problem

```
function compareProps(
  prevProps: CloudPulseResourcesSelectProps,
  nextProps: CloudPulseResourcesSelectProps
): boolean {
  // these properties can be extended going forward
  const keysToCompare: (keyof CloudPulseResourcesSelectProps)[] = [
    'region',
    'resourceType',
    'disabled',
    'placeholder'
  ];

  for (const key of keysToCompare) {
    if (prevProps[key] !== nextProps[key]) {
      return false;
    }
  }

  // Simple comparison for xFilter
  if (prevProps.xFilter !== nextProps.xFilter) {
    return false;
  }

  // Ignore function props in comparison
  return true;
}
```

2024-09-24 21:18 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +    let default_value =
Can you double check. It has not been updated from `default_value`.

2024-09-25 13:18 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
> +import deepEqual from 'fast-deep-equal';
updated the logic with custom deep equal for arrays

2024-09-25 20:23 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  }, []);
Can you provide more details regarding this? Are tests being included in an upcoming PR?

2024-09-25 20:44 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          onAggregateFuncChange(selectedAggregateFunc.label);
@nikhagra-akamai this may have been missed as well

2024-09-26 05:07 UTC, venkymano-akamai approved these changes

2024-09-26 07:57 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          onAggregateFuncChange(selectedAggregateFunc.label);
updated, the change was reverted while fixing some merge conflicts

2024-09-26 08:51 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +  }, []);
I've added global filters test cases in this PR only

2024-09-26 10:31 UTC, nikhagra-akamai commented
@abailly-akamai / @hkhalil-akamai I've updated all the changes and test cases as well. Please review it once & approve if all good

2024-09-26 14:45 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
> +  () => true
Should this be here? `useMemo` should only be used if necessary. Is it necessary here?

2024-09-26 14:45 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
> +    preferences: { ...(preferences?.aclpPreference ?? {}) },
What is going on here? Can this be

```suggestion
    preferences: preferences?.aclpPreference ?? {},
```

2024-09-26 14:45 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +): boolean => {
Utils like this need to be unit tested.

2024-09-26 14:45 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardRenderer.tsx
> +  }
I'm not saying this is wrong, but in my time writing React, I've never had to be this granular with memoization. I feel like things shouldn't have to be like this. 

I also wonder how the React 19 compiler could affect stuff like this

2024-09-26 15:06 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardRenderer.tsx
> +  }
I just checked this compare function will not be required, only surrounded with memo works

2024-09-26 15:15 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Utils/utils.ts
> +): boolean => {
I've removed this method, it is not required

2024-09-26 15:19 UTC, nikhagra-akamai commented
@bnussman-akamai  thanks for suggestions. Alot of not required code I've removed and pushed.

2024-09-27 16:55 UTC, bnussman-akamai approved these changes

2024-09-30 12:56 UTC, nikhagra-akamai commented
@jaalah-akamai / @abailly-akamai  / @hkhalil-akamai  can we have another approval & merge

2024-09-30 14:12 UTC, cpathipa approved these changes

2024-09-30 14:23 UTC, hkhalil-akamai approved these changes
Thanks for responding to feedback.

2024-09-30 14:38 UTC, nikhagra-akamai commented
@cpathipa @hkhalil-akamai thanks for the approvals

2024-09-30 20:41 UTC, jaalah-akamai approved these changes

2024-09-30 20:41 UTC, merged