upcoming: [DI-20501] - Fix Demo feedbacks and small bugs across ACLP
linode/manager pull request #10851
Opened 2024-08-29 07:56 UTC by venkymano

## Description 📝
Fixed demo feedbacks and small bugs across ACLP

## Changes  🔄

1. Fixed Dashboard Select placeholder from **Select a Dashboard to Select Dashboard**
2. Fixed striking functionality interchangeably while clicking native legend as well as legend table row.
3. Enhanced Region Selection component to honor the placeholder prop being passed.
4. Pass fill option to line graph only if the chart type is area.
5. Pass queried resource option for choosing default selections as well on the CloudPulseCustomSelect component
6. Integrate manual refresh functionality
7. Fix color for close icon in the CloudPulseResourcesSelection component
8. Update labels in time duration from **Past to Last**

## Target release date 🗓️
02-09-2024

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
|![Screenshot 2024-08-29 at 1 15 12 PM](https://github.com/user-attachments/assets/969e1b57-efb5-4276-9b4f-26aa44067908)|![Screenshot 2024-08-29 at 1 20 09 PM](https://github.com/user-attachments/assets/84f4bcc9-2cc2-413e-bcb7-ef6571e36bdb)|
|![Screenshot 2024-08-29 at 1 16 12 PM](https://github.com/user-attachments/assets/5b100d13-82cc-4003-b43d-5edefe7f0adb)|![Screenshot 2024-08-29 at 1 20 27 PM](https://github.com/user-attachments/assets/7d29e648-e871-4651-9428-af44599f4b59)|
|![Screenshot 2024-08-29 at 1 17 07 PM](https://github.com/user-attachments/assets/fa562bb4-e451-449c-9cef-c586e94e8f39)|![Screenshot 2024-08-29 at 1 21 09 PM](https://github.com/user-attachments/assets/bb54d463-28f1-42c7-8b31-f5b9976aca7a)|
|![Screenshot 2024-08-29 at 1 18 22 PM](https://github.com/user-attachments/assets/ec2454ba-3005-4dbc-9c17-4c72a73d006f)|![Screenshot 2024-08-29 at 1 20 48 PM](https://github.com/user-attachments/assets/2e0274bd-4d5c-4a3f-8a66-6102638b4e1a)|
|![Screenshot 2024-08-29 at 1 19 01 PM](https://github.com/user-attachments/assets/1b8e8029-dc33-46a5-8366-b3f7de524766)|![Screenshot 2024-08-29 at 1 21 31 PM](https://github.com/user-attachments/assets/460b58dc-90aa-464b-959a-bf47e1cd360d)|

## How to test 🧪

1. Enable mock service as some API endpoints are not available.
2. Click on the Monitor tab
3. You will be able to see the options and fixes
4. For global manual refresh, once you see the widgets rendered, click the refresh icon, you can see again the widgets are loaded.

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-08-29 08:47 UTC, venkymano commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +            handleLegendClick(legendItem.datasetIndex!);
FYI, this will strikeout the legend as well on nativelegend click

2024-08-29 08:48 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          borderColor: color,
FYI - pass border color for graphs

2024-08-29 08:48 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          fill: widgetChartType === 'area' ? true : false,
FYI - pass fill based on chart type

2024-08-29 08:53 UTC, venkymano commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +            handleLegendClick(legendItem.datasetIndex); // when we click on native legend, also call the handle legend click function
FYI - Even on clicking the native legend, make use of handle legend click functionality

2024-08-29 10:20 UTC, venkymano commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +    return { unit: 'days', value: 7 };
The metrics API understands days instead of day going forward

2024-08-29 10:44 UTC, nikhagra requested changes

2024-08-29 10:44 UTC, nikhagra commented on packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
> +      handleAnyFilterChange('timestamp', Date.now());
use REFRESH from constants instead of hardcoding 'timestamp'

2024-08-29 13:22 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          fill: widgetChartType === 'area' ? true : false,
```suggestion
          fill: widgetChartType === 'area',
```

2024-08-29 13:37 UTC, venkymano commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +          fill: widgetChartType === 'area' ? true : false,
@bnussman-akamai , fixed this comment, please check if it is good now

2024-08-30 03:23 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
> +              : [],
Nit: Would `options || queriedResources || []` give us the same here?

2024-08-30 03:56 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
> +              : [],
Yes, this will work as well, thanks for the simplification point

2024-09-02 04:13 UTC, kmuddapo approved these changes

2024-09-03 13:32 UTC, coliu-akamai commented on packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
> +    ''
nitpick: for readability, we could switch to having 

`const resource = resources.find((resourceObj) => String(resourceObj.id) === id);` 
(could name the const resourceObj instead)

outside of the return statement, and then here, just have 

`return resource?.label ?? id ?? '';`

2024-09-03 14:24 UTC, venkymano-akamai commented
@coliu-akamai , can you please check if it is good now

2024-09-03 16:19 UTC, coliu-akamai commented
This could just be a me problem, but I'm getting an error when trying to render all the graphs:
![image](https://github.com/user-attachments/assets/a449e6ca-27a5-4025-879f-7df1343d8659)

I have the CloudPulse flag and the MSW on - is there anything else I need to do?

2024-09-03 17:20 UTC, jaalah-akamai approved these changes
Thanks for making changes

2024-09-03 17:28 UTC, coliu-akamai approved these changes
✅ Fixed Dashboard Select placeholder from Select a Dashboard to Select Dashboard
✅ Fixed striking functionality interchangeably while clicking native legend as well as legend table row.
✅ Enhanced Region Selection component to honor the placeholder prop being passed.
✅ Integrate manual refresh functionality
✅ Fix color for close icon in the CloudPulseResourcesSelection component
✅ Update labels in time duration from Past to Last

Quick note for global refresh - seems like part of the title flickers. I'm unsure if this is an issue or not/or if it's already known, but here's the video in case:

https://github.com/user-attachments/assets/e8855e4e-e296-4656-80fc-391dbdc15d02

Had a couple of other minor comments below, but they're non-blocking. Thanks for the changes!

2024-09-03 17:28 UTC, coliu-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +              status === 'error' && error?.[0]?.reason !== jweTokenExpiryError // show the error only if the error is not related to token expiration
nitpick: now that `error?.[0]?.reason` is being used several times here and at lines 356, we could move it to a constant for better readability. Somewhere above, we could have something like `const metricsError = error?.[0]?.reason;` and then use `metricsError` here (potentially use a different name that better encompasses what the error is for)

2024-09-03 17:28 UTC, coliu-akamai commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +          if (legendItem && legendItem.datasetIndex!==undefined) {
Can we put spaces around the `!== `
(eslint complains otherwise)

2024-09-03 17:46 UTC, venkymano-akamai commented
@coliu-akamai , Thanks for the approval, i have fixed those minors. Also the flickering is due to preferences, for which we have a separate PR that is also under review

2024-09-03 23:50 UTC, merged