test: [M3-8485] - Unit Tests for Object Storage Gen2 feature
linode/manager pull request #10862
Opened 2024-08-30 06:18 UTC by harsh-akamai

## Description 📝
Unit tests for Bucket Landing page, Bucket Detail Drawer and Object Detail Drawers.

## Changes  🔄

- Added test to check if "Endpoint Type" column is displayed
- Added test to check if the CORS switch is disabled for E2 and E3 buckets in the Bucket Details Drawer
- Added test to check if the Bucket Rate Limit table is rendered for E2 and E3 buckets in the Bucket Detail Drawer
- Added test to check if the ACL switch is disabled for E2 and E3 buckets  in the Object Details Drawer

## Target release date 🗓️
N/A

## How to test 🧪

### Verification steps

- Run the unit tests for Object Storage feature and check if all tests pass.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-08-30 16:54 UTC, coliu-akamai reviewed
✅ confirmed tests pass - thanks for adding test coverage!

Some v small comments + one question below

2024-08-30 16:54 UTC, coliu-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
> +  it('doesnt show the CORS switch for E2 and E3 buckets', async () => {
```suggestion
  it("doesn't show the CORS switch for E2 and E3 buckets", async () => {
```

2024-08-30 16:54 UTC, coliu-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
> +  });
I'd added a `data-testid="bucket-rate-limit-table"` to the BucketRateLimitTable for testing - if you merge develop into your branch, you can use it here too with `getByTestId`

2024-08-30 16:54 UTC, coliu-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.test.tsx
> +    expect(getByText('Endpoint Type')).toBeVisible();
We could also check that the bucket's endpoint type itself is visible 
`expect(getByText('Standard (E3)')).toBeVisible();`

2024-08-30 16:54 UTC, coliu-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +        {Boolean(endpoint_type) && (
are the changes in this file just for stuff that was missed earlier? I don't see anything mentioned in the AC or ticket description about them

2024-09-02 05:10 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +        {Boolean(endpoint_type) && (
Yes, these changes are stuff that was missed earlier.

2024-09-03 14:00 UTC, coliu-akamai approved these changes

2024-09-03 16:24 UTC, cpathipa approved these changes
All tests passed! thank you adding unit test coverage.

2024-09-03 19:29 UTC, hkhalil-akamai commented
The ticket mentions updating integration tests to reflect the new changes. Is this still required (perhaps updating `bucket-create-gen2.spec.ts`)?

2024-09-04 06:22 UTC, harsh-akamai commented
> The ticket mentions updating integration tests to reflect the new changes. Is this still required (perhaps updating `bucket-create-gen2.spec.ts`)?

@hkhalil-akamai the ticket asked to perform integration tests to ensure the UI changes function as expected without affecting other feature. If we need to update the integration tests I guess handling that in a different ticket/PR would be better

2024-09-04 17:47 UTC, hkhalil-akamai approved these changes

2024-09-10 21:33 UTC, hkhalil-akamai requested changes

2024-09-10 21:33 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
Using `renderWithThemeAndHookFormContext` is unnecessary since the component doesn't need a Hook Form Context. Use `renderWithTheme` instead.

2024-09-10 21:33 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
> +    const rateLimitTable = getByTestId('bucket-rate-limit-table');
This test is failing since `isObjectStorageGen2Enabled` is derived from an RQ hook and is initially `undefined`. Awaiting via `await findByTestId` will wait for the query to resolve.

```suggestion
    const { findByTestId } = renderWithTheme(
      <BucketDetailsDrawer
        onClose={mockOnClose}
        open={true}
        selectedBucket={e3Bucket}
      />,
      {
        flags: { objMultiCluster: false, objectStorageGen2: { enabled: true } },
      }
    );

    const rateLimitTable = await findByTestId('bucket-rate-limit-table');
```

2024-09-10 21:33 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
> +    ).toBeInTheDocument();
```suggestion
    const { findByText } = renderWithTheme(
      <BucketDetailsDrawer
        onClose={mockOnClose}
        open={true}
        selectedBucket={e1Bucket}
      />,
      {
        flags: { objMultiCluster: false, objectStorageGen2: { enabled: true } },
      }
    );
    expect(
      await findByText(
        /This endpoint type supports up to 750 Requests Per Second \(RPS\)./
      )
    ).toBeInTheDocument();
```

2024-09-11 08:10 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
Currently the component doesn't need a Hook Form, but [M3-8501](https://jira.linode.com/browse/M3-8501)(optimzing AccessSelect.tsx using Hook Form) is in progress. Hence, I decided to go with `renderWithThemeAndHookFormContext`

2024-09-11 08:11 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
> +    const rateLimitTable = getByTestId('bucket-rate-limit-table');
Thank you so much for pointing this out! I've made the changes in 8974ea41a7d26f46fdb12d9f33c0e56cec2513c0

2024-09-11 15:53 UTC, hkhalil-akamai approved these changes
Thanks for making requested changes! Approved pending CI passes!

2024-09-11 15:53 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
Ohhh understood. Sounds good!

2024-09-11 16:23 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
For future reference, each PR should be self-contained and should not include changes for another ticket. This prevents issues when, for example, the other ticket is closed or modified.

2024-09-11 16:27 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
Noted 🗒️

2024-09-12 06:22 UTC, merged