refactor: [M3-8496] - Remove Placement Group flag and underlying logic
linode/manager pull request #10877
Opened 2024-09-03 20:55 UTC by abailly-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-09-04 18:03 UTC, carrillo-erik requested changes
These are the culprits causing the failures in the PR. Removing these should do the trick.

2024-09-04 18:03 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>    it('does not show Placement Groups navigation item when feature is disabled', () => {
This should be removed since we are no longer using the feature flag.

2024-09-04 18:03 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>    it('displays Not Found when manually navigating to /placement-groups with feature flag disabled', () => {
This one should also be removed since it becomes redundant without the feature flag.

2024-09-04 18:07 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>     * - Confirms that clicking Placement Groups navigation item directs user to Placement Groups landing page.
Can we delete the comment in line 19 that references a feature flag?

2024-09-04 18:07 UTC, mjac0bs commented on packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
> +  it('renders an placement group details', async () => {
Nit:
```suggestion
  it('renders placement group details', async () => {
```

2024-09-05 15:57 UTC, abailly-akamai commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts
>    // Mock the VM Placement Groups feature flag to be enabled for each test in this block.
fixed!

2024-09-05 15:57 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
> +  it('renders an placement group details', async () => {
fixed!

2024-09-05 15:57 UTC, abailly-akamai commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>     * - Confirms that clicking Placement Groups navigation item directs user to Placement Groups landing page.
yup

2024-09-05 15:57 UTC, abailly-akamai commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>    it('displays Not Found when manually navigating to /placement-groups with feature flag disabled', () => {
fixed

2024-09-05 15:58 UTC, abailly-akamai commented on packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
>    it('does not show Placement Groups navigation item when feature is disabled', () => {
fixed

2024-09-05 16:02 UTC, mjac0bs approved these changes
Thanks, this should be set now! 🚢

2024-09-05 17:00 UTC, jaalah-akamai approved these changes
🧹

2024-09-05 21:37 UTC, carrillo-erik approved these changes

2024-09-06 01:20 UTC, merged