upcoming: [DI-20555] - Added the Alerts tab and Create Alert Definition component
linode/manager pull request #10900
Opened 2024-09-06 09:07 UTC by santoshp210

## Description 📝
Added Alert tab under Monitor for the alerting services. Added the Create Alert Definition component under Alert Definition sub-tabs with few Basic components as part of the Create Alert Definition form.

## Changes  🔄
List any change relevant to the reviewer.
- Added Alerts tab under Monitor which is visible when at least one flag of the sub-tabs is accessible(via feature flag)
 -Added Recent activity, Alert Definitions, Notification channels tabs under Alert and the tabs visible only when they're accessible through feature flags
- Added a Create button for the Create Alert Definition form under Alert Definitions
- Added few basic components as part of the Create Alert Definition form.

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-09-04 at 14 47 05](https://github.com/user-attachments/assets/6fe23259-075c-4f91-b6fc-fb51c1f3338e) | ![Screenshot 2024-09-06 at 14 31 16](https://github.com/user-attachments/assets/6677b5f8-2fd1-4efc-a670-482efab3e279) ![Screenshot 2024-09-06 at 14 31 24](https://github.com/user-attachments/assets/981fc27e-eb80-4a4e-9db0-1ab621f5b7ee) |

## How to test 🧪
- Switch to mock user as APIs are not live and for the feature flags(Legacy MSW handlers)
- The Create Alert definition form is rendered after clicking on the Create button under Alert definition

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-09-06 15:01 UTC, bnussman-akamai requested changes

2024-09-06 15:01 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +            p: 2,
Why does this paper have such thick padding?

![Screenshot 2024-09-06 at 11 00 16 AM](https://github.com/user-attachments/assets/a679c356-ba8c-4350-b3fc-4b3692d98a54)

2024-09-06 15:06 UTC, santoshp210 commented on packages/api-v4/src/cloudpulse/types.ts
> +  severity: string;
Yeah it should be an enum, I'll make that change.

2024-09-06 15:10 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +                transform: 'scale(0.75)',
Sure, I'll see if there's an alternative way to achieve the same result

2024-09-06 15:37 UTC, jaalah-akamai commented
I'm going to send this back to draft until @venkymano-akamai or @nikhagra-akamai have a chance to review and give their approval

2024-09-09 05:26 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +          <ErrorMessage errors={errors['name']} touched={touched['name']} />
We did it this way so there'll be consistency with the errors from Autocomplete

2024-09-09 05:38 UTC, santoshp210 commented
> I'm going to send this back to draft until @venkymano-akamai or @nikhagra-akamai have a chance to review and give their approval

There was already a round of review with them and these are changes approved by them.

2024-09-09 05:58 UTC, santoshp210 commented on packages/api-v4/src/cloudpulse/alerts.ts
> +  );
@bnussman-akamai , Yeah the API specification for the alerting services is different document and it's still in progress. The endpoints or types that are written as per the document. Some specifics might change through the review process of the document, if those changes do occur we plan on updating them here.

2024-09-09 06:01 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const formik = useFormik({
@bnussman-akamai , Is there any specific reason to use `react-hook-form` instead of `formik`. We went with the implementation of formik, because took an example from component like `DatabaseCreate.tsx`.

2024-09-09 06:37 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +                transform: 'scale(0.75)',
I will wrap the the Button in a Box component to align with our design mockups .

2024-09-09 06:41 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  );
@bnussman-akamai , We did this way so we can have a generic function. But to avoid this complexity can we have directly pass the overrides with the labels and appropriate links ?

2024-09-09 06:44 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  };
The actual form has a lot of components, and from our internal review with @venkymano-akamai we were suggested that the it was complex to have a condition for each of the component.

2024-09-09 06:53 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/constants.ts
> +];
According to the ongoing discussion on the API specification , the expected payload as of the recent discussion is that it is going to be string type and should send just the string `Severe` or `Medium` accordingly. I will be making these changes.

2024-09-09 14:31 UTC, jaalah-akamai commented
Ok I plan to review this today 👍

2024-09-10 17:42 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const formik = useFormik({
We are phasing out `formik ` in favor of `react-hook-form`. `react-hook-form` features better type-safety and more performant patterns.

2024-09-10 20:21 UTC, hkhalil-akamai commented on packages/manager/src/featureFlags.ts
> +}
Is this interface correctly specified? Should the types be `boolean` instead of `true` or `false`?

2024-09-10 20:21 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
> +        component={() => <CreateAlertDefinition />}
```suggestion
        component={CreateAlertDefinition}
```

2024-09-10 20:21 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +            component={() => <AlertDefinitionLanding />}
```suggestion
            component={AlertDefinitionLanding}
```

2024-09-11 04:28 UTC, santoshp210 commented on packages/manager/src/featureFlags.ts
> +}
That's a mistake, idk how I missed it. I will change it right now.

2024-09-11 05:09 UTC, santoshp210 commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +              label: 'Submit',
@bnussman-akamai , This was what was decided from the Team and the UI/UX discussions. The reasoning is that since the user will be in the Alert Definitions tab it is understood the create and submit are for Creating and Submitting the Alert Definition.

2024-09-12 14:03 UTC, santoshp210 commented
@jaalah-akamai As per the recent changes regarding formik being deprecated. We would like to close this PR for now , implement the form with `react-hook-form` and then open the PR. Thank you!

2024-09-12 14:03 UTC, closed without merging