fix: [M3-7571] - Missing label for Full Account Access Toggle
linode/manager pull request #10931
Opened 2024-09-12 20:13 UTC by carrillo-erik

## Description 📝
This PR addresses the issue of the "Full Account Access" toggle missing a proper label. The changes in this PR improve accessibility in two ways. First by implementing correct markup semantics. Second, by ensuring screen readers inform the user more adequately by enhancing the output that is read.

## Changes  🔄
List any change relevant to the reviewer.
- Separates the "Full Account Access" toggle from the "User Permissions" header.
- Changes the `variant` property for some `Typography` components to ensure proper `Header` levels.
- Update e2e tests

## Target release date 🗓️
09/30/2024

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![m3-7571-screenreader-before](https://github.com/user-attachments/assets/eef372e2-fcc0-486f-bbaf-f5b2b61c892c) | ![m3-7571-screenreader-after](https://github.com/user-attachments/assets/5ba33ee4-8739-4226-9c0c-ac8ac5599b6b) |
| ![m3-7571-desktop-before](https://github.com/user-attachments/assets/6faa16e9-8101-476e-b3d1-ba5d589f70b6) | ![m3-7571-desktop-after](https://github.com/user-attachments/assets/0a595c68-1241-4af1-a968-d0283aa728fa) |
| ![m3-7571-mobile-before](https://github.com/user-attachments/assets/e0090352-d4d6-44af-a4af-0e092173c0b1) | ![m3-7571-mobile-after](https://github.com/user-attachments/assets/fd51f353-a23e-412f-9a29-87bed97fdc4e) |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- Visit the User Permissions landing page and activate the VoiceOver Utility (⌘ + F5) on your MAC computer.

### Verification steps
(How to verify changes)
- Use your keyboard to navigate to the "Full Account Access" toggle and changed the value a few times.
- Pay attention to the audio output of the VoiceOver utility and/or inspect the text transcript to verify the expected output.
- Verify that all Permission-related functionality works as expected.
- Verify that there are no unexpected visual regressions.

## As an Author I have considered 🤔
*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-09-13 15:48 UTC, abailly-akamai requested changes
Thx! - Accessibility fix looks good but the headings composition needs to be reverted

2024-09-13 15:48 UTC, abailly-akamai commented on packages/manager/src/features/Users/UserPermissions.tsx
> +              variant="h1"
You have two `h1` on the page now (the breadcrumb's last crumb is the title/h1 for the page by default)

2024-09-13 15:48 UTC, abailly-akamai commented on packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
> +            variant="h2"
This would have to be reverted as well based on the comment above

2024-09-13 15:48 UTC, abailly-akamai commented on packages/manager/src/features/Users/UserPermissions.tsx
> +            <Typography data-qa-permissions-header="billing" variant="h2">
same - the headings composition was already correct

2024-09-17 00:33 UTC, jaalah-akamai approved these changes
Yea these are good pending changes

2024-09-17 18:25 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +    cy.findByText('Full Account Access').should('be.visible').click();
@bnussman-akamai It's a valid question and I was confused by this as well. The error from running the cypress debug command states "The element is not visible because it has CSS property: `opacity: 0`."

Looking at the [Cypress docs](https://docs.cypress.io/guides/references/best-practices#How-It-Works), as a best practice, they recommend using `data-*` attributes to provide context to selectors and isolate them from CSS or JS changes. With that in mind, I went ahead and implemented this and confirmed the tests are still passing and VoiceOver works as expected.

2024-09-17 19:06 UTC, carrillo-erik commented on packages/manager/src/features/Users/UserPermissions.tsx
> +            <Typography data-qa-permissions-header="billing" variant="h2">
I found the culprit that led me to miscalculate the header order based on the Lighthouse tool. I've reverted the headers and updated the variant for the appropriate element.
![Screenshot 2024-09-17 at 11 49 22 AM](https://github.com/user-attachments/assets/54d4f492-59ea-4952-bf34-01811bff69a5)

2024-09-17 19:06 UTC, carrillo-erik commented on packages/manager/src/features/Users/UserPermissions.tsx
> +              variant="h1"
Got it. This has been reverted.

2024-09-17 20:12 UTC, bnussman-akamai commented on packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
> +    cy.findByText('Full Account Access').should('be.visible').click();
Understood! Thanks for the context 🙏

2024-09-17 21:08 UTC, abailly-akamai approved these changes
Thanks for addressing the changes - change looks good from my end and addresses the accessibility issue ✅

2024-09-23 16:32 UTC, merged