refactor: [M3-8501] - AccessSelect Optimization: Use React Hook Form
linode/manager pull request #10952
Opened 2024-09-17 12:29 UTC by harsh-akamai

## Description 📝
The goal is to see if we can eliminate the number of useState calls we're making in this file and potentially remove the useEffect by using React Hook Form and inferring values from other values.

## Changes  🔄
- Replaced the existing queries with `react-query` queries and mutations for managing state
- Used React Hook Form for better state management

## Target release date 🗓️
N/A

## How to test 🧪

### Verification steps
- Check if the AccessSelect component's functionality is unaffected by the changes

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-09-18 13:36 UTC, abailly-akamai commented
@harsh-akamai can you make sure to fix your unit tests before people review the PR?

2024-09-20 11:39 UTC, harsh-akamai commented
@abailly-akamai I have fixed the failing unit tests

2024-09-27 13:23 UTC, abailly-akamai requested changes
Thanks for working on this. The change makes sense and the code cleanup looks good, and is well self documented and tested

There is a state issue in the form however. The cors toggle shows always as enabled on page load, no matter it's value.

https://github.com/user-attachments/assets/5199dd40-89dd-43da-be64-5fce22c96afb

Looks like e2e test failures are flakes. You may want to rebase your PRA again to get the latest from develop since those have been fixed there i believe

2024-09-27 13:23 UTC, abailly-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +    (variant === 'bucket' || variant == 'object') &&
no reason to remove strict equality here

2024-09-30 10:55 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +    (variant === 'bucket' || variant == 'object') &&
Fixed this and the CORS toggle issue in cd6919b603e8ce2c6b5eed2d291676f4586c935f

2024-10-01 13:17 UTC, abailly-akamai approved these changes
Looks good, thanks for addressing the fix.

Approving, and leaving a few optional UI improvements to consider, out of the scope but we may as well tackle them now:

![Screenshot 2024-10-01 at 09 14 19](https://github.com/user-attachments/assets/c29ff2a1-eeb9-40b8-8fc6-852de2316a97)

2024-10-02 16:39 UTC, jaalah-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> -  ACLType,
We'll need this back with my suggested changes

2024-10-03 10:26 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +  }, [bucketAccessData, objectAccessData, variant, reset]);
I think removing useEffect might not solve the issue in this case since the `useForm` hook reads the `defaultValues` only on the initial render. Updating `defaultValues` to the values returned from the api wouldn't update the form state. We will have to use the `reset()` to update the form and I feel we will have to run `reset()`  inside a useEffect.

2024-10-08 07:37 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +  }, [bucketAccessData, objectAccessData, variant, reset]);
Looks like passing the `formValues` to the `values` parameter of useForm() removes the necessity of `useEffect()`.  I have pushed these changes in the latest commit(https://github.com/linode/manager/pull/10952/commits/9a2430fcbdcf0bfd4e80e7e2a7276d099c7fe2fb)

2024-10-14 23:05 UTC, mjac0bs approved these changes
Coming late to this PR, but wanted to prevent it from getting stale. I didn't notice any major regressions in the Access Select and test are passing. I did notice a minor regression in loading state (see video clips).

Also re-requesting Jaalah since this PR is blocked by requested changes that, I think, have all been addressed now.

2024-10-14 23:05 UTC, mjac0bs commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +              bucketAccessIsFetching || objectAccessIsFetching
This doesn't seem to be working as expected. We have a small regression in the loading state but I wasn't seeing why right off. We have the `loading` prop and the fetching state of the two queries. Autocomplete has the `loadingText` prop, but I don't think that makes a difference.

| Prod | This Branch |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/25465406-7266-4665-9a0b-b6c6720a1337"/> | <video src="https://github.com/user-attachments/assets/c0a82b4d-a6b2-44fb-8d82-411ff8a9ef53"/> |

2024-10-15 04:37 UTC, harsh-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +              bucketAccessIsFetching || objectAccessIsFetching
Thanks for pointing this out! The issue stems from setting default values for the form. One possible workaround is to add an option to the `Options` array with the placeholder text 'Loading access..', though I am uncertain if this would be the most optimal solution for maintaining clean and efficient code.

2024-10-22 13:03 UTC, abailly-akamai commented
@harsh-akamai what is the status of this PR? @jaalah-akamai I think you requested changes, unsure if they have been addressed.

May be a good idea to rebase for good measure as well 👍

2024-10-22 13:52 UTC, jaalah-akamai commented
Yea @harsh-akamai let's rebase and I'll give this another pass today 👍

2024-10-22 14:18 UTC, harsh-akamai commented
Rebased the PR with the latest changes on develop

2024-10-22 17:24 UTC, jaalah-akamai commented on packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
> +              bucketAccessIsFetching || objectAccessIsFetching
I think this is ok actually... we default to `private` automatically upon bucket creation and we still show a loading state/spinner.

@harsh-akamai Can we remove the placeholder code? I don't think that's relevant anymore

2024-10-22 17:24 UTC, jaalah-akamai approved these changes

2024-10-22 21:48 UTC, merged