feat: [UIE-8098] - DBaaS 2.0 Landing Page GA
linode/manager pull request #11039
Opened 2024-10-02 16:01 UTC by mpolotsk-akamai

## Description 📝
DBaaS 2.0 Landing Page GA

## Changes  🔄
List any change relevant to the reviewer.
- Added Action Menu Column to the Databases Table
- Updated Database Logo (removed Beta)

**Note: The suspend action menu item will be added with the suspend feature in a separate PR.**

## Target release date 🗓️
10/14/24

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-10-02 at 5 47 55 PM](https://github.com/user-attachments/assets/fc3b6cc5-4c25-48ae-8aaf-45f99f85cd3f) | ![Screenshot 2024-10-02 at 5 48 24 PM](https://github.com/user-attachments/assets/28c09a24-e8a7-4aeb-b2e6-757776239497) |
| | ![Screenshot 2024-10-02 at 5 48 38 PM](https://github.com/user-attachments/assets/b8422e69-bf28-4133-a95a-506ae61f63a9) |

## How to test 🧪

### Prerequisites
(How to setup test environment)
**Note: For testing this change, ensure that DBaaS v2 is enabled, Beta is turned off, and the user has the "Managed Databases" account capability.**

### Verification steps
(How to verify changes)
- Navigate to the Databases section.
- The Databases table will display an additional Action Menu column.
- Click on the Action Menu to reveal a dropdown with available actions.
- From the Action Menu, the user can manage the database cluster,  just like in the Settings tab.
- Clicking Resize from the Action Menu will redirect you to the Resize tab.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-10-03 14:11 UTC, bnussman-akamai commented
Looks like we have a failing unit test 👀

2024-10-03 14:29 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +  handlers?: ActionHandlers;
Could we make handlers required in `DatabaseRow` and `DatabaseActionMenu` so we don't have to handle the undefined case?

2024-10-03 14:29 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +            updateDatabase={updateDatabase}
Can we move the `useDatabaseMutation` / `updateDatabase` function into `AddAccessControlDrawer` so that it doesn't need to be a prop?

2024-10-03 14:29 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +  const [allowList, setAllowList] = React.useState<ExtendedIP[]>([]);
We shouldn't need to have `allowList` as state in this component. Can we just pass `selectedDatabase` to `AddAccessControlDrawer` and handle all of the state inside of `AddAccessControlDrawer`?

2024-10-03 14:29 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +        ''
Do we need this `''`? Can we just use the following?

```
{isNewDatabase && (
```

2024-10-03 16:29 UTC, cpathipa reviewed
Failed unit test in `DatabaseLanding.test` on this branch. left a few comments, other than that functionality LGTM! Agreed with Banks feedback.

2024-10-03 16:29 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
> +            marginTop: !isV2GAUser ? '8px' : '',
I recommend leveraging theme values for consistency instead of hardcoded.

2024-10-07 17:05 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +  handlers?: ActionHandlers;
Done

2024-10-07 17:05 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +            updateDatabase={updateDatabase}
Done

2024-10-07 17:05 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +  const [allowList, setAllowList] = React.useState<ExtendedIP[]>([]);
Done

2024-10-07 17:06 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +        ''
Done

2024-10-07 17:07 UTC, corya-akamai commented on packages/api-v4/.changeset/pr-11039-added-1727885059968.md
> +allow_list to the DatabaseInstance ([#11039](https://github.com/linode/manager/pull/11039))
Done

2024-10-07 17:07 UTC, corya-akamai commented on packages/manager/.changeset/pr-11039-upcoming-features-1727885138241.md
> +Landing Page for DBaaS V2 GA ([#11039](https://github.com/linode/manager/pull/11039))
Done

2024-10-07 17:07 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +      disabled: databaseStatus !== 'running',
Done

2024-10-07 17:08 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +      onClick: handlers ? handlers.handleResetPassword : () => {},
Done

2024-10-07 17:09 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    legacyDatabases?.data.length === 0 || legacyDatabases === undefined;
Done

2024-10-07 17:17 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
> +            marginTop: !isV2GAUser ? '8px' : '',
Done

2024-10-07 19:44 UTC, cpathipa requested changes
@corya-akamai Thank you for addressing the feedback. I left a minor comment to remove a redundant undefined check, and there is a unit test failure that should be fixed. Other than that, the PR is good to go.

2024-10-07 19:44 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    !legacyDatabases?.data?.length || legacyDatabases === undefined;
@corya-akamai Do we still need undefined check ? I think !legacyDatabases?.data? should cover both the cases.

2024-10-07 19:44 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    !newDatabases?.data?.length || newDatabases === undefined;
@corya-akamai Do we still need undefined check ? I think !newDatabases?.data? should cover both the cases.

2024-10-07 19:44 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +      _allowList: database!.allow_list.map(stringToExtendedIP),
@corya-akamai Looks like there is unit test failure here.

2024-10-07 20:32 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    !legacyDatabases?.data?.length || legacyDatabases === undefined;
@cpathipa good catch, nope, I've removed the undefined check. We still need to check for both legacy and default

2024-10-08 01:35 UTC, cpathipa approved these changes
@corya-akamai Thank you for addressing all the feedback. Changes LGTM!

2024-10-08 15:07 UTC, bnussman-akamai commented
There are some failing unit tests that need to be addressed

2024-10-08 15:13 UTC, bnussman-akamai reviewed
I'm seeing a stray `0` and none of my databases are showing up 😰 when testing this PR against the dev API

![Screenshot 2024-10-08 at 11 11 02 AM](https://github.com/user-attachments/assets/3d24df0a-2f3c-4cfd-b994-12234c5cb360)

2024-10-08 19:22 UTC, corya-akamai commented
> I'm seeing a stray `0` and none of my databases are showing up 😰 when testing this PR against the dev API
> 
> ![Screenshot 2024-10-08 at 11 11 02 AM](https://private-user-images.githubusercontent.com/115251059/374618274-3d24df0a-2f3c-4cfd-b994-12234c5cb360.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTQ0OTIsIm5iZiI6MTcyODQxNDE5MiwicGF0aCI6Ii8xMTUyNTEwNTkvMzc0NjE4Mjc0LTNkMjRkZjBhLTJmM2MtNGNmZC1iOTk0LTEyMjM0YzVjYjM2MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTAzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2UzZGEwYTE1ZGZkMjc4NDNhYzUwOWFkOTcxZDEwNWQ4NWU5YjdhZjQyNDQ5ZWI5NGZjY2UyZWU5MDcyZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VXSh9Z6fm-7nYYrD1P78e64KwUoJeDqsy2PDSY5jDBU)

@bnussman-akamai Can you try now?

2024-10-09 15:58 UTC, cpathipa commented
@corya-akamai There still a unit test failing in this one 

![image](https://github.com/user-attachments/assets/106b8f6f-15f7-47cf-b726-74250c46b566)

2024-10-09 20:00 UTC, bnussman-akamai approved these changes

2024-10-09 20:00 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +          ></DatabaseActionMenu>
```suggestion
          />
```

2024-10-09 20:02 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +      )}
Because we are conditionally rendering these dialogs/drawers. The open/close animation is broken. It is noticeable on `AddAccessControlDrawer`. We should consider keeping them rendered at all times. This is usually how we keep the animation working.

2024-10-09 21:07 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +      )}
Good catch @bnussman-akamai I'll address it. There also seems to be an issue with sorting that needs to be addressed before merging.

2024-10-10 13:48 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +          ></DatabaseActionMenu>
Done

2024-10-10 13:49 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +      )}
@bnussman-akamai I updated so the animation is working. The sorting is not workin for the "new" tab but that is a backend issue they are working on..

2024-10-10 17:57 UTC, mjac0bs commented
Test failures in CI were unrelated (Cypress failures on delete placement group spec and vpc landing page) and component test failures due to memory issues. Unit tests pass now. Going to merge.

2024-10-10 17:58 UTC, merged