feat: [UIE-8089] - DBaaS Resize GA
linode/manager pull request #11040
Opened 2024-10-02 23:08 UTC by smans-akamai

## Description 📝
DBaaS Resize GA

## Changes  🔄
List any change relevant to the reviewer.
- Added Number of Nodes selector to the Database Resize tab

## Target release date 🗓️
10/14/24

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![Before](https://github.com/user-attachments/assets/e8b04cfc-4826-4157-a393-2cf5c120ea30)| ![After](https://github.com/user-attachments/assets/8922088a-6915-49a7-b035-9a3ea1f09c43) |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- For testing this change, ensure that DBaaS v2 is enabled, Beta is turned off, and the user has the "Managed Databases" account capability

### Verification steps
(How to verify changes)
- Navigate to the Databases section.
- Select the New Databases tab and click into one of the databases to see your details
- Navigate to the Resize tab
- Scroll down below the plans selection to view the Number of Nodes section is visible
- Verify that the correct node options are visible in the different tabs (ie. Dedicated vs Shared, etc)
- Verify that your current cluster size is selected and that lower sizes are disabled
- Verify that making a higher node selection enables the Resize button

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-10-08 14:32 UTC, cpathipa requested changes

2024-10-08 14:32 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +    marginRight: '10px',
Can we use theme values here ?

2024-10-08 14:32 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +            Please select a plan or set the number of nodes.
Can we simplify this to something like this? 
```
{summaryText ? (
  <>
    <StyledPlanSummarySpan>
      Resized Cluster: {summaryText.plan}
    </StyledPlanSummarySpan>{' '}
    {isDatabasesGAEnabled && (
      <span className={classes.summarySpanBorder}>{summaryText.basePrice}</span>
    )}
    <span className={isDatabasesGAEnabled ? classes.nodeSpanSpacing : ''}>
      {summaryText.numberOfNodes} Node{summaryText.numberOfNodes > 1 ? 's' : ''}
      {isDatabasesGAEnabled ? ' - HA ' : ': '}
    </span>
    {summaryText.price}
  </>
) : (
  <>
    <StyledPlanSummarySpan>Resized Cluster:</StyledPlanSummarySpan>{' '}
    {isDatabasesGAEnabled
      ? 'Please select a plan or set the number of nodes.'
      : 'Please select a plan.'}
  </>
)}
```

2024-10-08 15:04 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
> +      fireEvent.click(selectedNodeRadioButton);
we should prefer `userEvent` over `fireEvent` whenever possible: https://testing-library.com/docs/user-event/intro/#differences-from-fireevent

```suggestion
      await userEvent.click(selectedNodeRadioButton);
```

2024-10-08 19:40 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +    marginRight: '10px',
Thanks @cpathipa! I've applying the theme spacing to the padding and margins instead of px.

2024-10-08 19:44 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +            Please select a plan or set the number of nodes.
@cpathipa Unfortunately, there isn't an easy way to simplify this since many of the smaller changes in the markup are hidden behind that flag so that they won't show without it.

I didn't include this in the my changes, but perhaps we could rework this in a future PR or refactor.

2024-10-08 19:45 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
> +      fireEvent.click(selectedNodeRadioButton);
Thanks @bnussman-akamai! I've included this changes in the test file!

2024-10-08 20:02 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +          'Please select a plan or set the number of nodes.'
This was part of the old version, so I've excluded this change as well.

2024-10-09 13:37 UTC, cpathipa approved these changes
Changes look good to me! Approving pending tests and follow-up tickets for refactoring the DatabaseResize component.

2024-10-09 14:53 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
> +            Please select a plan or set the number of nodes.
@cpathipa There's an upcoming ticket to refactor the CreateDatabase and ResizeDatabase components since they share a lot similar features (ie. node selector, summary). The ticket is **UIE-8082** and that work is set for the 10/28 release and will involve breaking down these similar features into smaller, shared components.

So we should be able to move ahead with this change and address the tech debt and maintainability for these 2 components with that upcoming ticket.

2024-10-09 14:57 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
This file needs so serious work
- There is way too much state
  - State like `summaryText`, `nodePricing` , and `shouldSubmitBeDisabled` all seem like states that do not need to exist. They likely should be `const`s that are derived from existing state. See https://medium.com/@noriller/react-state-x-derived-state-97ff47769914 
  - Fixing these unessesary states will hopefully allow us to remove the `useEffects`. We are really trying to eliminate use of `useEffect` in Cloud Manager because they are bug prone and generally a sign of bad state management

2024-10-09 15:12 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
@bnussman-akamai 
There's an upcoming ticket to refactor the CreateDatabase and ResizeDatabase components since they share a lot similar features (ie. node selector, summary). The ticket is UIE-8082 and that work is set for the 10/28 release and will involve breaking down these similar components into smaller shared components.

This should change how `summaryText`, and `nodePricing` are handled since those components share states and logic. I can include a note in the ticket to look into changing how the disabling behavior for the submit button is disabled in Resize, rather than using `shouldSubmitBeDisabled` in state.

2024-10-09 15:29 UTC, cpathipa commented
@smans-akamai Looks like there is E2E test failing in resize-database.spec.ts relevant to this PR. Could you look into this ?

2024-10-09 18:04 UTC, cpathipa approved these changes
Confirming on the failed e2e test `resize-database.spec`

2024-10-09 18:05 UTC, cpathipa commented
Looks like failed test clone-linode.spec is flaky cc: @jdamore-linode

2024-10-10 13:39 UTC, bnussman-akamai approved these changes

2024-10-10 15:11 UTC, merged