Upcoming: [DI-20844] - Tooltip for widget level filters and icons, beta feedbacks and CSS changes for CloudPulse
linode/manager pull request #11062
Opened 2024-10-08 10:04 UTC by venkymano-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-10-08 13:52 UTC, nikhagra-akamai requested changes

2024-10-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
> +  const scaledWidgetUnit = React.useRef(unit === 'Bytes' ? 'B' : unit);
```suggestion
  const scaledWidgetUnit = React.useRef(generateCurrentUnit(unit));
```

https://github.com/nikhagra-akamai/manager/blob/0bc9d73c4f351b6718061891cc6a9036ca4dff89/packages/manager/src/features/CloudPulse/Utils/unitConversion.ts#L222

2024-10-09 06:38 UTC, nikhagra-akamai approved these changes

2024-10-10 15:32 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +    }, [defaultValue]); // need to execute only once, during mounting of this component
The comment here is no longer true. In addition, I believe I was able to get this to work without useEffect, storing state, and without some of the other things in here:

```
export const CloudPulseTimeRangeSelect = React.memo(
  (props: CloudPulseTimeRangeSelectProps) => {
    const { defaultValue, handleStatsChange, savePreferences } = props;

    const defaultOption = React.useMemo(
      () => OPTIONS.find((o) => o.label === defaultValue) || OPTIONS[0],
      [defaultValue]
    );

    return (
      <Autocomplete
        onChange={(_, value: Item<Labels, Labels>) => {
          const timeDuration = TIME_RANGES[value.value];
          handleStatsChange?.(timeDuration, value.value, savePreferences);
        }}
        autoHighlight
        data-testid="cloudpulse-time-duration"
        value={defaultOption}
        disableClearable
        fullWidth
        isOptionEqualToValue={(option, value) => option.value === value.value}
        label="Select a Time Duration"
        options={OPTIONS}
        textFieldProps={{ hideLabel: true }}
      />
    );
  }
);
```

I also moved `getTimeDurationFromTimeRange` to a map lookup:

```
const TIME_RANGES: Record<Labels, TimeDuration> = {
  'Last 7 Days': { unit: 'days', value: 7 },
  'Last 12 Hours': { unit: 'hr', value: 12 },
  'Last 24 Hours': { unit: 'hr', value: 24 },
  'Last 30 Days': { unit: 'days', value: 30 },
  'Last 30 Minutes': { unit: 'min', value: 30 },
};

const OPTIONS: Item<Labels, Labels>[] = Object.keys(TIME_RANGES).map(
  (label) => ({
    label: label as Labels,
    value: label as Labels,
  })
);
```

2024-10-10 15:32 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
> +}));
I recommend we refrain from implementing this change at present. In fact, I strongly suggest removing it entirely. We have a larger initiative planned to align our tooltips with CDS 2.0 across the entire platform. Implementing this now would create additional cleanup work for us later. Moreover, if we were to keep this functionality, it would likely be more appropriate to place it in a different file.

2024-10-10 15:32 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
> +              height: `calc(${theme.spacing(4)} + 2px)`,
Nit: Do we need a height here? The flexbox already aligns it in the center. It just makes the outline look weird when tab focused: 
<img width="117" alt="Screenshot 2024-10-10 at 11 27 06 AM" src="https://github.com/user-attachments/assets/d2a8411d-5c09-4764-bc96-bd6102abae66">

2024-10-10 15:40 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          onChange={(_: any, selectedAggregateFunc: any) => {
Can we fix both of these `any` types?

2024-10-10 15:40 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          getOptionLabel={(option: { label: string }) => {
```suggestion
          getOptionLabel={(option) => {
```

We shouldn't need to put a type here. The typescript should be able to infer the type based on the Autocomplete's `options`/`value`

2024-10-10 15:40 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +        <StyledWidgetAutocomplete
There are some serious type-safety issues with this component that need to be fixed. 

If I switch `StyledWidgetAutocomplete` to just a plain `Autocomplete`, it seems to improve things

2024-10-10 15:40 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +          resourceSelections: CloudPulseResources[]
It's okay to just let typescript infer the types here

```suggestion
        onChange={(e, resourceSelections) => {
```

2024-10-10 15:43 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const isAutocompleteOpen = React.useRef(false); // Ref to track the open state of Autocomplete
We do something similar in `packages/manager/src/components/VLANSelect.tsx`, but we use state instead of a ref. 
I think the pattern is okay if it makes a significant optimization 

If we decide to keep this, maybe we can add a comment explaining the optimization

2024-10-11 13:02 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          getOptionLabel={(option: { label: string }) => {
@bnussman-akamai , here the type can be either string or label:string, i removed this and added a check at function level

2024-10-11 13:02 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +        <StyledWidgetAutocomplete
Here we need the styled component, as the widget filters are subject to some styles as per UX design

2024-10-11 13:02 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          onChange={(_: any, selectedAggregateFunc: any) => {
done

2024-10-11 13:05 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const isAutocompleteOpen = React.useRef(false); // Ref to track the open state of Autocomplete
Yes, the useRef here reduces the number of re-renders the component goes through, so we will keep this approach. I have added a comment as well.

2024-10-14 05:41 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +    }, [defaultValue]); // need to execute only once, during mounting of this component
@jaalah-akamai , here I have removed the comments and added appropriate. Implementing this works in product page, whereas in the contextual view it is not working, since we are caching the defaultOption based on defaultValue in useMemo, in the contextual view there is no preferences at all so the default value will always be same and it will always not get recomputed if we change the value in the dropdown

I think we need to spend more time on refactoring this approach. This improves the code whereas it doesn't optimize the user experience, also we can create a ticket to track these refactoring works.

2024-10-14 05:54 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
> +}));
@jaalah-akamai , As we don't know the alignment dates for CDS 2.0 and this is an important feature and a UX requirement,  we can keep this for now, it is already kept in a separate file, on CDS 2.0 alignment, only changes in this file should be enough.

2024-10-14 05:57 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
> +              height: `calc(${theme.spacing(4)} + 2px)`,
removed!!

2024-10-14 13:18 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
> +}));
How is a design change that departs from what Cloud Manager is doing today across all other features a requirement? This is a CDS 2.0 design element that has not been rolled out into Cloud Manager yet. This needs to be put on hold until this is tackled as part of the CDS 2.0 rollout effort which is currently underway in this quarter.

2024-10-14 14:22 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +        <StyledWidgetAutocomplete
Upon discussion with @jaalah-akamai  /. @bnussman-akamai , we have agreed to remove styled and use sx prop instead

2024-10-14 14:47 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +        <StyledWidgetAutocomplete
@jaalah-akamai / @bnussman-akamai  This is done.

2024-10-14 18:33 UTC, jaalah-akamai commented
This is looking better - just waiting on the tooltip update before approval

2024-10-15 05:04 UTC, venkymano-akamai commented
> This is looking better - just waiting on the tooltip update before approval

@jaalah-akamai , we have moved to the common tooltip

2024-10-15 10:30 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
> +}));
@kmuddapo , Thanks, I have already updated to use existing tooltip

2024-10-15 11:04 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
> +    const isAutocompleteOpen = React.useRef(false); // Ref to track the open state of Autocomplete
As per discussion, the useRef approach solves our use case better and we will use it.

2024-10-15 11:05 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
> +    }, [defaultValue]); // need to execute only once, during mounting of this component
As per the discussion, it is agreed we will not go ahead with this approach as it needs more code refactoring, we can take these later and for now will go with defaultValue based useEffect approach.

2024-10-15 14:16 UTC, jaalah-akamai approved these changes

2024-10-15 15:23 UTC, bnussman-akamai reviewed
Just a few small things then I will ✅

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
> +          sx={getAutocompleteWidgetStyles(theme)}
You can actually pass a  function to `sx`.  The theme will be passed automatically, so you can even remove the `useTheme` hook above

```suggestion
          sx={getAutocompleteWidgetStyles}
```

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +          fullWidth={false}
Same feedback here. Is this nessesaery?

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +            selectedInterval: IntervalOptions
Now that the type-safety issue is fixed, please remove these explicit types. Allowing typescript to infer the types will be more type-safe

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +            value: IntervalOptions
Same thing here. No need to explicitly put the types now that the type-safety is fixed

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Widget/components/CloudPulseIntervalSelect.tsx
> +          sx={getAutocompleteWidgetStyles(theme)}
Same thing here. `sx` can take a function. This will allow us to remove the `useTheme` call above 
```suggestion
          sx={getAutocompleteWidgetStyles}
```

2024-10-15 15:23 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
Should we keep this abstraction or just use `Tooltip` directly? cc @jaalah-akamai  This seems fine, but I feel like one could argue is it an extra abstraction that would be nice to not need if possible

2024-10-15 15:59 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/shared/CloudPulseTooltip.tsx
@bnussman-akamai , thanks for the suggestion, I suggest we can keep this abstraction, so in future any CloudPulse specific changes can go in one tooltip component rather than doing it in all filters.

2024-10-15 16:00 UTC, venkymano-akamai commented
@bnussman-akamai , I have addressed the comments you have left. Please check once

2024-10-15 17:49 UTC, bnussman-akamai approved these changes

2024-10-16 00:41 UTC, jaalah-akamai commented
I had to re-run the CI E2E... when it passes, we'll merge

2024-10-16 13:19 UTC, venkymano-akamai commented
@jaalah-akamai , for this PR, in the same branch, in local if run yarn coverage:summary, yarn test, our ACLP cy, everything is passing. I don't know whats with the CI

2024-10-16 13:59 UTC, merged