feat: [M3-8703] - Disable Create VPC button with tooltip text on Landing Page for restricted users
linode/manager pull request #11063
Opened 2024-10-08 11:21 UTC by hasyed-akamai

## Description 📝
To prevent unauthorized access to specific flows and provide clearer guidance, we aim to restrict entry to users without the required permissions.

Here, we are restricting users from creating new VPC from the Landing Page when they do not have access or have read only access.

## Changes  🔄
List any change relevant to the reviewer.

- For restricted users:
  - Disabled Create VPC Button on the Landing Page

## Target release date 🗓️

## Preview 📷

| Before | After |
| ------ | ----- |
| ![Before](https://github.com/user-attachments/assets/40ed17a1-0c8a-48c9-bc76-01c46e8fb4e4) | ![After](https://github.com/user-attachments/assets/5e61d605-a8bc-47b3-825e-f9b9ad8f8340) |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
- Log into two accounts side by side:
  - An unrestricted admin user account: full access
  - A restricted user account (use Incognito for this)
    - Start with Read Only for everything

### Reproduction steps
- Landing:
  - Observe as restricted user, notice shows and you cannot create VPC

### Verification steps

- After changes, observe tooltips are tailored to the action.

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-10-08 13:28 UTC, bnussman-akamai approved these changes

2024-10-08 13:28 UTC, bnussman-akamai commented on packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
> +  const isVPCSReadOnly = useRestrictedGlobalGrantCheck({
Something like `isVPCCreationRestricted` might be a bit more descriptive.

```suggestion
  const isVPCCreationRestricted = useRestrictedGlobalGrantCheck({
```

2024-10-08 16:32 UTC, cpathipa approved these changes

2024-10-08 18:28 UTC, hana-linode approved these changes

2024-10-09 07:16 UTC, pmakode-akamai requested changes
Hi @hasyed-akamai, I noticed a couple of test failures in this code. It seems that some of the suggested changes may not have been applied consistently across all relevant areas. 

I do like the updated variable names, but they need to be updated wherever they’re used. Could you take a look and make those adjustments before we merge?

2024-10-09 08:39 UTC, pmakode-akamai approved these changes
Thanks for the changes! Code looks good 🎉 Checks pass ✅

2024-10-14 06:41 UTC, merged