upcoming: [DI-21270] - Added the Alerts tab
linode/manager pull request #11064
Opened 2024-10-08 13:01 UTC by santoshp210-akamai

## Description 📝
Added Alert tab under Monitor for the alerting services

## Changes  🔄
List any change relevant to the reviewer.
- Added Alerts tab under Monitor which is visible when at least one flag of the sub-tabs is accessible(via feature flag)
- Added Recent activity, Alert Definitions, Notification channels tabs under Alert and the tabs visible only when they're accessible through feature flags

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-09-04 at 14 47 05](https://github.com/user-attachments/assets/6fe23259-075c-4f91-b6fc-fb51c1f3338e) | ![Screenshot 2024-10-08 at 18 28 48](https://github.com/user-attachments/assets/43448115-6612-427a-90b0-782b2e54254b) |

## How to test 🧪
- Switch to mock user as APIs are not live and for the feature flags(Legacy MSW handlers)

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [x] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-10-08 13:11 UTC, jdamore-linode commented
@santoshp210-akamai it looks like this branch might be pretty out-of-date. Would you mind pulling in the latest changes from our `develop` branch so all our latest tests run, etc.?

Thank you!

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +    <Paper>
Let's add `sx={{padding: 2}}` to the `Paper` as per design

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
> +    <Paper>
Let's add `sx={(theme) => ({ background: theme.bg.offWhite })}` to the `Paper` as per design

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +        >
We can remove this `Box` entirely and the tabs will span the entire content as per design

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
>      </StyledTabs>
Let's remove the `StyledTabs` and use `Tabs` directly and just apply `marginTop={0}` as props. No need to turn this into a styled component.

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
>  export const CloudPulseTabs = React.memo((props: Props) => {
Let's remove the `React.memo`, I feel like this feature is relying on this too much. React's built-in optimizations should be sufficient and we'll optimize when we need to.

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
> +      routeName: `${props.match.url}/alerts`,
Let's switch `props.match.url` to use `url` from the routing hook: const { url } = useRouteMatch();

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
>    const tabs = [
Tabs is something you could probably memoize with `useMemo` and `[url, flags.aclpAlerting]` as deps.

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
> +      routeName: `${props.match.url}/alerts`,
Let's do the same for `pathname`: const { pathname } = useLocation();

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
>    };
Remove the `navToURL` function. The TabLinkList component should handle navigation internally.

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
> +        accessibleTabs.findIndex((tab) => matches(tab.routeName)),
This is good, but we could memoize this match function probably in a handler above:
```
const activeTabIndex = useMemo(() => 
    Math.max(accessibleTabs.findIndex(tab => pathname.startsWith(tab.routeName)), 0),
  [accessibleTabs, pathname]);
```

2024-10-10 16:26 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
>    };
Shouldn't need `matches` since we can directly compare the current pathname with the route names of our tabs in the `activeTabIndex` function I mentioned below.

2024-10-14 07:46 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
> +    <Paper>
@jaalah-akamai This particular component is used as a placeholder for the AlertDefinition page, The contents of the page will be part of a later feature which we are planning to do after the create alert definition flow.

2024-10-14 07:52 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +        >
There is a Create button that is supposed to come after the tabs, so we had initially wrapped everything in the `Box` , too keep PR minimal we just went ahead with this tabs component.

2024-10-15 22:40 UTC, hkhalil-akamai approved these changes
One small suggestions, otherwise looks good.

2024-10-15 22:40 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +  const tabs = React.useMemo(
Can we add a type parameter to this?
```suggestion
  const tabs = React.useMemo<Tab[]>(
```

Also add to the imports:

```
import type { Tab } from 'src/components/Tabs/TabLinkList';
```

2024-10-15 22:40 UTC, hkhalil-akamai commented on packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
> +  const tabs = React.useMemo(
Same comment here.

```suggestion
  const tabs = React.useMemo<Tab[]>(
```

2024-10-16 14:47 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +  const tabs = React.useMemo(
@hkhalil-akamai , The accessible property added to the tabs here for the visibility might not be the same as the Tab from the TabLinkList , should we create a custom type for this here or is there any other way to do this ?

2024-10-16 14:53 UTC, jaalah-akamai approved these changes

2024-10-16 15:20 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +  const tabs = React.useMemo(
Oh good callout Hussain. Yes we want to make changes here. Give me a few and I'll point them out

2024-10-16 15:23 UTC, jaalah-akamai requested changes

2024-10-16 15:23 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +  const tabs = React.useMemo(
We don't want to change the Tab interface, so I suggest you create a new interface that's something like:
```
interface AlertsTab {
  isEnabled: boolean;
  tab: Tab;
}
```

```
const tabs = React.useMemo<AlertsTab[]>(
    () => [
      {
        isEnabled: Boolean(flags.aclpAlerting?.alertDefinitions),
        tab: {
          routeName: `${url}/definitions`,
          title: 'Definitions',
        },
      },
      // Add more tabs here as needed
    ],
    [url]
  );
```

Then you can filter based on that
```
const accessibleTabs = React.useMemo(
    () =>
      tabFlags
        .filter((tabFlag) => tabFlag.isTabEnabled)
        .map((tabFlag) => tabFlag.tab),
    [tabFlags, flags]
  );
```

2024-10-16 15:56 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
> +  const tabs = React.useMemo(
Yea that makes sense. I updated my snippets

2024-10-17 12:23 UTC, jaalah-akamai approved these changes

2024-10-17 12:24 UTC, merged