feat: [UIE-8074] - DBaaS GA Summary tab
linode/manager pull request #11091
Opened 2024-10-11 17:36 UTC by corya-akamai

## Description 📝
DBaaS GA summary tab refactor. Data remains the same, although the layout is altered.

## Changes  🔄
- V1 Summary components moved to /legacy dir marked deprecated and will be removed post GA release.
- V2 Summary components with tests

## Target release date 🗓️
10/28/24

## Preview 📷

| V1 Legacy | V1 Default | V2 Legacy | V2 Default |
| --- | --- | --- | --- |
| 
![v1-legacy](https://github.com/user-attachments/assets/84c130ad-b187-47e5-88be-b1813b0bad3e)
| 
![v1-default](https://github.com/user-attachments/assets/03f8afa9-2e44-41be-a4ad-f59710d0c5cd)
| 
![v2-legacy](https://github.com/user-attachments/assets/a158f3b6-f9dc-4464-9abf-cffbe9baf9f2)
| 
![v2-default](https://github.com/user-attachments/assets/eeccc6a8-fd88-4119-ae54-80bd78a51020)
|

## How to test 🧪

### Prerequisites
- Managed Databases account capability
- LD flag: beta: false, enabled: true

### Verification steps
- Toggle LD flag will show GA screen vs. V1 screen

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-10-16 23:31 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.style.ts
> +}));
Could we do something like the following to improve alignment (vertically centered values), make use of flex, and avoid the need for another nested component within the Grid item by replacing the parent of `StyledValueBox` with:

```suggestion
export const StyledGridValue= styled(Grid2, {
  label: 'StyledGridValue',
})(({ theme }) => ({
  alignItems: 'center',
  color: theme.palette.mode === 'dark' ? theme.color.grey8 : theme.color.black,
  display: 'flex',
  padding: `0 ${theme.spacing()}`,
}));
```

I was seeing some weirdness with the icons existing outside the grid container at really small screen sizes (which is also currently happening), so might need to make some adjustments to this still.

![Screenshot 2024-10-16 at 4 07 16 PM](https://github.com/user-attachments/assets/e3e958f4-ee0e-4507-bf33-8aa29533461b)

2024-10-16 23:31 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> +        />
![Screenshot 2024-10-16 at 3 16 57 PM](https://github.com/user-attachments/assets/fd0700dd-8d24-4d32-bd22-336e400e4ed3)

I think we'll want the copy tooltip not to render if the `readOnlyHostValue` is an empty string.

2024-10-16 23:31 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
CI has a typecheck error that I'm not seeing locally. 🤔 
![Screenshot 2024-10-16 at 4 21 44 PM](https://github.com/user-attachments/assets/c7cf70bd-b492-4c59-af07-e066f8e0ddb3)

2024-10-16 23:31 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Unrelated to the above, I am also seeing eslint warnings in several files. Can we clean those up before merging this?

![image](https://github.com/user-attachments/assets/f996eb05-32eb-4968-9e31-c421353e63d3)

The VSCode [ESLint extension](https://linode.github.io/manager/development-guide/13-coding-standards.html#linting) (if you don't already have it installed) is very useful.

2024-10-21 14:25 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> +        />
Done

2024-10-21 14:29 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
I'm not seeing it locally either

2024-10-21 14:32 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Done

2024-10-21 14:54 UTC, cpathipa requested changes
@corya-akamai Please resolve the linting errors; it looks like there are quite a few.

2024-10-21 14:54 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
> +  StyledValueBox,
No matching export in "src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.style.ts" for import `StyledValueBox`

2024-10-21 15:57 UTC, corya-akamai commented
> @corya-akamai Please resolve the linting errors; it looks like there are quite a few.

Done

2024-10-21 21:03 UTC, cpathipa reviewed
Overall looks good to me, left few comments to lift repeated code and make JSX cleaner.

2024-10-21 22:14 UTC, mjac0bs reviewed
The (mis)alignment of text in the table cells is pretty noticeable to me, so I'd like to see that fixed before approving, but this looked close otherwise. 

Thank you for the unit test coverage - there are a lot of test cases to keep track of now.

2024-10-21 22:14 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
> +      </StyledGridContainer>
My suggestion here was to avoid nesting another Box within a Grid because it's not really necessary if we just apply flex styling to the Grid item itself and vertically align its children. For example: remove `StyledValueBox` each place it occurs and replace its immediate parent `Grid` with a `StyledValueGrid`. Did you see any issues with that suggested approach?

This is what I'm currently seeing in the UI - the value fields are touching the top of the cell and misaligned with their labels:
![Screenshot 2024-10-21 at 2 43 48 PM](https://github.com/user-attachments/assets/02f876cf-b419-45e9-9fa6-722023b7dd4c)

And this is what I'm seeing if I make the above suggestions here to this file only (DatabaseSummaryConnectionDetails would also need the same changes):
![Screenshot 2024-10-21 at 2 50 28 PM](https://github.com/user-attachments/assets/02b9633e-6049-459b-827c-130d78a9450d)

``` suggestion
      <StyledGridContainer container md={10} spacing={0}>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>Status</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={1.5} md={4} xs={8}>
          <DatabaseStatusDisplay database={database} events={events} />
        </StyledValueGrid>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>Plan</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={2.5} md={4} xs={8}>
          {formatStorageUnits(type.label)}
        </StyledValueGrid>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>Nodes</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={2} md={4} xs={8}>
          {configuration}
        </StyledValueGrid>
        <Grid lg={1.5} md={2} xs={4}>
          <StyledLabelTypography>CPUs</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={1.5} md={4} xs={8}>
          {type.vcpus}
        </StyledValueGrid>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>Engine</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={1.5} md={4} xs={8}>
          {databaseEngineMap[database.engine]} v{database.version}
        </StyledValueGrid>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>Region</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={2.5} md={4} xs={8}>
          {region?.label ?? database.region}
        </StyledValueGrid>
        <Grid lg={1} md={2} xs={4}>
          <StyledLabelTypography>RAM</StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={2} md={4} xs={8}>
          {type.memory / 1024} GB
        </StyledValueGrid>
        <Grid lg={1.5} md={2} xs={4}>
          <StyledLabelTypography>
            {database.total_disk_size_gb ? 'Total Disk Size' : 'Storage'}
          </StyledLabelTypography>
        </Grid>
        <StyledValueGrid lg={1.5} md={4} xs={8}>
          {database.total_disk_size_gb ? (
            <>
              {database.total_disk_size_gb} GB
              <TooltipIcon
                status="help"
                sxTooltipIcon={sxTooltipIcon}
                text={STORAGE_COPY}
              />
            </>
          ) : (
            convertMegabytesTo(type.disk, true)
          )}
        </StyledValueGrid>
      </StyledGridContainer>
```

2024-10-21 22:14 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
Can we add a JSDocs comment in this file to indicate it will be deprecated in the near future? 

Something as simple as 
```
/**
 * TODO: Delete this component after GA release.
 */
```
would be great. I know it's implied via naming "legacy", but that can be 1) easy to miss in a long file name and 2) not always indicative of the reality of how long things can stick around.

2024-10-21 22:14 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
Same comment here about leaving a TODO/deprecated file comment.

2024-10-21 22:42 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
> +            ))}
@corya-akamai Considering that this legacy code will be deleted soon, this can be ignored.

2024-10-21 22:43 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
> +          </Box>
@corya-akamai Considering that this legacy code will be deleted soon, this can be ignored.

2024-10-21 22:48 UTC, cpathipa approved these changes
@corya-akamai Thank you for addressing the feedback, Approving pending feedback from  @mjac0bs

2024-10-22 14:18 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> +    marginTop: '10px',
Added theme values

2024-10-22 14:18 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
> +      </StyledGridContainer>
Ah gotcha, good call done.

2024-10-22 14:19 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
There is a JSDocs on the component and inline comments and a Jira tickets to track cleanup.
![deprecated](https://github.com/user-attachments/assets/2f4f4361-6ff2-4287-bff7-d5b9f5d8728b)

2024-10-22 14:20 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
There is a JSDocs on the component and inline comments and a Jira tickets to track cleanup.
![deprecated](https://github.com/user-attachments/assets/2f4f4361-6ff2-4287-bff7-d5b9f5d8728b)

2024-10-22 14:20 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.style.ts
> +}));
Fixed

2024-10-22 14:25 UTC, mjac0bs approved these changes
Thanks @corya-akamai. I'll let @cpathipa merge once CI finishes assuming tests pass, and I'd expect them to because they were passing before the last commit.

2024-10-22 14:26 UTC, corya-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
> +const useStyles = makeStyles()((theme: Theme) => ({
I pulled the styles out of the new DatabaseSummaryConnectionDetails into DatabaseSummaryConnectionDetails.styles.ts

2024-10-22 15:34 UTC, merged