feat: [UIE-8090] - DBaaS Settings and Landing Page
linode/manager pull request #11152
Opened 2024-10-23 19:52 UTC by smans-akamai

## Description 📝
Adding Suspend and Resume functionality to  Landing Page and database details Settings Views for GA

## Changes  🔄
- Suspend Cluster button can now appear in the DatabaseSettings that displays  and Suspend Cluster dialog
- Suspend and Resume actions added to Database Landing table
- Suspend notifications can now appear above the Database Landing table

## Target release date 🗓️
10/28/2024

## Preview 📷

| Before  | After  | After 2 
| ------- | ------- | ------- |
| ![Before-Db-Settings](https://github.com/user-attachments/assets/4233a5cf-45bf-4979-9cc9-0112b7884763) | ![After-Db-Settings-no-dialog](https://github.com/user-attachments/assets/ea84acb0-f02c-4eb8-8e3d-59e4856406e0)| ![After-Db-Settings-Dialog](https://github.com/user-attachments/assets/fe82f278-893e-4240-be04-a07426d7d391) 
| ![database-landing-before](https://github.com/user-attachments/assets/523245b2-cb53-4395-b3ff-ab41ac3fd570) | ![Db-Landing-after](https://github.com/user-attachments/assets/146f36ff-53d2-483b-9717-3ffb03f27103)

## How to test 🧪

### Prerequisites
- Managed Databases account capability
- LD flag: beta: false, enabled: true

### Verification steps
- Toggle LD will show Suspend and resume functionality
- Check DatabaseSettings to see new Suspend Button and Dialog behavior
- Check DatabaseLanding to see new actions
- Check DatabaseLanding to see banners if databases are suspended for specified duration
- Confirm that Suspend can only be used on active databases
- Confirm that the resume action can only be used on Suspending and Suspended database clusters

## As an Author I have considered 🤔

*Check all that apply*

- [ x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [x] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
I'd recommend breaking up this PR up so that this banner into its own PR. The banner logic seems somewhat complex and the implementation may be flawed (see comment below)

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +export default DatabaseSettingsSuspendClusterDialog;
Please avoid using default exports. You can just use the `export const DatabaseSettingsSuspendClusterDialog` and remove this export

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +    <Dialog
You may want to consider using the **[Confirmation Dialog](https://design.linode.com/?path=/docs/components-dialog-confirmationdialog--documentation)** component rather than a pure Dialog. It may help you to fix the style/spacing issues

![Screenshot 2024-10-23 at 6 24 42 PM](https://github.com/user-attachments/assets/a4c62642-a542-4071-bf60-63e3b566bca1)

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const [isLoading, setIsLoading] = React.useState(false);
No need to define your own error and loading state. The `useSuspendDatabaseMutation` hook returns a `isPending` and `error` state you can use

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +) => {
We prefer to not use `React.FC` in our repo. You can type your props this way:

```suggestion
export const DatabaseSettingsSuspendClusterDialog = (
  props: SuspendDialogProps
) => {
```

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  databaseID: number;
We prefer `databaseId` over `databaseID`
```suggestion
  databaseId: number;
```

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
>        <Paper>
While we're here, we may be able to refactor this layout a bit. 

We can use a `Stack` with the `divider` prop to make a consistent layout without needing to repeat the <Divider /> component a ton of times

```typescript
<Paper>
  <Stack divider={<Divider spacingBottom={0} spacingTop={0} />} spacing={3}>
    ...
  </Stack>
</Paper>
```

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +  const suspendClusterCopy = `Suspend the cluster if it's temporarily not used to prevent being billed for it.`;
This copy doesn't read super well to me.  

Here's what I came up with but we may want to check with UX or a copy/technical writer

```suggestion
  const suspendClusterCopy = `You can suspend a cluster temporarily if it is not being used. You will not be billed for it.`;
```

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +        ) : null}
This is fine, but don't hesitate to use the `&&` notation. It should be fine in situations like this. I find that it makes the JSX a bit cleaner 🧼 

```suggestion
        {isDatabasesV2GA && isDefault && (
          <>
            <DatabaseSettingsMenuItem
              buttonText={'Suspend Cluster'}
              descriptiveText={suspendClusterCopy}
              disabled={disabled || database.status !== 'active'}
              onClick={onSuspendCluster}
              sectionTitle={'Suspend Cluster'}
            />
            <Divider spacingBottom={22} spacingTop={28} />
          </>
        )}
```

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +    newDatabases.data.forEach((database) => {
We may need to reconsider/rearchitect this banner feature. Our tables are API-paginated, meaning that `newDatabases` only contains the **first page** of databases. This logic may not produce the desired result a suspended database is not on the current API paginated page.

I do not reccomend fetching all databases to solve this because it kind of defeats the purpose of API based pagunation. 


There may be a clever way we can use api-v4 x-filtering to query for only suspended databases, which might be a more scaleable solution. 

I'm happy to do a proof of concept or talk through alternatives to this, just let me know!

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +  const getSuspendNotification = (
In general, I recommend extracting stuff like this into utility functions outside of this component. It makes it easier to unit test and makes the code more readable.

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +        : null}
This is going to look very bad if a user has lots of suspended databases (especially on mobile).  I think we should consider a more scaleable UI. Cloud Manager already has enough banners.

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +  const handleResume = (database: DatabaseInstance) => {
Because this resume logic isn't really used in this component we might be able to move it down into the `DatabaseActionMenu` component

2024-10-23 22:51 UTC, bnussman-akamai commented on packages/manager/src/queries/databases/databases.ts
> +      queryClient.removeQueries({
Is the `removeQueries` call here and in `useResumeDatabaseMutation` intentional? I believe that will evict that database from the cache. 

`invalidateQueries` might be the desired function here. `invalidateQueries` will make Cloud Manager refetch the database as needed

2024-10-24 15:15 UTC, m-sulik commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +  const suspendClusterCopy = `Suspend the cluster if it's temporarily not used to prevent being billed for it.`;
Hi @bnussman-akamai , we're not using "You can" as users know that if the option is available that "they can", and I'm not sure "You will not be billed for it" would be clear that by "it" we mean "the suspended cluster". How about:

Suspend the cluster if you don't use it temporarily to prevent being billed for it. ?

2024-10-24 17:46 UTC, smans-akamai commented on packages/manager/src/queries/databases/databases.ts
> +      queryClient.removeQueries({
After reviewing your comment, I believe that [invalidateQueries](https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation) makes more sense for this use case as the database hasn't been removed, only updated. So we'll want to trigger a refetch on stale data rather than removing the cache entirely.

I'll update this for both `useResumeDatabaseMutation` and `useSuspendDatabaseMutation`.

2024-10-24 19:17 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +    <Dialog
@bnussman-akamai Can the confirmation dialog support a checkbox that enables/disables the Suspend Cluster button?

2024-10-24 19:29 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
>        <Paper>
@bnussman-akamai Thanks for suggesting to refactor. I'll plan to refactor this as part of a separate ticket.
https://track.akamai.com/jira/browse/UIE-8220

2024-10-24 19:51 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +  const getSuspendNotification = (
@bnussman-akamai Thanks for the recommendation. We'll follow moving this into utilities once/if it's used in a second place.

2024-10-24 19:52 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +        : null}
@bnussman-akamai Thanks, we'll note this concern.

2024-10-24 22:13 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +  const suspendClusterCopy = `Suspend the cluster if it's temporarily not used to prevent being billed for it.`;
@bnussman-akamai Text for the view above was provided by @m-sulik . Updating to the latest provided above:
`Suspend the cluster if you don't use it temporarily to prevent being billed for it.`

Please confirm if this text works.

2024-10-24 22:42 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +    <Dialog
@bnussman-akamai I've updated the suspend dialog to use the confirmation dialog.

![suspend-updated-to-confirmation](https://github.com/user-attachments/assets/8b54328d-c5f0-4ac0-b13f-3aa2016b6c64)

2024-10-24 22:43 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +) => {
Thanks! I've made this update.

2024-10-24 22:43 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const [isLoading, setIsLoading] = React.useState(false);
I've updated this to leverage `isPending` and `error` from `useSuspendDatabaseMutation`

2024-10-25 16:42 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
@bnussman-akamai After discussion, we've removed the banner and associated logic from this pull request and will separate that into it's own ticket. The design and logic will be reworked as part of that new ticket.

2024-10-25 16:43 UTC, smans-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
> +        : null}
@bnussman-akamai After discussion, we've removed the banner and associated logic from this pull request and will separate that into it's own ticket. The design and logic will be reworked as part of that new ticket.

2024-10-28 14:59 UTC, cpathipa requested changes
Functionality LGTM! left few comments to lift conditional rendering for modals and nit-picky things to improve readability.

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +      ) : null}
I think with conditional rendering, we may lose the Dialog's animation. We could render the Dialogs unconditionally, similar to how `DatabaseSettingsResetPasswordDialog` is rendered in this file, etc.

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  };
nitpicky:  Can we use async/await to improve readability. try/catch handles success and error notifications, while finally ensures cleanup ?
```suggestion
const onSuspendCluster = async () => {
  try {
    await suspendDatabase();
    enqueueSnackbar('Database Cluster suspended successfully.', { variant: 'success' });
    onClose();
    push('/databases');
  } catch (error) {
    enqueueSnackbar('Failed to suspend Database Cluster. Please try again.', { variant: 'error' });
  } finally {
    setHasConfirmed(false);
  }
};
```

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const actions = (
Use capital naming conventions for JSX elements used within a component ([Contributing Guidelines](https://linode.github.io/manager/development-guide/02-component-structure.html))

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const suspendClusterCopy = `A suspended cluster stops working immediately and you won't be billed for it.
This can be moved to constants file or out side of the component.

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const defaultError = 'There was an error suspending this Database Cluster.';
This can be moved to constants file or out side of the component.

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +      )}
Conditional rendering may lose animation effect for dialogs.

2024-10-28 14:59 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +
nitpicky: Can we use async/await to improve readability ?

```suggestion
const DEFAULT_RESUME_ERROR = 'There was an error resuming this Database Cluster.';

const handleResume = async () => {
  try {
    await resumeDatabase();
    return enqueueSnackbar('Database Cluster resumed successfully.', { variant: 'success' });
  } catch (e: APIError[]) {
    const error = getAPIErrorOrDefault(e, DEFAULT_RESUME_ERROR)[0].reason;
    return enqueueSnackbar(error, { variant: 'error' });
  }
};
```

2024-11-01 15:45 UTC, bnussman-akamai approved these changes
Looks good to me! 

There is a conflict that needs to be addressed

2024-11-01 15:45 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +        </Typography>
We might just want to pass 

```suggestion
        {suspendClusterCopy}
```

and let the Notice handle the text size and bolding

2024-11-01 15:45 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +import { APIError } from '@linode/api-v4/src/types';
Our import should not contain `src`. Might cause problems in the future

```suggestion
import { APIError } from '@linode/api-v4';
```

2024-11-01 20:49 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +      ) : null}
I made this change in branch that we merged in.  (Sam is on vacation.)

2024-11-01 20:49 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  };
I made this change in branch that we merged in.  (Sam is on vacation.)

2024-11-01 20:50 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const actions = (
I get the point of this comment, but if you search the code for `const actions =` you'll see there are a dozen like this and none with capitalization.  For now, it seems like consistency would be preferred, but I am new to this whole thing, so please correct me if I am wrong.

2024-11-01 20:52 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const suspendClusterCopy = `A suspended cluster stops working immediately and you won't be billed for it.
It could be but there are two different "suspendClusterCopy" constants in the code and they are different.  I'm just a visitor here while Sam is on vacation :) but I prefer the way Sam has done it, being close to the one place it's used.

2024-11-01 20:53 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const defaultError = 'There was an error suspending this Database Cluster.';
See comment above but in this case it's an even more generic name and is being used once in this area.  I toyed with the idea of removing it altogether and just inlining the text as is done throughout this codebase, it seems, but in the end decided to leave it alone.

2024-11-01 20:53 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
> +      )}
I made this change in branch that we merged in. (Sam is on vacation.)

2024-11-01 20:54 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +
I made this change in branch that we merged in. (Sam is on vacation.)

2024-11-01 20:56 UTC, rodonnel-akamai commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
> +import { APIError } from '@linode/api-v4/src/types';
This was removed because the import was removed.  (It was being used to because someone had added a type defn to the catch's error, but doing so was causing "TS1196: Catch clause variable type annotation must be 'any' or 'unknown' if specified." so I changed `APIError` to `any` and this import was no longer needed.) Good to know going forward though to look for this problem.

2024-11-04 15:05 UTC, cpathipa commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx
> +  const actions = (
We are indeed transitioning to this new approach to maintain a cleaner and consistent codebase.

2024-11-04 15:08 UTC, cpathipa approved these changes
Thank you for addressing the feedback, LGTM! Please update this branch with the latest from develop.

2024-11-05 16:26 UTC, cpathipa commented
Also, there is a failed unit test in DatabaseSetting 
![image](https://github.com/user-attachments/assets/8712be61-69a5-47c2-81ff-39712964ab4f)

2024-11-05 20:08 UTC, cpathipa commented
Confirming failed tests passed and type errors are fixed.

2024-11-05 20:08 UTC, merged