fix: [APL-354] - disable shared CPU whenever APL is enabled
linode/manager pull request #11216
Opened 2024-11-06 15:27 UTC by dennisvankekem

## Description 📝
Shared CPU's are currently unstable with APL, therefore we want to disable the entire table whenever APL is enabled.  

## Changes  🔄
List any change relevant to the reviewer.
- added 'shared' to LinodeTypeClass
- added isAPLEnabled to isPlanPanelDisabled
- created new notice for APL 

## Target release date 🗓️
November the 11th

## Preview 📷
![image](https://github.com/user-attachments/assets/13a1cb81-dc3d-4a91-a61b-4d4f8a2ab606)

## How to test 🧪
- Make sure APL feature flag is enabled and you are enrolled into the beta 
- go to create Kubernetes cluster page
- Enable APL
- Observe that the entire shared CPU table is disabled

2024-11-06 17:17 UTC, dennisvankekem commented
Will fix test tomorrow

2024-11-07 14:45 UTC, abailly-akamai commented on packages/manager/src/features/components/PlansPanel/APLNotice.tsx
> +  const programInfo = `Shared CPU instances are currently not available for Application Platform for LKE`;
Let's lift this out of functional component and cache it

2024-11-07 14:45 UTC, abailly-akamai commented on packages/api-v4/src/linodes/types.ts
> +  | 'shared'
I am confused by this. This isn't a proper value returned by the API
https://techdocs.akamai.com/linode-api/reference/get-linode-types

Orr API types are packaged separately and needs to strictly adhere to API types.

2024-11-07 14:45 UTC, abailly-akamai commented on packages/manager/src/utilities/planNotices.ts
> +    (planType === 'shared' && Boolean(isAPLEnabled));
I don't like adding a feature specific check in a generic component. 

can we modified 

```TS
 isPlanPanelDisabled: (
    planType?: LinodeTypeClass,
    isAPLEnabled?: boolean
  ) => boolean;
```

to being able to pass a custom function returning a boolean?


```TS
 isPlanPanelDisabled: (
    planType?: LinodeTypeClass,
    disableFn?: (arg) => boolean
  ) => boolean;
```

something like that

also, see my initial comment about types, based on that I would not expect this to work?

2024-11-08 08:31 UTC, dennisvankekem commented on packages/api-v4/src/linodes/types.ts
> +  | 'shared'
Is it not a proper value, or has the documentation never been updated for a new value? Because it does as a matter of fact seem to work.

2024-11-08 08:31 UTC, dennisvankekem commented on packages/api-v4/src/linodes/types.ts
> +  | 'shared'
Otherwise I'm curious how we can call for the shared type class

2024-11-11 09:42 UTC, dennisvankekem commented on packages/manager/src/utilities/planNotices.ts
> +    (planType === 'shared' && Boolean(isAPLEnabled));
Regarding this, looking deeper in the code. It might be redundant to do so actually. 

we call the function in `KubernetesPlansPanel`. If I were to lift the APL part out it would probably also live in `KubernetesPlansPanel` so we might as well change this line:

`wholePanelIsDisabled={isPlanPanelDisabled(plan, isAPLEnabled)}`

to something like this: 

`wholePanelIsDisabled={isPlanPanelDisabled(plan) || isDisabledByAPL()}`

where `isDisabledByAPL()`

would be something like this:

`const isDisabledByAPL = () => (planType === 'shared' && Boolean(isAPLEnabled));`

2024-11-11 09:52 UTC, dennisvankekem commented on packages/manager/src/utilities/planNotices.ts
> +    (planType === 'shared' && Boolean(isAPLEnabled));
![image](https://github.com/user-attachments/assets/71e6b47d-3856-45b2-9dba-edf0f8e95b2d)

Not really a big fan of the naming convention like so, open for suggestions

2024-11-11 09:52 UTC, j-zimnowoda commented on packages/api-v4/src/linodes/types.ts
> +  | 'shared'
standard = shared
I have just created a  cluster with shared node pool. Below the payload:
{"control_plane":{"acl":{"enabled":true,"revision-id":""},"high_availability":false},"k8s_version":"1.31","label":"jeho-sh","node_pools":[{"type":"g6-standard-1","count":3}],"region":"us-ord","apl_enabled":false}

2024-11-11 11:26 UTC, dennisvankekem commented
Regarding 'shared' type, it seems that it's indeed not an official type, however it is used as type in the plans panel, so I've tried my best to work around it

2024-11-11 12:12 UTC, dennisvankekem commented on packages/api-v4/src/linodes/types.ts
> +  | 'shared'
standard = shared, but this is not the case for checking whenever the the shared tab is active, because standard is not being used as an ID for that tab, but rather the type is being extended with 'shared' only in the plan segment

2024-11-11 12:22 UTC, dennisvankekem commented
adding @ElderMatt as internal reviewer

2024-11-11 12:31 UTC, dennisvankekem commented
error from storybook `Could not load .//src/components/Notice/Notice (imported by src/features/components/PlansPanel/APLNotice.tsx): ENOENT: no such file or directory, open './/src/components/Notice/Notice'` doesn't make sense to me, it loads `Notice` the exact same as the other notices like `MetalNotice`

2024-11-11 16:27 UTC, ElderMatt requested changes

2024-11-11 16:27 UTC, ElderMatt commented on packages/manager/src/utilities/planNotices.ts
> +   * @param {boolean} isAPLEnabled
Can you update the comment params? They are outdated.

2024-11-11 16:27 UTC, ElderMatt commented on packages/manager/src/utilities/planNotices.ts
> +    (planType === 'shared' && Boolean(isAPLEnabled));
I too would like to see a disableFn instead of having the logic in a generic component, this does not really look future proof.

2024-11-12 15:36 UTC, abailly-akamai commented on packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
> +      {planType === 'shared' ? <APLNotice dataTestId="apl-notice" /> : null}
this is problematic:
1. it shows in the Linode create flow (`/linodes/create`) which seems irrelevant to `APL`
2. it shows for ALL users (shouldn't it only show for users enrolled int he beta?)

This should only show in the LKE plan selection and the `isAPLEnabled?` logic should be contained there

2024-11-12 15:38 UTC, abailly-akamai commented on packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
> +      {planType === 'shared' ? <APLNotice dataTestId="apl-notice" /> : null}
We also have a lot of test failures on this PR. 

@dennisvankekem FYI a lot of components are being moved to a new `@linode/ui` package for modularization purposes. Besides the e2e failures, this is probably the issues you're seeing in the CI

2024-11-14 13:40 UTC, dennisvankekem commented on packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
> +      {planType === 'shared' ? <APLNotice dataTestId="apl-notice" /> : null}
this is indeed problematic. I was a little bit under the weather this week. I will work on it today

2024-11-14 14:47 UTC, dennisvankekem commented on packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
> +      {planType === 'shared' ? <APLNotice dataTestId="apl-notice" /> : null}
I've fixed it with the IsAPLEnabled check, that should be sufficient as it should only be true if it's set in createCluster which only can be set if the user is beta enrolled and APL feature flag is enabled

2024-11-14 14:52 UTC, dennisvankekem commented on packages/manager/src/features/components/PlansPanel/APLNotice.tsx
> +const programInfo = `Shared CPU instances are currently not available for Application Platform for LKE`;
agreed

2024-11-15 17:04 UTC, abailly-akamai commented
@dennisvankekem i think you need a proper rebase. Some of these issues stem from migrating some components to `@linode/ui` - please fix those failing checks and we should be ready to get this one moving. thx!

2024-11-18 16:38 UTC, abailly-akamai approved these changes
Approving, but PR will have to be opened against staging if needing a hotfix

2024-11-19 14:15 UTC, abailly-akamai commented
closing in favor of hotfix: https://github.com/linode/manager/pull/11284

2024-11-19 14:15 UTC, closed without merging