feat: [UIE-8193] - Tooltip for Create/Resize Database table
linode/manager pull request #11223
Opened 2024-11-07 11:48 UTC by mpolotsk-akamai

## Description 📝
Tooltip for Create/Resize Database table

## Changes  🔄
- Added 'Usable Storage' with tooltip to the Create/Resize Database Table.

## Target release date 🗓️
11/12/24

## Preview 📷
**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-11-07 at 12 44 11 PM](https://github.com/user-attachments/assets/86eabbb1-03f7-4d1b-be74-6cbf11dfd5a6) | ![Screenshot 2024-11-07 at 12 44 41 PM](https://github.com/user-attachments/assets/43dd99a9-b4be-44a5-b8eb-7e31cc1c4bb1) |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- Managed Databases account capability
- dbaasV2 feature flag set to GA

### Verification steps
(How to verify changes)
- Navigate to the Create Database Cluster page
- Navigate to the Resize Database Tab

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-11-07 15:52 UTC, mjac0bs commented
Same [question](https://github.com/linode/manager/pull/11227#issuecomment-2462549280) as Banks goes for here as well:

> Heads up the [release branch](https://github.com/linode/manager/tree/release-v1.132.0) for our 11/12 release has already been cut. How urgent is this?

2024-11-07 18:33 UTC, mjac0bs approved these changes
Approving this after confirming the tooltip appears where it should in the table and tests pass.

I don't think this is an urgent change to get into the already-cut release and so the target date should be updated to 12/10, but will let others including the FE fire chief determine that. 

I left some comments about accessibility and mobile view for consideration.

2024-11-07 18:33 UTC, mjac0bs commented on packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
> +                      </Link>
Mentioning an accessibility concern here: including links in a tooltip means that this link will [not be accessible via keyboard navigation](https://github.com/linode/manager/pull/9914#issuecomment-1830582774). Because of this issue, the front-end team has tried to move away from this practice and if the link is important for all users to be able to access, such as with warnings, to use another form of displaying the text (usually a notice). Here, I would consider just removing the Learn more link.

2024-11-07 18:33 UTC, mjac0bs commented on packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
>                <StyledTableCell
Any concerns about smaller screen sizes (tablet and mobile view)? We no longer have the 'Usable Storage' column, the selection cards just say "Storage", and there is no tooltip. Do we want to provide similar clarity there?

![Screenshot 2024-11-07 at 10 27 58 AM](https://github.com/user-attachments/assets/11c59b1e-1a31-4f45-a51c-90a87f59ca51)

2024-11-07 18:35 UTC, cpathipa approved these changes
Confirming on tooltip on resize tab.
![image](https://github.com/user-attachments/assets/6b8fded0-60b4-421d-a5af-2e4e80527b07)

2024-11-07 18:45 UTC, cpathipa commented
Agreed with @mjac0bs point, it would be nice to provide consistent context for small screens as well.

2024-11-07 19:24 UTC, mjac0bs requested changes
Small change requested given UX feedback.

2024-11-07 19:24 UTC, mjac0bs commented on packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
> +                    </Typography>,
After talking with UX about our latest patterns, Matthew has confirmed that no new tooltips should contain "Learn more" links, so I'm requesting that small change here. There may be some existing tooltips where the link exists, but let's not introduce it here.

```suggestion
                    'Usable storage is smaller than the actual plan storage due
                      to the overhead from the database platform.',
```

2024-11-08 15:47 UTC, mpolotsk-akamai commented on packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
>                <StyledTableCell
Thank you for the review, @mjac0bs !
After discussion with Kendall, I added note above the plans, for smaller screen sizes, and also changed "Storage" to "Usable Storage"

2024-11-08 15:48 UTC, mpolotsk-akamai commented on packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
> +                    </Typography>,
I've removed link, thanks!

2024-11-08 16:54 UTC, mjac0bs approved these changes
Thanks for checking in with Kendall and addressing feedback, @mpolotsk-akamai ! The change for smaller screen sizes looks good to me. 

![Screenshot 2024-11-08 at 8 51 28 AM](https://github.com/user-attachments/assets/54c48f91-dba6-4411-84a3-676205a93899)

2024-11-08 17:57 UTC, merged