refactor: [UIE-8245] - DBaaS: Replace Select component with Autocomplete
linode/manager pull request #11245
Opened 2024-11-12 15:25 UTC by mpolotsk-akamai

## Description 📝
DBaaS: Replace the deprecated Select component with Autocomplete.

## Changes  🔄
Replaced Select with Autocomplete
- Engine Select in Database Create
- Maintenance Window in Settings Tab

## Target release date 🗓️
12/10/2024

## As an Author I have considered 🤔

*Check all that apply*

- [x] 👀 Doing a self review
- [x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [x] ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2024-11-13 00:23 UTC, mjac0bs requested changes
Hey @mpolotsk-akamai - left you a few questions and notes in my review. Thank you for doing the swap from Select to Autocomplete, we appreciate it!

2024-11-13 00:23 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
> +  errors: FormikErrors<DatabaseCreateValues>;
Any reason we're passing the whole `errors` object in here as a prop instead of just the `errorText` for `errors.engine`? It doesn't look like we're doing anything to `errors` besides assigning `errors.engine` to the Autocomplete's `errorText` prop down below.

2024-11-13 00:23 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
A general note on error handling: surfacing the API error looks good. But I am wondering what happened to our schema validation on this field - it doesn't appear to be validating the Engine in prod, either, so this was an existing issue - optional but encouraged to address here. The engine field's behavior would ideally be consistent with that of other fields, validating before we get that API error. If not addressed in this PR, could you create a follow up to address?

![Screenshot 2024-11-12 at 3 59 10 PM](https://github.com/user-attachments/assets/9cb5d4c9-93b6-468b-b130-d70f959c759f)

![Screenshot 2024-11-12 at 3 59 52 PM](https://github.com/user-attachments/assets/105ef9b0-e152-4970-a952-86baf34e04a6)

2024-11-13 00:23 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
> +      clearOnBlur={true}
Do we need the `clearOnBlur` prop here and in the MaintenanceWindow autocomplete? None are freesolos, which means the default of `!prop.freesolo` will be `true`, so clear on blur will happen. (source: [MUI docs](https://mui.com/material-ui/api/autocomplete/))

```suggestion
```

2024-11-13 00:23 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
Existing code, but it looks like we have a typo in our `hourSelectionMap` in this component? We'll want to fix this, either here since we're already touching this file or in another 'bug' PR.

![image](https://github.com/user-attachments/assets/98972ed3-b334-4da4-bac4-36e349693f93)

2024-11-14 18:53 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
The schema validation didn't work because the field wasn’t empty; it had a default value intended to display prices in the Plan Table, which caused a minor bug. After discussing with Amit, I fixed it to properly display the default value in the 'Select a Database Engine' field.

2024-11-14 18:54 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
I've fixed this, thanks!

2024-11-14 21:06 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
Ah, I see. Thanks for looking into this. Things for further consideration by you, the rest of the DBaaS folks, and UX: Is showing the priced plans in the Plan Table prior to any Engine selection a requirement? And does surfacing a default Engine selection have any implications we want to avoid?

In other sections of the app, when we require a selection (in this case, region) to be made first, we display the following in the Plan Table.  I'm wondering if a 'Select an engine to view plans and prices' would be desirable for consistency here.

![Screenshot 2024-11-14 at 12 44 25 PM](https://github.com/user-attachments/assets/e7e741bc-ef75-4b2f-b954-ebdeec2c2ee3)
![Screenshot 2024-11-14 at 12 44 36 PM](https://github.com/user-attachments/assets/65159e42-3870-4376-8dc2-5213dd41d503)


I think that change would probably require more code changes even further outside the scope of the Autocomplete swap, so potentially a follow up.

2024-11-14 21:11 UTC, mjac0bs approved these changes
Thanks for the updates! A couple of suggestions related to the Database Engine field for consideration, but the Autocompletes looked good overall.

2024-11-14 21:11 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
> +      placeholder="Select a Database Engine"
Minor, but could we add some loading state to this field? I'm observing a flash of the placeholder text now before the value is assigned. It is not super noticeable, but would become so for slower connections.


https://github.com/user-attachments/assets/c4b238e0-ad41-4725-ad3f-a7c99c49e266

2024-11-14 21:30 UTC, mjac0bs commented on packages/manager/.changeset/pr-11245-changed-1731425235091.md
> +Replace Select component with Autocomplete ([#11245](https://github.com/linode/manager/pull/11245))
```suggestion
Replace Select component with Autocomplete in DBaaS([#11245](https://github.com/linode/manager/pull/11245))
```

Just noticed this. Can we please clarify where this change is being made? Once this changeset becomes part of a full list of changes in a changelog, it's not always clear at a glance what product was impacted.

2024-11-15 15:14 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
> +      placeholder="Select a Database Engine"
Thanks, @mjac0bs ! 
I've looked into it, and this is how the component works when we have default value. We see the same behavior in the "Create Linode" flow (specifically in the "Choose an OS" select). The flash happens because the component switches from the placeholder or loading text to the default value. However, for this Autocomplete, the flashing is minimal and not very noticeable, even on slower connections, because we check engines loading with other loading states when we show the CircleProgress.

2024-11-15 15:16 UTC, mpolotsk-akamai commented on packages/manager/.changeset/pr-11245-changed-1731425235091.md
> +Replace Select component with Autocomplete ([#11245](https://github.com/linode/manager/pull/11245))
Yes, sure, thanks for pointing that out. I will update it.

2024-11-15 15:19 UTC, cpathipa approved these changes
@mpolotsk-akamai Thank you for replacing select with Autocomplete component. Overall LGTM!

2024-11-15 15:38 UTC, mpolotsk-akamai commented
@cpathipa , @mjac0bs , thank you for the review!

2024-11-15 16:06 UTC, mjac0bs commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
> +      placeholder="Select a Database Engine"
Noted about Autocomplete behavior. I'll look into making a ticket on our end to see if that behavior can be improved at all.

2024-11-15 17:15 UTC, merged