feat: [M3-8676] - Provide Customer Notice for OS Distro Nearing EOL/EOS
linode/manager pull request #11253
Opened 2024-11-13 10:41 UTC by harsh-akamai

## Description 📝
Add Notice for OS Distro Nearing EOL/EOS

## Changes  🔄
- Added a notice for images that are nearing EOL/EOS

## Target release date 🗓️
10/12

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![image](https://github.com/user-attachments/assets/9a8c27c3-fb4f-43c2-a913-6bf217e916b6)| ![image](https://github.com/user-attachments/assets/31e95350-bf3b-476d-83fe-bd55ece67946) |

## How to test 🧪

### Verification steps

-  Navigate to the Create Linode page
- Choose an OS that is deprecated
- You should see a notice similar to the one in `Preview`

## As an Author, I have considered 🤔

- 👀 Doing a self review
- ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- 🤏 Splitting feature into small PRs
- ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- 🧪 Providing/improving test coverage
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 Providing mobile support
- ♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [ ] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

2024-11-13 14:57 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +  >(null);
We may want to consider deriving state from existing state rather than creating new state for this.

For example:

```typescript
  const { data: image } = useImageQuery(
    field.value ?? '',
    Boolean(field.value)
  );

  const showImageDeprecatedWarning =
    image !== undefined && isImageDeprecated(image);
```

Using extra state here might be fine, but deriving from the existing form state could be beneficial because it will gracefully handle things like the form being reset for example.

2024-11-13 14:57 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +        )}
Rather than having `imageDeprecatedText` be a string, what do you think about having a boolean control this, and putting the content directly in the JSX

```suggestion
        {image && showImageDeprecatedWarning && (
          <Notice
            dataTestId="os-distro-deprecated-image-notice"
            spacingBottom={0}
            spacingTop={16}
            variant="warning"
          >
            <Typography fontFamily={(theme) => theme.font.bold}>
              {image.label} will reach its end-of-life on{' '}
              {formatDate(image.eol ?? '', { format: 'MM/dd/yyyy' })}. After
              this date, this OS distribution will no longer receive security
              updates or technical support. We recommend selecting a newer
              supported version to ensure continued security and stability for
              your linodes.
            </Typography>
          </Notice>
        )}
```

I find that this is a bit cleaner and more readable.

2024-11-13 14:57 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +    if (image && isImageDeprecated(image)) {
Most of the images I select seem to have EOL dates in the past. Saying "Debian will reach its end of life on xx/xx/xx" may be a bit confusing if that date is in the past.

We may need different logic or a copy change here so that is makes more sense.

![Screenshot 2024-11-13 at 9 53 56 AM](https://github.com/user-attachments/assets/de8692e3-4844-4747-aa29-eb91e82de83f)

2024-11-13 15:33 UTC, hkhalil-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +    if (image && isImageDeprecated(image)) {
ahh beat me to it

2024-11-18 08:14 UTC, harsh-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +  >(null);
What you have recommended makes sense but when I implemented it there is a visible delay for the text displayed.

https://github.com/user-attachments/assets/eb62c9ee-4a50-4efb-89f5-26f426212aef

2024-11-18 14:26 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +  >(null);
That's a fair point. It is a tradeoff. You can make the final call here!

2024-11-19 17:21 UTC, harsh-akamai commented
> We should ask UX for a slight variation of the copy when the EOL date is in the past. As a suggestion we could say:
_The selected Ubuntu 23.10 reached its end-of-life on 07/12/2024. This OS distribution no longer receives security updates or technical support. We recommend selecting a newer supported version to ensure continued security and stability for your linodes._

I've pushed the changes to ensure the tense matches with the eol date.
@hkhalil-akamai @bnussman-akamai

2024-11-19 21:24 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +  >(null);
After thinking a little more, I think we should probably do it by deriving for now so that it is constant with with other parts of Linode Create like `packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx` for example. 

We can probably make some optimizations on the React Query level if we need to address the small delay

2024-11-20 11:53 UTC, harsh-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +  >(null);
Got it! Pushed the changes you've mentioned.

2024-11-20 20:54 UTC, hkhalil-akamai approved these changes
Thanks for responding to feedback!

2024-11-21 13:41 UTC, bnussman-akamai approved these changes

2024-11-21 13:41 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx
> +            dataTestId="os-distro-deprecated-image-notice"
Do we need this `dataTestId` if we don't have a unit test for this?

2024-11-21 15:22 UTC, abailly-akamai requested changes
@harsh-akamai & @bnussman-akamai 

I don't fully understand why we're doing an extra image query - why not displaying this within ImageSelect so:
- every consumer gets the warning
- we use the images query we already have running and use an effect in the component to conditionally display the warning

Please let me know if there is a good reason not to do this and I'll remove my request (wanted to prevent this to be merged if can be improved) 

it's worth noticing the lag with the notice display, especially on a slower connection

2024-11-21 15:42 UTC, bnussman-akamai commented
Doing this within `ImageSelect` would be nice because we wouldn't have to worry about the `useImageQuery` thing.

The only "downside" I can think of moving it in there would be `ImageSelect` would be less "pure", meaning it would return more than just a Select component, but that might be okay. 

If we want to keep this as-is, I could push a change on the React Query level to alleviate the extra fetch

2024-11-21 15:59 UTC, bnussman-akamai commented
@abailly-akamai Yeah, you make a good point. This would be really nice to have in other flows.

2024-11-22 08:09 UTC, harsh-akamai commented
>  I'd like to specify the ticket requirement, really - are we to add this notice on all flows? cause if so it's a no brainer

@abailly-akamai The ticket specifically mentions to add the notice in the Linodes/Create screen.

2024-12-09 07:18 UTC, harsh-akamai commented on packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
> +      />
Shifted `ImageSelect` out of the grid so that the banner could cover full width

2024-12-09 14:37 UTC, abailly-akamai approved these changes
Thanks for making this change! 

- Dynamic banner and logic looks great across `ImageSelect` instances ✅ 
- Handling of multiple deprecated images ✅ 

![Screenshot 2024-12-09 at 09 32 28](https://github.com/user-attachments/assets/34545e07-d7d7-41bb-b173-eff8749d1932)

2024-12-10 15:57 UTC, bnussman-akamai approved these changes

2024-12-11 14:44 UTC, merged