Upcoming: [DI-21694] - Added the Create Alert Button and few components for the Create Alert Definition Form.
linode/manager pull request #11255
Opened 2024-11-13 13:57 UTC by santoshp210-akamai

## Description 📝
 - Added Create Alert Button alongside the tabs under Alerts. 
 - Added few components for the Create Alert Definition form
 - Added types and interfaces relevant to the Create Alert Definition workflow

## Changes  🔄
- Added the Create Alert Button along the RecentActivity, Definitions, NotificationChannel tabs under Alerts in Monitor section
- Added a BreadCrumb component in the form 
- Added Name, Description, Severity components in the form
- Added the relevant types, hooks needed for the Create Alert form workflow
- Added a validation schema for the form

## Target release date 🗓️

Please specify a release date (and environment, if applicable) to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-10-08 at 18 28 48](https://github.com/user-attachments/assets/e2a2ffab-5de6-4210-bc48-ffec739e7236) | ![Screenshot 2024-11-13 at 19 17 49](https://github.com/user-attachments/assets/a1e64a6f-3c7b-4f3b-9809-12f000f2e7e3) ![Screenshot 2024-11-13 at 19 17 38](https://github.com/user-attachments/assets/b3a89732-53ab-4cb3-b9a1-e7a8edc46704) |

## How to test 🧪

### Prerequisites
- The tabs are controlled by a featureFlag called aclpAlerting, the flag has been currently disabled. For testing enable the definitions part of the aclpAlerting flag to be true.
- The API endpoints are not live yet, so use Legacy MSW Handlers for the mock responses.

### Verification steps
- In Monitor (once the prerequisites are followed) , Alerts tab should be visible next to Dashboards.
- Under that,  Definition tab and a Create button should be visible.
- On clicking Create, the Form Page should be visible.

## As an Author, I have considered 🤔

- 👀 Doing a self review
- ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- 🤏 Splitting feature into small PRs
- ➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- 🧪 Providing/improving test coverage
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 Providing mobile support
- ♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

2024-11-13 14:04 UTC, santoshp210-akamai commented
- The form is designed to have a lot of components, so the validation schema was written with keeping all of those components. Hence the submit button currently does not actually work as a lot of components are not yet part of the form. 
- The endpoint for the `POST` request for `createAlert` is not exactly as per specification as the API endpoint has URI encoded `service_type` variable which has to be user selected field and that component is not included in this PR. The endpoints will be changed in the coming PRs at the same time as when the `ServiceTypeSelect` component  is being added.
cc: @jaalah-akamai

2024-11-14 16:12 UTC, bnussman-akamai requested changes
Looks good, just have a few items of feedback!

2024-11-14 16:12 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/AlertSeveritySelect.tsx
I recommend Moving the `Controller` "one level up" so that it is outside of this component. It will benefit us in the long run to keep `AlertSeveritySelect` a pure select component so that it can easily be reused without depending on react-hook-form

2024-11-14 16:12 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/constants.ts
> +];
I'd prefer we don't use that generic `Item` type. It has that extra `data` property that is not typesafe and does not seem to be needed anyway.

I recommend we just use a simple one-off type like this:

```suggestion
interface AlertSeverityOption {
  label: string;
  value: AlertSeverityType;
}

export const alertSeverityOptions: AlertSeverityOption[] = [
  { label: 'Info', value: 3 },
  { label: 'Low', value: 2 },
  { label: 'Medium', value: 1 },
  { label: 'Severe', value: 0 },
];
```

2024-11-14 16:12 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/alerts.ts
> +export const aclpQueryKey = 'aclp-alerts';
We should use our [query key factory](https://github.com/lukemorales/query-key-factory) in `packages/manager/src/queries/cloudpulse/queries.ts` to manage our query keys rather than using a simple constant.

If there are no queries to invalidate yet, let's just delete this line and the `queryClient.invalidateQueries` call until that is added and leave a todo comment.

2024-11-15 15:48 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/constants.ts
> +];
After discussing, I think we should either go with 

```typescript
interface AlertSeverityOption {
  label: string;
  value: AlertSeverityType;
}
```

or something like

```typescript
export interface Item<L extends string, T> {
  label: L;
  value: T;
}

export const alertSeverityOptions: Item<string, AlertSeverityType>[] = [
  { label: 'Info', value: 3 },
  { label: 'Low', value: 2 },
  { label: 'Medium', value: 1 },
  { label: 'Severe', value: 0 },
];
```

2024-11-15 15:50 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/AlertSeveritySelect.tsx
After taking another look, I don't think we can proceed without making this change. 

This component is not typesafe at all and I'll leave some more comments explaining why. 

Doing what I suggested in my original comment will address the type-safety concerns

2024-11-15 15:55 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/AlertSeveritySelect.tsx
> +  const { control } = useFormContext();
```suggestion
  const { control } = useFormContext<CreateAlertDefinitionPayload>();
```

We must provide a generic type so that `react-hook-form` knows the types of the form state. Right now, if you look at `field.value` on line 44, it is type `any`. We need to improve that. 

Once this change is made, you'll realize that `name` isn't type-safe enough.

2024-11-18 15:53 UTC, bnussman-akamai approved these changes
Looks good! Thanks for addressing that feedback 🙏

2024-11-18 16:08 UTC, bnussman-akamai reviewed
The updated solution isn't completely typesafe like I was envisioning  🥲

|  Current |  Expected |
|---|---|
| ![Screenshot 2024-11-18 at 11 03 22 AM](https://github.com/user-attachments/assets/4ff6b55f-26ee-405c-bcce-5e4ac4a1e52f)  | ![Screenshot 2024-11-18 at 11 01 26 AM](https://github.com/user-attachments/assets/2b10a360-bf90-4118-8613-85a458317627)  |

Some possible fixes that come to mind are:
- Move the `Controller` one level up and make "SeveritySelect" pure
- Remove the `name` prop and just hardcode `name="severity"` on the controller

Sorry for continuing to bring this us. I just think proceeding with the best type safety possible will help all of us in the long run

2024-11-18 16:25 UTC, jdamore-linode commented
(FYI the test failure in `migrate-linode.spec.ts` can be disregarded. That's caused by an issue in the test: the assertion doesn't take our new region ID naming conventions into account. When the test uses the region select to search for Frankfurt , Frankfurt 2, which launched this morning, now appears in the list, but the test expects no results to appear. Will be fixed soon, but don't let it hold anything up in the meantime)

2024-11-18 19:48 UTC, santoshp210-akamai commented
@carrillo-erik , @santoshp210-akamai @pmakode-akamai . The changes requested by @bnussman-akamai have been fixed. So requesting for the review process to continue

2024-11-18 19:55 UTC, jaalah-akamai approved these changes

2024-11-18 19:56 UTC, merged

2024-11-25 06:59 UTC, santoshp210-akamai commented
@bnussman-akamai, In the use-cases where we cannot move the Controller component a level up or make the Select components pure. The learnings are that while passing the name to the controller we have to make sure the type of the name is very explicit by using `FieldPathByValue` by giving the relevant acceptable type for the value of the component under controller even after passing the relevant type of the form state. Ref: check FieldPathByValue in https://react-hook-form.com/ts#FieldPath.