upcoming: [DI-22217] - Added the Alert Listing page with Alerting Table and added relevant api endpoints
linode/manager pull request #11346
Opened 2024-12-02 13:10 UTC by santoshp210-akamai

## Description 📝

- Added the Alert Listing component
- Added the AlertTableRow component
## Changes  🔄

List any change(s) relevant to the reviewer.

- Added the AlertListing component with UT
- Added the AlertTableRow component with UT
- Added `GET` request to fetch the alert definitions
- Changed the `AlertDefinitionType` to `'system'|'user'`
- Added the AlertIcon svg for the Empty State for AlertListing component

## Target release date 🗓️

Please specify a release date (and environment, if applicable) to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![image](https://github.com/user-attachments/assets/d30bb4d0-b55d-494e-8dbf-ab2f6aac4175) | ![image](https://github.com/user-attachments/assets/f3237ea6-fce2-41cb-aedd-b23e99d3d3a3) |

## How to test 🧪

### Prerequisites
- The tabs are controlled by a featureFlag called `aclpAlerting`, the flag has been currently disabled. For testing enable the definitions part of the `aclpAlerting` flag to be true.
- The API endpoints are not live yet, so use Legacy MSW Handlers for the mock responses.
- This PR only contains the Table, the ordering, pagination will part of next PR.
- The Handlers for the rows in the Table are not yet part of this PR. It is dependent on another PR so it will part of that.

### Verification steps

(How to verify changes)

- [ ] The page to `/monitor/alerts/definitions` is the AlertListing component
- [ ] There is a TableRowError component if the API returns an error
- [ ] There is a TableRowLoading component if the API is still loading

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

</details>

2024-12-02 14:30 UTC, santoshp210-akamai commented
There are still on-going discussions with respect to the columns of the table in the Mockups with UX team, These are the currently agreed upon changes, there's a possibility of couple of columns re ordered or removed.
cc: @jaalah-akamai

2024-12-02 14:36 UTC, jdamore-linode commented on packages/manager/.changeset/pr-11346-added-1733145106911.md
> +AlertListing component and AlertTableRow component with UT ([#11346](https://github.com/linode/manager/pull/11346))
Can we avoid abbreviations like "UT" in the changelogs? Just so each entry is easier to skim if we're trying to find a particular change while troubleshooting a bug, test failure, etc.

2024-12-02 14:39 UTC, santoshp210-akamai commented on packages/manager/.changeset/pr-11346-added-1733145106911.md
> +AlertListing component and AlertTableRow component with UT ([#11346](https://github.com/linode/manager/pull/11346))
Sure, we will follow that from now. I will change this as well.

2024-12-02 14:40 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
> +  });
Can we improve this test so that it checks that the actual `mockResponse` data is displayed on the page? Confirming that the column titles are present doesn't get us very far.

2024-12-02 15:03 UTC, jdamore-linode commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
> +  });
I think we should at least check that each expected row is present (and that might just involve confirming that the label for each object in the `mockResponse` array is present, but you could approach it multiple ways e.g. using and checking a `data-test-id` attribute on each table row or something like that).

The table row tests (which are good!) confirm that an individual table row renders correctly with the right data given some individual `Alert` object, but for this test we want to know that `AlertListing` renders an `AlertTableRow` for each `Alert` object in the alerts array.

For example (albeit a bit contrived), if there were ever some logic bug where the `AlertTableRow`s weren't being rendered at all, this test wouldn't catch it. Feel free to reach out on Slack or continue the discussion here if I can answer any questions!

2024-12-02 15:21 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
> +  });
Yeah, I got it. I will add another test case to check for the label of each object.

2024-12-03 07:14 UTC, santoshp210-akamai commented on packages/manager/src/assets/icons/entityIcons/alert.svg
This file will be replaced before the PR is merged as the icon is not looking good on the UI. There are some confirmations from the UX side.

2024-12-03 19:00 UTC, bnussman-akamai requested changes

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/api-v4/src/cloudpulse/alerts.ts
> +import { Params, Filter, ResourcePage } from 'src/types';
Relative imports should be used in all packages (`ui`, `validation`, `api-v4`) except `manager`. This is because only the manager package has import aliases setup. 

```suggestion
import { BETA_API_ROOT as API_ROOT } from '../constants';
import { Params, Filter, ResourcePage } from '../types';
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
> +        component={() => <AlertListing />}
I think we can do this here:

```suggestion
        component={AlertListing}
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
> +*/
For future reference: Currently, this shows up like this:

![Screenshot 2024-12-03 at 1 46 34 PM](https://github.com/user-attachments/assets/c101c314-815f-4de6-9aa0-9532b75c7416)

If you format your comment like this:
```suggestion
/**
 * The handlers and alertType are made optional only temporarily, they will be enabled but they are dependent on another feature which will be part of next PR
 */
```

Code editors will be able to display the comment in a more readable way

![Screenshot 2024-12-03 at 1 46 05 PM](https://github.com/user-attachments/assets/a003fe09-9ccb-4599-994b-5e6348a955b3)

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
> +  /*
```suggestion
  /**
```

Refer to other comment about code comments

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
> +    await waitFor(() => expect(getByText('Created By')).toBeInTheDocument());
Because you are using static mocking to mock the return values of `useAllAlertDefinitionsQuery`, you don't need to await anything

```suggestion
    expect(getByText('Alert Name')).toBeInTheDocument();
    expect(getByText('Service Type')).toBeInTheDocument();
    expect(getByText('Status')).toBeInTheDocument();
    expect(getByText('Last Modified')).toBeInTheDocument();
    expect(getByText('Created By')).toBeInTheDocument();
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
> +    await waitFor(() =>
Refer to other comment about `await`ing

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +  const { data: alerts, isError, isLoading } = useAllAlertDefinitionsQuery();
Are we going to API paginate or client side paginate? We generally like to API paginate whenever possible.

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/queries.ts
> +  },
Optional, but we could organize this a bit better by moving `alert` inside the context of `alerts`

```suggestion
  alerts: {
    contextQueries: {
      alert: {
        // contextQueries: {
        // This query key is a placeholder , it will be updated once the relevant queries are added
        queryKey: null,
      },
      all: (params: Params = {}, filter: Filter = {}) => ({
        queryFn: () => getAllAlertsRequest(params, filter),
        queryKey: [params, filter],
      }),
    },
    queryKey: null,
  },
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +          {isError === true && (
No need to put `=== true` for a boolean value

```suggestion
          {isError && (
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +          {isLoading === true && <TableRowLoading columns={7} />}
```suggestion
          {isLoading && <TableRowLoading columns={7} />}
```

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +              }}
What is going on here?

2024-12-03 19:00 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +              label="lastModified"
Options because it doesn't matter right now, but we usually we make these values align with the API response. So in this case, `updated`. This makes API ordering work easily when it's time to implement it if you are going that route. 

Same goes for other table cells

2024-12-04 03:18 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +              label="lastModified"
We are not going for API ordering. These columns are aligned to the UX mockup hence named the labels appropriately.

2024-12-04 03:18 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +          {isError === true && (
Understood, it is redundant. Will make the change.

2024-12-04 03:19 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +          {isLoading === true && <TableRowLoading columns={7} />}
Understood, it is redundant. Will make the change.

2024-12-04 03:20 UTC, santoshp210-akamai commented on packages/manager/src/queries/cloudpulse/queries.ts
> +  },
In the future it might be a single `getAlertById` endpoint. Does it make sense for it to be under `alerts._ctx.alert` ?

2024-12-04 03:24 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +  const { data: alerts, isError, isLoading } = useAllAlertDefinitionsQuery();
We are going with client side paginate as decided during the API specification discussion. As per the mockups: https://www.figma.com/design/26kXnWVNU5tK2xQdDdISuC/Custom-Alerts?node-id=182-31355&node-type=canvas&t=RpnzXG6qoW63ls4N-0. 

We have a searching, filtering functionality to be added for these alerts and we are not doing that from API side, so pagination also is being done client side.

2024-12-04 03:30 UTC, santoshp210-akamai commented on packages/api-v4/src/cloudpulse/alerts.ts
> +import { Params, Filter, ResourcePage } from 'src/types';
Sure, will make that change.

2024-12-04 03:32 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
> +*/
This was mainly to let the reviewers and developers know that the current file is in a temporary stage. Will make the change and will follow that for future PRs

2024-12-04 15:53 UTC, bnussman-akamai commented on packages/manager/src/queries/cloudpulse/queries.ts
> +  },
Take this example: You need to invalidate **all** alerts. 

If we structure our query keys like this:
```
["alerts", "all"]
["alert", 1]
```

You have to make multiple invalidations calls to invalidate all alerts:
```typescript
queryClient.invalidateQueries(["alerts"])
queryClient.invalidateQueries(["alert"])
```

<hr />

On the other hand, we structure our query keys like this:
```
["alerts", "all"]
["alerts", "alert", 1]
```

You now can use one invalidation to invalidate **all** alert queries:
```typescript
queryClient.invalidateQueries(["alerts"])
```

React Query matches query keys **based on their prefix** so it is in our best interest to structure our query keys accordingly.

2024-12-04 17:15 UTC, santoshp210-akamai commented on packages/manager/src/queries/cloudpulse/queries.ts
> +  },
Okay will make the suggested changes

2024-12-05 13:05 UTC, jaalah-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
> +        <Typography color={status === 'enabled' ? 'limegreen' : 'gray'}>
We should be using our theme colors here. `Theme.tokens.Color.Green[70]` and then a similar one for the grey

2024-12-05 16:00 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
> +        <Typography color={status === 'enabled' ? 'limegreen' : 'gray'}>
Replaced them with appropriate Theme colors

2024-12-05 16:01 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +            </TableSortCell>
Created a map in `AlertsListing/constants.ts` and mapped over them.

2024-12-05 23:07 UTC, bnussman-akamai approved these changes

2024-12-05 23:07 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +            })}
Optional: we can use the shorthand 

```suggestion
            {AlertListingTableLabelMap.map((value, idx) => (
              <TableSortCell
                active={true}
                direction={order}
                handleClick={handleOrderChange}
                key={idx}
                label={value.label}
              >
                {value.colName}
              </TableSortCell>
            ))}
```

2024-12-05 23:07 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +                  key={idx}
We may want to use `value.label` as the key. See the "[Pitfalls](https://react.dev/learn/rendering-lists#why-does-react-need-keys)" on this page

2024-12-05 23:07 UTC, bnussman-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
> +      </TableCell>
This is fine but I'm wondering why UX didn't just use our [Status Icon](https://design.linode.com/?path=/docs/icons-statusicon--documentation)

2024-12-06 10:27 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +            })}
Yeah, using the shorthand

2024-12-06 10:27 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
> +                  key={idx}
The table is static, so having index shouldn't impact us. But made the change

2024-12-06 14:10 UTC, jaalah-akamai approved these changes

2024-12-06 14:11 UTC, jaalah-akamai commented
@santoshp210-akamai Update with latest from develop and we'll merge this - it's good to go

2024-12-10 14:18 UTC, merged