feat: [UIE-8269], [UIE-8290] - DBaaS: Access Controls text update, fix defaultDB for legacy instances
linode/manager pull request #11371
Opened 2024-12-04 19:36 UTC by mpolotsk-akamai

## Description 📝

DBaaS: Access Controls text update, fix defaultDB for legacy instances

## Changes  🔄

- Summary Tab: updated 'Database name' for legacy instances
- Database Create > Access Controls: updated copy, placeholder, button text 
- Settings Tab > Manage Access: updated copy (only for new instances)
- Manage Access Drawer: updated copy, placeholder, button text (only for new instances)

## Target release date 🗓️

12/10/24

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2024-12-04 at 8 19 32 PM](https://github.com/user-attachments/assets/f47b6447-9045-47fa-a28c-173ea78d033c) | ![Screenshot 2024-12-04 at 8 19 48 PM](https://github.com/user-attachments/assets/eea23fa1-49b7-4d36-97c1-7b50cf7f351d) |
| ![Screenshot 2024-12-04 at 8 20 33 PM](https://github.com/user-attachments/assets/d237ca15-4dcb-4646-b50b-2a5cf2d3446c) | ![Screenshot 2024-12-04 at 8 21 02 PM](https://github.com/user-attachments/assets/4ca20365-9f0e-4341-83a5-a23094b95ffb) |
| ![Screenshot 2024-12-04 at 8 22 32 PM](https://github.com/user-attachments/assets/825f1aac-cefb-464a-9de5-b5df6137f594) | ![Screenshot 2024-12-04 at 8 22 45 PM](https://github.com/user-attachments/assets/2d770eb1-2526-48fb-9dfe-60b9f8eb9999) |
| ![Screenshot 2024-12-04 at 8 24 44 PM](https://github.com/user-attachments/assets/c3a4be65-ff22-4bf9-b76a-9f5ce34e1460) | ![Screenshot 2024-12-04 at 8 24 37 PM](https://github.com/user-attachments/assets/0ba7ae8a-910d-47b3-9b7d-af5356439806) |

## How to test 🧪

### Prerequisites

(How to setup test environment)
- dbaasV2 feature flag set to GA

### Verification steps

(How to verify changes)

- Select the legacy database and navigate to the Summary tab. Verify that the Database Name value is updated.
- Navigate to the Database Create > Access Controls. The copy text, placeholder, and button text are updated.
- Navigate to the Settings tab and select Manage Access. The copy text is updated (applicable only for new instances).
- On the Landing Page, click the Action Menu and choose Manage Access Controls. Verify that the Manage Access Drawer has updated copy text, placeholder, and button text (applicable only for new instances).

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

</details>

2024-12-04 20:23 UTC, cpathipa approved these changes
LGTM! Confirming on copy updates in Summary tab and Manage Access Controls.

2024-12-04 20:31 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +          <Link to={learnMoreLink}>Learn more</Link>
```suggestion
          <Link to={learnMoreLink}>Learn more</Link>.
```

2024-12-04 20:31 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +    : 'https://techdocs.akamai.com/cloud-computing/docs/manage-access-controls';
Ideally we'd have these URLs in a `Databases/constants.ts` file (see `VPCs/constants.ts` as an example on how to structure the file and variable names)

2024-12-04 20:31 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +        : 'Add or remove IPv4 addresses or ranges that should be authorized to access your cluster.'}
would be good to get this copy in a `Databases/constants.ts` file also

2024-12-05 12:42 UTC, mpolotsk-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
> +        : 'Add or remove IPv4 addresses or ranges that should be authorized to access your cluster.'}
I've moved all that links and text to the new Databases/constants.ts
Thank you for the review!

2024-12-05 15:35 UTC, dwiley-akamai approved these changes

2024-12-05 15:48 UTC, jdamore-linode requested changes
@mpolotsk-akamai It looks like these changes may have broken the DBaaS update tests. Mind taking care of that before we merge? cc @cpathipa

2024-12-05 15:52 UTC, cpathipa commented
Yes, Just verified failed tests are passed in develop, But failed on this PR @mpolotsk-akamai Could you please take a look.

2024-12-05 17:16 UTC, merged