feat: [UIE-8138] - IAM RBAC: add new no assigned roles component
linode/manager pull request #11401
Opened 2024-12-11 13:17 UTC by aaleksee-akamai

## Description 📝

IAM RBAC - new no assigned roles component

## Changes  🔄

List any change(s) relevant to the reviewer.

- new no assigned roles component

## Target release date 🗓️

1/14/25 (dev)

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 |![image](https://github.com/user-attachments/assets/1241987e-4a8d-4e0d-ad8c-8d2cd578e331)|
| 📷 |![image](https://github.com/user-attachments/assets/c16469ad-a0fa-401a-b9dc-7a840e763fa9)|
| 📷 |![image](https://github.com/user-attachments/assets/f7e4fa17-3852-44eb-9d15-bf7ef7f129ac)|
| 📷 |![image](https://github.com/user-attachments/assets/d60464b8-4f5e-4513-a83b-4fbdeeabc136)|

## How to test 🧪

### Prerequisites

(How to setup test environment)

- Ensure the Identity and Access Beta flag is enabled in dev tools
- Click on the username in the users table and go to the tab `Assigned Roles` or click on the user's menu `View User Roles`
- Click on the username in the users table and go to the tab `Assigned Resources` or click on the user's menu `View User Roles` and go to the tab `Assigned Resources`
- Only mock user has some roles assigned

### Verification steps

- [x]  Confirm no assigned roles component renders for `Assigned Roles` tab when the user doesn't have any roles assigned.
- [x]  Confirm no assigned roles component doesn't renders for `Assigned Roles` tab when the user has some roles assigned.
- [x] Confirm no assigned roles component renders for `Assigned Resources` tab when the user doesn't have any roles assigned.
- [x]  Confirm no assigned roles component doesn't renders for `Assigned Resources` tab when the user has some roles assigned.

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [x] All unit tests are passing
- [x] TypeScript compilation succeeded without errors
- [x] Code passes all linting rules

</details>

2024-12-11 15:21 UTC, bnussman-akamai requested changes
Looking good! Just a handful of minor things

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Shared/NoAssignedRoles/NoAssignedRoles.tsx
> +    </Paper>
Is the use of `Grid` intentional here? Usually we like to reserve `Grid` for complex layouts only. In this case, you could just apply the intended styles to the `Paper`

```suggestion
    <Paper
      sx={{
        alignItems: 'center',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        paddingY: 16,
      }}
      variant="outlined"
    >
      <EmptyNotificationIcon />
      <Typography sx={{ marginTop: 1 }}>{text}</Typography>
    </Paper>
```

Or alternatively, you could use a `Stack`

```suggestion
    <Paper variant="outlined">
      <Stack alignItems="center" paddingY={10} spacing={2}>
        <EmptyNotificationIcon />
        <Typography sx={{ marginTop: 1 }}>{text}</Typography>
      </Stack>
    </Paper>
```

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UserResources/UserResources.tsx
> +        )}
Similar feedback here about `Grid`. Let's try to use `Stack` for these simple layouts. 

```suggestion
        <Stack spacing={3}>
          <Typography variant="h2">Assigned Resources</Typography>
          {hasAssignedRoles ? (
            <p>UIE-8139 - RBAC-5: User Roles - Resources Table</p>
          ) : (
            <NoAssignedRoles text={NO_ASSIGNED_RESOURCES_TEXT} />
          )}
        </Stack>
```

I know this code is unfinished and likely to evolve, but I still think `Stack` is preferable here. For example, if we need to add a button, it will be as simple as:

```typescript
        <Stack spacing={3}>
          <Stack
            alignItems="center"
            direction="row"
            justifyContent="space-between"
          >
            <Typography variant="h2">Assigned Resources</Typography>
            <Button buttonType="primary">New Button</Button>
          </Stack>
          {hasAssignedRoles ? (
            <p>UIE-8139 - RBAC-5: User Roles - Resources Table</p>
          ) : (
            <NoAssignedRoles text={NO_ASSIGNED_RESOURCES_TEXT} />
          )}
        </Stack>
```

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
> +        >
Can we make the same change here? Switch from Grid to Stack

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/assets/icons/emptynotification.svg
> +</svg>
Can we update the svg to inherit the `currentColor`? This makes dark mode better

| Before  | After   |
|---|---|
|  ![Screenshot 2024-12-11 at 10 12 59 AM](https://github.com/user-attachments/assets/20dddfbb-6f5e-4582-8fa3-032670388207) | ![Screenshot 2024-12-11 at 10 12 51 AM](https://github.com/user-attachments/assets/97302048-8f75-4afd-8058-1c65ff1a7982)  |


```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 44 44" fill="none">
  <g clip-path="url(#clip0_1595_73275)">
    <path d="M18.333 9.16667C18.333 8.19421 18.7193 7.26158 19.407 6.57394C20.0946 5.88631 21.0272 5.5 21.9997 5.5C22.9721 5.5 23.9048 5.88631 24.5924 6.57394C25.28 7.26158 25.6663 8.19421 25.6663 9.16667C27.7718 10.1622 29.5666 11.7119 30.8584 13.6497C32.1503 15.5875 32.8905 17.8403 32.9997 20.1667V25.6667C33.1376 26.8065 33.5413 27.8979 34.1782 28.8532C34.815 29.8085 35.6673 30.6009 36.6663 31.1667H7.33301C8.33206 30.6009 9.18432 29.8085 9.82118 28.8532C10.458 27.8979 10.8617 26.8065 10.9997 25.6667V20.1667C11.1089 17.8403 11.8491 15.5875 13.1409 13.6497C14.4328 11.7119 16.2276 10.1622 18.333 9.16667Z" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M16.5 31.1665V32.9998C16.5 34.4585 17.0795 35.8575 18.1109 36.8889C19.1424 37.9204 20.5413 38.4998 22 38.4998C23.4587 38.4998 24.8576 37.9204 25.8891 36.8889C26.9205 35.8575 27.5 34.4585 27.5 32.9998V31.1665" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M38.5003 12.3328C37.2977 9.71713 35.5515 7.38777 33.3779 5.5" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M5.5 12.3328C6.70147 9.71747 8.44644 7.38814 10.6187 5.5" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
</svg>
```

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserRoles assignedRoles={assignedRoles ?? {}} />
Rather than passing this via props, you could consider moving the `useAccountUserPermissions` hook into the components themselves. It could result in less prop drilling and cleaner code

2024-12-11 15:21 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserResources assignedRoles={assignedRoles ?? {}} />
Is there any specific reason for using `{}` as a fallback? We could just pass 
```suggestion
            <UserResources assignedRoles={assignedRoles} />
```

And handle `undefined` rather than `{}`

2024-12-12 10:39 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/NoAssignedRoles/NoAssignedRoles.tsx
> +    </Paper>
sure, done

2024-12-12 10:39 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UserResources/UserResources.tsx
> +        )}
sure, done

2024-12-12 10:40 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
> +        >
sure, done

2024-12-12 10:41 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserResources assignedRoles={assignedRoles ?? {}} />
yep, updated it as well, thanks!

2024-12-12 10:45 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserRoles assignedRoles={assignedRoles ?? {}} />
to be honest, I'm not sure what is better. 
we have:

```
function ParentComponent() {
  return (
    <>
      <Child1 />
      <Child2 />
      <Child3 />
    </>
  );
}
```


Should we make a call three times for each child, or is it better to send `assignedRoles` as a prop to all of them?

2024-12-12 13:42 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserRoles assignedRoles={assignedRoles ?? {}} />
Either is fine! React Query is smart enough to only fire off one API call so the performance will be the same either way

2024-12-12 13:46 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
> +            <UserRoles assignedRoles={assignedRoles ?? {}} />
I don't have any preferences, so if you want me to move that call into each child, I'll do that, otherwise it'll be with props

2024-12-13 16:24 UTC, bnussman-akamai approved these changes
Thanks for addressing that feedback

2024-12-16 14:49 UTC, merged