feat: [UIE-8136] - IAM RBAC: add new users table component (part 2)
linode/manager pull request #11402
Opened 2024-12-11 14:23 UTC by aaleksee-akamai

## Description 📝

IAM RBAC - users table component.
Includes the table for proxy users and the logic for deleting and filtering them, and an adding a new user.

## Changes  🔄

List any change(s) relevant to the reviewer.

- Table for proxy users
- Deleting users
- Adding user

## Target release date 🗓️

1/14/25 (dev)

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites

(How to setup test environment)

- Ensure the Identity and Access Beta flag is enabled in dev tools

### Verification steps

(How to verify changes)

- [ ] Confirm table renders.
- [ ] Confirm adding a new user
- [ ] Confirm deleting an user

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [ ] All unit tests are passing
- [ ] TypeScript compilation succeeded without errors
- [ ] Code passes all linting rules

</details>

2024-12-20 20:30 UTC, cpathipa reviewed
Confirming on the functionality adding / deleting the user.
@aaleksee-akamai Can we make this as `CreateUserDrawer` functional component  instead of class component. It's recommended ([CM development guide](https://github.com/linode/manager/blob/develop/docs/development-guide/02-component-structure.md#function-component-definition)) to have functional component instead class components.

2024-12-20 20:30 UTC, cpathipa commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +class CreateUserDrawer extends React.Component<CreateUserDrawerProps, State> {
Can we make this a functional component?

2025-01-07 12:17 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +class CreateUserDrawer extends React.Component<CreateUserDrawerProps, State> {
sure, thanks @cpathipa

2025-01-07 18:48 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +        }
```suggestion
        label={`This user will have ${restricted ? 'limited' : 'full'} access to account features.
              This can be changed later.`}
```

2025-01-07 18:48 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +      <div style={{ marginTop: 8 }}>
Please use a `<Box>` with `sx` prop - we want to avoid using `style` attributes

2025-01-07 18:48 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +        style={{ marginTop: 8 }}
Same here, please use `sx`

2025-01-07 18:53 UTC, jaalah-akamai commented
There appears to be an extra `Paper` around the user settings. I didn't see mocks for this in the Figma file, can we confirm this is accurate?

|Prod |This|
|---|---|
|![Screenshot 2025-01-07 at 1 52 10 PM](https://github.com/user-attachments/assets/1dfebe74-28ea-4c92-b089-99d66cf45add)|![Screenshot 2025-01-07 at 1 52 02 PM](https://github.com/user-attachments/assets/4313e0c2-45f7-415d-a838-a9d446818622)|

2025-01-07 19:05 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
> +    setFilteredUsers(res);
This entire `handleSearch` function is not how this should be done and should probably be re-written. Look at some examples from the LinodeCreate flow. We should be using our query for a lot of this. `isSearching` should be `isFetching` which comes from the `useAccountUsers`

2025-01-07 19:11 UTC, bnussman-akamai requested changes

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
There are **many** better ways to handle searching here. This is unmaintainable and confusing.

Some issues I see are
- Unnecessary state (`filteredUsers`)
  - We can derive this from existing state rather than having extra state
- A fake loading state is implemented???
- Lots of one-off logic for field searching that will be difficult to maintain

I recommend using our nice API filtering utils. It uses the API to perform the actual filtering so no client side filtering is needed.  This will clean things up a ton and give users the [full capability of @linode/search](https://github.com/linode/manager/tree/develop/packages/search)
 
<details>

<summary>Full Code Example</summary>

```typescript
import { getAPIFilterFromQuery } from '@linode/search';
import { Box, Button, Paper, Typography } from '@linode/ui';
import { useMediaQuery } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import React, { useState } from 'react';

import { DebouncedSearchTextField } from 'src/components/DebouncedSearchTextField';
import { DocumentTitleSegment } from 'src/components/DocumentTitle';
import { PaginationFooter } from 'src/components/PaginationFooter/PaginationFooter';
import { Table } from 'src/components/Table';
import { TableBody } from 'src/components/TableBody';
import { useOrder } from 'src/hooks/useOrder';
import { usePagination } from 'src/hooks/usePagination';
import { useAccountUsers } from 'src/queries/account/users';
import { useProfile } from 'src/queries/profile/profile';

import { UserDeleteConfirmation } from '../../Shared/UserDeleteConfirmation';
import CreateUserDrawer from './CreateUserDrawer';
import { ProxyUserTable } from './ProxyUserTable';
import { UsersLandingTableBody } from './UsersLandingTableBody';
import { UsersLandingTableHead } from './UsersLandingTableHead';

import type { Filter } from '@linode/api-v4';

export const UsersLanding = () => {
  const [isCreateDrawerOpen, setIsCreateDrawerOpen] = React.useState<boolean>(
    false
  );
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = React.useState(false);
  const [selectedUsername, setSelectedUsername] = React.useState('');

  const [query, setQuery] = useState<string>();

  const { data: profile } = useProfile();
  const theme = useTheme();
  const pagination = usePagination(1, 'account-users');
  const order = useOrder();

  const isProxyUser =
    profile?.user_type === 'child' || profile?.user_type === 'proxy';

  const { error: searchError, filter } = getAPIFilterFromQuery(query, {
    searchableFieldsWithoutOperator: ['username', 'email'],
  });

  const usersFilter: Filter = {
    ['+order']: order.order,
    ['+order_by']: order.orderBy,
    ...filter,
  };

  // Since this query is disabled for restricted users, use isLoading.
  const { data: users, error, isFetching, isLoading } = useAccountUsers({
    filters: usersFilter,
    params: {
      page: pagination.page,
      page_size: pagination.pageSize,
    },
  });

  const isRestrictedUser = profile?.restricted;

  const isSmDown = useMediaQuery(theme.breakpoints.down('sm'));
  const isLgDown = useMediaQuery(theme.breakpoints.up('lg'));

  const numColsLg = isLgDown ? 4 : 3;

  const numCols = isSmDown ? 2 : numColsLg;

  const handleDelete = (username: string) => {
    setIsDeleteDialogOpen(true);
    setSelectedUsername(username);
  };

  return (
    <React.Fragment>
      <DocumentTitleSegment segment="Users & Grants" />
      {isProxyUser && (
        <ProxyUserTable
          handleDelete={handleDelete}
          isProxyUser={isProxyUser}
          isRestrictedUser={isRestrictedUser}
          order={order}
        />
      )}
      <Paper sx={(theme) => ({ marginTop: theme.spacing(2) })}>
        <Box
          sx={(theme) => ({
            alignItems: 'center',
            display: 'flex',
            justifyContent: 'space-between',
            marginBottom: theme.spacing(2),
          })}
        >
          {isProxyUser && (
            <Typography
              sx={(theme) => ({
                [theme.breakpoints.down('md')]: {
                  marginLeft: theme.spacing(1),
                },
              })}
              variant="h3"
            >
              User Settings
            </Typography>
          )}
          {!isProxyUser && (
            <DebouncedSearchTextField
              clearable
              debounceTime={250}
              errorText={searchError?.message}
              hideLabel
              isSearching={isFetching}
              label="Filter"
              onSearch={setQuery}
              placeholder="Filter"
              sx={{ width: 320 }}
              value=""
            />
          )}
          <Button
            tooltipText={
              isRestrictedUser
                ? 'You cannot create other users as a restricted user.'
                : undefined
            }
            buttonType="primary"
            disabled={isRestrictedUser}
            onClick={() => setIsCreateDrawerOpen(true)}
          >
            Add a User
          </Button>
        </Box>
        <Table aria-label="List of Users">
          <UsersLandingTableHead order={order} />
          <TableBody>
            <UsersLandingTableBody
              error={error}
              isLoading={isLoading}
              numCols={numCols}
              onDelete={handleDelete}
              users={users?.data ?? []}
            />
          </TableBody>
        </Table>
        <PaginationFooter
          count={users?.results ?? 0}
          eventCategory="users landing"
          handlePageChange={pagination.handlePageChange}
          handleSizeChange={pagination.handlePageSizeChange}
          page={pagination.page}
          pageSize={pagination.pageSize}
        />
      </Paper>
      <CreateUserDrawer
        onClose={() => setIsCreateDrawerOpen(false)}
        open={isCreateDrawerOpen}
      />
      <UserDeleteConfirmation
        onClose={() => setIsDeleteDialogOpen(false)}
        open={isDeleteDialogOpen}
        username={selectedUsername}
      />
    </React.Fragment>
  );
};

```

</details>

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
> +        refetch={refetch}
Lets's remove the refetch prop. We need to create a `useCreateUserMutation` hook, and that hook can handle the invalidation of our user queries.

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +  const [submitting, setSubmitting] = React.useState(false);
No no no! We should use `react-hook-form` here.

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +    createUser({ email, restricted, username })
We should create a `useCreateUserMutation` in `packages/manager/src/queries/account/users.ts` and use it here.

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +        refetch();
Once we create `useCreateUserMutation`, we can use the `onSuccess` option of that mutation to handle query invalidation/refetching

2025-01-07 19:11 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +export default withRouter(CreateUserDrawer);
Let's use the `useHistory` hook instead of this HOC

Also, let's remove this default export and just use the `CreateUserDrawer` export itself.

2025-01-08 11:34 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +        }
cool, thanks @jaalah-akamai !

2025-01-09 11:03 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
@bnussman-akamai , I understand your point, and I see that I got it wrong — thank you for suggesting the correct implementation. However, it seems something might still be missing from my side, as it seems the filter works on its own but doesn’t apply the filtered data to the table

2025-01-09 11:14 UTC, aaleksee-akamai commented
> There appears to be an extra `Paper` around the user settings. I didn't see mocks for this in the Figma file, can we confirm this is accurate?
> 
> Prod	This
> ![Screenshot 2025-01-07 at 1 52 10 PM](https://private-user-images.githubusercontent.com/125309814/400884994-1dfebe74-28ea-4c92-b089-99d66cf45add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MjA5ODEsIm5iZiI6MTczNjQyMDY4MSwicGF0aCI6Ii8xMjUzMDk4MTQvNDAwODg0OTk0LTFkZmViZTc0LTI4ZWEtNGM5Mi1iMDg5LTk5ZDY2Y2Y0NWFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQxMTA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTIyZWU5MDZkNzAwZjg0YTdmZTFkODIyMjljY2U3MTU1ZGIzYTk2ZDIxMDJlNTU2NDlkYzkyMDY3ZmY0NTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1QoEQD3dNX3tFTg0Wo6V6in20FuI4_KRvWNO9auOtX4)	![Screenshot 2025-01-07 at 1 52 02 PM](https://private-user-images.githubusercontent.com/125309814/400885023-4313e0c2-45f7-415d-a838-a9d446818622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MjA5ODEsIm5iZiI6MTczNjQyMDY4MSwicGF0aCI6Ii8xMjUzMDk4MTQvNDAwODg1MDIzLTQzMTNlMGMyLTQ1ZjctNDE1ZC1hODM4LWE5ZDQ0NjgxODYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQxMTA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFkOWNkODYxYTE4ZDY0MzM1NjQ0YTQyMWYwMGFhMTEzMTdiYzI1OGNkYjUyZDY5NjM1MDVhYTA3Yzk5YWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5U1yzlwBkSf8GJht1QjQxkH34PnJazXdr2rozb7xs9Q)


@jaalah-akamai , Thank you for noticing this. This happens because we add Paper for non-proxy users (you can find it [here](https://www.figma.com/design/4TxCGLWo0tpnwyrdZvv1QX/IAM%3A-Beta-%5BReady-for-Dev%5D?node-id=475-29872&m=dev)). The design for proxy users hasn’t been implemented, as it wasn’t expected to change. Currently, I don’t see an easy way to ensure that Paper is only for non-proxy users without duplications. I can confirm this with the design team, but it won’t be earlier than Monday.

2025-01-13 17:24 UTC, cpathipa approved these changes
Confirming on the functionality, Approving pending changes suggested by Banks and Jaalah. 
- Table for proxy users
- Deleting users
- Adding user

2025-01-13 17:32 UTC, bnussman-akamai commented on packages/manager/src/queries/account/users.ts
> +export const useCreateUserMutation = () => {
Looks great!

2025-01-13 17:37 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
Seems to be working nicely for me!

https://github.com/user-attachments/assets/cc54252d-5350-469d-9015-dcb2eec1bd45

https://github.com/user-attachments/assets/02847799-9c74-407e-b191-1acfc0b0631e

2025-01-14 13:48 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
> +          )}
cool, thanks @cpathipa

2025-01-14 14:08 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +                    field.onChange(!e.target.checked);
thanks @bnussman-akamai , I've changed on that, it seems working, let me know if there is another way to do it better

2025-01-14 14:13 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
@bnussman-akamai , that's interesting. so it doesn't work with mock data then?

2025-01-14 15:03 UTC, jaalah-akamai approved these changes
@aaleksee-akamai This is looking great! 👏

2025-01-14 15:03 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Shared/UserDeleteConfirmation.tsx
> +        <Typography sx={{ fontSize: '0.875rem' }}>
It receives this fontSize by default
```suggestion
        <Typography>
```

2025-01-14 17:20 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
That's correct. Our mock service worker don't fully support X-filtering but the real API does

2025-01-15 12:10 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/UserDeleteConfirmation.tsx
> +        <Typography sx={{ fontSize: '0.875rem' }}>
sure, thanks @jaalah-akamai

2025-01-15 17:50 UTC, bnussman-akamai approved these changes

2025-01-15 17:50 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
> +                    field.onChange(!e.target.checked);
Change looks good. I recommend moving the `onChange` and `checked` to the `FormControlLabel` component rather than the `Toggle` directly. That's how it is intended to be used

2025-01-16 15:42 UTC, cpathipa commented
@aaleksee-akamaiThank you for addressing all the feedback. This PR is good to go with the above recommendation.

2025-01-17 15:51 UTC, merged