feat: [UIE-8134] - IAM RBAC: add new entities component
linode/manager pull request #11429
Opened 2024-12-17 13:30 UTC by aaleksee-akamai

## Description 📝

IAM RBAC - new entities component. This component currently uses mock data for demonstration purposes. The mock data will be removed in the next PR for the `Assign Permission component`.

## Changes  🔄

List any change(s) relevant to the reviewer.

- new entities component

## Target release date 🗓️

1/14/25 (dev)

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | ![image](https://github.com/user-attachments/assets/e43789a3-fd15-4379-b442-e80c98e38963) |

## How to test 🧪

### Prerequisites

(How to setup test environment)

- Ensure the Identity and Access Beta flag is enabled in dev tools
- Click on the username in the users table and go to the tab Assigned Roles or click on the user's menu View User Roles

### Verification steps

(How to verify changes)

- [x]  Confirm entities component renders.

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support

<br/>

- [x] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [ ] All unit tests are passing
- [ ] TypeScript compilation succeeded without errors
- [ ] Code passes all linting rules

</details>

2024-12-17 14:20 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Shared/utilities.ts
> +  vpc: 'Select Vpcs',
```suggestion
  vpc: 'Select VPCs',
```

2024-12-17 15:48 UTC, abailly-akamai commented on packages/manager/src/mocks/serverHandlers.ts
> +  http.get('*/resources', () => {
This could potentially intercept bundles named `resources` (i know we're not adding `v4` or `v4beta` consistently  but adding the `v4*/` prefix - ex: `v4*/resources` to your intercept) will ensure we're only targeting APINext.

2024-12-18 15:04 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/utilities.ts
> +  vpc: 'Select Vpcs',
thanks @bnussman-akamai , done

2024-12-18 15:04 UTC, aaleksee-akamai commented on packages/manager/src/mocks/serverHandlers.ts
> +  http.get('*/resources', () => {
thanks @abailly-akamai , done

2024-12-30 14:52 UTC, abailly-akamai approved these changes
Looks good! Approving pending small fix to the Autocomplete instance label

2024-12-30 14:52 UTC, abailly-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +          label=""
This breaks accessibility - If you don't want to display a label, still pass it as you would do usually and use the `hideLabel` property from `textFieldProps`

2025-01-02 14:19 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +};
We usually use **interfaces** when possible

```suggestion
interface Props {
  access: IamAccessType;
  type: ResourceType | ResourceTypePermissions;
}
```

2025-01-02 14:22 UTC, bnussman-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +      <StyledTypography>Entities</StyledTypography>
Why are we a Typography instead of the built in `label` on the autocomplete? Like Alban mentioned, there are accessibility implications to this.

2025-01-02 15:14 UTC, cpathipa approved these changes
@aaleksee-akamai Changes LGTM. I agreed with Banks feedback and it is good to go once the feedback is addressed and the conflict's are resolved.

2025-01-07 10:29 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +          label=""
thanks @abailly-akamai , done

2025-01-07 10:29 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +};
thanks @bnussman-akamai , done

2025-01-07 10:33 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +      <StyledTypography>Entities</StyledTypography>
The reason I do this is that we need a styled title, and I haven’t found a way to style a label. If it’s possible to style a label, I can use one instead.

2025-01-07 22:52 UTC, jaalah-akamai requested changes

2025-01-07 22:52 UTC, jaalah-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +      <StyledTypography>Entities</StyledTypography>
Please use the `label` from `Autocomplete`. The darker color for the label will come with our design token refresh when we get to this component. For now it should just follow the built-in color styles.

2025-01-08 11:22 UTC, aaleksee-akamai commented on packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
> +      <StyledTypography>Entities</StyledTypography>
@jaalah-akamai , so, are you saying this would be better? I still need this title for `account_access`. Also, what about the styles for the label and title? Do I need to make the title the same as the label?

```
  return access === 'account_access' ? (
    <>
      <StyledTypography>Entities</StyledTypography>
      {type === 'account' ? (
        <Typography>All entities</Typography>
      ) : (
        <Typography>All {type}s</Typography>
      )}
    </>
  ) : (
    <Autocomplete
      renderOption={(props, option) => (
        <li {...props} key={option.label}>
          {option.label}
        </li>
      )}
      ListboxProps={{ sx: { overflowX: 'hidden' } }}
      isOptionEqualToValue={(option, value) => option.label === value.label}
      label="Entities"
      multiple
      onChange={(_, value) => setSelectedEntities(value)}
      options={memoizedEntities}
      placeholder={placeholder}
    />
  );
  ```

2025-01-09 22:13 UTC, jaalah-akamai approved these changes

2025-01-09 22:14 UTC, jaalah-akamai commented
@aaleksee-akamai Let's update this branch with `develop` to fix all the test failures - otherwise this looks good

2025-01-10 15:46 UTC, corya-akamai reviewed
test

2025-01-10 15:47 UTC, corya-akamai approved these changes

2025-01-10 17:55 UTC, cpathipa approved these changes

2025-01-10 17:56 UTC, merged