refactor: [M3-9016] - Domain Records
linode/manager pull request #11447
Opened 2024-12-20 12:41 UTC by pmakode-akamai

## Description 📝

Highlight the Pull Request's context and intentions.

## Changes  🔄

List any change(s) relevant to the reviewer.

- ...
- ...

## Target release date 🗓️

Please specify a release date (and environment, if applicable) to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites

(How to setup test environment)

- ...
- ...

### Reproduction steps

(How to reproduce the issue, if applicable)

- [ ] ...
- [ ] ...

### Verification steps

(How to verify changes)

- [ ] ...
- [ ] ...

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

👀 Doing a self review
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
🤏 Splitting feature into small PRs
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
🧪 Providing/improving test coverage
 🔐 Removing all sensitive information from the code and PR description
🚩 Using a feature flag to protect the release
👣 Providing comprehensive reproduction steps
📑 Providing or updating our documentation
🕛 Scheduling a pair reviewing session
📱 Providing mobile support
♿  Providing accessibility support
</details>

- [ ] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [ ] All unit tests are passing
- [ ] TypeScript compilation succeeded without errors
- [ ] Code passes all linting rules

2025-01-03 14:08 UTC, pmakode-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +import { lensPath, over } from 'ramda';
I see there's another ticket (M3-8252) to remove ramda from Domains/Domain Records. I think this can be addressed there.

2025-01-07 22:38 UTC, mjac0bs approved these changes
Functionality looked good for creating, modifying, and deleting domain records.

I left some feedback that is more minor and/or stylistic.

2025-01-07 22:38 UTC, mjac0bs commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawer.tsx
Noticed a console error when opening and closing this drawer. I can file a separate bug ticket since this component was barely touched in this refactor.

![consoleerrorradiobuttons](https://github.com/user-attachments/assets/a2c5e3d7-96df-444d-9ceb-312830078e86)

2025-01-07 22:38 UTC, mjac0bs commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.styles.ts
>  export const StyledTableCell = styled(TableCell, { label: 'StyledTabelCell' })(
```suggestion
export const StyledTableCell = styled(TableCell, { label: 'StyledTableCell' })(
```
Nit: existing typo

2025-01-08 04:51 UTC, harsh-akamai approved these changes
Thanks for the PR! 🙌 
Approving pending Mariah's comments

2025-01-08 14:28 UTC, abailly-akamai requested changes
Thanks for taking this on! Left code suggestion to improve the overall code quality - converting `DomainRecordDrawer` should also be a requirement unless you are planning to do it as a follow up (I do think it falls within the scope of this PR)

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawer.tsx
Perhaps more importantly, it appears `DomainRecordDrawer` still is a class component - do you intend this conversion as a follow up task or was it an omission?

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +import { lensPath, over } from 'ramda';
agreed to keep this a separate effort and keep the scope tight

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +  };
💯 agreed

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +  const openForEditPrimaryDomain = (f: Partial<Domain>) =>
same applies here and below!

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +      scrollErrorIntoView();
++

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +        const ref: React.RefObject<HTMLDivElement> = React.createRef();
Did you intend to have the ref within the loop? I could see scope issues with this approach. Ideally I think you would want to declare a Array of refs?

pseudo code

outside of the map:
```
const refs: React.RefObject<HTMLDivElement>[] = React.createRef([]);
```

within the map:
```
{state.types.map((type, eachTypeIdx) => {
  <item ref={element => refs.current[index] = element} />
```

something like that. I am not 100% sure, perhaps your solution works fine but this seems to me like an unusual pattern.

2025-01-08 14:28 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordTable.tsx
> +                  {type.columns.length > 0 &&
small thing, but `idx` as indexes can lead to undesirable side effects - usually a good idea to interpolate and get a more unique value ex:

```
<TableRow data-qa-record-row={type.title} key={`domain-record-${idx}`}>
```

2025-01-09 07:06 UTC, pmakode-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawer.tsx
@abailly-akamai As per M3-9016, the focus is on converting `DomainRecords.tsx` to a functional component. I’ll create a follow-up PR for `DomainRecordDrawer`, since it’s a larger component.

2025-01-09 10:29 UTC, pmakode-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawer.tsx
@mjac0bs The console error doesn’t seem to be related (reproducible on dev branch). I believe the issue is originating from the `EditDomainDrawer` component (which isn’t touched in this PR), not from the `DomainRecordDrawer`

2025-01-09 10:46 UTC, pmakode-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +        const ref: React.RefObject<HTMLDivElement> = React.createRef();
The ref within the loop is part of the existing pattern (see https://github.com/linode/manager/blob/develop/packages/manager/src/features/Domains/DomainRecords.tsx#L638-L649), I haven't made any modifications to this part in my changes.

2025-01-09 15:25 UTC, pmakode-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordsUtils.ts
> +export const prependLinodeNS = compose<any, any, DomainRecord[]>(
Improving the typing of the `any`s here wasn't straightforward, so I refactored `getNSRecords`, `prependLinodeNS`, and `typeEq` to remove their dependency on ramda (commit f5a55249538bf8d8e83264c3af6820c63286ec2e)

2025-01-09 15:29 UTC, abailly-akamai approved these changes

2025-01-09 15:29 UTC, abailly-akamai commented on packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
> +        const ref: React.RefObject<HTMLDivElement> = React.createRef();
ok - does not mean it's great but i agree we don't have to fix something that's not broken

2025-01-13 06:27 UTC, merged