M3-4489: CMR Header for Object Storage > Buckets & Object Storage > Access Key
linode/manager pull request #6870
Opened 2020-09-03 20:48 UTC by DevDW

## Description
Apply CMR Header to Object Storage Access Key and Buckets landing pages

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Access Key page

2020-09-03 20:50 UTC, DevDW commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable_CMR.tsx
> +            </Grid> */}
I have this commented out momentarily because I noticed that using <LandingHeader /> works, but the header title is to the right slightly more than it should be because of there not being an icon.

2020-09-08 12:27 UTC, johnwcallahan requested changes
Code changes make sense, though the table needs to be called "Buckets" and the button should say "Create a Bucket...".

![Screen Shot 2020-09-08 at 8 24 50 AM](https://user-images.githubusercontent.com/16911484/92476486-08f2fd80-f1ad-11ea-95f0-b4635ee882dc.png)

Unrelated, there's a console warning happening here, probably for reasons similar to https://github.com/linode/manager/pull/6876. Could either be fixed here or filed in a separate ticket.

2020-09-08 14:54 UTC, DevDW commented
> Unrelated, there's a console warning happening here, probably for reasons similar to #6876. Could either be fixed here or filed in a separate ticket.

Thanks @johnwcallahan, I will take care of the console warning issue in a separate ticket & PR.

2020-09-08 18:04 UTC, Jskobos approved these changes
Table headers look good now. We haven't been very careful about document titles in CMR, we should fix this one (marking as non-blocking since this is happening in production too, please open a ticket for this):

![Screen Shot 2020-09-08 at 1 57 44 PM](https://user-images.githubusercontent.com/1624067/92511575-7cabff00-f1db-11ea-9408-e8196ca5a488.png)

2020-09-08 19:05 UTC, johnwcallahan approved these changes

2020-09-08 21:31 UTC, tiffwong approved these changes

2020-09-08 21:45 UTC, merged