[CMR] M3-4511: Remove container around StackScript table
linode/manager pull request #6879
Opened 2020-09-08 14:48 UTC by tiffwong

Remove the white container around the table and adjust the spacing to improve the grouping as mentioned in the demo prep

2020-09-08 18:36 UTC, Jskobos requested changes
Matches the design overall. This happened elsewhere too, but some of the padding is lost under the header, makes it look a little unbalanced:

![Screen Shot 2020-09-08 at 2 28 49 PM](https://user-images.githubusercontent.com/1624067/92514861-a3b8ff80-f1e0-11ea-9f37-21584cdd5395.png)

2020-09-08 20:52 UTC, tiffwong commented
> Matches the design overall. This happened elsewhere too, but some of the padding is lost under the header, makes it look a little unbalanced:
> 
> ![Screen Shot 2020-09-08 at 2 28 49 PM](https://user-images.githubusercontent.com/1624067/92514861-a3b8ff80-f1e0-11ea-9f37-21584cdd5395.png)

Gah, thanks for catching that!

2020-09-09 13:51 UTC, Jskobos approved these changes

2020-09-09 14:04 UTC, DevDW approved these changes
LGTM, the only thing I'd raise is that perhaps "StackScripts" should be aligned on its left margin with "Account StackScripts"

2020-09-11 15:00 UTC, merged