M3-4505: CMR Table Styles for OBJ Bucket Detail
linode/manager pull request #6885
Opened 2020-09-08 21:23 UTC by DevDW

## Description
CMR table styles for table on Bucket Detail page

## Type of Change
- Non breaking change ('update', 'change')

## To-Do

- [ ] Fix tabling styling for consistency with other tables
- [ ] ObjectActionMenu

2020-09-10 21:04 UTC, Jskobos requested changes
Styles look good. Two things left:

1. Build is failing because of your earlier PR, gotta remove hideLabelOnMobile or whatever here too
2. If you have a "folder", clicking on it should "open" the "folder". It's all fake, but there doesn't seem to be any click handling at all going on in the rows. Compare test account 4 on develop and on this branch.

2020-09-10 21:05 UTC, Jskobos commented
Maybe we'd also want to hide the "last modified" column on smDown.

2020-09-14 15:47 UTC, WilkinsKa1 approved these changes

2020-09-14 16:57 UTC, DevDW commented on packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
> +      {/* Three empty TableCells corresponding to the Size, Last Modified, and Action Menu (for ObjectTableRow) columns for formatting purposes. */}
This also fixes a small bug in production in the folder row in mobile view–"Size" and "Last Modified" should not display in-row as table cell values:

<img width="426" alt="Screen Shot 2020-09-14 at 12 53 43 PM" src="https://user-images.githubusercontent.com/32860776/93115371-bcfef780-f689-11ea-901d-8822fb64db95.png">

2020-09-14 18:23 UTC, tiffwong approved these changes

2020-09-14 20:08 UTC, Jskobos approved these changes

2020-09-14 20:08 UTC, Jskobos commented on packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
> +      {/* Three empty TableCells corresponding to the Size, Last Modified, and Action Menu (for ObjectTableRow) columns for formatting purposes. */}
👍  good catch

2020-09-14 20:14 UTC, merged