[CMR] M3-4206 pt3: Prevent text from being flush to the screen
linode/manager pull request #6907
Opened 2020-09-15 19:35 UTC by tiffwong

## Description
This PR will address the feedback from [https://github.com/linode/manager/pull/6853](https://github.com/linode/manager/pull/6853) which includes:
- [x] Linode Details: Backups / Activity Logs / Settings tabs
- [x] StackScripts Landing
- [ ] Lonview Details
- [x] Profile
- [x] Search Landing
- [x] Support Ticket Landing

## Type of Change
- Non breaking change ('update', 'change')

2020-09-16 17:06 UTC, DevDW reviewed
Nice work; I noticed a couple of small things:

1. The filter box and "Sort by" label are flush to the screen on the Longview landing page
<img width="834" alt="Screen Shot 2020-09-16 at 12 49 10 PM" src="https://user-images.githubusercontent.com/32860776/93369180-fb78eb80-f81c-11ea-893b-bc6afe655f1d.png">

2. "Duration" looks like it has an extra space in front of it
<img width="834" alt="Screen Shot 2020-09-16 at 12 47 30 PM" src="https://user-images.githubusercontent.com/32860776/93369324-38dd7900-f81d-11ea-9fe3-bf4d88d8b2fb.png">

2020-09-18 18:36 UTC, johnwcallahan approved these changes

2020-09-18 18:36 UTC, johnwcallahan commented on packages/manager/src/features/Search/SearchLanding.tsx
> +              Sorry, no results for this one
Ha, good catch.

2020-09-18 18:36 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity_CMR.tsx
> +        Activity Logs
I think I missed it... where is this change coming from? Seems like "Activity Log" might be better.

2020-09-18 19:34 UTC, WilkinsKa1 requested changes
Great work on this, I found a few more 😅   but then I think we should be all good:

On Linode Backups tab (at the very bottom):
<img width="756" alt="Screen Shot 2020-09-18 at 3 27 33 PM" src="https://user-images.githubusercontent.com/2565527/93637722-0cb02c80-f9c4-11ea-83b6-f1a576d9f912.png">

On Longview/overview tab:
<img width="613" alt="Screen Shot 2020-09-18 at 3 27 57 PM" src="https://user-images.githubusercontent.com/2565527/93637723-0d48c300-f9c4-11ea-944f-a102a1139863.png">

Longview/Apache tab (also on MySQL and Nginx):
<img width="613" alt="Screen Shot 2020-09-18 at 3 28 22 PM" src="https://user-images.githubusercontent.com/2565527/93637724-0d48c300-f9c4-11ea-91a2-7ba4523b20cc.png">

2020-09-21 13:47 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity_CMR.tsx
> +        Activity Logs
The tab says Activity Logs so I was trying to make them match 😅

2020-09-21 14:55 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity_CMR.tsx
> +        Activity Logs
I can change the tab to say Activity Feed instead so they'll be consistent

2020-09-22 14:54 UTC, WilkinsKa1 approved these changes
Good to go, thanks for updating!

2020-09-22 19:54 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
> -                autoFocus={true}
Linter recommended removing this

2020-09-24 15:00 UTC, merged