Cloning a domain in Cloud Manager leads to Not Found page instead of new domain page
linode/manager pull request #6911
Opened 2020-09-16 17:55 UTC by WilkinsKa1

## Description

Upon initiating a domain clone (for a master domain), the user is redirected to the details page, which initially displays a 'Not Found' page before resolving to display the details page. This PR adds a timeout to the clone action to prevent the Not found display.

## Type of Change
- Bug fix ('fix')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Note to Reviewers

To test:
On develop, clone a master domain. You should see 'Not Found' before the details page displays (or you may have to go back to the landing and re-click the newly made clone to see the details page). On this branch, you should never see 'Not found' display, only a brief loading screen.

2020-09-16 20:58 UTC, Jskobos requested changes
I'm not actually able to reproduce this, tried a bunch of clones on develop and never saw the 404. Maybe a race condition.

It's also a little unclear if this actually works in the order we're hoping it will, the timeout is in the action menu, but the redirect happens in the .then in DomainDrawer, which (I think?) is after the timeout is complete. Seems like things may be happening in a slightly different order.

In any case, I think a cleaner solution is to dispatch `upsertDomain(data)` on line 676 (sigh) of DomainDrawer. `cloneDomain` returns the new domain in its response, if we add that directly to the store before redirecting it should resolve any funkiness.

2020-09-16 20:59 UTC, Jskobos commented
though Domains are weird now, we should test this on prod-test-001 to make sure John's fallback logic is working

2020-09-16 21:54 UTC, tiffwong reviewed
I wasn't able to reproduce the issue on my account, is there a known test account that has this bug?

2020-09-17 16:17 UTC, johnwcallahan commented
FWIW I am unable to reproduce this too, but agree with Jared's proposed solution.

2020-09-17 21:58 UTC, DevDW approved these changes
Although I couldn't reproduce the issue, this should prevent the issue from arising.

2020-09-18 11:55 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainDrawer.tsx
> +        upsertDomain(data);
right action and right place, but `upsertDomain` has to be run through the totally intuitive and not at all circuitous Redux hoops and dispatched, can't use the import directly. Add it to the BindActionCreators and DispatchProps ~line 817, and make sure that every 3rd letter of the variable name is a consonant.

2020-09-25 17:21 UTC, Jskobos approved these changes
Approved pending change discussed offline.

2020-09-25 20:02 UTC, merged