M3-4540 VLAN Landing Table
linode/manager pull request #6935
Opened 2020-09-24 22:00 UTC by WilkinsKa1

## Description

Adding the landing table for VLANS. I created a very basic factory for VLANS using the service worker for testing this.

## Type of Change
- Non breaking change ('update')

## Note to Reviewers

Still left to do: 

- [ ] Linodes listing/linking handling (need to mock this out)
- [ ] Delete action handling

2020-09-28 21:56 UTC, DevDW commented on packages/manager/src/features/Vlans/VlanLanding/VlanLanding.tsx
>          title="Virtual LANS"
Minor thing I noticed when reviewing another PR but before I forget, we should change this to `Virtual LANs`

2020-09-30 16:57 UTC, Jskobos requested changes

2020-09-30 16:57 UTC, Jskobos commented on packages/manager/src/containers/vlans.container.ts
> +      if (mapAccountToProps) {
"account"

2020-09-30 16:57 UTC, Jskobos commented on packages/manager/src/factories/vlans.ts
> +  // TODO mock linodes
`[0,1,2]` or something is probably fine here, it'll match the ids of any mock linodes

2020-09-30 16:57 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanLanding/VlanActionMenu.tsx
> +  const createActions = () => (): Action[] => {
These don't need to be duplicated, if you rename `actionText` to `title` the same array should work in both places

2020-09-30 16:57 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanLanding/VlanLanding.tsx
>        dataColumn: 'label',
this needs to be "description".

2020-09-30 16:57 UTC, Jskobos commented on packages/manager/src/factories/vlans.ts
> +  cidr_block: 'eth1'
doesn't matter for mocking, but this is something like `10.0.0.0/24`

2020-09-30 18:15 UTC, Jskobos commented on packages/manager/src/store/index.ts
> +  vlans
it makes sense for these to live here, but I already put them under __resources, so they're in the store twice. you can delete mine and keep this one, but we shouldn't keep both.

2020-10-01 15:47 UTC, tiffwong approved these changes
Looks great!

2020-10-01 20:59 UTC, DevDW approved these changes

2020-10-01 20:59 UTC, DevDW commented on packages/manager/src/features/Vlans/VlanLanding/VlanActionMenu.tsx
> +          createActions={createActions()}
I believe we can delete the `createActions` function and change this line to:

`createActions={() => actions}`

(and rename `inlineActions` to `actions` ofc)

2020-10-07 19:26 UTC, johnwcallahan reviewed
UI Looks great. I'm getting an error when I delete a VLAN... it seems the Action Menu has the correct prop typing, but the deleteVlan function never actually gets passed down to it. I think you'll need to wrap it in the new VLAN container.

2020-10-09 11:49 UTC, johnwcallahan requested changes
Two quick things:

- Git didn't track the file rename, so the app wouldn't run when I pulled it down. You might have to change it to something else and change it back, or you could try `git mv`.
- Left a piece of feedback about the `delete` handler.

2020-10-09 11:49 UTC, johnwcallahan commented on packages/manager/src/containers/vlans.container.ts
> +      deleteVlan: (vlanId: { vlanID: number }) => dispatch(_delete(vlanId)),
Currently Deleting a VLAN doesn't work (it doesn't get called with the ID). This function signature and the typing on L21 don't match: this should be:

```ts
deleteVlan: (vlanID: number) => dispatch(_delete({ vlanID })),
```

2020-10-09 13:34 UTC, johnwcallahan commented on packages/manager/src/features/Vlans/VlanLanding/VlanLanding.tsx
> +  const handleOpenDeleteVlanModal = (id: number, label: string) => {
See my comment here: https://github.com/linode/manager/pull/6950#discussion_r498519314; this can similarly be just one function.

2020-10-12 20:04 UTC, johnwcallahan approved these changes

2020-10-12 20:09 UTC, merged