M3-4558 Add: VLAN attachment option to Linode create flow
linode/manager pull request #6941
Opened 2020-09-28 19:36 UTC by Jskobos

## Description

Add an "Attach to a VLAN" select to the optional addons panel in the Linode create flow.

## Note to Reviewers

2020-09-29 16:58 UTC, johnwcallahan requested changes
The placement seems fine to be. We should fix the alignment on mobile, though:

![Screen Shot 2020-09-29 at 12 42 27 PM](https://user-images.githubusercontent.com/16911484/94589427-3e8e8200-0253-11eb-9f4b-3c7512c37427.png)

Also, after selecting a Region and then another tab (like "Marketplace"), the VLAN Select is disabled even though there is a region selected.

Left a comment about an error state. 

Otherwise looks good.

2020-09-29 16:58 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
> +        {flags.cmr ? (
Should this be a VLAN flag instead?

2020-09-29 16:58 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
> +  const { vlans } = useVlans();
Should probably show an error state... right now if you block requests to `*vlans*` you just see the empty state.

2020-09-29 20:32 UTC, WilkinsKa1 requested changes
2 small feedback items, looks good otherwise!

2020-09-29 20:32 UTC, WilkinsKa1 commented on packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
> +    paddingLeft: '54px !important'
I think the placement works, can we add top/bottom padding here to match the checkbox + label options spacing?

2020-09-29 20:32 UTC, WilkinsKa1 commented on packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
> +        label={''}
We need a label here, can add a `hideLabel` prop to visually hide it. Could also add an aria-describedby attribute and attach the helper text above, but that part is more of an enhancement than necessity.

2020-09-30 21:29 UTC, WilkinsKa1 approved these changes

2020-09-30 21:32 UTC, johnwcallahan approved these changes

2020-09-30 21:54 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
> +        noOptionsMessage={() => 'No VLANS available in the selected region.'}
Should probably be 'VLANs' to match the naming convention

2020-09-30 21:55 UTC, tiffwong approved these changes
Other than the one minor callout I had, everything looks good!

2020-09-30 22:06 UTC, DevDW approved these changes
I was trying to think of a way to visually balance things in the Add-ons section given the lack of a checkbox to the left of "Virtual LAN," but I'm not sure there's anything that makes sense. The only thing I thought of was the icon that's used on the VLAN Landing page (sized down to match the checkboxes), but that might be too out-of-place there.

2020-10-01 13:50 UTC, merged