M3-4544: VLAN Panel in Linode Networking tab
linode/manager pull request #6950
Opened 2020-09-29 23:07 UTC by DevDW

## Description
Adds the VLAN panel to the Linode Networking tab

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Cleanup of unnecessary files/imports
- [ ] Match list of Linodes to format of designs

## Note to Reviewers
The "Attach a VLAN" button functionality will be added in a separate PR, and possibly the clickable label link and Details button as well.

2020-09-30 18:22 UTC, Jskobos reviewed
Working well so far, let me know when it's ready for final review. Left some stuff in the meantime.

2020-09-30 18:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +    error
you're making separate requests to two endpoints in this component (or 3, I guess), you have to account for multiple errors. Specifically, pass `vlans.error.read` here as well as `request.error`; to see why, block requests to /vlans and load this page.

2020-09-30 18:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  withSnackbar
you can use the hook version inside a function component

2020-09-30 18:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +const connected = connect(undefined, mapDispatchToProps);
you're not going to end up using this I think

2020-09-30 18:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  linodeContext,
you can get rid of the `compose` by passing the context props (configs, linodeId, and readOnly) as normal props from the parent, which is already using linodeContext. This is optional

2020-09-30 18:22 UTC, Jskobos commented on packages/manager/src/store/index.ts
> +  vlans: VlanState;
See my comment in Kayla's PR. We have to pick a place for vlans in the store, this results in them being in two places.

2020-09-30 21:41 UTC, DevDW commented
Going ahead and removing the WIP label here to open it up. 2 To-Do's remain; not sure how to get the Linodes list matching the designs since they need to be clickable links (unless the pattern used for `getDeviceLinks` in `FirewallRow_CMR.tsx` is a sufficient model -- the designs have "plus 2 more" as being clickable), and the `return undefined` part in `vlanData` in `LinodeVLANs.tsx` is a temporary placeholder

I'll have an additional follow-up PR cleaning up props and utilizing hooks where possible

2020-10-01 19:28 UTC, Jskobos requested changes
The major success/error paths are all working well now, we're down to smaller fixes. Still a few things that need to be taken care of before this can be merged.

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +    dataColumn: 'label',
Sorting is broken here, as discussed in demo prep the actual field on the vlan is "description"

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +    dataColumn: 'address',
this needs to match exactly the field on the object you're passing to the row component.

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +    dataColumn: 'linodes',
this is called `interfaceName` in your data model, so this sort isn't working either

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanActionMenu.tsx
> +      href: `networking/vlans/${vlanID}`
these need to be absolute paths (start with a `/`). Clicking this takes me to `http://localhost:3000/linodes/13873972/networking/vlans/networking/vlans/16000056`

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanActionMenu.tsx
> +  const createActions = () => (): Action[] => {
This is a pattern I've been fighting against. There's no need for two action arrays. Change `actionText` to `title` and use the same array for both versions of the menu.

2020-10-01 19:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +    if (data.length === 0) {
this is worth leaving as a safety check, but will never be true in this case (since by definition this VLAN is being displayed because it's attached to the Linode being viewed)

2020-10-01 20:59 UTC, Jskobos approved these changes
Thanks for all the fixes. This is ready to go, though you still have to resolve the expected merge conflicts in the hook

2020-10-01 21:55 UTC, johnwcallahan requested changes
One thing that needs to be addressed is the same thing I've got to do in my PR, which is that this has to be conditional so that people without access to VLANs don't see the VLAN table at all (instead of an error).

Also required: if you've got a VLAN attached to two Linodes and remove it from only one (from the network tab), the VLAN isn't removed from the table unless you refresh the page. Probably need to re-request VLANs after removing them as well.

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  const { loading, lastUpdated } = request;
Purely stylistic and option: since you're destructuring `request` here, you might as well grab `data` as well since you use it below.

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +              ...vlans.itemsById[thisInterface.vlan_id],
Subtle,  optional thing: it's more readable if you spread `thisVlan`, since you've: 

1. Declared a variable (L114)
2. Made sure it isn't undefined (L116)
3. But then you reference the value which you previously declared as a variable, instead of the variable itself. (L118)

It would better tell the story of what this code is doing if you did `...thisVlan` on L118.

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  };
This is strange. Why don't you just move the body of the `openModal` function to L145, and get rid of the `openModal` function altogether? 

```ts
  const handleOpenRemoveVlanModal = (id: number, label: string) => {
    setSelectedVlanID(id);
    setSelectedVlanLabel(label);
    toggleModal(true);
  };
```

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/RemoveVlanDialog.tsx
> +    const defaultError = 'There was an issue deleting this Virtual LAN.';
I think "There was an issue removing this Virtual LAN." is more accurate.

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +            {(idx !== firstFour.length - 1 && data.length < 4 && `, `) ||
As a followup, please see UserSSHKeyPanel.tsx and use the utility function there: https://github.com/linode/manager/blob/639cf211f0f29581a59ebefe477c73fbed01060e/packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx#L158

You'll have to convert the list of linodeIDs to a list of strings first, but that's easy with a simple map:

```ts
const linodeLabels = data.map(thisID => getLinodeLabel(thisID));
```

2020-10-01 21:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +            {(idx !== firstFour.length - 1 && data.length < 4 && `, `) ||
Also (in this PR or a followup) let's make these labels inline and with a much higher max (like 50).

2020-10-02 14:00 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +              ...vlans.itemsById[thisInterface.vlan_id],
Thanks for the reminder here, forgot the clean that up after I refactored the function

2020-10-05 15:43 UTC, WilkinsKa1 requested changes
Nice work on this, looks good. The links for the vlan details page have /networking as part of the link, which is throwing a 'Not Found' page. I think if you remove you should be g2g 👍

2020-10-05 15:43 UTC, WilkinsKa1 commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanActionMenu.tsx
> +          pathname: `/networking/vlans/${vlanID}`
need to remove networking here

2020-10-05 15:43 UTC, WilkinsKa1 commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +              <Link to={`/networking/vlans/${id}`}>{vlanLabel} </Link>
Need to remove networking here as well

2020-10-05 16:02 UTC, WilkinsKa1 approved these changes

2020-10-05 16:22 UTC, johnwcallahan approved these changes

2020-10-05 16:24 UTC, merged