[CMR] M3-4568: (Mostly) Linode Landing Refinements
linode/manager pull request #6958
Opened 2020-10-02 14:15 UTC by tiffwong

## Description
Fixes include:
- [x] Update toggle view icon depending on what state it's in (list vs table)
- [x] Only showing the copy icon for the IP Address when hovering over the table row
- [ ] Implement table setting icons tooltips (Summary View/Table View, Group by Tag)
- [x] Update font sizes in the EntityHeader, font color, and margins for tabs on linodes detail view

## Type of Change
- Non breaking change ('update', 'change')

2020-10-02 19:22 UTC, johnwcallahan requested changes
Thanks for these fixes.

MUI doesn't seem to be happy about these tooltips:
<img width="656" alt="Screen Shot 2020-10-02 at 3 19 57 PM" src="https://user-images.githubusercontent.com/16911484/94961614-faa1b400-04c2-11eb-9918-fff6d6bb9604.png">

2020-10-02 19:22 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
> +      minWidth: 135
I'm still seeing the cell changing sizes on hover when browsing my account with real IP addresses.

2020-10-02 19:22 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
> +  const [showCopy, setShowCopy] = React.useState<boolean>(false);
Could we find a way to show/hide the icon with CSS rather than JavaScript? Currently this results in _a lot_ of re-renders. (use an account with a lot of Linodes, enable "highlight on update" in React dev tools and move the mouse around the table).

Maybe we could control the opacity of the icon with the `:hover` selector on each row.

2020-10-05 14:49 UTC, WilkinsKa1 requested changes
Great work on these refinements! One comment in re tabs, and also noticed this: 
<img width="461" alt="Screen Shot 2020-10-05 at 10 41 44 AM" src="https://user-images.githubusercontent.com/2565527/95094352-cd8a1700-06f7-11eb-9ac3-c66746a8e0ab.png">
We need to reduce the spacing from the search bar area and the entity header to 20px.

2020-10-05 14:49 UTC, WilkinsKa1 commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation_CMR.tsx
> +    '& [data-reach-tab]': {
Let's apply these to the tab components instead so they're consistent throughout the app.

2020-10-06 12:29 UTC, johnwcallahan approved these changes
LGTM, thanks for the CSS fix.

2020-10-06 18:43 UTC, WilkinsKa1 approved these changes
Thanks for updating, changes look good 👍

2020-10-06 20:03 UTC, merged