M3-4544: VLAN Panel in Linode Networking tab, Pt. 2
linode/manager pull request #6968
Opened 2020-10-05 21:42 UTC by DevDW

## Description
The first follow-up to https://github.com/linode/manager/pull/6950. This PR addresses the `readOnly` prop to disable the Remove VLAN button and formatting for the Linodes list. I'll keep this PR small and address the other items in a separate ticket.

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
Coming in follow-up PRs:
- [ ]  "Attach a VLAN" button functionality
- [ ] Fix: when user clicks on a listed Linode, the VLAN panel should update to reflect the VLANs on that Linode

2020-10-05 21:46 UTC, DevDW commented on packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
> +                          readOnly={readOnly}
I did a brief run-through of other places in the app to see if this caused anything to break or generated console errors. What I checked seemed okay, but we will want to have all the CMR Row components that are connected to this accept and use the `readOnly` prop. That ties into M3-4575

2020-10-05 21:48 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +              (data.length > MAX_LINODES_VLANATTACHED_DISPLAY && `, `)}
Had some difficulty removing the comma from being part of the link

2020-10-07 14:03 UTC, johnwcallahan requested changes

2020-10-07 14:03 UTC, johnwcallahan commented on packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
> +  currentLinode?: number;
Remember, this is a generic component used for different types of entities. A prop called `currentLinode` doesn't belong here, since it's irrelevant in every case this component is used except for one (Linode VLANs).

One solution would be to add the LinodeID to the `vlanData` mapping in LinodeVlans.tsx (it's available on the LinodeInterface object).

I'd say the same thing for the `readOnly` property: better to let row components take care of it.

Related: the mapped vlanData in LinodeVlans.tsx data should get its own interface (`ExtendedVLAN` or something) since we've added fields to it that the row component doesn't know about.

2020-10-08 14:50 UTC, WilkinsKa1 approved these changes
Looks good, nice work with the current Linode list handling logic!

2020-10-08 18:42 UTC, johnwcallahan requested changes

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.test.tsx
> +describe('truncateAndJoinJSXList utility function', () => {
This function doesn't quite work in all cases, including the test case here. As an example, I have four Linodes attached to this VLAN, and I changed the max to 2:
![Screen Shot 2020-10-08 at 2 24 10 PM](https://user-images.githubusercontent.com/16911484/95499089-c3c01800-0972-11eb-9814-e8796a0c8a91.png)

Examining the result of L15, you can see that something similar happens with the test case here. You definitely want to check the corner cases with a function like this: `length == max-1`, `length == max`, `length == max+1`, etc.

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.test.tsx
> +      <Link key={item} to={`/test`}>
No need to use a `<Link />` which complicates the test, you can just do a one-level span, something like `<span key={item}>{item}</span>;`

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.test.tsx
> +    expect(truncatedList.props.children[1].props['children']).toEqual(
Nice job figuring out how to introspect these React elements;.

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +  readOnly: boolean;
This prop is actually coming from the `VlanData`, right? L19 should be `Props & VlanData & ActionHandlers` I think. You'll have circular imports though, so you need to declare the VlanData interface somewhere else.

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  currentLinode: number;
I'd recommend calling this `currentLinodeID`... this name implies it's of type `Linode`.

2020-10-08 18:42 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +          {(idx !== count - 1 && count <= max && `, `) || (count > max && `, `)}
I'd strongly recommend against this type of one-liner here; multi-line, more verbose logic is more readable in a situation like this. One thing that would make it cleaner is if you sliced the list ahead of time.

2020-10-09 12:08 UTC, johnwcallahan approved these changes
LGTM, assuming the splice issue will be addressed in the next PR. Nice job.

2020-10-09 12:08 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.test.tsx
> +  it('should have truncated text that reads " plus [X] more" if the max is 5', () => {
More precisely, "... if the max is less than the length of the list".

2020-10-09 12:08 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +  }
Great job with this. IMO it's worth the extra lines of code and a little duplication... so much more readable.

2020-10-09 14:44 UTC, merged