[VLAN] M3-4548: VLAN Details Header
linode/manager pull request #6971
Opened 2020-10-06 18:52 UTC by tiffwong

## Description

Please start the pull request title with the jira ticket corresponding to the work if applicable. Please include a short summary of the feature added, the change, or issue fixed.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')
- Non breaking change ('update', 'change')
- Breaking change ('break', 'deprecate')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

2020-10-15 13:18 UTC, johnwcallahan requested changes
Placement etc. is looking good. Note that `created` is available from the dev API, so you can go ahead and add that.

You'll need to rebase this with develop to square away the stuff in VlanDetail.tsx.

2020-10-15 13:18 UTC, johnwcallahan commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +  const [selectedVlanID, setSelectedVlanID] = React.useState<
We already have an `id` and a `label` given as props,  and there's no way to "select" any other VLAN from this view. So you can remove these useState bits and rely on the id and label from L113.

2020-10-15 17:23 UTC, tiffwong commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +    history.push({
If it doesn't redirect, it'll show an error since the VLAN won't exist anymore after deleting it. Should I move the redirect outside of that function instead?

2020-10-15 18:30 UTC, tiffwong commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +    history.push({
Nvm ignore this lol

2020-10-19 13:31 UTC, Jskobos requested changes
Looking good, still some cleanup to do and a few small changes.

2020-10-19 13:31 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanLanding/VlanDialog.tsx
> +    if (redirectToLanding) {
This is happening unconditionally (wrt the result of the submission function), so errors aren't displayed and the button loading state doesn't happen because as soon as the user hits Delete they get redirected.

2020-10-19 13:31 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanLanding/VlanDialog.tsx
> +import { useHistory } from 'react-router-dom';
This component takes deleteVlan as a prop, which isn't really necessary. You can remove it and use the `useVlans` hook inside the dialog to get at the deletion method (you'll have to add deleteVlan to the hook, but we should have done that anyway.)

2020-10-19 13:31 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +          {regionDisplay && (
This shouldn't be a button, since on this view clicking the region doesn't open the migrate modal.

2020-10-19 16:44 UTC, Jskobos commented on packages/manager/src/hooks/useVlans.ts
> +  deleteVlan: (vlanID: number) => Promise<VLAN>;
delete methods return `{}`, not an entity

2020-10-19 16:44 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +        deleteVlan={deleteVlan}
Can be removed

2020-10-19 16:44 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +          {regionDisplay && (
it's no longer a button, but it's blue, which makes me think maybe I should click on it

2020-10-19 16:44 UTC, Jskobos commented on packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
> +        deleteVlan={deleteVlan}
(and there's probably one being passed down through vlan landing which can be removed as well)

2020-10-20 12:30 UTC, johnwcallahan commented on packages/manager/src/features/Vlans/VlanLanding/VlanDialog.tsx
> +import { useHistory } from 'react-router-dom';
@tiffwong now that you've made this change, you don't need to wrap VlanEntityDetail in `withVlans`, and you don't need to pass down `deleteVlan` to the Header component.

2020-10-20 14:32 UTC, Jskobos approved these changes

2020-10-20 14:37 UTC, johnwcallahan approved these changes

2020-10-20 15:19 UTC, merged