initial access keys test with some buckets and keys helpers
linode/manager pull request #6980
Opened 2020-10-08 22:34 UTC by ndukatz

**How to verify that that the test works:**
- yarn up
- yarn cy:debug
- access-keys.spec.ts
- Test should pass

**Extra check (runs headless):**
- yarn cy:e2e -s ./cypress/integration/objectStorage/access-keys.spec.ts
- Result should be "✔  All specs passed!"

Make sure your .env contains:
REACT_APP_LOGIN_ROOT='https://login.linode.com'
REACT_APP_API_ROOT='https://api.linode.com/v4'
REACT_APP_APP_ROOT='http://localhost:3000'
REACT_APP_LAUNCH_DARKLY_ID='*************************' (CMR flag)
REACT_APP_CLIENT_ID='********************' (https://cloud.linode.com/profile/clients, copy ID)
MANAGER_OAUTH='**************************************************************************' 
(create in https://cloud.linode.com/profile/tokens > "Add a Person Access Token", Save the token that appears in the modal, you will only see it once)

2020-10-09 12:59 UTC, johnwcallahan requested changes
Great work; just one blocking comment about randomly generated bucket names.

2020-10-09 12:59 UTC, johnwcallahan commented on packages/manager/cypress/support/api/objectStorage.ts
> +const makeBucketCreateReq = (label, cluster, bucket) => {
Could add types to these arguments.

2020-10-09 12:59 UTC, johnwcallahan commented on packages/manager/cypress/support/api/objectStorage.ts
> +  const bucketData = bucket
Minor syntax this: you should be able to do:

```ts
const bucketData = bucket ?? {
  cluster,
  label
};
```

if you prefer.

2020-10-09 12:59 UTC, johnwcallahan commented on packages/manager/cypress/support/api/objectStorage.ts
> +    url: Cypress.env('REACT_APP_API_ROOT') + '/object-storage/buckets',
Since this pattern is used in a lot of places, you could simplify and make it a function, so that you could just do something like: `url: apiRoute('/object-storage/buckets')`.

2020-10-09 12:59 UTC, johnwcallahan commented on packages/manager/cypress/integration/objectStorage/access-keys.spec.ts
> +    const bucketLabel = 'cy-test-bucket';
This will need to have a randomly generated component, since bucket names are required to be unique per _cluster_ (not per customer).

Maybe something like `'cy-test-' + randomTitle()` so it'll still be considered a test entity.

2020-10-09 12:59 UTC, johnwcallahan commented on packages/manager/cypress/integration/objectStorage/access-keys.spec.ts
> +    createBucket(bucketLabel, clusterId).then(() => {
Strictly speaking you shouldn't _need_ to create a bucket here.

2020-10-14 21:36 UTC, tiffwong reviewed
I had one failed test:
<img width="392" alt="Screen Shot 2020-10-14 at 5 35 46 PM" src="https://user-images.githubusercontent.com/7692354/96047870-be1b7400-0e43-11eb-8ab9-99b66cb36644.png">

2020-10-26 14:18 UTC, tiffwong reviewed
I'm getting this message when I run the test
<img width="457" alt="Screen Shot 2020-10-26 at 10 18 07 AM" src="https://user-images.githubusercontent.com/7692354/97183821-98ac3580-1774-11eb-99ef-75a88386cfbe.png">
<img width="462" alt="Screen Shot 2020-10-26 at 10 18 13 AM" src="https://user-images.githubusercontent.com/7692354/97183822-9944cc00-1774-11eb-9133-8508e9ec7772.png">

2020-10-26 20:18 UTC, tiffwong approved these changes
The access key test passed 👍

2020-10-27 15:04 UTC, johnwcallahan approved these changes

2020-11-05 07:03 UTC, merged