M3-4544: VLAN Panel in Linode Networking tab, Pt. 3
linode/manager pull request #6981
Opened 2020-10-09 15:09 UTC by DevDW

## Description
Follows up https://github.com/linode/manager/pull/6950 and https://github.com/linode/manager/pull/6968 to wrap up the VLAN Panel on the Linode Network tab.

## Type of Change
- Non breaking change ('update', 'change')

## To-Do
- [ ] "Attach a VLAN..." button functionality

2020-10-12 13:43 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +          const thisVlanClone = clone(thisVlan);
What was happening here that caused mutation? Usually the spread operator is enough to create a copy of the object, unless it's deeply nested.

2020-10-13 20:01 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +          const thisVlanClone = clone(thisVlan);
IIRC we added this here just as another level of safety; some splicing logic from an earlier version of the code in `VLanTableRow.tsx` was causing some unwanted modification

2020-10-13 20:22 UTC, Jskobos requested changes
Attachment flow is working well. A few UX quirks:

1. After attaching, despite the requests you're making to update things the linodes column is blank until you reload the page: 
![Screen Shot 2020-10-13 at 4 07 32 PM](https://user-images.githubusercontent.com/1624067/95911609-b2f71400-0d6f-11eb-8516-17c2e9ee870b.png)

2. You need to filter VLANs by region (see inline comment)

3. A comma is getting put after a single-item list:
![Screen Shot 2020-10-13 at 4 07 44 PM](https://user-images.githubusercontent.com/1624067/95911682-cb672e80-0d6f-11eb-8199-fce65d841361.png)

4. Not sure what's happening here, this VLAN has 3 Linodes attached to it:
![Screen Shot 2020-10-13 at 4 21 15 PM](https://user-images.githubusercontent.com/1624067/95911986-331d7980-0d70-11eb-919e-156916575570.png)

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/AttachVlanDrawer.tsx
> +  vlansValues.forEach(vlanValue => {
Could clean this up with a `map`, something like:

```
Object.values(vlans).map(thisVlan => ({ value: thisVlan.id, label: thisVlan.description }))
```

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/AttachVlanDrawer.tsx
> +  onClose: () => void;
onClose and closeDrawer are the same function (technically one is a wrapper around the other but they behave identically). There's no need to have separate props for them.

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +          const thisVlanClone = clone(thisVlan);
Going to re-up this. Why is this necessary?

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +        resetInterfaces={requestInterfaces}
it's requesting them, so maybe this prop would be better named requestInterfaces or refreshInterfaces. Reset is a bit confusing.

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  vlanData.forEach((vlanDatum: { id: string | number }) => {
what you're doing is filtering, so it would be terser and more semantic/readable to use `.filter()`.

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/AttachVlanDrawer.tsx
> +  const vlansValues: VlanData[] = Object.values(vlans);
You also need to filter this list by region. Only VLANs in the current Linode's region should appear as options, since attaching from a different region results in an error.

![Screen Shot 2020-10-13 at 4 07 01 PM](https://user-images.githubusercontent.com/1624067/95911453-83480c00-0d6f-11eb-80ff-ecc629d7a35d.png)

2020-10-13 20:22 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
> +        <LinodeVLANs key={this.props.linode.id} />
Why was this necessary? If the linode id ever changes, all of the parents should re-render.

2020-10-13 20:31 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +          const thisVlanClone = clone(thisVlan);
I don't think you need this anymore. Originally it fixed a bug when the inner `linodes` array was being sliced: https://github.com/linode/manager/pull/6981/files#diff-8329ade4ac67ff5d400da441d8862e8a1091fb517ae801f300edd7658b224614L59

Since the spread operator only copies objects shallowly, the splice was causing an unwanted mutation to the Redux store.

The filter is a better solution there, though.

2020-10-14 21:21 UTC, tiffwong approved these changes
Other than the label being sorted by default, everything else looks good
<img width="614" alt="Screen Shot 2020-10-14 at 4 59 51 PM" src="https://user-images.githubusercontent.com/7692354/96044609-b0172480-0e3e-11eb-99ce-6a33269943a1.png">

2020-10-14 21:52 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
> +        <LinodeVLANs key={this.props.linode.id} />
When I remove this during testing, I observe some wildly inaccurate contents for the VLAN panel when clicking different linode links

2020-10-14 22:01 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  vlanData.forEach((vlanDatum: { id: string | number }) => {
I added some logic to exclude VLANs not in the same region as the linode in this function in [my latest commit](https://github.com/linode/manager/pull/6981/commits/a6c751f19223e6c9ac2d05523071154d2d8c4662) (instead of putting the logic in `AttachVlanDrawer.tsx`). I haven't been able to add a linode in regions outside us-east in my dev account to test though, so I didn't get a chance to confirm it works quite yet.

I also tried a few different refactors with `.filter()` but didn't arrive at something that works yet. I'll experiment some more with refactoring it.

2020-10-15 12:18 UTC, Jskobos approved these changes
Looking good now, nice work. I left some typescript clean up and a small fix that probably won't matter once the Redux stuff is done:

Line 219 is being called every time an attachment is complete, because you're re-requesting interfaces, which sets the loading state. Using Redux thunks for this instead is likely to resolve the problem on its own, but in the meantime might as well rework it so that setInterfaceDataLoading only happens in the initial load (in the useEffect).

2020-10-15 12:18 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  const vlanItems = Object.values(clone(vlans.itemsById));
You're not mutating anything anymore so the clone isn't necessary.

2020-10-15 12:18 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  vlans: any,
Need to get rid of these `any`s. The types are all in the file already so it should be easy (vlans is `Record<string, VLAN>` and vlanData is `VlanData[]`.)

2020-10-15 12:20 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +};
yes, this is the ticket

2020-10-15 19:53 UTC, merged