M3-4590: Store Linode Interfaces in Redux
linode/manager pull request #6985
Opened 2020-10-09 23:46 UTC by DevDW

## Description
Add actions, reducer, etc. for Linode Interfaces to enable data to be shared across the Linode Network and Configurations tabs easily.

## Type of Change
- Non breaking change ('update', 'change')

2020-10-16 12:52 UTC, johnwcallahan reviewed
The Redux boilerplate is looking good. Please pull in the latest changes from develop, since that sneaky splice bug is present here.

Also, the main goal of getting interfaces into Redux is so that multiple components have access to them without having to request them individual. You'll probably want to move the request to a higher level, maybe LinodesDetail.container (where configs and disks requests are made): https://github.com/linode/manager/blob/021d7c47398cb442253e51359fa9d04bdad6201b/packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx#L55

2020-10-16 12:52 UTC, johnwcallahan commented on packages/manager/src/store/linodes/interfaces/interfaces.reducer.ts
> +    // deleteLinode (sync – used to respond to events)
You can remove these two cases.

2020-10-19 13:59 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +      Object.values(interfacesList ?? {})
`interfacesList` is an array, so no need to use Object.values here.

2020-10-19 13:59 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  const thisLinodeInterfaces = reduxInterfacesObject[linodeId];
Won't this be the same as `interfacesList` which you've gotten from context? I'd argue you don't need both; probably better to stick with this one since you need access to `loading`, `error`, etc.

2020-10-20 16:11 UTC, Jskobos requested changes
Getting closer, have to refactor a thing that's using a useEffect + useState unnecessarily.

2020-10-20 16:11 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  const [interfacesList, setInterfacesList] = React.useState<LinodeInterface[]>(
What is the purpose of storing this in a state variable?

2020-10-20 16:11 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
> +  React.useEffect(() => {
If I understand this correctly, the goal here is to store a list of interfaces as a variable. Looks like you're jumping through a few unnecessary hoops. You can replace `thisLinodeInterfaces` on line 125 with `Object.values(thisLinodeInterfaces.itemsById)`, or do a separate, normal, inline variable declaration, e.g. `const interfaceItems = Object.values(this.LinodeInterfaces.itemsById)`.

2020-10-20 16:56 UTC, DevDW commented
> Getting closer, have to refactor a thing that's using a useEffect + useState unnecessarily.

I attempted it without those earlier and tried again now (commented them out and did the inline variable declaration):

<img width="546" alt="Screen Shot 2020-10-20 at 12 25 32 PM" src="https://user-images.githubusercontent.com/32860776/96616113-2c42b980-12d0-11eb-9964-195251dec33e.png">

It results in an app crash, saying that `thisLinodeInterfaces` is undefined: https://www.loom.com/share/69c28ee0c384454e97c364ea5d883b77

I think this refactor solves the problem though:
https://github.com/linode/manager/blob/98715826d94705d03dc91877916cb845a677ab63/packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx#L108

2020-10-20 19:58 UTC, Jskobos approved these changes
Looks good now. Please pull in develop before you merge this and make sure that the comma splice bug is solved in the version you're about to merge.

2020-10-20 19:59 UTC, Jskobos commented
> I think this refactor solves the problem though:
> 

Yes, that's correct. The reason the useState way worked for you is that `React.useState([])` sets up the state variable with a default.

2020-10-22 20:51 UTC, johnwcallahan requested changes
Getting very close, but this doesn't work for customer's without VLANs enabled, since they cannot use the `interfaces` and `vlans` endpoints. ~In this case, the Network tab goes into an infinite loop of `/vlans` requests.~

Edit: these are two separate issues; I'm going to address the infinite loop in a different PR since we have this problem in other places too.

LinodeDetails.container.tsx should still make sure that the feature is enabled before requesting interfaces, though.

2020-10-26 13:03 UTC, johnwcallahan approved these changes
Nice work, all things Redux are working well.

On a separate note, I noticed some comma weirdness in the Linode List (Networking tab); we should address this in a separate PR:
![Screen Shot 2020-10-26 at 9 00 03 AM](https://user-images.githubusercontent.com/16911484/97175474-f424f600-1769-11eb-9642-07c2e092905c.png)




![Screen Shot 2020-10-26 at 9 00 03 AM](https://user-images.githubusercontent.com/16911484/97175362-c8097500-1769-11eb-9b72-35d420ec5341.png)

2020-10-26 21:13 UTC, merged