M3 4556 domain text wrap
linode/manager pull request #6988
Opened 2020-10-12 17:35 UTC by Jskobos

## Description

I had TXT records set to truncate at 255 characters, but a few users had records close to that count that were still breaking the display. I added truncation to every other field I could find where it was possible to break the display; if you can find others please let me know.

## Note to Reviewers

Make very long TXT, CAA, and SOA records. Have fun!

![Screen Shot 2020-10-12 at 1 34 52 PM](https://user-images.githubusercontent.com/1624067/95775094-b9ae5a00-0c8f-11eb-9bc0-e9145a3529ba.png)

2020-10-13 13:17 UTC, johnwcallahan requested changes
This is probably not realistic, but might as well address MX records too:

<img width="1305" alt="Screen Shot 2020-10-13 at 9 16 07 AM" src="https://user-images.githubusercontent.com/16911484/95865511-c769eb00-0d34-11eb-9299-3af36c192a56.png">

More importantly, I'm easily able to break TXT record display with a medium-ish hostname:

<img width="1307" alt="Screen Shot 2020-10-13 at 9 14 22 AM" src="https://user-images.githubusercontent.com/16911484/95865401-a5706880-0d34-11eb-865e-d1d6a0425c2a.png">

We should probably explicitly set the widths of these columns so we can precisely set the truncation points.

2020-10-14 15:42 UTC, tiffwong reviewed
I agree with @WilkinsKa1's suggestion, CSS might be the easiest way to handle this responsively

2020-10-15 11:44 UTC, johnwcallahan reviewed
Seems like we could get away with a larger maxWidth on higher breakpoints, still a lot of horizontal space:
<img width="1311" alt="Screen Shot 2020-10-15 at 7 43 29 AM" src="https://user-images.githubusercontent.com/16911484/96118896-2c9b1900-0eba-11eb-9895-6d4fcbd3efdf.png">

2020-10-16 16:05 UTC, WilkinsKa1 approved these changes
Looks good- left some optional feedback items, one for cleanup and one that could address the white space callout.

2020-10-16 16:05 UTC, WilkinsKa1 commented on packages/manager/src/features/Domains/DomainRecords.tsx
>          wordBreak: 'break-all'
I think we can remove this line

2020-10-16 16:05 UTC, WilkinsKa1 commented on packages/manager/src/features/Domains/DomainRecords.tsx
> +        maxWidth: 300,
This is optional, but if we want to expand the amount of text displayed based on screensize, could add a breakpoint to increase this size for only large screens.

2020-10-19 17:22 UTC, johnwcallahan approved these changes
Any reason why `types.json` is updated here?

2020-10-19 17:47 UTC, merged