CMR AbuseTicketBanner
linode/manager pull request #6989
Opened 2020-10-12 20:05 UTC by WilkinsKa1

## Description

CMR version of this banner- really I added some logic to ensure this is not dismissible for CMR, most of the adjustments for this are in Notice.tsx. Please test both versions of the app, in DT mode, etc. I included a mock abuse ticket to make this easier to test, of course will remove pre-merge.

## Type of Change
- Non breaking change ('update', 'change')

2020-10-13 13:59 UTC, johnwcallahan requested changes
Placement of the notification looks good. One thing: it shouldn't be dismissible in CMR _or_ Production (I included that note in the ticket since in the original _design_ it's dismissible).

2020-10-13 13:59 UTC, johnwcallahan commented on packages/manager/src/factories/abuseTicket.ts
> +export const abuseTicketFactory = Factory.Sync.makeFactory<Notification>({
Instead of adding a new factory here, you can extend the factory in `/factories/notification.ts` at the bottom of that file, changing only the fields you need, something like:

```ts
export const abuseTicketNotificationFactory = notificationFactory.extend({
  type: 'ticket_abuse',
  message: 'You have an open abuse ticket!',
  // etc.
})
```

2020-10-13 14:50 UTC, Jskobos approved these changes

2020-10-13 15:16 UTC, tiffwong approved these changes

2020-10-15 11:49 UTC, johnwcallahan approved these changes

2020-10-15 17:51 UTC, merged