Group kernels in dropdown when selecting in Config drawer
linode/manager pull request #7015
Opened 2020-10-16 21:44 UTC by Jskobos

## Description

Please start the pull request title with the jira ticket corresponding to the work if applicable. Please include a short summary of the feature added, the change, or issue fixed.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')
- Non breaking change ('update', 'change')
- Breaking change ('break', 'deprecate')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

2020-10-19 16:52 UTC, Jskobos commented on packages/manager/src/cachedData/types.json
> +{"data":[{"id":"g6-nanode-1","label":"Nanode 1GB","price":{"hourly":0.0075,"monthly":5},"addons":{"backups":{"price":{"hourly":0.003,"monthly":2}}},"memory":1024,"disk":25600,"transfer":1000,"vcpus":
I ran `yarn build` to cache the kernels, this got updated as a side effect

2020-10-19 17:41 UTC, tiffwong approved these changes
Looks good!

2020-10-19 23:25 UTC, DevDW approved these changes

2020-10-19 23:25 UTC, DevDW commented on packages/api-v4/src/linodes/types.ts
> +  deprecated: boolean;
The screenshot says "depreciated," but I agree that it should be "deprecated"

2020-10-20 13:00 UTC, johnwcallahan requested changes
Great work with the sorting and grouping: clean and readable as always. Left one comment about a failure scenario.

2020-10-20 13:32 UTC, johnwcallahan approved these changes

2020-10-20 16:07 UTC, merged