M3-4603: DBaaS Create Modal
linode/manager pull request #7026
Opened 2020-10-19 21:57 UTC by DevDW

## Description
Add DBaaS Create modal

- Add 'Dbaas' to `AccountCapability` type
- Create DBaaS context & DBaaS Create modal; add modal/dialog to `MainContent_CMR.tsx`; add item in `AddNewMenu_CMR.tsx`
- Refactor `AddNewMenu_CMR.tsx` to accomodate multiple contexts

## Type of Change
- Non breaking change ('update', 'change')

2020-10-23 20:44 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
> +        `W${evenizeNumber(start.setZone('utc').hour)}`
The changes in this file and `LinodeBackup_CMR.tsx` were only made because I put the `evenize` logic into its own utility file to avoid repeating the logic in three different places

2020-10-26 16:39 UTC, DevDW commented on packages/manager/src/store/databases/databases.reducer.ts
> +
Added this in the `.reducer.ts` file based on precedent below, but happy to move this elsewhere if advised

https://github.com/linode/manager/blob/5e5cdbfa17f25a3670323cf8651df42c0dbac523/packages/manager/src/store/linodeType/linodeType.reducer.ts#L89

2020-10-26 16:43 UTC, DevDW commented
Going ahead and removing the WIP label. Some remaining issues:

1. Some complaints from TypeScript, mostly re: tags in `CreateDbaasDialog.tsx`
2. Tags not being added due to type mismatching
3. Maintenance Window fields should be on the same line

2020-10-26 20:16 UTC, johnwcallahan reviewed
Nice job; this is really coming together.

Haven't gotten to everything yet; thought I'd go ahead and leave the comments I've made so far.

2020-10-26 20:16 UTC, johnwcallahan commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +  const initWindows = (timezone: string) => {
There's a great opportunity here for a bit of refactoring: take the `initWindows` function from `LinodeBackup.tsx` and put it in a utility file, that way you can use it from both places. Even better, you could add a few unit tests.

2020-10-26 20:16 UTC, johnwcallahan commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +  const handleWindowSelection = (e: Item) => {
Minor: Usually `e` is an abbreviation for an HTML event (though we use it incorrectly in parts of our codebase). I'd use `item` or something else more descriptive.

2020-10-26 20:16 UTC, johnwcallahan commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +  React.useEffect(() => {
`useReduxLoad` is doing the work for you... no need to request the types manually here. (It also results in a double request).

2020-10-26 20:16 UTC, johnwcallahan commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +      tags: [''],
Remove the empty string here. That'll get rid of the TS error, though `tags` will be incorrectly typed as `never[]`. 

You might end up having to type useFormik with a custom type:

`useFormik<CreateDbaasForm>({ // ... })`

2020-10-26 21:05 UTC, Jskobos requested changes
This is very close, good work--the select plan panel in particular is working very well.

2020-10-26 21:05 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/SelectDBPlanPanel.tsx
> +    return [tabs, tabOrder];
This is unused

2020-10-26 21:05 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/SelectDBPlanPanel.tsx
> +    'Standard Availabilty allocates a single node to your database cluster. High Availability allocates 3 nodes for increased reliability and fault tolerance and has no downtime during maintenance.';
availability

2020-10-26 21:05 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/SelectDBPlanPanel.tsx
> +    <Table_CMR spacingBottom={16} aria-label="List of Database Plans">
This is throwing a DOM nesting error in the console (div can't be a child of table). Maybe this is happening elsewhere too, since this is a reused pattern.

2020-10-26 21:05 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +            <Select
This is giving me weird stuff, probably because my timezone is an empty string:
![Screen Shot 2020-10-26 at 5 03 17 PM](https://user-images.githubusercontent.com/1624067/97228477-5fdc8280-17ad-11eb-9f2e-87141c803ec5.png)

I think following John's advice about the useTimezone hook will fix this.

2020-10-27 20:52 UTC, tiffwong approved these changes
Not sure if this is how it's supposed to work but I can't create a database without adding a tag, otherwise everything else looks good!

2020-10-28 14:52 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +    if (!payload.maintenance_schedule) {
You've removed this in your recent commits, but it's necessary. You just have to fix it so that it clears the entire `maintenance_schedule` object:

```
    if (
      !payload.maintenance_schedule?.day &&
      !payload.maintenance_schedule?.window
    ) {
      payload.maintenance_schedule = undefined;
    }
```

This allows you to submit the form with these fields blank without receiving an error. You might want to get a bit more precise than this; even with this added, if you select one field but not the other, the payload has an empty string, which gives an error message but not a helpful one ("maintenance_window must be one of W0 W2..." when we want "Window is required").

2020-10-28 14:54 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +    if (!payload.maintenance_schedule) {
Thinking out loud here:

```
if (!payload.maintenance_schedule?.day) { payload.maintenance._schedule.day = undefined }
if (!payload.maintenance_schedule?.window) { payload.maintenance._schedule.window = undefined }
if (isEmpty(payload.maintenance_schedule)) { payload.maintenance_schedule = undefined } 
```

2020-10-28 14:59 UTC, Jskobos reviewed
Thanks for the fixes, I found a few more things we can polish up:

- The DBPlanPanel probably ought to have a loading state, since it's populated pending an API request. Linode types are always available so this isn't necessary in the original SelectPlanPanel.

- This is probably the tallest of our full height modals, and when the error states are displayed there's room for some scrolling, which causes a visual bug:

https://www.loom.com/share/92257b32f028415fbbcf2a4f8ec49209

2020-10-28 14:59 UTC, Jskobos commented on packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
> +import { createDatabase } from '@linode/api-v4/lib/databases';
If you create a database successfully, you end up on the landing page as expected but the new database isn't listed. This is because we're populating that page from Redux and you're using a JS client method ^^^ directly. You need to use the createDatabase thunk rather than this method. The useDatabases hook already has this wired up for you.

2020-10-28 16:07 UTC, DevDW commented
> * This is probably the tallest of our full height modals, and when the error states are displayed there's room for some scrolling, which causes a visual bug:
> 
> https://www.loom.com/share/92257b32f028415fbbcf2a4f8ec49209

I think this is a general problem with our modals as I noticed it elsewhere too -- I opened ticket M3-4623 for it late last week

2020-10-28 16:47 UTC, WilkinsKa1 reviewed
Really nice work on this, looks/works great! Only one small UI comment:

The main heading of the dialog is fixed scroll- this is fine but we should add a background as we do in other modals so it doesn't overlap the content (related, we should add the bottom border to this heading that is present in the designs): <img width="952" alt="Screen Shot 2020-10-28 at 11 49 50 AM" src="https://user-images.githubusercontent.com/2565527/97468296-815b7c80-191b-11eb-8d05-19905ea28189.png">

2020-10-28 20:29 UTC, Jskobos commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +    if (!payload.maintenance_schedule) {
@DevDW

2020-10-28 22:54 UTC, DevDW commented on packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
> +      // The "(undefined as unknown) as..." code is to avoid "Type 'undefined' is not assignable to type..." TypeScript error
Not super thrilled about the TypeScript trickery and shenanigans here, but it's the only method that worked cleanly when I tried, and we do have precedents for `(...as unknown)` in the codebase

2020-10-28 22:56 UTC, DevDW commented on packages/manager/src/features/Dbaas/CreateDbaasDialog/CreateDbaasDialog.tsx
> +  const initWindows = (timezone: string) => {
Thanks, I'm going to take care of this refactor & the unit tests in a follow-up PR

2020-10-29 12:52 UTC, Jskobos approved these changes
OK, I think this is ready to go. We can look into cleaning up some of the TS in your follow up, but what you've got works fine.

2020-10-29 13:50 UTC, johnwcallahan approved these changes
Agree that we can clean up TS separately.

Two other things we should address:

zIndex issue with the header:
![Screen Shot 2020-10-29 at 9 49 21 AM](https://user-images.githubusercontent.com/16911484/97582487-2fbefa80-19cc-11eb-9c69-1f6acad4c904.png)

As well as the general performance of the form, which is pretty laggy when typing into fields. Should probably use some heavy memoization.

2020-10-29 13:50 UTC, johnwcallahan commented on packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
> +    }
Minor: this can be a more terse one-liner: `formik.setFieldValue('maintenance_schedule.day', item?.value);`

2020-10-29 13:50 UTC, johnwcallahan commented on packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
> +    }
Minor: (same note as above)

2020-10-29 13:58 UTC, merged