M3-4613 Add: dbaas landing and row
linode/manager pull request #7033
Opened 2020-10-22 18:58 UTC by Jskobos

## Description

Landing page for DbaaS. Thoughts:

1. The chips add a lot of boilerplate; I want to work out a way to abstract them so we don't have to go through all this for every landing page. BUT Chris has expressed that he doesn't like them, so I'm not in a hurry to put in that work until this is demoed.
2. Known bug: blocked requests to /databases/ will result in an infinite request loop. Separate PR will fix this (it also occurs on DB detail and VLANs).

## Note to Reviewers

Mocks are set up if you'd like to use them.

2020-10-22 21:04 UTC, tiffwong commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
>    // const classes = useStyles();
You can probably delete this

2020-10-22 21:13 UTC, tiffwong requested changes
This happens for medium viewports:
<img width="887" alt="Screen Shot 2020-10-22 at 5 02 47 PM" src="https://user-images.githubusercontent.com/7692354/96930300-7b801a00-1489-11eb-85e7-490683c29e5c.png">

We can change `<Hidden smDown>` to `<Hidden xsDown>` for all the columns except for the tags in DatabaseRow to prevent scroll or implement a `hideOnTablet` prop for EntityTableHeader (which would probably be better in the long run).

Other than the one cleanup comment I had, everything else looks good!

2020-10-22 22:24 UTC, DevDW reviewed
Looking good so far aside from the medium viewport issues @tiffwong mentioned. Thanks for the mocks 👍🏾

2020-10-23 13:21 UTC, johnwcallahan approved these changes
The "Region", "Hostname", "Port", and "Last Backup" API fields aren't going to be ready anytime soon... I say just remove them for now.

2020-10-23 13:21 UTC, johnwcallahan commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +const getDisplayStatus = (status: DatabaseStatus) => {
I did a similar thing in my PR; once this is merge we should lift this up and share the code.

2020-10-23 14:41 UTC, Jskobos commented
> We can change `<Hidden smDown>` to `<Hidden xsDown>` for all the columns except for the tags in DatabaseRow to prevent scroll or implement a `hideOnTablet` prop for EntityTableHeader (which would probably be better in the long run).
> 

I looked into this, EntityTableHeader needs some refactors that are a bit large for this PR. Used xsDown and I can make a ticket for adding hideOnTablet.

2020-10-23 14:42 UTC, WilkinsKa1 approved these changes
Landing looks great! In re to the callout @tiffwong made, we have a backlog task to update entity table to handle for tablet size styling- I'll pull that in to this sprint to address.

2020-10-26 14:51 UTC, tiffwong approved these changes

2020-10-26 14:52 UTC, merged