Change: Show all devices (not just root) in Config rows
linode/manager pull request #7044
Opened 2020-10-26 17:54 UTC by Jskobos

2020-10-26 20:37 UTC, tiffwong requested changes
If there are no configs, the VM Mode column wraps and the last column in the table headers looks funky
<img width="1303" alt="Screen Shot 2020-10-26 at 4 36 18 PM" src="https://user-images.githubusercontent.com/7692354/97225829-8993aa80-17a9-11eb-9c70-03c31fc48f32.png">

2020-10-28 14:44 UTC, DevDW reviewed
The devices appear to be displaying accurately -- left a couple of comments

2020-10-28 14:44 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
>      rootDeviceColumn: {
Should probably rename this now that the column is no longer just for the root device

2020-10-28 14:44 UTC, DevDW commented on packages/manager/src/components/TableCell/TableCell_CMR.tsx
> +    padding: '10px 15px',
This throws off some padding elsewhere in the app, e.g.

<img width="1274" alt="Screen Shot 2020-10-28 at 10 37 56 AM" src="https://user-images.githubusercontent.com/32860776/97451181-e0b09100-1909-11eb-805f-ab989e959a43.png">

2020-10-28 17:12 UTC, WilkinsKa1 approved these changes
Changes look good; I did notice something slightly off with the table padding (sorry 😬 ) it's pretty edge-case (non-blocking) and only really noticeable when there are a certain number of disks:
<img width="1311" alt="Screen Shot 2020-10-28 at 1 04 59 PM" src="https://user-images.githubusercontent.com/2565527/97471452-21ff6b80-191f-11eb-8f7e-b024d64ff72b.png">

2020-10-28 18:44 UTC, johnwcallahan approved these changes

2020-10-30 12:08 UTC, merged