Refine VlanTableRow logic to prevent comma visual display bug
linode/manager pull request #7048
Opened 2020-10-26 22:50 UTC by DevDW

## Description
Add some additional logic to prevent the extra commas display bug in the Linodes column of the VLAN panel on the Network tab.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')

2020-10-26 22:55 UTC, DevDW commented
@johnwcallahan After investigating the instance you brought up [here](https://github.com/linode/manager/pull/6985#pullrequestreview-516752550), I found that linode 13874804 didn't exist but was still linked to that VLAN. So under the previous logic, it remained in the list but since a label couldn't be retrieved for that linode ID (since it doesn't exist), it got rendered as an empty string with a comma following it.

2020-10-27 13:13 UTC, johnwcallahan requested changes
Good catch with the API bug.

2020-10-27 13:13 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +    const generatedLinks = filteredData.map(linode => (
This would be more semantic and readable using the `filter` method, i.e.:

```ts
const filteredData = data.filter( /* predicate function here */ );
```

2020-10-27 17:57 UTC, Jskobos approved these changes
Looks good, thanks for the catch.

2020-10-27 17:57 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
> +    const filteredData = data.filter(datum => {
with "datum" you're continuing the existing naming convention, which is fine. It might be slightly better if it was semantic all the way down (data -> vlanLinodes, filteredData -> filteredLinodes, etc.). We haven't been great about this, but we should really only be using "data" as a variable name if the method is pretty generic.

2020-10-28 18:05 UTC, johnwcallahan approved these changes
Nice work.

2020-10-28 20:34 UTC, merged