CMR: Fix IP link on Linode Entity Detail & Fix "Attached to" column wrapping in Volumes Landing table
linode/manager pull request #7061
Opened 2020-10-28 20:10 UTC by WilkinsKa1

## Description

• Fix "Attached to" column wrapping in Volumes Landing table
• Fix IP link on Linode Entity Detail (impacts dashboard, /linodes, and Linode detail pages)

## Type of Change
- Bug fix ('fix', 'repair', 'bug')

2020-10-29 12:58 UTC, Jskobos requested changes

2020-10-29 12:58 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodeEntityDetail.tsx
> +                    : `/linodes/${linodeId}/networking`
I think adding the slash will handle both cases without needing a conditional. As is, when I'm on Linode detail I get redirected to localhost:3000/networking, which is a 404.

2020-10-29 18:21 UTC, DevDW approved these changes
Aside from fixing the link as Jared noted to `/linodes/${linodeId}/networking` without the conditional, this looks good to me

2020-10-30 14:02 UTC, Jskobos approved these changes

2020-10-30 15:45 UTC, merged