M3-4006 Add: progress bar to LinodeDiskRow when resizing
linode/manager pull request #7071
Opened 2020-11-02 18:46 UTC by Jskobos

## Description

Refactor LinodeDisks so that LinodeDiskRow is a separate component. Each row now looks to see if there's a matching `disk_resize` event for the current disk, and if so shows a progress bar instead of a value for the "size" field.

The acid test, which kicked off this ticket, will be:

1. Create a small Alpine disk
2. Imagize it
3. Create a new disk from the image, specifying a size a bit larger than the image itself.
4. Observe: we display an incorrect size in the table when the creation is complete.

This is because a disk resize is kicked off in the background after the disk is created. Previously we couldn't detect the resize because no events were created, and as of Monday afternoon we still can't do much because the newly-added events don't contain information about which disk they pertain to. But soon we can test this full flow, and avoid displaying incorrect information to users.

## Note to Reviewers

The code here is ready, we're waiting on the API to merge a related PR to add the `secondary_entity` to `disk_resize` events. You can use the provided mocks to test in the meantime.

2020-11-03 18:43 UTC, DevDW approved these changes
LGTM, thanks for providing the mocks 👍🏾

2020-11-03 18:43 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
> +            Resizing ({resizeEvent?.percent_complete}%)
Maybe we can make this bold?

2020-11-04 20:41 UTC, johnwcallahan requested changes

2020-11-04 20:41 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
> +    thisEvent => thisEvent.secondary_entity?.id === disk.id
This should specifically look for the `disk_resize` event, I think. 

Currently, sometimes when you delete a disk it shows a progress bar, which is coming from the "disk_delete" event.

2020-11-04 20:43 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
> +    thisEvent => thisEvent.secondary_entity?.id === disk.id
Also, I guess we're doing the best we can, but it does feel strange to create a new disk and see "Resizing: 5%".

2020-11-04 20:45 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
> +    thisEvent => thisEvent.secondary_entity?.id === disk.id
🤷

2020-11-04 20:56 UTC, johnwcallahan approved these changes

2020-11-04 21:15 UTC, merged