Events refactor
linode/manager pull request #7073
Opened 2020-11-02 20:03 UTC by Jskobos

## Description

No one asked for this, exactly, but I think it's helpful. I added a bit to our event message generators that uses the `event.message` API message when it's provided. Almost all events don't have one still, so the fallback (our existing logic) will usually be used. 

I also removed the Message column in the event table, since this information will now appear in the main Label column instead.

Please feel free to push back on or discuss any of this.

2020-11-03 12:54 UTC, johnwcallahan requested changes
In the EventsLanding table, the text is wrapping without a hyphen (in Chrome):
<img width="644" alt="Screen Shot 2020-11-03 at 7 37 39 AM" src="https://user-images.githubusercontent.com/16911484/97986308-856a1d00-1da7-11eb-8a26-9a7179431e8b.png">

Also, I haven't reproduced this for real, but this message field was put in place for the `lke_node_create` event. Mocking one of those events with a message leads to this:


![Screen Shot 2020-11-03 at 7 53 32 AM](https://user-images.githubusercontent.com/16911484/97987672-b0ee0700-1da9-11eb-9cf4-b6e1fe19a3ee.png)

2020-11-03 12:54 UTC, johnwcallahan commented on packages/manager/src/mocks/serverHandlers.ts
> +        'Rebooting this thing and showing an extremely long event message for no discernible reason other than the fairly obvious reason that we want to do some testing of whether or not these messag
😄

2020-11-03 20:50 UTC, WilkinsKa1 approved these changes
LGTM! Hope you don't mind, I made a style adjustment based on @johnwcallahan 's callout.

2020-11-04 19:43 UTC, johnwcallahan approved these changes

2020-11-04 19:44 UTC, merged