M3-4646: Implement Bucket Details Drawer
linode/manager pull request #7083
Opened 2020-11-04 22:57 UTC by DevDW

## Description
When a user clicks the "Details" button of a bucket listed on the Buckets landing page, open a drawer for that bucket listing details about it.

## Type of Change
- Non breaking change ('update', 'change')

## To-Do
- [ ] ACL & CORS Control pieces

2020-11-04 23:03 UTC, DevDW commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {size || objectsNumber ? <Divider className={classes.divider} /> : null}
I wanted to do this as I did above with

```
      {(hostname || formattedCreated || cluster) && (
        <Divider className={classes.divider} />
      )}
```

but for an empty bucket, a 0 was being rendered:

<img width="479" alt="Screen Shot 2020-11-04 at 4 38 13 PM" src="https://user-images.githubusercontent.com/32860776/98176939-8a25f280-1ec7-11eb-8fb7-38a7e06a1e8a.png">

2020-11-05 13:47 UTC, Jskobos commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {size || objectsNumber ? <Divider className={classes.divider} /> : null}
the ternary is better for exactly this reason. You could explicitly do a `!!size || !!objectsNumber || !!cluster` and that would probably give you the correct result, but again: ternary is better.

2020-11-05 17:12 UTC, johnwcallahan requested changes
Nice work, I just have a few suggestions/proposals. Only blocking thing is about the size section always being displayed.

2020-11-05 17:12 UTC, johnwcallahan commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +          Cluster: {cluster}
I'd propose using the `formatObjectStorageCluster` function here, and dropping the "Cluster: " bit, so it just says, for example:

`Newark, NJ`

2020-11-05 17:12 UTC, johnwcallahan commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +          Number of Objects: {objectsNumber}
What do you think about replacing `Number of Objects: 52` with `52 Objects`? Additionally, we could make the text a link that would take you too the details page (with the Object list).

2020-11-05 17:12 UTC, johnwcallahan commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {hostname ? (
I'd follow this convention from the ObjectDrawer and have this be the very last item, and make it a clickable link with a copy icon.

2020-11-05 17:12 UTC, johnwcallahan commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {size || objectsNumber ? <Divider className={classes.divider} /> : null}
Also, you should be checking `typeof size === 'number'` instead of just `size`, since the later evaluates to `false` if the size is 0 (for an empty Bucket). Which means this section isn't currently shown for empty Buckets (but it should be).

2020-11-05 22:04 UTC, Jskobos approved these changes
Good work, small fixes only.

2020-11-05 22:04 UTC, Jskobos commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {hostname || formattedCreated || cluster ? (
Is it possible for none of these to be defined? Seems like you could just always show this

2020-11-05 22:04 UTC, Jskobos commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {objectsNumber ? (
I think this will be hidden if the number is 0, as John said elsewhere this should be `typeof objectsNumber === 'number'`

2020-11-05 22:07 UTC, DevDW commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +          Number of Objects: {objectsNumber}
That rewording works, and the link adds convenience

2020-11-05 22:20 UTC, DevDW commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {objectsNumber ? (
Should we display `0 objects` right under `0 bytes` though? Assuming a bucket can't have a size > 0 without any objects in it and can't have a size === 0 if it does have objects in it, the only time the number of objects would show would be when the bucket has objects in it.

2020-11-06 17:16 UTC, Jskobos commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {objectsNumber ? (
We might want to ask UX, but imo it's good to show both. We don't generally hide things when they're implied.

2020-11-06 20:03 UTC, tiffwong approved these changes
The functionality looks great!

The only comments I have are to make the content font .85rem to be consistent, remove the copy text and move the icon next to the link

2020-11-06 20:37 UTC, johnwcallahan commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
> +      {objectsNumber ? (
I agree that we should show both, even if they're both `0`.

2020-11-06 22:37 UTC, DevDW commented
> The only comments I have are to make the content font .85rem to be consistent, remove the copy text and move the icon next to the link

The font size seemed rather small when I tried 0.85rem, can you take a screenshot of how things are looking on your end -- are the font sizes mismatched? I kept the copy text and icon as-is to be consistent with the Object Details drawer, but if the consensus is that the icon alongside the link without the copy text is better, we can change it in both places

2020-11-09 13:38 UTC, johnwcallahan approved these changes
This works. Technically L98 should also check `typeof objectsNumber === 'number'`, so:

```ts
typeof size === 'number' || typeof objectsNumber === 'number'
```

2020-11-09 16:40 UTC, merged