M3-4278: Lazy load OBJ Buckets
linode/manager pull request #7091
Opened 2020-11-06 21:55 UTC by DevDW

## Description
Lazy load OBJ buckets

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Test PrimaryNav hover approach vs. alternative

2020-11-10 16:10 UTC, Jskobos requested changes
Prefetch is doing its thing 👍 , one small change needed.

2020-11-10 16:10 UTC, Jskobos commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +  const clustersLoaded = objectStorageClusters.lastUpdated > 0;
Need to check for loading here too, otherwise you get in a bunch of /clusters requests before lastUpdated changes:


![Screen Shot 2020-11-10 at 11 08 21 AM](https://user-images.githubusercontent.com/1624067/98699451-28410f00-2345-11eb-9530-f19b9ff960d5.png)

2020-11-10 20:24 UTC, Jskobos approved these changes

2020-11-10 20:24 UTC, Jskobos commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +      !clustersLoaded &&
This is fine, but why not add the loading check to line 132 instead?

2020-11-11 16:45 UTC, johnwcallahan approved these changes
One small fix required about checking for errors, otherwise good to go.

2020-11-11 16:45 UTC, johnwcallahan commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +  const clustersLoadedOrLoading =
Note: the changes I'm proposing in #7094 will make these stuff easier. We can clean it all up at once in a future ticket.

2020-11-11 16:45 UTC, johnwcallahan commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +    objectStorageClusters.lastUpdated > 0 || objectStorageClusters.loading;
You've also got to check for objectStorageClusters.error here, otherwise if you block requests to `*clusters*`, there's an infinite request loop.

2020-11-11 16:45 UTC, johnwcallahan commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +  }, [
This is requesting /clusters on app load, which I don't think is necessarily a bad thing.

2020-11-11 20:44 UTC, merged