M3-4630: Refactor Domain Create workflow
linode/manager pull request #7105
Opened 2020-11-11 23:01 UTC by tiffwong

## Description
As mentioned in [https://github.com/linode/manager/pull/5646](https://github.com/linode/manager/pull/5646), the Domain Create flow is inconsistent with the rest of Cloud's creation flows. To fix this, Domain Create has been moved to it's own page with a corresponding route, `/domains/create`.

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
Please check the different routes that lead to the Domain Create workflow

2020-11-12 14:46 UTC, Jskobos requested changes
Good work, most of my comments are about old stuff that has been wonky for ages. Only blocking change is the broken errormap check for the domain name.

2020-11-12 14:46 UTC, Jskobos commented on packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
> +  componentDidUpdate(prevProps: CombinedProps, prevState: State) {
This pattern is bad and we should refactor it (later)

2020-11-12 14:46 UTC, Jskobos commented on packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
> +                errorText={'' && errorMap.domain}
Need to delete the `'' &&`, this always evaluates to false

2020-11-12 14:46 UTC, Jskobos commented on packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
> +  ) => this.setState({ type: value });
I think this should reset the error state too

2020-11-12 14:46 UTC, Jskobos commented on packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
> +                    <LinodeSelect
Can these be disabled? If possible they should be, for restricted users.

2020-11-12 19:21 UTC, WilkinsKa1 reviewed
This is great, nice work on this! Besides the error missing that Jared called out, I also noticed this: 
<img width="1201" alt="Screen Shot 2020-11-12 at 9 49 29 AM" src="https://user-images.githubusercontent.com/2565527/98985975-48fa9780-24f2-11eb-8f60-3562cff9d018.png">
may just need a max-width applied or some adjustments to the flex container.

2020-11-12 21:56 UTC, Jskobos approved these changes
Looks good, if possible please also disable the default records dropdown and nodebalancers dropdown for restricted users before merging.

2020-11-13 20:39 UTC, WilkinsKa1 approved these changes

2020-11-16 16:54 UTC, merged