M3-4662 Managed Summary tab
linode/manager pull request #7121
Opened 2020-11-17 18:30 UTC by johnwcallahan

## Description

Since we're removing the Dashboard in CMR, we need a place for the ManagedDashboardCard. There's now a new tab called "Summary" on the Managed Landing page which houses this component. I also refactored ManagedLandingContent to use NavTabs. Once we fully move to CMR we'll move the files to the Managed directory.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please check both CMR and non-CMR.

2020-11-18 15:49 UTC, Jskobos requested changes
I think the union of beta testers | managed customers is small, but even so I think we should remove the "Linode Managed" and "details" link (since you're already on Managed now and the details link takes you to where you are). seems like removing the dashboardcard wrapper will do both things, but maybe annoying to do it conditionally.

2020-11-19 14:02 UTC, johnwcallahan commented
> I think the union of beta testers | managed customers is small, but even so I think we should remove the "Linode Managed" and "details" link (since you're already on Managed now and the details link takes you to where you are). seems like removing the dashboardcard wrapper will do both things, but maybe annoying to do it conditionally.

Good call. I didn't end up having to do it conditionally since it's in a CMR file. I kept the card around (removed title and headerAction props) in order to keep the styling.

2020-11-19 14:17 UTC, Jskobos approved these changes

2020-11-19 16:15 UTC, DevDW approved these changes

2020-11-19 16:16 UTC, merged