CMR Action Menus
linode/manager pull request #7139
Opened 2020-11-20 22:40 UTC by tiffwong

## Description
- Huge PR to remove "Details" from the ActionMenu if the label has a link to the details view already
- As a result, had to bump up the following action in some cases 
- Rename "Details" to "Edit" on Images Landing
- Also cleaned up the styles and syntax of all the ActionMenu files _fingerscrossed_

## Type of Change
- Non breaking change ('update', 'change')

2020-11-23 15:30 UTC, WilkinsKa1 approved these changes
Nice work, well done! We didn't discuss this with Matthew but we should clarify the removal of this or not: 

<img width="211" alt="Screen Shot 2020-11-23 at 10 22 01 AM" src="https://user-images.githubusercontent.com/2565527/99980945-cc2faf00-2d76-11eb-8406-1dc4269f0c05.png"> (on Linodes detail landing view) I would think we should remove to be consistent but not blocking this PR.

2020-11-23 15:39 UTC, Jskobos requested changes
I'm very happy about these changes! I found a few oddities and made some cleanup suggestions.

- Linode Action menu still has details on mobile view
- Edit button for a primary domain doesn't do anything
- the mobile version of the above goes to the details page for the domain, but it should
  open the edit drawer
- Databases has both a label link to detail view and a details action

2020-11-23 15:39 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
> +        type === 'master' ? goToDomain : handleEdit;
You need to invoke these functions. And I don't think goToDomain is correct here, even though it seems to have been in the previous version. It should open the edit domain drawer.

2020-11-23 15:39 UTC, Jskobos commented on packages/manager/src/features/Volumes/VolumesActionMenu_CMR.tsx
> +      actionText: 'Details',
Now that we're getting rid of Details in general, I don't think Details is the correct thing to show here. This isn't details about the Volume, it's configuration information. Call it "Show config" or similar, that's what it used to be pre-CMR.

2020-11-23 15:39 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
> +      actionText: 'Edit',
This doesn't have to happen now, but I want to purge all "actionText" from the codebase. There's only Actions, which can be either inline or not. Then it might be workable to combine these rather than use all the unshift stuff...have a full list of actions, then use `actions.slice()` or (from Ramda) `splitAt(2, actions)` to pull off the front actions for inline stuff.

2020-11-23 15:39 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
> +      actionText: 'Edit',
`const [inlineActions, menuActions] = Ramda.splitAt(2, actions)`

2020-11-23 15:39 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
> +      actionText: 'Edit',
then 2 is conditional depending on whether mobile or &etc.

2020-11-23 16:07 UTC, DevDW reviewed
Looking good so far; aside from the points raised earlier, I noticed when there's a call-to-action banner in the mobile view, the ellipsis button for the action menu has the spacing for its active state thrown off a bit (although this is also happening outside this branch/PR)

<img width="429" alt="Screen Shot 2020-11-23 at 10 36 03 AM" src="https://user-images.githubusercontent.com/32860776/99984279-dbb0f700-2d7a-11eb-8b0e-010a3737213c.png">

2020-11-23 18:17 UTC, tiffwong commented on packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
> +      actionText: 'Edit',
I'll create another ticket for this!

2020-11-23 18:18 UTC, tiffwong commented
> Looking good so far; aside from the points raised earlier, I noticed when there's a call-to-action banner in the mobile view, the ellipsis button for the action menu has the spacing for its active state thrown off a bit (although this is also happening outside this branch/PR)
> 
> <img alt="Screen Shot 2020-11-23 at 10 36 03 AM" width="429" src="https://user-images.githubusercontent.com/32860776/99984279-dbb0f700-2d7a-11eb-8b0e-010a3737213c.png">

Good catch! This seems to be part of a larger issue that I think might be related to negative margins that MUI uses, I'll open a ticket to look into this!

2020-11-24 14:03 UTC, Jskobos approved these changes

2020-11-24 20:16 UTC, merged