CMR Documentation Button - Phase 2
linode/manager pull request #7142
Opened 2020-11-23 16:01 UTC by tiffwong

## Description

Please start the pull request title with the jira ticket corresponding to the work if applicable. Please include a short summary of the feature added, the change, or issue fixed.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')
- Non breaking change ('update', 'change')
- Breaking change ('break', 'deprecate')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

2020-11-23 21:56 UTC, WilkinsKa1 requested changes
Looking good- there are a few more places the new docs button needs to be added:

• Stackscript details
• LKE cluster details (replace old docs button with new)
• Domain details
• NodeBalancer details
• Longview details (replace old with new

2020-11-24 19:31 UTC, WilkinsKa1 approved these changes

2020-11-30 17:27 UTC, johnwcallahan reviewed
I vote for removing the "external" icon on hover; it's a bit jarring that it appears out of the main content area.

![Screen Shot 2020-11-30 at 12 16 05 PM](https://user-images.githubusercontent.com/16911484/100642790-3b714a00-3307-11eb-8e13-97e9031b17e2.png)

On Domain Details, when the domain name is long and the buttons wrap, there should be some left padding:

![Screen Shot 2020-11-30 at 12 20 34 PM](https://user-images.githubusercontent.com/16911484/100642800-3e6c3a80-3307-11eb-92fc-0f6391891c0e.png)

Also there's a regression present here (not on develop) in non-CMR:
![Screen Shot 2020-11-30 at 12 25 19 PM](https://user-images.githubusercontent.com/16911484/100642842-4deb8380-3307-11eb-8a8a-6eed80c6e396.png)

2020-11-30 20:31 UTC, DevDW approved these changes
LGTM 👌 

What are your thoughts on a bit of right padding for the Docs button in the mobile view so it isn't flush with the page edge?

<img width="401" alt="Screen Shot 2020-11-30 at 3 28 26 PM" src="https://user-images.githubusercontent.com/32860776/100661034-dcb8ca00-3320-11eb-9e6e-de7a9783dd7f.png">

2020-11-30 20:31 UTC, DevDW commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
> +  it.skip('includes the Pool ID', () => {
Do we still need to skip this? It passed when I ran the test without skipping it

2020-11-30 21:37 UTC, tiffwong commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
> +  it.skip('includes the Pool ID', () => {
It failed when I originally tried to commit but it seems to run fine now so I removed the skip, thanks for checking this!

2020-12-01 14:46 UTC, merged