Linode Entity Detail Adjustments
linode/manager pull request #7154
Opened 2020-11-24 20:26 UTC by tiffwong

## Description

**Before:**
<img width="1255" alt="Screen Shot 2020-11-24 at 3 25 47 PM" src="https://user-images.githubusercontent.com/7692354/100147439-61ab6b80-2e69-11eb-89e0-6686a3965b92.png">

**After:**
<img width="1113" alt="Screen Shot 2020-11-24 at 3 23 04 PM" src="https://user-images.githubusercontent.com/7692354/100147160-f6619980-2e68-11eb-9a2c-c840a21587e0.png">

- Updated the detail header to match the preliminary designs
- The buttons in the screenshot will be updated when [https://github.com/linode/manager/pull/7140](https://github.com/linode/manager/pull/7140) is merged
- Also added a fix to prevent the status on Domain Landing from wrapping 

## Note to Reviewers
There's definitely some scope creeping happening here so will wait for [https://github.com/linode/manager/pull/7145](https://github.com/linode/manager/pull/7145) to be merged first so I can fix the conflicts

2020-11-24 22:05 UTC, WilkinsKa1 reviewed
I know this has the wait label, but initial review on this looks great- this was a huge undertaking, really fantastic work on this. 

Only thing I've noticed so far is on linode landing details variant, the label is a bit wonky:
<img width="491" alt="Screen Shot 2020-11-24 at 4 38 55 PM" src="https://user-images.githubusercontent.com/2565527/100156503-0a13fc80-2e77-11eb-8913-5fac94af653a.png">

I think we can potentially remove the entity icon to regain some space and will probably need some additional flex adjustments to play well with the status.

2020-11-30 17:58 UTC, johnwcallahan reviewed
Do we have a design for tablet viewport sizes? There's a lot of whitespace here:

![Screen Shot 2020-11-30 at 12 46 18 PM](https://user-images.githubusercontent.com/16911484/100645942-62317f80-330b-11eb-8ae6-7e166bc3b8a8.png)

There's also a regression in VLANS: 
![Screen Shot 2020-11-30 at 12 53 11 PM](https://user-images.githubusercontent.com/16911484/100646125-9dcc4980-330b-11eb-9146-527f3276d2cb.png)

And (less importantly) DBaaS:
![Screen Shot 2020-11-30 at 12 57 27 PM](https://user-images.githubusercontent.com/16911484/100646148-a886de80-330b-11eb-82e8-059280b969df.png)

2020-11-30 19:57 UTC, tiffwong commented
> Do we have a design for tablet viewport sizes? There's a lot of whitespace here:
> 
> ![Screen Shot 2020-11-30 at 12 46 18 PM](https://user-images.githubusercontent.com/16911484/100645942-62317f80-330b-11eb-8ae6-7e166bc3b8a8.png)
> 
> There's also a regression in VLANS:
> ![Screen Shot 2020-11-30 at 12 53 11 PM](https://user-images.githubusercontent.com/16911484/100646125-9dcc4980-330b-11eb-9146-527f3276d2cb.png)
> 
> And (less importantly) DBaaS:
> ![Screen Shot 2020-11-30 at 12 57 27 PM](https://user-images.githubusercontent.com/16911484/100646148-a886de80-330b-11eb-82e8-059280b969df.png)

There are currently no tablet designs but I'll inquire about the status of those and I'll create a new ticket to fix the regressions

2020-12-01 14:19 UTC, Jskobos requested changes
This looks great, _very_ different from the CMR of yore. Everything seems to be working and I'd suggest getting this in to develop asap and iterating. That said, one blocking change (Dark theme needs some tweaking):
![Screen Shot 2020-12-01 at 9 09 13 AM](https://user-images.githubusercontent.com/1624067/100751133-f572bf80-33b4-11eb-9610-40bb97bee965.png)

Optionally, a fixed height for the footer would be nice. There's a bit of jump when opening the tag input.

And I noticed that the node pools table for LKE still has the old row click. There should be a separate task to make the label a link and remove the row-wide click handler.

2020-12-01 16:15 UTC, DevDW reviewed
Nice job with this; I noticed a couple of things in addition to what others have observed:

- On the Managed page, should the "Open Support Ticket" and "Docs" button be different colors?

<img width="1114" alt="Screen Shot 2020-12-01 at 10 51 35 AM" src="https://user-images.githubusercontent.com/32860776/100763768-9b2d2b00-33c3-11eb-9c94-1a828eb48b64.png">

- I think we should change "Vlans" to "VLANs". This will make it consistent with how we're capitalizing it for the Create button here and elsewhere in the app.

<img width="1114" alt="Screen Shot 2020-12-01 at 10 52 28 AM" src="https://user-images.githubusercontent.com/32860776/100764087-f6f7b400-33c3-11eb-8235-c58f810c9f68.png">

2020-12-01 18:10 UTC, tiffwong commented on packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
> +      <Grid
Not sure what happened but I replaced it with the `TagsPanelRedesigned` and that seems to fix the issue

2020-12-01 18:21 UTC, tiffwong commented
@DevDW good catch! There seem to be some inconsistencies throughout the app when it comes to the link colors in the dark theme so I'll create a separate ticket to handle any others but I did fix the managed one

You make a good point with the VLAN naming convention so I'll include that in another PR that I'll have up soon

2020-12-01 18:31 UTC, Jskobos approved these changes
Thanks for the quick turnaround. I found one other small thing, but that can go in a follow-on:

![Screen Shot 2020-12-01 at 1 29 32 PM](https://user-images.githubusercontent.com/1624067/100781766-7479ef00-33d9-11eb-94eb-d66c39884805.png)

(the header bulges out a pixel or two, happens on both themes but easier to see on dark)

2020-12-01 19:22 UTC, johnwcallahan approved these changes

2020-12-01 19:24 UTC, DevDW approved these changes

2020-12-01 20:39 UTC, merged