Change: add warning when migrating a Linode with VLANs to a region w/o VLANs
linode/manager pull request #7155
Opened 2020-11-24 20:51 UTC by Jskobos

## Description

- Check if the region to be migrated to supports VLANs.
- If it doesn't, show a note under the region input letting them know.
- Fix DOM nesting validation (we need to be more careful what we
  put inside a `<Notice />`).
- Fix a glitch where you could submit the form without accepting the
  conditions.

2020-11-25 14:10 UTC, johnwcallahan requested changes

2020-11-25 14:10 UTC, johnwcallahan commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
> +    !regions.entities[selectedRegion ?? '']?.capabilities.includes('Vlans');
Think this needs to use `.find()` or similar, since regions.entities is a Region[].

2020-11-25 16:54 UTC, johnwcallahan approved these changes

2020-11-30 16:59 UTC, tiffwong commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
> +            ? 'Note: this region does not support VLANs.'
The 't' in 'this' should be capitalized

2020-11-30 16:59 UTC, tiffwong approved these changes
Other than the one comment I had, everything else looks great!

2020-12-01 01:38 UTC, merged