M3-4582 Change: Use a shared component for view-only permissions tables.
linode/manager pull request #7169
Opened 2020-12-01 21:06 UTC by Jskobos

## Description

For OBJ access tokens and API access tokens, instead of showing a disabled version of the scopes form (with a bunch of radio buttons), if a user is in view-only mode instead use check marks for selected permissions. I opted to go with a shared (new) component for this, though it isn't clear if it's worth it in this case.

![Screen Shot 2020-12-01 at 4 04 07 PM](https://user-images.githubusercontent.com/1624067/100796558-da24a600-33ee-11eb-97bb-70ba01b3f89b.png)

@ndukatz there are a few existing e2e tests that used data-qa attributes that are lost using this approach (nothing in Cypress though). Please let me know if I broke anything you're working on.

@tiffwong making this change meant that the aria stuff needed to be dynamic. The results are a bit different but I think they're ok. Please let me know.

- [ ] unit tests

2020-12-01 21:10 UTC, Jskobos commented on packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
> +      return !isThirdPartyAccessToken
These are linter fixes

2020-12-02 16:00 UTC, johnwcallahan requested changes
UI looks good, one bug in the PAT drawer.

Not sure about the accessibility here. Maybe the span containing the SVG needs something like:

```
        role="checkbox"
        aria-checked="true"
        aria-disabled="true"
```

2020-12-02 16:00 UTC, johnwcallahan commented on packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
> +                    scope="2"
Think this should be "0"... currently there's some incorrect behavior when you click "None" for a single scope.

2020-12-02 16:46 UTC, Jskobos commented
> UI looks good, one bug in the PAT drawer.
> 
> Not sure about the accessibility here. Maybe the span containing the SVG needs something like:
> 
> ```
>         role="checkbox"
>         aria-checked="true"
>         aria-disabled="true"
> ```

I'm not sure about accessibility either, I feel weird telling people it's a checkbox when it isn't. I added an aria-label to the span instead, let me know what you think. @tiffwong please weigh in as well.

2020-12-02 18:18 UTC, johnwcallahan approved these changes
The ARIA label makes sense to me.

2020-12-02 19:06 UTC, tiffwong commented on packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
> +        aria-label={`This token has ${scope} access for ${scopeDisplay}`}
Currently, the `aria-label` isn't accessible so this never gets read but can easily be fixed by adding `tabIndex={0}`

2020-12-02 19:10 UTC, tiffwong requested changes
This looks great! The check icons are a great visual touch to prevent users from thinking they can edit the permissions 💯 

The only comment I have is to add a `tabIndex` so that users can access the `aria-label` and I agree with not labeling it as a checkbox since that could confuse the user into thinking they can edit it (which defeats the whole purpose of this)

2020-12-07 15:32 UTC, tiffwong approved these changes

2020-12-07 15:33 UTC, merged