M3-4687 Move Nav back to the Left
linode/manager pull request #7172
Opened 2020-12-01 22:43 UTC by johnwcallahan

## Description

Still todo:

- Use actual spacing, gradient, colors, etc. (waiting on design files)
- Fix mobile menu
- General cleanup

2020-12-02 21:21 UTC, tiffwong commented on packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
> +                [classes.linkItem]: true
If these are always true, we can probably simplify these

2020-12-02 21:24 UTC, tiffwong approved these changes
Other than the one commend I had about cleanup, everything else looks great!

2020-12-03 14:06 UTC, Jskobos requested changes
Looks good.
- VLANS should be VLANs
- What's up with Images? (you said spacing wasn't final, just curious)
- DW added prefetch logic for OBJ clusters, which seems lost in translation.

2020-12-03 15:08 UTC, johnwcallahan commented
> What's up with Images? (you said spacing wasn't final, just curious)

@Jskobos you mean the space between "Images" and "Domains"? That space is a way to group items in the Nav (also reflected in the 2D PrimaryLink array). It makes more sense when Managed is in the picture: 

<img width="175" alt="Screen Shot 2020-12-03 at 9 57 46 AM" src="https://user-images.githubusercontent.com/16911484/101046054-bc6e5280-354e-11eb-9408-764815700dd6.png">

Maybe when Managed is _not_ in the picture there should be more space between the Logo and Linodes, or make "Linodes" its own category.

2020-12-03 16:07 UTC, DevDW approved these changes
LGTM 👍 

In Zeplin it looks like the nav item titles aren't bold?

This can be considered later, but the spacing to group the nav items does strike me as a bit odd, maybe it'd look better if the first item in each group only had a bottom border instead of a top border?

2020-12-03 16:28 UTC, Jskobos approved these changes

2020-12-03 16:41 UTC, merged