M3-4707: Entity Detail tablet viewport
linode/manager pull request #7178
Opened 2020-12-04 18:21 UTC by tiffwong

## Description
- Update tablet viewport to match designs which are activated at 720px
- All inline actions for Linodes are now hidden for tablet
- Tags will wrap depending on how many details there are (ie. Linode tags wrap at 1280px and Database tags wrap at 720px)

## Note to Reviewers
The mock shadow plan Linode should now reflect the longest legacy plan name. If it is a legacy Linode, it will automatically move the tags to the following row

2020-12-04 18:23 UTC, tiffwong commented on packages/manager/src/components/TagCell/TagCell.tsx
> +    minHeight: 40,
Moved the `minHeight` here to prevent duplicate styles, everything else is mostly just me grouping the styles so they make more sense

2020-12-04 18:27 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodeEntityDetail.tsx
> +  // Cheat to determine if it's a legacy plan
This is me cheating on recognizing legacy plans, lmk if I should do this differently

2020-12-04 18:58 UTC, tiffwong commented on packages/manager/src/components/TagCell/TagCell.tsx
> +  breakpoint: {
Added this to prevent duplicate styles whenever we need the `TagCell` to wrap in `EntityDetail` components

2020-12-04 19:00 UTC, tiffwong commented on packages/manager/src/components/TagCell/TagCell.tsx
> +  const isBreakpoint = breakpoint ? true : undefined;
Seems convoluted but this is the workaround I came up with when react won't let me put hooks inside conditions

2020-12-04 20:54 UTC, DevDW reviewed
Looks good so far, two points --

1. Should we nudge the `Delete` button for VLANs to the right a bit? It could align with the Docs button

<img width="753" alt="Screen Shot 2020-12-04 at 3 37 30 PM" src="https://user-images.githubusercontent.com/32860776/101213503-7b5a6900-3648-11eb-93cb-976f621d1af9.png">

2. When you go to add a tag to a Linode in the Entity Detail header, the field jumps to the right

2020-12-04 22:25 UTC, tiffwong commented
@DevDW I made the "Delete" button aligned with the "Docs" button but the focus state is right up to the edge, how does that look to you?

2020-12-04 22:33 UTC, DevDW commented
> @DevDW I made the "Delete" button aligned with the "Docs" button but the focus state is right up to the edge, how does that look to you? It's also not aligned once the page is full width
> <img alt="Screen Shot 2020-12-04 at 5 26 30 PM" width="1124" src="https://user-images.githubusercontent.com/7692354/101221523-dc3c6e00-3655-11eb-892c-73c2acccc0d1.png">

I should have been clearer in my original comment, I meant nudging it a bit to the right so that their left edges would be aligned. If that's done I think it would address the edge concern and the misalignment when it's full width

Tags field looks good now 👍

2020-12-07 14:22 UTC, johnwcallahan requested changes
It's coming along, nice job. Left a few code comments, and here are some UI observations:

We probably want to shift the Docs button to the next line earlier, since when you go to edit your Linode's label, the Breadcrumb takes up more width. Also, note that the Docs button and breadcrumb aren't vertically aligned here:

![Screen Shot 2020-12-07 at 8 49 01 AM](https://user-images.githubusercontent.com/16911484/101361589-29465d00-386d-11eb-9354-e5e4efdd2a2c.png)

When the Docs button _is_ on the next line (like when you have a long Linode label), there should be some left margin:
![Screen Shot 2020-12-07 at 8 53 10 AM](https://user-images.githubusercontent.com/16911484/101361700-50049380-386d-11eb-82e3-6e03f99f373f.png)

There's a lot of extra margin/whitespace to the right of the Entity Detail Header around 600-700px:
![Screen Shot 2020-12-07 at 8 50 40 AM](https://user-images.githubusercontent.com/16911484/101361751-63176380-386d-11eb-801d-8c41e9043395.png)

Depending on the contents, the footer layout breaks at various breakpoints:
![Screen Shot 2020-12-07 at 8 51 21 AM](https://user-images.githubusercontent.com/16911484/101361836-8215f580-386d-11eb-808c-26511d2d599f.png)

2020-12-07 14:22 UTC, johnwcallahan commented on packages/manager/src/components/TagCell/TagCell.tsx
> +  const isBreakpoint = breakpoint ? true : undefined;
It's a lot of hoops to jump through. And the original DBaaS designs had "Region" and "Plan" in the footer like Linodes, which means that ultimately they'll want to shift the layout at the same breakpoint anyway.

I'd remove the `breakpoint` prop and just make it a hard CSS rule to shift at 1280px. We can adjust in the future if we need to.

2020-12-07 19:03 UTC, tiffwong commented on packages/manager/src/MainContent_CMR.tsx
> +    overflow: 'hidden',
Did this cause an issue before? I feel like I made this adjustment in the past to prevent the excess horizontal whitespace but it had had unexpected side effects 🤔

2020-12-07 19:53 UTC, Jskobos approved these changes

2020-12-08 14:59 UTC, johnwcallahan approved these changes
Looks good. We still need to handle for when the footer is large:

<img width="1136" alt="Screen Shot 2020-12-08 at 9 55 23 AM" src="https://user-images.githubusercontent.com/16911484/101499684-8b6d9380-393b-11eb-9158-c9840ac62de8.png">

The wrapping doesn't bother me but we should hide the borders. Can you think of any CSS magic to achieve that? I tried a few ideas without luck.

Another potential solution is to force the tags to be on their own row if the information is too large (like you had before; we just can't solely rely on the plan name).

2020-12-08 16:33 UTC, johnwcallahan approved these changes
The issue I mentioned with the footer has been fixed since the branch was brought up to date... looks good!

2020-12-08 19:25 UTC, merged