M3-4716 CMR fixes for profile section
linode/manager pull request #7186
Opened 2020-12-07 21:30 UTC by Jskobos

## Description

Things from LISH and Display settings in profile from the trello board:
1. Update LISH tab name to LISH Settings (to match user menu drop down)
2. Buttons on Display Settings tab are disabled until the user made a change
  - this involved tweaking the success/state logic for the time zone field
3. Same thing (disabled until change) on LISH settings. This doesn't quite work unless you have an SSH key saved already, but the fix for that case is larger and should be handled separately.
4. Change LISH buttons to normal `<button>`s with link styles, and move the "remove" buttons underneath the text field.
5. (wasn't part of the spec) move the helper text underneath the SSH key mapping (so it isn't repeated for each key)

2020-12-07 21:45 UTC, tiffwong commented on packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
>          <DocumentTitleSegment segment="Lish" />
Should. probably change it here as well

2020-12-08 16:08 UTC, johnwcallahan requested changes
Some of the new CSS is causing a super small text input on small breakpoints. Otherwise LGTM.
<img width="669" alt="Screen Shot 2020-12-08 at 11 06 44 AM" src="https://user-images.githubusercontent.com/16911484/101508453-b1983100-3945-11eb-9b1c-261a8c9723b3.png">

2020-12-08 21:44 UTC, tiffwong approved these changes
Piggybacking on @johnwcallahan's feedback, the "Save" button is misaligned for mobile but otherwise, it looks good!

2020-12-11 15:01 UTC, johnwcallahan approved these changes

2020-12-11 15:02 UTC, merged