Create button follow up
linode/manager pull request #7214
Opened 2020-12-11 22:40 UTC by tiffwong

2020-12-14 21:02 UTC, Jskobos reviewed
The docs link looks frail next to the bolded inline action on Domains landing:

![Screen Shot 2020-12-14 at 3 36 51 PM](https://user-images.githubusercontent.com/1624067/102135283-bcf7ca80-3e25-11eb-95eb-35225ceadeed.png)

2020-12-14 21:03 UTC, Jskobos commented
> The usage of "Kubernetes" and "Kubernetes Clusters" is inconsistent. The Kubernetes Landing page is also the only instance where the breadcrumb will wrap since it's so long so I'm considering changing it to say "Kubernetes" but I want to double-check with everyone before I go and do that 💁‍♀️

I agree, if nothing else the detail and landing text should match so there's no jump when clicking on the crumb. I'm fine with Kubernetes in both places (Kubernetes Clusters is more accurate but kind of long)

2020-12-14 21:31 UTC, Jskobos approved these changes
Looking pretty good. None of the feedback (from earlier or here) is blocking

1. Support tickets page looks good but uses the old pattern...is it fine as is?
2. Thanks for adding the loading state to the button for creating a longview client...usually, though, buttons use the built-in loading state (w/ a spinner) included in src/components/Button.

2020-12-14 21:31 UTC, Jskobos commented on packages/manager/src/components/EntityHeader/EntityHeader.tsx
> +            xs={actions ? 9 : 4}
lot of magic numbers here 🤷‍♂️

2020-12-14 22:00 UTC, johnwcallahan requested changes
Couple of notes:

Domains Header wraps strangely at smaller breakpoints:
<img width="500" alt="Screen Shot 2020-12-14 at 4 27 28 PM" src="https://user-images.githubusercontent.com/16911484/102140719-ac4b5280-3e2d-11eb-8752-2b2a68f9c7b2.png">

I feel that in general the Create Buttons should have right-padding so they don't run up against the edge of the screen:

<img width="527" alt="Screen Shot 2020-12-14 at 4 26 39 PM" src="https://user-images.githubusercontent.com/16911484/102140751-bcfbc880-3e2d-11eb-86d0-cfeedc9284c9.png">

(Also see my comment about the Object Storage buttons)

2020-12-14 22:32 UTC, DevDW reviewed
> I feel that in general the Create Buttons should have right-padding so they don't run up against the edge of the screen:

Relatedly, at tablet viewport sizes, I think the breadcrumb could use a bit of left-padding:

<img width="958" alt="Screen Shot 2020-12-14 at 5 18 16 PM" src="https://user-images.githubusercontent.com/32860776/102142605-b4f15800-3e30-11eb-9fa8-a7650848935d.png">

Side note, looks like that table row border issue is still pestering us:

<img width="408" alt="Screen Shot 2020-12-14 at 4 54 47 PM" src="https://user-images.githubusercontent.com/32860776/102143297-c129e500-3e31-11eb-97ce-729dc0d4c6f2.png">

2020-12-15 14:31 UTC, johnwcallahan requested changes
Left a few more comments. Additionally there's a bug on the OBJ Access Landing page where: 

1. Edit permissions of an existing Access Key. 
2. Click "Create an Access Key"
3. Observe: the drawer is in "Edit" mode.

2020-12-15 15:25 UTC, tiffwong commented on packages/manager/src/components/EntityHeader/EntityHeader.tsx
> +    paddingBottom: theme.spacing(),
Nope, that's a regression

2020-12-15 20:59 UTC, johnwcallahan approved these changes

2020-12-15 21:34 UTC, merged