M3 daily update
linode/manager pull request #7224
Opened 2020-12-15 06:40 UTC by ndukatz

## Description

Please start the pull request title with the jira ticket corresponding to the work if applicable. Please include a short summary of the feature added, the change, or issue fixed.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')
- Non breaking change ('update', 'change')
- Breaking change ('break', 'deprecate')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

2020-12-15 13:35 UTC, johnwcallahan requested changes
Haven't run the tests yet; let a few comments. Question though... why the super long timeouts?

2020-12-15 13:35 UTC, johnwcallahan commented on packages/manager/cypress/support/api/firewalls.ts
> +      getFirewalls().then(resp => {
Is the double loop + request necessary? Couldn't you do:

```ts
getFirewalls().then(resp => {
  resp.data.forEach(firewall => {
    if (isTestEntity(firewall)) {
      deleteFirewallById(firewall.id);
    }
  }
}

2020-12-15 13:35 UTC, johnwcallahan commented on packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts
> +          fbtClick('Create a Firewall');
Honestly this seems like the text is wrong... they should probably both be "Create a Firewall" in the UI.

2020-12-15 19:32 UTC, ndukatz commented on packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts
> +          fbtClick('Create a Firewall');
that would be nice

2020-12-15 19:39 UTC, ndukatz commented on packages/manager/cypress/support/api/firewalls.ts
> +      getFirewalls().then(resp => {
this is in order to handle pagination, but you made me realize that there are some missing parts. still might not be the best way but I'll push up the missing stuff first.

2020-12-16 13:54 UTC, Jskobos commented on packages/manager/cypress/support/api/firewalls.ts
> +      getFirewalls().then(resp => {
I don't think this will paginate correctly, if there's N pages it's just retrieving the first page N times. Pagination probably isn't necessary, anyway...you can specify `?page_size=500` in the request url and get 500 results in one page. I doubt that any automation test account will ever have >500 of a single entity, especially since we're cleaning after each run.

2020-12-18 14:46 UTC, Jskobos approved these changes

2020-12-21 21:19 UTC, merged