Trello button and link changes
linode/manager pull request #7241
Opened 2020-12-17 17:50 UTC by tiffwong

## Description

Remove the icons on the Kubernetes Detail pages and change the "Add a Node Pool" button to primary
Change the button to a link on `My Profile > Password & Authentication > Password Reset`
Change the button style from primary to secondary on `Firewalls > Rules`

2020-12-17 18:38 UTC, tiffwong commented on packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
> +      <Typography variant="h2">Password Reset</Typography>
Adjusted the variant here to match the styles used in the TFA section below

2020-12-17 18:40 UTC, tiffwong commented on packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
> +      <Typography variant="body1" className={classes.copy}>
Next Level Apparel

2020-12-17 18:41 UTC, tiffwong commented on packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
> +      <Typography variant="body1" className={classes.copy}>
Adjusted the variants here to match the ones used in the TFA section below

2020-12-18 14:03 UTC, johnwcallahan requested changes
This is also an issue in production, but we might as well fix it here:
![Screen Shot 2020-12-18 at 9 02 47 AM](https://user-images.githubusercontent.com/16911484/102623033-de9bcf00-410f-11eb-9795-394f762e6075.png)

2020-12-18 14:03 UTC, johnwcallahan commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
> +              handleOpenAddDrawer();
No need to create a new function here; you can do: `onClick={handleOpenAddDrawer}`.

2020-12-18 15:49 UTC, DevDW approved these changes
I didn't see any additional issues beyond what @johnwcallahan pointed out. Approved pending on those fixes

2020-12-21 15:56 UTC, johnwcallahan approved these changes

2020-12-21 17:05 UTC, merged