M3-4165: Refactor StackScripts
linode/manager pull request #7254
Opened 2020-12-21 20:44 UTC by tiffwong

## Description

Please start the pull request title with the jira ticket corresponding to the work if applicable. Please include a short summary of the feature added, the change, or issue fixed.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')
- Non breaking change ('update', 'change')
- Breaking change ('break', 'deprecate')

If the any above types of change apply to this pull request, please ensure to include one of the listed keywords in the pull request title.

## Applicable E2E Tests

To run relevant E2E tests, run these commands in 3 separate terminals:

1. `yarn && yarn start`
2. `yarn selenium`
3. `yarn e2e --spec=COMMA_SEPARATED_LIST_OF_SPECS_HERE --browser=headlessChrome`

## Note to Reviewers

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

2020-12-21 22:38 UTC, tiffwong commented on packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
> +            // eslint-disable-next-line array-callback-return
Linter

2020-12-21 22:39 UTC, tiffwong commented on packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
> -// import StackScriptDetailsHeader from './StackScriptDetailsHeader';
This component is no longer being used

2020-12-21 22:44 UTC, tiffwong commented on packages/manager/src/features/StackScripts/Partials/StackScriptTableHead_CMR.tsx
> +    width: '14%',
Prevents the "Total Deploys" column from wrapping at max-width (will still wrap for tablets though)

2020-12-21 22:45 UTC, tiffwong commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
> +              {/* @todo: fix stickiness */}
This is broken in prod but works on the Linode Create flow 💁‍♀️

2020-12-22 16:52 UTC, johnwcallahan requested changes

2020-12-22 16:52 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
> +  const inlineActions = [
Should probably sync up on this pattern with @DevDW after https://github.com/linode/manager/pull/7253 is merged.

2020-12-22 16:52 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
> +      <Tabs defaultIndex={tabValue} onChange={this.handleTabChange}>
You could/should use the new NavTabs pattern here.

2020-12-22 16:52 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
> +        handleCloseDialog();
We lost the success message here. (Be careful with mocking as to not actually publish a StackScript).

2020-12-23 16:57 UTC, DevDW reviewed
Looking good overall -- in addition to what John pointed out, I noticed that when you sort Community StackScripts by name in descending order (and in one or two other cases), the table extends beyond what it should on the right:

<img width="1261" alt="Screen Shot 2020-12-23 at 11 26 56 AM" src="https://user-images.githubusercontent.com/32860776/103020043-c9f77680-4515-11eb-9ca2-a76ac618825c.png">

It seems to be happening because of the length of some StackScript descriptions

2020-12-28 19:41 UTC, tiffwong commented on packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
> +        handleCloseDialog();
I removed it originally since it wasn't being called anywhere. I can put it back but where does it get passed to in order for the message to be displayed?

2021-01-04 16:55 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
> +        handleCloseDialog();
You're right; looks like the success message is displayed based on history state rather than component state: 

https://github.com/linode/manager/blob/01f7d0eb69b07b66e9fe2ce1819c9c5dc99f932e/packages/manager/src/features/StackScripts/StackScriptsLanding_CMR.tsx#L29

Seems like we'll need to refactor a few things to make the success message work. Just created a low-priority followup ticket for this.

2021-01-05 16:11 UTC, Jskobos approved these changes
I left some cleanup but the functionality looks good/unchanged. The searchbar overflows on mobile but that's on develop too

2021-01-05 17:35 UTC, tiffwong commented on packages/manager/src/components/NavTabs/NavTabs.tsx
> +import { matchPath, Redirect, useHistory, useLocation } from 'react-router-dom';
Linter

2021-01-05 17:36 UTC, tiffwong commented on packages/manager/src/components/NavTabs/NavTabs.tsx
> +  if (reactRouterLocation.search !== '') {
Added this to account for search params since it won't detect "?type=category" otherwise

2021-01-08 14:21 UTC, Jskobos commented
@tiffwong I'd ask John if it's ok to dismiss his review and merge this. Maybe hit up @DevDW for an approval too, but I think this is good to go and we ought to get it in.

2021-01-08 15:07 UTC, DevDW approved these changes
It appears that pesky row border misalignment issue surfaces here at medium and small viewports when there's a multi-line description:

<img width="913" alt="Screen Shot 2021-01-08 at 10 02 33 AM" src="https://user-images.githubusercontent.com/32860776/104030305-34a4e500-5199-11eb-87c3-893d60001a6e.png">

That can be addressed in a follow-up PR though

2021-01-08 15:07 UTC, DevDW commented on packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
> -// import StackScriptDetailsHeader from './StackScriptDetailsHeader';
can delete

2021-01-12 15:25 UTC, merged