M3-4751 Change: Add titles to top menu icons
linode/manager pull request #7255
Opened 2020-12-21 21:14 UTC by Jskobos

## Description

- Create a new component, TopMenuIcon, that wraps an icon in a div
and Tooltip (the div is necessary to make the tooltip display).
- Use the new component on all the icons in the top menu (including the user
profile/account dropdown) to display text explaining their purpose.

- Clean up CMR files in the TopMenu and UserMenu

2020-12-21 21:14 UTC, Jskobos commented on packages/manager/src/features/TopMenu/TopMenuIcon.tsx
> +import * as React from 'react';
This is the new component

2020-12-21 22:57 UTC, tiffwong approved these changes

2020-12-22 15:41 UTC, johnwcallahan requested changes
Left a comment/suggestion about `enterDelay`, and requested a change on the menu expansion button. 

New component looks good.

2020-12-22 15:41 UTC, johnwcallahan commented on packages/manager/src/features/TopMenu/TopMenuIcon.tsx
> +    <Tooltip title={title} disableTouchListener enterDelay={0} leaveDelay={0}>
What do you think about an `enterDelay` (and `nextEnterDelay`) of ~1000ms? Clicking through the app, I can see how it'd be annoying for them to immediately pop open every time you go to click on one of the buttons.

2020-12-22 15:41 UTC, johnwcallahan commented on packages/manager/src/features/TopMenu/TopMenu.tsx
> +  const navHoverText = isSideMenuOpen ? 'Collapse menu' : 'Expand menu';
Clicking on this button results in the text changing instantly, which is pretty jarring. 

One idea for a fix is to give `<TopMenuIcon />` a `key` of `navHoverText`, which will force a re-render (and subsequent hidden display) of the tooltip. 

It'll disappear instantly (instead of the fade out animation) but combined with the menu transition, it doesn't bother me personally.

2020-12-22 18:00 UTC, DevDW approved these changes
This looks good 👍  I agree with @johnwcallahan about the enterDelay & enterNextDelay, although I think the sweet spot for those is at 500ms or 750ms.

2020-12-22 18:00 UTC, DevDW commented on packages/manager/src/features/TopMenu/TopMenu.tsx
> +  const navHoverText = isSideMenuOpen ? 'Collapse menu' : 'Expand menu';
Since this is sandwiched between two menus, there could be a bit of confusion for some users. What if we said "sidebar" instead of "menu" here? I think that could eliminate the room for that confusion.

2020-12-23 13:40 UTC, merged

2020-12-23 19:30 UTC, johnwcallahan commented
> Feedback addressed; John is on vacation and this PR is too big to stew for 2 weeks

👍