POC: Paginated API Requests with React-Query (Firewalls)
linode/manager pull request #7277
Opened 2021-01-05 20:30 UTC by Jskobos

## Description

2021-01-05 20:30 UTC, Jskobos commented on packages/manager/src/components/EntityTable/APIPaginatedTable.tsx
> +        const _handleOrderChange = (order: any, orderBy: any) => {
I think we should do this?

2021-01-06 15:56 UTC, Jskobos commented on packages/manager/src/store/preferences/preferences.actions.ts
> +  entity_page_size?: number;
For a follow up I'm thinking about making this `Record<string, number>` and passing in the entity name dynamically so that each entity can have a different saved page size.

2021-01-06 15:57 UTC, Jskobos commented on packages/manager/src/queries/firewalls.ts
> +  results: number;
I think this will have to be a general pattern.

2021-01-06 23:21 UTC, DevDW reviewed
I'm going to test and review this further tomorrow, but one thing I'm noticing so far is that the page isn't being updated after you create a firewall, disable/enable one, etc. unless you refresh the page

2021-01-07 14:42 UTC, johnwcallahan requested changes
The pagination pattern looks good, nice job.

Sort isn't always working, and I noticed this console error:
![Screen Shot 2021-01-07 at 9 37 16 AM](https://user-images.githubusercontent.com/16911484/103905116-32288980-50cc-11eb-9409-46e78ea2fe0e.png)

I'm also unable to get to FW details; haven't worked out why.

2021-01-07 23:56 UTC, DevDW reviewed
Sorting and getting to Firewall details are working for me, but I do get this brief "Not Found" when I try getting to the Firewall details I first click on after initially loading/navigating to Firewalls landing: https://www.loom.com/share/1677073245ed4ec793f0216145ca2e0f

2021-01-13 16:45 UTC, johnwcallahan approved these changes

2021-01-13 17:42 UTC, merged