Restore tooltips to action menus and clean up old CMR files
linode/manager pull request #7279
Opened 2021-01-06 15:44 UTC by DevDW

## Description
Somewhere along the way the past few months we lost tooltip functionality for the new action menus in several cases. This PR is to restore that functionality and clean up old CMR files.

## Type of Change
- Bug fix ('fix', 'repair', 'bug')

## Note to Reviewers
Changes include:
- Adding tooltip prop to `InlineMenuAction.tsx`
- Fixes for files associated with Disks panel in Linode detail > Storage tab

2021-01-11 20:47 UTC, DevDW commented
Going ahead and opening this up for review; please let me know if there are any action menus that should have functional tooltips but don't

2021-01-12 16:01 UTC, Jskobos requested changes
This is pretty close, good work.

1. Linode action menu "Power On" action doesn't respect disabled state (inline or not):
![Screen Shot 2021-01-12 at 10 47 23 AM](https://user-images.githubusercontent.com/1624067/104339164-494cea00-54c5-11eb-86fb-b68d1d49f3b3.png)

2. Speaking of inline and not, the Power On action is repeated so you'll have to fix it in two places. This is why you did the cleanup in your earlier PR, we ought to fix it here too.
2. The hover state of the ? icon needs to be different from the menu background
![Screen Shot 2021-01-12 at 10 48 08 AM](https://user-images.githubusercontent.com/1624067/104339242-608bd780-54c5-11eb-9cd0-d5c807f12d67.png)


3. Optional: the `inVlanContext` stuff makes the Linode action menu much less readable, and it's no longer necessary (maybe someday it will be but that's unclear). It can be removed and cleaned up.

2021-01-12 16:08 UTC, tiffwong approved these changes
Approved pending the changes Jared mentioned

2021-01-12 21:04 UTC, Jskobos approved these changes

2021-01-12 21:19 UTC, merged