Assorted Trello tasks and CMR cleanup
linode/manager pull request #7287
Opened 2021-01-08 20:16 UTC by tiffwong

`SearchLanding` related tasks:
- Remove underline from result labels
- Clean up unused styles and CMR files

`Users` related tasks:
- Add "Users" link to breadcrumb to make it consistent (used to only show up after navigating to the User Permissions tab)
- Remove icon/photo from the breadcrumb
- Disable the save button for username until a change is detected
- Increase the contrast for a disabled email text field 
- Clean up unused styles and CMR files

2021-01-08 21:32 UTC, DevDW approved these changes
LGTM 👍

2021-01-08 21:32 UTC, DevDW commented on packages/manager/src/features/Search/ResultRow.tsx
> +      <TableCell className={classes.labelCell} parentColumn="Label">
I remember having some files in PRs earlier on in CMR where the `parentColumn` props were judged to be unnecessary, what do you think about that in these cases here?

2021-01-08 21:36 UTC, tiffwong commented on packages/manager/src/features/Search/ResultRow.tsx
> +      <TableCell className={classes.labelCell} parentColumn="Label">
I remember seeing that before, I'll go ahead and remove those!

2021-01-13 14:07 UTC, Jskobos requested changes
Looks good, I pushed up some cleanup, and I'm requesting one change to the email input in UserProfile.

2021-01-13 14:07 UTC, Jskobos commented on packages/manager/src/features/Users/UserProfile.tsx
> +            disabled={profileUsername !== originalUsername}
Seems like this should match the profile input (e.g. also disabled if the user hasn't made a change yet)

2021-01-19 15:45 UTC, Jskobos approved these changes

2021-01-19 15:53 UTC, merged