M3-4763: Update URL appropriately when opening, closing, and navigating to Resize, Rebuild, Rescue, & Migrate modals
linode/manager pull request #7301
Opened 2021-01-13 18:30 UTC by DevDW

## Description
Update the URL appropriately when opening, closing, and navigating to Linode Resize, Rebuild, Rescue, & Migrate modals.

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
The following scenarios should work:
1. Navigating to, for example, `/linodes/:id/resize` should still work as it did before.
2. From any tab in Linode details, clicking Resize/Rebuild/Rescue/Migrate should add said action to the URL as a query param (i.e. if you click Resize, "?resize=true" should be appended)
3. Navigating directly to a Linode details tab with a modal indicated to be open (e.g., `/linodes/:id/storage?rebuild=true`) should take you to the appropriate tab with the appropriate modal open.
4. Closing the modal should return you to the appropriate tab and update the URL accordingly.

2021-01-14 14:12 UTC, Jskobos requested changes
This is working well for most cases, and the logic is pretty clean. There's a funny bug where if you're on the detail page but not a tab:
1. Start from Linode landing
2. Click a Linode
3. Open a modal from the action menu
4. Close the modal
5. Observe:
![Screen Shot 2021-01-14 at 9 07 50 AM](https://user-images.githubusercontent.com/1624067/104601276-09624000-5648-11eb-8451-412c48f93a89.png)

2021-01-14 14:12 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +    open: isSubpath('resize') || isQueryParameter('?resize=true'),
There's a method in src/utilities/queryParams called `parseQueryParams` that uses the `qs` library to do this more elegantly. It'll parse a full query string into an object

2021-01-14 14:12 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +      isQueryParameter('?resize=true') ||
See above

2021-01-14 14:12 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +        history.push(`?migrate=true`);
I think `history.push({ search: 'migrate=true' });` is cleaner and safer

2021-01-14 14:12 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +        `/linodes/${match?.params.linodeId}/${match?.params?.subpath}`
`history.replace({ search: '' })` will fix the bug described above. or `{search: undefined}`

2021-01-14 14:13 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +        history.push(`?migrate=true`);
You could make a case for `history.replace()` here too, since opening a modal is maybe-kind of not a navigation event. I don't know

2021-01-14 14:16 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +    open: isSubpath('resize') || isQueryParameter('?resize=true'),
(you pass it `location.search`)

2021-01-14 21:21 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +        history.push(`?migrate=true`);
Thanks, I ended up going with `history.replace()` here since I agree that opening a modal isn't quite a navigation event

2021-01-19 15:46 UTC, Jskobos commented
@DevDW is this ready to go? I don't know if you're planning to drop the /xxx/resize paths in this or a follow-on PR

2021-01-19 15:48 UTC, johnwcallahan approved these changes
Nice work! This is working well. IMO the redirects can be added in a separate PR.

2021-01-19 15:48 UTC, DevDW commented
> @DevDW is this ready to go? I don't know if you're planning to drop the /xxx/resize paths in this or a follow-on PR

Yes, I can take care of the redirects in a follow-up PR

2021-01-19 16:05 UTC, merged