M3-4773: Add 'Plan' column to Linodes table
linode/manager pull request #7306
Opened 2021-01-14 17:48 UTC by DevDW

## Description
Restoring details about Linode plans in the Linodes table has been a commonly-requested piece of feedback after CMR's release. This PR adds a "Plan" column to the Linodes table.

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
The responsive experience is less than ideal at the tablet view currently -- between about 1033px and 960px in width, the table hits a point where you have to scroll to the right to see the action menu. Trying to fix that.

2021-01-15 15:00 UTC, Jskobos requested changes
Looks good, nice improvement. I left some cleanup stuff and some $.02 on the column widths but the only blocking change is the background on the hover state of the header column.

2021-01-15 17:36 UTC, tiffwong approved these changes
Approving based on the feedback Jared left being addressed

2021-01-19 16:57 UTC, johnwcallahan requested changes
UI looks good, see comment about performance.

2021-01-19 16:57 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
> +    types.entities?.find(thisType => thisType.id === type)?.label ?? 'Unknown';
This is pretty inefficient as it's iterating through the `types` per row, per render. It'd be better to do this once somewhere higher in the component tree and pass down the label directly.

2021-01-20 23:13 UTC, johnwcallahan requested changes

2021-01-20 23:13 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
> +  data.forEach(linode => {
This still results in _a lot_ of unnecessary cycles. With 13 Linodes on my account, the inner `find` loop is executed ~1300 times every page load or table re-order.

You'll either have to go higher up the tree, and/or get `types` data into a map somewhere (e.g. `{ 'g6-nanode': "Linode 2GB", ...etc}`). You could do that in the reducer, but since the data shape is changing soon you could maybe go ahead and put types into React Query.

Lots of different options for how to do it, we should just make sure we're wasting a ton of JS cycles every time the page is loaded.

2021-01-25 20:28 UTC, Jskobos approved these changes
This isn't too bad:

![Screen Shot 2021-01-25 at 3 27 35 PM](https://user-images.githubusercontent.com/1624067/105762078-e8d89680-5f21-11eb-942f-2a3eef3b1a0c.png)

2021-01-25 20:28 UTC, Jskobos commented on packages/manager/src/hooks/useTypes.ts
> +export type MappedLinodeType = Record<number, LinodeType>;
Type id's are strings

2021-01-25 20:28 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
> +
I don't know if it would be any more efficient but you could do the attaching right here so you don't have to do it inside the render function

2021-01-25 20:48 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
> +
yes this actually brings the `console.count` number down quite a bit 👌

2021-01-25 21:13 UTC, merged