Add redirects for /resize, /rebuild, /rescue, and /migrate
linode/manager pull request #7314
Opened 2021-01-19 19:39 UTC by DevDW

## Description
A follow-up to https://github.com/linode/manager/pull/7301 that adds redirects for /resize, /rebuild, etc. to `?resize=true`, `?rebuild=true`, etc.

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Investigate & clean-up console errors

2021-01-20 15:07 UTC, Jskobos reviewed
I left a refactor suggestion to avoid conditionally rendering redirects. Another part of this PR should be to deactivate the route handling in LinodeDetailHeader (this is still WIP so probably you already know that).

2021-01-20 15:07 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
> +            {isSubpath('resize') ? (
I think you're conditionally adding these redirect because otherwise the last one always holds. The [docs](https://reactrouter.com/web/api/Redirect) are not entirely clear on this but I think a better way to handle these is to wrap them in a `<Switch>`. You also have the url already available, which lets you make things terser:

```
<Switch>
              <Redirect from={`${url}/resize`} to={`${url}?resize=true`} />
               ...
</Switch>
```

2021-01-20 15:07 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
> +  // Several routes that used to have dedicated pages (e.g. /resize, /rescue)
See below, this isn't needed. I think there's an alternative approach where you can match the path and history.replace directly (without routes or a switch) but I'm not sure how that's any better in this case 🤷

2021-01-21 17:24 UTC, DevDW commented
Going ahead an opening this up; may have to get to the bottom of the `Failed prop type: Invalid prop 'open' of type 'string' supplied to 'ForwardRef(Dialog)', expected 'boolean'.` console error in a later PR

2021-01-21 17:37 UTC, Jskobos commented
> Going ahead an opening this up; may have to get to the bottom of the `Failed prop type: Invalid prop 'open' of type 'string' supplied to 'ForwardRef(Dialog)', expected 'boolean'.` console error in a later PR

`typeof queryParams.resize // ==> 'string'`

2021-01-21 17:42 UTC, Jskobos requested changes
This is very close, sorry to request more stuff. The blocking issue here is that navigating directly to /linode/id/?migrate=true doesn't open the modal. This is because the check on line 95 of MigrateLinode fails.

Please also remove the first clause of these conditions, since we no longer support /resize etc. paths explicitly:

```
open: isSubpath('rescue') || queryParams.rescue,
```

2021-01-21 21:53 UTC, Jskobos approved these changes

2021-01-21 21:53 UTC, Jskobos commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
> +  const linode = useExtendedLinode(linodeID) || _linode;
Good solution. Do we need the _linode prop at all now? What purpose does it serve?

2021-01-21 21:53 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +    open: Boolean(queryParams.resize),
Anyone who does this deserves what they get imo but pointing it out anyway:

![Screen Shot 2021-01-21 at 4 50 43 PM](https://user-images.githubusercontent.com/1624067/105417080-0e575e80-5c09-11eb-80f6-94ad1165fff6.png)

2021-01-22 03:51 UTC, ndukatz approved these changes
Works as expected. This is great!

2021-01-22 14:31 UTC, Jskobos commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
> +  const linode = useExtendedLinode(linodeID) || _linode;
Changed my mind about this, this bug is a symptom of a slightly deeper issue that we're discussing offline

2021-01-22 20:23 UTC, merged