M3-4830: Breadcrumb styles
linode/manager pull request #7329
Opened 2021-01-20 23:46 UTC by tiffwong

## Description

Decrease font size of breadcrumbs and change color

## Note to Reviewers

Please check all the different usages of the breadcrumb, ie. in the `LandingHeader` component and editable breadcrumbs

2021-01-22 13:51 UTC, Jskobos requested changes
Looks much nicer this way. In some places--I noticed on LKE detail--the error state has disappeared in this PR (try to rename your cluster to a blank string). On Linodes detail, the error state is present but looks funky (technically not new to this PR but we should fix it):

![Screen Shot 2021-01-22 at 8 48 13 AM](https://user-images.githubusercontent.com/1624067/105499161-10fc9700-5c8f-11eb-89bb-1be3d0cea07e.png)

2021-01-25 18:43 UTC, ndukatz commented
the edit looks way better. I did notice that if the text is long, it starts you at the end instead of the beginning of the text. This is most likely working as designed but I just wanted to make sure 
<img width="435" alt="Screen Shot 2021-01-25 at 1 41 29 PM" src="https://user-images.githubusercontent.com/66748958/105750892-487b7580-5f13-11eb-98e6-d6af9e6aee22.png">
.

2021-01-25 18:53 UTC, ndukatz commented
> Looks much nicer this way. In some places--I noticed on LKE detail--the error state has disappeared in this PR (try to rename your cluster to a blank string). On Linodes detail, the error state is present but looks funky (technically not new to this PR but we should fix it):
> 
> ![Screen Shot 2021-01-22 at 8 48 13 AM](https://user-images.githubusercontent.com/1624067/105499161-10fc9700-5c8f-11eb-89bb-1be3d0cea07e.png)

I am still seeing this same behavior on kubernetes page. the error text flashes for a second then disappears. too fast for a user to see.

2021-01-25 22:26 UTC, DevDW reviewed
Looking good overall so far -- should the StackScript and Domain labels be editable inline as it is for Linode labels and the others?

Also, the error needs some responsive styling for smaller viewports:

<img width="497" alt="Screen Shot 2021-01-25 at 5 24 56 PM" src="https://user-images.githubusercontent.com/32860776/105773755-6a382500-5f32-11eb-9a18-fb65aae16b0a.png">

2021-01-26 16:00 UTC, Jskobos approved these changes
I agree with the mobile styling fixes and making Domains etc. editable (also OBJ buckets). Otherwise looks good to go, going to approve pending those changes.

2021-01-27 20:34 UTC, ndukatz approved these changes
Looks really good to me now. great job!

2021-01-27 20:42 UTC, tiffwong commented
@ndukatz @DevDW @Jskobos thanks for the feedback!

If the label is long, I think starting at the end is fine and there is currently no way to update a bucket name

2021-01-28 17:57 UTC, Jskobos reviewed
Everything is working, I left one comment that should be addressed but otherwise good to go.

2021-01-28 17:57 UTC, Jskobos commented on packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
> +      .updateDomain({ domainId: domain.id, domain: label })
updateDomain is already included in this component via useDomains (line 55). No need to use the wrapper you've added.

2021-01-28 20:56 UTC, merged