M3-4850: Backups CTA Adjustments
linode/manager pull request #7342
Opened 2021-01-26 21:27 UTC by DevDW

## Description
Remove the "Enable Backups" button in banner and use user preferences instead of local storage to dismiss banner. And CMR cleanup -- `BackupsCTA_CMR.tsx` --> `BackupsCTA.tsx`

## Type of Change
- Non breaking change ('update', 'change')

2021-01-27 14:06 UTC, Jskobos approved these changes

2021-01-27 22:02 UTC, tiffwong commented on packages/manager/src/features/Backups/BackupsCTA.tsx
>    createStyles({
You can use `makeStyles`/`useStyles` here instead

2021-01-27 22:09 UTC, tiffwong approved these changes
Other than the one cleanup item I mentioned, everything else looks good!

2021-01-28 17:41 UTC, johnwcallahan requested changes
Overall this looks much cleaner, although it doesn't handle the case when the preference isn't found in either user preferences or local storage (e.g. new users). In that case I'm unable to see the CTA. The PreferenceToggle defaults to the first option you give it if it's not specified in preferences/localStorage, so in this case `dismissed` is defaulted to `true`. 

Also the text and X button should be aligned with each other (centered in the panel). 

![Screen Shot 2021-01-28 at 12 34 11 PM](https://user-images.githubusercontent.com/16911484/106177160-29285680-6166-11eb-8118-614d7b574bae.png)

2021-01-29 14:55 UTC, johnwcallahan reviewed
Thanks for the user preferences change, that's working really well.

The text still looks a bit low to me, though I'm not sure what the problem is. Maybe @tiffwong could weigh in here.
![Screen Shot 2021-01-29 at 9 54 21 AM](https://user-images.githubusercontent.com/16911484/106290111-166e5a00-6218-11eb-8091-2422ba939ced.png)

2021-02-02 21:16 UTC, tiffwong commented
@johnwcallahan I checked and it is aligned so maybe its an optical illusion?

2021-02-02 22:29 UTC, johnwcallahan commented
@tiffwong maybe something with line-height? The text sits lower than the "X" button, which seems perfectly aligned.
![Screen Shot 2021-02-02 at 5 27 25 PM](https://user-images.githubusercontent.com/16911484/106671194-1a81db00-657c-11eb-8f91-fd9c48bbb121.png)

2021-02-02 22:49 UTC, tiffwong commented
@johnwcallahan I removed some of the text to compare the "X" closer to full height letters like "k" and "l" and it looks even to me

<img width="313" alt="Screen Shot 2021-02-02 at 5 46 26 PM" src="https://user-images.githubusercontent.com/7692354/106672775-a432a800-657e-11eb-93af-24c6b2d05973.png">
<img width="341" alt="Screen Shot 2021-02-02 at 5 44 47 PM" src="https://user-images.githubusercontent.com/7692354/106672904-d6dca080-657e-11eb-8ead-9fb5f9910673.png">

2021-02-03 19:38 UTC, merged