M3-4778: Add "Edit" button on StackScript Detail page
linode/manager pull request #7344
Opened 2021-01-27 19:10 UTC by DevDW

## Description
Add "Edit" button on StackScript Detail page; minor updates to associated test & a function name change in `StackScripts.tsx`.

## Type of Change
- Non breaking change ('update', 'change')

## Note to Reviewers
Open to other ideas for the placement of the "Edit" button, but the upper right is consistent with what we have for Billing Contact, for example

2021-01-27 22:28 UTC, tiffwong commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        justifyContent: 'flex-end'
Instead of targeting the button here, it's better to apply a class directly on the button

Also instead of `justifyContent: 'flex-end'`, use `minWidth: 'fit-content'` instead. Otherwise, the button will look off center when click and hold the button

2021-01-27 22:30 UTC, tiffwong requested changes
I left a few cleanup items but I have a few more questions. 

Is the "Edit" button supposed to show up for Community StackScripts?

Additionally, the name of the StackScript is no longer aligned with the other content:
<img width="1260" alt="Screen Shot 2021-01-27 at 5 24 54 PM" src="https://user-images.githubusercontent.com/7692354/106062326-9f747c80-60c4-11eb-9282-f1de841fff1d.png">

2021-01-29 22:38 UTC, DevDW commented
> Is the "Edit" button supposed to show up for Community StackScripts?

My initial thought is that it shouldn't, but I'll get confirmation on that

2021-02-01 17:12 UTC, Jskobos commented
> > Is the "Edit" button supposed to show up for Community StackScripts?
> 
> My initial thought is that it shouldn't, but I'll get confirmation on that

It definitely should not. Only show Edit if the current user has the ability to edit the StackScript. This might require checking grants for Account scripts, since there are per-user grants for each script.

2021-02-01 20:12 UTC, Jskobos requested changes

2021-02-01 20:12 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        {!is_public ||
This doesn't quite work, since you can publish your own stackscripts and subsequently edit them.

2021-02-01 20:12 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        {!is_public ||
You may have to pass down a `type='community'` or `type='account'` to this component, I think Tiffany is running into something very similar so maybe discuss with her.

2021-02-01 23:21 UTC, DevDW commented
@Jskobos I made an attempt at passing it down via props from `StackScripts.tsx` --> `StackScriptsDetail.tsx` --> `StackScript.tsx`, but it wasn't quite fruitful. I commented out some of the code associated with that attempt so you can get an idea of what I was trying. 

On the other hand, in `StackScriptRow.tsx`, I persisted the `category` on the `History` object, and was able to use that in `StackScript.tsx`. With that approach it seems to work if a user navigates to a StackScript from the Account or Community tabs, but it wouldn't work if a user went to a direct URL.

2021-02-02 18:53 UTC, Jskobos commented on packages/manager/src/queries/accountUsers.ts
> +import { User, getUsers } from '@linode/api-v4/lib/account';
Query should live in src/queries/users.ts

2021-02-02 18:53 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +  if (!isRestrictedUser && accountUsersData) {
Some of this is duplicative, there's already a canUserModifyAccountStackScript function (imported in this file ^^^ ) that will help with these calculations. Probably something like this will work:

```
const showTheButton = isRestrictedUser ? canModifyAccountStackScript(...) : newFunctionCalledIsAccountStackScript(users, stackscript.username)

```

2021-02-02 18:53 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +  if (!isRestrictedUser && accountUsersData) {
From StackScript detail, I don't think a restricted user can possibly know if he can't edit it because he has read_only access or because it's from someone else's account (I mean they can figure this out but there's nothing in the response or elsewhere in the API that will help here)

2021-02-02 18:53 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +  if (!isRestrictedUser && accountUsersData) {
...so probably ix-nay on the disabled button

2021-02-02 18:55 UTC, johnwcallahan commented on packages/manager/src/components/StackScript/StackScript.tsx
> +  const { isRestrictedUser, stackScriptGrants } = useSelector(
Could the `useAccountManagement` hook be used here instead of this custom selector?

2021-02-02 21:05 UTC, Jskobos approved these changes
looks good 👍

2021-02-02 21:18 UTC, tiffwong approved these changes

2021-02-03 19:42 UTC, merged