M3-4880 Fix: Disk selection when opening Rebuild from /linodes
linode/manager pull request #7345
Opened 2021-01-27 19:55 UTC by Jskobos

This was a hooks dependency issue. The dialog state was being
reset when the dialog opened, as intended, but since only [open]
was included in the deps array, stale values of the device map
were used. In addition, when the dialog was opened without /disks
having been previously requested, the completed request wouldn't trigger
the effect.

Used the usePrevious hook to run the reset logic whenever `open`
changes _and_ the calculated deviceMap is different from the previous
value. This involves a deep object comparison on every render while
the dialog is open, but it seems ok in practice.

2021-01-27 22:47 UTC, johnwcallahan requested changes
I haven't fully comprehended the problem/solution here, but I believe I'm still seeing the bug by opening my Linode's Details page from a refresh and then selecting "Rescue".

2021-01-28 14:22 UTC, Jskobos commented
> I haven't fully comprehended the problem/solution here, but I believe I'm still seeing the bug by opening my Linode's Details page from a refresh and then selecting "Rescue".

I can't reproduce the bug anywhere on Linode detail...even on develop, so I thought it was just a context bug. Can you please screenshot what you're seeing? Might be something related that needs to be fixed

2021-01-28 15:00 UTC, johnwcallahan commented
@Jskobos on this branch, this is what I see when from the Linode Landing page I click the hamburger -> Rescue:

![Screen Shot 2021-01-28 at 9 55 15 AM](https://user-images.githubusercontent.com/16911484/106156035-0dfe1c80-614f-11eb-900f-a4ced48072f6.png)

It's most of the assignments, but not all.

If I go to that Linode's Details page, refresh the page, click the hamburger -> Rescue, I only see two of the assignments: 

![Screen Shot 2021-01-28 at 9 55 28 AM](https://user-images.githubusercontent.com/16911484/106156135-2cfcae80-614f-11eb-9850-4eaacb9e2e38.png)

2021-01-29 18:47 UTC, johnwcallahan approved these changes
I guess a side effect of using placeholderData is that there's a double /regions request until we move all the region-dependent stuff to RQ, which seems acceptable to me (it's disk cached).

2021-01-29 18:51 UTC, johnwcallahan commented
Left this review on the wrong PR ^.

2021-02-01 19:51 UTC, tiffwong approved these changes

2021-02-01 19:55 UTC, merged