Firewalls: update submission of IP addresses
linode/manager pull request #7350
Opened 2021-01-28 20:16 UTC by johnwcallahan

A change made in the API means that an empty address list is not accepted. Therefore if there are no ipv6 addresses for example, we don't include the ipv6 field at all.

I also made `ports` optional since that was changed in the API as well.

**To test,** use the dev API and check FW rule submission/editing thoroughly.

2021-01-29 14:13 UTC, Jskobos requested changes
![Screen Shot 2021-01-29 at 9 08 44 AM](https://user-images.githubusercontent.com/1624067/106285022-f50a6f80-6211-11eb-9933-9a7327f3adfe.png)

Did we ever resolve what was supposed to happen here? In any case looks like sending an empty object for addresses won't work. Probably should delete the field from the payload if it's empty (though the error message makes it seem like the API isn't handling it properly either).

2021-01-29 21:52 UTC, johnwcallahan commented
@Jskobos good catch. Addresses are now required, so I pushed up that change.

2021-02-02 20:33 UTC, Jskobos approved these changes
Sorry I forgot to re-review. I can still get to the bad place by selecting "IP/Netmask", leaving the text field blank, and submitting the form. I'm going to approve because honestly that's valid, but wanted to raise the issue.

2021-02-03 15:53 UTC, DevDW approved these changes

2021-02-03 20:31 UTC, merged