M3-4854: Fix StackScripts search
linode/manager pull request #7355
Opened 2021-01-29 15:57 UTC by tiffwong

Removing the type from `querySearch` fixes the search redirecting to /accounts

2021-02-01 15:20 UTC, Jskobos requested changes

2021-02-01 15:20 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
Clicking on one of my stackscripts takes me to something like `http://localhost:3000/stackscripts/type=community&query=username%3Aprod-test-004` which doesn't lead anywhere

2021-02-01 16:35 UTC, tiffwong commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
Is this from clicking on your stackscript from /accounts?

2021-02-01 17:51 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
Clicking on my username from StackScript detail

2021-02-01 18:22 UTC, tiffwong commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
What's the behavior supposed to be if you click on a username (that's not yours) from a community stackscript?

2021-02-01 18:26 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
Should go back to the relevant landing page with the search query set to that username. So that url above needs to be `/stackscripts/community/?query=username....`

2021-02-01 19:46 UTC, DevDW approved these changes
Search is working now 👌

2021-02-01 19:47 UTC, Jskobos commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
OK that wasn't a good example...if you click on your own script or the username of someone on your account, it has to go to `/account?query=username...`.

2021-02-01 20:09 UTC, tiffwong commented on packages/manager/src/components/StackScript/StackScript.tsx
> +        <Link to={`/stackscripts/${queryString}`} data-qa-community-stack-link>
When I tried the search query for my username on /accounts, there's no results 🤔 

Also I think the original redirected to /community, what's the best way to get the category type?

2021-02-02 20:27 UTC, Jskobos approved these changes

2021-02-02 20:29 UTC, merged