M3-4891: Remove sidebar upload panel in Object Storage
linode/manager pull request #7384
Opened 2021-02-08 19:10 UTC by tiffwong

Remove icon and prevent the upload panel from being displayed in the sidebar for all viewports

2021-02-09 14:10 UTC, Jskobos approved these changes
I liked the icon 😢 ...this looks good though, tables have margin against the edge of the viewport down to about 960 px then they're flush, the drop zone is using this style too and it looks a bit weird having the dotted line right at the edge of the screen.

2021-02-09 17:25 UTC, johnwcallahan requested changes
There needs to be a max height with overflow set to scroll. Currently the upload box takes over the whole page:
![Screen Shot 2021-02-09 at 12 22 01 PM](https://user-images.githubusercontent.com/16911484/107402151-a9897880-6ad1-11eb-843a-b353582644d4.png)

I think there are some other things we need to consider here too, as the layout kind of breaks in general when uploading stuff:
![Screen Shot 2021-02-09 at 12 24 15 PM](https://user-images.githubusercontent.com/16911484/107402323-d3429f80-6ad1-11eb-9165-bed9321e0332.png)

2021-02-09 17:26 UTC, johnwcallahan commented
> I think there are some other things we need to consider here too, as the layout kind of breaks in general when uploading stuff

E.g. we should consider moving the size and status icons to the left side (by the filename) and left-align the Cancel/Overwrite buttons instead of centering. Let's sync up with Matthew on this.

2021-02-15 15:10 UTC, johnwcallahan approved these changes

2021-02-15 15:11 UTC, merged