M3-4839: Notifications section in Notifications drawer follow-up
linode/manager pull request #7386
Opened 2021-02-08 20:41 UTC by DevDW

## Description
Follow-up to https://github.com/linode/manager/pull/7364 to improve formatting of Notification section items and more closely match the mockup:

![Mockup_02](https://user-images.githubusercontent.com/32860776/107278390-bea7ce00-6a23-11eb-9456-264ce1840b8b.png)

## Type of Change
- Non breaking change ('update', 'change')

2021-02-09 15:40 UTC, Jskobos approved these changes
Looks good. The drawer still needs to close when a notification is clicked, that can be done in a separate PR.

2021-02-09 15:48 UTC, johnwcallahan requested changes
Layout, messaging, etc. looks great. Still a crashing bug to address and some smaller code things to clean up.

2021-02-09 15:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +    (notification.type === 'maintenance' ||
You defined a nice `isMaintenanceNotification` variable in RenderNotification above. I'd turn that into a function, move it somewhere else, and use it here too.

2021-02-09 15:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
>      notification.entity.type === 'linode'
`notification.entity && notification.entity.type === 'linode'` can be shortened to `notification.entity?.type === 'linode`. (Appears in multiple places).

If `notification.entity` doesn't exist, `notification.entity?.type` will be `undefined` and thus the comparison will be false.

2021-02-09 15:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +        ? notification!.body!.replace(
It's almost always a bad idea to use the assertion operator. This is currently resulting in a crashing bug on test account 1 because it is currently receiving this notification, which doesn't have a body:

<img width="451" alt="Screen Shot 2021-02-09 at 10 39 24 AM" src="https://user-images.githubusercontent.com/16911484/107387823-32e57e80-6ac3-11eb-8db5-f647988780f9.png">

2021-02-09 15:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +    ['maintenance', 'maintenance_scheduled', 'migration_pending'].includes(
Here's another instance of the `isMaintenanceNotification` logic you could reuse.

2021-02-09 15:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +  if (severity === 'minor') {
I think this is redundant... at this point we're going to return `minor` anyway, so why do the additional `if` check?

2021-02-09 15:50 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +  if (severity === 'minor') {
Meant to leave an additional comment for this function: I know it's based on old code but we should add a few unit tests to verify the pathways are working out like we expect. Also please add some comments... the code is easy to read but the _why_ is unclear.

2021-02-09 18:24 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +        ? notification!.body!.replace(
It was a migration_scheduled notification that was crashing it, not a ticket_important notification as I first indicated.

<img width="221" alt="Screen Shot 2021-02-09 at 1 24 01 PM" src="https://user-images.githubusercontent.com/16911484/107409353-13a61b80-6ada-11eb-87a6-63374c3ba5ee.png">

2021-02-09 18:48 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +// For communicative purposes in the UI, in some cases we want to upgrade or downgrade the severity of certain notifications compared to what the API returns. Example: the API has ticket_abuse as hav
Thanks, this comment made it clearer.

Do we actually want to downgrade emergency maintenance tickets to `major`, though? That's a departure from what's currently in develop, which I think is more appropriate:

![Screen Shot 2021-02-09 at 1 45 01 PM](https://user-images.githubusercontent.com/16911484/107411891-0f2f3200-6add-11eb-8d37-16dc86d57826.png)

If that's the case, all this function is doing is upgrading ticket_abuse to `critical`, so the function body can be something like:

```ts
return type === 'ticket_abuse' ? 'critical' : severity;
```

In that case we should rename the function since it's misleading (makes me think it's _reducing_ the severity level instead of the intent, which is to serve as a reducer). 

Also, the return type should be `NotificationSeverity` instead of a plain string.

2021-02-09 20:05 UTC, DevDW commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +// For communicative purposes in the UI, in some cases we want to upgrade or downgrade the severity of certain notifications compared to what the API returns. Example: the API has ticket_abuse as hav
I may be mistaken, but during the last demo I thought Chris mentioned that Linode maintenance alerts shouldn't be so scary. If that shouldn't apply to the emergency maintenance (is that just `maintenance_pending` types?) notices I'll get this fixed

2021-02-10 14:43 UTC, johnwcallahan approved these changes
Thanks for making these changes, the adjustments look good. I have a handful of remaining questions we can discuss with the team offline.

2021-02-10 15:15 UTC, merged