M3-4897: Transfers Received & Sent tables
linode/manager pull request #7395
Opened 2021-02-13 01:37 UTC by DevDW

## Description
This PR adds the Transfers Received and Transfers Sent tables to the Transfers landing page.

As of the initial opening of this PR, it also adds the Transfers Pending table. I added entity transfers to React Query. Open to feedback on that and whether the partial departure from the M3-4896 ticket description is disagreeable or not.

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Unit tests
- [ ] Adjustments based on feedback

2021-02-15 22:40 UTC, DevDW commented
Going ahead and removing the WIP label here. A bit of accidental scope creep  -- I started to get into the Cancel Transfer modal stuff, but that's a separate ticket. Since I started some of that work, I grabbed that ticket, and commented out some of the stuff I did already in this PR and put "Cancel" text as a placeholder where the inline action will be.

2021-02-16 14:01 UTC, Jskobos requested changes
Really good work on this. I left a bunch of opinionated cleanup stuff that you can ignore, the only thing I think we have to change is handling of large numbers of transfers (pagination or whatnot). It'll probably be a while until someone has enough transfers for this to matter, but who knows what people will do.

Other general UI feedback:
- It's nice that the entities column scales with entity types but I wonder if we really want rows that thick (down the road):
![Screen Shot 2021-02-16 at 8 35 12 AM](https://user-images.githubusercontent.com/1624067/108072345-c4f60580-7034-11eb-92b8-ba2439bb3454.png)

- I'd like to think about setting explicit widths for all of these columns so that they line up across tables even when the columns themselves differ, it would look a little cleaner.
- I suggest this below but maybe a global loading/error state rather than three tables mirroring state based on the same request. I'm not as confident about this though.

2021-02-17 14:51 UTC, Jskobos approved these changes
Looks good pending the commenting stuff we discussed offline. One thing is that a Pending transfer also appears in sent transfers. You can maybe filter those out really quickly here, but the filtering we're talking about for using separate requests can handle this in the longer term.

2021-02-17 15:30 UTC, johnwcallahan approved these changes
Good work; left some feedback which should be addressed before release, but we should go ahead and merge this PR so we can connect the flow.

2021-02-17 15:30 UTC, johnwcallahan commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +              <TableCell key="transfer-token-table-header-token">
Just curious: why the `keys` on TableCells?

2021-02-17 15:30 UTC, johnwcallahan commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +              {transferTypeIsPending || transferTypeIsSent ? (
`<Hidden />` props are booleans, so you should do something like this to simplify the ternaries here:

![Screen Shot 2021-02-17 at 10 15 13 AM](https://user-images.githubusercontent.com/16911484/108224615-17a0f180-7109-11eb-81b3-0c211d21fb51.png)

2021-02-17 15:30 UTC, johnwcallahan commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +        {transferTypeIsPending ? (
See note below; you can remove the duplication and ternary by giving the condition (`transferTypeIsPending`) to `xsDown` on the Hidden component.

2021-02-17 15:30 UTC, johnwcallahan commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +  const renderTransferRow = (transfer: EntityTransfer, idx: number) => {
This function is being called _a lot_ (e.g. once per row for every keystroke in the "Receive a Transfer" input up top. This specific example can be solved other ways... @Jskobos maybe `ConfirmTransferDialog` should be moved to TransferControls so we don't have to keep track of `token` state on the Landing page.)

But in any case, this should probably be its own memoized Function Component (instead of a plain function). I'd go so far as to give it flat props (`token="" created="" linodes={}` etc) so that it can be memoized efficiently.

2021-02-17 15:35 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +  const renderTransferRow = (transfer: EntityTransfer, idx: number) => {
I thought about that, figured we might need that state on the landing page for whatever reason. But it seems not, so I can move it down a level

2021-02-17 15:58 UTC, DevDW commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +              <TableCell key="transfer-token-table-header-token">
these are artifacts from when I was mapping over an array of headers to generate these `<TableCell />`'s -- can remove them in the follow-up

2021-02-17 16:02 UTC, merged