M3-4899: Transfer Details modal
linode/manager pull request #7414
Opened 2021-02-18 14:55 UTC by tiffwong

Opens when the user clicks a token ID from the landing page tables

2021-02-18 19:32 UTC, Jskobos requested changes
Looks good, need to fix a missing `key` console error. 

What do you think about borrowing the logic used in the accept transfer modal to also display the time until expiry (if the transfer is pending) in human-readable format ("This transfer will expire in 16 hours (<timestamp>)")?

2021-02-18 19:32 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
> +          return <Typography data-test-id={idx}>{entity}</Typography>;
I think it's `data-testid` if it's for working with React Testing Library.

2021-02-18 19:32 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
> +        })}
Also need a key in here

2021-02-18 21:50 UTC, DevDW commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
> +        <div className={classes.label}>Transfer Token: </div>
I think this `<div>` might be causing this console error:

<img width="687" alt="Screen Shot 2021-02-18 at 4 47 43 PM" src="https://user-images.githubusercontent.com/32860776/108425876-16ef8480-7209-11eb-8af9-0a663de2cc51.png">

2021-02-19 19:18 UTC, Jskobos approved these changes

2021-02-22 15:33 UTC, DevDW approved these changes

2021-02-22 15:48 UTC, merged