Cancel Transfer modal follow-up
linode/manager pull request #7416
Opened 2021-02-18 19:54 UTC by DevDW

## Description
Ensure that the Transfers Pending & Transfers Sent tables update appropriately after a transfer is canceled; this is done by refreshing the `entity-transfers` query.

## Type of Change
- Non breaking change ('update', 'change')

2021-02-18 20:25 UTC, Jskobos requested changes

2021-02-18 20:25 UTC, Jskobos commented on packages/manager/src/queries/entityTransfers.ts
> +  }, mutationHandlers(queryKey, 'token'));
I don't think you actually need the mutation handlers here. The cancelTransfer method, unlike most of our PUT requests, doesn't return anything. The mutation handler is always getting `{}`, which doesn't have a `token`, so nothing is going to happen.

It's an open question whether you want to have a separate query for this or not, you could alternatively import the `queryClient` directly in the consumer and invalidate the query in your existing .then() block. Or you could keep this, which handles the error states etc., and just not set any of these handlers.

2021-02-18 20:25 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
> +    cancelTransfer(token, {
You may not end up keeping this (see my comments in the query definition). If you do, you have to handle two things:

1. you need a .catch() block even if it doesn't do anything (by which I mean `.catch(_ => null)`), or else an error will be uncaught and thus reported to Sentry (I only figured this part out this morning)
2. the error state persists across modals, so if you get an error then close the dialog and open it for another transfer, the error is still there.

On balance I'd say all of this argues in favor of doing normal JS client/then/catch stuff and just calling `queryClient.invalidateQueries()` in the .then() block. But you could make an argument either way, you can go with whichever way you think works out better.

2021-02-18 21:30 UTC, Jskobos approved these changes
Looks good now, I pushed up a small change I meant to do on my PR as well but forgot about.

2021-02-19 19:58 UTC, tiffwong approved these changes

2021-02-19 21:07 UTC, merged