Transfers Pending/Received/Sent follow-up
linode/manager pull request #7418
Opened 2021-02-18 23:54 UTC by DevDW

## Description
Follow-up to https://github.com/linode/manager/pull/7395 addressing feedback:
- Expand Transfers table accordion by default only if the table is not empty
- Clean up `key`'s on `<TableCell />`'s where appropriate
- Make use of `<Hidden />`'s boolean props to simplify conditional logic
- Make `RenderTransferRow` into its own memoized component

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Pagination

2021-02-19 23:00 UTC, DevDW commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +      sentTransfersLoading ? (
The purpose of showing this loading spinner if any transfer query is loading is to prevent the situation where a populated table is collapsed because the transfersCount isn't > 0 yet because the query didn't complete

2021-02-19 23:02 UTC, DevDW commented
Still looking into fixing the pagination, not sure yet what's not connected properly

2021-02-22 13:50 UTC, Jskobos reviewed
This is pretty close.

The problem is that you're using `data.entityTransfers.etc.length` to determine whether or not to display the pagination controls. (I commented inline on the actual place where this is happening). The process ends up being:
1. Request data from the API with a page_size of 25
2. Get back a list of 25 things (data.length === 25)
3. Tell TransferTable that if data.length > page_size (i.e. if 25 > 25) show the pagination controls.

You already have the information you need in `data.results`, need to grab that and use it for the comparison.

2021-02-22 13:50 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +  // Fetch the Sent Transfers
This duplication and all the proppiness below is understandable. I'm wondering though if it would work to move a lot of this down to TransfersTable (not generally a great idea but it might help here) since the only thing that's going to be different between the three tables is the X-Filter.

So in the table, you'd use usePagination and useEntityTransfers, then accept a filter from the parent (can be an object like `{ is_sender: true}` or whatever. Do all the pagination and whatnot from inside the table.

It will definitely be cleaner this way, but will it work? I have no idea!

2021-02-22 13:50 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +      sentTransfersLoading ? (
This is fine but if you do what I'm suggesting above you'll have to play around with an extra instance of the query (`const { isLoading } = useEntityTransfersQuery()` or something maybe) or ditch the concept altogether.

2021-02-22 13:50 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +      {transfersCount > pageSize ? (
This is the misconnected wire. Need the total length of the data here (data.results).

2021-02-22 13:50 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
>            fixedSize
Should this be fixedSize though? the create tables are the way they are to avoid things getting complicated in a tabbed searchable table, but we should check with Matthew to see if it's better to show or hide the page size controls here.

2021-02-22 13:54 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +  // Fetch the Sent Transfers
Or don't pass the filter and instead use the existing `transferType` to infer what the filter ought to be.

2021-02-22 22:10 UTC, DevDW commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
>            fixedSize
Checked with Matthew and John, consensus was to give it the normal treatment so I have the page size controls displaying now

2021-02-22 22:23 UTC, DevDW commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +  // Fetch the Sent Transfers
@Jskobos I tried this approach and it works, but the issue with tables that are populated being collapsed upon page load occurred again, and having three separate loading spinners for each table to get around that issue didn't look great to me. I think using the current pattern is the lesser evil compared to that, but maybe there's another way around it. I stashed my changes using that approach in case we want to revisit it.

2021-02-23 15:10 UTC, Jskobos requested changes
Still needs a rebase (most of the commit history is stuff that's already present in develop from the feature branch).

2021-02-23 15:10 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +      handlePageSizeChange: paginationReceivedTransfers.handlePageSizeChange
John pointed this out to me, the url this sends to the api is pretty funny: `Request URL: https://api.linode.com/v4beta/account/entity-transfers?page=1&page_size=25&handlePageChange=function+(newPage)+%7B%0A++++++++setPage(newPage)%3B%0A++++%7D` 

No need to send functions through the query. All it needs to care about is the page and the page size.

2021-02-23 15:10 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
> +  transferTypeIsPending?: boolean;
Bit odd to have 2 separate props for this. Just pass in the type. Also these are typed as `boolean | undefined` but they're always `boolean`

2021-02-23 15:10 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +    transferType,
This is a `string` but it ought to be an enum

2021-02-23 16:22 UTC, johnwcallahan commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +  // Fetch the Sent Transfers
Re: duplication. It might be good to combine the usePagination and useEntityTransfer queries to reduce this duplication.

2021-02-24 17:19 UTC, Jskobos reviewed
Pagination is working well now. Few things:

1. The pagination controls are outside the accordion, and are visible after a table is collapsed.
2. One quirk of having a global loading state is that if I change the page size, all three tables disappear for a bit even though only one of them is changing. Not a dealbreaker but there may be a way to juggle dataLastUpdated and isLoading to get around it.
3. The usePagination hook takes an optional preferenceKey argument that might be nice to use here so that each table's size is remembered.

2021-02-24 17:19 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> +        {results > pageSize ? (
It's not quite as simple as moving this up to inside the `<Accordion>` but somehow these have to go away when the accordion is collapsed.

2021-02-25 19:06 UTC, DevDW commented
I moved the pagination footer inside the accordion and partially fixed the UI issue with it, but the last row still has a chunk that looks like a partial row right below it:

<img width="1255" alt="Screen Shot 2021-02-25 at 1 24 08 PM" src="https://user-images.githubusercontent.com/32860776/109203696-7c47f600-7772-11eb-84d7-45d6815289a8.png">

@tiffwong any insights on how to fix this?

2021-02-25 22:05 UTC, Jskobos commented on packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
> +  const transfersTablePreferenceKey = 'entity-transfers-tables';
This could be specific to each table. Use case: I set the "received" table to page_size 50 because I'm weird; the next time I view the page, all tables will have page_size: 50.

2021-02-26 14:30 UTC, Jskobos commented
> I moved the pagination footer inside the accordion and partially fixed the UI issue with it, but the last row still has a chunk that looks like a partial row right below it:
> 
> <img alt="Screen Shot 2021-02-25 at 1 24 08 PM" width="1255" src="https://user-images.githubusercontent.com/32860776/109203696-7c47f600-7772-11eb-84d7-45d6815289a8.png">
> 
> @tiffwong any insights on how to fix this?

As a start I'd try merging in develop now that the new pagination controls have been merged. might fix it by itself

2021-02-26 16:28 UTC, tiffwong approved these changes

2021-02-26 16:45 UTC, Jskobos approved these changes

2021-02-26 18:05 UTC, merged