Marketplace Add: Q1 Partner Release
linode/manager pull request #7422
Opened 2021-02-19 17:55 UTC by hmorris3293

## Description
This PR adds the fakespec & svgs for our Q1 Partner release for Marketplace

## Type of Change
 * Non breaking change ('update', 'change')
 
## Note to Reviewers
Full release for prod will need to be coordinated with Marketing.

2021-02-19 19:40 UTC, Jskobos requested changes
What about Tomcat and Aberrit Node.js? There are scripts for them but no info here. Have they been pushed to the next release?

2021-02-19 19:40 UTC, Jskobos commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +    description: `Host multiple sites on a single server while managing apps, firewall, databases, backups, system users, cron jobs, SSL and email–  all in an intuitive interface.`,
This is the same description as serverwand above.

2021-02-19 19:40 UTC, Jskobos commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +    name: 'Cyberpanel',
Needs to be capitalized.

2021-02-19 19:45 UTC, hmorris3293 commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +    description: `Host multiple sites on a single server while managing apps, firewall, databases, backups, system users, cron jobs, SSL and email–  all in an intuitive interface.`,
fixed!

2021-02-19 19:46 UTC, hmorris3293 commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +    name: 'Cyberpanel',
fixed!

2021-02-19 19:47 UTC, hmorris3293 commented
@Jskobos Aberrit NodeJS & Tomcat did not make it into this release, so it is just the 4 apps

2021-02-19 19:48 UTC, Jskobos approved these changes

2021-02-19 20:08 UTC, Jskobos commented
The new apps have color icons used in the card view, they should be B&W

2021-02-22 16:35 UTC, tiffwong approved these changes

2021-02-22 16:40 UTC, merged