Update types and factories for VLAN Adjustments
linode/manager pull request #7439
Opened 2021-02-24 21:41 UTC by DevDW

## Description
Update the types and factories as per the new VLAN API adjustments.

## Type of Change]
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Get mock Configs populating in Linode Configs table

2021-03-01 18:44 UTC, DevDW commented
Going ahead and removing the WIP label.

With regards to the hard-coded IDs in `linodeConfigs.ts` and `serverHandlers.ts`, I tried using `Factory.each((i) => i)` but it was either causing a TS error or mismatching the data in such a way that the Network Interfaces column was empty

2021-03-02 14:41 UTC, Jskobos requested changes
- The payload for creating a Linode is different in the new system, the types and schema will have to be updated
- It will no longer be possible to PUT/POST/DELETE at networking/vlans, those should be removed
- Interface payloads and response values only have 3 fields: label, purpose, and ipam_address. Everything else is internal and not returned by the API
- Config schemas will need to be updated

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/factories/linodeInterfaces.ts
> +export const linodeInterfacesFactory = Factory.Sync.makeFactory<LinodeInterface>(
All of these endpoints are going away, I don't think it's necessary to add a factory for them. (related, all JS client types and methods for /interfaces requests should be deleted as part of this PR).

2021-03-02 14:41 UTC, Jskobos commented on packages/api-v4/src/linodes/types.ts
> +export type InterfacePurpose = 'public' | 'vlan' | 'internal' | 'multivlan';
internal and multivlan are not available for customers to use, they probably shouldn't be included or documented here.

2021-03-02 14:41 UTC, Jskobos commented on packages/api-v4/src/linodes/types.ts
>  export type InterfaceSlot = Record<string, InterfaceBody>; // e.g. { "eth0": { "id": 111 }}
This comment is no longer correct

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/factories/linodeConfigs.ts
> +      devum: 1,
This is an internal field

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/factories/linodeConfigs.ts
> +      create_dt: createDate,
this is a db field

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/factories/linodeConfigs.ts
> +      id: 3,
this will not come back from the API

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/mocks/serverHandlers.ts
> +  rest.get('*/instances/*/interfaces', async (req, res, ctx) => {
Remove please

2021-03-02 14:41 UTC, Jskobos commented on packages/api-v4/src/linodes/types.ts
>  export type InterfaceSlot = Record<string, InterfaceBody>; // e.g. { "eth0": { "id": 111 }}
(and InterfaceSlot is a bad name for the new pattern; and it's an array not a Record)

2021-03-02 14:41 UTC, Jskobos commented on packages/manager/src/factories/linodeConfigs.ts
> +      devum: 1,
(it's also "devnum")

2021-03-02 14:48 UTC, Jskobos commented on packages/manager/src/factories/linodeConfigs.ts
> +      id: 3,
the shape needs to be updated as well, it's no longer { eth0: {}...etc } it's an array.

2021-03-03 21:22 UTC, Jskobos commented on packages/api-v4/src/linodes/linodes.schema.ts
> +        /^\d{3}\.\d{3}\.\d{1,3}\.\d{1,3}$/,
The spec says the ipam_address has to be a range, so this won't work. It's also a risky way to validate IP addresses. I think the ipaddr.js library is already part of the JS client build, you can use ipaddr.parseCIDR here (I think, see firewalls.schema.ts for examples).

2021-03-09 13:53 UTC, Jskobos approved these changes

2021-03-10 02:08 UTC, johnwcallahan approved these changes

2021-03-10 16:24 UTC, merged