Add: Policy toggles to Firewall rule tables
linode/manager pull request #7453
Opened 2021-03-03 19:02 UTC by Jskobos

## Description

2021-03-03 22:31 UTC, johnwcallahan approved these changes
Functionality works well, design ongoing.

2021-03-03 22:31 UTC, johnwcallahan commented on packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
> +    paddingLeft: 4,
Minor: to my eye this needs to be 3px to be aligned with the actions above .

2021-03-04 15:14 UTC, tiffwong approved these changes

2021-03-04 15:23 UTC, johnwcallahan requested changes
Two small things.

2021-03-04 15:23 UTC, johnwcallahan commented on packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
> +      content: '',
@tiffwong this needs to be `content: '""',` (trips me up every time).

2021-03-04 15:23 UTC, johnwcallahan commented on packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
> +      traffic not covered by the inbound rules listed above.
"covered by the {category} rules listed above."

2021-03-04 16:48 UTC, johnwcallahan approved these changes

2021-03-04 16:52 UTC, merged