M3-4947 Add: status banners on all /support pages
linode/manager pull request #7496
Opened 2021-03-15 21:10 UTC by Jskobos

## Description

- Refactor routing of all /support links so that they share a common
rendered root.
- Add banners to the aforementioned root for all incidents

## Note to Reviewers

The banners are dismissible but the dismissals aren't saved anywhere (the banners come back if you reload the page). I'm waiting to use the notifications hooks in #7482 once that's been merged.

You can test with the mocks, or there are some real scheduled maintenance events atm too.

2021-03-16 14:26 UTC, Jskobos commented on packages/manager/src/features/Help/HelpLanding.tsx
> +  render(): JSX.Element {
I think we need to disable this rule, this is going to get very tedious

2021-03-16 15:59 UTC, johnwcallahan reviewed
<img width="538" alt="Screen Shot 2021-03-16 at 11 57 27 AM" src="https://user-images.githubusercontent.com/16911484/111340255-da1f7d80-864e-11eb-8776-7fafde5cbc51.png">

The font size looks a little big especially compared to existing banners. 

Also, we should only show active incidents here (we'll show maintenance in the upcoming "Maintenance" page, which we don't have tickets for yet).

2021-03-16 15:59 UTC, johnwcallahan commented on packages/manager/src/features/Help/StatusBanners.tsx
> +        dangerouslySetInnerHTML={{ __html: sanitizeHTML(message) }}
Do status body's have HTML?

2021-03-16 15:59 UTC, johnwcallahan commented on packages/manager/src/features/Help/StatusBanners.tsx
> +  const handleDismiss = () => {
I'd either just inline this or use useCallback.

2021-03-16 18:32 UTC, DevDW approved these changes
I agree with John regarding the font size for these banners, but the rest looks good to me. Approved pending the limiting of the incidents displayed to only active ones.

2021-03-16 19:37 UTC, Jskobos commented on packages/manager/src/features/Help/StatusBanners.tsx
> +        dangerouslySetInnerHTML={{ __html: sanitizeHTML(message) }}
apparently so, links to "open a support ticket" are common for unresolved incidents

2021-03-16 20:23 UTC, Jskobos commented on packages/manager/src/features/Help/StatusBanners.tsx
> +        dangerouslySetInnerHTML={{ __html: sanitizeHTML(message) }}
We could do the find-and-replace thing to avoid the dangerous stuff, but we don't control the banners, raw html looks horrible in them, and I think the status page api is a pretty safe source. Opted for innerHTML on balance but please feel free to argue the other side.

2021-03-16 20:24 UTC, Jskobos commented on packages/manager/src/features/Help/StatusBanners.tsx
> +  const handleDismiss = () => {
this is just a placeholder, the logic is built into the dismissibleNotifications hook so I'll just kill this when that piece is ready to pull in

2021-03-16 21:20 UTC, johnwcallahan commented on packages/manager/src/features/Help/StatusBanners.tsx
> +        dangerouslySetInnerHTML={{ __html: sanitizeHTML(message) }}
Yeah, that seems OK to me.

2021-03-16 21:23 UTC, johnwcallahan requested changes
Just found one more thing: we probably shouldn't display incident updates with a status of "postmortem":

<img width="1301" alt="Screen Shot 2021-03-16 at 5 16 42 PM" src="https://user-images.githubusercontent.com/16911484/111381382-056c9180-867c-11eb-890c-3897f9eb676e.png">

In fact, maybe we should apply a (liberal) character limit just in case. Maybe an ellipsis in brackets that takes you to status.linode.com? `[...]`

Also, as a follow-on, it'd be awesome if we could make the support ticket links smarter (rather than refreshing the whole app.) We could even pre-fill them. That's a really low-priority bonus, though.

2021-03-17 14:20 UTC, tiffwong approved these changes

2021-03-18 14:13 UTC, johnwcallahan approved these changes

2021-03-18 14:14 UTC, merged