M3-4981: Add Google as TPA provider
linode/manager pull request #7511
Opened 2021-03-18 17:34 UTC by tiffwong

Waiting on login before merging/release

2021-03-29 18:36 UTC, Jskobos requested changes
Looking good, some things need to be cleared up and/or cleaned up. And I think dark mode is a bit off:

![Screen Shot 2021-03-29 at 2 29 47 PM](https://user-images.githubusercontent.com/1624067/112882658-38ab1980-909b-11eb-9f32-3923457ef06e.png)

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyContent.tsx
> +    const index = providers.findIndex((provider) => provider.name === 'google');
This can be a `.filter()` to skip the multiple steps business.

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
> +            {thirdPartyEnabled && <ThirdParty authType={authType} />}
these names are confusing me 😕

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyContent.tsx
> +                disabled={thirdPartyEnabled}
I know there's color issues, but it's hard to tell from looking that the thing is actually disabled. If "Linode" is my auth type and I click on GitHub, I get a modal. If "Google" is my auth type and I click on GitHub, nothing happens and it isn't visually clear (only the cursor is different?) how the situation has changed.

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyContent.tsx
> +                {!thirdPartyEnabled && props.authType === 'password' && (
This check is redundant, if authType is password then mechanically thirdPartyEnabled is false

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyContent.tsx
> +              {!thirdPartyEnabled && props.authType === 'password' && (
Same here

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyDialog.tsx
> +      title="Change Log-in Method?"
I like log in (verb) and login (noun) but ymmv

2021-03-29 18:36 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyContent.tsx
> +    const index = providers.findIndex((provider) => provider.name === 'google');
You could even make the flag a `string[]` instead of a boolean, then do `providers.filter(thisProvider => flags.tpaProviders.includes(thisProvider.name))` or something similar.

2021-04-29 21:56 UTC, DevDW reviewed
Looking good so far, noticed a typo

2021-04-29 21:56 UTC, DevDW commented on packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
> +          availible in{' '}
"available"

2021-05-03 15:46 UTC, Jskobos approved these changes
Looks good, I left some cleanup stuff but nothing blocking.

2021-05-03 15:46 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
> +  return provider === undefined
Maybe add a comment here to clarify what's happening (you're using the fact that if `provider` is `undefined` it means they just clicked on "Linode" but it's a bit implicit. Another option would be to default `provider` to `linode` throughout this file and use it that way.

2021-05-03 15:46 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
> +        Change login
Capital L maybe

2021-05-03 15:46 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
> +                setProvider(undefined);
Maybe you could set provider to `linode` in this case to avoid the undefined stuff in TPADialog

2021-05-03 15:46 UTC, Jskobos commented on packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
> +                setProvider(undefined);
Another option would be to make a manual provider type for Linode so that you're not handling it differently (this button and grid code is mostly repetitive and there are few `currentProvider.displayName ?? 'username and password'` things that might be possible to clean up this way.

2021-05-04 14:41 UTC, johnwcallahan approved these changes
Good work on this. Let's merge it so we can test the whole flow in dev. There are a couple of things to address before release, including whether or not the confirmation dialog minWidth change was intended to be global, as well as the hardcoding of "Google" in the description.

Also, please create a tech-story ticket to add thorough unit tests.

2021-05-04 14:41 UTC, johnwcallahan commented on packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
> +    '& .MuiPaper-root': {
These are global changes. Are they intended only for the TPA confirmation dialogs, or for all of them app-wide?

2021-05-04 14:41 UTC, johnwcallahan commented on packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
> +        Change login
It does look a little inconsistent, but this is actually the direction that we want to move... only entity types (as proper nouns) being capitalized.

2021-05-04 14:41 UTC, johnwcallahan commented on packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
> +          You can use your Linode credentials or another provider such as Google
At least for the release, we shouldn't hardcode "Google" here, since we're releasing without the feature flag enabled for Google.

2021-05-04 14:44 UTC, merged