M3-4941: Attach a VLAN section in Linode Create flow
linode/manager pull request #7516
Opened 2021-03-18 19:43 UTC by DevDW

## Description
Create new `AttachVLAN` component that uses `InterfaceSelect.tsx` and appears above the Add-ons in the Linode Create flow

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Include VLAN data w/ Linode creation payload (as opposed to the "Attach VLAN" button in the designs)
- [ ] Helper text

2021-03-18 21:27 UTC, DevDW commented
I'll go ahead and open this up for review, but a few things are still being worked on (helper text finalization, error handling, tighten things up). The VLAN label and IPAM address get added to the Linode Create payload now.

2021-03-19 15:40 UTC, Jskobos requested changes
This is really good, the approach is exactly the right idea. Can't check the error handling yet obviously but the payload is correct.

I think we need to be a little more clever with the payload, though. Having a single select is better for UX, but if I choose to attach a VLAN, the `interfaces` array has only a single object, which means (I think) that the VLAN will end up attached to eth0 and the Linode will not be available on the public internet. We should essentially `[...publicInterfaceObject, ...this.state.interfaces]` or similar so that we always send a public interface in the payload.

2021-03-22 16:49 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
> +        <AttachVLAN
This will need to be behind a feature flag, using the showVlans logic you've removed.

2021-03-22 16:51 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
> +          {
This is better, but it introduces a new problem: it will always send 2 interfaces, even if the user doesn't choose a vlan.

2021-03-22 19:13 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
> +      interfaces = [];
This isn't necessary, if you submit just the defaultPublicInterface you end up with the same result (i.e. a config where eth0 is a public interface).

2021-03-23 13:03 UTC, Jskobos approved these changes

2021-03-23 13:08 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
> +                isClearable
This got overwritten in the merge resolution I think

2021-03-23 21:34 UTC, tiffwong requested changes
The label for IPAM Address wraps when there's plenty of space so I'd recommend adding `whiteSpace: nowrap` to the label
<img width="558" alt="Screen Shot 2021-03-23 at 5 34 06 PM" src="https://user-images.githubusercontent.com/7692354/112221567-fba7d880-8bfd-11eb-90c4-a3b157f1e32a.png">

The width of the input boxes should also be increased for mobile
<img width="646" alt="Screen Shot 2021-03-23 at 5 32 19 PM" src="https://user-images.githubusercontent.com/7692354/112221369-bbe0f100-8bfd-11eb-94aa-ea91f8e62468.png">

2021-03-25 20:15 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
> +    [theme.breakpoints.down(1280)]: {
Replace `1280` with `'md'` just in case we change our breakpoints in the future

2021-03-25 20:15 UTC, tiffwong approved these changes
I left one cleanup item but everything else looks good!

2021-03-25 22:46 UTC, merged