M3-5014 Fix: IP sharing bug
linode/manager pull request #7520
Opened 2021-03-22 21:10 UTC by Jskobos

## Description

IP sharing (and transfer) rely on having all of a user's Linodes in order to display the ip addresses as options. For large customers, this means that if you land directly on a detail page, and open the sharing modal, your options will be limited (or nonexistent), since only a single request for Linodes has been made.

I refactored the old code in IPSharing so that we could use useReduxLoad; a longer-term solution will be to use a query and request all Linodes in the selected region instead. There was some questionable code in there so I thought the refactor was worth it. I also removed IPSharingPanel, which afaict is an older, unused version of the same file.

2021-03-24 15:49 UTC, DevDW approved these changes
The functionality all seems to be working as intended 👍 . It appears that the hover state of the "Add IP Address" button got thrown off a bit compared to Prod though:

Prod:
<img width="263" alt="Screen Shot 2021-03-24 at 11 45 58 AM" src="https://user-images.githubusercontent.com/32860776/112340273-c4d1d100-8c96-11eb-95d2-a057661db76f.png">

This branch:
<img width="263" alt="Screen Shot 2021-03-24 at 11 46 20 AM" src="https://user-images.githubusercontent.com/32860776/112340292-ca2f1b80-8c96-11eb-8e70-43d7ad9077dc.png">

2021-03-25 13:52 UTC, johnwcallahan approved these changes
Looks good, left a few additional refactoring comments.

2021-03-25 13:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    const newIPsToShare = clone(ipsToShare);
I feel like this should use the function state updater pattern like `onIPDelete` uses, if nothing else but for consistency, but also since the new value is based on the old state value.

2021-03-25 13:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
>      if (ipIdx === undefined) {
I'd be in favor of removing this (hopefully) unnecessary check and trust TS and our code.

2021-03-25 13:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +      ipsToShare.filter((ip: string) => ip !== selectIPText)
Obviously this is carryover, but it's pretty weird that we treat `selectIPText` like an IP and then strip it out at the end. Shouldn't `selectIPText` just be a placeholder in the Select component instead of a selectable option?

2021-03-25 13:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
>            'Unable to complete request at this time.'
We should change this to something more stylistically aligned with our modern error messages.

2021-03-25 21:12 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +        <Grid item className={classes.removeCont}>
If you add `sm={2}` here, it won't wrap as early

2021-03-25 21:13 UTC, tiffwong approved these changes
Looks good! Left one cleanup item but otherwise, LGTM

2021-03-26 12:52 UTC, johnwcallahan requested changes
One more quick thing.

2021-03-26 12:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                  {remainingChoices('').length > 1 && (
I'm pretty sure this should be `>= 1` now... currently if you've got only two choices left, you can only select one.

2021-03-26 13:13 UTC, johnwcallahan approved these changes

2021-03-26 13:31 UTC, merged