M3-4985: StackScripts Details breadcrumb alignment
linode/manager pull request #7563
Opened 2021-04-06 15:48 UTC by tiffwong

Shift the username up 1px so that it's aligned with "StackScripts" and the title

2021-04-08 13:06 UTC, johnwcallahan requested changes
Thanks for the refactor – really nice work. Left a few minor comments; I think the one about `useEffect` is the only one required before merge.

2021-04-08 13:06 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
> +  }, [props.match.params]);
This is causing an extra function call/request since props.match.params is an object and the equality check doesn't do what we want.

If you destructure stackScriptId above the useEffect definition, then include `stackScriptId` as a dependency (instead of props.match.params) it should do what you want.

2021-04-08 13:06 UTC, johnwcallahan commented on packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
> +  }))
While we're at it we could refactor this to make use of e.g. `useProfile` hooks instead of containers. You don't have to do this now, though.. could open up a tech ticket.

2021-04-08 15:38 UTC, DevDW reviewed
Looking good overall; in addition to John's feedback, I also noticed that very long StackScript names push the Docs & "Deploy New Linode" and the Edit buttons to new lines:

<img width="1202" alt="Screen Shot 2021-04-08 at 11 28 27 AM" src="https://user-images.githubusercontent.com/32860776/114055462-cbe40c00-985e-11eb-8728-ad99b6aeb1b7.png">

"Deploy New Linode" is right up against the main content section, so that probably calls for some bottom spacing, and the Edit button has a left indentation

2021-04-15 13:07 UTC, johnwcallahan approved these changes
Great work on this, thanks for getting those little refactors in.

2021-04-15 14:13 UTC, DevDW approved these changes
🚢

2021-04-15 14:26 UTC, merged