M3-5045: Images Create page
linode/manager pull request #7575
Opened 2021-04-09 22:23 UTC by DevDW

## Description
- Create new "Images / Create" page at `/images/create`
- Make "/images*" to "/images" redirect & Create button behavior conditional on `machineImagesEnabled`

Will rebase once https://github.com/linode/manager/pull/7569 is merged to clean up repeated changes and bring in the newer fixes that are currently in `develop`.

## Type of Change
- Non breaking change ('update', 'change')

## To-Do:
- [ ] Tabs
- [ ] Cleanup

2021-04-13 13:26 UTC, Jskobos requested changes
Good work on this, I think the MainContent routing should be fixed (unless I'm missing something), otherwise most of what I've left is cleanup.

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
> +    if (!this.props.selectedLinode && prevProps.selectedLinode) {
This stuff is spooky and we should avoid it if we can. I know it's preexisting, though I can't remember why we (I) decided to manage drawer state in ImagesLanding instead of the actual drawer. See below

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const defaultCreateTabState = {
I'm not sure about this! Looks like machine images use a different API endpoint, but label and description are still part of the payload. Bundling them together with selected disk makes the update methods more complicated and makes it harder to reuse the state in the other tab.

A simple improvement would be to make these 3 separate state variables. 2 strings and 1 number isn't too many to juggle. Another possibility would be to manage Linode and disk selection entirely inside the CreateImageTab component, since that's the only place where they'll be used. That would also let you get rid of the componentDidUpdate stuff I mentioned above.

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
> +  withImages(),
Are these injected props being used in here? It's possible but I can't really see where

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
> +    availableImages: profile?.restricted
This looks like a bad name from way back when. It's a list of Linodes, not Images.

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  }, [route, props.location.pathname]);
What is this doing?

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const [route, setRoute] = React.useState<string>('');
This `route` variable is only used as a dependency in the useEffect below. What is its purpose?

2021-04-13 13:26 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +    setRoute(props.location.pathname.replace('/create/', ''));
Same comment, when I delete all of the setRoute stuff I can't see a change in behavior. Which case is this handling?

2021-04-13 21:15 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
> +  withImages(),
The `createImage` method is coming from this. I commented this line out and creation failed because `createImage` was undefined

2021-04-13 21:34 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +    setRoute(props.location.pathname.replace('/create/', ''));
I was using `ObjectStorageLanding.tsx` as a model and thought these pieces were necessary, but it seems they aren't. The behavior looks unchanged without them to me as well. I removed these pieces

2021-04-14 17:53 UTC, Jskobos approved these changes

2021-04-14 21:26 UTC, johnwcallahan requested changes
Good work, this routing stuff can be gnarly.

2021-04-14 21:26 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const tabs = [
We've been using the `<NavTabs />` pattern, which would clean up this component quite a bit. See Profile.tsx for example usage. I believe that would also fix the following bug: 

1. Go to `/images/create/random-bad-path`
2. Observe: it _doesn't_ redirect you to the URL of the first tab.

2021-04-14 21:26 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
> +        <ImageCreate />
Followup: check with Matthew and the docs team, but we should probably put a Docs link here like we usually do.

2021-04-14 21:26 UTC, johnwcallahan commented on packages/manager/src/features/Images/index.tsx
> +      </Switch>
We should add a redirect so that junk URLs take you back to the landing page, (like "/images/bad-path")

```tsx
<Redirect to="/images" />
```

2021-04-14 21:26 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +      title: 'Create Image',
I'm not super sold on this tab name. Seems weird to have the breadcrumb read "Images / Create" and the first tab to be "Create Image" (seems redundant). Make "From Disk"? @tiffwong thoughts here? Check with Matthew as well.

2021-04-15 17:39 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const tabs = [
`<NavTabs />` works wonderfully, thanks for bringing this to my attention

2021-04-15 18:47 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
> +      width: '70%',
Did 70% instead of 75% because it looked a bit better to me

2021-04-15 18:48 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const tabs: NavTab[] = [
I landed on using "From Linode" and "From Uploaded Source" after balancing the feedback from prep & from Slack, happy to continue brainstorming and tweaking though, especially if anyone has strong objections.

2021-04-15 18:51 UTC, DevDW commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +    if (account.data?.capabilities.includes('Machine Images')) {
This change means you'll need to test the Create page using dev until the feature is rolled out on prod more broadly

2021-04-16 12:46 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const tabs: NavTab[] = [
I don't think "From Uploaded Source" works. I think "Upload Image" worked well, because that's exactly what you'll be doing on the tab.

My proposal:

`Disk Image | Upload Image`

and the URLs should be:

`images/create/disk`
`images/create/upload`

2021-04-16 12:46 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const handleSetLabel = (e: React.ChangeEvent<HTMLInputElement>) => {
Why are `handleSetLabel` and `handleSetDescription` operating in this component (the parent) rather than in CreateImageTab? Is that just holdover from the old ImagesDrawer component? Once everything is merged and things are cleaned up, we should make sure this state is in the most appropriate component.

2021-04-16 13:55 UTC, Jskobos commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const handleSetLabel = (e: React.ChangeEvent<HTMLInputElement>) => {
The idea was we would share state between the tabs, since those fields are the same regardless of flow. In #7586 I saw this maybe didn't work out as well as I thought, we'll have to see what happens.

2021-04-16 13:56 UTC, DevDW commented on packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
> +  const handleSetLabel = (e: React.ChangeEvent<HTMLInputElement>) => {
I oscillated between moving them down a level and moving them back up between 5 and 6 commits ago, but I'll move them back down in a follow-up to this PR

2021-04-16 14:07 UTC, johnwcallahan approved these changes

2021-04-16 14:13 UTC, merged