M3-5046 upload image tab
linode/manager pull request #7586
Opened 2021-04-14 21:20 UTC by Jskobos

## Description

Branched off of #7575, will rebase and open for review once that's in.

2021-04-16 15:42 UTC, Jskobos commented on packages/manager/src/store/image/image.requests.ts
> +export const uploadImage = createRequestThunk(uploadImageActions, (payload) =>
I'm not happy to be adding more things using the old pattern, but trying to query-ify this on top of everything else is asking for trouble.

2021-04-19 17:25 UTC, tiffwong approved these changes

2021-04-19 21:27 UTC, johnwcallahan requested changes
Only blocking thing is clearing the error state on submit. I'll try to take another pass once @matthewbartholomew's updates are in.

2021-04-19 21:27 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImageUpload.tsx
> +    setSubmitting(true);
Should clear errors here too.

2021-04-19 21:27 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImageUpload.tsx
> +  const [submitting, setSubmitting] = React.useState(false);
Maybe make a comment that we should RQ-ify this later.

2021-04-19 21:27 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImageUpload.tsx
> +    <Paper className={classes.container}>
The Papers between tabs are different widths. I kind of like the more narrow "Upload Image" paper, but either way we ought to be consistent. @matthewbartholomew @tiffwong  which should we go with here?

2021-04-19 21:27 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +    window.setTimeout(() => setUploadURL(undefined), 500);
Is this that trick we use to keep the URL form changing while the modal is closing? Might be good to make this is own function for reusability and ease of reading.

2021-04-20 16:20 UTC, johnwcallahan approved these changes

2021-04-20 16:20 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImageUploadSuccessDialog.tsx
>                  Copy Curl Request
I saw @matthewbartholomew mention that the capitalization is still under review; personally I think either works as long as they're consistent.

2021-04-20 16:20 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImageUpload.tsx
> +      <div style={{ width: '100%' }}>
Minor/not exactly related: Kinda seems like a lot of space between the text and this button (same on the "Capture Image" tab)... maybe 16px instead of 32px?

2021-04-20 19:06 UTC, merged