Feedback: Machine Images table row updates
linode/manager pull request #7588
Opened 2021-04-15 17:25 UTC by tiffwong

- Always expose actions for pending Images
- Update "Cancel" to "Cancel Upload"
- Remove progress bar for pending images and have the corresponding size be "N/A"

2021-04-15 17:45 UTC, Jskobos commented on packages/manager/src/features/Images/ImageRow.tsx
> +        {isImageUpdating(event) ? 'N/A' : `${size} MB`}
I'd prefer "Pending" here, and it should show if the status is 'pending_upload' or 'creating'.

2021-04-15 18:52 UTC, Jskobos requested changes
Removing the progress bar also removed the progress display, which shows the percent complete (we do this on Linodes too). That should be brought back imo.

Also, a "pending_upload" image doesn't trigger the logic in isImageUpdating, which is event-based. So those images still show a size of 0, which should be Pending instead.

2021-04-19 12:56 UTC, Jskobos approved these changes

2021-04-20 15:24 UTC, DevDW approved these changes

2021-04-20 15:33 UTC, merged