M3-5062: VLAN Refinements in Linode Create flow
linode/manager pull request #7605
Opened 2021-04-22 18:22 UTC by DevDW

## Description
When VLANs are not available for the selected region, show the "Attach a VLAN" section in the Linode Create flow instead of hiding it but:
- Display notice with regions listed where VLANs are available
- Disable text fields

2021-04-22 21:28 UTC, tiffwong approved these changes

2021-04-23 12:30 UTC, Jskobos requested changes
Works well, we need to fix the hard-coding but otherwise good to go. Also, though, we discussed in sprint planning what to do about the case where you haven't selected a region yet. Right now if you scroll straight to the VLAN input you get a message saying "VLANs aren't supported in the selected region", which could be a bit confusing because there is no selected region. Please add a simple `const message = selectedRegionID ? <what you already have> : 'You must select a region before adding a VLAN'` or similar.

2021-04-23 12:30 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
> +                  VLAN instances are not available in the selected region.
We shouldn't hard code this. If a datacenter gets VLAN support, we'd have to release to include it in the list. You already have a list of regions that support VLANs, from where `regionSupportsVLANS` is calculated (might want to move that down into this component). There's also a method in src/utilities to join a list of region IDs into a comma separated list. I've been meaning to add support for semicolons, which you've used here and are a good idea. An optional `separator = ','` argument would be a nice addition to the helper function.

2021-04-23 21:54 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
> +                  VLAN instances are not available in the selected region.
Good point about the hard-coding, thank you. Not sure if this was the precise file you had in mind, but the placement seems fair:

https://github.com/linode/manager/blob/e78c98b5bd49c52752eb5d35926b15212f5fe76a/packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.ts#L14

2021-04-26 12:46 UTC, Jskobos reviewed
Thanks for the updates, this is good now pending a few cleanup items.

2021-04-26 12:46 UTC, Jskobos commented on packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.test.ts
> +  it('should return a list with items containing commas as semicolon-separated', () => {
I'm being pedantic here, sorry: "It should use the provided delimiter" etc; it isn't using a semicolon because the items have commas, it's because the test case is passing `;`

2021-04-26 12:46 UTC, Jskobos commented on packages/manager/src/utilities/doesRegionSupportVLANs.ts
> +export const regionsWithVLANs = (regionsData: Region[] | ExtendedRegion[]) => {
Appreciate the precision but unless you're using a field specific to ExtendedRegion I don't think you need to include it in the types.

2021-04-26 12:46 UTC, Jskobos commented on packages/manager/src/utilities/doesRegionSupportVLANs.ts
> +export const regionsWithVLANs = (regionsData: Region[] | ExtendedRegion[]) => {
(because it's a superset of Region, and TS generally doesn't care in its checking that the types match precisely, only that everything is compatible)

2021-04-26 12:46 UTC, Jskobos commented on packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.ts
> +    if (separator) {
This would be terser as an optional argument with a default value, `..., separator: string = ',')`

2021-04-26 12:46 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
> +  const warningMessage = selectedRegion
What do you think about including the second sentence (the list of regions) no matter what? So this conditional only handles the first sentence. That way, for impulsive users who get to the bottom of the view, they know that they have to select a region and also what regions they can choose from. Otherwise you might have to scroll back and forth twice.

2021-04-26 17:12 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
> +  const warningMessage = selectedRegion
Agreed; I pushed that change up

2021-04-27 13:10 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
> +            <Notice warning>
I know this is the pattern we use for GPUs, but this banner is much more visible. It really jumps out and makes you think something is wrong if you've scrolled down without selecting a region, or if you've selected an unsupported region.

![Screen Shot 2021-04-27 at 9 03 38 AM](https://user-images.githubusercontent.com/16911484/116245932-7e5d0f80-a737-11eb-9d44-1578fe20baab.png)


@tiffwong @matthewbartholomew what are your thoughts on making this text-only (instead of a `<Notice />` component? And/or updating the text to be less demanding? ("You **must** select a region...")

At the very least it should be consistent with GPUs, which currently does not have bolded text (not sure if it should be bolded or not).
![Screen Shot 2021-04-27 at 9 04 22 AM](https://user-images.githubusercontent.com/16911484/116246791-46a29780-a738-11eb-96a3-e006603b3761.png)

2021-04-30 13:56 UTC, merged