change status from disk imagize to capturing image
linode/manager pull request #7609
Opened 2021-04-23 14:29 UTC by HanaXu

## Description
Changes status transition text from `Disk Imagize` to `Capturing Image`
## How to test
1. Go to `Images` and create/capture an image.
2. The status in `Images` should be `Creating`
3. Go to `Linodes`, the linode status you captured the image from should be `Capturing image`

2021-04-26 12:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/transitions.ts
> +const transitionActionMap = {
You could provide a little type safety by typing this as `Partial<Record<EventAction, string>>`.

2021-04-26 12:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/transitions.ts
> +  if (recentEvent && transitionActionMap[recentEvent.action]) {
I think there's a good opportunity here for a simple unit test or two in `transitions.test.ts` to verify this new behavior.

2021-04-26 12:52 UTC, johnwcallahan commented on packages/manager/src/features/linodes/transitions.ts
> +  if (recentEvent && transitionAction.includes(recentEvent?.action)) {
I feel this function is still ripe with opportunity for refactor, and I'm not totally convinced this change makes things much clearer (still have the duplication of `.replace()`, and now `capitalizeAllWords` is duplicated).

Now that we have the mapping of actions to labels, maybe we could expand it to inlude for the actions in `transitionAction` and remove the `transitionAction` logic altogether (i.e. this whole `if` block).

2021-04-27 12:53 UTC, Jskobos requested changes
I think the refactor looks good. It looks like `buildLinodeCloneTransitionText` isn't used anywhere in the app anymore, it can probably be deleted.

The only required changes are the event renames and the test cleanup.

2021-04-27 12:53 UTC, Jskobos commented on packages/manager/src/features/linodes/transitions.ts
> +  disk_resize: 'Resizing',
This should be "Disk Resizing" or similar, there's a separate plan resize event that can happen.

2021-04-27 12:53 UTC, Jskobos commented on packages/manager/src/features/linodes/transitions.ts
> +  disk_duplicate: 'Duplicating',
Same here, Disk Duplicating so it doesn't get confused with Cloning

2021-04-27 12:53 UTC, Jskobos commented on packages/manager/src/features/linodes/transitions.test.ts
> +    expect(
You could use a factory here, 
```
import { eventFactory } from 'src/factories/events'; 
const mockEvent = linodeFactory.build({ action: 'disk_imagize', ...<whatever specific fields you need>})
```

2021-04-27 12:53 UTC, Jskobos commented on packages/manager/src/features/linodes/transitions.test.ts
> +  it('should use present tense if an event is a transition event and capitalize it', () => {
Present continuous tense if we're being pedantic 🙃

2021-04-27 15:45 UTC, Jskobos approved these changes

2021-04-27 15:48 UTC, johnwcallahan approved these changes
Nice job on the refactor 👍 

Left a few minor/optional notes on the tests, but I think this is good to go.

2021-04-27 15:48 UTC, johnwcallahan commented on packages/manager/src/features/linodes/transitions.test.ts
>    it('should remove "linode" from the event and capitalize it', () => {
I don't think this first test is providing value anymore since the "linode" string removal logic is no longer present.

2021-04-27 15:48 UTC, johnwcallahan commented on packages/manager/src/features/linodes/transitions.test.ts
> +      percent_complete: null,
I believe the only field needed to test the functionality here is `action`, so you could probably remove the other fields from all these test events.

2021-04-27 16:33 UTC, merged