M3 4841 consistent storage units render
linode/manager pull request #7614
Opened 2021-04-27 19:39 UTC by codyfinn

## Description

This PR updates formatting for storage units across the cloud manager application. There are a few places where storage sizes are listed that needed to updated in place but for the Linode plans there is an update to the reducer that should be reflected in all places where the name of the Linode plan are visible.

## How to test

Check to see if there are any places in the app where there is not a space before the storage unit

2021-04-29 13:02 UTC, johnwcallahan approved these changes
Great work tracking these down. I audited the app and wasn't able to find any inconsistencies. I left a minor, optional comment but otherwise good to go.

2021-04-29 13:26 UTC, Jskobos approved these changes
Looks good & thorough, I can't find any stragglers either. There's a non-user facing cleanup thing, and I made one suggestion for when/if you're addressing John's feedback. Neither is blocking.

2021-04-29 13:26 UTC, Jskobos commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +                  label={type.heading.replace('GB', ' GB')}
I think this is double dipping, though the extra space isn't visible to the user:

![Screen Shot 2021-04-29 at 9 22 59 AM](https://user-images.githubusercontent.com/1624067/116557529-8306fc80-a8cc-11eb-8efa-05e7f9210d4e.png)

...since this data comes from Redux where you've already done the replacement. As a safety, when/if you refactor this replace logic to a utility, maybe you could use a regex that checks for GB or MB next to a non-whitespace character.

2021-04-29 14:22 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
> +            {(type?.label ?? 'Unknown').replace('GB', ' GB')}
the `.replace('GB', ' GB')` has been moved to the reducer. This code is extraneous and will be removed in the next commit. I will make a utility function that will more generically format a string containing a storage unit like Jared suggested that way if we have future strings that are similar that function can be reused.

2021-05-03 16:22 UTC, tiffwong approved these changes
Great job!

2021-05-03 16:41 UTC, johnwcallahan requested changes

2021-05-03 16:41 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  if (!cleanedUnformattedString.match(storageRegex)) return 'unknown';
We have the `curly` eslint rule in place, so you'll need to add curly braces and break these to multiple lines.

![Screen Shot 2021-05-03 at 12 29 50 PM](https://user-images.githubusercontent.com/16911484/116904159-5b38d100-ac0b-11eb-8334-3c13b4e62113.png)

2021-05-03 16:41 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  if (match.length === 0) return 'unknown';
I think a better/safer alternative here is the string itself. I believe defaulting to "Unknown" its actually not necessary anymore, since we are requesting even shadow plan types in AuthenticationWrapper (with `ensureAllTypes()`).

2021-05-03 16:41 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.test.ts
> +  it('returns a string that contains the storage units and measurement seperated by a single space character', () => {
Spelling of "separated'.

2021-05-04 17:56 UTC, codyfinn commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  if (match.length === 0) return 'unknown';
I guess it should actually throw an error or return null or something else. This is supposed to be a generic function that doesn't only work on plan names but instead that works where ever we want to ensure consistent spacing with storage units.

2021-05-04 18:22 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  if (match.length === 0) return 'unknown';
But if it's run on a string without storage units? E.g. if we introduce a new plan name without storage units in the title, we'd wouldn't want this to throw an error or return null... we'd just want the original string.

2021-05-04 18:24 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +const storageRegex = /([0-9])([kMGTPEZY]?i?[B])/;
I plugged this into regex101.com I think we should add a `+` after the group of digits: `([0-9]+)` and make the whole thing case insensitive.

2021-05-04 18:36 UTC, codyfinn commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  if (match.length === 0) return 'unknown';
Good point!

2021-05-04 18:57 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +const storageRegex = /([0-9])([kMGTPEZY]?i?[B])/;
👍  good points.

2021-05-05 20:48 UTC, johnwcallahan approved these changes

2021-05-05 20:48 UTC, johnwcallahan commented on packages/manager/src/utilities/formatStorageUnits.ts
> +  const cleanedUnformattedString = `${unformattedString}`;
Super nitpicky... doesn't seem "cleanedUnformattedString" is necessary anymore.

2021-05-10 18:55 UTC, merged