show promo service type in billing summary
linode/manager pull request #7620
Opened 2021-04-28 19:52 UTC by HanaXu

## Description
Displays `Applies to: <service_type>` in the promo billing summary if the service type is not "all".

## How to test

1. You will need to update your `.env` file to point to the dev/alpha api and be on the vpn:
```
REACT_APP_LOGIN_ROOT='https://login.dev.linode.com'
REACT_APP_API_ROOT='https://api.dev.linode.com/v4'
REACT_APP_CLIENT_ID='UPDATE_WITH_DEV_CLIENT_ID'
```

2. Login to a dev test account that has a specific service type promo applied to it. The 4th dev test account currently has the service type `linodes` applied.
3. Click on `Accounts`
4. You should see a promotions box, under the `expires` line, there should be another line that says `Applies to: <service_type`

2021-04-29 13:11 UTC, Jskobos requested changes
Good work on this, the types and mapping etc. are all appropriate. The ticket didn't specify this, but I think we should remove the bit of code that's only displaying a single promotion. Now that these product-specific ones exist, it's possible to have one type = 'all' and one type = 'whatever' on your account; for example the test account we're using has two valid promos on it, but only the Linodes one is displayed. We can open a separate ticket for this if you feel it's out of scope or needs further discussion.

2021-04-29 13:11 UTC, Jskobos commented on packages/api-v4/src/account/types.ts
> +  service_type: string;
This should probably be `PromotionServiceType`

2021-04-29 13:11 UTC, Jskobos commented on packages/manager/src/factories/account.ts
> +      service_type: 'all',
I don't know why we added a "BAD_PROMO" to the factory here but it should be removed. If a test is depending on it it should do the mocking within the test. Then you can delete this repetition and just do `active_promotions: promoFactory.buildList(2)`

2021-04-29 13:11 UTC, Jskobos commented on packages/manager/src/factories/account.ts
> +      service_type: 'all',
Oh it looks like it was me 🙃 ...please delete this and if a test breaks we can patch it.

2021-04-29 13:11 UTC, Jskobos commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
> +  it('displays promo service type unless the service type is all', () => {
Text is incorrect

2021-04-29 13:37 UTC, johnwcallahan requested changes
Great work; requesting a couple of small changes.

2021-04-29 13:37 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
> +  longview: 'Longviews',
Should be "Longview".

2021-04-29 13:37 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
> +  transfer_tx: 'Service Transfers',
Are you sure this refers to Service Transfers (free service)? My guess is that this refers to transfer overages... I'd check with Nick.

2021-04-29 13:37 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
> +  all: 'All',
If we're not displaying this, maybe remove it from this mapping.

2021-04-29 13:37 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
> +      {service_type !== 'all' ? (
We should add one more check here, to make sure the service type is in our mapping before rendering this bit. E.g. with the current logic, if the API adds a new service type without us handling for it, we'll end up displaying `Applies to: `.

2021-04-29 13:39 UTC, johnwcallahan commented
> The ticket didn't specify this, but I think we should remove the bit of code that's only displaying a single promotion

@Jskobos we do display multiple promotions correctly ([here](https://github.com/linode/manager/blob/333445e4396732e4c361fe94578e53002c555537/packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx#L194))...  I think the example you're talking about is because the expiry is `null`, and we're filtering those out [here](https://github.com/linode/manager/blob/a989db90290bcee6a8749c830a77c9e1b59334a5/packages/manager/src/store/account/account.requests.ts#L25).

2021-04-29 13:57 UTC, HanaXu commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
> +  all: 'All',
I originally left it out, but then decided to keep it in case we ever needed it in the future and to more closely match the api

2021-04-29 14:10 UTC, codyfinn commented on packages/api-v4/src/account/types.ts
> +
Could this be changed to an Enum instead of a type?
```suggestion
export enum PromotionServiceEnum {
  all = 'All',
  backup = 'Backups',
  blockstorage = 'Volumes',
  dm_mysql = 'DBaas',
  ip_v4 = 'IPv4',
  linode = 'Linodes',
  linode_disk = 'Storage',
  linode_memory = 'Memory',
  longview = 'Longviews',
  managed = 'Managed',
  nodebalancer = 'NodeBalancers',
  objectstorage = 'Object Storage',
  transfer_tx = 'Service Transfers',
};

```
This would then remove the need for the `serviceTypeMap` in `BillingSummary.tsx`

2021-04-29 14:22 UTC, Jskobos commented on packages/api-v4/src/account/types.ts
> +
This is a cool idea...is there some way to use enums as union types (quick googling says no but I'm not super familiar with these). I'd like to have type safety/autocomplete for the JS client PromoType. Also, the string values are a bit Cloud-specific, so the Enum should probably live outside of api-v4.

2021-04-29 15:56 UTC, codyfinn commented on packages/api-v4/src/account/types.ts
> +
Do you mean union typing two Enums together or do you mean treating the keys/values as union types?

2021-04-29 16:21 UTC, codyfinn commented on packages/api-v4/src/account/types.ts
> +
A union type of keys of an enum can be achieved through `keyof typeof PromotionServiceEnum`. the Resulting type can be used to restrict the value assigned to a variable to only the keys of the enum.

2021-04-29 17:05 UTC, HanaXu commented on packages/api-v4/src/account/types.ts
> +
This seems a bit out of scope for this story as it's a larger architectural change. We can create a tech story to address this if anyone feels strongly.

2021-04-30 13:43 UTC, Jskobos approved these changes

2021-05-03 16:20 UTC, tiffwong approved these changes

2021-05-03 21:19 UTC, johnwcallahan approved these changes
Great work on this.

2021-05-04 14:22 UTC, merged