M3-5122 create cluster UI updates
linode/manager pull request #7654
Opened 2021-05-13 14:59 UTC by bnussman

## Description

Updates the Create Cluster page to new UI spec and sets the default number of nodes to 3 in the Node Pool Panel. 

Copy and Kubernetes documentation link for less than 3 nodes needs to be updated and finalized. 

## How to test

Visit `/kubernetes/create` to view the UI changes and ensure pool selection still works as expected.

2021-05-13 20:19 UTC, tiffwong commented on packages/manager/src/components/CheckoutBar/styles.ts
> +    fontSize: '24px',
Was there a reason why you changed this from `rem` to `px`?

2021-05-13 20:21 UTC, tiffwong commented on packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
> +    height: 34,
These aren't actually being applied to the plus and minus buttons, they're being overwritten by the dimensions on L52-53

2021-05-13 20:22 UTC, tiffwong commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +              </Link>
This should probably link to a Linode docs but as for which one, I'm not sure

2021-05-13 20:29 UTC, tiffwong requested changes
Great job getting this out! 

According to the design, the outlines for the plus and minus buttons should be the same color as the input field (#cccccc)
<img width="229" alt="Screen Shot 2021-05-13 at 2 17 05 PM" src="https://user-images.githubusercontent.com/7692354/118168610-0ad52680-b3f6-11eb-9b5f-5b445c733134.png">

The divider and the plan name is looking a little tight, can you also increase the margin to 4px?
<img width="262" alt="Screen Shot 2021-05-13 at 2 18 31 PM" src="https://user-images.githubusercontent.com/7692354/118168673-1a546f80-b3f6-11eb-8b18-1b9baa7ad411.png">

I left a few other cleanup items but otherwise, this is awesome!

2021-05-14 13:34 UTC, Jskobos requested changes
Nice work, I have just a few suggestions in addition to Tiffany's. Clicking "Add" for one of the number inputs resets its count to 0 (this is controlled on line 103 of NodePoolPanel.tsx). This is ok behavior, it might even be what we want, but it's perfectly possible to have multiple node pools of the same type and this might discourage that. Please check with Matthew, and depending on what he says you might want to reset to 3 on submit instead of 0.

2021-05-14 13:34 UTC, Jskobos commented on packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
> +        outline={true}
`outline` is fine here, the `={true}` is explicit which is nice but not needed in this case imo.

2021-05-14 13:34 UTC, Jskobos commented on packages/manager/src/features/Kubernetes/kubeUtils.ts
> +export const nodeWarning = `We recommend at least 3 nodes in each pool. Fewer nodes may affect availability. For more info see `;
Having a sentence fragment inside a constant is a bit risky. In this case, the warning is used elsewhere so you end up with:

<img width="420" alt="Screen Shot 2021-05-14 at 9 32 47 AM" src="https://user-images.githubusercontent.com/1624067/118277978-70c5ba80-b497-11eb-8f76-8d8b50c2f000.png">

...in the Resize Pool drawer in the LKE detail view.

Probably the best thing to do is make another display component like you did for Rescue and include the link in there.

2021-05-17 13:57 UTC, tiffwong approved these changes

2021-05-17 15:20 UTC, DevDW approved these changes
Looks good, left one minor comment.

This is an existing issue, but I noticed in mobile view that the number input is larger than the plus and minus signs:

<img width="498" alt="Screen Shot 2021-05-17 at 11 13 51 AM" src="https://user-images.githubusercontent.com/32860776/118513533-cdc4a900-b701-11eb-8083-7a121519b6f2.png">

2021-05-17 15:20 UTC, DevDW commented on packages/manager/src/features/Kubernetes/KubeNodeWarning.tsx
> +function KubeNodeWarning(props: Props) {
to be consistent with our current patterns, I'd say change this to

```
const KubeNodeWarning: React.FC<Props> = (props) => {
...
```

2021-05-17 18:31 UTC, merged