M3-5083: Dismissible Images pricing banner
linode/manager pull request #7655
Opened 2021-05-13 15:55 UTC by DevDW

## Description
Adds a dismissible banner that explains Images pricing to the Images landing and and Images creation pages. The displaying of the banner is conditional upon the feature flag and whether the user has images or not.

## How to test
The feature flag is on in the testing environment, so please ensure that the banner does not display on Images pages when you have no images, and that the banner does display on Images pages when you do have images.

The banner should not return on its own after being dismissed (if you dismiss it and want to bring it back for further testing, you can hit the `profile/settings?preferenceEditor=true` page and remove the corresponding entry from `dismissed_notifications`).

2021-05-13 21:02 UTC, bnussman approved these changes
Looks good to me!

2021-05-14 18:33 UTC, codyfinn approved these changes
Looks good to me!

2021-05-14 18:48 UTC, tiffwong requested changes
Functionality looks good, only thing I noticed is that the padding between the vertical bar and copy is a bit tight. I attached a screenshot of the banner on a Kubernetes that needs updating which is more consistent with the spacing

<img width="117" alt="Screen Shot 2021-05-14 at 2 45 15 PM" src="https://user-images.githubusercontent.com/7692354/118315147-235f4280-b4c3-11eb-9002-b59cc9b68ee9.png">
<img width="139" alt="Screen Shot 2021-05-14 at 2 45 22 PM" src="https://user-images.githubusercontent.com/7692354/118315148-23f7d900-b4c3-11eb-8545-360e573497e2.png">

2021-05-14 19:50 UTC, bnussman approved these changes
Correct me if I'm wrong but, I think the only issue I could see is if the feature flag data is bad. 

Ex. If the `text` field does not end with a trailing space then we'll get this. 
![example](https://wsend.net/b5944c86cbf0b3e54575a60765bd151c/Screen%20Shot%202021-05-14%20at%202.53.52%20PM.png)

Otherwise, looks good.

2021-05-14 22:23 UTC, DevDW commented
> Correct me if I'm wrong but, I think the only issue I could see is if the feature flag data is bad.
> 
> Ex. If the `text` field does not end with a trailing space then we'll get this.
> ![example](https://camo.githubusercontent.com/21e894fa8c5790882a65a87e6a0721e266d35de9d5fab5cf7d48b97f30522747/68747470733a2f2f7773656e642e6e65742f62353934346338366362663062336535343537356136303736356264313531632f53637265656e25323053686f74253230323032312d30352d31342532306174253230322e35332e3532253230504d2e706e67)

Yes, I've vacillated once or twice in this PR between including the space within the code or forcing it to be included in the text string in LD. I switched it back to be in the code instead; maybe that's the safer option.

2021-05-17 12:54 UTC, johnwcallahan requested changes
The approach looks good; just have a few stylistic things.

2021-05-17 12:54 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesPricingBanner.tsx
> +  const bannerHasContents = checkFlagsForImagesPricingBanner(flags);
The `checkFlagsForImagesPricingBanner` function does path checking the old school JS way. It'd be more succinct and stylistic to use optional chaining, e.g. `Boolean(flags?.imagesPricingBanner?.key)` (like you do a few lines down). 

In fact, you could use `bannerCoreText` for this instead to make it more streamlined:

```ts
const bannerCoreText = flags.imagesPricingBanner?.text;

if (images.results === 0 || !bannerCoreText) {
  return null;
}
```

2021-05-17 12:54 UTC, johnwcallahan commented on packages/manager/src/features/Images/ImagesPricingBanner.tsx
> +  const generateLede = () => {
Any particular reason you made these functions? I separating them from this FC's `return` value is good, since it allows us to see the structure of the content, but you could easily do:

```tsx
const Lede = bannerLede ? (
  <span>
    <strong>{bannerLede}</strong>:{' '}
  </span>
) : null;
```

... instead of defining separate functions.

2021-05-17 18:11 UTC, HanaXu approved these changes
LGTM!

2021-05-19 16:38 UTC, tiffwong approved these changes

2021-05-28 12:34 UTC, johnwcallahan approved these changes

2021-05-28 12:35 UTC, merged