Added connect with LISH copy to rescue modal
linode/manager pull request #7660
Opened 2021-05-17 21:15 UTC by bnussman

## Description

Adds copy to the Rescue Dialog informing the user that they should use the LISH console to connect to their Linode upon rescue. Also includes a link that directly opens LISH for them. 

![screenshot](https://wsend.net/6fa53e3cef6b5faa4fd47533ec938f38/Screen%20Shot%202021-05-17%20at%205.10.49%20PM.png)

## How to test

**What are the steps to reproduce the issue or verify the changes?**

Open the Rescue Dialog on a Linode and ensure copy and links are good.

2021-05-18 15:55 UTC, DevDW requested changes

2021-05-18 15:55 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +        <ExternalLink
We can use the `<Link />` component instead here; we're moving in the direction of getting rid of `<ExternalLink />` since `<Link />` does the same thing when the URL starts with "https": https://github.com/linode/manager/pull/7629#discussion_r625779478

2021-05-18 15:55 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +          onClick={() => lishLaunch(linodeId)}
When I clicked this, the LISH console that popped up was never able to validate the token. Is this also happening for you?

2021-05-18 15:55 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +          text="Learn more."
I wonder if we should say "Learn more" twice in the same modal? 🤔

2021-05-18 15:55 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +  linodeId: number;
Since this was added for the logic launching the LISH console and that copy should only pop up for Bare Metal instances, let's go ahead and make this an optional prop, and remove the passing in of the linodeId to this component in `RescueDialog.tsx`

2021-05-18 16:27 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +          onClick={() => lishLaunch(linodeId)}
LISH is opening successfully for me, I'll look into it.

2021-05-20 15:15 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +          text="Learn more."
@matthewbartholomew Any particular opinion on this?

2021-05-20 15:27 UTC, DevDW approved these changes
LGTM now 👌 

I still haven't been able to get the LISH console up and running for a Bare Metal instance, but that's also happening when I try it from the Linode Details page (so it's not an issue with how it's being invoked here). I'm not sure what's causing this for the instances I'm testing with, but if everyone else is able to successfully launch LISH with theirs, we should be good to go.

2021-05-21 18:51 UTC, johnwcallahan approved these changes

2021-05-21 18:51 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +      {linodeId && (
A while back Jared convinced us that using ternaries is better, since using the logical `&&` operator can sometimes result in sneaky bugs. So this would be `linodeId ? (...) : null`.

2021-05-21 18:53 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +      {linodeId && (
Good to know! I was wondering why everyone was doing that... I'll make that change.

2021-05-26 14:19 UTC, matthewbartholomew commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
> +          text="Learn more."
I think we can drop the second Learn More link. I expect that users who need more guidance will click on the first link even if they need info about using the LISH Console.

2021-05-26 21:31 UTC, merged