added time for scheduled migrations to banner
linode/manager pull request #7668
Opened 2021-05-19 16:16 UTC by bobby-palko

## Description

This adds a timestamp of when a Linode will enter the queue for a scheduled migration. If the time is within the next 24 hours, it also displays the rounded hours remaining. This updates the banner on the Linode page as well as the text in the notification center. 

## How to test

Configure a cold migration for a Linode and verify the time appears

2021-05-20 16:17 UTC, HanaXu requested changes
Looks fine functionally! Left some comments on the wording

2021-05-20 16:17 UTC, HanaXu commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +        You have a migration pending for{' '}
We should keep the `scheduled` wording since `migration_scheduled` and `migration_pending` are different notification types.

i.e. `You have a scheduled migration for`

2021-05-20 16:18 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +    let returnText = `You have a migration pending, which will automatically execute `;
Same here: `You have a scheduled migration, which will automatically execute `

2021-05-20 16:19 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +      : (returnText += `on ${formattedMigrationTime}.`);
`returnText` can be part of the template literal, though we'd probably want a better variable name

2021-05-20 17:46 UTC, bobby-palko commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +        You have a migration pending for{' '}
Makes sense to me. Updated!

2021-05-20 17:47 UTC, bobby-palko commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +    let returnText = `You have a migration pending, which will automatically execute `;
Same here. Updated.

2021-05-20 17:48 UTC, bobby-palko commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +      : (returnText += `on ${formattedMigrationTime}.`);
I honestly don't know why I didn't have it part of the template literal in the first place. It has been renamed to `baseText` and the template now includes the variable.

2021-05-20 19:27 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +    const baseText = `You have a scheduled migration pending, which will automatically execute`;
Same here. We should also update the `migrationActionDescription` variable to  `schedule your migration now` because the action will always be to enter the migration queue

2021-05-21 11:05 UTC, bobby-palko commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +        You have a scheduled migration pending for{' '}
updated

2021-05-21 11:05 UTC, bobby-palko commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +    const baseText = `You have a scheduled migration pending, which will automatically execute`;
also updated

2021-05-21 14:09 UTC, HanaXu approved these changes
LGTM! :tada:

2021-05-21 22:30 UTC, DevDW reviewed
Thanks for the PR! Left one cleanup comment and I want to do a bit more testing to make sure the type castings hold up under different circumstances; looks good so far though.

2021-05-21 22:30 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +        )} hour(s) (${formattedMigrationTime}).`
Let's pull in `pluralize` here to handle the hour/hours issue more cleanly:

`import { pluralize } from 'src/utilities/pluralize';`

then I'd do something like:

```
    const roundedHourDifference = Math.round(
      migrationTimeObject.diff(now, 'hours').as('hours')
    );
    const approximateTime = pluralize('hour', 'hours', roundedHourDifference);

    return roundedHourDifference <= 24
      ? `${baseText} in approximately ${approximateTime} (${formattedMigrationTime}).`
      : `${baseText} on ${formattedMigrationTime}.`;
  };
```

2021-05-22 10:49 UTC, bobby-palko commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +        )} hour(s) (${formattedMigrationTime}).`
brought in `pluralize` for the hour/hours issue. the casting _should_ be fine; it's only casted since `notification.when` may not get passed from the API (in which case this logic won't fire anyway), so the prop is declared as `string | null`. since luxon requires a string, it's only casted to get rid of the `null` type and make TS happy. lmk if you need anything else!

2021-05-24 14:47 UTC, DevDW requested changes
Upon further testing I haven't seen any issues with the type casting, but realized that `migration_pending` and `migration_scheduled` are now showing the same notification banner on the Linode details page. (you can turn on the mocks for testing)

2021-05-24 14:47 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +          {migrationTime ? migrationText() : notificationMessage}
I think this may need to be a check for `migration_scheduled` instead. Right now, it seems that `migration_pending` notifications will be handled the same way:

https://github.com/linode/manager/blob/59c7a88a974ff7163f18bc3d8ecdd1c5beef4b65/packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx#L46-L60

Therefore if you were to go to a Linode with a pending migration, it'd have a scheduled migration banner.

2021-05-25 12:24 UTC, bobby-palko commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
> +          {migrationTime ? migrationText() : notificationMessage}
Interesting. I tested this by scheduling all sorts of different migrations for one of my Linodes, and both banners showed as I would suspect. Regardless, I've updated this to check for the `notificationType`, as it's a cleaner approach anyway. I'd be interested in learning how to use the mocks when you have some time (just hit me up on Slack - @rpalko)

2021-05-25 15:24 UTC, DevDW approved these changes
For the sake of clarity I'd probably rename `migrationText` to something like `migrationScheduledText`, but the functionality LGTM now 👍  will reach out re: the mocks

2021-06-11 15:43 UTC, merged