M3-5000: Auto fill request description when opening support ticket
linode/manager pull request #7673
Opened 2021-05-21 18:33 UTC by HanaXu

## Description
If additional verification is required, autofill the request description with the plan the user was trying to create.

## How to test
Try to create a Linode on an account that requires additional verification.

2021-05-24 18:17 UTC, DevDW approved these changes
LGTM, works well from my testing 👌

2021-05-24 21:20 UTC, johnwcallahan reviewed
Two things:

- We should check in with someone from Support on what this exact messaging should be (if you haven't already).
- The way we're intercepting errors and replacing with React components is definitely not ideal, but I really don't love sending `type_display_title` with the payload to the API. Have you  thought about doing the id => label conversion in the error interceptor? We could use the cached types data, or potentially a function that access the store directly. (this is dependent on my first point about getting the exact messaging, though).

2021-06-09 19:42 UTC, HanaXu commented on packages/manager/src/request.tsx
> +      'Please let me know if there is any other information I can provide. Thank you.',
Ended up using string concatenation bc of formatting issues with template literals

2021-06-14 16:10 UTC, johnwcallahan requested changes
We should make sure the plan title actually exists before constructing the message and make sure a better fallback is in place. If you try to receive a service transfer with a low reputation, you also get the "verification request" error, resulting in:

<img width="919" alt="Screen Shot 2021-06-14 at 12 07 05 PM" src="https://user-images.githubusercontent.com/16911484/121923878-5a668500-cd09-11eb-8906-b9b4d24db300.png">

I think that's why "Verification Request" was the old fallback, which I think would be good to keep for cases like this.

2021-06-16 18:58 UTC, johnwcallahan approved these changes

2021-06-17 13:53 UTC, merged