M3-5061: Create Linode UI Refinements
linode/manager pull request #7677
Opened 2021-05-25 20:31 UTC by tiffwong

## Description

- Add divider between "Root Password" and "SSH Keys"
- Move VLAN into it's own panel
- Rename the add-ons panel and add divider between "Backups" and "Private IP"

## How to test

Go to http://localhost:3000/linodes/create

2021-05-26 14:07 UTC, bnussman requested changes
If the feature flag for VLANs or a customer isn't permitted use VLANs for whatever reason, we get a blank box on the Create Linode page.  
<img width="795" alt="Screen Shot 2021-05-26 at 10 05 12 AM" src="https://user-images.githubusercontent.com/6440455/119674394-2c78d980-be0a-11eb-872e-85b395a85eb2.png">

2021-06-01 14:20 UTC, bnussman approved these changes

2021-06-01 14:25 UTC, HanaXu commented
We should add margin between the SSH Keys and Add-ons if the customer doesn't have access to VLANs

![image](https://user-images.githubusercontent.com/14323019/120340011-a229ed00-c2c3-11eb-9dd5-e80a54c7e20b.png)

2021-06-01 14:26 UTC, HanaXu reviewed
We should add margin between the SSH Keys and Add-ons if the customer doesn't have access to VLANs

![image](https://user-images.githubusercontent.com/14323019/120340230-cf769b00-c2c3-11eb-8609-efe03d921332.png)

2021-06-02 13:57 UTC, HanaXu approved these changes

2021-06-02 14:59 UTC, merged