M3-5126: Update make payment drawer UI
linode/manager pull request #7693
Opened 2021-06-04 16:28 UTC by HanaXu

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-06-08 20:28 UTC, ndukatz approved these changes
Looks good! The space between these two buttons are a little weird to me but that could just be me. 
<img width="465" alt="Screen Shot 2021-06-08 at 4 25 45 PM" src="https://user-images.githubusercontent.com/66748958/121252863-8354c900-c876-11eb-8d27-73330b98d6a2.png">

2021-06-08 20:34 UTC, DevDW commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
> +            <span>{`Expires ${expiry}`}</span>
<img width="573" alt="Screen Shot 2021-06-08 at 3 58 49 PM" src="https://user-images.githubusercontent.com/32860776/121249550-b432ff00-c872-11eb-947b-3c337fe3d5a5.png">

but when I click the "Make a Payment" button:

<img width="444" alt="Screen Shot 2021-06-08 at 3 59 04 PM" src="https://user-images.githubusercontent.com/32860776/121249574-b8f7b300-c872-11eb-8e11-0d9c07518a2b.png">

It appears that we're currently not properly handling in full the case where a user has no payment methods on file (even in prod). Seems to be tied to this:

https://github.com/linode/manager/blob/fe65c798487ed77763840009667fcf53bfab6add/packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx#L273

2021-06-10 19:07 UTC, bnussman approved these changes
I think well end up cleaning this up and updating types as Google Pay comes together, but looks good!

2021-06-10 21:58 UTC, DevDW approved these changes
LGTM after one more change below

2021-06-10 21:58 UTC, DevDW commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
> +              <CreditCard type={'Visa'} expiry={expiry} lastFour={lastFour} />
`type={type}`

2021-06-11 20:37 UTC, HanaXu commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
> +    it.skip('should not display a warning for a normal successful payment', async () => {
Skipping these tests for now.

After setting `lastFour` to default to `''`, the UI is fixed, but `PaymentDrawer.test.tsx` ends up failing bc there is no pay button (which I updated to be hidden if there is no credit card on file, which is determined by if there is a lastFour).

The value `lastFour: '9999'` defined in the test doesn’t seem to be actually used. Instead, PaymentDrawer seems to be accessing the store to get the value, so the props being passed into the component are ignored.

2021-06-16 18:05 UTC, tiffwong requested changes
Seems like the credit card and PayPal payment buttons are disabled for amounts under $5 but the GPay one isn't. Also the cursor on hover should also reflect a disabled state

The white dividers also stand out a little too much on dark mode imo

<img width="487" alt="Screen Shot 2021-06-16 at 2 02 06 PM" src="https://user-images.githubusercontent.com/7692354/122269757-920d3280-ceab-11eb-8bdf-499612966e48.png">

2021-06-17 14:36 UTC, HanaXu commented
@tiffwong Good catch, the button states are handled in https://github.com/linode/manager/pull/7676, didn't want to rewrite the same code since it's all going to get merged.

2021-06-17 15:21 UTC, tiffwong approved these changes

2021-06-17 15:23 UTC, merged