M3-5146: image upload success fail
linode/manager pull request #7703
Opened 2021-06-15 03:02 UTC by codyfinn

## Description

This PR handles the failure and success of uploading custom Images. When an Image is successfully uploaded and decompressed by the server a Toast notification is shown to the user. When an Image fails to decompress on the server a persistent Toast notification is shown to the user. In addition to the persistent Toast notification a user will also see that the status of the Image on the Image Landing table will be changed to 'Failed'.

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-06-15 14:13 UTC, bnussman commented
When an upload is successful, could we refresh the images table so it shows the updated state? It's confusing when there is a toast saying the upload was successful but the table's state is not updated

2021-06-15 15:22 UTC, codyfinn commented
> When an upload is successful, could we refresh the images table so it shows the updated state? It's confusing when there is a toast saying the upload was successful but the table's state is not updated

Good catch. We don't need to refresh the screen. We just need to listen for events that have the finished status in a similar way that we listen to ones that have a failed status. The table will then automatically update like it does for failures.

2021-06-15 15:56 UTC, HanaXu reviewed
Idk if this is happening for anyone else, but it's really inconsistent when I get the error toast after uploading an invalid image. Sometimes, it just won't show up at all. Sometimes, it'll display on another Cloud Manager tab I have open, but not on the tab where I uploaded the image.

When I do get an error toast, in the notification drawer, it says it failed after 23 hours 57 minutes when I know it was only a minute or two.

![image](https://user-images.githubusercontent.com/14323019/122082816-4f295d00-cdce-11eb-86e7-fdd816f106e2.png)

![image](https://user-images.githubusercontent.com/14323019/122082825-518bb700-cdce-11eb-8766-c20be1fc9d7c.png)

If an upload failed, in the table we should change the Size from `pending` to something like `N/A`, and there shouldn't be a `cancel upload` button displayed.

![image](https://user-images.githubusercontent.com/14323019/122083090-90ba0800-cdce-11eb-9a40-777c86b19e9f.png)

What it looks like after clicking on the cancel upload on a failed image. Semi-related, we should display which image we are trying to cancel the upload for.

![image](https://user-images.githubusercontent.com/14323019/122083208-a5969b80-cdce-11eb-8bdc-edc0fad2e53e.png)

And specify which image was deleted as well
![image](https://user-images.githubusercontent.com/14323019/122083612-02925180-cdcf-11eb-8f88-aae351c8833d.png)

The table doesn't seem to be updating even though a toast says the image upload was successful:
![image](https://user-images.githubusercontent.com/14323019/122085257-8862cc80-cdd0-11eb-9909-6aee3e68e36c.png)
![image](https://user-images.githubusercontent.com/14323019/122085306-96185200-cdd0-11eb-8837-980038fb8ab9.png)

2021-06-15 16:02 UTC, bnussman commented
> change the Size from `pending` to something like `N/A`
 
I agree with this, noticed it as well.

2021-06-15 17:05 UTC, DevDW requested changes

2021-06-15 17:07 UTC, codyfinn commented on packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
> +    persistFailure: boolean
I could use enqueNotification directly and not use the premade _toast function. That way everything else would be left alone.

2021-06-15 19:30 UTC, johnwcallahan commented on packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
> +                : `There was a problem uploading image ${label}. ${event.message}`,
Also, maybe consider replacing "uploading" with "processing", to avoid this slightly awkward toast stack:
<img width="625" alt="Screen Shot 2021-06-15 at 3 29 23 PM" src="https://user-images.githubusercontent.com/16911484/122112206-90316980-cdee-11eb-99df-d74b6163217b.png">

2021-06-15 19:36 UTC, johnwcallahan commented on packages/manager/src/store/events/event.helpers.ts
> +export const LONG_PENDING_EVENTS = [''];
This array is used in RenderEvent.tsx... maybe we should update that to reference `isLongPendingEvent` and remove this array altogether.

2021-06-15 19:38 UTC, johnwcallahan commented on packages/manager/src/store/events/event.helpers.ts
> +      !isLongPendingEvent(event)
I think this is already covered on L168, right?

2021-06-15 19:43 UTC, johnwcallahan commented on packages/manager/src/store/selectors/imageEvents.ts
> +        isEventFailedImageUpload(thisEvent)
Instead of adding this condition to this events selector, have you thought about using `useEvents` in ImagesLanding instead?

2021-06-15 20:06 UTC, DevDW commented on packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
> +    persistFailure: boolean
After thinking about this more, the fix I mentioned doesn't seem as bad–it builds in the option of persisting toasts if we happen to want to do that in the future in other cases 🧐 one can argue that having to throw all those booleans in throughout the file would muddy it up a bit, but I'm not sure if that's entirely valid. Interested in hearing @johnwcallahan's thoughts on this though.

Because this is curried, I don't think that default params are an option here. So I think our choices are what I described in my previous comment, or not using `_toast` and enqueueing independently for the `image_upload` case as Cody said.

2021-06-16 16:34 UTC, DevDW approved these changes
I think all of the major issues have been addressed so this is in a good state to get it merged. Left one suggestion about a variable renaming.

For a follow-up PR I think some refactoring such as what John mentioned about possibly using `useEvents` in `ImagesLanding.tsx` would be good

2021-06-16 16:34 UTC, DevDW commented on packages/manager/src/store/events/event.helpers.ts
> +export const isEventFailedImageUpload = (event: Event): boolean => {
This variable is only checking for the event's action type and doesn't have a check for whether it failed or not, so maybe rename this variable and add a comment explaining its purpose/use case?

2021-06-16 16:36 UTC, DevDW commented on packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
> +        );
This is a good middle ground between the approaches discussed yesterday IMO 👍

2021-06-16 16:43 UTC, codyfinn commented on packages/manager/src/store/events/event.helpers.ts
> +export const isEventFailedImageUpload = (event: Event): boolean => {
I knew I forgot to change something. It used to only check for failed upload messages but we still need to check for successful ones. I can change that real quick.

2021-06-16 17:35 UTC, johnwcallahan approved these changes

2021-06-16 17:39 UTC, merged