M3 5250: Clean up Tables CMR
linode/manager pull request #7705
Opened 2021-06-15 21:49 UTC by tiffwong

## Description

Replace old Table-related components with the new CMR version and rename the file wherever it's being imported

## How to test

Make sure all the components that were updated all look good

2021-06-16 13:58 UTC, bnussman commented
I'm seeing some horizontal scroll bars on some tables on `/domains/{id}` that were not there before

<img width="1277" alt="Screen Shot 2021-06-16 at 9 57 09 AM" src="https://user-images.githubusercontent.com/6440455/122232433-3af66600-ce89-11eb-8eab-21fb1aee2eb2.png">

2021-06-16 17:43 UTC, bnussman commented
Found a slight dark mode bug that was introduced on the Linode graph's table header 

<img width="1214" alt="Screen Shot 2021-06-16 at 1 39 46 PM" src="https://user-images.githubusercontent.com/6440455/122267412-d814c700-cea8-11eb-9c7b-1a55a677c373.png">

2021-06-17 13:24 UTC, bnussman commented
Seeing the same overflow problem with the backups table.

<img width="1233" alt="Screen Shot 2021-06-17 at 9 23 54 AM" src="https://user-images.githubusercontent.com/6440455/122405077-bfaab800-cf4d-11eb-92dc-fca090ee5b6c.png">

2021-06-17 13:52 UTC, bnussman requested changes

2021-06-17 15:23 UTC, tiffwong commented on packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
>  import TableSortCell_PreCMR from 'src/components/TableSortCell';
Nice catch!

2021-06-17 16:29 UTC, DevDW reviewed
I still need to comb through the code and the app a bit more, but I haven't noticed any UI bugs so far. Banks raised a good point about the `linkTarget` piece with the Events though; we'll definitely want to restore that functionality.

2021-06-17 21:23 UTC, tiffwong commented on packages/manager/src/features/Events/EventRow.tsx
> -      rowLink={entityId ? undefined : (linkTarget as any)}
This should be fixed now 😅

2021-06-21 20:08 UTC, bnussman approved these changes
Everything throughout the app looks good to me! More 👀 on this one might be nice just to check for things I may have missed

2021-06-21 21:03 UTC, DevDW requested changes
I have a little bit more to test, but I did find a bug in `DomainRecordActionMenu`

2021-06-21 21:48 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackupActionMenu.tsx
> +      title: 'Restore to Existing Linode',
side note: clicked this and noticed the hover color of the "Cancel" button in the drawer is odd

<img width="453" alt="Screen Shot 2021-06-21 at 5 45 09 PM" src="https://user-images.githubusercontent.com/32860776/122831998-b6f11380-d2b8-11eb-814d-125830682ec8.png">

2021-06-22 16:29 UTC, DevDW approved these changes
LGTM now!

2021-06-23 18:58 UTC, HanaXu approved these changes
LGTM! Left a comment about the rowLink test

2021-06-23 18:58 UTC, HanaXu commented on packages/manager/src/components/TableRow/TableRow.test.tsx
> +  it.skip('calls history.push with the given rowLink', () => {
Do we still need this test if we removed `rowLink`?

2021-06-24 14:16 UTC, tiffwong commented on packages/manager/src/components/TableRow/TableRow.test.tsx
> +  it.skip('calls history.push with the given rowLink', () => {
Probably not but I wasn't sure how to fix the test otherwise lol

2021-06-24 15:23 UTC, merged

2021-06-24 15:23 UTC, HanaXu reviewed
Actually one more thing, can we fix this warning?

![image](https://user-images.githubusercontent.com/14323019/123289522-8ab6dc00-d4de-11eb-8765-c1e343383d70.png)