M3-5075: Rework payment method panel for multiple payment methods
linode/manager pull request #7708
Opened 2021-06-17 15:16 UTC by bnussman

## Status

Ready for review, but plan to merge after #7676

## Description

- Uses Feature Flag where needed
- Add copy about Google Pay now being an option
- Use new `GET` `/account/payment-methods` endpoint to populate payment method rows
- Uses new PaymentMethodRow component
- Adds Drawer for adding new payment methods
- Adds mock for `GET` `/account/payment-methods` 

## How to test

View `/account/billing` and view the page with the Google Pay feature flag both on and off. Ensure items listed above are solid.

2021-06-21 20:40 UTC, johnwcallahan requested changes
Really great work. I just have on blocking comment (re: error state)... the rest are minor.

Also, not sure we want to merge in the changes from the hotfix (with the referral stuff). We should probably merge the hotfix branch directly to the feature branch.

2021-06-21 20:40 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +          ? 'No payment methods have been specified for this account.'
I think the error message should take precedence. If you block requests to `/payment-methods`:

<img width="637" alt="Screen Shot 2021-06-21 at 4 00 15 PM" src="https://user-images.githubusercontent.com/16911484/122820855-17c51f80-d2aa-11eb-8b76-c3759a4264c2.png">

2021-06-21 20:40 UTC, johnwcallahan commented on packages/manager/src/queries/accountPayment.ts
> +      paymentMethod.is_default === true && paymentMethod.type === 'credit_card'
Minor: I believe `paymentMethod.is_default && paymentMethod.type === 'credit_card'` would be sufficient.

But... it doesn't look like it's in use anywhere?

2021-06-21 20:40 UTC, johnwcallahan commented on packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
> +              thirdPartyPayment={paymentMethod.type as ThirdPartyPaymentType}
Minor: looks like TS handles this correctly without the type casting (so you can remove it) 🎉

2021-06-21 20:40 UTC, johnwcallahan commented on packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
> +          {paymentMethod.type === 'credit_card' ? (
Minor: there are a lot of references to `paymentMethod` in this return value... might be worth destructuring.

2021-06-22 13:10 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +          ? 'No payment methods have been specified for this account.'
Good catch, thank you.

2021-06-22 13:20 UTC, bnussman commented on packages/manager/src/queries/accountPayment.ts
> +      paymentMethod.is_default === true && paymentMethod.type === 'credit_card'
Yes, good catch. I'm going to keep this around for a little but longer because it may have temporary use in the 'Make a Payment' drawer when we use this React Query to populate that drawer.

2021-06-22 13:24 UTC, bnussman commented
@johnwcallahan and also, sorry for the weird hot fix and develop merges... that was not intentional 😕

2021-06-22 13:56 UTC, johnwcallahan approved these changes

2021-06-22 13:56 UTC, johnwcallahan commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +          'No payment methods have been specified for this account.'
One more quick thing... this should be wrapped in a `<Typography />`.

2021-06-22 15:00 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +          'No payment methods have been specified for this account.'
Fixed!

2021-06-22 20:36 UTC, HanaXu approved these changes
LGTM! Left some UI suggestions

Don't remember why I added an extra margin left here but I think we can remove it (line 33 and 80 in `CreditCard.tsx`.

![image](https://user-images.githubusercontent.com/14323019/122995413-950a9600-d377-11eb-9c10-56b7f114990e.png)

2021-06-22 20:36 UTC, HanaXu commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +              Add a Payment Method
Can we remove the `a`?

2021-06-22 20:36 UTC, HanaXu commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +                Add Payment Method.
Remove the period in `Add Payment Method.`

2021-06-22 20:36 UTC, HanaXu commented on packages/manager/src/assets/icons/payment/googlePay.svg
> +	 x="0px" y="0px" height="48" viewBox="0 0 1094 742" enable-background="new 0 0 1094 742" xml:space="preserve">
Making the height 48 causes the payment row component to be taller:

![image](https://user-images.githubusercontent.com/14323019/122994145-22e58180-d376-11eb-98d2-bc67d0861714.png)

2021-06-22 21:00 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +              Add a Payment Method
I can get behind this 👍🏼

2021-06-22 21:03 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
> +                Add Payment Method.
Removing period and changing link to `Add Google Pay`

2021-06-22 21:05 UTC, bnussman commented on packages/manager/src/assets/icons/payment/googlePay.svg
> +	 x="0px" y="0px" height="48" viewBox="0 0 1094 742" enable-background="new 0 0 1094 742" xml:space="preserve">
I think I changed this a while ago, reverting back to 35.

2021-06-22 21:09 UTC, bnussman commented
Going to address some styling issues in the upcoming days...

2021-06-28 18:56 UTC, merged