M3-5254: Improve presentation of info & fix error-surfacing bug in LinodeConfigDialog
linode/manager pull request #7718
Opened 2021-06-23 19:59 UTC by DevDW

## Description
- [ ] If devices are assigned non-sequentially (e.g. `sda` and `sdb` are assigned, then no others until `sdh`), display up to the last assigned device to the user instead of having the user click "Add a Device" until reaching that slot
- [ ] Surface the errors when a user assigns a volume or a disk that is already assigned on a different slot

2021-06-23 20:01 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        setDeviceCounter(1);
This is being set explicitly because if a user went to edit a config first and then went to add a configuration, the modal to add a config would display the same number of device slots as was in the edit modal

2021-07-02 15:54 UTC, tiffwong approved these changes
LGTM

2021-07-07 15:54 UTC, bnussman approved these changes
Good work 👍🏼

2021-07-08 19:30 UTC, johnwcallahan reviewed
In the error message, I'd like to see us substituting the device ID with the device label (e.g. `Debian 10 Disk already in use`).

2021-07-08 19:30 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.test.ts
> +      expect(extractDiskOrVolumeId(errorReasons[0])).toBe('disk-2005');
Super minor. You could choose to make this dynamic:


```ts
const tests = [
  { input: "disk ID 2005 is referenced more than once", expected: 'disk-2005' },
  // ... etc.
]
```

Then you just iterate through the tests:
```ts
  tests.forEach(thisTest => {
    expect(extractDiskOrVolumeId(thisTest.reason).toBe(thisTest.expected)
  }
```

2021-07-08 19:30 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        // If device slots are populated out of sequential order (e.g. sda and sdb are assigned but no others are until sdf), ascertain the last assigned slot to determine how many device slots to di
Minor: this is quite a long line... I'd recommend adding a newline or two.

2021-07-08 19:30 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        setDeviceCounter(1);
Might be clearer to set a `deviceCounterDefault` value somewhere and use it here as well as the original `useState` call.

2021-07-08 19:30 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.test.ts
> +    });
What happens when an ID isn't included in the error reason? (looks like it returns "volume-NaN"). A test should be added for this case, and a better value should be returned as well (maybe `null`).

2021-07-08 19:30 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
> +const blockDeviceRegex = /[0-9][0-9]+/g;
Why two digit minimum?

2021-07-09 19:14 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
> +const blockDeviceRegex = /[0-9][0-9]+/g;
I couldn't think of a reason to keep a two digit minimum so I changed this accordingly

2021-07-13 12:26 UTC, johnwcallahan requested changes
The disk label substitution works well. This seems a bit odd though... what are your thoughts on only displaying the error on the last instance of the field error?
<img width="466" alt="Screen Shot 2021-07-13 at 8 23 19 AM" src="https://user-images.githubusercontent.com/16911484/125451277-f469fc0d-a5eb-430e-bedd-c40d391194e1.png">

2021-07-13 12:26 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.test.ts
> +  },
What about these test cases are different from the first two? Seems like you could cut them.

2021-07-13 12:26 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
> +                  ? adjustedErrorText(errorText!, selectedDevice.label)
I don't think we should be using the assertion operator (it's too easy to break it later). Either check that `errorText` is defined or handle for it being undefined in the helper function.

2021-07-13 12:26 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
> +  return `${type}-${Number(blockDeviceRegexMatch)}`; // return a string structured in a way that it is easily compared to selectedDevice.value
More idiomatic would be to return a ternary expression.

2021-07-13 12:26 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx
> +  return `${deviceLabel} is already in use.`;
(same comment about ternary expressions)

2021-07-13 18:23 UTC, DevDW commented
> The disk label substitution works well. This seems a bit odd though... what are your thoughts on only displaying the error on the last instance of the field error?
> <img alt="Screen Shot 2021-07-13 at 8 23 19 AM" width="466" src="https://user-images.githubusercontent.com/16911484/125451277-f469fc0d-a5eb-430e-bedd-c40d391194e1.png">

It seems it might be a bit arbitrary to display it on the last instance only since Block Devices don't have to be assigned sequentially. For example, if `/sdg` has VolumeA on it already and a user tries to assign VolumeA to `/sdb` as well, we would encounter a situation where the error would get placed only on the slot that's already assigned (`/sdg` in this example).

2021-07-16 18:00 UTC, johnwcallahan commented
> It seems it might be a bit arbitrary to display it on the last instance only since Block Devices don't have to be assigned sequentially. For example, if `/sdg` has VolumeA on it already and a user tries to assign VolumeA to `/sdb` as well, we would encounter a situation where the error would get placed only on the slot that's already assigned (`/sdg` in this example).

Great point, let's keep it as is.

2021-07-16 18:00 UTC, johnwcallahan approved these changes

2021-07-19 18:15 UTC, merged