M3-5259: Referral page changes
linode/manager pull request #7721
Opened 2021-06-24 20:17 UTC by tiffwong

## Description

Changes to reflect the upcoming referral threshold:
- If a user has not spent $25, display message and hide referral link
- If a user has spent $25 but has not referred anyone yet, show referral link but hide results
- If a user has spent $25 and has referred people, show referral link and results

Created a local variable that currently represent if users are allowed to make referrals

**Remaining tasks:**
- [ ] Replace local variable with actual variable from API

## How to test

- Go to `/profile/referrals`
- Make sure each state matches the corresponding designs including when the flag is turned off

2021-06-24 21:25 UTC, HanaXu requested changes
Will look at this more tomorrow but we should display the images on separate rows for mobile

![image](https://user-images.githubusercontent.com/14323019/123334365-fe71dc80-d510-11eb-94d8-14368891c49b.png)

2021-06-24 21:41 UTC, tiffwong commented
@HanaXu I totally forgot about responsiveness 🤦‍♀️

2021-06-24 21:49 UTC, johnwcallahan reviewed
Will look more tomorrow, but I believe Matthew has another screenshot showing a "Pending referrals" line if `referrals.pending > 0`. 

How are we feeling about dark mode? Contrast is a little much, maybe:
<img width="952" alt="Screen Shot 2021-06-24 at 5 48 12 PM" src="https://user-images.githubusercontent.com/16911484/123336902-7a215880-d514-11eb-874b-bbf097df0bbf.png">

2021-06-24 22:02 UTC, DevDW reviewed
This is looking good to me so far 👌 

The middle image seems like it might need a closer cut by the person's arm since a little bit of the background runs along it (this is only visible in dark mode) 🤔 

John mentioned the "Pending referrals" line which is right, that's in the screenshots shared on Tuesday

2021-06-25 14:05 UTC, tiffwong commented
@johnwcallahan Matthew brought up some other dark mode color changes so I'll address the contrast in a follow up PR since it would be a global change

@DevDW those are apparently the OG image files from the marketing site so leaving those as is for now

2021-06-25 14:23 UTC, tiffwong commented on packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
> +      height: 14,
Was requested to reduce the height for the copy icon globally so I refactored this component while I was here

2021-06-25 15:39 UTC, HanaXu requested changes
Left some feedback on consistency!

2021-06-25 15:39 UTC, HanaXu commented on packages/manager/src/assets/icons/referrals/step-1.svg
> +<svg enable-background="new 0 0 260 260" viewBox="0 0 260 260" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><clipPath id="a"><path d="m0 0h260v260h-260z"/></clipPath>
These are more-so images than icons 🤔 . We should move them to `/src/assets/referrals/step-1.svg` etc instead

2021-06-25 15:39 UTC, HanaXu commented on packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
> +      height: 14,
The copy icon isn't exactly centered

![image](https://user-images.githubusercontent.com/14323019/123446941-5fe48a80-d5a7-11eb-99a6-65e0c2f470ba.png)
![image](https://user-images.githubusercontent.com/14323019/123446953-62df7b00-d5a7-11eb-930e-d7c8f640c47c.png)

2021-06-25 15:39 UTC, HanaXu commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                <Grid item>
We should hide this for state 2

![image](https://user-images.githubusercontent.com/14323019/123447853-4bed5880-d5a8-11eb-90bc-5cb356d3d212.png)

2021-06-25 15:39 UTC, HanaXu commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                        <Grid item>${credit}</Grid>
The credit amount should be green to be consistent with how we currently display credits

![image](https://user-images.githubusercontent.com/14323019/123448081-8820b900-d5a8-11eb-8962-7a4d1201c3f0.png)

2021-06-25 18:56 UTC, tiffwong commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                <Grid item>
Are you referring to the images?

2021-06-25 19:10 UTC, HanaXu commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                <Grid item>
The empty Grid item which is causing extra padding between the referral link and image

2021-06-25 21:22 UTC, HanaXu approved these changes
Left two more minor comments but LGTM :money_with_wings: !

2021-06-25 21:22 UTC, HanaXu commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                        <Grid item>Pending referrals</Grid>
Maybe add a colon after each of these lines

2021-06-25 21:22 UTC, HanaXu commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +    marginTop: theme.spacing(5),
5 is a bit much, what about 4?

2021-06-28 15:51 UTC, DevDW approved these changes
LGTM 👍

2021-06-28 15:51 UTC, DevDW commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
> +                    {pending != undefined && pending > 0 ? (
`pending !== undefined...`

2021-06-28 16:05 UTC, ndukatz approved these changes

2021-06-28 18:02 UTC, merged