Maintenance Table Updates and Tests
linode/manager pull request #7728
Opened 2021-06-29 22:13 UTC by bnussman

## Description

- Adds tests to the Maintenance Table
- Moved Row logic into `MaintenanceTableRow.tsx`

## How to test

- Make sure Maintenance Table still functions an intended
- `yarn test Maintenance`

2021-07-02 15:03 UTC, tiffwong approved these changes

2021-07-02 16:06 UTC, DevDW requested changes

2021-07-02 19:55 UTC, bnussman commented on packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
> -  }, []);
Good catch. I removed it because It caused problem with the unit tests. I'll find a way to get this back in.

2021-07-06 19:15 UTC, codyfinn requested changes

2021-07-06 19:15 UTC, codyfinn commented on packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
> +const MaintenanceTableRow = (props: AccountMaintenance) => {
Could we get a type annotation on the return type of this function?

2021-07-06 19:15 UTC, codyfinn commented on packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
> +    status: 'pending' | 'ready' | 'started' | 'completed'
The AccountMaintenance type only has `'pending' | 'started'` as valid values for the status field. Are `'ready'` and `'completed'` needed here?

2021-07-06 20:15 UTC, codyfinn approved these changes
LGTM!

2021-07-06 20:32 UTC, DevDW approved these changes

2021-07-07 14:10 UTC, merged