M3-5261: Update billing and payment history table after payment
linode/manager pull request #7730
Opened 2021-06-30 20:50 UTC by HanaXu

## Description
Populate billing & payment history table using React Query and update the table by invalidating the query after a payment is made

## How to test
Go to Account and make a payment. After a payment is successfully submitted, the billing & payment table should automatically update with the new payment without requiring a page refresh

2021-07-01 15:13 UTC, bnussman requested changes
Looks good and functions very nicely! 

Two thoughts I have now are: 
- ~~Would it be worth it to API paginate the payments and invoices table?~~ (Probably not because we merge payments and invoices and it would get messy)
- When a user successfully submits a one time payment, would it be better if we have a success toast and close the drawer automatically? This makes sense to me and It would emphasize the update to the table

2021-07-01 15:13 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
> +    setLoading(accountPaymentsLoading || accountInvoicesLoading);
I'm not completely sure, but maybe we could eliminate the `loading` state and just rely on `accountPaymentsLoading` and `accountInvoicesLoading`. This might eliminate an extra render. Maybe same with the `error` state.

2021-07-02 17:42 UTC, tiffwong approved these changes
Great job! Everything worked smoothly for me! 🎉 

Only thing I noticed is the hover state for "Add Google Pay" is underlining the space before the text starts
<img width="461" alt="Screen Shot 2021-07-02 at 1 33 03 PM" src="https://user-images.githubusercontent.com/7692354/124310503-48267c80-db3a-11eb-868c-5e3649eca69a.png">

2021-07-02 17:56 UTC, bnussman commented
> Great job! Everything worked smoothly for me! 🎉
> 
> Only thing I noticed is the hover state for "Add Google Pay" is underlining the space before the text starts
> <img alt="Screen Shot 2021-07-02 at 1 33 03 PM" width="461" src="https://user-images.githubusercontent.com/7692354/124310503-48267c80-db3a-11eb-868c-5e3649eca69a.png">

This is my bad, sorry! You can fix it @HanaXu or I can in another Google Pay PR!

2021-07-02 19:11 UTC, bnussman approved these changes

2021-07-06 15:51 UTC, merged