Use new status page url for system status
linode/manager pull request #7738
Opened 2021-07-02 22:21 UTC by bnussman

## Description

Uses new env variable `LINODE_STATUS_PAGE_URL` instead of  `LINODE_STATUS_PAGE_ID` to populate system status. This also improves defaults because you no longer need an env variable for the fetch to work. 

## How to test

Ensure Manager can still fetch for system status.

2021-07-06 12:41 UTC, johnwcallahan requested changes
Looks good, but you'll need to fix the failing test by updating the glob in serverHandlers.ts, currently:

```
*statuspage.io/api/v2/incidents*
```

2021-07-06 12:52 UTC, johnwcallahan approved these changes

2021-07-06 18:14 UTC, codyfinn approved these changes
Looks good to me!

2021-07-09 13:17 UTC, tiffwong approved these changes

2021-07-12 20:11 UTC, merged