Cleanup Referrals
linode/manager pull request #7752
Opened 2021-07-09 19:19 UTC by tiffwong

## Description

Removal conditional logic since the referral changes have been released to GA

## How to test

Make sure the referral states look like they're supposed to, message me if you need help seeing the different states

2021-07-09 19:20 UTC, tiffwong commented on packages/manager/src/featureFlags.ts
> -  thirdPartyAuth: boolean;
This flag is also no longer used so I removed it

2021-07-12 14:17 UTC, bnussman requested changes

2021-07-12 14:17 UTC, bnussman commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
>    const allowReferral = url !== undefined;
Getting an empty field. Do we need this change again?
```ts
const allowReferral = Boolean(url);
```

2021-07-12 16:07 UTC, DevDW commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
>    const allowReferral = url !== undefined;
I'm getting the same thing -- I think that when the hotfix went out for this, `staging` wasn't merged into `develop` so this change didn't get in

2021-07-12 17:03 UTC, tiffwong commented on packages/manager/src/features/Profile/Referrals/Referrals.tsx
>    const allowReferral = url !== undefined;
@bnussman @DevDW that's exactly what happened...thanks for catching that! 😓

2021-07-12 18:39 UTC, DevDW approved these changes
LGTM now, can you add the other changes from https://github.com/linode/manager/pull/7732/files so that `develop` gets updated when you merge this?

2021-07-12 18:40 UTC, bnussman approved these changes

2021-07-12 19:30 UTC, merged