added Mui-disabled rules for MuiButton
linode/manager pull request #7772
Opened 2021-07-16 16:51 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-07-19 17:32 UTC, tiffwong commented on packages/manager/src/themes.ts
> +          color: '#5c6470',
These don't do anything since they're missing the `.` to signify that it's a class but they're also not needed since the `$disabled` basically converts the styles to that when it's rendered

2021-07-19 17:32 UTC, tiffwong commented on packages/manager/src/themes.ts
> +        },
Same thing here

2021-07-19 17:33 UTC, tiffwong requested changes
Changes look good but there's duplicate styles that aren't doing anything so will approve once those are cleaned up 👍

2021-07-19 17:39 UTC, bnussman approved these changes
Disabled buttons in dark mode look much better now 🙂

2021-07-20 12:16 UTC, tiffwong approved these changes

2021-07-26 18:12 UTC, merged