M3-5191: Use React Query for Profile and Grants
linode/manager pull request #7778
Opened 2021-07-20 18:26 UTC by bnussman

## Description

- Uses React Query for all profile related API fetching and store

## How to test

- Test everything in Cloud Manager ☁️

2021-07-30 16:10 UTC, DevDW reviewed
I have quite a bit of testing left to do across the app, but I noticed that if a restricted user has just `read_only` access for a Linode, on this branch the action buttons for that Linode aren't disabled on the Linodes landing page

2021-08-02 19:52 UTC, HanaXu commented
There were a lot of issues, but I think I finally merged develop in correctly after the 5th try :crossed_fingers:. This should be ready for review now

2021-08-03 19:21 UTC, HanaXu requested changes
I'm also seeing the buttons not being disabled for restricted users with `read_only` access for a Linode. Other than that, things look fine to me! Just mainly have cleanup comments

This branch:
![image](https://user-images.githubusercontent.com/14323019/128057640-3b3d3e3a-a5f0-4bb5-99ab-8e943b890269.png)
Remote dev:
![image](https://user-images.githubusercontent.com/14323019/128057651-7d0c5ad3-c6dd-47b1-b646-ea5958e659de.png)

The dark mode button text style for `images/create` seem to be off on this branch:

![image](https://user-images.githubusercontent.com/14323019/128058371-5854352e-bdbb-4680-a213-bddbe054b33f.png)

The following can be handled in a separate PR; We don't currently handle this consistently in Volumes, NodeBalancers, Firewalls, Images, Domains either:

![image](https://user-images.githubusercontent.com/14323019/128057915-2acc87bc-f8eb-4a8f-82b0-f56c183ced64.png)

When we disable the buttons, we should display an error notice similar to `images/create` so users know why the buttons are disabled.

![image](https://user-images.githubusercontent.com/14323019/128058192-c213325d-6fda-4781-9f4c-779f2b0daa82.png)

We should do the same in `images/upload` and disable the input fields as well. And display a similar Notice error in `account/billing` and disable the buttons there for users with `read_only` access

2021-08-03 20:58 UTC, DevDW reviewed
Going to revisit this in-depth tomorrow, but on a restricted account I observed calls to `/account` and `/settings` being fired off every few seconds. 🤔  We'll want to get to the bottom of that

2021-08-03 21:55 UTC, bnussman commented
ImagesDrawer.tsx needs some attention. Unable to edit a description of an Image.

2021-08-04 17:44 UTC, DevDW reviewed
This happens on prod as well, but when a StackScript is created from a restricted account, it can't be edited, etc. until the page is refreshed.

Prod behavior for a restricted user navigating to `/images/create` is that they can't even get there; this branch improves upon by that by allowing navigation to it and disabling interaction with the contents of the "Capture Image" tab. We should give the "Upload Image" tab similar treatment by disabling all of the fields.

2021-08-05 12:56 UTC, bnussman commented
@HanaXu @DevDW  Addressed yall's feedback. I definitely would like to work on a follow up PR down the road that improves consistency for restricted users / users with only some grants. For now, trying to make sure this PR has no regressions in comparison to prod.

2021-08-05 18:17 UTC, johnwcallahan reviewed
I've reviewed the bottom half of the files so far.

In general I'm a little hesitant by the pattern of getting query data in `mapStateToProps`. It feels anti-pattern-y to me, though it seems to work to the extent that the function is run with the query is re-fetched. One option would be to build a wrapper FC that uses the useProfile hook and injects the data into class components.

2021-08-09 15:51 UTC, DevDW reviewed
Gave this another lookover and it's looking good to me. If you're looking to do that wrapper component in this PR, I'll hold off the approval until that's in so I can test that

2021-08-10 16:42 UTC, tiffwong approved these changes
Everything works the same as prod for me 👍

2021-08-10 17:58 UTC, codyfinn commented on packages/manager/src/queries/accountSettings.ts
> +  Boolean(queryClient.getQueryData<AccountSettings>(queryKey)?.managed);
Is there a reason this was changed to a function?

2021-08-10 17:58 UTC, codyfinn commented on packages/manager/src/queries/accountSettings.ts
> +  Boolean(queryClient.getQueryData<AccountSettings>(queryKey)?.backups_enabled);
Is there a reason this was changed to a function?

2021-08-10 18:52 UTC, codyfinn approved these changes
Looks good to me! Nice job!

2021-08-10 19:05 UTC, HanaXu approved these changes
LGTM! 👍

2021-08-10 21:23 UTC, DevDW approved these changes
Great work! I didn't encounter any new issues in this round of testing.

I investigated the repeated API calls for restricted users in greater depth. The cause of what is bothering me there seems to be the `refetchOnWindowFocus` setting. It is true by default. So for restricted users, since the queries go stale after 3 attempts, the refetching happens when the window is brought back into focus.

Maybe it is worth exploring in a follow-up the extent to which we can set `refetchOnWindowFocus` to false if it is a restricted user? Endpoints of particular note from what I saw are `/account`, `/settings`, and `/payment-methods`. If it is explored further, we might be looking at something like the below, for example (I just did this to see if the general approach would work; refinements can be made):

<img width="372" alt="Screen Shot 2021-08-10 at 5 15 59 PM" src="https://user-images.githubusercontent.com/32860776/128936323-1855b42d-5ccb-4f2c-a3b6-4bb060cd5d31.png">

2021-08-11 14:47 UTC, merged