M3-5296: Add banner for Block Storage availability in Atlanta
linode/manager pull request #7783
Opened 2021-07-21 20:08 UTC by tiffwong

## Description

Adds a banner to the Volumes Landing page and the Linode Details page if the Linode is in Atlanta that's hidden behind a feature flag. Dismiss both banners if either of them are dismissed.

I also included a fix for Kubernete's Upgrade Version banner since the font size wasn't being applied.

Additionally, I noticed that there's a style conflict if a banner that uses the `Notice` component is also being displayed.
<img width="1073" alt="Screen Shot 2021-07-21 at 3 59 38 PM" src="https://user-images.githubusercontent.com/7692354/126552258-835eaa73-b495-47ed-be90-b16534a5338a.png">

## How to test

- Go to `/volumes` and check to see if the banner is visible depending on the flag.
- Go to a Linode Details page and check to see if the banner is visible depending on the flag and if the Linode is located in Atlanta.

2021-07-22 13:28 UTC, bnussman approved these changes
Looks really good!

One tiny change you could make is to `export const useStyles` from `VolumesLanding.tsx` and importing it in `LinodeDetailHeader.tsx` to prevent duplicating the styles.

2021-07-23 14:30 UTC, ndukatz approved these changes

2021-07-23 14:38 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +  const region = 'ca-central';
Temporarily set to Toronto for demo purposes

2021-07-23 18:48 UTC, tiffwong commented
@bnussman @ndukatz I re-requested reviews since I updated the branch to staging 😅

2021-07-27 01:52 UTC, johnwcallahan requested changes
Since this was originally branched from develop you'll need to rebase it on top of staging (and choose only the commits you're intending to merge).

2021-07-27 13:12 UTC, johnwcallahan requested changes
Nice work getting this running. The behavior is correct; I just have a few code comments.

2021-07-27 13:12 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +      getVolumesByLinode(linode.id) === 0 &&
It's unnecessary (and wasteful) to call this function for every element in the array, since you're testing a condition that is unrelated to the values of the array being filtered. I would suggest restructuring this logic so the check for volumes attached to this Linode happens somewhere else.

Related, this function is called a few times in the body of this component; it's worth assigning it to a variable and then referencing that:

```ts
const numAttachedVolumes = getVolumesByLinode(linode.id);
// .. and then using `numAttachedVolumes` anywhere you need to reference this value.

2021-07-27 13:12 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +  const allVolumes = Object.values(volumes.itemsById).filter(
The variable name `allVolumes` is a misnomer since by design this function is taking all volumes and filtering them down to a subset.

2021-07-27 13:12 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
> +  const isCreateMode = allVolumes.length === 0 ? true : false;
The ternary is unnecessary: `const isCreateMode = allVolumes.length === 0;` is equivalent and is more idiomatic.

2021-07-27 21:13 UTC, DevDW reviewed
I still need to go through the code of a couple of files and do a bit more testing, but it looks good so far (banner appearing where and when expected, banner formatting, dismissals, etc.)

2021-07-28 12:37 UTC, johnwcallahan reviewed
Code looks good. One UI thing: strangely, my cursor is not a pointer when hovering over the actions in the banner.

2021-07-28 13:24 UTC, tiffwong commented
@johnwcallahan what browser were you using?

2021-07-28 13:54 UTC, DevDW approved these changes
LGTM! 👍

2021-07-28 19:16 UTC, HanaXu approved these changes
LGTM! I'm not seeing the cursor issue in Chrome or Safari

2021-07-29 11:41 UTC, tiffwong commented
@DevDW @HanaXu not sure why it dismissed your reviews but if you could give it another look, that would be great! Also as a heads up, I updated the region to be Atlanta now.

2021-07-29 13:30 UTC, DevDW reviewed
Did we get an unintended styling reversion (font size) here on the `<Notice />` component?

<img width="1164" alt="Screen Shot 2021-07-29 at 9 28 22 AM" src="https://user-images.githubusercontent.com/32860776/127500571-4cfc13a3-7ef6-4238-9af9-dba272a08104.png">

2021-07-29 14:24 UTC, HanaXu commented
Ack, it dismissed bc this is trying to merge to staging. Do we still want to merge to staging now? 🤔

2021-07-29 16:33 UTC, bnussman commented
Looks good so far! Did we intend to have any logic for conditionally rendering on VolumesLanding.tsx though?

2021-07-29 16:40 UTC, DevDW approved these changes
LGTM -- there are some git history issues from the messiness of this release cycle... may need to drop `8bd3796` or even rebase to `develop` once it is brought up to current with the master branch.

2021-07-29 16:50 UTC, tiffwong commented
@bnussman nope, the only condition is the flag

2021-07-29 17:13 UTC, bnussman approved these changes

2021-07-29 17:18 UTC, HanaXu approved these changes

2021-07-29 20:18 UTC, johnwcallahan requested changes

2021-07-29 20:18 UTC, johnwcallahan commented on packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
> +                      High-performance NVMe block storage is currently availible
spelling of "available".

2021-07-29 20:18 UTC, johnwcallahan commented on packages/manager/src/components/Notice/Notice.tsx
> +    borderLeft: `5px solid ${theme.color.green}`,
This appears to be a global change.. is that intended?

<img width="343" alt="Screen Shot 2021-07-29 at 4 16 10 PM" src="https://user-images.githubusercontent.com/16911484/127559952-0abd0e9b-550a-4b28-ba2a-7668f94238ac.png">

2021-08-02 10:23 UTC, tiffwong commented on packages/manager/src/components/Notice/Notice.tsx
> +    borderLeft: `5px solid ${theme.color.green}`,
Yeah, Matthew had updated the designs on sketch so I decided to make them match since I was inside this component already

2021-08-02 20:35 UTC, johnwcallahan approved these changes

2021-08-03 11:09 UTC, merged