Marketplace Add: Q3 Release
linode/manager pull request #7799
Opened 2021-07-27 19:09 UTC by hmorris3293

## Description
This PR adds the fakespec & svgs for our Q3 release for Marketplace

## Type of Change
 * Non breaking change ('update', 'change')
 
## Note to Reviewers
Full release for prod will need to be coordinated with Marketing. ESTIMATED: August 23rd

2021-07-28 14:25 UTC, tiffwong reviewed
Hmm I don't see aaPanel, Chevereto, JetBackup, MagicSpam, Moodle, Nirvashare, Severalnines, or Splunk on Marketplace 🤔

2021-07-28 15:02 UTC, HanaXu commented
@tiffwong There needs to be some additional stuff done in LaunchDarkly, will look into this later

2021-07-28 20:16 UTC, bnussman reviewed
Loooks good so far, but I can't get the drawer to open for `NirvaShare`

2021-07-28 20:19 UTC, bnussman commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +    name: 'Nirvashare',
Capitalize the `s` to fix the drawer not opening for this one. It should like like:

```ts
name: 'NirvaShare',
```

2021-07-28 20:22 UTC, bnussman requested changes
Once we get `Nirvashare` fixed this should be good to go (along with updating the feature flags). 

On a another note and out of the scope of this PR we really should fix the drawer animation on first open 
https://user-images.githubusercontent.com/6440455/127390376-055ec08c-2902-4f93-8461-d7215b8cea73.mov

2021-07-30 14:47 UTC, HanaXu requested changes
The colored icons for the newly added apps are not visible in the drawer, though they are present in the DOM. Looks like some kind of styling issue 🤔 

![image](https://user-images.githubusercontent.com/14323019/127670409-22b6aac8-a955-4025-90de-ea01ce799e44.png)

2021-07-30 14:47 UTC, HanaXu commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +        title: 'Deploy Aapanel With Marketplace Apps',
aaPanel

2021-08-02 14:27 UTC, HanaXu commented on packages/manager/src/features/OneClickApps/FakeSpec.ts
> +          'https://www.linode.com/docs/guides/deploy-aaPanel-with-marketplace-apps',
The capital `P` in this href link might be an issue. We don't capitalize the other apps in the `docs/guides/deploy` links

2021-08-04 14:00 UTC, tiffwong approved these changes
Looks great! The documentation link for several of the apps don't work yet but I'm assuming those will be published closer to when this will be released.

2021-08-04 15:48 UTC, bnussman approved these changes
Looks good now, like @tiffwong said, lets check the links to the Linode guides before this is shipped

2021-08-06 16:20 UTC, hmorris3293 commented
Doc URLs are updated, you can refer to the "slug:" in the doc PR's that correspond to the release: https://github.com/linode/docs/pulls?q=is%3Apr+is%3Aopen+Marketplace+add%3A

2021-08-06 17:45 UTC, HanaXu approved these changes

2021-08-06 17:46 UTC, merged