M3-5248: Change look of Selectable Linode Plan to fix wrapping
linode/manager pull request #7802
Opened 2021-07-27 21:24 UTC by bnussman

## Description

- Refactors `SelectionCard.tsx` to be a functional component
- Removes the check icon from the selected plan and changes selected state
  - The goal here is to make things like `2GB RAM` not wrap so it is more clear and readable

Before:
<img width="310" alt="Screen Shot 2021-07-27 at 5 22 58 PM" src="https://user-images.githubusercontent.com/6440455/127229222-be78d474-f7e1-40ec-9962-03b66074c240.png">

After:
<img width="310" alt="Screen Shot 2021-07-27 at 5 22 27 PM" src="https://user-images.githubusercontent.com/6440455/127229255-dc6b1888-cadf-43b9-bd21-4751c71b2f87.png">

## How to test

- Test selecting a Linode plan at `/linodes/create` on a small screen size

2021-07-28 16:45 UTC, tiffwong commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +      maxWidth: '32px',
Instead of `'32px'`, you can actually just write these as `32`

2021-07-28 16:46 UTC, tiffwong commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +      borderRadius: '16px',
Same thing regarding `'16px'` here

2021-07-28 16:47 UTC, tiffwong commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +      borderColor: theme.palette.primary.main,
This can be rewritten as "border: `1px solid ${theme.palette.primary.main}`"

2021-07-28 16:47 UTC, tiffwong commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +      borderColor: theme.palette.primary.main,
(but make sure the line is surrounded by `)

2021-07-28 17:18 UTC, tiffwong commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +    border: '1px solid ' + `${theme.bg.main}`,
This can also be wrapped entirely with ticks instead of concatenating them

2021-07-28 17:25 UTC, tiffwong requested changes
Looks great! Left a few cleanup items and the only other thing that needs to be changed is dark mode
<img width="632" alt="Screen Shot 2021-07-28 at 6 19 25 PM" src="https://user-images.githubusercontent.com/7692354/127367594-8b924013-66be-454d-b4ab-ee03feb588eb.png">

2021-07-29 13:55 UTC, bnussman commented
Changed the selected colors, take a look at the video in the PR description

2021-07-29 14:10 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +            variant="selectable"
Should I make this change on other selectable places like `/linodes/create?type=Clone%20Linode`?

2021-07-29 14:14 UTC, tiffwong commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +            variant="selectable"
That would be great!

2021-07-29 14:15 UTC, tiffwong approved these changes
Looks much better now! 🎉

2021-07-29 16:58 UTC, HanaXu reviewed
Changes look good! Left some cleanup comments

2021-07-29 16:58 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +          [classes.disabled]: disabled === true,
This can be
```
checked,
[classes.disabled]: disabled
```

2021-07-29 16:58 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +          selectionCard: true,
Is `selectionCard: true` needed?

2021-07-29 16:58 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +      {content()}
I don't think `content()`, `renderVariant()` or `cardGrid()` need to be functions. What about turning `renderVariant` into an object that returns jsx, replace `renderVariant()` in `content()` with a ternary, etc?

2021-07-29 20:34 UTC, DevDW approved these changes
I agree with @HanaXu that those handful of functions can be refactored to not be functions, but everything else looks good 👍

2021-07-30 14:18 UTC, HanaXu approved these changes
LGTM!

2021-07-30 14:18 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> -      default:
Let's remove the comment above the `check` case since it's no longer being used as the default case

2021-07-30 15:22 UTC, merged