M3-5321: Add restricted user support for Firewalls
linode/manager pull request #7838
Opened 2021-08-09 21:38 UTC by HanaXu

## Description
Adds restricted user support for Firewalls

## How to test
In `/account/users/<username_here>/permissions` for a limited user:

- The ability to add Firewalls should now be an option under `Global Permissions`
- You should be able to see Firewalls, similar to other entities, under `Specific Permissions`

In `/firewalls`:

- If a user has no permissions for a specific Firewall, the firewall row should not display at all
- If a user has `read_only` permissions for a specific Firewall, the buttons for that firewall should be disabled and hovering over it should display tooltip text explaining why
- If a user has `read_write` permissions for a specific Firewall, the buttons for that firewall should not be disabled
- If a user does not have the ability to add Firewalls, the Create Firewall drawer should display an error notice at the top and the inputs should be disabled

In `/firewalls/id`:
- If a user has `read_only` permissions, there should be an error notice under the Rules/Linodes tab and the inputs should be disabled
    - In the Linodes tab, I specifically left the Linode label clickable, let me know if I should disable that as well

To add a Firewall to a Linode, you need read/write permissions on the Firewall and on the Linode

2021-08-10 14:28 UTC, bnussman requested changes
Looks like we need to check for the add_firewall grant in `packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx`. Right now it only checks if a user is restricted, not the actual add permission for Firewalls. 

<img width="346" alt="Screen Shot 2021-08-10 at 10 26 20 AM" src="https://user-images.githubusercontent.com/6440455/128884806-00323b98-91dc-4417-8051-936b860df402.png">
<img width="1496" alt="Screen Shot 2021-08-10 at 10 19 07 AM" src="https://user-images.githubusercontent.com/6440455/128884613-c8bc6e2c-2a4b-444f-a5df-08b492d5e0ea.png">

2021-08-10 14:28 UTC, bnussman commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
> +          error={true}
just use `error` shorthand

2021-08-10 18:01 UTC, bnussman commented
One thing I am noticing (API related) is that a restricted user can create a Firewall, but then by default, that restricted user **does not** have read or write perms on the firewall they created. This behavior seems confusing and I think we should propose that if a restricted user creates a Firewall, they should have default access to read and write on it.

2021-08-10 18:20 UTC, HanaXu commented
@bnussman Good catch, that will be addressed in ARB-2671

2021-08-10 21:17 UTC, bnussman approved these changes

2021-08-11 19:02 UTC, DevDW approved these changes
Nice job! 🚢

2021-08-12 14:45 UTC, merged