M3-5384: Add support for multiple payment methods in make payment drawer
linode/manager pull request #7866
Opened 2021-08-17 15:26 UTC by HanaXu

## Description
- Adds support for displaying multiple payment methods in the Make a Payment drawer
- If a user is making a payment through the action dropdown, auto-select that payment in the Make a Payment drawer
- Refactor CardBase into a functional component
- Refactor variant logic out of SelectionCard; accept a renderVariant function instead, remove duplicate css
    - I went ahead and deleted the check mark since it was only being used in one other place and selectable does the job

## How to test
The Make a Payment drawer should now display multiple payment methods. The default payment method is auto-selected unless the user opened the drawer through the payment method dropdown menu, then that payment method is selected. Making a payment should charge the selected card (check the network tab).

Check places in the app where the SelectionCard component is used, ensure it looks good on mobile and that there are no regressions.

2021-08-17 15:26 UTC, HanaXu commented on packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
> -    },
Added width to the svg itself

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/assets/icons/payment/googlePay.svg
> +<svg id="G_Pay_Acceptance_Mark" width="33" enable-background="new 0 0 1094 742" version="1.1" viewBox="0 0 752 400" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
Is this causing a regression in the Add Payment Method drawer?

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
> +                      </Grid>
![Screen Shot 2021-08-17 at 12 07 14 PM](https://user-images.githubusercontent.com/6440455/129761738-bbcd1cd9-a343-415d-8c55-d25b44f0c0bd.png)
I find that the placement of the `DEFAULT` being different to be a bit odd looking, but I personally don't mind it.

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
> +                </Typography>
We should be consistent with the `:`'s

![Screen Shot 2021-08-17 at 12 21 00 PM](https://user-images.githubusercontent.com/6440455/129763692-9d2bcf99-a001-40ce-a7b9-ce5d03435641.png)

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
> +    })
Use this, no need to spread here
```ts
makePayment(makePaymentData)
```

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
> +                    );
Can we return `null` instead of `<Grid />`?

2021-08-17 16:37 UTC, bnussman commented on packages/manager/src/assets/icons/payment/googlePay.svg
> +<svg id="G_Pay_Acceptance_Mark" width="33" enable-background="new 0 0 1094 742" version="1.1" viewBox="0 0 752 400" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
The icon got tiny

![Screen Shot 2021-08-17 at 12 31 18 PM](https://user-images.githubusercontent.com/6440455/129764920-6bc71e91-49bf-4908-a612-203bb495b5ba.png)

2021-08-17 19:21 UTC, bnussman reviewed
Would it be possible to line up the right side of the **Pay Now** button and the selectable cards?

![Screen Shot 2021-08-17 at 3 20 34 PM](https://user-images.githubusercontent.com/6440455/129787421-5c76b12c-bbc4-461a-8279-b746a6bbce31.png)

2021-08-17 20:01 UTC, HanaXu commented
@bnussman good catch! 🔍

2021-08-18 13:59 UTC, bnussman requested changes
When a user clicks a different payment method in the drawer, can we update the URL in the address bar with the new ID? This isn't super important, but could be useful for some users and we do it many other places in Cloud Manager.

2021-08-18 17:58 UTC, HanaXu commented
@bnussman I decided to pass the id using the state instead of in the url since most users won't know what their payment method id is, and this makes the code less complicated

2021-08-19 15:41 UTC, tiffwong approved these changes
Couldn't find any regressions, great job!

2021-08-19 15:47 UTC, bnussman approved these changes
Awesome job!

2021-08-19 17:11 UTC, DevDW approved these changes
LGTM! ➕➕

2021-08-19 17:11 UTC, DevDW commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +  renderVariant?: () => any;
`renderVariant?: () => JSX.Element;`

2021-08-19 18:05 UTC, ndukatz approved these changes
Looks good. I didn't find any regressions and it still passes google pay tests with the update I pushed up to this branch. I will add a bit more testing around this later.

2021-08-19 18:22 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +  renderVariant?: () => any;
I made this any since the `renderVariant` function in `PaymentDrawer.tsx` can return null if the payment method is not the default and TS complains about that since null is not a JSX element

2021-08-19 18:36 UTC, DevDW commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +  renderVariant?: () => any;
I see, how about `renderVariant?: () => JSX.Element | null;`?

2021-08-19 19:05 UTC, HanaXu commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> +  renderVariant?: () => any;
Oh yeah 😅

2021-08-19 21:15 UTC, merged