M30---5401 eu contract cluster create
linode/manager pull request #7928
Opened 2021-09-07 15:30 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-09-07 16:27 UTC, bnussman requested changes

2021-09-07 16:27 UTC, bnussman commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +        isEURegion(region) && !isRestrictedUser ? (
We also don't want this to render if the user has signed the agreement already. So we only render the agreement when `agreements?.eu_model === false`.
```ts
!profile?.restricted && agreements?.eu_model === false && isEURegion(selectedRegion)
```

2021-09-07 16:27 UTC, bnussman commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +  const { _isRestrictedUser: isRestrictedUser } = useAccountManagement();
Consider just using `useProfile`. `useAccountManagement` may have some unnecessary overhead.

2021-09-07 16:27 UTC, bnussman commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +      })
This may just be me, but the two `.then()`'s are sketching me out. Can we consolidate the `.then()`'s into one function?

Also, you can pull in new changes into this PR from `gdpr-compliance` and update the API call to use our React Query Mutation with this logic around it. 

```ts
import {
  reportAgreementSigningError,
  useAccountAgreements,
  useMutateAccountAgreements,
} from 'src/queries/accountAgreements';

...

const { mutateAsync: updateAccountAgreements } = useMutateAccountAgreements();

...

if (hasAgreed) {
      updateAccountAgreements({
        eu_model: true,
        privacy_policy: true,
      }).catch(reportAgreementSigningError);
}
```

2021-09-07 16:34 UTC, codyfinn commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +      })
The `.then()` is needed to ensure that the EU agreement happens after and only if the cluster creation was successful.

2021-09-07 19:49 UTC, johnwcallahan commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +      })
I believe the two `then()`s that @bnussman is referring to are:

1. the first `then()` which uses history.push to navigate the user to the cluster details page
2. the second `then()` which calls `signAgreement`

These can be consolidated to something like:

```ts
createKubernetesCluster(payload).then(cluster => {
  push(`/kubernetes/clusters/${cluster.id}
  if (hasAgreed) {
    updatedAccountAgreements({...}).catch(reportAgreementSigningError);
  }
}).catch( // handle cluster creation error

2021-09-07 20:59 UTC, johnwcallahan requested changes
One quick blocking comment, everything else lgtm.

2021-09-07 20:59 UTC, johnwcallahan commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      disabled={pools.length < 1 || !hasAgreed}
This needs to take `showGDPRCheckbox` into account as well. (Currently the button is disabled if you're a customer that doesn't need to sign the agreement)

2021-09-07 21:00 UTC, bnussman commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +    isEURegion(region) && !profile?.restricted && !agreements?.eu_model;
Can we change `!agreements?.eu_model` to `agreements?.eu_model === false`?

@johnwcallahan mentioned that this would be prefered so in the case `agreements` is undefined, the checkbox would show.

2021-09-07 21:00 UTC, bnussman approved these changes

2021-09-07 21:29 UTC, bnussman approved these changes

2021-09-07 22:07 UTC, HanaXu approved these changes
LGTM, just left two minor non-blocking comments! ☑️

2021-09-07 22:07 UTC, HanaXu commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +    setAgreed(!hasAgreed);
Should we use the function updater pattern here?
```typescript
setAgreed((hasAgreed) => !hasAgreed)
```

2021-09-07 22:07 UTC, HanaXu commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +    needsAPool || (!hasAgreed && showGDPRCheckbox)
I don't think `needsAPool` needs to be a variable as it's kind of self explanatory

2021-09-08 13:12 UTC, johnwcallahan approved these changes
Agreed with Hana's minor comments, looks good though.

2021-09-08 15:37 UTC, codyfinn commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +    needsAPool || (!hasAgreed && showGDPRCheckbox)
I think while it is very easy to understand the meaning of `pools.length < 1` putting it in a variable does improve the readability of the value of `disableCheckout` as well as shortening what is already a long variable declaration.

2021-09-08 15:43 UTC, merged