Upgrade Sentry SDK
linode/manager pull request #7948
Opened 2021-09-14 16:20 UTC by bnussman

## Description

- Updates `@sentry/browser` to the latest version `6.12.0`
- I'm not exactly sure why the lock file changed a ton but I think it is ok

## How to test

- Define `REACT_APP_SENTRY_URL` in your local env
  - To get the Sentry URL ask me or find it in Sentry (Cloud Manager -> Project Settings -> DSNs)
- Add some code in Cloud Manager anywhere that will call Sentry's captureException function to test that exceptions get sent to Sentry
```ts
import { captureException } from '@sentry/browser';

captureException("Test Sentry");
```
- Go to Sentry and verify that exceptions are captured as expected

2021-09-28 21:26 UTC, DevDW reviewed
I keep getting errors on the POST requests for some reason. When I check DevTools, the "Status" column on the Network tab says "blocked:other" for them, and in the console I see entries that say `net::ERR_BLOCKED_BY_CLIENT`

2021-10-01 21:28 UTC, johnwcallahan requested changes
We'll want to disable auto session tracking, since v6 does this by default now: https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#600

Also, I believe the excessive lockfile changes can be fixed by manually updating package.json then running `yarn install` from the root directory.

2021-11-17 17:00 UTC, DevDW reviewed
I'm still seeing what I saw back in September, but interestingly, I also encountered an app crash on this branch when logging into a dev account that has Managed enabled 🤔 

<img width="1059" alt="Screen Shot 2021-11-17 at 11 58 33 AM" src="https://user-images.githubusercontent.com/32860776/142246392-43acb59a-999c-47e4-a008-81f54f650328.png">

safe accessing the `[0]` and `.reason` seemed to fix it

edit: I was able to use `captureException` successfully but had to use an Incognito Chrome window to circumvent the blocks I was encountering. Ready to approve this once we figure out the crash issue

2021-11-17 17:50 UTC, HanaXu approved these changes
POSTing works for me. I am also seeing the same Managed error as Dajahi, approving pending the safe access change

2021-11-29 17:09 UTC, bnussman commented
I want to merge, but that Object()()[] error should not be possible. Will investigate further

2021-12-06 16:45 UTC, bnussman commented
Closing due to really odd dependency issues after bumping Sentry version

2021-12-06 16:45 UTC, closed without merging