M3-5530: Add IPv6 ranges to IP Transfer modal
linode/manager pull request #8037
Opened 2021-11-11 17:37 UTC by HanaXu

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-11-11 21:53 UTC, johnwcallahan requested changes
Awesome work with this, especially navigating these old components with ancient patterns!! 

Just two things I think should be addressed before moving forward:

1. Error/loading state
2. Extracting the range mapping function and adding a few unit tests. 

The other comment is a minor suggestion.

2021-11-11 21:53 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +            queryClient.invalidateQueries(queryKey);
Minor suggestion: 

I'd recommend importing `queryKey as ipv6RangeQueryKey` or something similar, and adding a comment before this line to explain why we're doing this.

2021-11-11 21:53 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +  const getLinodeIpv6Ranges = (ipv6: string | null) => {
Great thinking putting this in a separate function! 

I'd recommend going one step further and moving this function outside of the component, give`ipv6RangesData` as a second argument , and then add a few unit tests. Let me know if you want me to provide more clarity here.

2021-11-11 21:53 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +  const { data: ipv6RangesData } = useIpv6RangesQuery();
I think we could use an error state if IPv6 ranges fail to load (currently if you block requests to `*ranges*` there's a silent failure ... IPv6 ranges are missing from the appropriate dropdowns).

We probably want the error indicator to go where the `<CircleProgress />` component is rendered while loading. 

Speaking of loading... the loading state should also take into account whether or not ipv6 ranges are loading as well (from this query).

2021-11-11 22:10 UTC, DevDW reviewed
Nice work, left a couple of comments in addition to what John mentioned re: the error state

2021-11-11 22:10 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +  const getLinodeIpv6Ranges = (ipv6: string | null) => {
would be good to add a unit test for this given the multiple layers of operation on strings

2021-11-12 17:53 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +  const { data: ipv6RangesData } = useIpv6RangesQuery();
I didn't want the IPv6 error state to block IPv4 stuff so I decided not to replace the `<CircleProgress />` component with the error notice.

![image](https://user-images.githubusercontent.com/14323019/141512517-0cacea28-fe2f-471f-b928-e227422febd2.png)

2021-11-12 20:15 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
> +  const { data: ipv6RangesData } = useIpv6RangesQuery();
@HanaXu good idea!

2021-11-12 20:18 UTC, johnwcallahan approved these changes
Great work @HanaXu! This LGTM.

2021-11-12 21:12 UTC, DevDW approved these changes
🚢

2021-11-12 21:17 UTC, merged