[WIP] M3-5531: Handle IPv6 Range Deletion
linode/manager pull request #8039
Opened 2021-11-11 19:03 UTC by bcmertz

## Description

Add support for deleting IPv6 Ranges

## How to test

While pointed at dev, add IPv6 range through API like: `curld networking/ipv6/ranges POST '{"linode_id":<linode_id>,"route_target":<route_target>,"prefix_length":64}'` , delete IPv6 range in CM, confirm success

2021-11-11 20:06 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPv6RangeActions.tsx
> +}
Could this be refactored in the a function component?

2021-11-11 22:10 UTC, johnwcallahan requested changes
Great job getting this working @bcmertz!!

Let's see if we can reduce the code duplication, which will help our future selves when we need to work on this again. 

Both the Actions and Confirmation components are copied over from their `IP` counterparts. The changes between the "IP" and "IPRange" versions are minimal. Can we find a way to dictate those differences with props, maybe? (or render props). 

Let me know if you have any questions or need any assistance 👍

2021-11-11 22:10 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPv6RangeConfirm.tsx
> +            ipv4: linode.ipv4.filter((eachIP) => eachIP !== data.IPv6Range),
Instead of updating the Linode itself, I _think_ this will need to invalidate the ipv6 range query and the linode/ips Redux state.

2021-11-11 22:27 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPv6RangeConfirm.tsx
> +            ipv4: linode.ipv4.filter((eachIP) => eachIP !== data.IPv6Range),
👍 good point, missed that in the first pass - on it!

2021-11-11 22:48 UTC, DevDW reviewed
I was able to successfully delete an IPv6 range 👍 

It would be great if we could have `DeleteIPv6RangeActions.tsx` and `DeleteIPv6RangeConfirm.tsx ` converted to function components

2021-11-11 22:48 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
> +    (ipType === 'IPv4 – Public' || ipType === 'IPv6 – Range')
We could also make an array, `['IPv4 – Public', 'IPv6 – Range']` (can be stored in a variable)

and change this OR condition to [raw array or variable name here]`.includes(ipType)`

2021-11-12 18:54 UTC, bcmertz commented
Components deduplicated and combined back into 1, and converted into functional components

2021-11-12 20:18 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPv6RangeConfirm.tsx
> +            ipv4: linode.ipv4.filter((eachIP) => eachIP !== data.IPv6Range),
it appears this isn't necessary since we requery in `refreshIPs` (LinodeNetworking)

2021-11-12 20:51 UTC, DevDW approved these changes
LGTM, left a few optional items for cleanup

2021-11-12 20:51 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +      removeIPRangeDialogOpen: !this.state.removeIPRangeDialogOpen,
could we set this explicitly to `true`?

2021-11-12 20:51 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
> +          : 'Are you sure you want to delete this IPv6 Range? This action cannot be undone.'}
since only the `IP Address`/`IPv6 Range` text is changing, we could do

```
{`Are you sure you want to delete ${linode ? 'this IP Address' : 'this IPv6 Range'}? This action cannot be undone.`}
```

2021-11-12 20:51 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
> +      .then((response) => {
do we need the unused `response` variable or can it be replaced with `_`?

2021-11-12 20:55 UTC, johnwcallahan approved these changes
Nice work with the class -> function component refactor! Looks good to me, left one thing that can be done as a follow-up.

2021-11-12 20:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
> +  const deletable = ['IPv4 – Public', 'IPv6 – Range'];
Minor: a more descriptive variable name here would be ideal: `deletableIPTypes`, maybe?

2021-11-12 20:55 UTC, johnwcallahan commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
> +      title={`Delete ${IPAddress}?`}
Not required for merge, but would be good as a follow-on: 

It may be helpful to users and overall more consistent if we include the prefix in the modal title (i.e. include `/64` or `/56`).

2021-11-12 21:00 UTC, HanaXu approved these changes
Great job! Just left one optional cleanup comment 🚀

2021-11-12 21:12 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx
> +  }) => void;
much cleaner, done! thanks!

2021-11-12 21:42 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
> +      title={`Delete ${IPAddress}?`}
added!

2021-11-12 21:43 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx
> +      .then((response) => {
done good call :)

2021-11-12 22:58 UTC, merged