M3-5190: React Query for Object Storage
linode/manager pull request #8046
Opened 2021-11-17 04:01 UTC by bnussman

> ⚠️ Work in progress

## Description

- React Query for Object Storage 

## How to test

- Test **all** Object Storage Functionality

2021-11-23 20:28 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
> -  }
Re-add this type of error state

2021-11-30 19:46 UTC, codyfinn requested changes
Looks good overall. The way we are searching through the paginated data seems pretty inefficient. It would be nice to do so in a more performant way.

2021-12-02 16:47 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +  };
Yes, but it's my understanding that two objects can't have the same name. Is my understanding correct?

2021-12-02 17:59 UTC, codyfinn commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +  };
Yeah looking closer at how the API handles it that seems to be the case. I still think finding a way to not continue searching after you have found the entry to delete would be worth it though.

2022-01-31 20:57 UTC, HanaXu reviewed
Can we merge develop in and resolve conflicts?

2022-02-01 21:53 UTC, codyfinn commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +  };
```suggestion
  const removeOne = (objectName: string) => {
    const newPagesArray = produce(data?.pages, (draft) => {
      let objectIndex = -1;
      const pageIndex = draft?.findIndex((thisPage) => {
        const _objectIndex = thisPage.data.findIndex(
          (object) => object.name === objectName
        );
        objectIndex = _objectIndex !== -1 ? _objectIndex : -1;
        return _objectIndex !== -1;
      });
      if (draft && pageIndex !== undefined && pageIndex !== -1) {
        draft[pageIndex].data.splice(objectIndex);
      }
    });

    updateStore(newPagesArray ?? []);
  };
```
Just a rough draft of what that could look like

2022-02-08 21:51 UTC, HanaXu requested changes
The error loading notice is a bit big, can we reduce the margin and maybe remove the last sentence as it's a bit redundant?

<img width="589" alt="image" src="https://user-images.githubusercontent.com/14323019/153081523-0ee83f51-9a7f-46a7-a61e-45fed047847e.png">

2022-02-08 21:51 UTC, HanaXu commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +                  ? `Delete  ${truncateMiddle(displayName(objectToDelete))}`
``Delete ${truncateMiddle(displayName(objectToDelete))}``

2022-02-08 21:51 UTC, HanaXu commented on packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
> -  const { _isRestrictedUser, accountSettings } = useAccountManagement();
There seems to be some kind of regression for the restricted user `Create Access Key` drawer

This branch:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/14323019/153079846-4431a787-88b4-4205-b1b0-384260d7fd33.png">

Prod:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/14323019/153079912-9ad1b734-74dd-41e0-82b1-b5ca9684f136.png">

2022-02-09 16:13 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +                  ? `Delete  ${truncateMiddle(displayName(objectToDelete))}`
What do you mean by this? @HanaXu

2022-02-09 16:23 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
> -  const { _isRestrictedUser, accountSettings } = useAccountManagement();
Resolved by a59f125

2022-02-09 16:44 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
> +                  ? `Delete  ${truncateMiddle(displayName(objectToDelete))}`
Didn't even notice, thank you!

2022-02-09 16:58 UTC, bnussman commented
@HanaXu Would you be ok with holding off on those UI changes to keep the scope of this PR focused?

2022-02-09 18:03 UTC, DevDW reviewed
Nice work! The functionality and Redux cleanup are looking good overall, left a few comments

2022-02-09 18:03 UTC, DevDW commented on packages/manager/src/mocks/serverHandlers.ts
> +    const buckets = objectStorageBucketFactory.buildList(10);
Why are we mocking the GET request 4 times here?

2022-02-09 19:00 UTC, bnussman commented on packages/manager/src/mocks/serverHandlers.ts
> +    const buckets = objectStorageBucketFactory.buildList(10);
When we fetch Object Storage Buckets, we make an API request for each cluster. We do this so we know if any of the clusters are offline. I mocked 4 times so I could simulate some failures to test clusters that error out. I can remove the erroring mocks prior to merge.

2022-02-10 16:45 UTC, bnussman commented on packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
> -            objectStorageBuckets.lastUpdated === 0,
Sounds good! Will re-add prefetching

2022-02-14 18:24 UTC, HanaXu approved these changes
Object Storage LGTM, great job! 🚀

2022-02-14 18:35 UTC, codyfinn approved these changes

2022-02-16 16:51 UTC, merged