M3-5549: Backup Auto Enrollment – Remove redundant head
linode/manager pull request #8051
Opened 2021-11-23 18:31 UTC by codyfinn

## Description

Removes the redundant header on the account settings backup auto enrollment section. There was also a tooltip that would show up to inform managed users that they are already auto enrolled in backups. I removed the tooltip and replaced it with a success notice.

## How to test

1. Open the Account Settings page as managed user.
2. There should be no redundant header in the back up auto enrollment section.
3. There should be a success notice informing you that you are already enrolled in auto backups.
4. Open the Account Settings page as an unmanaged user.
5. There should be no redundant header in the back up auto enrollment section.

2021-11-23 20:12 UTC, bnussman reviewed
Looks solid, but I have two minor things
- The external link icon looks really big
- I feel like the spacing below the Managed notice could be a little bit less

<img width="1667" alt="Screen Shot 2021-11-23 at 3 09 30 PM" src="https://user-images.githubusercontent.com/6440455/143096651-0e189a58-393d-4db5-9608-5bd7a08c1cb0.png">

2021-11-23 22:24 UTC, HanaXu requested changes
Agreed with Banks on removing the extra margin in the Notice

![image](https://user-images.githubusercontent.com/14323019/143138683-47d81557-eb72-42c4-a032-9153cc8d8ffc.png)

2021-12-01 17:03 UTC, tiffwong requested changes
The changes looks great other than the spacing that's been mentioned already. 

Unrelated to the changes made but the link hover state is including the space.
<img width="197" alt="Screen Shot 2021-12-01 at 4 58 34 PM" src="https://user-images.githubusercontent.com/7692354/144278960-e3a386d3-c818-4e53-81eb-4c4b380e1f6e.png">

Also `createStyles` can be replaced by `useStyles` here instead since it's a FC and there's several classes that can be removed (including `classes.link`)

2021-12-02 19:26 UTC, tiffwong approved these changes

2021-12-02 20:25 UTC, HanaXu approved these changes

2021-12-02 20:25 UTC, merged