M3-5580: Update Storybook Entity Table
linode/manager pull request #8059
Opened 2021-11-30 18:34 UTC by HanaXu

## Description
Convert file to mdx and add other instances of where EntityTable is used (Volumes/Images/Firewalls/NodeBalancers landing)

The Volume and NodeBalancer headers are imported from their component but they display as cut off, I'm not sure why
![image](https://user-images.githubusercontent.com/14323019/144106923-d88c7f5f-da06-4a08-9b09-7d79537b2d23.png)

![image](https://user-images.githubusercontent.com/14323019/144106993-ff439980-5f25-4147-ac28-8be9e366e0d4.png)

## How to test
`yarn storybook` and check the stories under `Components/Entity Table`

2021-12-02 15:34 UTC, DevDW reviewed
> The Volume and NodeBalancer headers are imported from their component but they display as cut off, I'm not sure why

I looked into this and will revisit it later today, but I couldn't quite pinpoint why this is happening. The only way I was able to fix it so far was by creating a new variable with the headers plus the visually hidden header for the Actions column, like

```
  const headers = [
      {
    label: 'Label',
    dataColumn: 'label',
    sortable: true,
    widthPercent: 40,
  },
  {
    label: 'Region',
    dataColumn: 'region',
    sortable: true,
    widthPercent: 15,
  },
  {
    label: 'Size',
    dataColumn: 'size',
    sortable: true,
    widthPercent: 5,
  },
  {
    label: 'Attached To',
    dataColumn: 'Attached To',
    sortable: false,
    widthPercent: 25,
  },
      {
      label: 'Action Menu',
      visuallyHidden: true,
      dataColumn: '',
      sortable: false,
      widthPercent: 5,
    },
  ]
```

and passing that to the `headers` prop.

2021-12-02 16:39 UTC, bnussman requested changes

2021-12-02 16:39 UTC, bnussman commented on packages/manager/src/components/EntityTable/EntityTable.stories.mdx
> +    <h2 style={{marginTop: 0}}>Volumes: </h2>
Can we remove these `<h2 />`s and use Markdown outside of the `<Canvas />` instead?

2021-12-02 16:39 UTC, bnussman commented on packages/manager/src/components/EntityTable/EntityTable.stories.mdx
> +    />
This should fix the visual error with the NodeBalancers table.

```suggestion
    <EntityTable
      entity="nodebalancer"
      toggleGroupByTag={() => false}
      isGroupedByTag={false}
      headers={nodeBalancerHeaders}
      row={{
        Component: NodeBalancerTableRow,
        data: nodeBalancers,
        handlers: {},
        lastUpdated: 1637782175231,
      }}
      initialOrder={{ order: 'asc', orderBy: 'label' }}
    />
```

2021-12-03 22:52 UTC, DevDW approved these changes
LGTM 🚢

2021-12-06 16:32 UTC, bnussman approved these changes

2021-12-06 21:05 UTC, tiffwong approved these changes
Great job!

2021-12-06 22:35 UTC, merged