M3-5609 PasswordInput component story
linode/manager pull request #8060
Opened 2021-11-30 19:19 UTC by johnwcallahan

## Description

- Convert PasswordInput story to MDX
- Remove unused styles in PasswordInput component

## How to test

Run Storybook and visit http://localhost:6006/?path=/docs/ui-elements-password-input--password-input. Run the app and ensure there are no regressions with the PasswordInput component.

2021-12-02 16:17 UTC, bnussman commented
This isn't urgent, but do we want the value field in the args table to update the actual component? 

https://user-images.githubusercontent.com/6440455/144460500-276aa9e4-1557-4e01-8f0f-acae4376e464.mov

2021-12-02 17:34 UTC, DevDW approved these changes
Aside from possibly having the input update based on what's typed into the "Control" field for `value` as Banks pointed out, this LGTM 🚢

2021-12-06 14:36 UTC, codyfinn requested changes
Everything looks good. Just left a request for change to address the point that Banks brought up.

2021-12-06 14:36 UTC, codyfinn commented on packages/manager/src/components/PasswordInput/PasswordInput.stories.mdx
> +      },
By adding a `control` field to the value object and setting a `type` field in there to null you will display the field and not allow the user to control the value.

```suggestion
      value: {
        description: 'The current value of the underlying TextField',
        control: {
          type: null,
        },
      },
```

2021-12-06 15:15 UTC, johnwcallahan commented
Thanks everyone. I made a change that will let you control the component with the ArgsTable control. This results in a "controlled component" console error in the Story, but I think that's OK in this case.

2021-12-06 15:41 UTC, codyfinn commented
> Thanks everyone. I made a change that will let you control the component with the ArgsTable control. This results in a "controlled component" console error in the Story, but I think that's OK in this case.

I think it makes more sense to not allow the user to edit it in the ArgsTable since the point of the component isn't really to display the value so much as it is to capture it.

2021-12-06 16:56 UTC, bnussman commented
@codyfinn While I agree the point of the component isn't to display the value so much as it is to capture it, there is a benefit in allowing the ArgsTable to dictate the `value` for purposes of documenting our component library and the props components utilize.

2021-12-06 16:57 UTC, bnussman approved these changes

2021-12-06 16:58 UTC, codyfinn approved these changes

2021-12-06 17:55 UTC, merged