M3-5588 Drawer component story
linode/manager pull request #8063
Opened 2021-11-30 22:18 UTC by johnwcallahan

## Description

This adds stories for the Drawer and NotificationDrawer components.

There are also a few other things going on:

- Add support for MSW in Storybook. 
	- This helps the issue that @HanaXu pointed out which is that some components make API requests.
	- We’ll need to figure out how to address this long term when we publish the component library.
- Add support for an optional parameter in the hooks that drive the NotificationDrawer.
	- This is so I could provide mock notifications and events.
- Updated the eventFactory to include better mock data.

## How to test

Run Storybook and visit http://localhost:6006/?path=/docs/components-drawer--default-story.

2021-12-02 15:18 UTC, codyfinn commented on packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
> +  const events = givenEvents ?? useEvents().events;
Would changing the `useEvents` hook make more sense in this case? We could pass the `givenEvents` as an optional parameter to the hook. If the hook would otherwise return a falsey value it would instead return the `givenEvents`;

2021-12-02 15:19 UTC, codyfinn commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +  const notifications = givenNotifications ?? useNotifications();
Same question as my comment here https://github.com/linode/manager/pull/8063/files#r761195212 but for the `useNotifications` hook.

2021-12-02 15:21 UTC, codyfinn commented on packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
> +  const events = givenEvents ?? useEvents().events;
I realized that `useEventNotifications` exemplifies the changes I am suggesting.

2021-12-02 15:21 UTC, codyfinn commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +  const notifications = givenNotifications ?? useNotifications();
I realized that `useEventNotifications` exemplifies the changes I am suggesting.

2021-12-06 15:21 UTC, johnwcallahan commented on packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
> +  const events = givenEvents ?? useEvents().events;
Great feedback. My thinking was that if you already have event data you want to use (`givenEvents`), there would be no need to use the `useEvents` hook (same thing for your other comment about useNotifications).

`useEventNotifications` and `useFormattedNotifications` both return something other than raw events/notifications, so to me it made sense to optionally receive data. It would make unit testing these hooks easier as well.

2021-12-06 16:03 UTC, HanaXu requested changes
The `show code` output is kind of unreadable 😅 

![image](https://user-images.githubusercontent.com/14323019/144879567-f9492350-4371-41d1-af55-8060e4b87d0e.png)

2021-12-06 16:33 UTC, johnwcallahan commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +- Clicking off of the drawer closes it and data will not be saved.
True! Removed.

2021-12-06 16:34 UTC, johnwcallahan commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +        description: 'Whether or not the Drawer is currently open',
I tried a few things to get around this, but wasn't able to find a good way to address it.

2021-12-06 16:35 UTC, johnwcallahan commented
> The `show code` output is kind of unreadable 😅

Good call; addressed.

2021-12-06 17:15 UTC, bnussman requested changes
Non-blocking, but it would be nice if the `Notification Drawer` Story was nested under the `Drawer` section in Storybook's sidebar.

2021-12-06 17:15 UTC, bnussman commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +          </Button>
Update button order so action button is on the right

```suggestion
          <Button buttonType="secondary" onClick={close}>
            Cancel
          </Button>
          <Button buttonType="primary" onClick={close}>
            Save
          </Button>
```

2021-12-06 17:15 UTC, bnussman commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +- Drawers can also be closed by clicking the “X” icon or the “Close” button.
Include `esc` key for closing drawers

```suggestion
- Drawers can be closed by pressing the `esc` key, clicking the “X” icon, or clicking the “Cancel” button.
```

2021-12-06 17:15 UTC, bnussman commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +    </Button>
Update button order so action button is on the right here also

```suggestion
    <Button buttonType="secondary" onClick={close}>
      Cancel
    </Button>
    <Button buttonType="primary" onClick={close}>
      Save
    </Button>
```

2021-12-06 17:54 UTC, johnwcallahan commented
@bnussman great feedback; addressed!

2021-12-06 18:22 UTC, HanaXu requested changes

2021-12-06 18:22 UTC, HanaXu commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +</Canvas>
What about removing this and renaming the `Component API` story to `Default` since they basically seem to be the same? This would also cleanup the sidebar a bit (specifically in Canvas view, there is no difference between `Default` and `Component API`)

2021-12-06 20:28 UTC, tiffwong commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +</Canvas>
It seems like the code generated from the ArgsTable never updates regardless of the changes made under the `Component API` example so I'm okay with moving it up. In that case, would we move the other examples below the ArgsTable (ie. for Buttons: primary, ArgsTable, secondary, outlined)?

2021-12-06 20:32 UTC, tiffwong approved these changes
I arbitrarily picked `###` to dictate "Overview" and other subheadings to be `h3` but we should probably decide on some standard so that everything looks cohesive. Otherwise everything looks good and amazing job getting MSW linked to Storybook!

2021-12-06 21:26 UTC, bnussman approved these changes
Looks good and great job with the MSW

2021-12-08 13:02 UTC, johnwcallahan commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
> +</Canvas>
You're right that the code in the ArgsTable doesn't change, but the component does change (e.g. if you toggle "Wide" in the ArgsTable, the drawer will be updated accordingly), which is why I think a separate component specifically for the ArgsTable makes sense. It's less clear in this example with the Drawer since you have to click a button in order to see the drawer.

(Also, I'd love to eventually find a way to update the code when values in the ArgsTable changes!)

2021-12-08 17:39 UTC, HanaXu approved these changes

2021-12-13 12:58 UTC, merged