M3-5591: Add Story for Paper
linode/manager pull request #8068
Opened 2021-12-03 18:47 UTC by codyfinn

## Description

Adds a story in storybook mdx format for the Paper component

## How to test

Ensure the Paper component has a story that renders correctly in storybook.

2021-12-09 15:44 UTC, tiffwong commented on packages/manager/src/components/Paper.stories.mdx
>  <Meta title="Components/Papers" component={Paper} />
Can you rename this from `Papers` to `Paper`? This way it own't create another level before you get to the docs

2021-12-09 15:47 UTC, tiffwong commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
We never use the `error` prop from what I can tell so can we remove the related logic and styles from the doc and component?

2021-12-09 15:49 UTC, tiffwong commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
We also have an outlined variant which should be added to the `ArgsTable`

2021-12-09 15:50 UTC, tiffwong requested changes
Left some cleanup items

2021-12-09 18:56 UTC, HanaXu commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
Looks like we use `error` in the `PreviewReply` component. But since that's the only place it's used, I agree with Tiff on removing the `error` prop. We can just display the error in the `PreviewReply` component

2021-12-13 16:39 UTC, bnussman requested changes
No need for the wrapping `<div />` here

2021-12-13 17:11 UTC, DevDW commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
What would be the benefit of removing the `error` prop here? I'm inclined to say we should keep it, unless we're going to be deprecating the `error` prop for the component and removing it from the `PreviewReply` component.

2021-12-13 20:47 UTC, DevDW commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
@HanaXu Ah okay. Here's what it looks like in the app with an error:

<img width="1185" alt="Screen Shot 2021-12-13 at 3 41 35 PM" src="https://user-images.githubusercontent.com/32860776/145885679-b0f995b2-348c-470d-bd0e-9032c4e66f09.png">

I would agree with removing the prop and cleaning up the `PreviewReply` component to use a `<Notice />` instead.

The way it is currently doesn't work too well; there's an error indicated but it still shows a preview anyway.

So if there is an error, I think `<PreviewReply />` should render an error notice instead of the paper with markdown.

2021-12-13 21:13 UTC, codyfinn commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
I can't seem to get the error to show up. I tried to upload a giant file and that gave me an error but that showed up as a notice in the reply page. Not sure what the error does in the `PreviewReply` case.

2021-12-14 18:22 UTC, bnussman commented
Looks solid! Last thing to add would be the proposed copy from Jira.

2021-12-14 19:27 UTC, bnussman approved these changes

2021-12-14 20:50 UTC, HanaXu requested changes

2021-12-14 20:50 UTC, HanaXu commented on packages/manager/src/components/Paper.stories.mdx
> +        error: undefined
We can make a tech debt ticket to address removing the error prop from the Paper component. For now, can we set the error to be an empty string so that there's one less click to update the string?

![image](https://user-images.githubusercontent.com/14323019/146077170-36ac1c67-1761-4f6d-9977-8d4aea8fbe78.png)

2021-12-15 14:54 UTC, tiffwong commented on packages/manager/src/components/Paper.stories.mdx
> +<hr />
Can we remove this divider?

2021-12-15 14:55 UTC, tiffwong approved these changes
Left one optional cleanup item but otherwise lgtm!

2021-12-15 15:54 UTC, HanaXu approved these changes

2021-12-16 18:26 UTC, merged