M3-5610: Storybook for Radios
linode/manager pull request #8071
Opened 2021-12-06 20:11 UTC by bnussman

## Description

- Updates Storybook for the Radio component
- Now uses mdx
- Fixed padding on radio causing ripple to be a non-square size
- Use makeStyles() in the`<Radio />` component
- Removed the `error` and `warning` variant

## How to test

- Check for regressions with `<Radio />`
- View all Radio stories in Storybook (`yarn storybook`)

## Args Notes

It would be nice if Storybook automatically knew **all** of the types we generally extend in our own components (in this case all ButtonProps) so we don't have to manually populate the args. Seems like we're not the only ones having this issue. Typescript isn't inferring all prop types, so our args table is not completely populated with all possible props form MUI that can be used on the component 😕

[This fix](https://storybook.js.org/docs/ember/configure/typescript#overriding-the-configuration-to-infer-additional-props) did not seem to work on my initial attempt 

https://github.com/storybookjs/storybook/issues/12558

2021-12-07 18:23 UTC, bnussman commented on packages/manager/src/themeFactory.ts
> +            backgroundColor: 'rgba(36, 83, 233, 0.04)',
Any idea on how I could clean this up without using an arbitrary color?

2021-12-09 13:37 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +### Reasons for A Default Selection
Just saw that the "A" is also capitalized in the ticket but can you make it lowercase?

2021-12-09 13:37 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +## Radio
Since there's the header above, we probably don't need this one since it's a duplicate

2021-12-09 13:39 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +## Controled Radio
I think "controlled" is spelled with two `l`'s

2021-12-09 13:40 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +      color: "primary",
I don't think we ever use the `color` prop for `Radio` so we can remove it from the code and the docs

2021-12-09 13:54 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +      color: "primary",
Actually I see that we use it inside the `Radio` component itself so we could just hide it from the `ArgsTable` since the prop is always `primary`

2021-12-09 13:59 UTC, tiffwong commented on packages/manager/src/themeFactory.ts
> +            backgroundColor: 'rgba(36, 83, 233, 0.04)',
I'm not seeing these styles be applied 🤔 

Also `colorSecondary` seems to apply to `Radio`'s that have `color="secondary"` so I don't think anything of those styles are ever used on Cloud so we can probably remove that whole section

2021-12-09 14:55 UTC, tiffwong requested changes
Left some items that can be cleaned up a bit. 

Also I think we can exclude the following props from the `ArgsTable`:
- `color`
- `disableRipple`
- `inputProps`
- `inputRef`
- `size` (this has no effect from what I can see)
- `disableFocusRipple`
- `centerRipple`
- `disableTouchRipple
- `focusRipple`
- `focusVisibleClassName`
- `onFocusVisible`
- `TouchRippleProps`

2021-12-09 17:12 UTC, bnussman commented on packages/manager/src/themeFactory.ts
> +            backgroundColor: 'rgba(36, 83, 233, 0.04)',
I made this change to fix this pink background around some Radios

Here's an example:
<img width="1344" alt="Screen Shot 2021-12-09 at 12 02 28 PM" src="https://user-images.githubusercontent.com/6440455/145442170-38d460da-547b-4395-9692-e388429d3fce.png">

Should we fix this in the styles the way I did, or should we address this in the file the component is used in?

To fix it without modifying our theme, I would have to replace 
```ts
control={<Radio />}
``` 
with
```ts
control={<Radio color="primary" />}
``` 
on line `242` and `283` of `packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx`

What do you think @tiffwong

2021-12-09 19:54 UTC, HanaXu requested changes
Can we fix the Controlled Radio and Radio Group being cut off in Canvas view?

![image](https://user-images.githubusercontent.com/14323019/145466219-e72b2352-946a-41e8-9447-7c005044d4c2.png)

![image](https://user-images.githubusercontent.com/14323019/145466253-799c5981-e59b-468d-ba9f-edde69d50e51.png)

2021-12-09 19:54 UTC, HanaXu commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +    'edge',
Can we remove `edge` from exclude since it does change the UI? And add `required` to exclude since there's no visual change

https://user-images.githubusercontent.com/14323019/145465159-b1465f37-75fb-4598-a9e4-9d360c300605.mov

2021-12-10 19:38 UTC, bnussman commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +    'edge',
I was thinking the `required` prop may have some accessibility implications, but I went ahead and removed it

2021-12-10 20:23 UTC, tiffwong commented on packages/manager/src/themeFactory.ts
> +            backgroundColor: 'rgba(36, 83, 233, 0.04)',
In that case, let's go with the way you originally had it. The only way to not use an arbitrary code is to create a variable but unless we plan to reuse the color for something else, the way you did it is fine

2021-12-10 20:25 UTC, tiffwong commented on packages/manager/src/components/Radio/Radio.stories.mdx
> +    'edge',
Hmm might be nice to keep required just so we know it's an option

2021-12-10 20:25 UTC, tiffwong approved these changes
Great work on this! 🎉

2021-12-10 21:19 UTC, bnussman commented
## 🔎 **Preview**
[https://m3-5610-update-story-for-radio.manager-ec2.pages.dev/](https://m3-5610-update-story-for-radio.manager-ec2.pages.dev/)

2021-12-10 21:31 UTC, HanaXu approved these changes
🚀

2021-12-13 16:21 UTC, merged