M3-5582: Update stories for Forms
linode/manager pull request #8072
Opened 2021-12-07 14:45 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-12-15 16:54 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +- Consider using [radio buttons](?path=/docs/ui-elements-radio--interactive) if there are 3 or fewer items to select. While a dropdown looks simpler and saves space it can be beneficial for a custome
Can you add a comma after "While a dropdown looks simpler and saves space"?

2021-12-15 16:57 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +</Canvas>
The dropdown is getting cutoff so it would good to add a `height` prop to these stories

2021-12-15 17:25 UTC, tiffwong commented on packages/manager/src/components/TextField.stories.mdx
> +<Meta title="Components/Forms/Input Fields" component={TextField} />
This should stay as "Text Fields"

2021-12-15 17:30 UTC, tiffwong commented on packages/manager/src/components/TextField.stories.mdx
> +- Consider sizing the input field to the data being entered (example the field for a street address should be wider than the field for a zip code). Balance this goal with the visual benefits of field
Can we make "ex" and "example" consistent by using "ex."?

2021-12-15 17:36 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +</Canvas>
I think we can get rid of this example since it's very similar to the Component API example

2021-12-15 17:39 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +      },
The component is being referenced in different ways here (ie. "Select drop down" vs "Selection Drop Down" vs "select component") so it might be good to keep them consistent

2021-12-15 17:39 UTC, tiffwong requested changes
Functionality works great!

Left a few cleanup items and `EnhancedSelect.stories.tsx` can be deleted

2021-12-20 16:32 UTC, HanaXu requested changes

2021-12-20 16:32 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +      },
Can we remove value?

2021-12-20 16:32 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +        description: 'When true the Selection Drop Down will have a spinning loading indicator.',
"When true,"

2021-12-20 16:32 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +        description: 'When true the Selection Drop Down component allows the user to create new items to choose from',
"When true,"

2021-12-20 16:32 UTC, HanaXu commented on packages/manager/src/components/TextField.stories.mdx
> +|             | Don’t make the user guess what format they should use for the field. Tell this information up front.                               |
Is there a way to make `Label` and `Placeholder` multi-line?

![image](https://user-images.githubusercontent.com/14323019/146799810-9add2054-f4cd-4377-a30f-c8f7eb89c17e.png)

2021-12-20 16:32 UTC, HanaXu commented on packages/manager/src/components/TextField.stories.mdx
> +- Consider sizing the input field to the data being entered (ex. the field for a street address should be wider than the field for a zip code). Balance this goal with the visual benefits of fields of
Line 54 is a duplicate of Line 28, we should remove one to keep it succinct

2021-12-20 20:36 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +    name="Component API"
Can you change the name here to "Selection Drop Down" so instead of being nested inside the "Selection Drop Down" entry, it'll take you there directly

2021-12-20 20:36 UTC, tiffwong commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +## Component API
These can be removed

2021-12-20 20:39 UTC, tiffwong commented on packages/manager/src/components/TextField.stories.mdx
> +- Grouping related inputs (ex mailing address) under a subhead or rule can add meaning and make the form feel more manageable.
"ex."

2021-12-20 20:40 UTC, tiffwong commented on packages/manager/src/components/TextField.stories.mdx
>  <Meta title="Components/Forms/Text Fields" component={TextField} />
This should probably be renamed to "Text Field" to be consistent

2021-12-20 20:41 UTC, tiffwong requested changes
Left some more changes and I agree with the feedback Hana left

2021-12-21 17:00 UTC, HanaXu approved these changes
LGTM 🚢 , left some optional cleanup comments

2021-12-21 17:00 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +import timezones from 'src/assets/timezones/timezones';
Can we remove timezones since it's not being used anywhere?

2021-12-21 17:00 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
> +export const SelectTemplate = (args, context) => {
Remove context as well

2021-12-21 18:26 UTC, tiffwong approved these changes
Great job!

2021-12-21 18:44 UTC, merged