M3-5534: IPv6 sharing support
linode/manager pull request #8082
Opened 2021-12-15 09:44 UTC by bcmertz

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-12-22 17:27 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +      .filter((thisLinode: Linode) => {
can this `.filter.map` be replaced by a `.reduce` instead? That way we don't go through the array twice.

2021-12-22 18:06 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          await getLinodeIPs(thisLinode.id).then((ips) => {
Rather than mixing promise chains with async/await could this be done using only async/await?

2021-12-22 19:23 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +        .filter((i: IPRange) => {
Another possible simplification to use `reduce` instead of `.filter.map`

2021-12-22 19:24 UTC, codyfinn requested changes
Just a couple of small changes but overall looks good

2021-12-23 03:24 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +        .filter((i: IPRange) => {
done

2021-12-23 04:00 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +      .filter((thisLinode: Linode) => {
great idea, done!

2021-12-23 04:06 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          await getLinodeIPs(thisLinode.id).then((ips) => {
nice, done!

2021-12-23 04:11 UTC, bcmertz commented
@codyfinn any idea why we previously didn't show IP Sharing choices when there was 1 available IP address? Is there any reason to keep that around?

2022-01-03 14:21 UTC, codyfinn commented
> @codyfinn any idea why we previously didn't show IP Sharing choices when there was 1 available IP address? Is there any reason to keep that around?

I do not know the reason. Maybe because if you only have one IP to share then you only have one linode? @DevDW might be a better person to ask.

2022-01-03 14:49 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +            ranges.forEach((i: IPRange) => {
I think both of these could be replaced with optional chaining.
`const ranges = linodeIPs?.ipv6?.global`

`ranges?.forEach((i: IPRange) => {...`

2022-01-03 14:56 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          const ranges = pathOr([], ['ipv6', 'global'], linodeIPs);
I think both of this could be replaced with optional chaining.
`const ranges = linodeIPs?.ipv6?.global ?? []`

2022-01-03 14:57 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +            });
This could be replaced with the `array.map` function assigning it's evaluation to the ipv6Ranges variable.

2022-01-03 18:42 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  };
This is not a required change at all but I think you could leverage the reduce function a bit more to build up the object that is returned at the end of the function as opposed to creating two arrays.

2022-01-03 18:53 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +      pathOr([], ['ipv6', 'global'], linodeIPs).reduce(
Another place I think the optional chaining operator could clean the code up a bit

2022-01-03 20:19 UTC, DevDW commented
> > @codyfinn any idea why we previously didn't show IP Sharing choices when there was 1 available IP address? Is there any reason to keep that around?
> 
> I do not know the reason. Maybe because if you only have one IP to share then you only have one linode? @DevDW might be a better person to ask.

Hmm, I am not sure on the reasoning behind not showing it. That line of code came in with https://github.com/linode/manager/pull/7520, but I don't see any discussion surrounding that bit specifically. I'd check with API in case there's a backend reason for it, but my initial thought is that there's no reason why we shouldn't show the available IP address.

2022-01-06 08:55 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +      pathOr([], ['ipv6', 'global'], linodeIPs).reduce(
done

2022-01-07 14:42 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +        return acc.concat(`${i.range}/${i.prefix}`);
Could this be made more concise with a ternary something like:
 ```suggestion
        if (i.route_target !== null) {
          return acc;
        }
        return acc.concat(`${i.range}/${i.prefix}`);
        return i.route_target ? acc.concat(`${i.range}/${i.prefix}`) : acc;
```

2022-01-07 14:42 UTC, codyfinn approved these changes
I left a small suggestion but the code looks good with or without it. Nice job!

2022-01-07 22:43 UTC, DevDW commented
Hoping to take a look on Monday -- devenv refused to run properly for me today 😔

2022-01-08 00:39 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  // we check against this on unmount to cancel any outstanding requests
test

2022-02-11 18:49 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  });
Can this be pulled out into a function that is not inside a component? That way the component logic is simpler and the functionality can be tested more easily. Also I think this might be another good place to use the `.reduce` function.

2022-02-11 18:49 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  };
Can this be pulled out into a function that is not inside a component? That way the component logic is simpler and the functionality can be tested more easily. Also I think this might be another good place to use the `.reduce` function.

2022-03-02 19:47 UTC, bnussman reviewed
Functionality is looking solid against my local env but I have some questions and comments.

2022-03-02 19:47 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    true // always make the request so we have the data preloaded and don't need to wait to make further requests
If functionality is not compromised, we should still lazy load this.

2022-03-02 19:47 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +              this.props.flags.ipv6Sharing && sharedRanges.push(range);
I don't know how this should work, but to me, its confusing that when a Linode that "owns" an IPv6 range, if the IP is shared, in the Share IP modal, the IP shows up there... Should the shared range only show on the Linode's modal that doesn't "own the IP"... 

The code below explains what I mean, but needs modification in `ipResponseToDisplayRows` to work as I'm explainig

```suggestion
            if (
              resp.is_bgp &&
              resp.linodes.includes(this.props.linode.id) &&
              !this.state.linodeIPs?.ipv6?.global.some(
                (thisRange) => thisRange.range === range.range
              )
            ) {
              this.props.flags.ipv6Sharing && sharedRanges.push(range);
```

2022-03-03 21:43 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +              });
good point! we could do it that way, however if the refreshIPv4 promise doesn't resolve first we won't have the slaac address in state. It appears that promises resolve in order but underneath they can resolve out of order so I'm hesitant to make this change

2022-03-03 21:58 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  }, [linodeID, data, availableRanges]);
Hmm afaict we need the useEffect to update ipChoices when we get the data back from our request on line 96. However, to your point we could make ipChoices a var that the rest of the code could access to avoid keeping it in state.

However, I don't know how worthwhile it is only making that one suggested change and introducing a global ipChoices variable instead of ipChoices state

2022-03-03 22:08 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +              this.props.flags.ipv6Sharing && sharedRanges.push(range);
It's a little strange (took me a long time to get), but this is the intended behavior. Showing it allows us to unshare that Linode from that range.

We want ranges not shared to a Linode in availableRanges, and ranges that are shared to a Linode in shared ranges

2022-04-06 15:17 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          });
```suggestion
       if (flags.ipv6Sharing) {
        availableRangesMap?.[currentValue.id].forEach((range: string) => {
          previousValue[range] = currentValue.label;
          updateipToLinodeID({
            [range]: [...(ipToLinodeID?.[range] ?? []), currentValue.id],
          });
        });
      }

      return previousValue;
    }, {});
```

2022-04-06 16:18 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const data = resp.data;
This can be simplified to

```suggestion
  { data: linodesData, isLoading } = useAllLinodesQuery(
    { page_size: API_MAX_PAGE_SIZE },
    {
      region: linodeRegion,
    },
    open // Only run the query if the modal is open
  );
```

2022-04-06 16:18 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  }, [linodeID, data, availableRanges]);
We can remove the `linodes` variable and React Query handles the loading states for us so this can be simplified to

```suggestion
  React.useEffect(() => {
    // don't try anything until we've finished the request for the Linodes data
    if (!linodesData) {
      return;
    }
    const ipChoices = getIPChoicesAndLabels(linodeID, linodesData);
    setipChoices(ipChoices);
  }, [linodeID, linodesData, availableRanges]);
```

2022-04-06 16:27 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const data = resp.data;
^ oops, forgot the `const`

2022-04-06 16:27 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const data = resp.data;
just remembered I didn't do this because isLoading can't be a const

2022-04-06 16:27 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const data = resp.data;
unless theres a way around that

2022-04-06 17:01 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          : currentValue;
```suggestion
        const strippedIP: string = currentValue.split('/')[0];
```

I think this is equivalent.

2022-04-06 17:03 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          ipToLinodeID[currentValue].length === 1;
```suggestion
        const isStaticv6 = ipToLinodeID?.[currentValue]?.length === 1;
```

I think this is equivalent.

2022-04-06 17:03 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +          : currentValue;
nice

2022-04-06 17:24 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    setSubmitting(localSubmitting);
Why do we need to use an additional local variable? Isn't that what useState is essentially?

2022-04-06 17:24 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +      ipsToShare.forEach((ip) => {
Do we need this outer `forEach` if `ip` is never referenced?

2022-04-06 17:28 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    setSubmitting(localSubmitting);
unfortunately we do unless there's a workaround I can't find, useState is asynchronous (sorta), and can't be depended on to update state synchronously. Useeffect could be a work around but can't be used here. here's a stackoverflow with more info

https://stackoverflow.com/a/54069332

2022-04-06 18:11 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    }
```suggestion
    previousValue[currentValue.linodes[0]] = [...(previousValue?.[currentValue.linodes[0]]) ?? [], `${currentValue.range}/${currentValue.prefix}`];
```

2022-04-06 18:12 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    }
I think that is equivalent

2022-04-06 18:35 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                    <Link to="https://deploy-preview-5342--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/ip-failover/">
Can we use the finalized link here?

2022-04-06 18:41 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                    <Link to="https://deploy-preview-5342--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/ip-failover/">
definitely once it's merged :)

2022-04-06 18:46 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                    to setup BGP on a Linode.
`set up` (since it's a verb here)

2022-04-06 18:53 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +    return [refreshIPv4, refreshIPv6];
Ideally I would like to see the combination of async/await and promise chains consolidated to one or the other. Also the nested promise chains are another thing I would want to see addressed.

2022-04-06 19:01 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +    return [refreshIPv4, refreshIPv6];
I'll break this cleanup task into another ticket

2022-04-06 19:20 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    }
I think this should instead be:
```
previousValue[currentValue.linodes[0]] = [...(previousValue?.[currentValue.linodes[0]] ?? []), `${currentValue.range}/${currentValue.prefix}`];
```

2022-04-06 19:29 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const getIPChoicesAndLabels = (linodeID: number, linodes: Linode[]) => {
For a follow-up: I think this function can be moved back outside the FC with the flag boolean added as another parameter. Ideally we'd be able to add a unit test for it to ensure it is working as intended.

2022-04-06 19:31 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const updateipToLinodeID = (newData: Record<string, number[]>) => {
`updateIPToLinodeID`

2022-04-06 19:31 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const [ipChoices, setipChoices] = React.useState({});
`setIPChoices`

2022-04-06 19:31 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const [ipToLinodeID, setipToLinodeID] = React.useState({});
`setIPToLinodeID`

2022-04-06 19:34 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                    <Link to="https://deploy-preview-5342--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/ip-failover/">
trying to see if we can get it ahead of time before its released

2022-04-06 19:38 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +                    <Link to="https://deploy-preview-5342--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/ip-failover/">
done

2022-04-06 19:57 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const getIPChoicesAndLabels = (linodeID: number, linodes: Linode[]) => {
we'd also have to pass availableRangesMap, updateIPToLinodeID, ipToLinodeID, and linodeSharedIPs. Still move?

2022-04-06 20:02 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const getIPChoicesAndLabels = (linodeID: number, linodes: Linode[]) => {
might still be worth doing for the sake of the test, but otherwise I'd say no

2022-04-06 20:10 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +  const getIPChoicesAndLabels = (linodeID: number, linodes: Linode[]) => {
follow up PR

2022-04-06 21:20 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +    const refreshIPv6 = getAllIPv6Ranges({})
I don't think the `{}` is needed

2022-04-06 21:20 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +            let slaac;
an explanatory comment here could be helpful

2022-04-06 21:20 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
> +    ipAddress.prefix !== 116 &&
maybe we could put the `ipAddress.prefix !== 116` piece in a variable along with an explanatory comment to add a bit of clarity about the logic behind that in the context of this file

2022-04-06 21:36 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +            }
Can we move the flag checking to be the first thing checked for short circuiting?

```suggestion
            if (
              this.props.flags.ipv6Sharing &&
              resp.is_bgp &&
              resp.linodes.includes(this.props.linode.id)
            ) {
              // any range that is shared to this linode
              sharedRanges.push(range);
            } else if (!resp.is_bgp && range.route_target === slaac) {
              // any range that is statically routed to this linode
              staticRanges.push(range);
            } else if (this.props.flags.ipv6Sharing) {
              // any range that is not shared to this linode or static on this linode
              availableRanges.push(resp);
            }
```

2022-04-06 21:36 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +    return errorText ? <ErrorState errorText={errorText} /> : null;
This function is only called when there is an error so we can simplify this to
```suggestion
    const errorText =
      IPRequestError ||
      ipv6Error ||
      'There was an error retrieving your networking information.';
    return <ErrorState errorText={errorText} />;
```

2022-04-07 14:39 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    }
We can define the share value with a ternary
```typescript
    const share = flags.ipv6Sharing ? shareAddresses : shareAddressesv4;
    const promises: Promise<void | {}>[] = [];

    if (flags.ipv6Sharing) {
      // share unshared ranges first to their staticly routed Linode, then later we can share to the current Linode
      Object.keys(groupedUnsharedRanges).forEach((linode_id) => {
        promises.push(
          shareAddresses({
            linode_id: parseInt(linode_id, 10),
            ips: groupedUnsharedRanges[linode_id],
          }).catch((errorResponse) => {
            const errors = getAPIErrorOrDefault(
              errorResponse,
              'Unable to complete request at this time.'
            );
            localErrors = errors;
            setErrors(errors);
            localSubmitting = false;
            setSubmitting(false);
            setSuccessMessage(undefined);
          })
        );
      });
    }
```

2022-04-07 14:39 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> +          });
Let's unnest this a bit
```suggestion
          // get info on an IPv6 range; if its shared check if its shared to our Linode;
          // if its not shared (!is_bgp) figure out if its a slaac address or a statically routed range
          const resp = await getIPv6RangeInfo(range.range);
          let slaac;
          if (!resp.is_bgp) {
            await getLinodeIPs(this.props.linode.id).then((ips) => {
              slaac = ips?.ipv6?.slaac.address;
            });
          }

          if (
            this.props.flags.ipv6Sharing &&
            resp.is_bgp &&
            resp.linodes.includes(this.props.linode.id)
          ) {
            // any range that is shared to this linode
            sharedRanges.push(range);
          } else if (!resp.is_bgp && range.route_target === slaac) {
            // any range that is statically routed to this linode
            staticRanges.push(range);
          } else if (this.props.flags.ipv6Sharing) {
            // any range that is not shared to this linode or static on this linode
            availableRanges.push(resp);
          }
```

2022-04-07 14:39 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
> +  const is116 = ipAddress?.prefix === 116;
Can we rename this variable to be a bit more specific?

2022-04-07 16:00 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +            ].concat([strippedIP]);
can we do this instead of the array concatenation?

```suggestion
            groupedUnsharedRanges[linode_id] = [...groupedUnsharedRanges[linode_id], [strippedIP]];
```

2022-04-07 16:09 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +    setSubmitting(localSubmitting);
I would like us to revisit this in the follow-up PR and see if there's a better way for us to achieve what we're looking for here

2022-04-07 16:09 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +              {flags.ipv6Sharing && (
let's go with a ternary here instead of the `&&`

2022-04-07 16:39 UTC, bcmertz commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> +            ].concat([strippedIP]);
good suggestion, this was actually a bug if there were more than 1 unshared range being shared

2022-04-07 16:54 UTC, HanaXu approved these changes

2022-04-07 17:11 UTC, merged