DBAAS1-85: Database Details Backups Tab UI
linode/manager pull request #8083
Opened 2021-12-15 18:27 UTC by bnussman

## Description

- Adds UI and functionality to the database backups tab

## How to test

⚠️ Work in Progress

2021-12-23 21:28 UTC, bcmertz commented
Looks good, 2 small things that I saw in DBaaS D04 that we might want:

1. The "Restore" column has a title in the designs called "Actions"
2. Date Created should have two arrows pointing opposite directions for sorting

2022-01-03 16:31 UTC, HanaXu requested changes

2022-01-03 16:31 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +    } else if (backups) {
Can we unnest these else ifs and just change them to ifs since we return out of the function?

2022-01-03 16:31 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +      {error && (
Ternary

2022-01-03 16:31 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +        text="Restoring from a backup will erace all existing data on this cluster."
erase

2022-01-03 16:31 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +        To confirm restoring from a backup, type the name of the database
What about `To confirm restoration...`?

2022-01-03 16:31 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +  const onRestore = () => {
Can we rename this to something like `handleRestoreDatabase`?

2022-01-04 18:51 UTC, HanaXu approved these changes

2022-01-05 14:42 UTC, tiffwong commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +        </Typography>
The text is a bit too close to the header. Can you apply a class that sets `lineHeight` to `20px` and `marginTop` to `4px` to the description text?

2022-01-05 21:16 UTC, merged