DBAAS1-106: Database Landing Table
linode/manager pull request #8094
Opened 2021-12-21 22:53 UTC by bnussman

## Preview

<img width="1557" alt="Screen Shot 2021-12-21 at 5 49 30 PM" src="https://user-images.githubusercontent.com/6440455/147007865-18a6c4e5-049c-4fa1-a3aa-b3730587abd0.png">

## Description

- Makes DBaaS landing table according to spec

## How to test

- Enable the MSW
- Go to `/databases` and make sure the landing table matches the proposed spec in the internal ticket description

2021-12-28 19:26 UTC, bcmertz commented
The "Label" sort direction looks like it should match the styling of "Created" sort arrows according to the designs

2021-12-28 19:34 UTC, bcmertz commented
Nice job! Two small things:

- "Label" should be "Cluster Label"
- "Created" should have the same sort arrow as "Label"

according to DBaaS MVP designs in "Cloud Manager Final" project (there are outdated designs posted elsewhere)

2021-12-28 19:35 UTC, bcmertz requested changes
Nice job! Two small things:

- "Label" should be "Cluster Label"
- "Created" should have the same sort arrow as "Label"

According to DBaaS MVP designs in "Cloud Manager Final" project (there are outdated designs posted elsewhere)

2021-12-28 19:52 UTC, bnussman commented
I changed `Label` to `Cluster Label` but I'm unsure of any action to do about the sort arrows. It is standard that you can only sort by one column at once. The default sort I chose is by `label` `descencing`.

2021-12-28 20:11 UTC, bcmertz commented
Good point, I suppose its a little error in the designs, thanks!

2021-12-29 23:05 UTC, bcmertz requested changes

2021-12-29 23:05 UTC, bcmertz commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +};
The nimbus DBaaS PR describes the following engines:
```class DatabaseEngineType(Enum):
    mysql = "mysql"
    postrgresql = "postgresql"
    mongodb = "mongodb"
    redis = "redis"```

It might be worth adding support here and to update `Engine` type in `api-v4/lib/databases/types.d.ts` to reflect we expect one of those strings, not just mysql

2021-12-30 16:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +};
I think we may want to hold off since MySQL will be the only option for now. Any thoughts @DevDW @johnwcallahan ?

2021-12-30 18:56 UTC, johnwcallahan commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +};
I don't see any harm in going ahead and adding them to the map. One less thing to update once we support more engine types.

2021-12-30 20:48 UTC, bcmertz approved these changes
🎉

2022-01-03 18:09 UTC, DevDW approved these changes
LGTM, left a couple of minor comments 👍

2022-01-03 18:09 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +        <TableCell>{dcDisplayNames[region]}</TableCell>
in case the region isn't in the array, we should probably have `region` or possibly `"Unknown Region"` as a backup (we do this elsewhere, `KubeSummaryPanel.tsx` for example)

2022-01-03 21:43 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +          className={`${chipClasses.chip} ${chipClasses.nvmeChip}`}
To keep scope focused, can I make these changes in a follow up ticket?

2022-01-03 21:52 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +          className={`${chipClasses.chip} ${chipClasses.nvmeChip}`}
definitely, this isn't blocking by any means

2022-01-03 22:15 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
> +          className={`${chipClasses.chip} ${chipClasses.nvmeChip}`}
Thank you!

2022-01-03 22:17 UTC, merged