Small types & factories fixes/updates
linode/manager pull request #8097
Opened 2021-12-22 19:10 UTC by DevDW

## Description
Fix TypeScript error from `id` field in `databaseBackupFactory` and update `databaseType` interface and `databaseTypeFactory` per API specs

2021-12-22 21:10 UTC, bnussman requested changes
I few things I found we should change: 
- The `DatabaseFactory` should now return `failover_count`
- `getEngineDatabase` should return `CreateDatabaseResponse` type instead of `Database`
- It would be nice to have two factories for database instances since `getEngineDatabase` and `getDatabases` return different schemes for database instances

2021-12-23 15:41 UTC, HanaXu commented on packages/api-v4/src/databases/types.ts
>    ipv4_public: string[];
is `ipv4_public` supposed to be a string or string array?

2021-12-23 15:54 UTC, DevDW commented on packages/api-v4/src/databases/types.ts
>    ipv4_public: string[];
looks like a string -- just fixed it, thanks for catching

2021-12-23 15:55 UTC, bnussman approved these changes
Changes looks good. I like the decision to use `DatabaseInstance` and `Database` 🚀

2021-12-23 15:55 UTC, bnussman commented on packages/api-v4/src/databases/types.ts
>    ipv4_public: string[];
`string` I believe

2021-12-23 15:59 UTC, HanaXu approved these changes
🚀

2021-12-23 16:13 UTC, bcmertz approved these changes
LGTM!

2021-12-23 16:38 UTC, merged