Database summary scaffolding
linode/manager pull request #8098
Opened 2021-12-22 23:01 UTC by bcmertz

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2021-12-23 15:42 UTC, DevDW reviewed
I did some skeletal structure while working on the Access Controls ticket that I'll share with you; I think we can match the mockups more closely

2021-12-23 15:42 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
> +      <DatabaseSummaryAccessControls />
Can these three components be renamed to remove the "DatabaseSummary" piece since they're all in the `DatabaseSummary/` directory?

2021-12-23 19:56 UTC, bcmertz commented
Rename components and more closely match spec per @DevDW 's suggestion 😃 thanks!

2021-12-29 18:58 UTC, bnussman requested changes

2021-12-29 18:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
> +      </Grid>
Switch the order of these to match the spec and remove trailing space

```suggestion
        <Grid item>
          <ClusterConfiguration />
        </Grid>
        <Grid item>
          <ConnectionDetails />
        </Grid>
      </Grid>
```

2021-12-29 18:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
> +      <Divider className={classes.divider} />
You can use the `spacingTop` and `spacingBottom` props on the divider to add spacing instead of using classes. 

```
<Divider spacingTop={...} spacingBottom={...} />
```

2021-12-29 18:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
> +  );
To match spec headings

```suggestion
  return <>Cluster Configuration</>;
```

2021-12-29 18:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> +  );
To match spec heading

```suggestion
  return <>Connection Details</>;
```

2021-12-29 18:58 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryAccessControls.tsx
> +  );
To match spec headings

```suggestion
  return <> Access Controls </>;
```

2021-12-29 20:23 UTC, bnussman approved these changes
Looks good, just make this one last change to the spacing values and fix conflict.

2021-12-29 20:23 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
> +      <Divider spacingTop={1.5} spacingBottom={1} />
```suggestion
      <Divider spacingTop={24} spacingBottom={16} />
```

2021-12-30 17:38 UTC, tiffwong commented
Great job! There seems to be a merge conflict but everything lgtm! 🎉

2021-12-30 18:05 UTC, merged