DBaaS1-84: Access Control in Database Details
linode/manager pull request #8099
Opened 2021-12-23 22:03 UTC by DevDW

## Description
Adds the Access Control section to the Summary tab of the Database Detail page.

## To-Do:
- [ ] Code cleanup
- [ ] Add "Remove" button per mockups
- [ ] Improve empty state
- [ ] Improve styling

## Note to Reviewers
As of 12/23/21 I merged in https://github.com/linode/manager/pull/8096 which may undergo changes prior to being merged into the feature branch. A rebase of this PR or just merging the feature branch back in will need to be done before this gets merged in.

2022-01-03 19:28 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/AccessControls.tsx
> +              <TableCell key={idx} className={classes.cell}>
I think we generally want to avoid using the index in an array as the key.

2022-01-06 19:53 UTC, bnussman commented on packages/manager/src/queries/databases.ts
> +          [queryKey, Number(id)],
Thanks :)

2022-01-07 14:53 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +  const [submitting, setSubmitting] = React.useState<boolean>(false);
When you provide `useState` with a default value it should infer the typing. In the case above for the `error` variable it is needed since undefined is being unioned with the string type. Unless you want to keep the typing for consistency.

2022-01-07 14:57 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +      .filter((ip) => ip !== '');
I would expect the number of allowed IP addresses to be pretty short and if it is then the `.map.filter` is probably fine. Otherwise I would suggest `.reduce` to avoid looping through the array twice.

2022-01-07 15:22 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
>    };
Do we want to continue to use the promise chain pattern or should we start migrating towards async await?

2022-01-07 16:52 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/AccessControls.tsx
> +              <TableCell key={idx} className={classes.cell}>
Hmm, I did a search in the codebase and saw `key={idx}` quite a bit. Do you think it should be an interpolated string instead (e.g. `access-control-${idx}`)?

2022-01-07 16:53 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +  const [submitting, setSubmitting] = React.useState<boolean>(false);
removed this bit since I ended up using Formik

2022-01-12 17:52 UTC, HanaXu reviewed
I'm also seeing the "1" issue in this PR 🤔

2022-01-12 17:52 UTC, HanaXu commented on packages/validation/src/databases.schema.ts
> +import { IP_ERROR_MESSAGE, validateIP } from '../lib/firewalls.schema';
For some reason, importing lib schemas inside a schema causes a compile error so we should import from src instead
![image](https://user-images.githubusercontent.com/14323019/149194326-7a5d9138-87bb-4b4c-bd84-95172ecf338c.png)

```suggestion
import { IP_ERROR_MESSAGE, validateIP } from './firewalls.schema';
```

2022-01-12 19:25 UTC, DevDW commented on packages/manager/src/queries/databases.ts
> +          [queryKey, Number(id)],
This may prove to be temporary, but the mutation doesn't work properly without this coercion -- it treats the `id` as a string otherwise. Will look into this further at a later time.

2022-01-14 02:47 UTC, bcmertz reviewed
Remove IP address modal has an overly large font

2022-01-14 02:50 UTC, bcmertz commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +          <MultipleIPInput
In this component, when an IP is in error, the "X" button becomes misaligned

2022-01-14 15:05 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/AccessControls.tsx
> +              <TableCell key={idx} className={classes.cell}>
The bigger concern is that it is supposed to be a unique identifier for that element. So if the underlying array changes it's sorting react can still track changes in a performant manner. React links to this article for why it is a bad practice: https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318

2022-01-14 17:35 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/AccessControls.tsx
> +            this database cluster by restricting access.{' '}
I think the Database won't be accessible if there are no access controls specified. Is my understanding correct?

2022-01-14 19:42 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/AccessControls.tsx
> +            this database cluster by restricting access.{' '}
That is my current understanding as well. This draft of the warning copy is an earlier version prior to that being clarified; I need to confirm whether there is an updated version yet

2022-01-14 22:43 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
> +          <MultipleIPInput
I'll create a separate ticket for this issue

2022-01-18 20:55 UTC, HanaXu reviewed
Removing an IP via the table works but adding/removing from the drawer isn't working for me 🤔 

https://user-images.githubusercontent.com/14323019/150017127-6b8572fe-404d-4174-8c49-eac1e2a07288.mov

2022-01-18 21:09 UTC, DevDW commented
> Removing an IP via the table works but adding/removing from the drawer isn't working for me 🤔
> 
>  Screen.Recording.2022-01-18.at.3.50.18.PM.mov

Odd, I just tried it 🧐 

https://user-images.githubusercontent.com/32860776/150019244-90d37e4e-c366-4d59-ad7a-3a9f0ac6bde9.mov

Did you have the latest version of this branch pulled? What browser were you using?

2022-01-18 21:16 UTC, HanaXu commented
@DevDW nvm, I just did a clean `yarn up` and it's working now 😅

2022-01-18 22:07 UTC, HanaXu requested changes
The remove button padding seems uneven
![image](https://user-images.githubusercontent.com/14323019/150025962-c96645ff-1ec5-494b-b2a7-efd93fee2102.png)


Can we improve the mobile view? The primary button is taking up a lot of space

![image](https://user-images.githubusercontent.com/14323019/150025578-89be3717-36c9-4b2c-a015-57fb8cf0f4a4.png)

2022-01-19 19:37 UTC, HanaXu requested changes
Can we add an `xs` breakpoint for phones?

![image](https://user-images.githubusercontent.com/14323019/150201528-63bbc73d-43fb-4a20-b386-a58e6f8a3f76.png)


![image](https://user-images.githubusercontent.com/14323019/150201231-b05edfb1-36e4-4066-8843-bb6d2a539446.png)

2022-01-19 19:37 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
> +  },
```suggestion
  sectionText: {
    marginBottom: '1rem',
    width: '65%',
    marginRight: 0,
    [theme.breakpoints.down('xs')]: {
      width: '100%',
    },
  },
```

2022-01-19 19:37 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
> +  },
```suggestion
  table: {
    width: '50%',
    border: `solid 1px ${theme.cmrBorderColors.divider}`,
    '&:last-child': {
      borderBottom: 'none',
    },
    [theme.breakpoints.down('xs')]: {
      width: '100%',
    },
  },
```

2022-01-19 20:41 UTC, tiffwong approved these changes
Everything looks good! 

Non-blocking but it seems weird to me that the button says "Add Inbound Sources" even if you're removing one. Is it possible to make it dynamic or change it something more generic (ie. "Save Changes")?

2022-01-19 20:58 UTC, HanaXu approved these changes

2022-01-19 21:41 UTC, DevDW commented
> Everything looks good!
> 
> Non-blocking but it seems weird to me that the button says "Add Inbound Sources" even if you're removing one. Is it possible to make it dynamic or change it something more generic (ie. "Save Changes")?

will raise this point in demo prep tomorrow to see if we want to tweak this

2022-01-19 21:58 UTC, merged