M3-5641 & 5642: Update URL for invalid paths and cleanup routing
linode/manager pull request #8100
Opened 2021-12-28 16:45 UTC by tiffwong

## Description

**M3-5641:**

Previously, the page would redirect to the first tab if the URL was invalid but the URL was not updated. This PR fixes that and also updates the tab-related functions to be consistent.

**M3-5642:**

Cleans up the routing so that it'll redirect to the landing pages and replace `RouteComponentProps` with `useRouteMatch` hook.

## How to test

Make sure none of the links have regressed and try breaking the URL from different pages.

2021-12-30 17:08 UTC, bnussman reviewed
Still need to do more testing, but added some minor items.

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/Lish/Lish.tsx
> +        this.props.history.push(`${this.props.match.url}`);
```suggestion
        this.props.history.push(this.props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
> +      props.history.push(`${props.match.url}`);
```suggestion
      props.history.push(props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
> +      props.history.push(`${props.match.url}`);
```suggestion
      props.history.push(props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
> +      this.props.history.push(`${this.props.match.url}`);
```suggestion
      this.props.history.push(this.props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
> +      props.history.push(`${props.match.url}`);
```suggestion
      props.history.push(props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
> +      props.history.push(`${props.match.url}`);
```suggestion
      props.history.push(props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
> +      history.push(`${props.match.url}`);
```suggestion
      history.push(props.match.url);
```

2021-12-30 17:08 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
> +      props.history.push(`${url}`);
```suggestion
      props.history.push(url);
```

2021-12-30 21:17 UTC, bcmertz commented on packages/manager/src/features/Help/index.tsx
> -const HelpAndSupport: React.FC<{}> = (_) => {
Breaking the path for /support doesn't redirect to the HelpLanding page, however the status banners still present as normal since they're outside the routing switch. I think we should either choose to present the not found page or redirect to the help and support landing page

2021-12-30 21:18 UTC, bcmertz commented on packages/manager/src/features/Help/index.tsx
> -const HelpAndSupport: React.FC<{}> = (_) => {
perhaps we just add back in the Redirect?

2021-12-30 21:21 UTC, bcmertz commented on packages/manager/src/features/Images/index.tsx
> +        <Route component={ImagesLanding} path={path} exact strict />
We get immediately redirected from /images/create back to /images after pressing the "Create Image" button

2021-12-30 21:28 UTC, bcmertz commented on packages/manager/src/features/Images/index.tsx
> +        <Route component={ImagesLanding} path={path} exact strict />
this seems to be because of the Machine Images feature flag and is probably unrelated to this PR, but might be worth hiding the Create Image button if the flag is off

2021-12-30 21:49 UTC, bcmertz commented on packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
> -// const Access = React.lazy(() => import('./BucketAccess'));
/object-storage is accessible, however /object-storage/access-keys and /object-storage/buckets/create are not

2021-12-30 22:05 UTC, bcmertz commented on packages/manager/src/features/Users/UserDetail.tsx
> +  const getDefaultTabIndex = () => {
/account/billing/make-payment is broken here, the side bar appears but the url reverts to /account/billing

2021-12-30 22:19 UTC, bcmertz commented on packages/manager/src/features/Account/AccountLanding.tsx
> -  const matches = (p: string) => {
i think /account/billing/make-payment is broken by the changes in this component, the side bar appears but the url reverts to /account/billing

2021-12-30 22:29 UTC, bcmertz requested changes
Nice job! A few broken links

2022-01-03 22:26 UTC, DevDW reviewed
Still testing across the app, but one thing I found is that there appears to be a regression when navigating directly to `/stackscripts/community` -- you get redirected to `/stackscripts/account` now

2022-01-03 22:26 UTC, DevDW commented on packages/manager/src/features/Account/AccountLanding.tsx
> -  const matches = (p: string) => {
I am observing the same issue with `/account/billing/make-payment`

2022-05-03 19:07 UTC, tiffwong commented
Closing cause it'll be more work to resolve the conflict than starting from scratch

2022-05-03 19:07 UTC, closed without merging