DBAAS1-79: Database Create Page
linode/manager pull request #8101
Opened 2021-12-30 23:09 UTC by HanaXu

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2022-01-07 21:28 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +          Create Volume
Create Database

2022-01-10 15:25 UTC, bnussman commented on packages/api-v4/src/databases/types.ts
> +
We would probably want this type in Manager's code rather than api-v4

2022-01-10 22:38 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
> +    // update node pricing if a plan is selected
Not sure exactly how to test this, the actual plan info doesn't seem to be in the debug DOM

2022-01-11 16:10 UTC, bnussman requested changes
Here are some small things I've found so far. Nice work on this!

2022-01-11 16:10 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +  mysql: () => <MySQLIcon width="32" height="24" />,
I think we'll want to make the icon greyscale to match other things in Cloud Manager. Where did we get the svg from?

2022-01-11 16:10 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        <Divider spacingTop={38} />
Spacing after Dividers looks a bit inconsistent. 
<img width="601" alt="Screen Shot 2022-01-11 at 11 03 25 AM" src="https://user-images.githubusercontent.com/6440455/148978207-2e51cbb5-c132-4fdf-9a4c-abf8b402af7e.png">

2022-01-11 16:24 UTC, tiffwong requested changes
Functionality and POST data look great. 

It was a bit weird when I triggered errors for the label and IP fields where only an error for label was displayed. The IP error was displayed after I addressed the label error but they should both be displayed at the same time.

Additionally, the "Database Label" should say "Cluster Label" according to the sketch files and the 3 nodes option should be selected by default.

The spacing between the divider and header is inconsistent. The space between the two should be `12px`.

<img width="130" alt="Screen Shot 2022-01-11 at 4 22 29 PM" src="https://user-images.githubusercontent.com/7692354/148981187-00c1011e-fd8c-4d42-93c0-4b554324fb90.png"> It's `24px` here.


<img width="132" alt="Screen Shot 2022-01-11 at 4 22 23 PM" src="https://user-images.githubusercontent.com/7692354/148981190-a153e7d2-22ad-42a2-bd8f-01b7a59c43b2.png"> It's `8px` here and for the rest of the page.

2022-01-11 16:26 UTC, tiffwong commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        </Button>
The create button is showing up as right aligned for me 🤔

2022-01-11 17:53 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +          <Typography variant="h2">Select Engine and Region</Typography>
Agreed. I talked with Matthew about this before and we ended up keeping this as is

2022-01-11 17:53 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        </Button>
Same 🤔

2022-01-11 17:54 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +  mysql: () => <MySQLIcon width="32" height="24" />,
Some random site 😆

2022-01-11 18:55 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        </Button>
Woah, ok. I'll double check this

2022-01-11 20:04 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +    justifyContent: 'end',
Here's the fix for the Create Button alignment. Safari must not accept `end`

```suggestion
    justifyContent: 'flex-end',
```

2022-01-11 21:16 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        </Button>
Talked with Matthew, we're going to leave the button outside of the paper. Having it outside reinforces that the CTA applies to all sections above it

2022-01-11 22:22 UTC, DevDW reviewed
Looking good overall, left a few comments

When there's a field error, can we have the scroll-to-error effect? For example, if the label field has an error, we should auto-scroll up to it to bring it into view.

Also, I don't think the IP validation is working quite as intended -- it's accepting "1" as a valid IP, for example 🧐

2022-01-11 22:22 UTC, DevDW commented on packages/validation/src/databases.schema.ts
>  export const createDatabaseSchema = object({
from the discussion we kicked off today regarding the IPs being required in the Create flow -- this schema will need to be updated accordingly (either in this PR or separately -- just wanted to note it here)

2022-01-11 22:22 UTC, DevDW commented on packages/api-v4/src/databases/types.ts
> +      price: PriceObject;
strictly speaking, `null` won't be a possible value for the fields here. Maybe we should make a new interface?

2022-01-11 22:30 UTC, HanaXu commented
@DevDW I noticed the "1" issue as well, not sure why though 🤔

2022-01-12 20:40 UTC, HanaXu commented on packages/validation/src/databases.schema.ts
>  export const createDatabaseSchema = object({
I updated `updateDatabaseSchema` but am keeping IP validation out of `createDatabaseSchema` since I'm validating the IP in the DatabaseCreate component

2022-01-13 21:30 UTC, DevDW reviewed
Going to go through this more thoroughly tomorrow morning, but left a couple of small comments

2022-01-13 21:30 UTC, DevDW commented on packages/validation/src/databases.schema.ts
> +  allow_list: array().of(string()).required('An IPv4 address is required'),
`An IPv4 address or range is required`

2022-01-14 01:53 UTC, bcmertz commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +            onChange={(e) => setFieldValue('label', e.target.value)}
Unlike Volume create the validation doesn't appear on this field until submission, is this intended?

2022-01-14 02:10 UTC, bcmertz commented on packages/validation/src/databases.schema.ts
> +  allow_list: array().of(string()).required('An IPv4 address is required'),
The API only handles IPv4 addresses right now

2022-01-14 02:18 UTC, bcmertz commented on packages/validation/src/databases.schema.ts
>      .required('Replication Type is required'),
super small and doesn't matter right now, but in the future `replication_type` will be an optional field which gets set to to default `none` on the backend. Might be worth reflecting that in the schema now

2022-01-14 02:28 UTC, bcmertz commented on packages/validation/src/databases.schema.ts
> +  allow_list: array().of(string()).required('An IPv4 address is required'),
API checks against a config that limits the maximum number of IPv4 addresses allowed, might be worth adding a check for length and limit it from being arbitrarily high. Probably worth checking to see what that is expected to be

2022-01-14 02:32 UTC, bcmertz commented on packages/manager/src/utilities/ipUtils.ts
> +  return ips.map(({ address }) => {
we should be deduplicating IPv4 addresses or the request will fail

2022-01-14 02:37 UTC, bcmertz requested changes
Looks really good, left a few small comments

2022-01-14 14:03 UTC, tiffwong commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +            3 Nodes - High Availability (recommended)
I agree ☝️

2022-01-14 14:18 UTC, tiffwong approved these changes
Other than the points Dajahi and Leah mentioned, everything else lgtm!

2022-01-14 15:58 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
> +    }
Could this be simplified by using the `.buildList` method?

2022-01-14 16:04 UTC, codyfinn commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +  renderPlanContainer = (plans: Array<ExtendedType | ExtendedDatabaseType>) => {
Is there a reason this is `Array<ExtendedType | ExtendedDatabaseType>` and not `ExtendedTypes`?

2022-01-14 16:43 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +            onChange={(e) => setFieldValue('label', e.target.value)}
Yes, this is intended

2022-01-14 16:46 UTC, HanaXu commented on packages/validation/src/databases.schema.ts
> +  allow_list: array().of(string()).required('An IPv4 address is required'),
I think this is fine as we use Yup for basic frontend validation and rely on API for the rest

2022-01-14 16:54 UTC, HanaXu commented on packages/manager/src/utilities/ipUtils.ts
> +  return ips.map(({ address }) => {
This function is used to add an error property if an ip is not valid as determined by ipaddr.js and meant to be generic. Deduplicating IPv4 addresses so that a request doesn't fail seems more like business logic. I think it's fine if the request fails as duplicate IPv4 addresses seems like an edge case and we handle API errors

2022-01-14 17:54 UTC, bcmertz commented on packages/manager/src/utilities/ipUtils.ts
> +  return ips.map(({ address }) => {
awesome, sounds good

2022-01-14 17:55 UTC, bcmertz approved these changes

2022-01-14 18:50 UTC, DevDW approved these changes
Nice work! This is looking good to me.

2022-01-14 18:50 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +        {createError ? <Notice error text={createError} /> : null}
Can we have this error scroll into view as well?

2022-01-18 15:13 UTC, bnussman commented
Currently seeing this in dev

<img width="515" alt="Screen Shot 2022-01-18 at 10 12 31 AM" src="https://user-images.githubusercontent.com/6440455/149964161-70fb7558-6ce8-4379-a98c-26a100e867b6.png">

2022-01-18 16:05 UTC, HanaXu commented
@bnussman Looks like the API response is missing `label`, they will be adding that soon. In the meantime, I'll add the label from the UI side

2022-01-18 17:02 UTC, bnussman commented
API is returning a weird version now. 

Also, unit tests aren't passing so we'll need those fixed up before merge. 

<img width="515" alt="Screen Shot 2022-01-18 at 12 02 02 PM" src="https://user-images.githubusercontent.com/6440455/149983787-81979395-e85a-42ae-9b9b-27ac624891e5.png">

2022-01-19 15:10 UTC, merged