Marketplace: Document link updates an cleanup
linode/manager pull request #8106
Opened 2022-01-06 15:15 UTC by hmorris3293

## Description

This PR is to clean up FakeSpec.ts. Long overdue cleanup of doc URLs, clean up formatting, remove "One Click App" references, align all apps, and put them in alphabetical order. 

## How to test

Click the info tabs on each Marketplace app and review. 

One Note: OpenLiteSpeed Wordpress URL will be the only doc link that 404s. This is set to be update tomorrow via the Docs team.

2022-01-07 17:03 UTC, tiffwong requested changes
No broken links but the summary drawer for UTunnel doesn't open.

Can you make the "More info" links for MySQL/MariaDB on separate lines?
<img width="482" alt="Screen Shot 2022-01-07 at 4 51 20 PM" src="https://user-images.githubusercontent.com/7692354/148579502-b694e400-d788-4407-9949-cb415b6aeb44.png">

The summary for Webuzo needs a period at the end.
<img width="485" alt="Screen Shot 2022-01-07 at 4 59 41 PM" src="https://user-images.githubusercontent.com/7692354/148579508-6d53680a-0c9d-4113-8c9f-44ce7340c785.png">

2022-01-07 17:19 UTC, HanaXu commented
@tiffwong The UTunnel drawer doesn't open rn bc the naming was updated in https://github.com/linode/manager/pull/8075. And the internal naming still needs to be updated as well (it was temporarily updated when the PR was opened so that the drawer would open). The UTunnel drawer should work after our next Manager release on the 10th.

2022-01-12 02:21 UTC, hmorris3293 commented
@tiffwong pushed update for webuzo. MySQL/Maria are on separate titles/hrefs but I'm not 100% how to separate it on a new line

2022-01-12 15:26 UTC, tiffwong approved these changes

2022-01-12 16:44 UTC, HanaXu approved these changes

2022-01-12 17:21 UTC, merged