DBAAS1-86: Database Details Settings
linode/manager pull request #8116
Opened 2022-01-12 22:37 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2022-01-14 15:53 UTC, codyfinn commented
Still a work in progress and currently broken due to a typo. Should be ready for review after the next push.

2022-01-18 21:45 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
> +    await deleteDatabase(databaseEngine, databaseID);
Can we use `useDeleteDatabaseMutation`. That way the React Query cache knows to remove the entity.

2022-01-20 15:35 UTC, bnussman requested changes
Code looks super clean so far 🥵

Here's a few items 
- The Delete Modal should be a DeleteConfirmation that is typeToConfirm
- More spacing is needed between each section
- Button wrapping feels a bit inconsistent (shown in screenshot)
- Access controls needs to be hooked up (should be same component as summary page)

<img width="896" alt="Screen Shot 2022-01-20 at 10 29 12 AM" src="https://user-images.githubusercontent.com/6440455/150370054-6b719eba-169a-48a2-9594-a022d3eb06f2.png">

2022-01-20 22:55 UTC, codyfinn reviewed
Still waiting on final copy for resetting the root password

2022-01-20 22:56 UTC, bnussman requested changes

2022-01-20 22:56 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
> +    await resetDatabaseCredentials(databaseEngine, databaseID);
We should have a loading state for this API call and pass that loading boolean value to the `Reset Password` button in the `actions`. Use state or make a React Query Mutation and use the `isLoading` value it provides

2022-01-21 04:24 UTC, bnussman requested changes
Can we add some padding above the buttons on small viewports? Other than that this is looking good!

![Screen Shot 2022-01-20 at 11 18 22 PM](https://user-images.githubusercontent.com/6440455/150465472-5d08ed90-f704-48b6-9730-e264b0e6a1f9.png)

2022-01-21 04:24 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
> +    }
I think we'll need to also call `setIsLoading(false);` in the catch too

2022-01-21 14:56 UTC, HanaXu reviewed
This seems to be an incomplete sentence

![image](https://user-images.githubusercontent.com/14323019/150548428-4474b6f0-22c5-45f4-a437-bffe42809aa8.png)

2022-01-21 14:58 UTC, HanaXu approved these changes

2022-01-21 15:07 UTC, bnussman approved these changes

2022-01-21 15:07 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
> +        text="Resetting your root password requires your database node(s) to"
Fix this like @HanaXu said, then it should be good to go!

2022-01-21 15:09 UTC, DevDW approved these changes
The feedback items can be hit with a follow-up PR.

The copy in the `Delete Cluster` section starts wrapping very early compared to the other sections:

<img width="1132" alt="Screen Shot 2022-01-21 at 10 00 32 AM" src="https://user-images.githubusercontent.com/32860776/150550316-47fb5e95-e4e5-478a-9cd7-133127cf6fe2.png">

2022-01-21 15:09 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
> +import * as React from 'react';
since this file is in `/DatabaseSettings` already, we could be more concise with the file name and make it `DeleteClusterDialog.tsx` instead

2022-01-21 15:09 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
> +          total of # nodes and any backups associated with database{' '}
is the `#` supposed to be a placeholder for something?

2022-01-21 15:12 UTC, bcmertz approved these changes
LGTM! This can be addressed after merging, and I believe I discussed this with @HanaXu, but it would be nice to deduplicate access control addresses and have better validation on them. However, perhaps instead of doing deduplicating automatically it should just be part of the validation logic and we throw an error prior to the request

Other than that, +1 to everyone else's feedback.

2022-01-21 15:26 UTC, merged