M3-5646: Tax Collection Banner
linode/manager pull request #8118
Opened 2022-01-14 14:51 UTC by tiffwong

## Description

This PR will show a global dismissible banner for customers whose billing info is located in nexus states (Arizona, Hawaii, Pennsylvania, Texas, and Washington) or in taxable countries (Canada and Japan). Additionally, show a button for taxable countries that opens the contact info drawer.

**Remaining tasks:**
- [ ] Get copy

## How to test

Make sure the flag is on and the banner show be displayed for only nexus states or taxable countries.

2022-01-24 17:16 UTC, HanaXu reviewed
Can we make the `Edit` button in the Billing Contact paper also update the url?

2022-01-25 16:26 UTC, HanaXu requested changes

2022-01-25 16:26 UTC, HanaXu commented on packages/manager/src/features/Account/AccountLanding.tsx
> +    }
This change is causing a regression by overriding the `/billing/make-payment` and `/billing/add-payment-method`  urls to `/billing`

2022-01-27 16:09 UTC, HanaXu approved these changes

2022-01-27 18:25 UTC, bnussman approved these changes
Functionality is great. All of the routing changes and added code make me nervous but everything seems to work!

2022-01-31 13:48 UTC, merged