M3-5676: Database Backups Refinements
linode/manager pull request #8143
Opened 2022-01-25 20:51 UTC by bnussman

## Description

- Added **relative date** column to the backups table
- Updated **copy** to explain that **backups are retained for 7 days**
- When user successfully initializes a restore, we toast a success message, and redirect them to the summary page
  - The user will see the status `Restoring` immediately they start a restore successfully. This may not be immediately updating until #8131 is merged. 
 
## How to test

- Try restoring a database form a backup. Ensure the flow as described above is accurate
- Check copy change for spelling and grammar
- Check that the relative date in the table works and looks good

2022-01-26 15:15 UTC, tiffwong approved these changes

2022-01-26 18:03 UTC, HanaXu requested changes
It seems a bit odd to me that the relative date is in the middle of the table instead of next to the absolute date. Can we make them closer? Also, when restoring from a backup, the url changes to `/summary` but the view stays on the backups tab

![image](https://user-images.githubusercontent.com/14323019/151220399-9b780eb7-f59c-4195-aae0-2e17e16bfb33.png)

2022-01-27 16:23 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +        </TableRow>
Okay, I know this is kind of bad. But it is **finally** a loading state that matches the correct column widths. I can't stand when the loading skeletons don't match the Table head column widths

I want to make this a component but I'll want to do that in a follow up ticket. 


## This is what I'm referring to...

**Loading state with incorrect column size**


https://user-images.githubusercontent.com/6440455/151399964-45daaaa6-2363-4c81-a06a-b100c37bd84f.mov



**The better loading state I made with so much less code**

https://user-images.githubusercontent.com/6440455/151399928-d0869fe7-16db-4a75-8410-2ff78fd9551b.mov

2022-01-27 21:43 UTC, DevDW approved these changes
LGTM -- I did have to use the mocks to test, though, as the request to `/backups` was failing with an error of `Could not retrieve backups at this time`.

2022-01-27 21:46 UTC, HanaXu approved these changes

2022-01-27 22:10 UTC, merged