M3-5679: Querify database credentials reset
linode/manager pull request #8152
Opened 2022-01-26 21:22 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2022-01-27 16:41 UTC, bnussman commented
@codyfinn Try [this](https://github.com/codyfinn/manager/compare/M3-5679-query-for-reseting-database-creds...bnussman:reset-creds-testing) out and let me know what you think.

2022-02-01 16:04 UTC, bnussman requested changes

2022-02-01 16:04 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
> +  );
```suggestion
  const { mutateAsync, isLoading, error } = useDatabaseCredentialsMutation(
    databaseEngine,
    databaseID
  );
```

Source the error from here and remove the `error` state.

2022-02-01 17:31 UTC, bnussman approved these changes
Revert the noted item and this should be good to go!

2022-02-01 17:31 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> -    showCredentials && credentials ? credentials?.password : '••••••••';
May want to revert back to this, I think this got changed unintentionally.

2022-02-01 17:31 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
> +  const password = showCredentials ? credentials?.password : '••••••••';
```suggestion
  const password =
    showCredentials && credentials ? credentials?.password : '••••••••';
```

2022-02-02 19:42 UTC, HanaXu approved these changes

2022-02-02 21:36 UTC, bnussman approved these changes

2022-02-03 15:44 UTC, merged