Database Create Copy updates
linode/manager pull request #8154
Opened 2022-01-27 19:47 UTC by HanaXu

## Description
M3-5684: Add notice that beta is free
M3-5685: Update Add Access Controls language
M3-5686: Move the provisioning helper text next to create button

## How to test
In `databases/create` check for the changes above and also check mobile view

**How do I run relevant unit tests?**
`yarn test DatabaseCreate`

2022-01-27 21:41 UTC, jdamore-linode approved these changes

2022-01-28 21:36 UTC, DevDW reviewed
Looks good; we can clean up the tablet view a bit (>600 px width) though when it comes to the padding so these aren't flush to the page edges:

<img width="956" alt="Screen Shot 2022-01-28 at 3 27 56 PM" src="https://user-images.githubusercontent.com/32860776/151616976-ca276c69-c639-4443-a805-effb8c3f7b02.png">

<img width="611" alt="Screen Shot 2022-01-28 at 3 28 11 PM" src="https://user-images.githubusercontent.com/32860776/151617072-21723bc1-bf31-449c-92e6-66880e226024.png">

2022-01-28 21:36 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +              title="Allowed IP Address(s) or Range(s)"
`Address(es)`

2022-01-28 21:36 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +              placeholder="Add IP Address or Range"
Since these have to be IPv4 addresses/ranges, we should display the example hint as the placeholder like we now do in the Access Controls IP fields.

You can do

`import { ipFieldPlaceholder } from 'src/utilities/ipUtils';`

and pass `ipFieldPlaceholder` here

2022-01-31 14:51 UTC, tiffwong reviewed
I seem to be getting an error when I try to check this out including after running `yarn clean`. Is anyone else getting this?

<img width="692" alt="Screen Shot 2022-01-31 at 9 49 40 AM" src="https://user-images.githubusercontent.com/7692354/151815296-55881ea2-0dfc-4529-82bd-f7ae0fe3cd8e.png">

2022-01-31 14:52 UTC, bnussman commented
I'm getting the same issue as @tiffwong. I assume it's because the API response changed for something?

2022-01-31 16:06 UTC, tiffwong commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +  createText: {
Can you add `marginLeft` here to prevent the text from being flush to the window when it's around 600-700px?

2022-01-31 16:09 UTC, tiffwong requested changes
Left a couple cleanup items for small-medium resolutions

2022-01-31 21:42 UTC, DevDW approved these changes
Looks good 👍 

left a bit of feedback on a potential copy change and something that may be out of scope for these tickets

2022-01-31 21:42 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +                Notice: There is no charge for database clusters during beta.
One thought on this copy is that a single node is not technically a cluster, but single nodes are not being charged for as well during beta. Perhaps we can look at using "instances" instead of "clusters" 🤔

2022-01-31 21:42 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
>              <MultipleIPInput
I was thinking that it would make sense for us to enforce the IP masking here as well. This can be achieved relatively painlessly with the `onBlur` prop for this component and logic similar to https://github.com/DevDW/manager/blob/167f7f91c10e420fb41d1c271f0d2c08cdd19e46/packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx#L55-L59

(a bit of scope creep, so it's fine to create a separate ticket for this or do a follow-up PR if you want)

2022-02-01 16:15 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +                Notice: There is no charge for database clusters during beta.
Good point, I'm going to leave the copy as is for now and we can revisit this if we get any feedback about the copy

2022-02-01 16:20 UTC, tiffwong approved these changes

2022-02-01 17:42 UTC, merged