M3-5694: Changes to types, schema, and Database components to reflect cluster_size
linode/manager pull request #8155
Opened 2022-01-28 19:17 UTC by DevDW

## Description
The API has revised the shapes of some data points:

1. The database types will no longer have `addons` or `price` properties; they are being replaced by `cluster_size` which is an array here consisting of a `quantity` property and a `price` property.
2. `failover_count` is being replaced by `cluster_size` (different from the above), which is a number (either 1 or 3) here. 

## To-Do:
- [ ] Update the logic in the Create flow to reflect these changes

## How to test
Coming soon

2022-01-31 18:24 UTC, bnussman commented
If I remember correctly, before this, the 3 node option was disabled for nanodes (otr some config like that). Is it supposed to still do that?
<img width="1121" alt="Screen Shot 2022-01-31 at 1 22 57 PM" src="https://user-images.githubusercontent.com/6440455/151850894-f08a75d9-8656-4b1c-9401-b32d1dd7c1ad.png">
?

2022-01-31 18:34 UTC, bnussman requested changes
When I try to create a Database, nothing happens. I'm assuming it has something to do with IP validation... I am entering `192.168.1.1` as the IP. 

Also, do we need to use something other than `Inbound Sources` for the input title so it makes more sense to users? 

<img width="733" alt="Screen Shot 2022-01-31 at 1 32 52 PM" src="https://user-images.githubusercontent.com/6440455/151852175-0554c67e-881e-4dcf-99cf-2ebe631e13bb.png">

2022-01-31 18:34 UTC, bnussman commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +    setFieldValue('cluster_size', 3);
Changing the plan changes the number of nodes, can we make it so the node count does not change if the plan is changed?

https://user-images.githubusercontent.com/6440455/151851952-df19eff3-8e95-49d9-bfff-70f2dbdc1f8f.mov

2022-01-31 18:42 UTC, HanaXu commented
@bnussman 3 Node options for Nanodes are no longer disabled. Re: nothing happening when creating a database, I just tried creating a database cluster with `192.168.1.1` and it sent the request 🤔 . Have you tried rebuilding validation? The Inbound Sources copy and etc will be updated in https://github.com/linode/manager/pull/8154

2022-01-31 21:08 UTC, DevDW reviewed
@HanaXu the Database Create piece looks good to me, the only thing we may want to address is the error that pops up for Nodes when you try creating a DB without a plan selected:

<img width="695" alt="Screen Shot 2022-01-31 at 4 00 24 PM" src="https://user-images.githubusercontent.com/32860776/151873210-ff5e33b0-62df-402c-94a9-226f8b427476.png">

2022-01-31 21:08 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +    setFieldValue('replication_type', 'semi_synch');
`semi_synch` is the default here because 3 is the default `cluster_size`?

2022-01-31 21:19 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> +    setFieldValue('replication_type', 'semi_synch');
Oops, good catch! 🔍

2022-01-31 21:22 UTC, HanaXu commented
@DevDW How did you get to that state? If a plan isn't selected the Node price should be $0 🤔

2022-01-31 21:49 UTC, DevDW commented
> @DevDW How did you get to that state? If a plan isn't selected the Node price should be $0 🤔

whoops, I took that screenshot after I chose a plan after first submitting with no plan selected (so the node pricing and whatnot updated).

but to get the "Nodes are required" error, just try to create a DB without a plan selected. We should probably put that error in a `<Notice />` at the top of that section.

2022-02-01 14:55 UTC, bnussman approved these changes

2022-02-01 14:58 UTC, HanaXu approved these changes

2022-02-01 14:59 UTC, merged