M3-5598: Update stories for Breadcrumb
linode/manager pull request #8186
Opened 2022-02-10 14:52 UTC by codyfinn

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2022-02-14 20:32 UTC, HanaXu requested changes

2022-02-14 20:32 UTC, HanaXu commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +  }}
Can we set some default values here so that we don't have to click the `Set ...` button to display controls?
```suggestion
  args={{
    pathname: '/linodes/9872893679817/test/lastcrumb',
    crumbOverrides: [],
    firstAndLastOnly: false,
    labelOptions: {
      subtitle: ''
    },
    labelTitle: '',
    removeCrumbX: 0
  }}
```
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/14323019/153940482-b4453fa1-f633-4c18-95da-9a4a7d8e73ef.png">

2022-02-14 20:32 UTC, HanaXu commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +    },
Instead of setting the control for `crumbOverrides` and `labelOptions` false, what about just setting it to an empty array/empty object in the args?

2022-02-14 20:32 UTC, HanaXu commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +### Breadcrum with Subtitle
Breadcrumb

2022-02-14 20:32 UTC, HanaXu commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +### Breadcrum with Prefix Component
Breadcrumb

2022-02-14 20:32 UTC, HanaXu commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +### Breadcrum with Editable Text
Breadcrumb

2022-02-17 16:02 UTC, codyfinn commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +  }}
I think it makes sense to have defaults set for `pathname` and `firstAndLastOnly`. The other two would change the component if something is set. If the user wants to see what that version of the component is they can click an extra button.

2022-02-17 16:28 UTC, codyfinn commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +    },
I don't think that will work well. It probably would cause rendering issues.

2022-02-17 20:25 UTC, HanaXu approved these changes

2022-02-18 20:10 UTC, tiffwong commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +- Include the current page as the last item in the Breadcrumb trail.
```suggestion
- Include the current page as the last item in the breadcrumb trail.
```

2022-02-18 20:10 UTC, tiffwong commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +- In the Breadcrumb trail, the Breadcrumb corresponding the the current page should not be a link.
```suggestion
- In the breadcrumb trail, the breadcrumb corresponding the the current page should not be a link.
```

2022-02-18 20:11 UTC, tiffwong commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +      description: "A string representation of the path of a resource. Each crumb is seperated by a '/' character.",
```suggestion
      description: "A string representation of the path of a resource. Each crumb is separated by a `/` character.",
```

2022-02-18 20:12 UTC, tiffwong commented on packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
> +      description: 'A boolean that if true will only show the first and last crumb',
```suggestion
      description: 'A boolean that if true will only show the first and last crumb.',
```

2022-02-18 20:13 UTC, tiffwong approved these changes
Suggested some non-blocking changes so approving

2022-02-18 20:41 UTC, merged