M3-5589: Added Storybook Story for File Uploads
linode/manager pull request #8192
Opened 2022-02-11 16:21 UTC by bnussman

## Description

- Adds a Storybook Story for our File Uploader

## How to test

- `yarn storybook`
- Find the `File Uploader` story and test it!

2022-02-14 20:47 UTC, jdamore-linode approved these changes
Looks good!

2022-02-14 21:10 UTC, tiffwong commented on packages/manager/src/components/FileUploader/FileUploader.stories.mdx
> +<Meta title="Components/File Uploads" />
The documentation says "Uploader" but the side menu has these stories listed says "Uploads" so I think we should make them consistent.

<img width="212" alt="Screen Shot 2022-02-14 at 4 08 52 PM" src="https://user-images.githubusercontent.com/7692354/153946765-a6370eb0-dcf9-4d54-babf-c28527eb39bc.png">

2022-02-14 21:12 UTC, tiffwong commented on packages/manager/src/components/FileUploader/FileUploader.stories.mdx
> +        description: "The label of the upload that will be sent to the Linode API (used for Image uploads)",
Also all the props here look like they're required other than `onSuccess` 🤔

2022-02-16 20:10 UTC, HanaXu requested changes
Setting `apiError` doesn't seem to do anything 🤔 . If we're keeping that field, can we initialize an empty string so that there's no extra `Set...` button click? And maybe set the controls for the function fields to null as well?

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/14323019/154346998-5140dfdc-ab51-40b2-904a-8594572ab9b9.png">

2022-02-17 15:27 UTC, HanaXu approved these changes

2022-02-18 01:29 UTC, merged