M3-5595: Storybook for Accordions
linode/manager pull request #8198
Opened 2022-02-14 16:32 UTC by bnussman

## Description

- Cleans up and converts the Accordions story to `mdx`
- Removes the Asynchronous Content example
- Adds copy
- Adds a Component API section with and Args Table
- Update Show More Expansion Story
- Convert Show More Expansion to a FC

## How to test

- `yarn storybook`
- Check all Accordion stories ([Link](http://localhost:6006/?path=/docs/ui-elements-accordion--default-story))

2022-02-15 19:52 UTC, bnussman commented on packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.tsx
> -  }
Please check behind me on removing this

2022-02-17 15:38 UTC, tiffwong commented on packages/manager/src/components/Accordion/Accordion.stories.mdx
> +- Can be cumbersome which adds to cognitive load. “People treat clicks like currency and they don't spend it frivolously.” - NNG [Citation](https://www.nngroup.com/articles/clickable-elements/)
Can the quote be a sub-bullet?

2022-02-17 15:38 UTC, tiffwong commented on packages/manager/src/components/Accordion/Accordion.stories.mdx
> +- Accordions collapsed by default diminish people's awareness of content
"diminishes"

2022-02-17 15:45 UTC, tiffwong requested changes
We can remove the `success`/`warning`/`error` examples since they can be generated in the ArgsTable.

Can we initialize the values for the following props to prevent the user from having to click the `Set ...` button to change the value?
- `defaultExpanded`
- `expanded`
- `headingNumberCount`
- `actions`
- `success`
- `warning`
- `error`

And then can we disable the controls for the remaining props?

Also since we're moving the `Show More Expansion` story to its own section, can we reference the use case for it over `Accordion` in `Accordion` and vice versa?

2022-02-17 16:02 UTC, bnussman commented
@tiff going to make most of these changes. In the args table, I leave many values uninitialized because they are optional props and imo the `Set boolean` buttons help the reader understand they are setting an optional prop

Additionally, I must leave `expanded` undefined with a `Set boolean` button so `defaultExpanded` won't get overwritten.

2022-02-17 20:51 UTC, HanaXu reviewed
Can we rename the component API to Accordion and remove the default since they're basically the same and to unnest the sidemenu?

2022-02-18 14:36 UTC, tiffwong approved these changes

2022-02-18 15:13 UTC, HanaXu approved these changes

2022-02-18 16:11 UTC, merged