M3-5599: Update story for CheckBox
linode/manager pull request #8199
Opened 2022-02-14 20:42 UTC by codyfinn

## Description

* Refactors CheckBox component to use `makeStyles`.
* Refactors CheckBox stories to use MDX

## How to test

run `yarn storybook`
ensure documentation is correct.

2022-02-15 19:37 UTC, bnussman requested changes

2022-02-15 19:37 UTC, bnussman commented on packages/manager/src/components/CheckBox/CheckBox.stories.mdx
> +            control: 'text',
```suggestion
            type: { summary: 'string', name: 'string' },
```

This minor change will show the type `string` below the description

![Screen Shot 2022-02-15 at 2 36 35 PM](https://user-images.githubusercontent.com/6440455/154135910-63a361fd-e85b-4c34-9ee9-d35b7e2c47cc.png)

2022-02-15 19:37 UTC, bnussman commented on packages/manager/src/components/CheckBox/CheckBox.stories.mdx
> +            control: 'text',
```suggestion
            type: { summary: 'string', name: 'string' },
```

2022-02-16 20:21 UTC, HanaXu requested changes
We should include some of the other Checkbox props such as `checked` and `disabled` and set initial arg values for all the args

2022-02-17 15:57 UTC, tiffwong commented on packages/manager/src/components/CheckBox/CheckBox.stories.mdx
> +- A stand-alone checkbox is used for a single option that the user can turn on or off. Example: accepting terms and conditions.
Can we change the example to look like this: `(ie. accepting terms and conditions)`?

2022-02-17 15:58 UTC, tiffwong commented on packages/manager/src/components/CheckBox/CheckBox.stories.mdx
> +     name="Default"
Can we change the name here and in the ArgsTable to "Checkbox" so that the story won't be nested?

2022-02-17 19:13 UTC, tiffwong approved these changes

2022-02-17 20:31 UTC, HanaXu approved these changes

2022-02-18 19:19 UTC, merged