M3-5621: Update stories for Typography
linode/manager pull request #8219
Opened 2022-02-22 17:57 UTC by codyfinn

## Description

Adds stories for Typography components using the MDX format

## How to test

Ensure the stories for the Typography components render correctly.

2022-02-23 20:33 UTC, HanaXu requested changes

2022-02-23 20:33 UTC, HanaXu commented on packages/manager/src/components/Typography.stories.mdx
> +Implemented using the `h1` variant.
Can we remove the `Implemented using the <variant> variant` lines as it's kind of redundant?

2022-02-23 20:33 UTC, HanaXu commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
This looks pretty cluttered, can we add an args table for Typography instead?

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/14323019/155402727-25c15fae-c34e-4bda-9779-aca1d6f688e8.png">

2022-02-23 20:33 UTC, HanaXu commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
Not sure if we need to include this here. There's a separate `Placeholders.stories.mdx` file

2022-02-23 22:53 UTC, DevDW commented on packages/manager/src/components/Currency/Currency.stories.mdx
> +      decimalPlaces: 2,
Maybe the default quantity should be `4` so that we can toggle the `decimalPlaces` more flexibly. Right now if I set the decimal places to `0` or `1`, it still shows `4.51`.

2022-02-23 22:53 UTC, DevDW commented on packages/manager/src/components/Currency/Currency.stories.mdx
> +      wrapInParentheses: false,
for the description of this, it might be good to clarify how we use it. From the current uses I see in the codebase, it only gets used to indicate negative amounts, but the actual logic in `Currency.tsx` is a tad ambiguous as to whether that _has_ to be the case.

2022-02-24 15:40 UTC, codyfinn commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
I agree that it is cluttered but one thing I was hoping to do was have the different variants be easily compared.

2022-02-25 17:09 UTC, bnussman commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
I'd like to see an args table too if that's possible

2022-02-28 19:14 UTC, tiffwong commented on packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
> +      description: 'If the date and time provided is within the designated time frame then the date is displayed as a relative date.'
All the options display the same result for me in the ArgsTable 🤔

2022-02-28 19:14 UTC, tiffwong commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
Agreed

2022-02-28 19:17 UTC, tiffwong commented on packages/manager/src/components/Typography.stories.mdx
> +</Canvas>
I agree with having an ArgsTable

Might be cleaner if we remove `<Canvas>` from these examples and label each variant so we can still be able to compare the different styles

2022-03-01 20:11 UTC, HanaXu approved these changes

2022-03-01 21:08 UTC, bnussman approved these changes
Looks good, added one optional comment

2022-03-01 21:08 UTC, bnussman commented on packages/manager/src/components/Typography.stories.mdx
> +Utilized for
I'm not sure it's worth having `Utilized for` below every heading

2022-03-01 22:04 UTC, DevDW reviewed
Looks good overall, but there's one issue with the Date Time Display story

2022-03-01 22:04 UTC, DevDW commented on packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
> +  story="Date Time Display"
Looks like something wonky happened with the `humanizeCutoff` options -- they're not showing up

<img width="1242" alt="Screen Shot 2022-03-01 at 5 00 54 PM" src="https://user-images.githubusercontent.com/32860776/156256342-05e6833b-08bf-4a05-b097-1ae53bbf92e9.png">
s

2022-03-01 22:27 UTC, merged