M3-5700: Linode Create Replace Checkout Sidebar with Summary Paper
linode/manager pull request #8258
Opened 2022-03-07 22:15 UTC by bnussman

## Description

>  Work In Progress

## How to test

>  Work In Progress

2022-03-10 21:44 UTC, HanaXu requested changes

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/MainContent.tsx
> +        preferenceOptions={[false, true]}
Is there a reason for switching these? 🤔

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/components/CheckoutSummary/SummaryItem.tsx
> +import { SummaryItem as Props } from './index';
Can we rename this file to `CheckoutSummary` so that it's easier to search for?

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
> +              }
Add-ons checkbox and label alignment looks a bit weird to me 🤔 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/14323019/157758386-e3fc42c8-1d71-4f72-8908-7bcdb5270583.png">

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
> +    if (Boolean(this.props.privateIPEnabled)) {
I don't think we need to cast these as Booleans

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
> +        <Grid item className={`py0`}>
`'py0'`

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesCreate/TabbedContent/utils.ts
> +  details: `$${price.toFixed(2)}/monthly`,
`/month`

2022-03-10 21:44 UTC, HanaXu commented on packages/manager/src/components/CheckoutSummary/index.tsx
> +        <Typography variant="body1">Please configure your Linode.</Typography>
Padding looks off

<img width="311" alt="image" src="https://user-images.githubusercontent.com/14323019/157759173-cd42e38a-3b8f-4526-9179-904fcf73eb58.png">

2022-03-10 22:23 UTC, bnussman commented on packages/manager/src/MainContent.tsx
> +        preferenceOptions={[false, true]}
For some reason my nav side bar keeps defaulting to closed and it's been driving me insane. I think this fixed it but I'll see if this should be reverted

2022-03-14 14:48 UTC, tiffwong approved these changes
Left one small cleanup item but looks good otherwise!

2022-03-14 17:49 UTC, HanaXu approved these changes
🚢

2022-03-15 20:47 UTC, DevDW approved these changes
Looks good 👌, I left a couple of comments & I also agree with Tiffany on the Create button at smaller viewport widths.

It isn't in the mockups but I do think a sum total somewhere would be useful, was that decided against already @MBartholomew-design?

2022-03-15 20:47 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
> +              label={
Totally optional but I think the JSX can be moved into the same function and then we just pass it to `label`, e.g. something like

```
  const renderBackupsAddon = () => {
    const { backupsMonthly } = props;
    return (
      <Grid container spacing={2} alignItems="center">
        <Grid item>Backups</Grid>
        {backupsMonthly && (
          <Grid item>
            <Typography variant="body1">
              <Currency quantity={backupsMonthly} /> per month
            </Typography>
          </Grid>
        )}
      </Grid>
    );
  };
```

and then

```suggestion
label={renderBackupsAddon()}
```

makes it a tad cleaner

2022-03-15 20:47 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
> +        title: `${selectedImage.vendor ? selectedImage.label : ''}`,
the previous logic was to use `selectedImage.vendor` or fall back to `selectedImage.label` if the former wasn't defined and non-empty -- should we be sticking with that here?

2022-03-17 18:16 UTC, merged