M3-5495: UI refinements for Volume Create
linode/manager pull request #8277
Opened 2022-03-15 14:19 UTC by tiffwong

## Description

This PR adds contextual help, rearranges the Size fields, makes the Linode dropdown clearable, and removes the Tags section. The width of the fields have also been reduced.

## How to test

There are several type changes to components that are used frequently in Cloud Manager so check the other forms for regressions.

2022-03-16 20:17 UTC, HanaXu reviewed
Should we move the label icon next to the input field (as seen in the label)?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/14323019/158681075-ab2f95b2-bb2a-43ad-b1e3-73ee692c9d08.png">

2022-03-16 20:17 UTC, HanaXu requested changes
There's a bug with the region not clearing if we select a region, then select a linode, and clear the selected linode. However, if we skip selecting a region and select a linode to prefill region, then clear the selected linode, the region clears.

There's also a whitespace issue with the dropdown expanded

https://user-images.githubusercontent.com/14323019/158682531-5d191987-b92c-459d-b527-1a30e221288d.mov

2022-03-17 21:50 UTC, DevDW approved these changes
LGTM 👌

2022-03-18 14:21 UTC, bnussman reviewed
In progress of reviewing but have a few comments. 

It would be nice if this paper took up the whole width of the container. This patterns is being used just about everywhere now (Linode Create, Images Create, ...)
<img width="1534" alt="Screen Shot 2022-03-18 at 10 15 45 AM" src="https://user-images.githubusercontent.com/6440455/159020092-796576af-d765-42e0-b0a8-3beffcda0f6b.png">

Not really a change but I hope we can find some consistency on this button placement. In some places it's in the paper, in other places it's outside...
<img width="1534" alt="Screen Shot 2022-03-18 at 10 19 13 AM" src="https://user-images.githubusercontent.com/6440455/159020184-3ba6bec6-fbb0-421c-971f-988128e93ef6.png">

2022-03-18 16:47 UTC, HanaXu approved these changes
LGTM, left some minor clean up comments 🚢

2022-03-18 16:47 UTC, HanaXu commented on packages/manager/src/components/EnhancedSelect/Select.tsx
> +  label: string | JSX.Element;
Do we still need this change?

2022-03-18 16:47 UTC, HanaXu commented on packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
> +            setLinodeId(initialValueDefaultId);
```suggestion
            setFieldValue('linode_id', initialValueDefaultId);
            setLinodeId(initialValueDefaultId);
```

2022-03-18 19:41 UTC, merged