M3-5775: Add support for DBaaS Maintenance Windows
linode/manager pull request #8306
Opened 2022-04-01 16:55 UTC by DevDW

## Description
Adds support for DBaaS Maintenance Windows and updates types, factory, and schema accordingly.

## To-Do:
- [ ] Post-demo UI revisions
- [ ] Get schema validation working
- [ ] Code cleanup/refactoring

## How to test
From a Database Cluster's Settings page, set the desired maintenance window and save your changes. Ensure that the settings you indicated are correctly passed to the `POST` request.

2022-04-12 21:35 UTC, DevDW commented
Going to go ahead and open this up to review. I haven't gotten the schema validation working just yet, but it might not be necessary given the specific combination of fields here (select fields and radio fields that don't allow custom inputs requiring validation)

2022-04-13 17:32 UTC, codyfinn commented
> Going to go ahead and open this up to review. I haven't gotten the schema validation working just yet, but it might not be necessary given the specific combination of fields here (select fields and radio fields that don't allow custom inputs requiring validation)

I think having validation working would be nice if even just for consistency. But the code so far looks great! Nice job with this!

2022-04-13 18:12 UTC, HanaXu commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
> +  const [formTouched, setFormTouched] = React.useState<boolean>(false);
Instead of checking if the form has been touched to detect changes, we should check if the form values are equal to the current values to disable the Save Changes button. Otherwise, making a change and then undoing that change will un-disable the button

https://user-images.githubusercontent.com/14323019/163243412-85836628-80ce-4b54-bf04-f8963fb41785.mov

2022-04-13 21:47 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
> +  const [formTouched, setFormTouched] = React.useState<boolean>(false);
This is the same logic we have in `AddAccessControlDrawer.tsx` and `FirewallRuleDrawer.tsx`, so I'll create a separate ticket calling for the creation of a utility function for checking object deep equality that can be used in all three places

2022-04-18 15:20 UTC, HanaXu reviewed
~When I update the maintenance window and refresh, the display defaults back to the old window~ nvm I was pointing to the wrong environment lol

2022-04-18 15:43 UTC, HanaXu requested changes
Updating just the weekly time throws an API error since week of month defaults to 1

https://user-images.githubusercontent.com/14323019/163833834-acb58899-6b29-4e11-8f6e-53e5dd6df3aa.mov

2022-04-18 16:21 UTC, HanaXu approved these changes

2022-04-18 17:36 UTC, bcmertz approved these changes
LGTM!

2022-04-18 17:45 UTC, merged