M3-5759: Don't make /account requests if restricted user
linode/manager pull request #8432
Opened 2022-06-28 21:25 UTC by HanaXu

## Description
Once Cloud has established that a user is restricted, we should not attempt to request any of the account endpoints

## How to test
Go to `/account` on a restricted user and click through the tabs while verifying that we longer make requests to /account endpoints

2022-06-29 14:47 UTC, bnussman requested changes
Works great and implementation is super simple! 🚀 I found one issue that might apply to some of the queries.

2022-06-29 17:31 UTC, johnwcallahan commented on packages/manager/src/queries/account.ts
> +    enabled: !profile?.restricted,
Is the non-null assertion operator necessary here? (and similar places)

2022-06-29 18:19 UTC, codyfinn commented on packages/manager/src/queries/account.ts
> +    enabled: !profile?.restricted,
Do you mean the optional chaining operator?

2022-06-29 19:08 UTC, bnussman commented on packages/manager/src/queries/account.ts
> +  const { data: profile } = useProfile();
The profile is fetched and cached whenever Cloud Manager loads (see `AuthenticationWrapper.tsx`). So making queries dependent on the `useProfile` query should be fine. I won't actually make extra https requests unless somehow the profile is evicted from the cache.

2022-06-29 20:31 UTC, johnwcallahan commented on packages/manager/src/queries/account.ts
> +    enabled: !profile?.restricted,
Yeah, I was confusing the leading `!` with a non-null assertion; that's my mistake. Thanks for the discussion @codyfinn and @bnussman.

2022-07-01 16:55 UTC, bnussman requested changes

2022-07-01 16:55 UTC, bnussman commented on packages/manager/src/queries/accountPayment.ts
> +      enabled: grants?.global.account_access !== null,
![Screen Shot 2022-07-01 at 12 40 31 PM](https://user-images.githubusercontent.com/6440455/176935878-8a81bd97-b53b-46a3-a37a-b074a97cde94.jpg)

The `!== null` seems spot on. I think we just need this optional chain to not crash non-restricted accounts

```suggestion
      enabled: grants?.global?.account_access !== null,
```

2022-07-06 13:46 UTC, codyfinn approved these changes
Looks good to me! Might want to add tests but I don't think that is blocking.

2022-07-06 14:16 UTC, bnussman approved these changes
Nice work on this one 🚀

2022-07-06 19:30 UTC, merged