M3-5901: Support Pro Dedicated Plans
linode/manager pull request #8508
Opened 2022-08-24 18:25 UTC by HanaXu

## Description

**What does this PR do?**

## How to test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit tests?**

2022-10-13 17:40 UTC, bnussman requested changes
I don't think `Pro Dedicated CPU` should be the first item in the plans table. Can it go after `Dedicated CPU`? If a customer saw a $960 monthly price as the first plan we show, they may be very disturbed.

2022-10-13 17:40 UTC, bnussman commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +              </Typography>
Is this copy temporary? It does not sound right to me. I left what I think sounds better below.

```suggestion
              <Typography data-qa-prodedi className={classes.copy}>
                Pro Dedicated CPU instances are for very demanding workloads. They
                have AMD Epyc 2nd generation processors or newer.
              </Typography>
```

2022-10-13 19:02 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +              </Typography>
Not sure if `AMD Epyc` has been finalized so just going to leave it as `AMD 2nd generation` for now

2022-10-13 21:17 UTC, DevDW approved these changes
LGTM assuming the copy has been ran by stakeholders (even if it's still subject to change at the moment)

2022-10-14 17:33 UTC, jdamore-linode approved these changes
Looks good!

2022-10-17 15:13 UTC, merged