M3-5934: Fix MUI v5 TypeScript errors
linode/manager pull request #8545
Opened 2022-09-20 19:07 UTC by DevDW

## Description
Fix errors from TypeScript caused by the MUI v5 upgrade

## How to test
Confirm that the app compiles and check the VSCode shell and the Dev Tools console to see if any errors are logged

2022-09-21 18:47 UTC, DevDW reviewed
The changes made in this PR were informed by the breaking changes and troubleshooting sections of https://mui.com/material-ui/migration/migration-v4/.

2022-09-21 18:47 UTC, DevDW commented on packages/manager/src/components/SnackBar/SnackBar.tsx
> +      ref={notistackRef as React.RefObject<SnackbarProvider>}
this seems fair based on `notistack/dist/index.d.ts`:

![Screen Shot 2022-09-21 at 2 41 04 PM](https://user-images.githubusercontent.com/32860776/191585090-8a293df9-3d04-4955-bf17-f545ca5c25d8.jpg)

![Screen Shot 2022-09-21 at 2 41 19 PM](https://user-images.githubusercontent.com/32860776/191585087-10347927-e166-4372-84d1-b22d24840d01.jpg)

2022-09-21 18:47 UTC, DevDW commented on packages/manager/src/features/Help/Panels/PopularPosts.tsx
> +const styled: any = withStyles(styles);
not my favorite thing, but the error seemed to be intractable otherwise

2022-09-22 16:43 UTC, bnussman requested changes

2022-09-22 16:43 UTC, bnussman commented on packages/manager/src/components/Breadcrumb/FinalCrumbPrefix.tsx
> +      style={prefixStyle as React.CSSProperties}
Rather than casting the type here, can we change the import to `import { CSSProperties } from "react";` in both `packages/manager/src/components/Breadcrumb/types.ts` and `packages/manager/src/components/Breadcrumb/FinalCrumbPrefix.tsx`

2022-09-22 16:43 UTC, bnussman commented on packages/manager/src/components/SnackBar/SnackBar.tsx
> +      ref={notistackRef as React.RefObject<SnackbarProvider>}
Instead of this type case here, maybe we can update the `notistackRef` on line 43 to the following?
```ts
  const notistackRef = React.createRef<SnackbarProvider>()
```

2022-09-22 16:43 UTC, bnussman commented on packages/manager/src/features/Help/Panels/PopularPosts.tsx
> +const styled: any = withStyles(styles);
Instead of this `any`. How about we just rewrite `packages/manager/src/features/Help/Panels/PopularPosts.tsx` into a functional component. It should be a very light lift.

2022-09-23 17:58 UTC, bnussman approved these changes
Looks good. A lot of the calcs could optionally be simplified.

2022-09-23 17:58 UTC, bnussman commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
> +    marginTop: `calc(${theme.spacing()} / 2)`,
```suggestion
    marginTop: theme.spacing(0.5),
```

2022-09-26 14:31 UTC, codyfinn approved these changes

2022-09-26 15:34 UTC, merged