M3-5552: Fix Linode Add Disk Drawer UI width bug
linode/manager pull request #8558
Opened 2022-09-29 22:08 UTC by mjac0bs

## Description 📝

**What does this PR do?**
Fixes the bug causing misalignment of Password and SSH Key fields by removing the default MUI padding applied to Paper component.
For consistency, applied a bottom margin to match the top margin once bottom padding was removed.

## Preview 📷
![fixedDrawerMargins](https://user-images.githubusercontent.com/114685994/193150231-912b761e-75df-4938-9e28-2522adb23e73.jpg)
![buggyDrawerPadding](https://user-images.githubusercontent.com/114685994/193150241-cf9f52d0-2b7e-4b17-a6b6-511473480888.jpg)

## How to test 🧪
**What are the steps to reproduce the issue or verify the changes?**
Using the browser Developer Tools, view the component with the React Developer Tools > Components tab and search for 'AccessPanel'. Verify that the component's padding has been removed and a bottom margin added in its place.

2022-09-30 15:47 UTC, DevDW requested changes
Nice work getting your first PR up! 🎉 

The `<AccessPanel />` component is used in a few different files (you can do a keyword search in VSC for "<AccessPanel" to see which ones). Although the changes you made work in the "Add Disk" drawer, in some other contexts the formatting has become misaligned, for example in the Linode Create flow:

![Screen Shot 2022-09-30 at 11 36 43 AM](https://user-images.githubusercontent.com/32860776/193306174-21b3c76d-75e8-41c7-aeea-bf76ce5e07d3.jpg)

One option would be for us to make a change at a level closer to this specific individual instance the component is used in, perhaps adding some styling in `ImageAndPassword.tsx`, for example.

2022-09-30 19:44 UTC, mjac0bs commented
> Nice work getting your first PR up! 🎉
> 
> The `<AccessPanel />` component is used in a few different files (you can do a keyword search in VSC for "<AccessPanel" to see which ones). Although the changes you made work in the "Add Disk" drawer, in some other contexts the formatting has become misaligned, for example in the Linode Create flow:
> 
> ![Screen Shot 2022-09-30 at 11 36 43 AM](https://user-images.githubusercontent.com/32860776/193306174-21b3c76d-75e8-41c7-aeea-bf76ce5e07d3.jpg)
> 
> One option would be for us to make a change at a level closer to this specific individual instance the component is used in, perhaps adding some styling in `ImageAndPassword.tsx`, for example.

Thanks for catching that @DevDW! 

I've now checked that the Create Linode page, the Add Disk Drawer, and the Rebuild from Image or StackScript, where the AccessPanel is used, all seem to be aligned correctly with this updated change. I went ahead and moved the styling to the ImageAndPassword component. Let me know if there are any further revisions I should make there; I modeled my styling changes after the styling in AccessPanel.

![Screen Shot 2022-09-30 at 12 18 02 PM](https://user-images.githubusercontent.com/114685994/193344517-10138205-86d4-4543-ba40-19a180c18931.jpg)
![Screen Shot 2022-09-30 at 12 18 18 PM](https://user-images.githubusercontent.com/114685994/193344525-8d3e64d7-5a8f-4769-982a-7fbe7732df9e.jpg)
![Screen Shot 2022-09-30 at 12 20 09 PM](https://user-images.githubusercontent.com/114685994/193344529-1a0085f2-3712-4dc4-b4b7-fa9f192b457c.jpg)

2022-09-30 21:09 UTC, DevDW reviewed
Thanks for making that adjustment!

One further improvement we can make from a code pattern perspective is to make use of the `useStyles()` hook instead of `withStyles` wrapper.

The reason why `AccessPanel.tsx` uses the `withStyles` wrapper is because it is currently written as a class component, so hooks can't be used in it. However, we don't have that restriction here in `ImageAndPassword.tsx` since it is a function component.

In general, our current pattern preference is to write function components instead of class components, and to use hooks where possible over wrappers.

A related file that is a function component and uses the `useStyles()` hook that you can refer to as an example is `RebuildFromImage.tsx`.

2022-09-30 21:47 UTC, mjac0bs commented
@DevDW Makes a lot of sense! Latest commit reflects those code pattern improvements.

2022-10-03 14:18 UTC, DevDW approved these changes
Looks good! 🚀 I left a comment re: one final cleanup item

2022-10-03 14:18 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx
> +  className?: string;
Given the current approach, we can get rid of this prop

2022-10-03 15:14 UTC, mjac0bs commented
@jdamore-linode 

Could you give this a once over and let me know if my updates to `ImageAndPassword.test.tsx` look correct? I noticed that the test-manager build failed and found this error that seemed to be causing it in the [logs](https://github.com/linode/manager/actions/runs/3174976305/jobs/5172588427):

``` FAIL  src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
  ● Test suite failed to run

    TypeError: theme.spacing is not a function

      12 | const useStyles = makeStyles((theme: Theme) => ({
      13 |   root: {
    > 14 |     margin: `${theme.spacing(3)}px 0 ${theme.spacing(3)}px 0`,
         |                      ^
      15 |     padding: 0,
      16 |   },
      17 | }));
```

I updated the unit test to include the `wrapWithTheme` helper function, like `RebuildFromImage.test.tsx` and re-ran the unit tests locally, and no longer noticed the failure.

2022-10-03 15:58 UTC, jdamore-linode commented
@mjac0bs Nicely done, that is correct!

Without `wrapWithTheme(...)`, the `theme` object that gets passed to your `makeStyles(...)` callback is just `{}`, so that's why you were seeing an error saying that `theme.spacing()` doesn't exist. Any component with custom styling that depends on the `theme` object will need to use `wrapWithTheme()` in its tests :)

It's also worth mentioning that this is an older unit test that uses [enzyme](https://www.npmjs.com/package/enzyme) rather than React Testing Library. That fact isn't really relevant to your question, just pointing it out since some of the patterns you see in our older tests won't line up exactly with the patterns we use in our newer tests!

2022-10-03 16:44 UTC, jdamore-linode approved these changes
Looks great! 🚢 Nicely done @mjac0bs!

2022-10-03 18:32 UTC, merged