M3-5941: Linode landing page – Empty state
linode/manager pull request #8559
Opened 2022-09-29 22:53 UTC by codyfinn

## Description 📝

**What does this PR do?**

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2022-09-30 20:37 UTC, DevDW reviewed
left some feedback in addition to what was pointed out in the demo today -- I would say that time permitting, some of the refactoring I mention in the comments can be done in this PR, but if there are time constraints early next week then it can possibly be done in a follow-up PR instead.

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
> +            <List>
similar feedback as above re: `.map()`'ing

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
> +                <ExternalLinkIcon style={{ marginLeft: 8 }} />
could be worth making use of `useStyles()` and putting these inline styles into classes

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                  View the complete playlist
need a `{' '}` here

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                <Link to="">
playlist link?

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                  <Link to="https://www.linode.com/docs/products/databases/managed-databases/get-started/">
Should this be `https://www.linode.com/docs/products/databases/managed-databases/guides/database-engines/` instead?

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                </ListItem>
looks like this last `ListItem` is an accidental leftover

2022-09-30 20:37 UTC, DevDW commented on packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
> +              <ListItem>
these are all linking to docs still instead of the YouTube videos

2022-10-03 17:28 UTC, DevDW reviewed
The functionality is looking good.

There's still unaddressed feedback from my last review; I'm all right with the more involved refactoring being held off on until a follow-up PR but let's get the less involved pieces squared away (feel free to resolve the comment convos as you address them)

2022-10-03 17:28 UTC, DevDW commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                  View the complete playlist
Still need to add the space

2022-10-03 17:40 UTC, codyfinn commented on packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
> +                  View the complete playlist
Applying the `marginLeft` rule instead to be the same as other instances. Later this should be refactored into the `useStyles` hook as you mentioned before.

2022-10-03 17:54 UTC, codyfinn commented
>     1. The demo feedback re: section header and header icon horizontal alignment
We decided leave the icon alignment as is since the icons will never look centered due to their proportions. We figured baseline was a better place to have the icons.

2022-10-03 18:05 UTC, HanaXu requested changes
The spacing between sections seem a bit tight and uneven in the Linode Empty State
![image](https://user-images.githubusercontent.com/14323019/193644593-1e01f0fd-c2f3-4078-82c3-4529824d1169.png)

Dark mode link contrast isn't great, can we update this to look like our other dark mode links? The Marketplace App list colors look off too, we use that styling for inputs but the app links aren't inputs.
![image](https://user-images.githubusercontent.com/14323019/193645066-40fb31b2-12c6-454e-97d8-40cfcd0c7717.png)

Here's a dark mode link for reference
![image](https://user-images.githubusercontent.com/14323019/193645398-62ac6572-9b2b-4803-8d49-b32e036ad1a0.png)

2022-10-03 18:05 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
> +const YoutubeLinks = () => (
Can we have these return just JSX instead of a function?

2022-10-03 19:16 UTC, matthewbartholomew commented
vertically center pointer icons on lower case letters (move them down 2px)
![Screen Shot 2022-10-03 at 3 12 33 PM](https://user-images.githubusercontent.com/16086141/193660000-f5b5cd55-20da-4475-8338-7e9e995b7803.jpg)

2022-10-04 14:24 UTC, HanaXu approved these changes

2022-10-04 14:24 UTC, HanaXu commented on packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
> +));
This is pretty simple so I think we can just inline this instead of defining a separate variable

2022-10-04 14:46 UTC, DevDW approved these changes
LGTM now, thanks for the cleanup 🚢

2022-10-04 14:49 UTC, merged