Update imageFactory eol fied as null
linode/manager pull request #8646
Opened 2022-12-08 22:04 UTC by cpathipa

## Description 📝

End of life field is set to null in `imageFactory` As our e2e specs are using this factory to build mock data.
This fixes failed 2e2 test `create-linode-from-image.spec.ts`

## How to test 🧪
Navigate to `imageFactory` validate end of life filed

**How do I run relevant unit or e2e tests?**
yarn cypress:debug 
Then run spec file `create-linode-from-image.spec.ts` under Images

2022-12-08 22:23 UTC, cpathipa commented
@jdamore-linode Created PR to address the failed spec `create-linode-from-image.spec.ts.`

**Thought:** Wondering it would be worth if we update the spec that leverages this `imageFactory` and build expected data from it. My thought is we can make this spec more robust and avoid breakages in future because of changing any default values in the `imageFactory`. But, I'm open your thoughts on this.

2022-12-09 14:52 UTC, jdamore-linode commented
> @jdamore-linode Created PR to address the failed spec `create-linode-from-image.spec.ts.`
> 
> **Thought:** Wondering it would be worth if we update the spec that leverages this `imageFactory` and build expected data from it. My thought is we can make this spec more robust and avoid breakages in future because of changing any default values in the `imageFactory`. But, open your thoughts on this.

@cpathipa Not a bad idea at all! I would probably suggest modifying the `createMockImage()` helper function in `packages/manager/cypress/support/images.ts` to explicitly set `eol` to `null`, and then it may be worth reconsidering whether we should change the factory default at all

2022-12-09 14:55 UTC, jdamore-linode requested changes
Looking good so far!

(Edit) Whoops, disregard the previous post! I think this is good to go once you make that helper function change :)

2022-12-09 15:11 UTC, jdamore-linode approved these changes

2022-12-09 16:59 UTC, dwiley-akamai reviewed
I agree with Joe; this sort of change should be made closer to where it is consumed for the E2E test instead of at the factory level.

2022-12-09 17:14 UTC, dwiley-akamai approved these changes
🚢

2022-12-09 17:16 UTC, cpathipa commented
@jdamore-linode @dwiley-akamai Sounds good to me, I meant the same. As, we have flexibility to build the mock data with custom values from factory w.r.t to test scenario. So, reverted the initial commit made to factory `imageFactory` and updated `createMockImage`

2022-12-09 17:19 UTC, merged