Bugfix/access controls ips fix
linode/manager pull request #8665
Opened 2022-12-16 00:07 UTC by ericsund

## Description 📝

**What does this PR do?**

This PR ensures duplicates are removed by casting the access control list to a `Set`.  Furthermore, it ensures `/32` is appended to the end of every IP address in the list.

## Preview 📷

With `/32` filtering enabled:
![Screen Shot 2022-12-15 at 3 42 04 PM](https://user-images.githubusercontent.com/5467060/207990932-f80389cd-0a0c-4e43-a92e-647be957a14c.jpg)

Without `/32` filtering enabled (adding one more IP after reverting the changes):
![Screen Shot 2022-12-15 at 3 44 14 PM](https://user-images.githubusercontent.com/5467060/207991073-c656696e-4657-46d1-99f4-ec3eb787746d.jpg)

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

* Navigate to your `/databases` endpoint and create a new database (I used MySQL but it should work for any DB).
* Click the blue **Manage Access Controls** button under the **Summary** tab.
* Add an IP, like 127.0.0.0 and hit Enter right away without clicking **Update Access Controls**
* When the right sidebar collapses, ensure that `/32` is prepended to the newly added IP in the **Summary** tab.

**How do I run relevant unit or e2e tests?**

```
yarn test AccessControls.test
```

2022-12-16 15:45 UTC, dwiley-akamai reviewed
Thanks for opening this PR! 🎉 

Not sure if it's just a matter of the PR description being outdated now, but the duplicates are prevented by logic on the back-end and Cloud displays the error to users:

![Screen Shot 2022-12-16 at 10 44 13 AM](https://user-images.githubusercontent.com/114682940/208135389-5fb921f1-b6b5-4ba7-b785-abc3a949ad93.jpg)

![Screen Shot 2022-12-16 at 10 28 32 AM](https://user-images.githubusercontent.com/114682940/208135078-2bd551aa-fb7e-4a24-a41c-342f24567e4d.jpg)

Were you somehow still ending up with duplicates getting through?

2022-12-16 16:30 UTC, ericsund commented
Thanks @dwiley-akamai!  I realized duplicates were already being handled, so I removed code that casts it to a `Set` in my last commit -- just didn't take it out in the PR description.  The issue of `/32` missing is still present, though.

2022-12-16 19:16 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
>      const allowListRetracted = _allowList
Since the chained array methods are starting to pile up now (3), we can consider using `.reduce()` instead. We'll avoid looping over the array 3 separate times, while still getting the IP strings, filtering out the empty strings, and appending `/32` if needed.

```suggestion
    const allowListRetracted = _allowList.reduce((acc, currentIP) => {
      let ipString = extendedIPToString(currentIP);
      if (ipString === '') {
        return acc;
      }

      if (ipString.indexOf('/32') === -1) {
        ipString += '/32';
      }

      return [...acc, ipString];
    }, []);
```

2022-12-16 21:38 UTC, dwiley-akamai approved these changes

2022-12-19 16:33 UTC, ericsund commented
Can we get some feedback from @bnussman as well?

2022-12-19 17:17 UTC, bnussman-akamai requested changes
I'm not sure adding `/32` to every IP is exactly the behavior we want. I tried adding a new IP address to an existing allow list and it caused `/32` to be added to a `/16` I already had setup. 

https://user-images.githubusercontent.com/115251059/208482721-2c638369-a6c2-40dc-b472-a6e915cc2f68.mov

2022-12-20 15:04 UTC, bnussman-akamai approved these changes

2022-12-20 15:27 UTC, cpathipa approved these changes

2022-12-20 16:13 UTC, merged