surface any api errors during paypal one time payment
linode/manager pull request #8666
Opened 2022-12-19 20:15 UTC by bnussman-akamai

## Description 📝

- Surface any API errors that happen when we make a payment with PayPal 
  -  Previously we just showed a generic error
  - This is important because the API may return something like `{ "errors": [ { "reason": "Maximum amount is $2000.00" } ] }`
- Makes Paypal and Google pay buttons use updated limit logic

## Preview 📷

> **Warning**: Work in progress

## How to test 🧪

> **Warning**: Work in progress

2022-12-21 18:07 UTC, cpathipa requested changes
Nice work @bnussman-akamai, Only thing I have is, we can probably use async / await and replace chained promises.

2022-12-22 16:13 UTC, cpathipa commented
LGTM! Thank you @bnussman-akamai for addressing the feedback.

2022-12-22 16:13 UTC, cpathipa approved these changes

2022-12-22 16:29 UTC, bnussman-akamai commented
Thanks for the help on this! @cpathipa 🚀

2023-01-03 21:32 UTC, carrillo-erik commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
> +          title={`Payment amount must be between $${min} and $${max}`}
Nice way to get rid of extra in-line logic.

2023-01-03 21:33 UTC, carrillo-erik approved these changes

2023-01-04 16:07 UTC, merged