select respective plan tab w.r.t the selected linode to be cloned.
linode/manager pull request #8670
Opened 2022-12-20 22:14 UTC by cpathipa

## Description 📝

**What does this PR do?**

- In the Plan selection table, default selection to the currently selected Linode's plan
- Add the "Current Plan" chip to the selected Linode's plan 
- Focus the correct tab on the plan selection table.

Address this in both cloning and resizing Linode. 

## Preview 📷

![image](https://user-images.githubusercontent.com/119517080/208776355-4f1da731-3aae-4563-9bfe-8f080de4d8b3.png)

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

- Click clone Linode
- Select Linode to be cloned
- Scroll down the page and validate selected tab w.r.t the Linode's plan.
- 

- Click resize Linode
- Scroll down the modal and validate selected tab w.r.t the Linode's plan.

**How do I run relevant unit or e2e tests?**

`yarn test`

2022-12-21 23:01 UTC, dwiley-akamai requested changes
1. In the Resize flow, if you select a different plan, you get two "Current Plan" chips:

![Screen Shot 2022-12-21 at 5 45 41 PM](https://user-images.githubusercontent.com/114682940/209017109-f9dea09a-5c73-498f-bb99-1640f21459e0.jpg)

2. In the Clone flow, when you select a different plan, the "Current Plan" chip moves to whichever plan is selected at that moment. Is this the intended behavior per the discussion on the ticket?

IMO the behavior for the Resize flow should remain as it is in prod with regards to the chip, but we should have the appropriate plan tab selected upon modal open. And for the Clone flow, maybe the "Current Plan" chip should be displayed on the plan of the to-be-cloned-Linode, unless the user selects a different plan, at which time the chip would go away?

I also left a few other minor comments related to the linter and conventions.

2022-12-22 15:04 UTC, cpathipa commented
> 1. In the Resize flow, if you select a different plan, you get two "Current Plan" chips:
> 
> ![Screen Shot 2022-12-21 at 5 45 41 PM](https://user-images.githubusercontent.com/114682940/209017109-f9dea09a-5c73-498f-bb99-1640f21459e0.jpg)
> 
> 2. In the Clone flow, when you select a different plan, the "Current Plan" chip moves to whichever plan is selected at that moment. Is this the intended behavior per the discussion on the ticket?
> 
> IMO the behavior for the Resize flow should remain as it is in prod with regards to the chip, but we should have the appropriate plan tab selected upon modal open. And for the Clone flow, maybe the "Current Plan" chip should be displayed on the plan of the to-be-cloned-Linode, unless the user selects a different plan, at which time the chip would go away?
> 
> I also left a few other minor comments related to the linter and conventions.

@dwiley-akamai Good catch! Applied the fix.  Also, I think we should revisit the linter configurations, since we are loosing some of the TS features. 
https://user-images.githubusercontent.com/119517080/209161730-6d0f6f40-792b-4350-8273-71678f0ab177.mov

2022-12-22 17:48 UTC, dwiley-akamai approved these changes

2022-12-22 20:15 UTC, bnussman-akamai approved these changes
Nice improvement

2022-12-22 20:19 UTC, merged