M3-5182: RQ-ify Images, Pt. 2
linode/manager pull request #8673
Opened 2022-12-21 21:48 UTC by dwiley-akamai

## Description 📝
Part 2 of the effort to transition Images from Redux to React Query.

## How to test 🧪
Coming soon

2022-12-22 20:31 UTC, bnussman-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
> +  withImages,
Is `withImages` needed here?

2023-01-03 17:35 UTC, dwiley-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
> +  withImages,
Nope, I went ahead and removed that

2023-01-18 20:48 UTC, bnussman-akamai reviewed
I have a few small items and I see that the unit tests are failing. Do you intend to fix those in the next PR?

2023-01-18 20:48 UTC, bnussman-akamai commented on packages/manager/src/features/Images/utils.ts
> +  const grants = getGrantData();
Should we be using the hooks here instead? I remember keeping `getProfileData` and `getGrantData` only so we could get the RQ data in class components.

2023-01-18 20:48 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
>    }
I think we should remove this entire chunk of logic. The `LinodeCreateContainer` should have no business dealing with the freshness of the Images data. 

I think for now, we just remove this chunk of code, and fine tune staleTime of the images query down the road

2023-01-19 23:02 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
>    }
That should be fine, I removed this chunk.

2023-01-19 23:04 UTC, dwiley-akamai commented
> I have a few small items and I see that the unit tests are failing. Do you intend to fix those in the next PR?

The test that failed before seemed to be an unrelated stray flake. I merged `develop` into the feature branch and rebased so everything should be fine now, but I'll keep an eye on it.

2023-01-20 16:17 UTC, bnussman-akamai requested changes
When I load up Cloud Manager and go to `http://localhost:3000/linodes`, I see 4 listeners to the images query. I think we really should work to make this number 0. Unless something on the screen renders an image's information. We should try to not query until we really need to. Here's what I think we should do:

1. Remove useAllImagesQuery() from `packages/manager/src/features/linodes/LinodesLanding/index.tsx` completely
2. Remove any `withImages` usage from `packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx`
3. The `packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx` dialog should use the `open` prop to conditionally enable the  `useAllImagesQuery` so that data is not fetched until the dialog is open
4. `useAPISearch` should not query images unless someone is searching

Resolving those 4 items will allow us to load `http://localhost:3000/linodes` without making any requests to the images endpoint. This is definitely an over-optimization in some ways but will be very beneficial at scale

2023-01-20 16:17 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodeEntityDetail.tsx
> +  const { data: images } = useAllImagesQuery({}, {});
Why not use `useImageQuery` here? Is it to prevent another fetch?

2023-01-20 22:21 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodeEntityDetail.tsx
> +  const { data: images } = useAllImagesQuery({}, {});
Yes, that was the intention with this

2023-01-24 14:59 UTC, bnussman-akamai approved these changes
Looks good!

I think the "use all" approach makes sense for images considering how they are used and what they are needed for. For further optimization we could start replacing  client side filtering with api filters. For example, replacing the `filteredImages` in `ImageSelect.tsx` with a dynamic API filter.

2023-01-25 20:48 UTC, hana-linode approved these changes
Functionality looks good to me!

Not sure if this is related to the sorting issue but the sorting for the search results seem to be in a different order than prod

Prod:

https://user-images.githubusercontent.com/115299789/214686983-98d2e276-cc55-495d-860b-f0d9d8ac808e.mov

This branch:

https://user-images.githubusercontent.com/115299789/214687037-21d774aa-d72f-4bc3-9af4-7173a92af6fa.mov

2023-01-25 20:48 UTC, hana-linode commented on packages/manager/src/features/Search/SearchLanding.tsx
> +  // const _isLargeAccount = true;
Can we remove this comment?

2023-01-27 16:43 UTC, dwiley-akamai commented
Thanks for the comments here, I'll circle back around and look into these items in Pt. 3.

2023-01-27 18:33 UTC, merged