Increase page size to prevent api throttle error
linode/manager pull request #8678
Opened 2022-12-28 18:52 UTC by carrillo-erik

## Description 📝

This PR increases the page size from 25 to 500 in order to avoid the API from throttling users who switch routes frequently resulting in a 429 error code from the server.

## Preview 📷
**`page_size=25`**
![page-size-25](https://user-images.githubusercontent.com/119514965/209858910-2ebfbbaf-4716-456c-b82f-c428fb43cf8e.jpg)

**`page_size=500`**
![page-size-500](https://user-images.githubusercontent.com/119514965/209858916-14582dd2-dd9c-43ab-8344-a346e192d673.jpg)

## How to test 🧪
Log into Cloud Manager with a user account that has more than one StackScript. Next navigate to any other page and then quickly return to the StackScripts landing page. User should NOT experience any 429 server codes.

**How do I run relevant unit or e2e tests?**
`yarn test`

2022-12-28 21:52 UTC, bnussman-akamai requested changes
This seems to fix this issue of hitting the rate limit, but now, rather than the `Community StackScripts` tab loading 25 items at a time, it seems to just load 500. Can we keep the old behavior on the `Community StackScripts` tab?

2022-12-29 15:39 UTC, carrillo-erik commented
> This seems to fix this issue of hitting the rate limit, but now, rather than the `Community StackScripts` tab loading 25 items at a time, it seems to just load 500. Can we keep the old behavior on the `Community StackScripts` tab?

I see the side effect this is causing, I will look into it. Thanks for catching it.

2022-12-29 16:10 UTC, cpathipa commented
I agree with @bnussman-akamai point, As long as we don't get rate limit issue by page_size to 25 only for community tab we should be good.

2022-12-30 15:00 UTC, cpathipa reviewed
@carrillo-erik We can use prop `category` to set page size for community.

2023-01-03 15:14 UTC, carrillo-erik commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
> +            window.location.pathname === '/stackscripts/community' ? 25 : 500,
Thank you for showing me this, I had missed it. I've made the change.

2023-01-03 15:32 UTC, cpathipa approved these changes

2023-01-03 15:53 UTC, bnussman-akamai approved these changes

2023-01-03 16:01 UTC, merged