Manual Backups for Managed Databases
linode/manager pull request #8692
Opened 2023-01-07 01:15 UTC by ericsund

## Description 📝

**What does this PR do?**

Enables managed database users to trigger backups on demand.  This will hit the `POST` endpoint with a custom label, defined here in the public API: https://www.linode.com/docs/api/databases/#managed-mysql-database-backup-snapshot-create

This is a proof of concept -- more details to come.

## Preview 📷

https://user-images.githubusercontent.com/5467060/211124090-5d631a69-88d0-4e59-85c3-87242f33c50e.mov

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

Head to the managed databases using the left sidebar.  Create a new managed database (or use an existing one).  Select your database, then hit the `Backups` tab.  From here, you should see a `Manual Backup` section, where you'll be able to click the blue `Start Backup` button.  Enter a custom label using only alphanumeric characters and no spaces, then click `Backup Database`.  Observe that the correct endpoint is hit successfully.

**How do I run relevant unit or e2e tests?**

`yarn test` (for now)

2023-01-13 21:20 UTC, bnussman-akamai reviewed
Thank you for adding these features! Here are a few comments to start with

2023-01-13 21:20 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +          style={{ marginLeft: 12, marginTop: 12 }}
I think this button looks a bit weird with the left margin. I think it would be okay to align it left with the header and other text.

2023-01-13 21:20 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseDeleteDialog.tsx
> +const enhanced = compose<CombinedProps, Props>(withPreferences());
Rather than using withPreferences, can you use the `usePreferences` hook

2023-01-13 21:20 UTC, bnussman-akamai commented on packages/manager/src/utilities/formatBackupLabel.ts
> +export const formatBackupLabel = (backup: any): string => {
I think I'd prefer to have this file in `packages/manager/src/features/Databases/` called something more generic like `utils.ts`. That way we can add more DBaaS helper functions in the future.

2023-01-13 21:20 UTC, bnussman-akamai commented on packages/manager/src/utilities/formatBackupLabel.ts
> +export default formatBackupLabel;
Lets remove the default export

```suggestion
```

2023-01-13 21:20 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseDeleteDialog.tsx
> +      history.push('summary');
I don't think we need to redirect the user back to summary here

```suggestion
```

2023-01-13 23:42 UTC, ericsund commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseDeleteDialog.tsx
> +const enhanced = compose<CombinedProps, Props>(withPreferences());
Can you describe a the benefit of using `usePerferences()` over `withPerferences()`?

2023-01-13 23:43 UTC, ericsund commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +          style={{ marginLeft: 12, marginTop: 12 }}
Fair point -- removed the left offset.

2023-01-13 23:44 UTC, ericsund commented on packages/manager/src/utilities/formatBackupLabel.ts
> +export const formatBackupLabel = (backup: any): string => {
Good idea, this will indeed grow in the future.

2023-01-17 14:51 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseDeleteDialog.tsx
> +const enhanced = compose<CombinedProps, Props>(withPreferences());
No major benefits, it's just a more modern approach, uses less code, and is easier to trace.

2023-01-19 15:47 UTC, bnussman-akamai requested changes

2023-01-19 15:47 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.css
> +}
In Cloud Manager, we try to avoid using `.css` files whenever possible. Can we move this into the same file as a component?

2023-01-19 15:47 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/databaseUtils.ts
> +export const generateManualBackupLabel = (): string => {
Why did we decide to not let users choose their own label? We should let users choose their label if the API supports it.

2023-01-19 16:50 UTC, ericsund commented on packages/manager/src/features/Databases/databaseUtils.ts
> +export const generateManualBackupLabel = (): string => {
Marking this as resolved: discussed that this approach would make the UI more intuitive for this scope.

2023-01-19 18:08 UTC, bnussman-akamai requested changes

2023-01-19 18:08 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +          className="backups_section"
```suggestion
```

2023-01-19 20:01 UTC, bnussman-akamai approved these changes
Nice work on this!

2023-01-19 22:26 UTC, hana-linode reviewed
Functionality looks good! Left some clean up comments

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/CreateBackupDialog.tsx
> +        another.
Copy sounds a bit off, did UX approve of this copy? 🤔

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +      </Paper>
Can we hide this while the Database is provisioning?
![image](https://user-images.githubusercontent.com/115299789/213572745-b66fcf67-15aa-41bd-9ecc-946a1e901848.png)

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DeleteBackupDialog.tsx
> +          manual backup frees up space that counts toward the limit of 3.
Same here, copy seems a bit verbose/off. Did UX approve this copy?

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DeleteBackupDialog.tsx
> +      />
Can we use the `TypeToConfirmDialog` component here? (might require a little bit of refactoring)

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/databaseUtils.ts
> +    +currDate.getSeconds()
We can use a template literal here instead of concatenating strings together

2023-01-19 22:26 UTC, hana-linode commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +        }
We can clean up these `backup.type === 'snapshot'` conditionals with a map variable

Something like:
```typescript
  interface backupDialogData {
    title: string;
    confirmationText: JSX.Element;
    label: string;
  }

  const backupDialogMap: Record<DatabaseBackupType, backupDialogData> = {
    snapshot: {
      title: `Restore Manual Backup ${formatDate(backup.created)}`,
      confirmationText: (
        <span>
          To confirm manual backup restoration, type the date/time of the manual
          backup (<strong>{formatDate(backup.created)}</strong>) from the{' '}
          <strong>{database.label}</strong> database in the field below.
        </span>
      ),
      label: `Manual backup date from  ${database.label}`,
    },
    auto: {
      title: `Restore Automatic Backup ${formatDate(backup.created)}`,
      confirmationText: (
        <span>
          To confirm automatic backup restoration, type the date/time of the
          automatic backup (<strong>{formatDate(backup.created)}</strong>) from
          the <strong>{database.label}</strong> database in the field below.
        </span>
      ),
      label: `Automatic backup date from  ${database.label}`,
    },
  };
```

2023-01-20 12:41 UTC, matthewbartholomew commented
This is looking great. UX copy needs to be finalized.

2023-01-20 15:33 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
> +      </Paper>
Pushed up a03291a to address this @hana-linode. Can you double check my logic in that commit?

2023-01-20 22:14 UTC, ericsund commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DeleteBackupDialog.tsx
> +          manual backup frees up space that counts toward the limit of 3.
Sounds like @matthewbartholomew will follow up.

2023-01-20 23:02 UTC, ericsund commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DeleteBackupDialog.tsx
> +      />
Can you describe some differences between `TypeToConfirmDialog` and `TypeToConfirm`?  We use one in `/object-storage/buckets` and it appears functionally the same.  Any advantages of using one over the other?

2023-01-21 00:56 UTC, ericsund commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +        }
Nifty!  Thanks, I hadn't thought of doing this.

2023-01-21 01:07 UTC, ericsund commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +              To confirm deletion, type the{' '}
There are two usages of `TypeToConfirmDialog` in this change: one in `RestoreFromBackupDialog.tsx` and one in `DeleteBackupDialog.tsx`.  In both cases, we provide a custom `confirmationText` prop which overrides the default one, so we don't ever need it.

However, I've made the default dialog more generic by adding a `TypeToConfirmDialogMap`.  The intention here is to make this dialog future-proof so we can use it on more `EntityType`s.  Let me know if this is worthwhile to keep (even though it doesn't actually benefit us now).

2023-02-15 22:05 UTC, dwiley-akamai reviewed
We need to handle for the event in the Events dropdown:

![Screen Shot 2023-02-15 at 4 31 16 PM](https://user-images.githubusercontent.com/114682940/219182270-0d3bc7f4-a865-49c7-8883-3be2cea8f503.jpg)

(this would be done in `eventMessageGenerator.ts`)

It also seems that the Backups table doesn't update on its own once the manual backup is created successfully

2023-02-15 22:05 UTC, dwiley-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +              To confirm deletion, type the{' '}
I don't think it'd be bad to keep this, seems nice to have. I'd probably move lines 114-120 into a variable outside the `return` statement just to tidy this area of the code up a bit. Could store `TypeToConfirmDialogMap[entity.type].labelPrefix` in a `const` as well.

2023-02-24 19:00 UTC, jaalah-akamai commented
@ericsund A few minor changes here and we should be good to go!

2023-03-08 22:42 UTC, jaalah-akamai commented
This PR is paused since until we determine who will be taking over this work from @ericsund and if this is the route they want to continue to take.

2023-03-15 14:59 UTC, bnussman-akamai commented
This PR can probably be reviewed by the team. All it needs is final copy 📝

2023-07-25 15:31 UTC, closed without merging