M3 dynamically generate c url and cli
linode/manager pull request #8710
Opened 2023-01-11 20:08 UTC by CodyFinn-Akamai

## Description 📝

Adds functions to generate Linode CLI and cURL commands to create Linodes.
This is a work in progress to just get the basics down. I want to move this to a single function or an object that can generate both cURL and Linode CLI comands.

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2023-01-11 21:04 UTC, cpathipa commented
@CodyFinn-Akamai This should go to `feature/api-cli` branch

2023-01-25 15:50 UTC, carrillo-erik requested changes

2023-01-25 15:50 UTC, carrillo-erik commented on packages/manager/src/utilities/generate-cURL.ts
> +  return command.trimStart().trimEnd();
I think you can simply use the `.trim()` method here instead. I believe it accomplishes the same result you are looking for.

2023-01-25 15:50 UTC, carrillo-erik commented on packages/manager/src/utilities/generate-cli.ts
> +    .trimEnd();
Same thing in this instance as my previous comment, the `.trim()` method returns a new string without the whitespaces from beginning and end of the original string.

2023-01-25 19:19 UTC, carrillo-erik approved these changes

2023-01-25 20:03 UTC, cpathipa commented
Hold on merging this PR until M3-6047 merges to the feature branch.

2023-01-26 19:31 UTC, cpathipa approved these changes
LGTM!

2023-01-26 19:31 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
>    // This harcoded values will be removed as part of following story that generated dynamic CURL and CLI commands.
We can remove this comment.

2023-01-26 20:45 UTC, merged