M3 6047
linode/manager pull request #8725
Opened 2023-01-13 21:44 UTC by cpathipa

## Description 📝

Work in progress...

## Preview 📷

Work in progress...

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2023-01-25 15:54 UTC, CodyFinn-Akamai commented on packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
> +                  fireGAEvent('Click: Get Started with the Linode API')
This probably needs to be documented better but the fields for GA events are supposed to represent the following:
category: Where in the application this event is coming from
action: Type of interaction and type of contextual help
label: The text displayed on the textual help to the user

So in this case I think the GA event would look something like:
```
{
  category: 'Linode Create API CLI Awareness Modal',
  action: 'Click:link',
  label: 'Get Started with the Linode API'
}
```

2023-01-25 16:02 UTC, carrillo-erik requested changes

2023-01-25 16:02 UTC, carrillo-erik commented on packages/manager/src/features/linodes/LinodesCreate/CodeBlock/styles.ts
> +    top: '8px',
Changing this to `30px` fixes the UI defect where the copy icon is on top of the command text.

2023-01-25 20:08 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/CodeBlock/styles.ts
> +    top: '8px',
Actually this causing by hardcoded command using template literals. Once command is generated dynamically headers will be printed in multiple lines.

2023-01-25 20:41 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
> +                  fireGAEvent('Click: Get Started with the Linode API')
Thank you @CodyFinn-Akamai for guiding on this.

2023-01-25 21:06 UTC, CodyFinn-Akamai commented on packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
> +    action: `Click:${action}`,
Sorry I was unclear in the last comment. The format for the action property should be:

<ActionTheUserDid>:<TypeOfContextualHelp>

So in this case it would be the string literal `'Click:link'` since the user clicked on a link. If the user hovered over a tooltip the proper action property would be the string literal `'Hover:tooltip'`

2023-01-25 21:21 UTC, CodyFinn-Akamai requested changes

2023-01-25 21:21 UTC, CodyFinn-Akamai commented on packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
> +    action: 'Click:Link',
It should be `'Click:link'` to be consistent with our other usage

2023-01-25 21:37 UTC, CodyFinn-Akamai approved these changes

2023-01-25 21:52 UTC, bnussman-akamai requested changes

2023-01-25 21:52 UTC, bnussman-akamai commented on packages/manager/package.json
> +    "highlightjs-curl": "1.3.0",
```suggestion
```

I think we can completely remove `highlightjs-curl` and references to curl. cURL is not necessarily even a language. If we just use `language: "bash"` we get good enough syntax highlighting for cURL

2023-01-25 21:52 UTC, bnussman-akamai commented on packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
> +      )}
I believe that this works the same and is more simple

```suggestion
      className={classNames(classes.root, 'formatted-text', className)}
```

2023-01-26 15:23 UTC, bnussman-akamai approved these changes

2023-01-26 15:23 UTC, bnussman-akamai commented on packages/manager/src/components/HighlightedMarkdown/highlight.d.ts
> +declare module 'highlightjs-curl';
```suggestion
```

2023-01-26 15:34 UTC, merged