M3-5182: RQ-ify Images Pt. 3
linode/manager pull request #8756
Opened 2023-02-02 20:28 UTC by dwiley-akamai

## Description 📝
Complete the trilogy of PRs for the RQ-ify Images effort.

Detailed description forthcoming

## How to test 🧪
Coming soon

2023-02-08 21:26 UTC, dwiley-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +                <TableCell>Status</TableCell>
We were hoping we'd be able to sort by `Status` with an x-filter via the API. Making this sortable works when you first click on the column cell, but if you navigate away from the Images landing page and come back, it will fail, and navigating directly to a URL with the sort-related params will fail as well.

We don't do any client-side sorting elsewhere in the app in these situations, so I decided to make this column non-sortable. If the API supports it down the line, we can come back and update this accordingly.

2023-02-09 16:57 UTC, bnussman-akamai reviewed
On `ImagesLanding.tsx`, I was expecting to see two `useImagesQuery`s. With the current implementation, I'm not sure how pagination would work in regards to going to the next page of either `Custom` or the `Recovery` section. 

```ts
  const {
    data: automaticImages,
    isLoading: automaticImagesLoading,
    error: automaticImagesError,
  } = useImagesQuery(
    {
      page: pagination.page,
      page_size: pagination.pageSize,
    },
    {
      type: 'automatic',
      is_public: false,
      ...filter,
    }
  );

  const {
    data: manualImages,
    isLoading: manualImagesLoading,
    error: manualImagesError,
  } = useImagesQuery(
    {
      page: pagination.page,
      page_size: pagination.pageSize,
    },
    {
      type: 'manual',
      is_public: false,
      ...filter,
    }
  );
```

Is filtering on `type` bugged or not possible? I can't seem to get it to work

2023-02-13 16:46 UTC, dwiley-akamai commented
Confirmed there is an API bug for filtering with automatic private images. The most recent commit has the logic splitting out the automatic and manual images queries though. We can hold off on releasing the Images RQ-ification work until the API bug has been fixed

2023-02-16 21:29 UTC, dwiley-akamai commented
The API bug fix has been merged into dev and will be released to prod next week, so I'm removing the `Blocked` label here as this can be tested currently by pointing your local to the `dev` environment

2023-02-21 18:50 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +  const pagination = usePagination(1, queryKey);
We will need 2 `usePagination`s on this page becuase each table needs different state to track the page numbers

2023-02-21 18:50 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +  const { order, orderBy, handleOrderChange } = useOrder(
Same here applies to `useOrder`. Users may want to sort each table by different keys at the same time. The 3ed paramater of `useOrder` will need to be used here so that the query params have a way to differentiate between the two tables

2023-02-22 20:55 UTC, bnussman-akamai requested changes

2023-02-22 20:55 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +    `automatic-${queryKey}`
For all of these preference keys, I think we should have the common key first followed by the variant.

```suggestion
    `${queryKey}-automatic`
```

2023-02-22 20:55 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
>    );
For both of the `useOrder` hooks, I think we should add a 3ed parameter so that the query params don't override each other when sorting.

```suggestion
    `${queryKey}-automatic-order`,
    'automatic'
  );
```

![Screenshot 2023-02-22 at 3 43 33 PM](https://user-images.githubusercontent.com/115251059/220754906-71fc10c5-b669-46f1-b52c-4beb6b844bb4.jpg)

2023-02-22 20:55 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +                <TableCell>Created</TableCell>
Let's let people sort by `created` because the API supports it

```suggestion
                <TableSortCell
                  active={automaticImagesOrderBy === 'created'}
                  direction={automaticImagesOrder}
                  label="created"
                  handleClick={handleAutomaticImagesOrderChange}
                >
                  Created
                </TableSortCell>
```

2023-02-22 20:55 UTC, bnussman-akamai commented on packages/manager/src/features/Images/ImagesLanding.tsx
> +                <TableCell>Created</TableCell>
```suggestion
                <TableSortCell
                  active={manualImagesOrderBy === 'created'}
                  direction={manualImagesOrder}
                  label="created"
                  handleClick={handleManualImagesOrderChange}
                >
                  Created
                </TableSortCell>
```

2023-02-23 17:36 UTC, bnussman-akamai approved these changes
Looking good. I'll do more testing when we get this merged into `feature/react-query-images` but things look great so far!

2023-02-24 14:14 UTC, jaalah-akamai approved these changes

2023-02-24 15:09 UTC, merged