[M3-5195] RQ-ify user preferences
linode/manager pull request #8795
Opened 2023-02-14 22:36 UTC by hkhalil-akamai

## Description 📝

**What does this PR do?**

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2023-02-17 21:40 UTC, hkhalil-akamai commented on packages/manager/src/features/Help/StatusBanners.test.tsx
> +    it("clicking a banner's close icon should remove it from view", () => {
[Context](https://github.com/linode/manager/pull/8803#discussion_r1109086845)

2023-02-21 18:26 UTC, bnussman-akamai reviewed
This is **amazing** clean up. Good job working through all of the unit tests, I'm sure that was not easy. I left a good bit of minor feedback items.

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/App.tsx
> +              ...this.props.preferences,
Do we need to spread and include the old preferences data here? I think the mutation handler should take care of that

```suggestion
```

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
> +  withPreferences
Can we just use the `usePreferences` hook in this component?

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/components/MainContentBanner.tsx
>  export default enhanced(MainContentBanner);
Can we use hooks in this component instead of `withPreferences`?

```suggestion
export default React.memo(MainContentBanner);
```

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/containers/preferences.container.ts
> +  }
I don't know if it is great to block rendering if `preferences` is `undefined`. Is this necessary?

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
>  export default enhanced(RestoreFromBackupDialog);
Let's use the hooks in this component too.

```suggestion
export default RestoreFromBackupDialog;
```

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
>  export default enhanced(DatabaseSettingsDeleteClusterDialog);
Use hooks in this component

```suggestion
export default DatabaseSettingsDeleteClusterDialog;
```

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/Profile/Settings/Settings.tsx
> +    updatePreferences({ ...preferences, theme: newTheme });
Same feedback as earlier. Do we need to spread preferences here (`...preferences`) if the mutation handler takes care of that?

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
> +  withPreferences
Use Hooks in the component

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +  withPreferences,
use Hooks in this component

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/features/Profile/Settings/Settings.tsx
> +    );
I see what you are accomplishing with `indicatePromise`,  but to me it hurts readability. If I were new to the repo i'd have to jump to `indicatePromise`'s definition to understand how it works. Maybe the team has some thoughts?

2023-02-21 18:26 UTC, bnussman-akamai commented on packages/manager/src/queries/preferences.ts
> +  func(...args).then((preferences) => preferences as ManagerPreferences);
Can you explain what this does?

2023-02-21 18:55 UTC, hkhalil-akamai commented on packages/manager/src/features/Profile/Settings/Settings.tsx
> +    );
Yeah the idea was that it can be easy to forget to reset the loading state, leading to infinite loading. But I agree that it impacts readability.

Another (albeit more complicated) way to accomplish this is to globally define a `Promise.prototype.indicate` method.

2023-02-21 18:56 UTC, hkhalil-akamai commented on packages/manager/src/queries/preferences.ts
> +  func(...args).then((preferences) => preferences as ManagerPreferences);
This was purely to make TypeScript happy and cast from API's `UserPreferences` type to the new `ManagerPreferences` interface. Removed since this doesn't seem necessary anymore.

2023-02-21 19:19 UTC, jdamore-linode reviewed
Seeing an issue with the preference editor at `/profile/settings?preferenceEditor=true` -- there's a little "Loading..." indicator that appears and disappears, causing a flickering effect, and it seems like each time that happens it resets the contents of the text box, making it difficult (impossible?) to edit:

https://user-images.githubusercontent.com/97627410/220438076-57b926ef-9446-4ec6-be97-d9530c9d1c4d.mp4

(It also seems like each flicker corresponds to a GET request to `profile/preferences`, so be careful not to linger too long on that dialog)

2023-02-21 19:35 UTC, jdamore-linode commented
E2E tests pass, and manually went through flows involving all of the components you listed in the PR description. Didn't notice anything aside from that issue above! I'll circle back to test any new changes and approve this once you've had a chance to check out that issue and Banks's suggestions. Awesome work!

2023-02-21 19:48 UTC, hkhalil-akamai commented on packages/manager/src/containers/preferences.container.ts
> +  }
Looks like the original behavior was to pass the empty object `{}` while preferences were loading, would that be preferable to render-blocking?

2023-02-21 22:00 UTC, hkhalil-akamai commented on packages/manager/src/App.tsx
> +              ...this.props.preferences,
There appears to be some inconsistency between the `profile` and `preferences` APIs. Whereas `updateProfile` only updates the provided fields, `updateUserPreferences` will totally overwrite the existing record with the provided data. Hence the spread is currently necessary.

We could possibly move the spread to the `useMutatePreferences` hook to locally emulate this behavior.

2023-02-21 22:01 UTC, hkhalil-akamai commented on packages/manager/src/features/Profile/Settings/Settings.tsx
> +    updatePreferences({ ...preferences, theme: newTheme });
[See above](https://github.com/linode/manager/pull/8795#discussion_r1113612423)

2023-02-21 22:58 UTC, hkhalil-akamai commented
Not strictly related to this PR, a concern from testing the `PreferenceEditor` is that users can set the preference blob to invalid values (e.g., setting `theme` to `"not a real theme"`) and thus break the Cloud Manager for themselves. Arguably, the user preferences type should be defined as:

```
export type UserPreferences = Record<string, unknown>;
```

instead of:

```
export type UserPreferences = Record<string, any>;
```

This forces components to validate preference values before using them.

2023-02-21 23:01 UTC, bnussman-akamai commented on packages/manager/src/containers/preferences.container.ts
> +  }
I think it would be best for the HOC to match RQ as much as possible, so we just pass whatever React query returns. For example `PreferencesStateProps` would become

```ts
export interface PreferencesStateProps {
  preferences: ManagerPreferences | undefined;
}
```

2023-02-22 19:33 UTC, bnussman-akamai requested changes
Found a bug. I think what's happening is that the `updatePreferences` is being called without the old preferences being spread, causing all of the existing preferences to go away. This is in the `useOrder` hook. 

I think the best solution for this would be to do what you recommended so that other consumers of the `useMutatePreferences` don't cause this same bug in the future.

> We could possibly move the spread to the useMutatePreferences hook to locally emulate this behavior.

Something like this (double check what I did here)
```
export const useMutatePreferences = () => {
  const { data: preferences } = usePreferences();

  return useMutation<ManagerPreferences, APIError[], ManagerPreferences>(
    (data) => updateUserPreferences({ ...(preferences ?? {}), data }),
    {
      onMutate: updatePreferenceData,
    }
  );
};
```


https://user-images.githubusercontent.com/115251059/220737563-f55f8c07-ecd7-4773-9ffe-bb2abefdca89.mov

2023-02-23 23:19 UTC, bnussman-akamai commented on packages/manager/src/queries/preferences.ts
> +  >((data) => updateUserPreferences({ ...(preferences ?? {}), data }), {
Oops, I think I messed you up here. The data value should be spread.

```suggestion
  >((data) => updateUserPreferences({ ...(preferences ?? {}), ...data }), {
```

2023-02-24 15:37 UTC, bnussman-akamai approved these changes
Massive improvement to our codebase. This does a really nice job cleaning up our index and App level files. 🎉

2023-02-24 15:37 UTC, bnussman-akamai commented on packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
> +      updatePreferences(parsed as any)
Type is already `any` so can just remove the cast

```suggestion
      updatePreferences(parsed)
```

2023-02-24 15:50 UTC, bnussman-akamai commented on packages/manager/src/queries/preferences.ts
> +      ...newData,
This just occurred to me, but do you think a deep merge is needed/desirable here? From my testing, this is working fine so I don't think we need to make a change. Just a thought.

2023-02-24 16:17 UTC, hkhalil-akamai commented on packages/manager/src/App.tsx
> +  PreferencesStateProps &
App doesn't use preferences

2023-02-24 17:00 UTC, hkhalil-akamai commented on packages/manager/src/queries/preferences.ts
> +      ...newData,
This is just to make sure `updatePreferenceData` is consistent with `useMutatePreferences` now with the the `replace` flag.

2023-02-24 20:28 UTC, jaalah-akamai approved these changes

2023-02-27 18:01 UTC, jdamore-linode approved these changes

2023-02-28 17:22 UTC, merged