feat: [M3-6147] - Add warning for invalid user data
linode/manager pull request #8819
Opened 2023-02-23 22:49 UTC by hkhalil-akamai

## Description 📝

The User Data of a linode will generally be used by a something like cloud-init to initialize a VM. There is an extremely broad set of valid configuration formats ([described here](https://cloudinit.readthedocs.io/en/latest/explanation/format.html)). Custom formats are also possible if the user image uses something besides cloud-init.

To helpfully guide Metadata users, this feature uses basic string matching to determine if User Data does not match one of the most common formats and displays a warning to the user. The user is able to ignore the warning and proceed anyways if they wish.

*Note: Since I built this branch off [M3-6143](https://github.com/Hana-Linode/manager/tree/M3-6143-add-user-data-linode-create), this PR currently includes extra commits until that branch is reviewed and merged.*

## Preview 📷

https://user-images.githubusercontent.com/122488130/221046661-b82c03d1-60c1-4db6-80b0-23e647deb719.mov

## How to test 🧪

[For now, you must be using the dev API.]

1. In the Create Linode flow, select an image that is cloud-init compatible. This will enable the Cloud Data dropdown.
2. In the Cloud Data, verify entering a User Data script that doesn't match a common cloud-config format causes the warning to appear.
3. Verify correcting the format causes the warning to disappear.

2023-02-23 22:50 UTC, hkhalil-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +      !userDataLower.startsWith('#!')
Matches YAML and bash user data formats

2023-02-25 04:13 UTC, jaalah-akamai requested changes

2023-02-25 04:13 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +  const checkFormat = (userData: string, isOnChange: boolean) => {
Two nits for readability: 
- `isOnChange` suggests that the function is being called when the value of an input field changes. Since that's not the case, a more meaningful name could be `isInputValueChanged` or `hasInputValueChanged`.
- This may not be a big deal since there's not a lot of parameters. But it's hard to know what `true` and `false` do at a glance if let's say `checkFormat` was in some util or something. One option would be to deconstruct this so the function call would be `checkFormat({ userData: e.target.value, hasInputValueChanged: true });`

2023-02-25 04:21 UTC, jaalah-akamai requested changes

2023-02-25 04:21 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +      !userDataLower.startsWith('#!')
We could remove some of the redundant checks by moving the strings into an array called `validPrefixes` and then using the `some` method to check if any of the prefixes match the start of the string.
```
const isUserDataValid = validPrefixes.some((prefix) =>
  userDataLower.startsWith(prefix)
);
```
Then we can just use the `!isUserDataValid && !hasInputValueChanged` variables in the if/else statement to toggle only the state.

2023-02-25 04:22 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +      !userDataLower.startsWith('#!')
Guess Github wants to duplicate things... 😮‍💨

2023-02-27 16:16 UTC, mjac0bs commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +        <Notice warning important>
What do you think about adding a little spacing between the bottom of the `TextField` and top of the warning `Notice`, or getting some feedback from UX on their thoughts? 

**Now**:
![Screen Shot 2023-02-27 at 7 49 35 AM](https://user-images.githubusercontent.com/114685994/221616040-bcdaa01a-fe8e-46ff-b7af-b84a9a4a1976.jpg)


**With some margin** (this was a top margin of 24 to match default bottom margin styling for `Notice`, but may be too much space):

```suggestion
        <Notice warning important spacingTop={24}>
```
![Screen Shot 2023-02-27 at 7 59 51 AM](https://user-images.githubusercontent.com/114685994/221616062-2676a2fa-8aa5-433c-8e8a-5a8662ae3dc2.jpg)

2023-02-28 16:27 UTC, hana-linode requested changes

2023-02-28 16:27 UTC, hana-linode commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +        <Notice warning important>
I don't think we need to make this warning important, a regular warning notice should suffice

2023-02-28 18:09 UTC, hkhalil-akamai commented
Blocked pending UX consideration.

2023-03-01 23:14 UTC, jaalah-akamai approved these changes

2023-03-01 23:15 UTC, jaalah-akamai commented
Nice work @hkhalil-akamai 🚀

2023-03-02 05:24 UTC, mjac0bs approved these changes
Functionality looks good. Warning spacing and placement on top of the text field definitely feel more standard; thanks for getting the feedback and making the change.  🚀

2023-03-02 14:55 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +          This user data may not be in a format accepted by cloud-init.
Is this warning message final?  I think it is too vague and could be frustrating to users. The warning says that something is wrong but It doesn't say what or instructions on how to correct it.

2023-03-02 15:46 UTC, hkhalil-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +          This user data may not be in a format accepted by cloud-init.
There is a link to the cloud-init format docs that was originally in this message but was moved to the helper text above it.

2023-03-02 15:56 UTC, merged