refactor: [M3 5800] - Improve notification event links
linode/manager pull request #8828
Opened 2023-02-27 23:20 UTC by mjac0bs

## Description 📝

**What does this PR do?**
TODO

- Apply hover state on every event type
- Remove hyperlinks from event row itself
- Add hyperlinks to entity names 

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**
TODO

## How to test 🧪
TODO

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2023-03-03 20:14 UTC, hana-linode requested changes
On the events landing page, it's not immediately obvious that the entity names are clickable, can we make them blue here as well?

![image](https://user-images.githubusercontent.com/115299789/222817227-5ec8d5fd-5c62-43cc-9f30-3ddffcb04f09.png)

Now that we're making the entity linkable and blue, the event row in the notification menu looks cluttered with the bolding, non-bolding, and blue all in one sentence. Thoughts on removing some of the bolding to make the UI look cleaner?

![image](https://user-images.githubusercontent.com/115299789/222818360-e6598eaf-2e63-410e-8e7d-b86e15ef9f36.png)

2023-03-03 20:59 UTC, mjac0bs commented
@hana-linode Good callouts on both accounts. I'll have a look at applying styling to the events on event landing and will get some UX feedback next week on options for removing bolding or otherwise adjusting styling in the notification menu events.

2023-03-07 21:06 UTC, mjac0bs commented
@hana-linode How do these styling changes look to you?

Events landing:
![Screen Shot 2023-03-07 at 1 04 20 PM](https://user-images.githubusercontent.com/114685994/223552356-05df13de-bd48-4ed7-932f-dc4507468e84.jpg)

Notification menu:
![Screen Shot 2023-03-07 at 1 04 42 PM](https://user-images.githubusercontent.com/114685994/223552378-ca1bd569-e77b-4228-b030-6b90dbb53db7.jpg)

2023-03-08 16:35 UTC, hana-linode reviewed
Changes look a lot cleaner! Can we also add entity linking for Firewalls?

![image](https://user-images.githubusercontent.com/115299789/223773392-b5446d34-7e84-4556-9585-58711b56ffaa.png)

2023-03-08 19:54 UTC, hana-linode approved these changes
🧽 🧹

2023-03-08 22:00 UTC, merged