refactor: [M3-5194] - RQify Types endpoints
linode/manager pull request #8840
Opened 2023-03-03 23:27 UTC by hkhalil-akamai

## Description 📝

**What does this PR do?**

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

2023-03-08 23:23 UTC, hkhalil-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
> +    withTypes(component, { enabled: props.open })(props),
TODO: is this the right way to accomplish this?

2023-03-08 23:25 UTC, hkhalil-akamai commented on packages/manager/src/containers/types.container.ts
> +  setRequestedTypes: (types: string[]) => void;
TODO: discuss this pattern in cafe

2023-03-09 17:10 UTC, jaalah-akamai requested changes

2023-03-09 17:10 UTC, jaalah-akamai commented on packages/manager/src/utilities/cleanArray.ts
> +  array.filter((el) => !isNil(el)) as T[];
Let's do this in javascript without ramda, we want to eventually get rid of that library:
`el !== null && el !== undefined`

2023-03-09 17:10 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/index.tsx
> +    cleanArray(Object.values(linodes.itemsById).map((linode) => linode.type))
Curious if the team wants to adopt this approach to cleaning the array, may not be necessary.

2023-03-10 16:23 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/index.tsx
> +    cleanArray(Object.values(linodes.itemsById).map((linode) => linode.type))
I'm okay with not cleaning the array if it doesn't break anything.

2023-03-10 16:28 UTC, bnussman-akamai commented on packages/manager/src/queries/types.ts
> +    [queryKey, options ?? {}],
React Query relation options should not be in the query key.

2023-03-10 16:28 UTC, bnussman-akamai commented on packages/manager/src/queries/types.ts
> +export const extendType = (type: LinodeType): ExtendedType => {
This may add complexity to the PR, but would it be possible for us to not "extend" the types data at the React Query level? I think it makes more sense to do the "extending" at the component level.

2023-03-10 16:54 UTC, jaalah-akamai commented on packages/manager/src/queries/types.ts
> +export const extendType = (type: LinodeType): ExtendedType => {
Agreed - for clarity... the reason for this is that this can produce unintended consequences for other parts that will rely on this as the app grows and changes. We just want to do this in a more controlled way at the component level.

2023-03-10 21:15 UTC, dwiley-akamai reviewed
I still have a lot of code to sift through and testing to do, but I left a few comments for what I took a look at so far.

With regards to the question about shadow plans out in the wild, I'm going to reach out offline about how we might be able to check that.

2023-03-10 21:15 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
> +    withTypes(component, { enabled: props.open })(props),
the general approach seems correct to me, I will circle back to this though

2023-03-10 23:21 UTC, hkhalil-akamai commented on packages/manager/src/features/linodes/index.tsx
> +    cleanArray(Object.values(linodes.itemsById).map((linode) => linode.type))
The problem here is that the `linode.type` property is of type `string | null`. Without `cleanArray`, we would have to change the signature of `useSpecificTypes` to accept null IDs.

2023-03-10 23:26 UTC, hkhalil-akamai commented on packages/manager/src/queries/types.ts
> +const getSingleType = async (type: string, queryClient: QueryClient) => {
Actually this touches on a larger refactoring I wanted to bring up. Currently we're using a single global instance of `queryClient` but I think the recommended pattern is to use the `useQueryClient` hook to get the query client instance from context. This would allow use to use multiple distinct query client instances in our app if we needed to, or allow us to write unit tests with a custom query client.

2023-03-10 23:27 UTC, hkhalil-akamai commented on packages/manager/src/queries/types.ts
> +const getSingleType = async (type: string, queryClient: QueryClient) => {
But if the team feels like we should continue our current pattern, I can make the requested change.

2023-03-11 01:53 UTC, hkhalil-akamai commented on packages/manager/src/queries/types.ts
> +export const extendType = (type: LinodeType): ExtendedType => {
This raises an interesting formatting consideration... the API returns plan labels like 'Linode 1GB' (w/o a space between 1 and 'GB'), whereas the `extendLinode` function adds a space to make it 'Linode 1 GB'. I've changed `extendLinode` to match the API for consistency but I think it's worth discussing which direction we want to go.

2023-03-13 15:56 UTC, hkhalil-akamai commented on packages/manager/src/queries/types.ts
> +export const extendType = (type: LinodeType): ExtendedType => {
Moved to `src/utilities/extendType.ts`

2023-03-13 17:23 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/index.tsx
> +    cleanArray(Object.values(linodes.itemsById).map((linode) => linode.type))
What do we think about having the `useSpecificTypes` hook filter for null or undefined which would simplify the usage of the hook? 

In other area's where we're directly calling `cleanArray`, I suppose I'm ok with... although I think this would achieve the same result:
```
const types = typesQuery
  .map((result) => result.data)
  .filter(isNotNullOrUndefined)
  .map(extendType);
```

2023-03-14 16:41 UTC, jaalah-akamai approved these changes
Nice, thanks for making the changes

2023-03-14 17:13 UTC, bnussman-akamai reviewed
As much as I'm against the "fetch all" approach, I think it would be nice if we could do that for types. Is the only reason we are not doing that because of the shadow plans?

2023-03-14 17:13 UTC, bnussman-akamai commented on packages/manager/src/App.tsx
> +    withTypes(component, false)
In my opinion I don't think it's worth blocking the app from rendering just because types has an error

```suggestion
```

2023-03-14 18:28 UTC, hkhalil-akamai commented on packages/manager/src/App.tsx
> +    withTypes(component, false)
Just to be clear, you think L223 should be deleted as well?

2023-03-14 19:34 UTC, bnussman-akamai commented on packages/manager/src/App.tsx
> +    withTypes(component, false)
Hmm, honestly yeah. Now that I'm looking at it, a lot of this logic in `App.tsx` is broken anyway. For example, `volumesErrors` and `bucketsError` are not a thing anymore now that those have been React Queryified

2023-03-14 20:33 UTC, bnussman-akamai approved these changes
Nice work, there are a lot of conflicts now somehow :0

2023-03-14 20:51 UTC, hkhalil-akamai commented
Tested and confirmed working with an "shadow-plan" Linode instance.

2023-03-15 18:14 UTC, dwiley-akamai reviewed
Still doing a final look-through of the code but the functionality is looking good to me so far.

One thing I did notice is that it seems we've had a regression on the Linodes landing page compared to prod, losing a space between the number and "GB" for the plan type:

![Screenshot 2023-03-15 at 2 13 48 PM](https://user-images.githubusercontent.com/114682940/225404425-35a71f27-1854-45b9-867b-a47646b37c0c.jpg)

2023-03-16 16:28 UTC, dwiley-akamai reviewed
I see that `{size}GB` regression in the Service Transfers table as well:

![Screenshot 2023-03-16 at 11 20 50 AM](https://user-images.githubusercontent.com/114682940/225664053-eefc4899-41de-47d4-9e24-a5aa4bd16686.jpg)

2023-03-16 16:28 UTC, dwiley-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +    if (prevProps.linodesWithoutBackups !== this.props.linodesWithoutBackups) {
Since `linodesWithoutBackups` is an array, do we need to do a deep equality check here?

2023-03-16 16:28 UTC, dwiley-akamai commented on packages/manager/src/features/Search/SearchLanding.tsx
> +    .map(extendType);
We repeat this `.map().filter().map()` in many different files. Could we abstract it out into a utility function?

2023-03-22 21:27 UTC, dwiley-akamai approved these changes
LGTM, great work! Thanks for addressing the feedback 🚀

2023-03-22 22:51 UTC, merged