M3-6146: Add User Data to Linode Rebuild flow
linode/manager pull request #8850
Opened 2023-03-07 17:08 UTC by dwiley-akamai

## Description 📝
Adds User Data section to the Linode Rebuild flow when an image with `cloud-init` capability is selected.

## Preview 📷
![Screenshot 2023-03-07 at 11 33 22 AM](https://user-images.githubusercontent.com/114682940/223487141-234304c0-911c-4a2c-ae13-f70efe967406.jpg)

## To-Do
- [ ] Add unit tests

## How to test 🧪
- Ensure that the existing User Data work elsewhere in the app has not been adversely impacted by changes made on this branch
- Confirm that Linode rebuild requests go through with the `{ metadata: { user_data: [encoded string ...] } }` property (or `null` instead of encoded string when the Reuse checkbox is marked)

2023-03-07 17:09 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +    marginBottom: '0px !important',
not ideal, open to styling tweaks that would circumvent the need for these `!important`'s

2023-03-07 21:07 UTC, hana-linode requested changes
Can we make the spacing between Add User Data and SSH Keys the same?

![image](https://user-images.githubusercontent.com/115299789/223550239-ad0c73a4-20bb-4668-b397-9a987397d5cd.png)

2023-03-07 21:07 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +      },
We only want to add metadata to the request if the user enters User Data or clicks on the reuse button (and only then do we send null). Right now, if we rebuild without touching the User Data input, we send null.

2023-03-07 21:07 UTC, hana-linode commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +  flowSource?: 'rebuild' | null;
Thoughts on adding a `renderCopy`, `renderNotice`, `renderAction` prop instead of `flowSource` to make this component more generic?

2023-03-08 15:26 UTC, jaalah-akamai requested changes

2023-03-08 15:26 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +    marginBottom: '0px !important',
I would keep this as a normal `div` in the JSX with no styles attached to it. Then allow `Notice` to accept an `sx` prop where you pass the `padding` and `marginBottom` down to it. You won't need the important tags and there will be no need to reference the `.notice` class which we need to avoid doing from now on as we refactor.

2023-03-08 15:26 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +          : { padding: '0px 24px 24px 24px' },
You can simplify this by doing something like:
```
const sxDetails = {
    padding: `0px 24px 24px ${renderNotice ? 0 : 24}px`,
  }
```

2023-03-08 17:05 UTC, dwiley-akamai commented
> I would keep this as a normal div in the JSX with no styles attached to it. Then allow Notice to accept an sx prop where you pass the padding and marginBottom down to it. You won't need the important tags and there will be no need to reference the .notice class which we need to avoid doing from now on as we refactor.

`<Notice />` is built largely with `<Grid />`, which is a custom implementation to mimic MUIv4's grid behavior, and `src/components/core/Grid.tsx` returns a `<div>`. If I'm understanding correctly, the `sx` prop in `Notice.tsx` would be applied to the top-level `<Grid />` instance. Is the `sx` prop approach still viable here @jaalah-akamai (since we're not using the MUIv5 Grid)?

2023-03-08 22:20 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +});
As we introduce `styled()` components into the codebase, my position is that we ought to position them at the end of our files. There will be many times where multiple styled components are used in a single component, and the beginning of the file can get cluttered, disrupting the visually logical flow of imports --> Props interfaces/types --> component --> utility functions at the end. That flow at the top gives you the high-level view of the lay of the land that you need to jump into a component, understand it, and start making logic changes you may have to make.

I added this as a topic for our Cafe so we can decide on a convention.

If we decide to go with this, I'll move `StyledHelpIcon` in `UserDataAccordion.tsx` down in that file as well.

2023-03-08 22:27 UTC, jaalah-akamai approved these changes

2023-03-09 00:34 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +                          checked={reuseUserData}
Can we use a more descriptive variable name for `reuseUserData`? Maybe something like `shouldReuseUserData`? reuseUserData sounds more like a function name to me.

Also what makes us need to use state here over the formik form?

```suggestion
                          checked={reuseUserData}
```

2023-03-09 17:45 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +                          checked={reuseUserData}
With regards to the state for `checked`, since we wouldn't want to submit `shouldReuseUserData` as part of the payload, I think we're in a similar position here as we were in for `AccessKeyDrawer.tsx`

2023-03-09 21:13 UTC, hana-linode requested changes

2023-03-09 21:13 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +
Sorry, looks like I misunderstood the rebuild endpoint 😅 
1. By default, if no user data has been added/user hasn't clicked on the re-use checkbox, we should send user_data as null to the rebuild endpoint
2. If the user checks the reuse checkbox, then we should not send any metadata/user data
3. If metadata/user data is given, we send user_data encoded in base64

2023-03-10 16:17 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +
This should be good to go now 🚀

2023-03-10 16:47 UTC, cpathipa reviewed
Overall, it looks great. I only have a few comments left related to the naming of JSX elements.

2023-03-10 18:38 UTC, cpathipa commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +);
```suggestion
const AcceptedFormatsCopy = () =>  (
  <Typography>
    <br /> Accepted formats are YAML and bash.{' '}
    <Link to="https://www.linode.com/docs">Learn more.</Link>
  </Typography>
);
```

2023-03-10 18:38 UTC, cpathipa commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +);
```suggestion
const UserDataExplanatoryCopy = () => (
  <Typography>
    <Link to="https://cloudinit.readthedocs.io/en/latest/reference/examples.html">
      User Data
    </Link>{' '}
    is part of a virtual machine&rsquo;s cloud-init metadata that contains
    anything related to a user&rsquo;s local account, including username and
    user group(s).
  </Typography>
);
```

2023-03-10 18:38 UTC, cpathipa commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +        userDataExplanatoryCopy
```suggestion
        <UserDataExplanatoryCopy />
```

2023-03-10 18:38 UTC, cpathipa commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +      {acceptedFormatsCopy}
```suggestion
      <AcceptedFormatsCopy />
```

2023-03-10 18:57 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
> +
We wouldn't be able to use `useMemo` in this spot since it's currently within a callback, and I don't think we're experiencing a performance hit here so a refactor to be able to use `useMemo` seems like an over-optimization to me

2023-03-10 19:05 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/UserDataAccordion.tsx
> +);
Our current precedent in the codebase seems to point away from doing this so I'll keep the casing as-is for now, but it can be a Cafe item if we want to revisit it

2023-03-10 20:04 UTC, hana-linode approved these changes
🚀

2023-03-10 20:27 UTC, cpathipa approved these changes

2023-03-10 21:39 UTC, merged