refactor: [M3-6081] - Use region `label` from `/v4/regions` instead of `dcDisplayNames` constant
linode/manager pull request #8851
Opened 2023-03-07 19:31 UTC by bnussman-akamai

## Description 📝

- Uses the API to derive region names rather than the constant `dcDisplayNames`

## How to test 🧪

- Run e2e tests
- Verify that region names in Cloud Manager match what production shows

2023-03-08 14:16 UTC, jdamore-linode commented
Noticing that one of the `Migrate Linode With Firewall` tests is failing because it's waiting for a request to the regions endpoint that isn't happening. On closer inspection, I haven't been able to observe Cloud making any requests to fetch the regions from the API and instead it appears to be relying entirely on the cached data. Is this expected/is there some specific trigger for Cloud to make that request?

(If you try to reproduce the migrate firewall failure, you may have to enable `esModuleInterop` in the Cypress tsconfig to get tests to run due to the changes to the import in the regions factory)

2023-03-08 21:44 UTC, jaalah-akamai commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +      const region = regions.find((r) => r.id === notification.entity?.id);
I think we could extract this to a little util function, what do you think? We're using it in half a dozen or more places

2023-03-09 00:43 UTC, bnussman-akamai commented on packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
> +      const region = regions.find((r) => r.id === notification.entity?.id);
Because the `region` value is often a value "derived" from the regions query in components, I prefer to keep it in the component. If the team thinks a function would be better we can do that.

2023-03-10 17:00 UTC, hkhalil-akamai requested changes
Overall, this is an excellent and much-needed refactor. I like the deduplication of interfaces and utility functions.

Tested locally and looks good to me.

Left a few minor suggestions/comments.

2023-03-10 17:00 UTC, hkhalil-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
> +  const { data: clusters } = useObjectStorageClusters();
This is minor but since the clusters query is only used if regions are unavailable (which may be very rare), it might make sense to disable this query until it's needed (using the enabled RQ option)

2023-03-10 17:00 UTC, hkhalil-akamai commented on packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
> +        allRegions={regions}
Should `ConfigureForm` call `useRegionsQuery` itself?

2023-03-10 17:00 UTC, hkhalil-akamai commented on packages/manager/src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
> +            closeMenu={() => this.closeMenu}
It also looks like `UserNotificationsMenu` is not used anywhere, should this dir be deleted?

2023-03-10 17:42 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/kubeUtils.ts
> +    cluster.region ?? 'Unknown Region',
Yeah, this is not great but I found that this wasn't an easy function to wire-up to React Query. I will take another look

2023-03-10 17:42 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/kubeUtils.ts
> +    cluster.region ?? 'Unknown Region',
Good catch, I'll make this change.

2023-03-10 17:42 UTC, bnussman-akamai commented on packages/manager/src/features/GlobalNotifications/RegionStatusBanner.tsx
>    regions: Region[];
Good catch. I'll make this change.

2023-03-10 18:46 UTC, bnussman-akamai commented on packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
> +  const { data: clusters } = useObjectStorageClusters();
The clusters query is used to determine the region the object storage cluster is in. I think this is fine because by the time the user renders a `<BucketTableRow />`, `useObjectStorageClusters` would have already fetched anyway

2023-03-10 19:46 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/kubeUtils.ts
> +    cluster.region ?? 'Unknown Region',
I think two options here are
- Pass `regions` down many levels to restore the current behavior
- Just leave this and hope we refactor search soon because it really needs it

Thoughts?

2023-03-10 22:52 UTC, hkhalil-akamai commented on packages/manager/src/features/Kubernetes/kubeUtils.ts
> +    cluster.region ?? 'Unknown Region',
My initial thought is we want to avoid any user-facing regressions here so I would go with #1 even if it's not ideal.

2023-03-10 22:54 UTC, hkhalil-akamai approved these changes
Approved pending [one remaining question](https://github.com/linode/manager/pull/8851#discussion_r1132951920).

2023-03-13 15:24 UTC, bnussman-akamai commented
![Screenshot 2023-03-13 at 11 24 04 AM](https://user-images.githubusercontent.com/115251059/224747507-9a1213e1-841a-41cc-971c-28581ba9b33e.jpg)

2023-03-14 16:45 UTC, jaalah-akamai approved these changes
🚀

2023-03-14 17:03 UTC, cpathipa approved these changes
LGTM! Nice work @bnussman!

2023-03-14 19:20 UTC, merged