refactor: [M3-5945] - Parameterize DBaaS tests for multiple engines
linode/manager pull request #8900
Opened 2023-03-21 18:44 UTC by cliu-akamai

## Description 📝

- Parameterize DBaaS `update` and `delete` tests for multiple engines

## How to test 🧪

**How do I run relevant unit or e2e tests?**
Run the commands: 
`yarn cy:run -s "cypress/e2e/databases/create-database.spec.ts"`
`yarn cy:run -s "cypress/e2e/databases/update-database.spec.ts"`
`yarn cy:run -s "cypress/e2e/databases/delete-database.spec.ts"`

2023-03-22 21:36 UTC, bnussman-akamai commented on packages/manager/cypress/e2e/databases/update-database.spec.ts
> +      it(`creates a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
Should `creates` be `updates` here?

```suggestion
      it(`updates a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
```

2023-03-24 15:31 UTC, jdamore-linode requested changes
Nice work @cliu-akamai!

The only real issues I'm seeing are those `it(...)` calls that should be replaced with `describe(...)`, and I posted a couple other suggestions which aren't crucial, but otherwise this looks good!

2023-03-24 15:31 UTC, jdamore-linode commented on packages/manager/cypress/e2e/databases/database-configuration.ts
Do you think we could rename/move this file to `cypress/support/constants/databases.ts`?

I think we can establish a pattern here where any constants/data needed by multiple specs for a single feature could all be consolidated in `constants/<feature name>.ts`. (I think I did something similar for the LKE PR too)

2023-03-24 15:31 UTC, jdamore-linode commented on packages/manager/cypress/e2e/databases/update-database.spec.ts
> +      it(`creates a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
```suggestion
      describe(`updates a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
```
In addition to Banks's suggestion, we'll also want to replace `it(...)` with `describe(...)` here since there are multiple tests defined in this block with their own `it(...)` statements.

2023-03-24 15:31 UTC, jdamore-linode commented on packages/manager/cypress/e2e/databases/delete-database.spec.ts
> +      it(`Deletes a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
Similar to the previous comment, we just want to swap `it(...)` out with `describe(...)` here!

```suggestion
      describe(`Deletes a ${configuration.linodeType} ${configuration.engine} v${configuration.version}.x ${configuration.clusterSize}-node cluster at ${configuration.region}`, () => {
```

2023-03-24 15:31 UTC, jdamore-linode commented on packages/manager/cypress/e2e/databases/database-configuration.ts
> +import { randomIp, randomLabel } from 'support/util/random';
Looks like we can get rid of `randomIp` here!

```suggestion
import { randomLabel } from 'support/util/random';
```

2023-03-29 21:18 UTC, cliu-akamai commented on packages/manager/cypress/e2e/databases/database-configuration.ts
Sure!

2023-03-30 15:05 UTC, bnussman-akamai approved these changes

2023-03-31 19:53 UTC, jaalah-akamai approved these changes

2023-04-03 20:23 UTC, jdamore-linode approved these changes
Nice work @cliu-akamai !

2023-04-03 21:51 UTC, merged