fix: [M3-6387] - MUI v5 Migration - Components > SelectionCard & ActionsPanel
linode/manager pull request #8939
Opened 2023-03-29 20:38 UTC by jaalah-akamai

## Description 📝
The parent components for Marketplace selection cards needed to be updated as well with new Gridv2.

## Major Changes 🔄 
- Updated all Grid references that used `SelectionCard`
- Migrated `ActionsPanel` since that was connected to one of the files affected

## Preview 📷
| Before      | After |
| ----------- | ----------- |
|<img width="889" alt="Screen Shot 2023-03-29 at 4 32 55 PM" src="https://user-images.githubusercontent.com/125309814/228661204-76251380-13fd-40d1-baaf-64617a2ef83d.png">|<img width="1918" alt="Screen Shot 2023-03-29 at 4 31 25 PM" src="https://user-images.githubusercontent.com/125309814/228661232-11390ab1-8424-4899-8843-fbc79ead28a0.png">|

<img width="1150" alt="Screen Shot 2023-03-29 at 6 00 39 PM" src="https://user-images.githubusercontent.com/125309814/228677434-6f422ad9-be4c-4693-a212-21560c4704d8.png">

## How to test 🧪
- Compare http://localhost:3000/linodes/create?type=One-Click with Prod
- Ensure "Make a Payment" is still good: http://localhost:3000/account/billing/make-payment
- User Permissions: http://localhost:3000/account/users/{USER}/permissions

2023-03-29 20:40 UTC, jaalah-akamai commented on packages/manager/src/components/SelectionCard/SelectionCard.tsx
> -  outline: 0,
No need for any of these styles anymore, the Grid should handle all this.

2023-03-29 20:40 UTC, jaalah-akamai commented on packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
> +      container
This was the main fix

2023-03-29 20:40 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
> -    },
This style wasn't doing much at all, so I removed.

2023-03-29 20:41 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
> -  },
`flatImagePanelSelections` here was unused

2023-03-29 20:41 UTC, hana-linode requested changes
Looks like the layout is wonky in some other places that use SelectionCard

![image](https://user-images.githubusercontent.com/115299789/228662156-944f2cbe-76a0-4f32-bf29-027662fa1192.png)

Linode Plan mobile view
![image](https://user-images.githubusercontent.com/115299789/228662256-31940eb0-5be9-424d-86e6-7b856f7a8c0c.png)

2023-03-29 22:02 UTC, jaalah-akamai commented
@hana-linode should be working again!

2023-03-29 23:59 UTC, hana-linode requested changes
Just noticed some minor regressions in the Make a Payment drawer, but other than that I think we're good!

This branch:
Chip text being cut off on mobile screens and extra spacing between Pay Now button
![image](https://user-images.githubusercontent.com/115299789/228693955-4fe1ce85-9bc6-4600-bedf-352b74e9b4a7.png)

Prod:
![image](https://user-images.githubusercontent.com/115299789/228694149-668f913c-ba73-4a76-a990-5ec2f2245c06.png)

2023-03-30 11:47 UTC, jaalah-akamai commented
The space between the "Pay Now" button will be addressed in [PR #8933](https://github.com/linode/manager/pull/8933/files#diff-8a21e23fcac02097f86824bdd156bc44d90851c4c159b1503c66cf78316ebaca) with changes to `PaymentDrawer.tsx` where I update the Grid for that file. I'll make sure to check this on that end 👍

2023-03-30 14:22 UTC, hana-linode approved these changes

2023-03-30 14:45 UTC, merged