refactor: [M3-6296] - MUI v5 Migration - `Components > BarPercent`
linode/manager pull request #8962
Opened 2023-04-04 19:58 UTC by dwiley-akamai

## Description 📝
Migrates `SRC > Components > BarPcent` from JSS to tss-react (Emotion)

## How to test 🧪
Confirm that the `BarPercent` component looks as expected throughout the app, including in the Monthly Network Transfer Pool modal and event progress bar in the notifications drawer.

2023-04-04 20:18 UTC, bnussman-akamai approved these changes

2023-04-04 20:18 UTC, bnussman-akamai commented on packages/manager/src/components/BarPercent/BarPercent.tsx
>            narrow,
I wonder what affect this has. narrow is just a `boolean`

2023-04-05 14:01 UTC, jaalah-akamai requested changes

2023-04-05 20:53 UTC, dwiley-akamai commented on packages/manager/src/components/BarPercent/BarPercent.tsx
> +    padding: 8,
The border radius and reduced padding don't seem to be working as intended here 🤔

![Screenshot 2023-04-05 at 4 47 10 PM](https://user-images.githubusercontent.com/114682940/230208880-8a4c48e0-155c-4024-af5b-4c9d395f45c4.jpg)

2023-04-05 21:04 UTC, jaalah-akamai commented on packages/manager/src/components/BarPercent/BarPercent.tsx
> +    padding: 8,
This is because the `rounded` and `narrow` prop need to be passed into your styled component as props

2023-04-06 18:26 UTC, jaalah-akamai approved these changes

2023-04-06 19:44 UTC, merged