refactor: [M3-6343] - MUI v5 Migration - Grid v2 for Features
linode/manager pull request #8985
Opened 2023-04-11 18:16 UTC by jaalah-akamai

TODO:  Updated detailed description coming soon...

## Description 📝

**What does this PR do?**

## Preview 📷

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

**What are the steps to reproduce the issue or verify the changes?**

**How do I run relevant unit or e2e tests?**

## Commit message and pull request title format standards

**Remove this section before opening the pull request**

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**commit types:**  
`feat`: New feature for the user (not a part of the code, or ci, ...).  
`fix`: Bugfix for the user (not a fix to build something, ...).  
`refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.  
`style`: General styling changes. Does not change any functionality.  
`build`: Changes to the application build.  
`chore`: Other changes that do not impact production code.  
`ci`: Changes to the CI pipeline.  
`docs`: Changes to the documentation docs.  
`perf`: Performance changes.  
`test`: New tests or changes to existing tests. Does not change the production code.  
`change`: Only use for something that doesn’t fit in any other category.  

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-04-11 20:52 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx
> -
I could've gone further with this file, but I left it intact for now

2023-04-11 20:53 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
> -          <Grid item className={classes.addNewWrapper}>
No need for all the spacing adjustment from `addNewWrapper` anymore.

2023-04-13 14:28 UTC, bnussman-akamai reviewed
Things generally look good so far, can we decrease the spacing here across all entities, it has gotten larger in this PR

![Screenshot 2023-04-13 at 10 26 12 AM](https://user-images.githubusercontent.com/115251059/231790716-61bc2337-93f1-433a-b8d7-a030cd2d850b.jpg)

2023-04-13 15:02 UTC, jaalah-akamai commented
> Things generally look good so far, can we decrease the spacing here across all entities, it has gotten larger in this PR
> 
> ![Screenshot 2023-04-13 at 10 26 12 AM](https://user-images.githubusercontent.com/115251059/231790716-61bc2337-93f1-433a-b8d7-a030cd2d850b.jpg)

Yea I was going back and forth with that, but yea let's do it!

2023-04-13 19:00 UTC, dwiley-akamai reviewed
I still have a few more places in the app to check and a lot of code to sift through, but it's looking good so far.

One small thing I noticed is that the graphics on the Referrals page are closer together than they were previously, do we want to keep that?

2023-04-13 19:26 UTC, hana-linode requested changes
The TagsPanel is no longer flush to the right side

![image](https://user-images.githubusercontent.com/115299789/231855416-e63e3ae1-8a27-4481-b420-7e296e18802c.png)

Mobile spacing for the firewalls rule table seems a bit tight now
This branch
![image](https://user-images.githubusercontent.com/115299789/231858379-b5c85dca-fc85-4b69-ad2b-3067b3e9dc2e.png)

Prod
![image](https://user-images.githubusercontent.com/115299789/231858276-3605979d-d1c5-4501-a8cc-1046afa8417d.png)

Mobile spacing for Kube display is a bit off/tight
![image](https://user-images.githubusercontent.com/115299789/231860743-07607e5d-107a-427f-8837-c3bf8605dc3d.png)

"Port Configuration" display disappeared
This branch
![image](https://user-images.githubusercontent.com/115299789/231861115-8f0d775e-e5ca-49d6-a9ae-bd88b269d861.png)

Prod
![image](https://user-images.githubusercontent.com/115299789/231861165-73589f70-f41f-4b14-9928-6b45e28363d4.png)

The extra white padding around the accordion header looks less clean imo
This branch
![image](https://user-images.githubusercontent.com/115299789/231861724-fe58b843-1f97-4b74-85ef-f82b852ed586.png)

Prod
![image](https://user-images.githubusercontent.com/115299789/231861798-6f035511-01d9-4321-bd6a-8399595d93f7.png)

2023-04-13 19:32 UTC, bnussman-akamai commented
@hana-linode The removal of `Port Configuration` was done by me in https://github.com/linode/manager/pull/8964, it was intentional

2023-04-13 20:38 UTC, jaalah-akamai commented
Thanks @hana-linode let me know if things are looking better now. I actually improved the alignment of the inbound rules dropdown to always match the action column since I saw that was the intent cc: @mjac0bs 


https://user-images.githubusercontent.com/125309814/231877452-286e8fe0-23fb-47b8-8110-53ddaddb4c02.mp4

![Screen Shot 2023-04-13 at 4 36 33 PM](https://user-images.githubusercontent.com/125309814/231877481-32abf260-d80d-4334-90c1-5b0cbb8c08f5.png)

![Screen Shot 2023-04-13 at 4 38 34 PM](https://user-images.githubusercontent.com/125309814/231877566-9f2dc47a-c234-4245-892c-f01836f5e11d.png)

2023-04-13 20:40 UTC, jaalah-akamai commented
> 3c6f9ab

Hmm fix incoming!

2023-04-13 20:42 UTC, mjac0bs commented
> I actually improved the alignment of the inbound rules dropdown to always match the action column since I saw that was the intent

🥇 @jaalah-akamai Thank you for doing that. I remember it being just slightly off in the accessibility fix and it haunted me a little. Giving the Firewalls page and the rest of this PR a closer look now!

2023-04-13 20:49 UTC, hana-linode commented
Ah I probably should have cropped the image more, but I meant that the mobile spacing between table columns looks a bit tight now

This branch
![image](https://user-images.githubusercontent.com/115299789/231879640-51d90146-c250-4bb6-bdcf-8d9a3bfad6f4.png)

Prod
![image](https://user-images.githubusercontent.com/115299789/231879687-ef6ad6cc-1db9-4ff4-b736-138eada19545.png)

2023-04-13 21:29 UTC, jaalah-akamai commented
@hana-linode gotcha! should be good now, increased spacing slightly for the first item from `30%` to `32%` because we couldn't use margins to create space like we did in prod. I didn't want any words breaking to new lines as things got smaller.

2023-04-13 21:56 UTC, mjac0bs reviewed
I'm still working my way through pages at each breakpoint, but here are a few spacing differences so far:

Firewalls -- This looks better now! I'm happy with the changes here.
~~As @hana-linode pointed out, spacing between columns is tight as we move to smaller screens. This is especially noticeable in columns if a user has a long rule name or list of many IPs.~~ ✅ 
| This branch  | Prod  |  
|---|---|
|  ![Screenshot 2023-04-13 at 2 00 18 PM](https://user-images.githubusercontent.com/114685994/231885647-1b824c7a-135c-41b0-be2a-372afb15b853.jpg) | ![Screenshot 2023-04-13 at 2 00 04 PM](https://user-images.githubusercontent.com/114685994/231885625-03a762e8-d2c5-4c51-a47f-c84a168d1d64.jpg)  |

Linode Landing --  The collapsed tags "..." and the "Add a Tag" button lack some spacing between so they meld into one.
| This branch  | Prod  |  
|---|---|
| ![Screenshot 2023-04-13 at 2 11 05 PM](https://user-images.githubusercontent.com/114685994/231886407-2d4b60e4-58a7-4676-8845-44e563b9da60.jpg)  | ![Screenshot 2023-04-13 at 2 11 11 PM](https://user-images.githubusercontent.com/114685994/231886420-762f87aa-5b45-43e8-b92a-20f3303cfa5d.jpg)  |

StackScripts
- Thank you for fixing Image Select > Target Images! I recently made a ticket for this because I noticed our wandering TooltipIcons. 

Linodes Details > Storage > Add a Disk - in the same ticket I made for the above, I noticed another spot with the misaligned icon. On this branch, it's still looking like it needs some adjustment on the Image field.
| This branch  | Prod  |  
|---|---|
| ![Screenshot 2023-04-13 at 2 50 53 PM](https://user-images.githubusercontent.com/114685994/231891062-220f436f-fea0-49dc-b63b-80928abf409a.jpg) |  ![Screenshot 2023-04-13 at 2 51 21 PM](https://user-images.githubusercontent.com/114685994/231891104-a695f024-be72-42b8-9a58-ce96884ce8bb.jpg) |

Images -- Looks good to me, other than: just noticed this minor styling bug while testing (also in prod) that might be out of scope of this PR, but it would be cool if we could get our TooltipIcon on the Region field in Upload Image to stop having this weird  spacing at the `599` breakpoint. 

https://user-images.githubusercontent.com/114685994/231888206-08ef9bbd-ff5c-466c-a56f-e5716687a7a4.mov

2023-04-14 16:21 UTC, dwiley-akamai approved these changes
LGTM 🚀

2023-04-14 17:06 UTC, mjac0bs reviewed
**Help and Support:**

At a width of `599px` on down, there is some misalignment happening that I think we could fix here (also currently in prod):
![image](https://user-images.githubusercontent.com/114685994/232109369-190a7ee0-bed3-4f01-86df-72effed3a257.png)

**Profile > Login & Authentication:** (https://localhost:3000/profile/auth)
TPA provider options are having some issues now at smaller breakpoints.

Prod:

https://user-images.githubusercontent.com/114685994/232110345-86263e3f-9549-4db8-aeee-2a05586ea3f5.mov

This branch:

https://user-images.githubusercontent.com/114685994/232110321-2597db55-616e-4b1e-8bf7-12067719d4af.mov

**Linode Create:**
|  This branch |  Prod | 
|---|---|
| ![Screenshot 2023-04-14 at 10 35 04 AM](https://user-images.githubusercontent.com/114685994/232118768-529d4e09-3c1f-458b-aff6-6ee9f292f454.jpg) | ![Screenshot 2023-04-14 at 10 34 49 AM](https://user-images.githubusercontent.com/114685994/232118786-fb685b93-a67a-48c1-8b3b-645034893cb5.jpg)

Kubernetes:
I know we recently did some work on this page... the margin on the right seems to small to me and feels better in prod, but I didn't review the other ticket when this was refactored.

|  This branch |  Prod | 
|---|---|
| ![Screenshot 2023-04-14 at 10 29 30 AM](https://user-images.githubusercontent.com/114685994/232119074-27a839d5-5a25-4024-bb0e-8e94d38bcd8f.jpg)
 | ![Screenshot 2023-04-14 at 10 29 37 AM](https://user-images.githubusercontent.com/114685994/232119079-3f664dc1-9f3f-44a7-91b8-527821ef3d18.jpg) |

2023-04-14 18:11 UTC, bnussman-akamai approved these changes
I think this is in a good enough state to proceed! I think any outstanding issues could be resolved in this PR or after this is merged

2023-04-14 18:33 UTC, hana-linode approved these changes
Other than Mariah's comments, this is looking good to me 🚀

2023-04-14 20:08 UTC, jaalah-akamai commented
Here are the updates - thanks everybody!
|||
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/125309814/232144970-f22ca018-3b81-4b4a-b2fe-60703ba36d5f.mp4" />| <video src="https://user-images.githubusercontent.com/125309814/232145051-a719f115-13e0-4280-8655-6010833dbe8c.mp4" />|
| <video src="https://user-images.githubusercontent.com/125309814/232145107-5dcbb717-dcb0-40dd-8c22-e80296ae11bd.mp4" />| <video src="https://user-images.githubusercontent.com/125309814/232145140-5cabc548-a9c8-4c63-b714-8c04508e6bf1.mp4" />|

2023-04-14 20:13 UTC, mjac0bs approved these changes
Thanks for the fixes! 🚀 Can we add this to the Tech Stories section in the changelog?

2023-04-14 20:35 UTC, merged