feat: [M3-6427] - Add No Results section for Marketplace Search
linode/manager pull request #8999
Opened 2023-04-13 15:11 UTC by cpathipa

## Description 📝
Add No Results section for Marketplace Search

## Preview 📷
![image](https://user-images.githubusercontent.com/119517080/231802578-86ab823a-b33a-48a6-9b83-afd791b4f5cb.png)

**Remove this section or include a screenshot or screen recording of the change**

## How to test 🧪

- Navigate to Marketplace search
- Search for app that doesn't exists (ex; datadog)
- Should display "No Results" message. 

**How do I run relevant unit or e2e tests?**

- yarn test
- yarn cy:run

2023-04-13 20:13 UTC, jdamore-linode commented
Nice, it works well!

Would it be possible to center the "No Results" text?

<img width="1351" alt="Screen Shot 2023-04-13 at 4 11 29 PM" src="https://user-images.githubusercontent.com/97627410/231872385-ba542ccf-3995-48f6-8b2f-807fd221e74d.png">

Do we need any other input from the UX team as far as wording and design should go?

2023-04-13 22:14 UTC, mjac0bs reviewed
I'm glad we're doing this! Seconding @jdamore-linode's request to center the text horizontally. And I'm wondering about the overall placement within that container. 

Mock (assume actual center alignment):
![Screenshot 2023-04-13 at 3 09 00 PM](https://user-images.githubusercontent.com/114685994/231894758-cd147aef-f33e-445f-878f-f8a831343ed7.jpg)

2023-04-14 18:57 UTC, cpathipa commented
Thank you @jdamore-linode and @mjac0bs thank you for the feedback, I will circle back with UX on this.

2023-04-14 21:49 UTC, dwiley-akamai reviewed
I also agree with checking on the centered-within-container option

2023-04-17 17:14 UTC, cpathipa commented
Thank you for the feedback. Based on the UX feedback, updated the no results copy and adjusted alignment to center. 
![image](https://user-images.githubusercontent.com/119517080/232560166-728e0e87-7239-40e7-b9a2-cb45d48a9a64.png)

2023-04-17 18:53 UTC, hana-linode reviewed
Thoughts on left aligning the no results section? The selection cards are left aligned as well as the "no compatible images" text below

![image](https://user-images.githubusercontent.com/115299789/232583293-ebc50f94-d4d6-4003-b5d9-4e2487917945.png)

2023-04-17 18:59 UTC, mjac0bs commented
Nitpicks on copy: I'm wondering if clearer copy might read: "Sorry, no results matched your search for "datadog". Please try another term."

Thought process being:
1. "no <search term> results" sounds kind of strange and is slightly harder to scan as a reader than "no results"
2. telling the user to "please try again" feels misleading because if the user were to try the same action again, the results would be the same. It feels more clear to state what they should actually try to yield different results.

What do others (and UX) think?

2023-04-17 19:31 UTC, hana-linode commented
@mjac0bs Agreed that "Sorry, no results matched your search for "datadog" sounds clearer. I don't think we even need the second sentence as it's pretty obvious that the user should search for a different term

2023-04-18 16:56 UTC, jaalah-akamai requested changes

2023-04-18 16:56 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
> +        )}
I think we can simplify the JSX a little here by doing:
```
{apps.length > 0 ? (
  <AppPanelGrid container spacing={2}>
    {apps.map((eachApp) => { ... })}
  </AppPanelGrid>
) : (
  <Typography>
    {`Sorry, no results matching "${searchValue}" were found.`}
  </Typography>
)}
```
We won't need the extra Grid in this case

2023-04-18 17:21 UTC, jaalah-akamai commented
Let's remember to update changelog too 👍

2023-04-18 22:57 UTC, jaalah-akamai approved these changes

2023-04-19 14:21 UTC, mjac0bs approved these changes
Just a changelog update and this looks like it's good to go.

2023-04-19 16:00 UTC, merged