fix: [M3-6480] - Fix blank Node Pool plan selection
linode/manager pull request #9009
Opened 2023-04-17 17:40 UTC by hkhalil-akamai

## Description 📝

Fixes a bug introduced in #8840 that causes the AddNodePool drawer to not show any plans in certain situations.

Also included are basic unit tests that validate the fix and small amendments to the recent `useQueryClient` PR.

## Preview 📷

| Before      | After |
| ----------- | ----------- |
|![Screenshot 2023-04-17 at 1 30 24 PM](https://user-images.githubusercontent.com/122488130/232564232-18e6a2a3-d6bd-465d-bb98-297c8e8a5cc0.jpg)|![Screenshot 2023-04-17 at 1 30 07 PM](https://user-images.githubusercontent.com/122488130/232564301-475d8176-4cf7-45d0-8180-7f2d7acb4e3c.jpg)|

## How to test 🧪

1. Under Kubernetes, navigate to an existing cluster or create a new one.
2. Refresh the page to clean the RQ store.
3. Click on 'Add A Node Pool'.
4. Verify the `AddNodePoolDrawer` appears and displays all plan types and details.

2023-04-17 17:56 UTC, hkhalil-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
> +    new Map()
Decided to use a `Map` here instead of an index signature object because those can lead to runtime errors without [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) enabled:

```
const map1: { [key: string]: number } = {"type1": 0};
const type2Count: number = map1["type2"]; # no type error
```

vs with `Map`:

```
const map1: Map<string, number> = new Map([[ "type1", 0 ]]);
const type2Count: number = map1.get("type2"); # type error: number | undefined is not assignable to number.
```

2023-04-17 21:17 UTC, bnussman-akamai requested changes

2023-04-17 21:17 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
> +    setSelectedTypeInfo({ planId, count: newCount });
Would doing this allow us to get rid of the `useEffect` that runs `setSelectedTypeInfo(undefined)`

```suggestion
    if (newCount === 0) {
      setSelectedTypeInfo(undefined);
    } else {
      setSelectedTypeInfo({ planId, count: newCount });
    }
```

2023-04-18 13:31 UTC, bnussman-akamai approved these changes
I did not notice any regressions, thank you for for the fix!

2023-04-19 19:57 UTC, merged