test: [M3-6248] - Add Cypress Firewall e2e Update tests
linode/manager pull request #9017
Opened 2023-04-17 22:44 UTC by cliu-akamai

## Description 📝

Add Cypress end-to-end tests which confirm the expected behavior of Cloud Manager Firewall features.

Test cases:
- Linodes can be added and removed from a firewall
- Inbound rules can be added and removed from a firewall
- Outbound rules can be added and removed from a firewall
- Firewalls can be enabled and disabled, and their status is reflected on the landing page (/firewalls)

## How to test 🧪

`yarn cy:run -s "cypress/e2e/firewalls/update-firewall.spec.ts"`

2023-04-18 15:51 UTC, jdamore-linode requested changes
Nice work @cliu-akamai! Left a couple notes but the only one that I think is really worth holding up the merge is the `cy.findByText('No rules')` call that wasn't `within(...)` the table row on the landing page

2023-04-18 15:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/firewalls/update-firewall.spec.ts
> +    });
```suggestion
  ui.drawer
    .findByTitle(`Add Linode to Firewall: ${firewall.label}`)
    .should('be.visible')
    .within(() => {
      // Fill out and submit firewall edit form.
      cy.get('[data-testid="textfield-input"]:last')
        .should('be.visible')
        .click()
        .type(linode.label);
        
      ui.autocompletePopper
        .findByTitle(linode.label)
        .should('be.visible')
        .click();
          
      ui.button.findByText('Add').click();
    });
```

I think we can simplify this so that it's all inside one `within(() => { ... })` block, since the `autocompletePopper` UI helper breaks out of the `within(() => { ... })` context.

2023-04-18 16:08 UTC, hkhalil-akamai commented
Overall this looks good to me; I wonder if we also want to test modifying the default inbound/outbound policy:
![Screenshot 2023-04-18 at 12 05 25 PM](https://user-images.githubusercontent.com/122488130/232837541-b144046f-c2e0-46a3-9897-84878c61c055.jpg)

2023-04-18 17:19 UTC, cliu-akamai commented on packages/manager/cypress/support/ui/buttons.ts
> +  findByText: (buttonText: string): Cypress.Chainable => {
I don't know why, the `findByTitle()` helper won't work for these buttons.
![image](https://user-images.githubusercontent.com/126020611/232854673-175dc1b9-b429-43e2-9915-38eb17a5ff9a.png)

2023-04-18 17:32 UTC, jdamore-linode commented on packages/manager/cypress/support/ui/buttons.ts
> +  findByText: (buttonText: string): Cypress.Chainable => {
Oh these were tricky -- it looks like we have a CSS `text-transform: capitalize` style on these, but the actual text for the buttons is `Add an Inbound Rule`/`Add an Outbound Rule` (`an` instead of `An`), and `Add Linodes to Firewall` (`to` instead of `To`). I think if you were to use `ui.button.findByTitle("Add an Inbound Rule")`, `ui.button.findByTitle("Add an Outbound Rule")`, and `ui.button.findByTitle("Add Linodes to Firewall")` it would probably work!

2023-04-19 18:16 UTC, jdamore-linode commented on packages/manager/cypress/e2e/firewalls/update-firewall.spec.ts
> +      cy.visitWithLogin('/firewalls');
Oh great point! In that case you'll want to write an intercept utility that matches that API request if we don't have one already (I don't think we do), and then wait for that request to be intercepted. That would look something like this:

```typescript
// Call the new intercept util sometime before updating the firewall, assign it an alias.
interceptUpdateFirewall(firewall.id).as('updateFirewall');

// Update firewall, save changes, etc
// ...
ui.button.findByText('Save Changes').click();

// Wait for the HTTP request to resolve using the alias we assigned via `as()` above.
cy.wait('@updateFirewall');

// Continue with the test, navigate wherever, etc.
// ...
```

At the end of the day this accomplishes the same thing was `cy.wait(200)` would, but it ensures that the tests wait long enough to proceed without waiting any longer than necessary.

2023-04-19 18:35 UTC, jdamore-linode commented
> Is there a way to verify the modification? I don't see any column in the landing page shows the default action.

@hkhalil-akamai Great catch!

@cliu-akamai I think the best approach here would be to check if the API response upon clicking "Save Changes" matches the policies selected by the user/Cypress -- this would require intercepting the request just like [I described here](https://github.com/linode/manager/pull/9017#discussion_r1171704712), and inspecting the response. It would look something like this:

```typescript
// Assume the intercept is set up like described in the comment above:
// https://github.com/linode/manager/pull/9017#discussion_r1171704712

// User updates the firewall, clicks Save Changes, etc...
ui.button.findByText('Save Changes').click();

// Wait for API request to resolve and inspect response.
// (Simplified example, feel free to modify assertions however needed.)
cy.wait('@updateFirewall').then(({ response }) => {
  expect(response?.body?.inbound_policy).to.eql('DROP');
  expect(response?.body?.outbound_policy).to.eql('ACCEPT');
});

// Continue with the test here...
```

We do similar things in a few other tests if you'd like to see some real examples:
- [`account/billing-contact.spec.ts`](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/account/billing-contact.spec.ts#L136-L138)
- [`kubernetes/lke-create.spec.ts`](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/kubernetes/lke-create.spec.ts#L152-L160)
- [`helpAndSupport/open-support-ticket.spec.ts`](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/helpAndSupport/open-support-ticket.spec.ts#L24-L84)

2023-04-19 18:55 UTC, jdamore-linode approved these changes
Great work @cliu-akamai !

2023-04-19 21:18 UTC, jaalah-akamai approved these changes
Thanks @cliu-akamai and @jdamore-linode this is working great

2023-04-21 20:39 UTC, jdamore-linode commented on packages/manager/cypress/support/intercepts/firewalls.ts
> +  return cy.intercept('PUT', apiMatcher(`firewalls/${firewallId}/rules`));
```suggestion
  return cy.intercept('POST', apiMatcher('networking/firewalls'));
};

/**
 * Intercepts PUT request to update a Firewall.
 *
 * @param firewallId the ID of the Firewall to update
 * @returns Cypress chainable.
 */
export const interceptUpdateFirewall = (
  firewallId: string
): Cypress.Chainable<null> => {
  // return cy.intercept('PUT', apiMatcher('firewalls'));
  return cy.intercept('PUT', apiMatcher(`networking/firewalls/${firewallId}/rules`));
```
Sorry for not catching this sooner! I think all of our [Firewall API endpoints](https://www.linode.com/docs/api/networking/) are prefixed with `networking/` so we'll probably want that included here.

2023-04-21 21:23 UTC, merged