refactor: [M3-6320] - MUI v5 Migration - Components > DialogTitle
linode/manager pull request #9050
Opened 2023-04-24 20:55 UTC by jaalah-akamai

## Description 📝
Refactors `src/components/DialogTitle/DialogTitle.tsx` to remove JSS

> **Note**: The close button aspect of this component is not actually used anymore. I figured that I would keep it in for the time being.

## Major Changes 🔄
- Updated references for named export

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![Screen Shot 2023-04-24 at 11 28 54 AM](https://user-images.githubusercontent.com/125309814/234044332-188a3214-8f02-4207-ab76-96b01f5ef6ee.png) | ![Screen Shot 2023-04-24 at 11 29 07 AM](https://user-images.githubusercontent.com/125309814/234044363-7ec8bd3e-25ed-4210-9511-12d3ebe9003f.png) |

## How to test 🧪
1. `yarn dev`
2. Go to http://localhost:3000/linodes
3. Attempt to delete any linode and observe no differences
4. N/A

2023-04-24 21:45 UTC, bnussman-akamai reviewed
Should `Dialog.tsx` be using this instead of its own StyledDialogHeader?

2023-04-25 17:39 UTC, mjac0bs reviewed
Since our Standard Dialog has a close button, I would be for adding it on our Confirmation/Deletion dialogs too as you've done here. Lack of contrast in dark mode does make the "X" really difficult to see, though. Could we make that more accessible? 

![image](https://user-images.githubusercontent.com/114685994/234357218-0b30646c-fbf6-44fc-92b6-3265170c4e18.png)

2023-04-25 17:39 UTC, mjac0bs commented on packages/manager/src/components/DialogTitle/DialogTitle.tsx
> +interface DiaglogTitleProps {
```suggestion
interface DialogTitleProps {
```

2023-04-25 17:39 UTC, mjac0bs commented on packages/manager/src/components/DialogTitle/DialogTitle.tsx
> +const DialogTitle = (props: DiaglogTitleProps) => {
```suggestion
const DialogTitle = (props: DialogTitleProps) => {
```

2023-04-25 18:57 UTC, dwiley-akamai commented on packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
> +      <DialogTitle title={title} onClose={dialogProps.onClose} />
optional: destructure `onClose` as well and use it here and on L48

2023-04-25 21:30 UTC, hkhalil-akamai requested changes

2023-04-25 21:30 UTC, hkhalil-akamai commented on packages/manager/src/components/DialogTitle/DialogTitle.tsx
> +      <Box
Noticing a visual regression here in scrollable dialogs (such as `LinodeConfigDialog`):

https://user-images.githubusercontent.com/122488130/234408326-e48948df-a245-48ae-bb3a-f85ac7e5535c.mov



This could be caused by differences between `div` to `Box`.

2023-04-26 20:48 UTC, jaalah-akamai commented on packages/manager/src/components/DialogTitle/DialogTitle.tsx
> +      <Box
Should be fixed - replaced the header with what we're using elswhere 👍

2023-04-26 20:52 UTC, jaalah-akamai commented
The heading now matches what we use for confirmation/deletion dialogs using `DialogTitle` which is the standard.

| Light      | Dark | Prod |
| ----------- | ----------- | ----------- |
|![Screen Shot 2023-04-26 at 4 10 03 PM](https://user-images.githubusercontent.com/125309814/234699040-8964a2e4-c1c7-43ca-ab53-0b0eeb8e3003.png)|![Screen Shot 2023-04-26 at 4 10 34 PM](https://user-images.githubusercontent.com/125309814/234699080-54257b56-5f76-44fa-b99c-8a541c242feb.png)| ![Screen Shot 2023-04-26 at 4 51 11 PM](https://user-images.githubusercontent.com/125309814/234699427-3ba7b1ab-e692-4e74-b307-ffd671b0370b.png)|

<img width="773" alt="Screen Shot 2023-04-26 at 4 47 52 PM" src="https://user-images.githubusercontent.com/125309814/234699160-20673a24-7a30-4a46-aef5-2dd4a064dca1.png">
<img width="772" alt="Screen Shot 2023-04-26 at 4 48 00 PM" src="https://user-images.githubusercontent.com/125309814/234699162-c1df8088-d0d2-4c57-b057-9bb540759b64.png">

2023-04-26 21:17 UTC, mjac0bs approved these changes
'X' looks good in both modes and confirmed the regression on scrolling dialog modals is fixed. 🚢

2023-04-26 21:26 UTC, bnussman-akamai approved these changes

2023-04-27 15:21 UTC, hkhalil-akamai approved these changes
Looks great! Thanks for making this consistent across the app

2023-04-27 15:35 UTC, dwiley-akamai approved these changes

2023-04-27 16:19 UTC, merged