M3 6510
linode/manager pull request #9053
Opened 2023-04-25 16:40 UTC by cpathipa

## Description 📝
Fix - Modifying Configuration Profile in Cloud breaks with VLANs

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------ | ------- |
| ![image](https://user-images.githubusercontent.com/119517080/234343757-8eba9940-909d-41f9-95fd-f7a41f0c16bf.png) | ![image](https://user-images.githubusercontent.com/119517080/234344043-60f93cb9-42c5-4e25-9a78-f4f1fb04c274.png) |

## How to test 🧪

**How to reproduce the issue (if applicable)?**
- Checkout to develop branch
- Create a Linode in Cloud Manager with a standard image (Ubuntu, for example) and no VLAN
- After the Linode provisions, edit the configuration profile in Cloud Manager, adding a VLAN (with or without an IPAM address), then Save the configuration profile
- Edit the configuration profile again, then try to either a) add another VLAN, b) remove the existing VLAN by switching eth1 to None, or c) do literally nothing other than immediately Save the configuration profile (with no changes made).

**How to verify changes?**

- Follow the above steps to create Linode, configure and update with VLAN

**How to run Unit or E2E tests?**

- yarn test
- yarn cy:run

2023-04-25 16:56 UTC, bnussman-akamai requested changes

2023-04-25 16:56 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        const configInterfaces = config?.interfaces?.map(
Looks like we should update the type of `config.interfaces` so that this makes more sense. The API returns an `id` but our types don't show that.

2023-04-25 20:41 UTC, dwiley-akamai reviewed
Curious as to what made this break out of nowhere 🤔

2023-04-25 20:41 UTC, dwiley-akamai commented on CHANGELOG.md
> +- fix: [M3-6510] - Modifying Configuration Profile in Cloud breaks with VLANs #9053
```suggestion
Inability to edit and save Linode Configurations #9053
```

2023-04-25 20:41 UTC, dwiley-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        const configInterfaces = config?.interfaces?.map(
Interestingly, it's also [undocumented](https://www.linode.com/docs/api/linode-instances/#configuration-profiles-list) in the API docs 🤔

2023-04-25 21:09 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +        const configInterfaces = config?.interfaces?.map(
Also, as per the documentation Payloads doesn't accept` id` as well.

2023-04-25 21:23 UTC, hkhalil-akamai commented
> Curious as to what made this break out of nowhere 🤔

It appears to be related to this API ticket ARB-3629. The interface was modified to add the `id` field but the docs have not been updated.

2023-04-25 21:34 UTC, hkhalil-akamai approved these changes
Tested to confirm the fix is working as intended.

Approved pending `api-v4` suggestion by @bnussman-akamai.

2023-04-26 14:22 UTC, bnussman-akamai reviewed
I think the next steps for this PR would to be to update the `api-v4` types like the following

```ts
export interface Interface {
  id: number;
  label: string | null;
  purpose: InterfacePurpose;
  ipam_address: string | null;
}

type InterfacePayload = Omit<Interface, 'id'>;
```

Then update `LinodeConfigCreationData` to use `InterfacePayload`

2023-04-26 14:22 UTC, bnussman-akamai commented on CHANGELOG.md
> +Inability to edit and save Linode Configurations #9053
```suggestion
- Inability to edit and save Linode Configurations #9053
```

2023-04-26 14:22 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
> +            interfaces: interfacesToState(configInterfaces),
Instead of doing the `map` before this to setup the data, I think we should move all of that data manipulation to `interfacesToState`

2023-04-26 15:01 UTC, cpathipa commented
Great feedback! Thank you @bnussman-akamai and @hkhalil-akamai for taking a deeper look into this PR.

2023-04-26 15:45 UTC, bnussman-akamai approved these changes

2023-04-26 15:45 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
>  };
`interfacesToState` could use some clean up, but looks good to me otherwise

```typescript
const interfacesToState = (interfaces?: Interface[]) => {
  if (!interfaces || interfaces.length === 0) {
    return defaultInterfaceList;
  }
  const interfacesPayload = interfaces.map(
    ({ ipam_address, label, purpose }) => ({ ipam_address, label, purpose })
  );
  return padInterfaceList(interfacesPayload);
};
```

2023-04-26 16:58 UTC, merged