feat: [M3-5655] - Allow user to download DNS zone file
linode/manager pull request #9075
Opened 2023-05-02 14:43 UTC by cpathipa

## Description 📝
This enables user to Download DNS Zone file. 

| Before  | After   |
| ------- | ------- |
| ![image](https://user-images.githubusercontent.com/119517080/235699906-961cf306-3955-4206-ab6c-631fc6ca48e5.png) | ![image](https://user-images.githubusercontent.com/119517080/235700184-fea765a7-cb7a-4421-b3c2-ca24d8093b4c.png) |

## How to test 🧪

- Navigate to http://localhost:3000/domains
- Click on any domain.
- Able to see "Download DNS Zone file" link type button.
- Upon clicking should be able to download the DNS zone file.

2023-05-02 14:46 UTC, bnussman-akamai commented on packages/manager/src/features/Domains/DownloadDNSZoneFileButton.tsx
> +      document.body.removeChild(a);
Can we use our `downloadFile` helper function here?

2023-05-02 14:46 UTC, bnussman-akamai commented on packages/manager/src/features/Domains/DownloadDNSZoneFileButton.tsx
> +  const { data } = useDNSZoneFileQuery(id);
This might be one of the rare cases where we don't really need to use React query. We could just call `await getDNSZoneFile()` in handleClick

2023-05-02 17:34 UTC, jdamore-linode commented on packages/api-v4/src/domains/domains.ts
> + */
I think this might've been carried over from some older code and not updated for the new function

2023-05-02 17:34 UTC, jdamore-linode approved these changes
Looks good! Approving pending that suggestion from Banks. Nice work!

2023-05-02 18:19 UTC, bnussman-akamai requested changes

2023-05-02 18:19 UTC, bnussman-akamai commented on packages/manager/src/features/Domains/DownloadDNSZoneFileButton.tsx
> +      downloadFile('DNSzonefile.txt', zoneFileContent);
Can we have the file name be in the format `[domain].txt`? For example, `linode.com` would be  `linode.com.txt`. `DNSzonefile.txt` isn't very descriptive

```suggestion
      downloadFile(`${domain}.txt`, zoneFileContent);
```

2023-05-02 18:19 UTC, bnussman-akamai commented on packages/manager/src/features/Domains/DomainRecords.tsx
> +      link: () => <DownloadDNSZoneFileButton id={this.props.domain.id} />,
Just realized this now and it's not your fault, but the location of this button makes no sense. Downloading the entire zone file isn't specific to the "SOA records"... 

 I think this button should go beside the `Delete Domain` button at the bottom of the page

![Screenshot 2023-05-02 at 2 14 03 PM](https://user-images.githubusercontent.com/115251059/235751492-735ab124-b533-4bf1-9575-132e5064f6b8.jpg)

2023-05-02 20:01 UTC, cpathipa commented on packages/manager/src/features/Domains/DomainRecords.tsx
> +      link: () => <DownloadDNSZoneFileButton id={this.props.domain.id} />,
Good call. I agree, it shouldn't be specific to SOA records. IMO, we showing it next to docs link may be more visible to user to download DNS. I will circle back with UX on this. 

![image](https://user-images.githubusercontent.com/119517080/235772823-0333f2ea-ee57-4f97-859e-89b0f12a9a35.png)

2023-05-03 13:45 UTC, bnussman-akamai approved these changes
Awesome! 🚀

2023-05-03 13:45 UTC, bnussman-akamai commented on packages/manager/src/features/Domains/DownloadDNSZoneFileButton.test.tsx
> +      require('src/utilities/downloadFile').downloadFile
That's cool that this works, I'm just unsure if it is recommended. `require` might not work nicely in a non commonjs environment in the future.

```suggestion
      require('src/utilities/downloadFile').downloadFile
```

2023-05-03 14:37 UTC, cpathipa commented on packages/manager/src/features/Domains/DownloadDNSZoneFileButton.test.tsx
> +      require('src/utilities/downloadFile').downloadFile
Good call, replaced `require` with `import`.

2023-05-03 16:28 UTC, merged