feat: [M3-6470] - Add resource links to StackScripts empty state landing state
linode/manager pull request #9091
Opened 2023-05-06 02:44 UTC by cpathipa

## Description 📝
**Brief description explaining the purpose of the changes**

| Before  | After   |
| ------- | ------- |
| ![image](https://user-images.githubusercontent.com/119517080/236594445-536f4d0c-7682-471d-aba6-25cd29375c9e.png) | ![image](https://user-images.githubusercontent.com/119517080/236594452-f48a1f6c-4f01-4939-bc31-c45b6117cd83.png)) |

## How to test 🧪

- Navigate to http://localhost:3000/stackscripts/account
- Validate the empty state landing page and links
- Validate Create StackScript flow

2023-05-08 15:20 UTC, abailly-akamai requested changes
Looks good! couple changes needed

2023-05-08 15:20 UTC, abailly-akamai commented on packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSubSection.tsx
> +      <Typography variant="h2" style={{ textAlign: 'left' }}>
We shouldn't need this and it points to some a CSS bleed which we should address instead

![Screenshot 2023-05-08 at 11 16 10 AM](https://user-images.githubusercontent.com/130582365/236862570-67b582e6-326d-4ffd-a556-19fe712a7f0a.jpg)

2023-05-08 15:20 UTC, abailly-akamai commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
> +import { StackScriptsEmptyLandingState } from './StackScriptsEmptyLandingPage';
Let's start ordering imports where we can!

2023-05-08 15:20 UTC, abailly-akamai commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyResourcesData.ts
> +      to: 'https://jira.linode.com/browse/M3-6470#10',
this links to a Jira ticket!

2023-05-08 15:45 UTC, cpathipa commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyResourcesData.ts
> +      to: 'https://jira.linode.com/browse/M3-6470#10',
My bad! for some reason right click and copy link address capturing ticket address.

2023-05-08 16:40 UTC, cpathipa commented on packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSubSection.tsx
> +      <Typography variant="h2" style={{ textAlign: 'left' }}>
Good call. Addressed this in the commit [611ee46](https://github.com/linode/manager/pull/9091/commits/611ee46c2c432be69bf5ec1070983a4bee2e4b1f)

2023-05-08 17:19 UTC, dwiley-akamai commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyResourcesData.ts
> +        'https://www.linode.com/docs/products/tools/stackscripts/guides/create/',
This is a docs guide but should be a YouTube video–can we get confirmation from UX on what link should be used here?

2023-05-08 17:20 UTC, abailly-akamai approved these changes

2023-05-09 17:17 UTC, cpathipa commented on packages/manager/src/features/StackScripts/StackScriptBase/StackScriptsEmptyResourcesData.ts
> +        'https://www.linode.com/docs/products/tools/stackscripts/guides/create/',
Thank you @dwiley-akamai working with Matt regarding that. Will update the relevant link once confirmed.

2023-05-10 17:18 UTC, jaalah-akamai approved these changes
Approved pending updated link

2023-05-10 17:58 UTC, cpathipa commented
> Approved pending updated link

Thank you @jaalah-akamai still waiting for the confirmation on video link.

2023-05-10 20:07 UTC, cpathipa commented
Updated the Shell Scripts video link. Also, update title `Shell Scripts`  to `Shell Scripts Explained`" as suggested by Marketing Team.

2023-05-10 20:15 UTC, merged