refactor: M3-6489: React Query Linode Details - Network Tab
linode/manager pull request #9097
Opened 2023-05-08 18:32 UTC by bnussman-akamai

## Description 📝

- React Query-ifys most things under the Linode Details Network Tab
- Moved around some components and renamed many components to be more simple and clear
- Logic specifically around IPv6, IP Transfer, and IP sharing all feel very sketchy, please test these

## Preview 📷

> **Note**: No visual changes are expected

![Screenshot 2023-05-08 at 2 28 20 PM](https://user-images.githubusercontent.com/115251059/236902440-896a6d1b-42cd-4ae7-b7b4-7640de4905ec.jpg)

## How to test 🧪
- I recommend spinning up two linodes in the same datacenter before you begin your testing
- Please thoroughly test all possible actions under the Network tab
  - Add an IP
  - Delete an IP
  - Share IPs
  - Transfer and Swap IPs
  - Edit RNDS

2023-05-09 01:14 UTC, bnussman-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
> +        {ipv6Error && (
```suggestion
        {Boolean(ipv6Error) && (
```

2023-05-10 17:25 UTC, jaalah-akamai commented on packages/api-v4/src/linodes/ips.ts
>   * @param {IPv6Range: string} payload - the IPv6 Range for which you'd like the delete request to be invoked
Probably should update the param here too

2023-05-10 17:30 UTC, jaalah-akamai commented on packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRangeRDNSDrawer.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
Are you ok with converting this to tss since we changed the file name - I don't want us losing track of this. Open to suggestions

2023-05-10 17:33 UTC, jaalah-akamai approved these changes
Just a few comments! Nice job

2023-05-10 19:13 UTC, hkhalil-akamai requested changes
Noticing one teeny tiny regression: when editing the RDNS domain on a public IPv4 address, if the field is cleared and saved, this results in the RDNS domain being reset. When opening the drawer again, it should show the default domain, but it instead shows an empty field. See attached video:

https://github.com/linode/manager/assets/122488130/b81cc19f-978b-4315-9231-5a2aa4f46991

2023-05-10 20:30 UTC, hkhalil-akamai approved these changes

2023-05-11 01:59 UTC, merged