test: [M3-6549] - Add Cypress Integration tests for OAuth Apps
linode/manager pull request #9163
Opened 2023-05-23 21:03 UTC by cliu-akamai

## Description 📝
Add new cypress tests for OAuth Apps

## Major Changes 🔄
- Add `OAuth Apps` addition tests.
- Add `OAuth Apps` editing  tests.
- Add `OAuth Apps` resetting tests.
- Add `OAuth Apps` deletion tests.

## How to test 🧪
`yarn cy:run -s "cypress/e2e/profile/*.spec.ts"`

2023-05-24 13:19 UTC, jdamore-linode requested changes
Great start Cassie! I haven't been able to actually run your tests right now due to unrelated issues so I will circle back later this afternoon once everything's working, but in the meantime I left a few suggestions

2023-05-24 13:19 UTC, jdamore-linode commented on packages/manager/cypress/support/util/random.ts
> +  const characterSelection = [hexNumber].join('').split('');
```suggestion
  const characterSelection = hexNumber.split('');
```
I think this could be simplified a bit! Is there anything major that distinguishes this from the `randomString()` util? If I'm understanding correctly we might be able to use `randomString(64)`

2023-05-24 17:39 UTC, cliu-akamai commented on packages/api-v4/src/account/types.ts
> +  secret: string | null;
Got it.

2023-05-26 01:30 UTC, jaalah-akamai approved these changes

2023-05-26 15:16 UTC, jdamore-linode commented on packages/manager/cypress/e2e/profile/add-oauth-app.spec.ts
This test doesn't seem to be using mock data and is actually creating real OAuth apps. I think we're going to want some mock utils in `intercepts/profile.ts` for this since we don't want Cypress to actually create and delete OAuth apps (mostly due to concerns with having the secrets exposed in the recordings).

2023-06-08 22:56 UTC, hkhalil-akamai commented
Looks really good. Just one minor concern: the tests do not check that the dialog/drawer for the add/edit/reset/delete actions actually close when the action is completed/cancelled (e.g., by checking that the dialog/drawer is no longer rendered or visible).

Also, should the tests try closing the dialog/drawer using the 'X' in the corner?
![Screenshot 2023-06-08 at 6 54 00 PM](https://github.com/linode/manager/assets/122488130/2d62d6c6-a859-4a2d-91b6-1834e032750f)
![Screenshot 2023-06-08 at 6 54 32 PM](https://github.com/linode/manager/assets/122488130/e92306c2-f2a5-4828-ad4c-503544c37015)

2023-06-16 18:08 UTC, cliu-akamai commented
> Looks really good. Just one minor concern: the tests do not check that the dialog/drawer for the add/edit/reset/delete actions actually close when the action is completed/cancelled (e.g., by checking that the dialog/drawer is no longer rendered or visible).
> 
> Also, should the tests try closing the dialog/drawer using the 'X' in the corner? ![Screenshot 2023-06-08 at 6 54 00 PM](https://user-images.githubusercontent.com/122488130/244528663-2d62d6c6-a859-4a2d-91b6-1834e032750f.jpg) ![Screenshot 2023-06-08 at 6 54 32 PM](https://user-images.githubusercontent.com/122488130/244528796-e92306c2-f2a5-4828-ad4c-503544c37015.jpg)

That's a good point, I will update that.

2023-06-20 20:04 UTC, hkhalil-akamai approved these changes
Thanks for making the changes! I think you might have missed testing the 'X' button in Delete and Reset. It would be great if you could add those checks, but I will approve now so you don't have to wait on me!

2023-06-20 20:04 UTC, hkhalil-akamai commented on packages/manager/cypress/e2e/profile/add-oauth-app.spec.ts
> +  ui.drawerCloseButton.find().click();
Thank you for testing the 'X' button in Add and Edit, can you add this check to the Delete and Reset dialog as well?

2023-06-21 19:55 UTC, jdamore-linode commented on packages/manager/cypress/support/api/profile.ts
> +  console.log(`oauth apps: ${JSON.stringify(oauthApps)}`);
```suggestion
```
I don't think this is too big a deal since the secret gets redacted but probably good to get rid of this just in case!

2023-06-21 19:57 UTC, jdamore-linode commented on packages/manager/cypress/support/ui/common.ts
> +      deleteAllTestOAuthApps(),
I don't think we really need this since the tests don't make OAuth apps anymore, but it doesn't hurt anything by being there either

2023-06-21 19:57 UTC, jdamore-linode approved these changes
Nice work @cliu-akamai !

2023-06-22 16:10 UTC, merged