M3 6572
linode/manager pull request #9165
Opened 2023-05-24 03:59 UTC by cpathipa

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-05-25 12:53 UTC, bnussman commented
Please add a chageset to your PR 🥺🚨

2023-05-30 14:26 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
> +    const premium = getPremium(types);
In this PR we are currently not referencing SelectPlanPanel in any where. `SelectPlanPanel` and `SelectPlanQuantityPanel` components will be removed completely in the following PR.

2023-05-31 18:51 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/GPUNotice.tsx
> +  };
This function is duplicated in a few other places, can we move this to a utility file?

2023-05-31 18:51 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.test.tsx
> +  });
Do we still need this test if we have `PremiumPlansAvailabilityNotice.test.tsx`?

2023-05-31 18:51 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
> +  };
What about something like this instead?

```suggestion
  const getDisabledClass = (thisClass: LinodeTypeClass) => {
    return Boolean(disabledClasses?.includes(thisClass));
  };
```

2023-05-31 18:51 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.tsx
> +      {planType === 'premium' ? <PremiumPlansAvailabilityNotice /> : null}
`dataTestId` is being passed as a prop but then the components end up using a hardcoded string. Do we need `dataTestId` as a prop?

2023-05-31 18:51 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
> +  const planTooSmall = diskSize > type.disk;
```suggestion
  const planTooSmall = diskSize > type.disk;
  const tooltip = planTooSmall
    ? 'This plan is too small for the selected image.'
    : undefined;
```

2023-05-31 20:19 UTC, hkhalil-akamai requested changes
Overall functionality looks good, I agree with the approach of not merging the two Plan selection components since they sufficiently different but taking out shared functionality instead.

Left a few comments.

2023-05-31 20:41 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/GPUNotice.tsx
> +  };
Good catch @hana-linode That was part of my initial plan, but somehow I forgot to move it.

2023-05-31 20:44 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlanInformation.test.tsx
> +  });
Technically, it's not required as it is covered at the unit level in PremiumPlansAvailabilityNotice. However, it may be needed if we consider integration level. Nevertheless, I have removed it.

2023-06-01 16:47 UTC, cpathipa commented
> Overall functionality looks good, I agree with the approach of not merging the two Plan selection components since they sufficiently different but taking out shared functionality instead.
> 
> Left a few comments.

@hkhalil-akamai Thank you for bringing this up. I'm inline with your suggestions. As we discussed following PR that further simplifies `KubernetesPlanContainer`, `KubernetesPlanSelection` `PlanContainer` and `PlanSelection` Also, address your feedback.

2023-06-01 20:27 UTC, hana-linode reviewed
Can we remove the original components and the backup plan can be to revert this PR if necessary? It's a bit confusing to have the old and new components together imo

2023-06-01 20:27 UTC, hana-linode commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
> +export const RenderSelectionLKE = ({
Can we rename this to the file name `KubernetesPlanSelection`?

2023-06-02 17:52 UTC, cpathipa commented
> Can we remove the original components and the backup plan can be to revert this PR if necessary? It's a bit confusing to have the old and new components together imo

@hana-linode There may be a potential risk of handling code conflicts in case we go with route of reverting the PR. I'm trying to avoid that scenario. Additionally, old and unused components will be completely removed in the next release. If it's still confusing, I can create a PR removing those files, but we can hold off on merging it until the following release.

2023-06-02 20:39 UTC, hkhalil-akamai approved these changes

2023-06-05 14:20 UTC, jcallahan-akamai commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
> +  ldClient?: LDClient;
Is this used anywhere?

2023-06-05 20:02 UTC, cpathipa commented on packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
> +  ldClient?: LDClient;
We are not using this. I think it is because we carried all the props from `SelectPlanPanel`, removed from the Prop types.

2023-06-07 19:59 UTC, merged