WIP
linode/manager pull request #9175
Opened 2023-05-25 12:39 UTC by carrillo-erik

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-05-25 12:39 UTC, bnussman commented
Please add a chageset to your PR 🥺🚨

2023-05-25 12:39 UTC, bnussman commented
Please add a chageset to your PR 🥺🚨

2023-05-30 17:56 UTC, abailly-akamai commented
@carrillo-erik not sure what you are trying to do with passing `{...rest}` to `TypeToConfirmDialog`? Maybe start by deleting that and work your way from there?

![Screenshot 2023-05-30 at 1 47 03 PM](https://github.com/linode/manager/assets/130582365/0441f60d-9906-4cde-b26c-c0c83c593040)

2023-06-05 14:33 UTC, bnussman-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +      <div style={{ display: 'flex', flexDirection: 'column', order: 2 }}>
I don't think this div is doing much. I think it maybe can removed. If we need it, I think we should use a `<Stack />`.

```suggestion
```

2023-06-05 14:33 UTC, bnussman-akamai commented on packages/manager/src/features/Account/EnableObjectStorage.tsx
This dialog has the wrong copy and also the `entity.type` saying "AccountSetting" needs to be improved.
![Screenshot 2023-06-05 at 10 30 31 AM](https://github.com/linode/manager/assets/115251059/558ffa7c-ceb2-40a0-85eb-f721649b97ab)

2023-06-05 17:23 UTC, abailly-akamai reviewed
Nice! needs some cleanup (will review in the browser when done)

Also, don't hesitate to add a comment why you are using a flex order because of the renderProps

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +    if (entity.type === 'Volume' && title.startsWith('Detach')) return 'Detach';
isn't `title` an optional prop? seems odd that TS isn't complaining here

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +    if (entity.type === 'Volume' && title.startsWith('Detach')) return 'Detach';
```suggestion
    if (entity.type === 'Volume' && title?.startsWith('Detach')) return 'Detach';
```

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +    order: 3,
I believe you don't need `display` or `flexDirection` to declare an `order` with a grid or flex parent

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +        >
same here, no need for flex and we should use a styled component

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +      <div style={{ display: 'flex', flexDirection: 'column', order: 4 }}>
same

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/features/Account/EnableObjectStorage.tsx
>            <Typography style={{ fontSize: '0.875rem' }}>
let's get rid of style in favor of sx when possible

2023-06-05 17:23 UTC, abailly-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +        >
also you already have an order 3 on the `dontgo` className - wondering what this does

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +    if (entity.type === 'AccountSetting' && entity.subType === 'CloseAccount') {
Are you seeing this linter complaint also?

![Screenshot 2023-06-05 at 4 59 29 PM](https://github.com/linode/manager/assets/114682940/1f57670f-45ae-4c06-85b3-bba7e73103cc)

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +          confirmationText={
Would there be a scenario under which `confirmationText` would be defined but shouldn't be rendered?

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +      case 'ObjectStorage':
The distinction between `Bucket` and `ObjectStorage` here wasn't clear to me on the first pass or two -- had to check to ascertain that the latter was referring to canceling OBJ

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
> -          </span>
the removal of this results in some slightly different copy now with a capitalized entity name -- has UX weighed in?

![Screenshot 2023-06-05 at 5 16 21 PM](https://github.com/linode/manager/assets/114682940/ce8bce50-687c-4559-a942-e9cf0ad0b15d)

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
> +      entity={{ type: 'Kubernetes', subType: 'Cluster', label: clusterLabel }}
leads to "the Kubernetes" with the current logic in `TypeToConfirmDialog.tsx`

![Screenshot 2023-06-05 at 5 18 08 PM](https://github.com/linode/manager/assets/114682940/905d540d-a79a-4d1d-91d1-0a1f371d1bb7)

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
"Warning" is on its own line now compared to production:

![Screenshot 2023-06-05 at 1 15 49 PM](https://github.com/linode/manager/assets/114682940/f8236a6f-f230-4b8b-9af5-e2c4d52f37a3)

2023-06-05 21:23 UTC, dwiley-akamai commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
Looks like the copy got mixed up with database deletion:

![Screenshot 2023-06-05 at 12 58 11 PM](https://github.com/linode/manager/assets/114682940/94c4b954-9f2e-460e-bf5a-76ebfce18587)

2023-06-08 13:50 UTC, abailly-akamai commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +      ttcAction = 'deletion';
those would be much better as switch statements

2023-06-08 17:43 UTC, carrillo-erik commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
I have resolved this issue with my latest changes.

2023-06-08 17:43 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
> +      entity={{ type: 'Kubernetes', subType: 'Cluster', label: clusterLabel }}
I've updated the logic to address this issue.

2023-06-08 17:46 UTC, carrillo-erik commented on packages/manager/src/features/Account/EnableObjectStorage.tsx
I think I must have inadvertently copied and pasted code from a different component here and it slipped by. I have fixed this issue.

2023-06-08 17:47 UTC, carrillo-erik commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +      <div style={{ display: 'flex', flexDirection: 'column', order: 2 }}>
After addressing other comments, I realized this was not necessary. It's been removed.

2023-06-08 17:49 UTC, carrillo-erik commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +    order: 3,
You are correct. I think I had my components mixed up and left these properties on accident.

2023-06-08 17:53 UTC, carrillo-erik commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
> +        >
Thanks for the second pair of eyes on this. I've made the necessary changes.

2023-06-08 17:57 UTC, carrillo-erik commented on packages/manager/src/features/Account/EnableObjectStorage.tsx
>            <Typography style={{ fontSize: '0.875rem' }}>
Done ✅

2023-06-08 18:09 UTC, carrillo-erik commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
> -          </span>
I've changed the logic to keep it consistent to the previous implementation.

2023-06-08 18:53 UTC, carrillo-erik commented on packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
> +      ttcAction = 'deletion';
Took your suggestion and made the change.

2023-06-09 19:55 UTC, dwiley-akamai reviewed
I went through the app on this branch and compared and to prod and noticed:

- There's a bit of extra padding below the Warning notice in the `Close Account` modal and below the Warning notice in the `Delete OBJ Bucket` modal
- There's a lot of extra padding below the input field in the Linode Resize & Rebuild modals
- Still seeing "To confirm deletion..." (instead of "To confirm cancellation...") in the `Cancel Object Storage` modal

2023-06-15 21:27 UTC, carrillo-erik commented on packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
> +      onClick={() => handleRestoreDatabase}
This was the one issue I was having the TS and the `onClick` event when I started refactoring the component. I've made several changes from when I first started working on this ticket. I went back and revert the changes to this event handler and TS doesn't complaint anymore and the functionality works.

2023-06-15 21:28 UTC, carrillo-erik commented
I've addressed these concerns with my latest changes.

2023-06-26 23:29 UTC, hkhalil-akamai requested changes

2023-06-26 23:29 UTC, hkhalil-akamai commented on packages/manager/src/features/Account/CloseAccountDialog.tsx
Noticing a regression in this component as the "Close Account" button is never enabled, even when the correct username is entered in the confirmation field. Looks like the `inputtedUsername` state is never being updated.

2023-06-30 17:26 UTC, bnussman-akamai requested changes
Can you checkout the PR and run `yarn`, then push the changes. The `yarn.lock` is out of date

2023-06-30 17:50 UTC, jaalah-akamai commented
@carrillo-erik There has come together really nice. I think this component will benefit a ton from a storybook page. See https://github.com/linode/manager/tree/develop/packages/manager/src/components/Button as to how we did the JSDocs and stories file.

2023-06-30 17:51 UTC, carrillo-erik commented
@bnussman-akamai I had pushed some changes to the `yarn.lock` file and the `cachedData` files. John asked me to remove those changes from the PR. I reverted the commit and reintroduced the changes to fix the pertaining issue.

2023-06-30 18:22 UTC, hkhalil-akamai approved these changes
Functionality of all improved components looks good. Approved pending suggestions from @jaalah-akamai @bnussman-akamai.

Nice work and thanks for bearing with the review changes!

2023-06-30 18:44 UTC, cpathipa approved these changes

2023-06-30 20:14 UTC, bnussman-akamai commented
Sounds good @carrillo-erik, still before you merge, just run `yarn` and push those changes. If we don't we'll get dependabot alerts

2023-07-03 20:48 UTC, carrillo-erik commented
> Can you checkout the PR and run `yarn`, then push the changes. The `yarn.lock` is out of date

I had some merge conflicts with the `yarn.lock` file after pulling the latest. I believe this resolves the issue you brought up. Let me know, thanks.

2023-07-05 16:04 UTC, merged