refactor: [M3-6377] - MUI v5 - Components > ProductInformationBanner
linode/manager pull request #9213
Opened 2023-06-06 14:33 UTC by cpathipa

## Description 📝
**MUI migration SRC > Components > ProductInformationBanner**

## Major Changes 🔄

- Run tss-react codemod on `ProductInformationBanner` 
- Renamed Props to    ProductInformationBannerProps.
- Changes default exports to named exports.

## How to test 🧪

- Verify all the references of `ProductInformationBanner`.
- Verify e2e tests pass

2023-06-13 00:59 UTC, jaalah-akamai approved these changes

2023-06-13 01:00 UTC, jaalah-akamai commented
@cpathipa let's merge in develop like Hana suggested first

2023-06-13 14:45 UTC, hana-linode requested changes
Can we fix the import errors?

![image](https://github.com/linode/manager/assets/115299789/b1b10841-995f-49c1-b89f-b5c011818ad8)

2023-06-14 16:25 UTC, hana-linode approved these changes

2023-06-14 19:47 UTC, merged