refactor: [M3-6503] - Combine SelectPlanPanel and SelectPlanQuantityPanel components - part 1
linode/manager pull request #9225
Opened 2023-06-07 20:01 UTC by cpathipa

## Description 📝

- This PR simplifies  `SelectPlanPanel` and  `SelectPlanQuantityPanel` components.
- Removes redundant / duplicate code.
- Provides single source of truth to generate tabs and plan types from utils `getPlanSelectionsByPlanType` and  `planTabInfoContent`.
- As a back-out plan, original components are untouched, created new components (`PlansPanel` and `KubernetesPlansPanel`) and referenced in respective plans tables.

## Major Changes 🔄
- References PlansPanel instead of SelectPlanPanel
- References KubernetesPlansPanel instead of SelectPlanQuantityPanel

## Preview 📷
No visual changes. 

## How to test 🧪
- Validate Linodes Plans Table.
- Validate Database Plans Table.
- Validate Kubernetes Plans Table.
- Validate general functionalities in Linode create / clone / backup/ resize/ rebuild flow's.
- Validate general functionalities in Database create flow.
- Validate general functionalities in Kubernetes create cluster flow.
- yarn test 
- yarn cy:run

2023-06-07 20:33 UTC, bnussman commented
Please add a chageset to your PR 🥺🚨

2023-06-08 14:14 UTC, jaalah-akamai commented
@cpathipa I think the description got deleted?

2023-06-08 14:27 UTC, dwiley-akamai requested changes
The Linode Create and Kubernetes Create pages crash for me (as well as the Resize modal):

![Screenshot 2023-06-08 at 10 23 29 AM](https://github.com/linode/manager/assets/114682940/4a666a47-266b-4b77-8847-31fa2648191e)

![Screenshot 2023-06-08 at 10 24 02 AM](https://github.com/linode/manager/assets/114682940/17f91639-6584-4b71-b22d-6d9333486523)

2023-06-08 14:32 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
> +  });
We could follow the same pattern as you did above by using `reduce` to filter the plan:
```
const filteredPlansByType = Object.keys(plansByType).reduce((acc, key) => {
    if (plansByType[key].length > 0) {
      acc[key] = plansByType[key];
    }
    return acc;
  }, {} as PlansByType<T>);

return filteredPlansByType;
```

2023-06-08 14:54 UTC, cpathipa commented
> @cpathipa I think the description got deleted?

@jaalah-akamai its the same [PR](https://github.com/linode/manager/pull/9165). but, merging to develop.

2023-06-08 15:57 UTC, cpathipa commented
> The Linode Create and Kubernetes Create pages crash for me (as well as the Resize modal and Add Node Pool drawer):
> 
> ![Screenshot 2023-06-08 at 10 23 29 AM](https://user-images.githubusercontent.com/114682940/244411183-4a666a47-266b-4b77-8847-31fa2648191e.jpg)
> 
> ![Screenshot 2023-06-08 at 10 24 02 AM](https://user-images.githubusercontent.com/114682940/244411217-17f91639-6584-4b71-b22d-6d9333486523.jpg)

@dwiley-akamai handled this scenario.

2023-06-08 16:53 UTC, dwiley-akamai approved these changes

2023-06-08 16:53 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanContainer.tsx
> +  { cellName: 'Quantity', testId: 'quantity', center: false, noWrap: false },
It looks a tad odd to not center `Quantity` IMO:

![Screenshot 2023-06-08 at 12 42 59 PM](https://github.com/linode/manager/assets/114682940/7e9928e0-d199-467e-ab72-a42a35d788f3)

2023-06-08 16:53 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
> +//We could update this to add or remove any new or existing plan tabs.
```suggestion
// We could update this to add or remove any new or existing plan tabs.
```

2023-06-08 16:53 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
> +  //group plans by type
```suggestion
// group plans by type
```

2023-06-08 17:01 UTC, bnussman-akamai approved these changes
I tested general provisioning of Linodes and LKE clusters

2023-06-08 18:51 UTC, merged