style: [M3-6314] - Plan selection—reduce space
linode/manager pull request #9238
Opened 2023-06-09 17:32 UTC by cpathipa

## Description 📝

- Reduce space between selection column and Plans column 
- Consolidate plansPanelStyles 

Linode Create 
| Local  | Production   |
| ------- | ------- |
|![image](https://github.com/linode/manager/assets/119517080/7bface6f-d622-487a-b205-2a5e8077e6ba) | ![image](https://github.com/linode/manager/assets/119517080/d35a4c0d-391a-456c-9088-0f03d880c3ca) |

Kubernetes
| Local  | Production   |
| ------- | ------- |
| ![image](https://github.com/linode/manager/assets/119517080/6f596c52-79c1-40ac-8b3a-0d1db5596ad8) | ![image](https://github.com/linode/manager/assets/119517080/a7e4545a-8951-4770-98ea-83489505bd89) |

Node pools
| Local  | Production   |
| ------- | ------- |
| ![image](https://github.com/linode/manager/assets/119517080/30c8106d-37da-4fb3-8bfe-585ccc95ae4e) | ![image](https://github.com/linode/manager/assets/119517080/72aa758c-fc6a-43b8-9e85-3dbe3e2235aa) |

Databases
| Local  | Production   |
| ------- | ------- |
| ![image](https://github.com/linode/manager/assets/119517080/99c79c90-1875-4d19-8ab6-60badd490778) | ![image](https://github.com/linode/manager/assets/119517080/47394ec8-4f48-456a-9a7f-320ff2139c0b) |

## How to test 🧪

- Validate plans table in Linode , Databases and LKE

2023-06-13 01:06 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles/plansPanelStyles.ts
> +export const usePlansPanelStyles = makeStyles()((theme: Theme) => ({
We need to work to convert this to re-useable styled components. Having a shared styles file like this will be hard to maintain over time

2023-06-13 01:06 UTC, jaalah-akamai approved these changes

2023-06-13 14:00 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
> +  // const { classes } = useSelectPlanQuantityStyles();
Please delete comment

2023-06-13 14:00 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles/plansPanelStyles.ts
> +export const usePlansPanelStyles = makeStyles()((theme: Theme) => ({
Agreed!

2023-06-15 14:05 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
> +                      } ${classes.headerCell}`}
Can we use `cx` here? Also, it would be nice if `planHeaderCell` wasn't just a string class name

```suggestion
                      className={cx(
                        { planHeaderCell: cellName === 'Plan' },
                        classes.headerCell
                      )}
```

2023-06-15 16:36 UTC, dwiley-akamai reviewed
Did UX request/approve that heavy indentation of the "Add Node Pools" section on the LKE Create page?

2023-06-15 16:36 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
> +  const { classes } = usePlansPanelStyles();
`cx` needs to be destructured here, Linode Create is crashing for me currently:

![Screenshot 2023-06-15 at 12 32 56 PM](https://github.com/linode/manager/assets/114682940/e2fb359f-8cae-4978-907e-6c0b43553644)

2023-06-16 15:31 UTC, cpathipa commented
@abailly-akamai @bnussman-akamai @dwiley-akamai Great feedback, made additional changes which include converting to styled components and enabling CompactX for all type of Button components. PR is now ready for re-review.

2023-06-16 18:11 UTC, abailly-akamai requested changes
Nice refactor! pls see comments to comply with our MUI refactors and stories

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/components/Button/Button.stories.mdx
> +/>
We are deprecating .mdx files, let's not add new ones!

Besides, this work has already been done in #9248 and pease see comment about use of mdx https://github.com/linode/manager/pull/9248#pullrequestreview-1477238756

maybe you can just add to the story as needed

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
> +const StyledInputOuter = styled('div')(({ theme }) => ({
let's always add a `label` on Styled components for easier debugging

```suggestion
const StyledInputOuter = styled('div', { label:  'StyledInputOuter'})(({ theme }) => ({
```

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
> +      <StyledInputOuter theme={theme}>
you don't need to pass theme to a styled component. it's available by default as a destructured prop

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
> +            <StyledInputOuter theme={theme}>
same here, no need to pass `theme`

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
> +
just add this as an SX prop and remove makeStyles all together

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.tsx
> +
this should probably be in its own `.styles.ts` file and we should use Styled components here as well. We want to rely as little as possible on makeStyles()

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.tsx
> +}));
same here, let's not add makeStyles(), use Styled Components

2023-06-16 18:11 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlansPanel.tsx
> +
same! use sx or styled component

2023-06-16 18:15 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlanSelection.tsx
> +}));
[bottom of the file](https://github.com/linode/manager/blob/develop/docs/development-guide/02-component-structure.md#styles)

2023-06-20 14:41 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/KubernetesPlansPanel.tsx
> +      rootClass={cx(classes.root)}
Yeah, cx is not required here. So removed it. Also, used `sx` here since it is has very little styles.

2023-06-20 16:13 UTC, cpathipa commented on packages/manager/src/components/Button/Button.stories.mdx
> +/>
@abailly-akamai Sure, reverted this change https://github.com/linode/manager/commit/9b28b9c7e5e4e98c05f93df24c245b85dbe9cc2f

2023-06-20 16:14 UTC, cpathipa commented
@abailly-akamai and @jaalah-akamai removed makeStyles completely and addressed all the PR feedback and ready for review.

2023-06-20 16:26 UTC, jaalah-akamai commented on packages/manager/src/components/Button/Button.stories.mdx
> +/>
@cpathipa pull in latest from develop. I redid the storybook page for buttons last week where I removed the MDX file

2023-06-20 16:27 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
Let's rename this file `PlansPanel.styles.ts` instead of `styles.ts`

2023-06-20 16:42 UTC, jaalah-akamai requested changes

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
> +import { useTheme } from '@mui/material/styles';
This is the wrong import, should be: `import { styled } from '@mui/material/styles';`

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
> +    const theme = useTheme();
You shouldn't need to do this, you can pull the theme like this:
```
export const StyledTypography = styled(Typography, {
  label: 'StyledTypography',
})(({ theme }) => ({
  fontSize: '0.9em',
  '& a': {
    color: theme.textColors.linkActiveLight,
  },
  '& a:hover': {
    color: '#3683dc',
  },
  '& p': {
    fontFamily: '"LatoWebBold", sans-serif',
  },
}));
```

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
> +export interface StyledDisabledTableRowProps extends TableRowProps {
No need to export this and it's cleaner to just pick this type off: `type StyledDisabledTableRowProps = Pick<TableRowProps, 'disabled'>;`

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
> +  const theme = useTheme();
Same as above, also just export this inline and remove L47

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.styles.ts
See my other comments above using the correct `styled` import, exports, and removing `useTheme`

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.styles.ts
See my other comments above using the correct `styled` import, exports, and removing `useTheme`

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.styles.ts
> +export interface StyledTableCellPropsProps extends TableCellProps {
Just pick this property off instead of extending

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanContainer.styles.ts
> +  shouldForwardProp: (prop) => isPropValid(['isPlanCell'], prop),
Let's add a label

2023-06-20 16:42 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.styles.ts
> +    color: '#fff',
We can probably use `theme.color.white`

2023-06-20 17:02 UTC, dwiley-akamai reviewed
the UI looks good to me but I agree with Jaalah's feedback. With those changes I think this will be good to go

2023-06-20 18:47 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/PlanSelection.styles.ts
> +    color: '#fff',
@jaalah-akamai Not sure if this is desired UX for Chip. Looks like irrespective of theme we are applying white here.
![image](https://github.com/linode/manager/assets/119517080/84f6c0c7-2e36-4bfe-bed1-252f6b14ece1)

2023-06-21 00:59 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/styles.ts
This looks like the last thing needed to be done - other stuff looks good

2023-06-21 13:39 UTC, abailly-akamai approved these changes
Nice rework! approving pending removing the Button.mdx file and the styles file rename

2023-06-21 13:39 UTC, abailly-akamai commented on packages/manager/src/components/Button/Button.stories.mdx
> +/>
@cpathipa what do you mean? We just don't want to re-add this file

2023-06-21 14:20 UTC, cpathipa commented
@abailly-akamai sorry for the confusion, For some reason Button.stories.mdx file didn't show up in my VScode. I thought it got updated automatically after pulling latest from develop.
@jaalah-akamai Also, renamed the file to `PlansPanel.styles.ts`

2023-06-21 14:37 UTC, jaalah-akamai approved these changes

2023-06-21 14:51 UTC, merged