refactor: [M3-6356] - MUI v5 Migration - `Components > LineGraph`
linode/manager pull request #9276
Opened 2023-06-16 18:35 UTC by jaalah-akamai

## Description 📝
Refactor `LineGraph` with `styled` api

## Major Changes 🔄
- Removed `jss` and `makeStyles` for `styled` api
- Updated imports/exports
- Fixed bug for `LinodeEntityDetail.tsx` causing console error `Cannot have a div within a p tag`
- Uncovered bug for `NetworkGraphs.tsx` where the graphs weren't spanning full width after properly refactoring (probably was masked by some collision between `jss` and new styles`

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![Screenshot 2023-06-16 at 2 13 35 PM](https://github.com/linode/manager/assets/125309814/dbbed174-0d56-4003-9f6f-22f76d7d428b) | ![Screenshot 2023-06-16 at 2 14 19 PM](https://github.com/linode/manager/assets/125309814/26809965-552f-48c9-b6b9-cc24c675a864) |

## How to test 🧪
1. Go to a linode detail page where you see line graphs
2. You shouldn't notice any observable changes with exception of what I fixed

2023-06-16 18:36 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
> +            <Box component="span" sx={sxLabel}>
Fixed bug for LinodeEntityDetail.tsx causing console error `Cannot have a div within a p tag`

2023-06-16 18:38 UTC, jaalah-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
> +    <Grid container className={`${classes.graphGrids} p0`} xs={12} spacing={4}>
This was missing, should match what we're doing here: https://github.com/linode/manager/blob/develop/packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx#L293

2023-06-16 18:39 UTC, jaalah-akamai commented on packages/manager/src/components/LineGraph/LineGraph.tsx
> +
Didn't think these warranted using `styled` api

2023-06-16 19:21 UTC, bnussman-akamai approved these changes
Nice! Thank you for fixing the Linodes Details page, it was driving me nuts 🌰

2023-06-16 19:34 UTC, bnussman-akamai requested changes
Testing BanksBot

2023-06-16 19:37 UTC, bnussman-akamai approved these changes

2023-06-20 15:52 UTC, cpathipa approved these changes

2023-06-20 16:23 UTC, merged