Refactor: [M3-6522-copy-tooltip] CopyTooltip: Styled component and v7 story
linode/manager pull request #9323
Opened 2023-06-27 16:12 UTC by abailly-akamai

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-06-27 16:15 UTC, abailly-akamai commented on packages/manager/src/components/Chip.stories.tsx
> +  title: 'Components/Chip',
Fixing from a previous PR since we decided not to deal with the concept of `core` components

2023-06-27 17:51 UTC, bnussman-akamai approved these changes

2023-06-28 15:43 UTC, hana-linode requested changes
Seems like there's some visual regressions for the IP Address text color on the Linode's landing page/network tab and Nodebalancers detail summary page

Prod
![Screenshot 2023-06-28 at 11 33 50 AM](https://github.com/linode/manager/assets/115299789/3033fd28-6ade-4096-871f-0cae83a30ec3)

This branch
![Screenshot 2023-06-28 at 11 33 42 AM](https://github.com/linode/manager/assets/115299789/e4740b97-6b46-43f7-8ca6-7e6e8542b016)

2023-06-29 18:34 UTC, hana-linode approved these changes
LGTM!

2023-06-30 15:03 UTC, merged