fix: [M3-5577] - Disable delete button for public IP addresses
linode/manager pull request #9332
Opened 2023-06-27 21:41 UTC by hana-linode

## Description 📝
Disable delete button for public IP addresses if it's the only IP address and display a tooltip

## Preview 📷
![image](https://github.com/linode/manager/assets/115299789/0648b4f1-5277-45e2-b4ee-9b429e44133d)

## How to test 🧪
Check the Network tab of a Linode's details page

2023-06-27 22:00 UTC, bnussman-akamai requested changes
I see the Tooltip on private IPv4s

![Screenshot 2023-06-27 at 5 58 44 PM](https://github.com/linode/manager/assets/115251059/09c2097b-5043-4ce6-be97-69300ee93353)

2023-06-28 18:11 UTC, bnussman-akamai approved these changes
Works well! 

Unrelated to your work but I pray there is a day where Linodes are not required to have a public IP

2023-06-29 19:54 UTC, mjac0bs approved these changes

2023-06-29 20:12 UTC, dwiley-akamai approved these changes

2023-06-29 21:19 UTC, merged