refactor: [M3-6434] - Improve reusability for ActionPanel component
linode/manager pull request #9341
Opened 2023-06-29 16:47 UTC by cpathipa

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-07-07 15:42 UTC, cpathipa commented on packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
> -        </ActionsPanel>
We don't need to wrap the Typography within the ActionsPanel; it can be placed outside of it.

2023-07-07 15:42 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
> +        )}
Followed the same pattern, But, this could be consistent with other button tooltip.

2023-07-07 15:42 UTC, cpathipa commented on packages/manager/src/features/Volumes/VolumeDrawer/VolumesActionsPanel.tsx
>  import * as React from 'react';
We could replace entire `VolumesActionsPanel` with `ActionsPanel`.

2023-07-10 17:06 UTC, jaalah-akamai commented on packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
> +  primaryButtonCompactY?: boolean;
This is never passed down to the button, so we can probably remove the X/Y here.

What do we think of just spreading these props instead of being so explicit? I was thinking maybe `primaryButtonProps` and `secondaryButtonProps` that we spread to each button.

2023-07-12 03:04 UTC, jaalah-akamai commented on packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
> +    showSecondary: secondary,
I think you forgot about this

2023-07-14 14:59 UTC, abailly-akamai reviewed
I did not see any regression in all the ones I saw, but I probably missed a bunch. I think that a successful e2e suite adds confidence for this PR.

That being said I'd like to see a unit test for the component since the prop change is very consequent

2023-07-14 14:59 UTC, abailly-akamai commented on packages/manager/cypress/support/util/promises.ts
> +};
Can you describe the changes in this file?

2023-07-14 15:00 UTC, abailly-akamai commented
@cpathipa you also probably want to rebase with develop to get the latest e2e improvements

2023-07-19 12:25 UTC, cpathipa commented on packages/manager/cypress/support/util/promises.ts
> +};
Initially, it has prettier formatting. However, with a rebase, there are no changes here.

2023-07-19 12:27 UTC, cpathipa commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/EditIPRDNSDrawer.tsx
> +import ActionsPanel from 'src/components/ActionsPanel/ActionsPanel';
This is fixed.

2023-07-19 21:28 UTC, abailly-akamai approved these changes
Looks good to me! Approving pending passing e2e - 

also, you also may want to rebase to fix your type error (fixed in develop)

2023-07-19 21:28 UTC, abailly-akamai commented on packages/manager/src/components/Drawer/Drawer.stories.mdx
FYI There's another story refactoring drawer (that will remove the mdx file)

2023-07-19 21:33 UTC, jaalah-akamai approved these changes
Thanks for tackling this. @jdamore-linode is it ok to commit `kernals.json` and `regions.json`?  I don't think it would matter, but let me know

2023-07-20 12:17 UTC, jdamore-linode commented
> Thanks for tackling this. @jdamore-linode is it ok to commit `kernals.json` and `regions.json`? I don't think it would matter, but let me know

@jaalah-akamai I _think_ it's ok:

- This data comes from a public API endpoint, so as far as I know there's no risk of leaking DCs or Images that are only available for internal testing
- These files get regenerated when `yarn build` runs during the build/deploy, so it shouldn't have _any_ impact on the cached data used for cloud.linode.com
- I've committed and merged these before and nothing bad has ever come from it

... However, I seem to remember there being a PR opened within the past few weeks where these files were modified, and it was asked that they be removed from the PR. I can't remember the nature of that PR or who that ask might've come from (I might be misremembering altogether) so it might be safer to double check with John.

2023-07-20 15:53 UTC, bnussman-akamai requested changes
I should have weighed in earlier but I'm not sure if this is the best route to go. This solution does not feel very flexible to me having to define all of these props like this.

```tsx
// This PR
<ActionsPanel
  primaryButtonDataTestId="submit"
  primaryButtonDisabled={disabled || !formik.dirty}
  primaryButtonLoading={formik.isSubmitting}
  primaryButtonText="Save Changes"
  primaryButtonType="submit"
  secondaryButtonDataTestId="cancel"
  secondaryButtonHandler={onClose}
  secondaryButtonText="Cancel"
  showPrimary
  showSecondary
/>
```

Are there any reasons not to organize the props like this? 

```tsx
// Alternative
<ActionsPanel
  primaryButton={{
    children: "Save Changes",
    isLoading: formik.isSubmitting,
    disabled,
  }}
  secondayButton={{
    children: "Cancel",
    onClick: onClose,
  }}
/>
```

2023-07-20 16:09 UTC, cpathipa commented
> ```tsx
> onClick
> ```

I don't have any strong opinions, and I think that route make sense to me. @jaalah-akamai  is also aligned with that approach, will make the changes accordingly.

2023-07-20 16:09 UTC, cpathipa commented
> I should have weighed in earlier but I'm not sure if this is the best route to go. Are there ways to do this cleaner?
> 
> ```tsx
> // This PR
> <ActionsPanel
>   primaryButtonDataTestId="submit"
>   primaryButtonDisabled={disabled || !formik.dirty}
>   primaryButtonLoading={formik.isSubmitting}
>   primaryButtonText="Save Changes"
>   primaryButtonType="submit"
>   secondaryButtonDataTestId="cancel"
>   secondaryButtonHandler={onClose}
>   secondaryButtonText="Cancel"
>   showPrimary
>   showSecondary
> />
> ```
> 
> Are there any reasons not to organize the props like this?
> 
> ```tsx
> // Alternative
> <ActionsPanel
>   primaryButton={{
>     children: "Save Changes",
>     isLoading: formik.isSubmitting,
>     disabled,
>   }}
>   secondayButton={{
>     children: "Cancel",
>     onClick: onClose,
>   }}
> />
> ```

I don't have any strong opinions, and I think that route make sense to me. @jaalah-akamai  is also aligned with that approach, will make the changes accordingly.

2023-07-20 17:02 UTC, abailly-akamai commented
@bnussman-akamai @cpathipa didn't think of that, it's a much clearer API indeed - we should def consider this change

2023-07-24 14:36 UTC, cpathipa commented
@bnussman-akamai @jaalah-akamai Refactored and organized the props, PR is ready for re-review.

2023-07-25 15:27 UTC, bnussman-akamai reviewed
This is looking a lot better to me! I left one question about the purpose of `showPrimary` and `showSecondary`.

2023-07-25 15:27 UTC, bnussman-akamai commented on packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
> +      showSecondary
Do we need `showPrimary` and `showSecondary`? 

If we don't want to render a secondary button, can't we just not pass `secondaryButtonProps`? Is there a situation where were passing `secondaryButtonProps` but not specifying `showSecondary`?

2023-07-25 17:23 UTC, bnussman-akamai commented on packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
> +      showSecondary
Got it. In that cause, I think we should make one of the following changes:

1. Make `showPrimary` and `showSecondary` default to true so they don't have to be specified every time `<ActionsPanel />` is used 
2. Change `showPrimary` and `showSecondary` to `hidePrimary` and `hideSecondary`
3. Don't have show/hide props and just pass undefined if we want to "hide" a button (enable below)


```typescript
         <StyledActionsPanel
              primaryButtonProps={
                forEdit
                  ? {
                      'data-testid': 'save-config',
                      disabled,
                      label: 'Save',
                      loading: submitting,
                      onClick: onSave,
                    }
                  : undefined
              }
              secondaryButtonProps={
                forEdit || configIdx !== 0
                  ? {
                      'data-testid': 'delete-config',
                      disabled,
                      label: 'Delete',
                      onClick: props.onDelete,
                    }
                  : undefined
              }
            />
```

2023-07-25 19:08 UTC, cpathipa commented on packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
> +      showSecondary
Yea, Option3 makes sense to me. IMO, first two are inverse of existing way.

2023-07-25 19:41 UTC, bnussman-akamai commented on packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
> +export default RenderGuard(ActionsPanel);
One more thing, sorry!! Let's remove the default export

2023-07-25 21:19 UTC, cpathipa commented on packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
> +export default RenderGuard(ActionsPanel);
Removed default export, But not sure lifting RenderGuard cause any regressions.

2023-07-26 16:33 UTC, merged