fix: [M3-6499] - Entity links in notification menu/events page
linode/manager pull request #9387
Opened 2023-07-11 18:15 UTC by hana-linode

## Description 📝
- Clicking on entity links in the notification menu no longer causes a hard refresh
  - Previously, the links were just `a` tags so they weren't connected with the react-router-dom. The fix was to use the `Link` component which required some refactoring to get `eventMessageGenerator` to return JSX instead of a string
- Fix backticked word display on the event page
- Fix fake entity links that shouldn't be links
- Remove extra space and quotation marks from support message link

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![event page before](https://github.com/linode/manager/assets/115299789/120695ef-f508-41d2-b06c-8181eac50f03) | ![event page after](https://github.com/linode/manager/assets/115299789/7e378fb1-d21b-48d1-9460-9a433072389d) |

## How to test 🧪
```
yarn test eventMessageGenerator
```

- Check various events in the notification menu and event page
- Ensure that previous known regressions are not present e.g.
  - #9280
  - #9360

2023-07-11 19:21 UTC, hana-linode commented on packages/manager/src/eventMessageGenerator.tsx
> +    return applyLinkingAndBolding(e, messageWithUsername, bold);
With these new changes, I don't think we need to wrap the code in a try/catch block since we're not doing any fancy regex anymore, but curious to hear the team's thoughts

2023-07-11 19:21 UTC, hana-linode commented on packages/manager/src/eventMessageGenerator.tsx
> +) => {
Sorry in advance for this ugly code 😅

This was the best solution I could come up with to turn a string into JSX without bringing in a new library/package

2023-07-11 21:15 UTC, jaalah-akamai commented on packages/manager/src/eventMessageGenerator.test.tsx
> +      expect(container.firstElementChild).toContainHTML('<code>foo</code>');
Instead of `{container}` do search the DOM, can't we use `getByRole('code')`?

2023-07-11 21:15 UTC, jaalah-akamai commented on packages/manager/src/eventMessageGenerator.test.tsx
> +      expect(container.firstElementChild).toHaveTextContent(message);
Same here, let see if we can use a RTL query

2023-07-11 21:15 UTC, jaalah-akamai commented on packages/manager/src/eventMessageGenerator.tsx
> +              <strong key={word}>{word}</strong>{' '}
We should add the index to the key in case we have similar words to avoid conflict. This is for every case as well

2023-07-11 21:15 UTC, jaalah-akamai commented on packages/manager/src/eventMessageGenerator.tsx
> +              <code>{word.substring(1, word.length - 1)}</code>{' '}
I think we would need a key here

2023-07-11 21:21 UTC, hkhalil-akamai commented on packages/manager/src/eventMessageGenerator.tsx
> +) => {
Parsing is notoriously one of the most difficult challenges in computer science so it's no surprise the code gets pretty gnarly here. While I think this works for the most part, I wonder how this could be made more readable, especially if we need to add more rules/functionality in the future.

It may be easier to process the message in 'passes', such as a bolding pass, linking pass, and <code> pass in three separate functions. This will allow being more specific in how the message is split up (e.g., for the <code> pass, instead of splitting word-by-word, the message could be split to focus on sections wrapped in the backtick).

2023-07-11 21:21 UTC, jaalah-akamai commented on packages/manager/src/eventMessageGenerator.tsx
> +  bold = false
I think it's a good habit that when function parameters are more than two, to this into an object so that we have some context for what's being passed in. If we ever need to extend this or make something optional in the future we'll have that flexibility

2023-07-11 21:36 UTC, hkhalil-akamai requested changes
Great work at accomplishing a very technically complicated task.

Noticing some issues in testing:

1. The `formatEventWithAppendedText` function adds anchor tags to the messages in some cases (i.e., "Snapshot backup failed" from #9364), causing raw HTML to appear in the event message

    - Screenshot: ![Screenshot 2023-07-11 at 5 30 16 PM](https://github.com/linode/manager/assets/122488130/3585605a-6211-4e65-aafa-15de565be2fb)
    - It might be best to update that function to return `string | JSX` instead of inline HTML


2. There can sometimes be spaces inside of backticks (e.g., TXT domain records), causing the `<code>` formatting to break
    - Screenshot:  ![Screenshot 2023-07-11 at 5 32 43 PM](https://github.com/linode/manager/assets/122488130/9ba701b7-8df7-47fb-b003-de6ad096c5df)
    - This might be complicated to fix using the current word-by-word approach. See my suggestion about using multiple passes as an alternative

3. There can sometimes be backticks within entity labels and even within other backticks
    - E.g., TXT records or support ticket titles can contain backticks
    - I'm not sure we can do much here besides ensuring starting backticks have a matching ending backtick, since the API does not sanitize user-specified labels to be free of Markdown (so it's impossible to distinguish a user-specified backtick from a backtick added by the API)

2023-07-11 21:39 UTC, hkhalil-akamai commented
Unrelated to this PR specifically, I'm not very keen on the way we format event messages in general between the API and the frontend. This PR makes a good attempt at improving that functionality but I think we need to fundamentally rethink how we do this.

My opinion on the best approach would be to generate the messages ourselves on the FE, using the event data like entity id, action, etc. This avoids needing to parse at all.

2023-07-11 21:43 UTC, hkhalil-akamai commented
Do we want to include formatting in the `EventsLanding` component? Previously, things like bolding and `<code>` formatting only appeared in the menu and not in the EventsLanding, although I'm not sure if that was intentional.

2023-07-11 23:07 UTC, jaalah-akamai commented
> My opinion on the best approach would be to generate the messages ourselves on the FE, using the event data like entity id, action, etc. This avoids needing to parse at all.

This isn't a bad idea if all the parts are coming from the api already. Probably a discussion for our cafe

2023-07-17 18:38 UTC, hana-linode commented
Closing this for now as these changes introduce more issues than it fixes and we want to go in a direction where we do not parse the messages. An epic (M3-6891) has been created to look into refactoring event messaging more holistically.

2023-07-17 18:38 UTC, closed without merging