refactor: [M3-6260] - MUI v5 Migration - SRC > Features > Backups
linode/manager pull request #9438
Opened 2023-07-21 18:58 UTC by tyler-akamai

## Description 📝
- MUI style migration for Backups feature

## Major Changes 🔄
### BackupsTable
- [x] Remove React.FC and rename interface 'Props' to '{ComponentName}Props'  
- [x] You can remove 'CombinedProps' if it's directly referencing Props with nothing additional  
- [x] Export component inline, and remove 'export default {ComponentName}' at bottom of file. You will have to fix the exports/imports throughout the project where it's used  
- [x] Any style attributes can be converted to 'sx prop' or 'styled API'

### BackupsCTA
- [x] Remove React.FC and rename interface 'Props' to '{ComponentName}Props'  
- [x] Remove makeStyles for new styled API. We typically use 'Styled ComponentName) as our prefix  
- [x] Export component inline, and remove 'export default {ComponentName}' at bottom of file. You will have to fix the exports/imports throughout the project where it's used  
- [x] Any style attributes can be converted to 'sx prop' or 'styled API'
- [x] The `button` element can probably use `components/Button/StyledLinkButton.ts`
- [x] The close `button` can probably use `import { IconButton } from 'src/components/IconButton';`

### BackupsLinode
- [x] Remove React.FC and rename interface 'Props' to '{ComponentName}Props'  
- [x] Export component inline, and remove 'export default {ComponentName}' at bottom of file. You will have to fix the exports/imports throughout the project where it's used  
- [x] Any style attributes can be converted to 'sx prop' or 'styled API'

### AutoEnroll
- [x] Remove React.FC and rename interface 'Props' to '{ComponentName}Props'   
- [x] Export component inline, and remove 'export default {ComponentName}' at bottom of file. You will have to fix the exports/imports throughout the project where it's used  
- [x] Any style attributes can be converted to 'sx prop' or 'styled API'

### BackupDrawer
- [x] Remove React.FC and rename interface 'Props' to '{ComponentName}Props'  
- [x] Export component inline, and remove 'export default {ComponentName}' at bottom of file. You will have to fix the exports/imports throughout the project where it's used  
- [x] Any style attributes can be converted to 'sx prop' or 'styled API'
- [x] Convert this to a functional component

## Preview 📷
Before:
![Screenshot 2023-07-21 at 1 33 26 PM](https://github.com/linode/manager/assets/139489745/93fe001a-5e6d-41c0-9dad-8472a25ff98b)

![Screenshot 2023-07-21 at 1 32 09 PM](https://github.com/linode/manager/assets/139489745/45f2d666-5fa3-446c-b132-2a2011491696)

After:
![Screenshot 2023-07-21 at 1 32 51 PM](https://github.com/linode/manager/assets/139489745/193d229e-9f76-4422-9971-03e9a9cff5a1)

![Screenshot 2023-07-21 at 1 31 38 PM](https://github.com/linode/manager/assets/139489745/6e309a7f-8819-4059-a4b5-49a7f991adda)

## How to test 
Navigate to the Linodes page. There should be a popup on the top of the screen that says "Enable Linode Backups to protect your data and recover quickly in an emergency."
![Screenshot 2023-07-21 at 1 11 01 PM](https://github.com/linode/manager/assets/139489745/9b8c9cd4-2848-416e-b13e-321bb5324657)

If you dont have it:
This means you previously clicked 'x' so it doesn't pop-up anymore. An easy work around is to go into BackupsCTA.tsx line 49, and change "isDismissed" to "!isDismissed". The pop-up should now be there. Hit "x" one more time in the pop-up, and go back and get rid of the '!' before isDismissed. This is the only work around I have found so far. I haven't been able to find a way to bring the pop-up back within Cloud Manager.

Make sure the side panel pops up and you can sign up for backups for the correct Linodes. Also make sure the styling is consistent with the dev branch.

**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-07-25 01:57 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/AutoEnroll.tsx
> +const StyledTypography = styled(Typography)(({ theme }) => ({
Let's add a label to each of these styled components.
```
const StyledDiv = styled('div', {
   label: 'StyledDiv`
})(({ theme }) => ({
  ...
}));
```

2023-07-25 02:41 UTC, jaalah-akamai requested changes

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  } = props;
Let's move these props to the top of the function

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +    const { autoEnroll, enableSuccess, updatedCount } = props;
You almost never want to define props inside a `useEffect` because that can cause side effects. Just group them with the other props at the top of the function

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +};
This entire method should live within the functional `BackupDrawer` component and can be simplified:
```
const handleSubmit = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (accountSettings.data?.backups_enabled) {
      enable();
    } else {
      enroll(accountSettings.data?.backups_enabled ?? false, props.queryClient);
    }
  };
```

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +              onClick={(e) => handleSubmit(e, props)}
After moving the method you can just pass `onClick={handleSubmit}`

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +              {getFailureNotificationText(updatedCount, enableErrors.length)}
I know you didn't write this, but it's a good habit to learn - updating the method to accept an object for parameters will not only make it more flexible/extensible, but also help others understand what these arguments are doing:
```
const getFailureNotificationText = ({
  failedCount,
  successCount,
}: FailureNotificationData) => { ... }
```

Invocation
```
getFailureNotificationText({
    failedCount: updatedCount,
    successCount: enableErrors.length,
})
```

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  );
We can do the same here by updating the function definition/invocation to be a bit more clear

2023-07-25 02:41 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +      props.linodesWithoutBackups.some(
You can destructure `props.linodesWithoutBackups` and `props.enqueueSnackbar`

2023-07-25 02:54 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  }, []);
I don't think `updateRequestedTypes` even does anything... we could probably just remove this and it's function definition.

2023-07-25 02:55 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  }, []);
cc: @bnussman-akamai @DevDW for a second opinion

2023-07-25 03:14 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupLinodes.tsx
> +                      sx={(theme: Theme) => ({
Here you can use the `useTheme` hook from MUI and just pass in the object.
```
import { useTheme } from '@mui/material/styles';

export const BackupLinodes = (props: BackupLinodesProps) => {
    const theme = useTheme();
}
```
```
<Typography
    ...
    sx={{ 
        color: theme.color.red,
        fontSize: 13,
    }}
>
```

2023-07-25 03:14 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupsCTA.styles.ts
> +}));
Would we be able to spread `...StyledLinkButton({ theme })` here instead?

2023-07-25 19:25 UTC, dwiley-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  }, []);
I think it's necessary. Right now something is broken which is resulting in this:

![Screenshot 2023-07-25 at 3 20 54 PM](https://github.com/linode/manager/assets/114682940/d58f98d3-6f2e-475c-8969-87aec6714d4c)

The unknown/unavailable parts are being displayed because types aren't being fetched and passed to `addTypeInfo()`.

Once that's fixed `updateRequestedTypes()` would run upon drawer open and update whichever linodes are in the table so that the unknown/unavailable parts are replaced with the real data

2023-07-26 20:19 UTC, tyler-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +            {linodeCount > 1 ? 'Linodes' : 'Linode'}.
Interesting, how were you able to popup the sidebar with 0 eligible backup Linodes. From my knowledge, there are two ways you can access the sidebar. Either in the Linodes tab or the account --> settings page. Both options for me atleast get disabled when I dont have any eligible Linodes to backup.

2023-07-26 21:30 UTC, dwiley-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +            {linodeCount > 1 ? 'Linodes' : 'Linode'}.
This really happened as a testing quirk; my account didn't have any eligible Linodes but I modified the logic to display the banner no matter what so I could test the PR.

I doubt this would actually be encountered in the wild, but it'd be a good piece of cleanup. That line of code probably predates our implementation of `pluralize` in the codebase.

2023-07-27 14:07 UTC, bnussman-akamai commented on packages/manager/src/features/Backups/AutoEnroll.tsx
> +  marginTop: theme.spacing(1) + theme.spacing(0.5),
`theme.spacing()` returns a `string` so this code would result in `marginTop: 8px4px`. Do we want to change this to

```suggestion
  marginTop: theme.spacing(1.5),
```

2023-07-28 16:13 UTC, dwiley-akamai commented on packages/manager/src/features/Backups/BackupLinodes.tsx
> +              <TableRow data-qa-linodes data-testid="backup-linode-table-row">
Do we still need `data-qa-linodes` here? Doesn't look like it's being used in the test anymore

2023-07-28 17:37 UTC, tyler-akamai commented on packages/manager/src/features/Backups/BackupLinodes.tsx
> +              <TableRow data-qa-linodes data-testid="backup-linode-table-row">
I noticed that as well, I left it just in case we wanted to use it in the future but I can get rid of it.

2023-08-01 16:19 UTC, jaalah-akamai commented on packages/manager/src/features/Backups/BackupDrawer.tsx
> +  const prevProps = React.useRef(props);
Let's use our hook for this `usePrevious`, and we only need to store `linodesData`.
`const prevLinodesData = usePrevious(linodesData);`

2023-08-04 13:10 UTC, bnussman-akamai approved these changes

2023-08-05 01:00 UTC, jaalah-akamai approved these changes

2023-08-05 14:25 UTC, merged