feat: [M3-6944]: Add Firewalls table to `Linode Details > Network` tab
linode/manager pull request #9470
Opened 2023-07-28 20:11 UTC by dwiley-akamai

## Description 📝
Add Firewalls table to `Linode Details > Network` tab.

## To-Do:
- [ ] Logic cleanup + general cleanup
- [ ] Squash bugs

## Major Changes 🔄
Coming soon

## Preview 📷
Coming soon

## How to test 🧪
Coming soon

2023-08-08 20:33 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls.tsx
> +  } as unknown) as FirewallHandlers;
The casting is not ideal, but seemed to be the lesser evil compared to unnecessarily adding `triggerDeleteFirewall: () => null` etc. within this object (to match `ActionHandlers` from `FirewallActionMenu.tsx`). This is also a one-off so modifying the original `ActionHandlers` to make those optional didn't seem like the best course of action.

2023-08-08 21:47 UTC, bnussman-akamai reviewed
Things generally look good! 

I do feel like we added complexity by trying to make the FirewallRow and FirewallActionMenu work for this new table. I almost feel like it would be worth just making a new Row and Action menu for this table. This was we could avoid the `as unknown) as FirewallHandlers;`, the `predefinedActions` logic, and `onLinodeNetworkTab` logic. I'm always on the fence about this kind of thing. I'm just trying to find the solution that is simpler and easier to consume, even if it's at the cost of more lines of code and duplicate code. I'd be curious to hear other opinions.

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
> +      ]);
This logic should live in the `useRemoveFirewallDeviceMutation` `onSuccess` function in `packages/manager/src/queries/firewalls.ts`. Also, I don't think we should invalidate conditionally. We **always** want that query invalidated.

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
> +              firewallStatus === ('enabled' as FirewallStatus)
Remove this `as` cast while we're here. No idea why it's there.

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls.tsx
> +          <Grid className="p0">
Delete this `Grid`

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls.tsx
> +      <StyledDiv>
I think we should replace this div that has `marginTop` with a `<Stack>` that wraps all if this stuff

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls.tsx
> +        >
This whole StyledGrid seems overkill, can we simplify it?

```suggestion
      <Box bgcolor={theme.color.white} display="flex">
```

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls.tsx
> +            <StyledHeadline variant="h3">Firewalls</StyledHeadline>
Optional: use sx insted of styled for this typography.

2023-08-08 21:47 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
> +            // eslint-disable-next-line no-unused-expressions
Remove this eslint warning. I don't think it's doing anything

```suggestion
```

2023-08-09 19:24 UTC, dwiley-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
> +      ]);
We don't have the `linodeID` available in `useRemoveFirewallDeviceMutation`, so we'd either have to pass it as an argument or do something like this prior to the `return` statement in `useRemoveFirewallDeviceMutation`:

```
  // Find the ID of the Linode so we can invalidate its firewalls data as well.
  const devicesData = queryClient.getQueryData<FirewallDevice[]>([
    queryKey,
    'firewall',
    firewallId,
    'devices',
  ]);
  const thisDevice = devicesData?.find((device) => device.id === deviceId);
  const thisDeviceEntityID = thisDevice?.entity.id;
```

2023-08-09 20:15 UTC, dwiley-akamai commented
> I do feel like we added complexity by trying to make the FirewallRow and FirewallActionMenu work for this new table. I almost feel like it would be worth just making a new Row and Action menu for this table. This was we could avoid the `as unknown) as FirewallHandlers;`, the `predefinedActions` logic, and `onLinodeNetworkTab` logic. I'm always on the fence about this kind of thing. I'm just trying to find the solution that is simpler and easier to consume, even if it's at the cost of more lines of code and duplicate code. I'd be curious to hear other opinions.

Same, it could go either way – happy to undo those changes and make a new row and action menu for this use case if there's consensus for that

2023-08-09 21:37 UTC, hana-linode commented
Agreed with Banks. I really don't like the added complexity of the `predefinedActions` and `onLinodeNetworkTab` logic. Let's make a new row and action menu component

2023-08-09 21:40 UTC, hana-linode requested changes
Adding a Firewall doesn't seem to update the table in the Linode Network tab w/o a hard refresh

(linode was deleted after this)

https://github.com/linode/manager/assets/115299789/eeee2bc0-5738-49dd-bdef-a4565ff038ec

2023-08-11 21:33 UTC, dwiley-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
> +    queryClient.refetchQueries([
Doing a `refetchQueries` instead of an `invalidateQueries` here to avoid a split-second display of old data on the Linode Network tab in the following flow: visit the Network tab of a Linode assigned to a firewall --> go to the Firewall Details page and unassign that Linode --> go back to the Linode Network tab

2023-08-14 14:07 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/LinodeFirewalls.tsx
> +          }}
This was we can avoid needed the `useTheme` hook.

```suggestion
          sx={(theme) => ({
            lineHeight: '1.5rem',
            marginBottom: theme.spacing(),
            marginLeft: '15px',
            marginTop: theme.spacing(),
          })}
```

2023-08-14 19:12 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
> +    queryClient.refetchQueries([
The "split second" issue is pretty consistent throughout the app so I think we should continue to use `invalidateQueries `.

2023-08-14 20:41 UTC, dwiley-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
> +    queryClient.refetchQueries([
Reverted back to `invalidateQueries`.

Having the logic here is cleaner than in `useRemoveFirewallDeviceMutation` because we'd have to get the `linodeId` to be available in there some way (see [PR comment](https://github.com/linode/manager/pull/9470#discussion_r1289099517)).

2023-08-15 19:09 UTC, hana-linode reviewed
Functionality LGTM. Looks like there's a merge conflict with develop now

Can we have the linode link in `https://github.com/linode/manager/blob/develop/packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx#L22` link to the networking tab?

2023-08-15 19:09 UTC, hana-linode commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx
> +    );
Can we use the `getPermissionsForLinode` function instead?

2023-08-15 19:09 UTC, hana-linode commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
> +    );
Same here

2023-08-16 14:51 UTC, hana-linode approved these changes
🚀

2023-08-16 15:04 UTC, bnussman-akamai approved these changes

2023-08-16 15:16 UTC, merged