M3-6614 Add Cypress tests for Linode landing page 'Summary View'
linode/manager pull request #9477
Opened 2023-08-01 16:49 UTC by cliu-akamai

## Description 📝
Add Cypress tests for Linode landing page "Summary View" button

## Major Changes 🔄
- Add test to verify "Summary View" button works as expected.

## How to test 🧪
`yarn cy:run -s "cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts"`

2023-08-01 18:55 UTC, jaalah-akamai approved these changes

2023-08-01 21:02 UTC, cpathipa approved these changes

2023-08-02 17:34 UTC, jdamore-linode commented
@cliu-akamai I'm hoping to take a look at this before you merge if you wouldn't mind waiting, I've been held up by region testing but am hoping to look at this today

2023-08-03 14:20 UTC, jdamore-linode requested changes

2023-08-03 14:20 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
> +        .parent()
I think in this case adding a `data-qa` attribute would be better: it's difficult to tell which element is being selected here, and it's a little bit fragile to changes that could be made to the component.

Instead, I'd add the following data attribute to the component in `src/features/Linodes/LinodesLanding/CardView.tsx` `ln 92`:

```tsx
// Currently: <Grid className={`${classes.summaryOuter} py0`} xs={12}>
<Grid className={`${classes.summaryOuter} py0`} xs={12} data-qa-linode-card={linode.id}>
```

Then, in the test, you can select the card like this:

```typescript
cy.findByText(linode.label)
  .should('be.visible')
  .closest('[data-qa-linode-card]')
```

2023-08-04 19:18 UTC, jdamore-linode approved these changes

2023-08-08 17:47 UTC, merged