feat: [M3-6787] - Update LKE HA implementation
linode/manager pull request #9489
Opened 2023-08-03 17:54 UTC by carrillo-erik

## Description 📝
Replaces the former HA Checkbox with a Radio Group and moves the HA Control Plane away from the KubeCheckoutBar into the main content.

## Major Changes 🔄
- New `HAControlPlane` component consisting of a `RadioGroup` forcing users to make an active selection for HA
- Remove `HACheckbox` component from the `KubeCheckoutBar` component in the sidebar.
- User's choice to either opt-in or opt-out of HA is now required to create a Cluster.

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![beforeChanges](https://github.com/linode/manager/assets/119514965/6b92eb5d-1f9b-4503-96bb-53818f0e7613) | ![afterChanges](https://github.com/linode/manager/assets/119514965/a6165fd5-9b12-44ca-8a61-3e64d549daaa) |

## How to test 🧪
1. Visit the `kubernetes/create` landing page and inspect for any UI defects.
2. Test the functionality of the new `HAControlPlane` component.
3. Verify that LKE HA flow works as expected.

2023-08-03 18:09 UTC, mjac0bs commented
Something is slightly off with the form... I'm seeing the "HA Control Plane" label selected in blue when the radio selection is toggled. Clicking far outside the button also seems to toggle the selection. 

https://github.com/linode/manager/assets/114685994/b13fb0d4-bb21-4f21-9caa-8c60a1ce3a4a

2023-08-03 18:13 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +  ] = React.useState<boolean>(false);
Rather than having two states, maybe we could just have one state that is `boolean | null` and `null` would imply no selected has been made yet.

Also, somewhat related and this might be out of the scope of your changes, but... I think in general we decided that Create buttons on forms should **not** never disabled so that the user can get validation. As the form sits right now, I think it could be confusing that the Create button is disabled if no HA decision was made. 

https://github.com/linode/manager/assets/115251059/45110f8d-0578-449c-a531-c71d92cb8111

2023-08-03 20:37 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +  ] = React.useState<boolean>(false);
@bnussman-akamai Thanks for identifying this issue. I've pushed a fix for this now. As for the disabled state of the create button, that's one of the asks for this ticket. We want users to make an active selection for opting-in or opting-out of HA. The default state for the HA control panel is meant to be unchecked, however, that presents an issue with the current types. I found it easier to create a new value to keep track of the user choice for this purpose . 

Also, this brings up the discussion of whether to use checkboxes vs radio buttons. Take a look at this quick resource https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/. 

Also, if you take a look at the JIRA ticket, there's a link to a Slack thread where this decision was made from a business and ux perspective.

Now, that I've shared this extra information, I'm happy to discuss this further and make any changes that are deemed appropriate.

2023-08-04 17:23 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +  ] = React.useState<boolean>(false);
Good with me if UX is okay with it! I still feel that not letting the user get validation feedback by clicking the Create button is a bit bad and breaks our pattern. 

My feedback about two states still stands. I think it can be consolidated into one.

2023-08-04 20:24 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
> +    }
```suggestion
      setHighAvailability(e.target.value === 'yes');
```

2023-08-04 20:24 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
> +          id="ha-radio-buttons-group-label"
Optional, but instead of using the `useTheme` hook, you can pass a function to `sx`, which exposes the theme.

```suggestion
          sx={(theme) => ({
            '&&.MuiFormLabel-root.Mui-focused': {
              color: theme.name === 'dark' ? 'white' : theme.color.black,
            },
          })}
          id="ha-radio-buttons-group-label"
```

2023-08-04 20:29 UTC, bnussman-akamai approved these changes

2023-08-04 20:29 UTC, bnussman-akamai commented on packages/api-v4/src/kubernetes/types.ts
> +  high_availability: boolean | undefined;
Now that I think about it, this notation might be more appropriate, although they accomplish the same thing. 

```suggestion
  high_availability?: boolean;
```

2023-08-04 21:10 UTC, carrillo-erik commented on packages/api-v4/src/kubernetes/types.ts
> +  high_availability: boolean | undefined;
Yeah, this makes sense.

2023-08-04 21:11 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
> +          id="ha-radio-buttons-group-label"
I went ahead and removed the `useTheme` hook. Less things to import.

2023-08-04 21:12 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
> +    }
Good suggestion!

2023-08-08 18:20 UTC, jdamore-linode commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      (highAvailability === undefined && showHighAvailability)
This line is the source of the e2e test failures.

If `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` is `undefined`, the `<HAControlPlane />` component is correctly hidden from the Create Cluster form.

In these cases, `highAvailability` will always be `undefined` when the `<HAControlPlane />` component does not render because there's no way for the user to select either yes or no, so this condition will always resolve to `false`. Consequently, the _Create Cluster_ button always stays disabled.

This is a problem because it means that developers or users self-hosting Cloud who don't have `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` defined in their `.env` will not be able to spin up LKE clusters even if they don't need HA. `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` is not defined when building Cloud Manager for our E2E tests, which should be fixed, but LKE cluster creation should continue working even when this environment variable does not exist.

2023-08-08 20:37 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      (highAvailability === undefined && showHighAvailability)
> If `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` is `undefined`, the `<HAControlPlane />` component is correctly hidden from the Create Cluster form.

Correct, this is the expected behavior.
 
> In these cases, `highAvailability` will always be `undefined` when the `<HAControlPlane />` component does not render because there's no way for the user to select either yes or no, so this condition will always resolve to `false`. Consequently, the _Create Cluster_ button always stays disabled.

We actually do want this to resolve to `false` because that would make the boolean variable `disableCheckout` resolve to `false` as well. When `disableCheckout` is `false` the `Create Cluster` button is enabled.

> This is a problem because it means that developers or users self-hosting Cloud who don't have `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` defined in their `.env` will not be able to spin up LKE clusters even if they don't need HA.

This was my reasoning behind my latest changes to the conditional logic. I played around with this and tested it manually by negating the result from `getKubeHighAvailability(account)` and by running the e2e tests in `debug` mode. We can take a look at it together to see to identify any other scenarios to account for or different solution.

2023-08-08 20:40 UTC, jdamore-linode commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      (highAvailability === undefined && showHighAvailability)
> > In these cases, highAvailability will always be undefined when the <HAControlPlane /> component does not render because there's no way for the user to select either yes or no, so this condition will always resolve to false. Consequently, the Create Cluster button always stays disabled.
> 
> We actually do want this to resolve to false because that would make the boolean variable disableCheckout resolve to false as well. When disableCheckout is false the Create Cluster button is enabled.

Sorry -- that was a typo on my part. Because `highAvailability` is always `undefined` when the environment variable is not defined, that conditional resolves to `true` and prevents the button from becoming enabled. That's the bug.

(Also updated my original comment to reflect that)

2023-08-08 20:42 UTC, jdamore-linode commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      (highAvailability === undefined && showHighAvailability)
Reproduction steps for the bug:

1. Remove `REACT_APP_LKE_HIGH_AVAILABILITY_PRICE` from your `.env` file.
2. Build and serve Cloud Manager, preferably via `yarn && yarn build && yarn start:manager:ci`
3. Run `yarn cy:debug`, run either of the affected LKE tests, and observe that when the Create Cluster form is filled out, the submit button erroneously stays disabled and the test fails

2023-08-10 08:19 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
> +      (highAvailability === undefined && showHighAvailability)
@jdamore-linode After our discussion and a few more changes all tests (both unit and e2e) are passing. Please look at the comments I left on the `HAControlPlane.test.tsx` file and if you agree I can go ahead and remove them before merging this PR.

2023-08-10 14:23 UTC, bnussman-akamai approved these changes

2023-08-10 14:35 UTC, jdamore-linode requested changes

2023-08-10 14:35 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
> +    });
```suggestion
```

We really want to avoid adding conditional logic which alters the behavior of the test based on an environmental factor, because it creates a situation where a test running in one environment is not guaranteed to perform the same actions when performed in another environment. On a great enough scale it really hurts test maintainability because troubleshooting and modifying tests becomes more difficult (for example, if a test can do multiple things based on multiple factors, how can a developer best guarantee that their test modifications don't cause a failure under every possible condition that the test may run under?)

For now I'd suggest removing the E2E modifications -- they're not covering much that isn't already covered by the unit tests. The solution, broadly, is to have one test case that covers when HA is enabled, and another that covers when it isn't, but because of the way this constant works that really isn't feasible here.

*: The only case I'd really consider conditional logic to be acceptable in the tests is when you can guarantee that every case is covered during every run.

2023-08-10 14:35 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
> +    });
```suggestion
```
Ditto to what I said for `lke-create.spec.ts`

2023-08-10 14:35 UTC, jdamore-linode commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +import { HIGH_AVAILABILITY_PRICE } from 'src/constants';
Can we take a step back and reevaluate why `HIGH_AVAILABILITY_PRICE` has to be read from an environment variable and can't just be hardcoded in `constants.ts`? Is there ever a case where we would want HA to be unavailable or have a different price based on the environment it's built for?

If this value becomes hardcoded, all of this test complication goes away.

(cc @abailly-akamai in case he has any historical knowledge from when LKE was implemented)

2023-08-10 14:41 UTC, bnussman-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +import { HIGH_AVAILABILITY_PRICE } from 'src/constants';
LKE HA was new a few months ago and I added the `HIGH_AVAILABILITY_PRICE ` env variable based on recommendations from others. I'd prefer a constant or, hopefully soon, we can get this value from the API as part of  our upcoming pricing project.

2023-08-10 14:46 UTC, abailly-akamai commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +import { HIGH_AVAILABILITY_PRICE } from 'src/constants';
I am unsure about this, but I can only assume that the reason could be for easier value control outside of our release cycle. I am seeing the the value itself is displayed in `UpgradeClusterDialog` so I doubt it has to do with masking the value in any way. @johnwcallahan any thoughts?

2023-08-11 18:51 UTC, carrillo-erik commented
After discussing the LKE HA pricing variable issue, it was decided that at this time the e2e test coverage for HA Control Plane would be removed. An additional unit test was implemented to help mitigate any loss of coverage. A spike ticket will be created to investigate the `HIGH_AVAILABILITY_PRICE` constant variable and explore other options for maintaining it. After the spike ticket is complete, the e2e test coverage will be revisited.

2023-08-11 18:52 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> +import { HIGH_AVAILABILITY_PRICE } from 'src/constants';
I left a comment below in regards to our discussions.

2023-08-11 18:52 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
> +    });
Done.

2023-08-11 18:52 UTC, carrillo-erik commented on packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
> +    });
Made the changes as you suggested.

2023-08-11 18:53 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
> +    Recommended for prodcution workloads, a high availability (HA) control plane
👍 👀

2023-08-11 18:54 UTC, carrillo-erik commented on packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.test.tsx
> +// }));
I added a unit test for the scenario you mentioned.

2023-08-11 19:22 UTC, jdamore-linode approved these changes

2023-08-11 20:05 UTC, merged