refactor: [M3-6922] - Add Autocomplete Component
linode/manager pull request #9497
Opened 2023-08-05 04:02 UTC by jaalah-akamai

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-08-07 13:43 UTC, abailly-akamai reviewed
This is really nice and clean. Great work!

Added some comments to clean things up. 

Also, have we discussed the use of the "Autocomplete" VS "Select" nomenclature. I don't think it is a crucial discussion but I'd be curious to know why gearing towards the MUI naming convention rather than keeping our existing one

2023-08-07 13:43 UTC, abailly-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +export interface AutocompleteProps {
You are overriding a lot of MUI `Autocomplete` props which I think we should avoid to prevent breaking changes when updating MUI. Rather we should extend the MUI component's props and only declare our custom props. (same with other interfaces below)

They will be automatically picked up by storybook

2023-08-07 13:43 UTC, abailly-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const [inputValue, setInputValue] = React.useState('');
Out of curiosity, can the value be an object if (for instance) there's an icon to be displayed with the label and in the selected state? I assume this could be also an iteration

2023-08-07 13:43 UTC, abailly-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +          <li {...props}>
Could we just pass the props we need here?

2023-08-07 13:43 UTC, abailly-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  loading: boolean | undefined;
This feels a bit odd, since it should just be a boolean (pretty low on this, not sure it matters in any way)

2023-08-07 13:43 UTC, abailly-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.stories.tsx
> +      </div>
Maybe a min-height so we don't have to scroll the stories to see then options when the Autocomplete is open?

2023-08-07 13:54 UTC, jaalah-akamai commented
> This is really nice and clean. Great work!
> 
> Added some comments to clean things up.
> 
> Also, have we discussed the use of the "Autocomplete" VS "Select" nomenclature. I don't think it is a crucial discussion but I'd be curious to know why gearing towards the MUI naming convention rather than keeping our existing one

Yes, I thought about this too! The existing `EnhancedSelect` allows for typeahead interactions, so that falls within the `Autocomplete` nomenclature

2023-08-08 18:12 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const handleChange = (value: OptionsType | OptionsType[]) => {
Would it make sense to wrap this function in `React.useCallback(...)` to prevent unnecessary re-rendering?

```
const handleChange = React.useCallback((value: OptionsType | OptionsType[]) => {
  if (Array.isArray(value)) {
    // It's an array, so it's the multiple selection case
    if (!multiple) {
      return;
    }
    onSelectionChange(value);
  } else {
    // It's not an array, so it's the single selection case
    if (multiple) {
      return;
    }
    onSelectionChange(value);
  }
}, [multiple, onSelectionChange]);
```

2023-08-08 18:16 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +import { CustomPopper, SelectedIcon } from './Autocomplete.styles';
I think the customPopper styling can be simplified:

Current code:
```
export const CustomPopper = (props: PopperProps) => {
  return (
    <Popper
      {...props}
      style={{
        ...(props.style ?? {}),
        ...(props.style?.width
          ? typeof props.style.width == 'string'
            ? { width: `calc(${props.style.width} + 2px)` }
            : { width: props.style.width + 2 }
          : {}),
        zIndex: 1,
      }}
      data-qa-autocomplete-popper
      modifiers={[{ enabled: false, name: 'preventOverflow' }]}
    />
  );
};
```

i dont think you need this conditional:
```
typeof props.style.width == 'string'
            ? { width: `calc(${props.style.width} + 2px)` }
            : { width: props.style.width + 2 }
```

I think the `calc(${props.style.width} + 2px)` will work whether the width is a string or number.

2023-08-08 18:22 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +    options,
Is it a good idea to provide a default value here to prevent optional chaining?

2023-08-08 18:28 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  multiple?: false;
Why is `multiple` for `AutocompleteSingleSelectProps` optional and `multiple` for `AutocompleteMultiSelectProps` required?

2023-08-08 18:29 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +    return 'An error occurred while fetching your options';
Would it make sense to use an enum here?

2023-08-09 02:38 UTC, jaalah-akamai commented
Sorry @tyler-akamai been making major changes to this PR, I'm going to close out-of-date comments, but looking forward to your review when I put it up again!

2023-08-09 02:38 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +    return 'An error occurred while fetching your options';
Yes I agree

2023-08-09 02:40 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +import { CustomPopper, SelectedIcon } from './Autocomplete.styles';
I'm not so sure if what you suggest would work, however I cleaned this up regardless. If you have time to help me test this aspect when this PR is ready I'd appreciate it!

2023-08-09 15:22 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
So it the long-term goal to have `LinodeSelect` use this new `Autocomplete` or will `LinodeSelect` continue to import directly from MUI?

2023-08-09 20:08 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +import { CustomPopper, SelectedIcon } from './Autocomplete.styles';
Just tested it, your right, it doesnt work like that haha

2023-08-11 03:44 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +    options,
Options is required, so I don't think we need a default unless I'm misunderstanding what you're saying

2023-08-11 03:47 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +          <li {...props}>
We're type-checking that only list item properties are applied here, I'd rather keep it for flexibility.

2023-08-11 03:48 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const [inputValue, setInputValue] = React.useState('');
I'm assuming you mean like Regions selector? If so, I added an example of how to do that via the optional `data` property

2023-08-11 03:48 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +export interface AutocompleteProps {
Consider this done!

2023-08-11 03:50 UTC, jaalah-akamai commented
There's still a lot more unit tests we can write for this. I may tackle writing them in a separate PR due to my time constraints or someone on the team can pick that up. Ready for review again! 🚀

2023-08-14 20:20 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +    options,
if required then we dont need optional chaining on line 139, is that correct?

2023-09-05 17:57 UTC, dwiley-akamai approved these changes
This is looking good based on my testing 🎉

We discussed on Friday during the group review/testing that some improvements can be made for the types (e.g. the one marked `TODO` in `Autocomplete.tsx`), but I think that could be done in a follow-up PR or iteratively as we implement this component in the app.

2023-09-05 17:57 UTC, dwiley-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const [inputValue, setInputValue] = React.useState('');
To clarify, this should already be working for the selected option too? I might be missing something but in Storybook it doesn't seem like the flag gets displayed upon selecting an option.

2023-09-05 19:24 UTC, hana-linode commented on packages/manager/src/components/Autocomplete/Autocomplete.styles.tsx
> +  shouldForwardProp: (prop) => prop != 'visible',
Should we add a label here as well?

2023-09-05 19:24 UTC, hana-linode commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  errorText: APIError[] | null | string | undefined;
```suggestion
  errorText?: APIError[] | null | string;
```

2023-09-05 19:24 UTC, hana-linode commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const selectAllText = selectAllActive ? 'Deselect All' : 'Select All';
Thoughts on the term `Unselect` vs `Deselect`?

2023-09-05 19:24 UTC, hana-linode commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  }
We can unnest the ifs since each option returns out of the function
```suggestion
  if (errorText) {
    return NoOptionsMessage.Error;
  }
  if (!options?.length) {
    return NoOptionsMessage.NoOptions;
  }
  return NoOptionsMessage.NoResults;
```

2023-09-05 21:33 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const selectAllText = selectAllActive ? 'Deselect All' : 'Select All';
No preference, open to feedback

2023-09-05 21:34 UTC, jaalah-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  }
I have no preference since it's interchangeable - open to feedback from others on both conventions

2023-09-06 13:20 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  }
I would say the second one looks a little more readable.

2023-09-06 13:25 UTC, tyler-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  const selectAllText = selectAllActive ? 'Deselect All' : 'Select All';
`Dictionaries (Merriam-Webster and New Oxford American Dictionary) have deselect but not unselect. The NOAD defines deselect as “turn off (a selected feature) on a list of options on a computer menu”, which is what you want.

Unselected, on the other hand, is used to qualify something that has not been selected, not something that was selected and isn't anymore.` - https://english.stackexchange.com/questions/18465/unselect-or-deselect

I would probably go with deselect. It also seems more common across ux design.

2023-09-06 16:49 UTC, jaalah-akamai commented
Added a storybook example for having separate options as opposed to using `Tags`. 

@dwiley-akamai Adding flags to the value is not something we can do easily given the types we're restricted to. This may be one tradeoff unless we do a customized input.

2023-09-06 16:56 UTC, bnussman-akamai commented
Looks great but I have some general concerns about the typesafety of this component.

- No type safety on the `data`
- `renderInput` is required
- The `onSelectionChange` value is an array even though `multiple` is `false`

![Screenshot 2023-09-06 at 12 50 39 PM](https://github.com/linode/manager/assets/115251059/46f329c8-fb04-451d-aa93-08685fc6f58b)

None of this stuff is easy but I propose we try to align our component more with MUI's implementation
- Allow options to be any type `T`
- Use `onChange` instead of a custom `onSelectionChange`
- And so on...

2023-09-08 18:51 UTC, jaalah-akamai commented on packages/manager/src/foundations/themes/light.ts
> -          padding: 12,
This was a bug that prevented the `IconButton` `size` prop from working properly. There should be no regressions since we default to the large size which has a padding of `12` by default. https://github.com/linode/manager/pull/9497/files#diff-f767369a01cd40921dc0da8dac44cf6777e3c155f3680aa2990be0da93c2dc48R659

2023-09-08 18:52 UTC, jaalah-akamai commented
Thanks @bnussman-akamai for the review and providing an alternative solution 🎉

2023-09-08 20:04 UTC, bnussman-akamai requested changes

2023-09-08 20:04 UTC, bnussman-akamai commented on packages/manager/src/components/Autocomplete/Autocomplete.tsx
> +  required?: boolean;
I think we can remove these 3 props because `AutocompleteProps` already includes them!

2023-09-08 20:13 UTC, bnussman-akamai approved these changes
I think this is a great starting point! 🎉 We can refine this component as we use it and see what changes it may need

2023-09-08 21:36 UTC, merged