refactor: [M3-6286] - SRC > Features > TopMenu
linode/manager pull request #9498
Opened 2023-08-07 06:08 UTC by carrillo-erik

## Description 📝
MUI v5 migration for `TopMenu`. 

## Major Changes 🔄
- Ran `tss-react` codemod on `TopMenu`
- Replaced `default export` with `named export`
- Deleted `index.tsx` files
- Convert Class Components to Functional Components

## How to test 🧪
1. Inspect the `TopMenu` and encompassing components for visual regressions.
2. Complete the inspection in Step 1 under both themes, light mode and dark mode.
3. Complete the inspection in Step 1 using browser devtools for mobile devices.
4. Ensure `TopMenu` functionality works as expected.

2023-08-07 13:12 UTC, abailly-akamai reviewed
Nice! early review to clean some stuff up - will test in the browser later on

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/components/EnhancedSelect/Select.styles.ts
> -  },
The `EnhancedSelect` is widely used in CM and I am not too comfortable modifying its core styling considering it is likely to introduce regressions. Instead, you should create a `StyledEnhancedSelect` styled component of a `EnhancedSelect`  instance for your use case only

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
> +  const types = extendTypesQueryResult(typesQuery);
let's name this constant better. what types are they for?

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
> +  },
is there no way to disable the indicators via props?

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
> +      <div style={{ display: 'flex', flexFlow: 'row nowrap' }}>
You could use a <Box /> with sx rather than inline styles

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
> +        <div style={{ padding: '8px' }}>
same here

2023-08-07 13:12 UTC, abailly-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
> +}));
Probably a good idea to move this to its own .styles.ts file

2023-08-07 14:43 UTC, tyler-akamai requested changes

2023-08-07 16:27 UTC, carrillo-erik commented on packages/manager/src/components/EnhancedSelect/Select.styles.ts
> -  },
I searched the entire project to identify potential issues before removing the specific style classes. From my investigation I identified that these styles only applied to the `SearchSuggestion` component and that's why I felt comfortable in proceeding. If you believe it would be better to revert this I can go ahead and take that approach.

2023-08-08 13:03 UTC, abailly-akamai commented on packages/manager/src/components/EnhancedSelect/Select.styles.ts
> -  },
Sounds good

2023-08-08 13:08 UTC, abailly-akamai reviewed
@carrillo-erik, some comments are not addressed. Also, I found a regression with the search dropdown:

| Your PR  | Production   |
| ------- | ------- |
| ![Screenshot 2023-08-08 at 14 58 19](https://github.com/linode/manager/assets/130582365/b3063de4-35aa-4844-9e09-012ec2001f17) | ![Screenshot 2023-08-08 at 14 58 32](https://github.com/linode/manager/assets/130582365/0ad3d457-3f7a-4f5f-b5d7-ab8d87a06046) |

2023-08-08 20:41 UTC, carrillo-erik commented
I can see a green shadow around the search suggestions in the second picture but I'm not able to replicate this defect locally. I tried Chrome and FireFox and looked at different viewports sizes. Could you share how you were able to find this defect?

2023-08-09 08:37 UTC, abailly-akamai commented
@carrillo-erik the defect is the search suggestion result which seems to be a different result (or styled differently) - the title of the search result for an "east" search (if having a linode with "east" in the title is different from the result in production)

2023-08-11 15:30 UTC, carrillo-erik commented
Issue has been taken care of. Screenshot below, please inform me if you see other issues with the search.

![fix-searchbar](https://github.com/linode/manager/assets/119514965/0e860848-9a76-4397-86e4-66e360b63f21)

2023-08-14 13:20 UTC, bnussman-akamai approved these changes

2023-08-14 16:48 UTC, coliu-akamai approved these changes
looks good + tested searchbar and functionality seemed to be working as expected!

2023-08-14 20:05 UTC, tyler-akamai approved these changes

2023-08-14 20:05 UTC, tyler-akamai commented
Looks good and works good!

2023-08-14 20:07 UTC, tyler-akamai commented on packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
> +    backgroundColor: `${theme.bg.main} !important`,
just one last !important we can get rid of

2023-08-15 15:03 UTC, merged