feat: [M3 7015] - Create nodebalancer tab in firewalls landing
linode/manager pull request #9590
Opened 2023-08-24 17:52 UTC by tyler-akamai

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
- Added new NodeBalancer tab
- Added the total number of each product as an integer next to the tab label
- Added breadcrumb prefix "Assigned" to Linodes and NodeBalancers

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![Screenshot 2023-08-24 at 1 48 55 PM](https://github.com/linode/manager/assets/139489745/eb2918b5-ed3f-4ed3-89af-cab126d49cb1) | ![Screenshot 2023-08-24 at 1 49 06 PM](https://github.com/linode/manager/assets/139489745/fa2a18e9-524e-46af-9597-f909e39d6360) |
|  | ![Screenshot 2023-08-24 at 1 50 10 PM](https://github.com/linode/manager/assets/139489745/ccb8f067-da18-4deb-abeb-370d6edb9a35) |

## How to test 🧪
1. Navigate to http://localhost:3000/firewalls
2. Click on any of your firewalls
3. Ensure there is an extra NodeBalancers tab
4. Ensure the number next to the Linodes tab accurately represents the number of assigned linodes
5. Ensure the Linode tab functionality still works
6. Ensure the breadcrumb now has "Assigned [Device]", device is either a Linode or NodeBalancer

2023-08-24 19:29 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
> -            <FirewallLinodesLanding
There would be a lot of commonality between the FirewallsLinodeLanding and the FirewallsNodeBalancerLanding, so I decided to make a generic FirewallsDeviceLanding that contains either a table of Linodes or a table of NodeBalancers. If we want more customization, we might have to look into having two separate files.

2023-08-24 20:14 UTC, jcallahan-akamai requested changes
Great work @TylerWJ. 

We need to fix the breadcrumb. The "Assigned Linodes" part should not be editable. Let's check with UX to see what the options are here.

Everything else LGTM.

![Screenshot 2023-08-24 at 4 13 54 PM](https://github.com/linode/manager/assets/114753608/4959fb53-1ebe-43bf-822a-677a9ec459fa)

2023-08-25 15:29 UTC, carrillo-erik commented
Just my small change request, everything looks good to me. My other suggestion would be to add some unit tests.

2023-08-25 18:41 UTC, jcallahan-akamai approved these changes

2023-08-28 13:54 UTC, bnussman-akamai reviewed
Should we feature flag this?

2023-08-28 17:19 UTC, carrillo-erik approved these changes

2023-08-28 17:51 UTC, tyler-akamai commented
> Should we feature flag this?

I created a feature branch for all of our changes and then when we are done we will merge it into develop.

2023-08-28 18:25 UTC, merged