feat: [M3-6754] - Create new react list component
linode/manager pull request #9594
Opened 2023-08-25 13:51 UTC by coliu-akamai

## Description 📝
- created simple scrollable list 
- the majority of the logic would really be in the custom list items -- I have a version where all of this is one component, on [this branch](https://github.com/coliu-akamai/manager/tree/feat-m3-6754) that I was first working on, before feeling like this wasn't as clean as an approach that I'd hoped. In this version though, the simplicity of the Scrollable list component here makes me wonder if it's needed

## Major Changes 🔄
- Scrollable list component
- custom list items 

## Preview 📷
(this would be used for the unassign linodes drawer)
![image](https://github.com/linode/manager/assets/139280159/847eaea4-4cdc-40f2-bb52-6eabd179ca79)

(this would be used for the assign linodes drawer)
![image](https://github.com/linode/manager/assets/139280159/1cce2c9a-dc65-49a4-baf0-a8713a48b117)
![image](https://github.com/linode/manager/assets/139280159/a45113f4-1412-48ea-886c-31fa094e7d0e)

## How to test 🧪
`yarn storybook` --> ScrollableList

2023-08-28 16:03 UTC, abailly-akamai requested changes
As per my comments, the API is a little too open IMO, and makes an "everything is possible" component, which I'd like to flag. I wonder about a component that accepts "deletableItems" & "selectableItems" props and contain that logic as well. 

Also, why are we not using the multiSelect component (or a variation of it at least) which achieves all this functionality? (ex: https://cloud.linode.com/firewalls/create)

2023-08-28 17:01 UTC, coliu-akamai commented
@abailly-akamai Thanks for the feedback, and good point about the multiSelect component -- I'll ask UX about using this rather than having a new list-like component, especially if the multiSelect already has all the functionality needed. Will work on the other feedback soon too!

2023-08-28 17:37 UTC, coliu-akamai commented
@abailly-akamai spoke with UX, one of the main reasons to not use the multi-select component was due to how the selected linodes appeared at the top -- if there are too many linodes selected, it could get cluttered. Depending on a linode label's length, multiple linodes might appear on the same line of the box at the top:

![image](https://github.com/linode/manager/assets/139280159/a1b0f4ad-264a-4b7b-b5e4-f9ae514cd31e)

Might be worth looking into this component further to see if it's possible for each linode label tag to be on a separate line

2023-08-28 17:45 UTC, abailly-akamai commented
@coliu-akamai thanks for checking with UX - I think there's a disconnect between UX requirements and what we're trying to achieve here. We shouldn't have to build a whole new series of components an achieve existing functionality with a UI variation

2023-08-31 17:35 UTC, coliu-akamai commented
Closing based on 8/31 Frontend Cafe discussion as we won't be moving forward with this approach -- we will either go with [Jaalah's autocomplete](https://github.com/linode/manager/pull/9497) (which allows for multiselect) or the existing table component (similar to what's done in the Server Transfers page).

2023-08-31 17:35 UTC, closed without merging