M3-6551 Add Community Stackscripts integration tests
linode/manager pull request #9595
Opened 2023-08-25 14:57 UTC by cliu-akamai

## Description 📝
Add integration tests for Community Stackscripts.

## Major Changes 🔄
- Add test to check StackScripts are listed with expected info.
- Add test to check Pagination works as expected.
- Add test to check Search works as expected
- Add test to check Deploy flow works as expected

## How to test 🧪
`yarn cy:run -s "cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts"`

2023-08-28 15:32 UTC, abailly-akamai approved these changes
This is REALLY cool. thanks for writing this! 

I would wait for @jdamore-linode's approval before merging but you get my vote 👍

2023-08-29 20:11 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
> +      : DateTime.fromISO('1970-01-01T00:00:00.000');
I'll circle back to this first thing tomorrow morning, but on my account specifically the tests are tripping up because this time does not equal what's shown on screen.

I did confirm it's working on other accounts, so I'm assuming this has to do with the timezone set in the Profile display settings at `/profile/display`

2023-08-29 20:13 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
> +      cy.scrollTo(0, 500);
Nice solution! I was curious how difficult it would be to test the infinite scrolling pagination on this page

2023-08-31 20:37 UTC, jdamore-linode commented
@cliu-akamai Even with those changes, it's still expecting to find the incorrect date via my test account -- I think the reason is that the timezone needs to be applied when we call `formatDate()` which I think is imported but isn't used in the spec (and actually you might be able to skip `DateTime.fromISO()` altogether since I think `formatDate()` accepts an ISO formatted string anyway).

Dealing with the timezone adjusted dates in the UI is always a pain, let me know if I can help out!

2023-09-11 18:17 UTC, jdamore-linode requested changes
Hey Cassie! Just noticing there's still a failure here in CI and wanted to mark this with "Request changes" just so it doesn't get merged.

I'll catch up with you momentarily!

2023-09-13 17:02 UTC, jdamore-linode approved these changes

2023-09-13 18:40 UTC, merged