fix: MUI Theme - Base CSS Styles
linode/manager pull request #9636
Opened 2023-09-06 01:34 UTC by bnussman-akamai

## Description 📝
- Oh no! Our MUI theme isn't installed correctly! 😖
- The background color of the body is white ⚪️ in dark mode and it drives me absolutely nuts 🌰

## Major Changes 🔄
- Set missing UI theme styles
- Add `<CssBaseline />` to mount base styles

## Preview 📷

### Before ☹️

https://github.com/linode/manager/assets/115251059/b3088fa1-0e78-484d-8dab-a52049db4ea4

### After 😁

https://github.com/linode/manager/assets/115251059/6e9aa519-b56e-48ce-9a07-38931fe054f9

## How to test 🧪
- Checkout this PR
- Check that the body's background in light mode is white
- Check that the body's background is in dark mode is gray
- Check for general style regressions

2023-09-06 01:37 UTC, bnussman-akamai commented on packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
> +      fontSize: '1rem',
Fixes fontSize regression

2023-09-06 01:37 UTC, bnussman-akamai commented on packages/manager/src/features/Footer/Footer.tsx
> +    fontSize: '1rem',
Fixes fontSize regression

2023-09-06 12:43 UTC, cpathipa approved these changes
TY @bnussman-akamai for fixing this.

2023-09-06 20:27 UTC, abailly-akamai requested changes
Thanks for working on this!

This is a PR that needs far more visual testing before approving (CC @cpathipa). We really need to pull the code and test in the browser until we have visual regression tools. I tested quickly and found regressions right away so I suspect there could be more.

![Screenshot 2023-09-06 at 16 19 53](https://github.com/linode/manager/assets/130582365/115df2c4-9f42-43d2-b366-1753b2300bdb)

![Screenshot 2023-09-06 at 16 18 50](https://github.com/linode/manager/assets/130582365/cb697804-d1e9-4b2e-ba66-53ff6f03acb5)

2023-09-06 20:35 UTC, bnussman-akamai commented
@abailly-akamai 

1. First regression was fixed by merging `develop` in (https://github.com/linode/manager/pull/9622)
2. Second screenshot is fixed by 990e8a1

2023-09-06 20:56 UTC, mjac0bs commented
Tbh, I can't see a different in font size in Alban's screenshot [990e8a1](https://github.com/linode/manager/pull/9636/commits/990e8a1dd72d20ea6d840e88226fa226505a62d4) fixed and thought that table arrow was pointing to the typo in "Transferred". It looked wrong spelled as is, so I googled it. Two "r"s.  (I'm sorry 😅 )

2023-09-06 21:16 UTC, bnussman-akamai commented
Wait I'm confused... @abailly-akamai, what is the first screenschot suppose to show?

2023-09-06 21:20 UTC, abailly-akamai commented
@bnussman-akamai 🤣  the grid cells were misaligned

2023-09-06 21:22 UTC, bnussman-akamai commented
Ah okay, my fault. Should be good then! (https://github.com/linode/manager/pull/9622)

2023-09-07 14:20 UTC, abailly-akamai approved these changes
Thanks for the fixes! Looks good - went through most flows and couldn't find aby other visual regressions 👍

2023-09-07 14:59 UTC, merged