test: [M3-7068] - Add Cypress integration tests for Linode migration dialog DC …
linode/manager pull request #9681
Opened 2023-09-14 20:31 UTC by cliu-akamai

## Description 📝
Add new cypress tests for Linode migration dialog DC pricing

## Major Changes 🔄
- Add e2e tests to verify the DC pricing information in Linode migration dialog.

## How to test 🧪
`yarn cy:run -s "cypress/e2e/core/linodes/migratie-linode.spec.ts"`

2023-09-15 21:45 UTC, mjac0bs approved these changes
Thanks for adding! Test passes. ✅ 
![image](https://github.com/linode/manager/assets/114685994/4f9d76e3-8386-41ce-8db1-2efd3e4969c6)

I left a few comments about minor clean up on some comments.

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +   * - Confirms that pricing comparison is not shown in "Region" section migration occurs in the same DC.
```suggestion
   * - Confirms that pricing comparison is not shown in "Region" section if migration occurs in a DC with the same price structure.
```

Here, it is the same DC, because that's the mock data we have to work with, but for clarity, it's probably best to note that the price notice shouldn't show up if the region prices are the same -- even if they're different regions.

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +   * - Confirms that pricing comparison is shown in "Region" section when migration occurs in different DCs.
```suggestion
   * - Confirms that pricing comparison is shown in "Region" section when migration occurs in DCs with different price structures.
```

Similar comment as below.

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +  it('shows DC-specific pricing information when migrating linodes between different DCs', () => {
```suggestion
  it('shows DC-specific pricing information when migrating linodes between differently priced DCs', () => {
```

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    // TODO Remove feature flag mocks once DC pricing is live.
```suggestion
    // TODO: DC Pricing - M3-7073: Remove feature flag mocks once DC pricing is live.
```

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    // TODO Remove feature flag mocks once DC pricing is live.
```suggestion
    // TODO: DC Pricing - M3-7073: Remove feature flag mocks once DC pricing is live.
```

For clarity and ease of clean up later, let's format DC pricing related TODOs with `TODO: DC Pricing`. In this case, we have a related ticket number, so it's useful to include that too.

2023-09-15 21:45 UTC, mjac0bs commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +   * - TODO This test should be updated to ignore the pricing information when the feature is released.
Do we mean that this test just not exist once DC-pricing goes live? The other two test cases test that pricing information is shown and isn't shown depending on region prices.

2023-09-18 17:51 UTC, jdamore-linode requested changes
Nice work @cliu-akamai! I agree with the clean up suggestions that Mariah made, and additionally have a few suggestions of my own.

It also seems like there may've been a misunderstanding on the requirements for one of the tests, so I posted a pair of comments that I hope will clear that up without sacrificing any of the coverage you've already added 👍

2023-09-18 17:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    ).as('migrateReq');
Could we define a helper in `support/intercepts/linodes.ts` named `mockMigrateLinode()` that does this?

2023-09-18 17:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    mockGetLinodeType(dcPricingMockLinodeTypes[1]).as('getLInodeTypeNew');
```suggestion
    // Mock requests to get individual Linode types.
    mockGetLinodeType(dcPricingMockLinodeTypes[0]);
    mockGetLinodeType(dcPricingMockLinodeTypes[1]);
```
No need to assign an alias via `.as("...");` here since we don't `cy.wait()` for it later 👍

2023-09-18 17:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    mockGetLinodeType(dcPricingMockLinodeTypes[1]).as('getLInodeTypeNew');
```suggestion
    // Mock requests to get individual Linode types.
    mockGetLinodeType(dcPricingMockLinodeTypes[0]);
    mockGetLinodeType(dcPricingMockLinodeTypes[1]);
```
(Same as my other comment)

2023-09-18 17:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    const newRegion = getRegionById('us-west');
Expanding on [Mariah's suggestion](https://github.com/linode/manager/pull/9681/files#r1327807976), I think there might be a misunderstanding over the requirements for this one.

We want to test that the DC-specific pricing warnings do not appear if we're migrating from one DC to another DC which has the same pricing structure. Right now, the tests confirm that the user can't select the same region where the Linode is already hosted (which is good to have, too!)

We can extend this pretty easily to cover both cases, but we need to modify these two constants first so that 1) they're two different regions, and 2) they're _not_ the same regions we mock in [dcPricingMockLinodeTypes](https://github.com/linode/manager/blob/develop/packages/manager/cypress/support/constants/dc-specific-pricing.ts#L26)

```suggestion
    const initialRegion = getRegionById('us-southeast');
    const newRegion = getRegionById('us-central');
```

2023-09-18 17:51 UTC, jdamore-linode commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +    cy.get('[data-testid="new-price-panel"]').should('not.exist');
Following up from my other comment, we can extend these assertions to ensure that the test covers both flows: that the user cannot select the same DC where the Linode is already hosted, and that when the user selects another DC with the same price structure, no DC-specific pricing information is shown.

 ```suggestion
    // Confirm that user cannot select the Linode's current DC when migrating.
    cy.findByText('New Region')
      .click()
      .type(`${initialRegion.label}{enter}`);

    cy.findByText('No results').should('be.visible');

    // Confirm that DC pricing information does not show up
    cy.findByText(dcPricingCurrentPriceLabel).should('not.exist');
    cy.get('[data-testid="current-price-panel"]').should('not.exist');
    cy.findByText(dcPricingNewPriceLabel).should('not.exist');
    cy.get('[data-testid="new-price-panel"]').should('not.exist');

    // Change region selection to another region with the same price structure.
    cy.findByText('New Region')
      .click()
      .type(`${newRegion.label}{enter}`);

    // Confirm that DC pricing information still does not show up.
    cy.findByText(dcPricingCurrentPriceLabel).should('not.exist');
    cy.get('[data-testid="current-price-panel"]').should('not.exist');
    cy.findByText(dcPricingNewPriceLabel).should('not.exist');
    cy.get('[data-testid="new-price-panel"]').should('not.exist');

    // Confirm that migration queue button is enabled.
    ui.button
      .findByTitle('Enter Migration Queue')
      .should('be.visible')
      .should('be.enabled');
```

2023-09-19 14:26 UTC, cliu-akamai commented on packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
> +   * - TODO This test should be updated to ignore the pricing information when the feature is released.
Yes, I think so.

2023-09-19 20:36 UTC, jdamore-linode approved these changes
Thanks for the updates @cliu-akamai, everything looks great!

2023-09-20 00:15 UTC, merged