feat: [M3-7017] - Update firewall events
linode/manager pull request #9693
Opened 2023-09-18 16:33 UTC by carrillo-erik

## Description 📝
Changes the copy of the notification message in the `Events` landing page to account for the ability to add `NodeBalancers` to `Firewalls`. 

## Major Changes 🔄
- Replaces `device` for the appropriate device type (`Linode` or `NodeBalancer`) in the message displayed in the `Events` landing page.

## Preview 📷
| Before  | After   |
| ------- | ------- |
| ![m3-7017-before](https://github.com/linode/manager/assets/119514965/ae5708cf-385c-4919-9f09-bb27c26cd8f7) | ![m3-7017-after](https://github.com/linode/manager/assets/119514965/5ee485d4-b763-465c-9171-1e3db74889f6) |

## How to test 🧪
1. On you `localhost` instance, switch over to the `Dev` environment via the CloudManager dev tools.
2. On a existing `Firewall` entity add at least one instance of both `Linode` and `NodeBalancer`.
3. Validate the event notification messages in the `Events` landing page.
4. On the same `Firewall` instance remove the `Linode` and `NodeBalancer` instances that you added in step 2.
5. Validate the event notification messages in the `Events` landing page.

2023-09-18 20:41 UTC, abailly-akamai approved these changes
Looks good! 

tested events on this branch and now showing secondary entities

@carrillo-erik don't forget to add a changeset

2023-09-19 14:16 UTC, bnussman-akamai approved these changes
Both events look good!

<img src="https://github.com/linode/manager/assets/115251059/8a2844fd-4a08-44f1-bcce-36d666eb25ef" width="420px" />

2023-09-19 14:16 UTC, bnussman-akamai commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +        : e.secondary_entity?.type;
Worst case this could return `undefined undefined has been added to Firewall .` if something goes terribly wrong on the API side. Should we consider adding any fallbacks to the `undefined`s?

2023-09-19 14:26 UTC, jdamore-linode requested changes
Looks good! Just have one ask regarding the formatting of NodeBalancers, otherwise ready to approve!

2023-09-19 14:26 UTC, jdamore-linode commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +        : e.secondary_entity?.type;
Is there any chance we can use an object as a key/value dictionary to format the entity type name, similar to [how it's handled on the landing page](https://github.com/linode/manager/blob/feature/firewall-nodebalancer/packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx#L26), so that `nodebalancer` is formatted as `NodeBalancer` instead of `Nodebalancer`? `capitalize()` would still be good as a fallback for theoretical cases where `secondary_entity.type` is something unexpected.

2023-09-19 14:48 UTC, abailly-akamai commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +        : e.secondary_entity?.type;
That's a good idea 👍

2023-09-19 21:15 UTC, carrillo-erik commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +        : e.secondary_entity?.type;
I think we can fallback to the previous generic message in this case.

2023-09-19 21:17 UTC, carrillo-erik commented on packages/manager/src/features/Events/eventMessageGenerator.ts
> +        : e.secondary_entity?.type;
@jdamore-linode Thanks for pointing this out. I went ahead and removed `capitalize()` after taking @bnussman-akamai comment into consideration for the event in which the API returns `undefined`.

2023-09-20 12:35 UTC, jdamore-linode approved these changes
Thanks, @carrillo-erik!

2023-09-20 14:42 UTC, abailly-akamai approved these changes
Changes look good and fallback implemented works 🚢

2023-09-20 14:54 UTC, merged