fix: [M3-7078] codeQL warning with analytics.ts
linode/manager pull request #9700
Opened 2023-09-19 20:29 UTC by abailly-akamai

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-09-19 21:20 UTC, dwiley-akamai reviewed
Do extra spaces in the `category` name impact the integrity of the analytics? Two examples below:

<details>
<summary>Example 1</summary>

Change in code:
![Screenshot 2023-09-19 at 5 13 39 PM](https://github.com/linode/manager/assets/114682940/7629b68a-8560-4e38-a00f-0380a50095ba)

Logged to console:
![Screenshot 2023-09-19 at 5 14 01 PM](https://github.com/linode/manager/assets/114682940/28e99c4a-7015-4360-8d1f-a74046270d4c)
</details>

<details>
<summary>Example 2</summary>

Change in code:
![Screenshot 2023-09-19 at 5 14 52 PM](https://github.com/linode/manager/assets/114682940/9a883944-824c-4c5e-b681-e3fea43cc449)

Logged to console:
![Screenshot 2023-09-19 at 5 15 03 PM](https://github.com/linode/manager/assets/114682940/e8851ef7-d7e1-45d0-b377-7b4acd6e6dc8)

</details>

Would those end up getting classified as different `categories`?

2023-09-20 12:50 UTC, abailly-akamai commented
@dwiley-akamai I don't think so and couldn't find a reference to extra in the [docs](https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en) and elsewhere.

It should be noted that the pipe delimiter in custom events does is already a bit of an edge case we document (we are the ones defining those).

2023-09-20 13:55 UTC, bnussman-akamai requested changes

2023-09-20 13:55 UTC, bnussman-akamai commented on packages/manager/src/utilities/analytics.ts
> +  if ((window as Window)._satellite) {
Because we augmented the global window, I don't think we need the `as` anymore 🎉

```suggestion
  if (window._satellite) {
```

2023-09-20 16:38 UTC, abailly-akamai commented on packages/manager/src/utilities/analytics.ts
> +  if ((window as Window)._satellite) {
ah yeah of course. done

2023-09-20 16:54 UTC, mjac0bs approved these changes
Thanks for the improvements!

Yeah. `|` is an edge case of our own because of the way that our Analytics team is reading and delimiting these custom event attributes in Adobe, and so while we should avoid  introducing pipes into our custom events in the first place, it's great to fix the warning and correctly prevent developer error.

2023-09-20 16:54 UTC, mjac0bs commented on packages/manager/src/utilities/analytics.ts
> +      label: eventPayload.label?.replace(/\|/g, ''),
Thanks! 😅

2023-09-20 16:54 UTC, mjac0bs commented on packages/manager/src/utilities/analytics.ts
> +};
Nice!

2023-09-21 14:32 UTC, bnussman-akamai approved these changes
I confirmed that the `.replace` works! ✅ 

Nice improvement to the types!

2023-09-22 17:45 UTC, merged