feat: [M3-7121] - Add VPC to Linode Add Config dialog
linode/manager pull request #9709
Opened 2023-09-21 19:06 UTC by hana-linode

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-09-30 00:21 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
>                        label={thisInterface.label}
(in the Edit dialog when it is first opened) -- working through a bug where the actual VLAN label isn't coming through reliably here, causing the VLAN dropdown to show "Create or select a VLAN" instead of having the existing VLAN show up as selected 🤔

2023-10-02 19:54 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
>                        label={thisInterface.label}
it's due to the `useEffect` logic in `InterfaceSelect.tsx` -- the VLAN `label` is being overwritten

2023-10-02 22:14 UTC, dwiley-akamai commented
Observed some instances of errors not surfacing, so the error mapping still needs tweaking

2023-10-04 15:05 UTC, dwiley-akamai commented
Going to go ahead and mark this as ready for review now. We are aware of two somewhat edge case errors that don't get surfaced currently for `ipv4.vpc` and `ipv4.nat_1_1`. We will try to get a fix for that into this PR but otherwise, it will be addressed in the coming days in a follow-up PR; this PR represents the last core piece of functionality for the full VPC flows in Cloud.

2023-10-05 15:23 UTC, coliu-akamai commented
If I uncheck the "Auto-assign a VPC IPv4 [...]" checkbox but do not input any IPv4, what's the expected behavior? Currently it creates (or edits) the config:

https://github.com/linode/manager/assets/139280159/5db1d57f-c5d8-42f1-a297-4409ac0ec1c0

2023-10-05 15:53 UTC, coliu-akamai commented
For spacing on smaller viewports, the eth0-2 fields get smaller than the primary field, and the margin between the eth-x and vpc field disappears. The tooltip also gets cutoff:

![image](https://github.com/linode/manager/assets/139280159/6e3483fe-5cee-4b9e-8211-74c7a39c5038)

this could probably be moved to a later ticket if needed

2023-10-05 16:17 UTC, coliu-akamai commented
For some reason I'm no longer able to assign a linode to a subnet via the SubnetAssignLinode drawer -- will look into this one shortly 😖 
![image](https://github.com/linode/manager/assets/139280159/410e4e56-9c9a-4f2a-960b-b237d82ee5f6)

2023-10-05 17:32 UTC, coliu-akamai reviewed
great work!! left a few comments above. Did a first pass through the code, will be doing another one soon

2023-10-05 17:32 UTC, coliu-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
> +    })
nitpick: I see what we're trying to do here -- maybe worth excluding the two properties and then just using rest? (I think these are the properties we want)
```suggestion
    ({
      ipv6, ip_ranges, ...rest
    }) => rest
```

2023-10-05 19:15 UTC, dwiley-akamai commented
> If I uncheck the "Auto-assign a VPC IPv4 [...]" checkbox but do not input any IPv4, what's the expected behavior? Currently it creates (or edits) the config:
> 
> Oh is this one of the errors that don't get surfaced correctly?
> 
>  Screen.Recording.2023-10-05.at.11.21.28.AM.mov 
> followup: when creating a Linode and leaving that blank, an error surfaces for a blank IPv4: ![image](https://user-images.githubusercontent.com/139280159/272968566-9db18790-12cb-403b-b790-a81b6365cfa2.png)

The latter case is because we're able to easily see if the checkbox is unchecked and if there's a blank VPC IPv4 and set the error accordingly (L758-L773 in `LinodeCreateContainter.tsx`). There's only one pair of those fields in the Linode Create flow, whereas here we can have multiple pairs of those fields in the form (one pair per interface)

2023-10-06 13:52 UTC, abailly-akamai requested changes

2023-10-06 13:52 UTC, abailly-akamai commented on packages/api-v4/src/linodes/types.ts
> +  label?: string;
Can you explain these this change? This props should remain required here and remain true to the API type. 

https://www.linode.com/docs/api/linode-instances/#configuration-profile-create

![Screenshot 2023-10-06 at 09 47 08](https://github.com/linode/manager/assets/130582365/f408f31c-281b-4691-9fe6-317895627e37)

If this is a case of an API request that can be undefined it should be handled in the component making the request (early return)

2023-10-06 13:52 UTC, abailly-akamai commented on packages/api-v4/src/linodes/types.ts
> +  vpc_id?: number;
Please confirm these fields are indeed not required (can be undefined) VS being required and nullable.

2023-10-06 18:37 UTC, dwiley-akamai commented
For endpoints that take a list of interfaces, if one of the interfaces has an API error, that should be indicated in the `field` property -- e.g., `interfaces[0].ipv4.vpc` instead of `ipv4.vpc`. API has a bug ticket to address this and it should be done in the near future. In the meantime, I pushed up some code to surface those errors in a non-ideal capacity, just so they don't stay submerged until that fix is in. I'll make a follow-up ticket now for cleaning that up when the API fix is in.

With regards to the error when you uncheck the VPC IPv4 autoassign checkbox but don't input a VPC IPv4: I am going to make a separate ticket to handle that situation and will work on that today.

2023-10-06 18:48 UTC, hana-linode commented on packages/api-v4/src/linodes/types.ts
> +  label?: string;
@abailly-akamai This was a remnant of a previous implementation, will revert this change

2023-10-06 18:49 UTC, hana-linode commented on packages/api-v4/src/linodes/types.ts
> +  vpc_id?: number;
Same here, remnant of a previous implementation. Confirmed via the API Spec docs that these are required and nullable

2023-10-06 21:22 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
> +    })
Going to keep this as-is for now since the linter will give an unused variable warning for the two unused ones currently, but once VPC is in GA and `ipv6` and `ip_ranges` are supported down the line we should be able to remove this bit entirely (just padding `interfaces` without doing any mapping).

2023-10-10 18:59 UTC, coliu-akamai commented
Functionality from above that I checked off still looks good + the error on the Subnet Assign Linodes Drawer is fixed and I saw the tickets for the other error surfacing issues 🚀 

One other thing I'm noticing is that when we edit a Linode's configuration details to include or delete a VPC related interface, the configuration will update, but other information won't until we refresh - something to do with query invalidation/the query cache, most likely?

https://github.com/linode/manager/assets/139280159/9150f54e-7507-4afc-a172-7eddb6d055c7

(Actually this reminds me about the issue for freshly deleted linodes still appearing in VPCs -- let me make a ticket for that so it doesn't get lost 😅)

2023-10-10 21:15 UTC, coliu-akamai approved these changes
awesome work Hana and Dajahi!

approving pending query caching issue is resolved (moved to a new ticket or handled in this PR)!

2023-10-11 14:23 UTC, abailly-akamai reviewed
Nice work! things are working 

I tested both flows (edit and create config) as we will as the linode creation flow and the form behaviors work well. Left a couple comments to clarify and clean up a couple things.

Also, there is no test coverage added here although we are modifying core flows and adding/modifying many components. I know there must be upcoming e2e tests covering some of those cases but we should also have unit tests testing the rendering and some of the utilities added.

2023-10-11 14:23 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
> +  selectedVPCId?: null | number;
Can we confirm these are not required fields VS being required and nullable?

2023-10-11 14:23 UTC, abailly-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
> +              {assignPublicIPv4Address && nat_1_1Error && (
how can we test this error?

also, let's update this variable name so it's human readable, it's pretty unclear from reading the code

2023-10-11 21:34 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
> +        {copy} <Link to="">Learn more</Link>.
The corresponding to-do is on L179, but I'll move it here to be more direct.

2023-10-11 22:16 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
> +              {assignPublicIPv4Address && nat_1_1Error && (
If the linode doesn't have an unused public IP available and the "Assign a public IPv4 address for this Linode" checkbox is checked, the following error gets returned:

![Screenshot 2023-10-03 at 2 24 44 PM](https://github.com/linode/manager/assets/114682940/75dca197-8690-44bb-a590-204b006547b2)

One way to get it to be returned is to have an interface with 2 VPC slots and checking off that checkbox for both of them. You need an extra tag to be able to get to that state.

I'll rename the variable to `publicIPv4Error` or something to that effect.

2023-10-12 19:35 UTC, jaalah-akamai commented
✅ For both the "Add Configuration" and "Edit Configuration" dialogs:

- [x] The section title should be "Networking" and there should be updated helper text that reflects the VPC option
- [x] There should be a "Primary Interface (Default Route)" dropdown
- [x] You should be able to successfully create a config with the designated interfaces
- [x] Field errors should be surfaced (example: uncheck the "Auto-assign a VPC IPv4 [...]" checkbox, input an invalid VPC IPv4, and observe the field error)
- [x] The dialog should reset when closed and re-opened

✅ For the "Edit Configuration" dialog:

- [x] Ensure the "Primary Interface" field displays the correct primary interface (the interface designated as "primary" based on the API payload should be in the eth position indicated by the "Primary Interface" field)
- [x] Changing the primary interface gets reflected in the payload submitted to the API, and after a successful submission, opening the dialog again for that config should reflect the changes you just made

2023-10-12 19:35 UTC, jaalah-akamai approved these changes

2023-10-12 20:04 UTC, dwiley-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx
> +  selectedVPCId?: null | number;
Strictly speaking they are not optional for this component so I removed the `?` which suggests they are.

2023-10-16 14:14 UTC, abailly-akamai approved these changes
Thanks for addressing the feedback and adding coverage - looks great!

Functionality and UI are good as far as my testing went. ✅ 
E2E failure seems unrelated

2023-10-16 14:32 UTC, merged