fix: [M3-7072] - Long drawer titles overlapping close icon
linode/manager pull request #9731
Opened 2023-09-28 17:10 UTC by mjac0bs

## Description 📝
This PR fixes an edge case where very long `Drawer` titles (in this case, due to long firewall names) overlap the `Drawer` close (X) icon.

Note: we fixed a similar issue before with Dialogs, not Drawers.

## Major Changes 🔄
**List highlighting major changes**
- Adds right margin to the drawer title to prevent overlap with close icon
- Reorders props to resolve eslint perfectionist warnings
- Fixes a typo that appears in the component's Storybook documentation

## Preview 📷

| Before | After |
| ---- | ---- |
| ![longdrawertitle_prod](https://github.com/linode/manager/assets/114685994/0fd5e514-92c0-4ac3-9594-9e303feaddcd) | ![Screenshot 2023-10-04 at 6 56 05 AM](https://github.com/linode/manager/assets/114685994/3574a681-fd39-4757-8b02-30be3fe6e0a3) |

## How to test 🧪
1. **How to setup test environment?**
- Create a firewall with a long label (max is 32 characters) at https://cloud.linode.com/firewalls/create with word breaks that get as close as possible to the close button. (e.g. `test-this-re-l-y-l-o-n-gf-ir-e-w`)
- Check out this PR.
- `yarn dev`
2. **How to reproduce the issue (if applicable)?**
- Go to https://cloud.linode.com/firewalls and visit the details page for your new firewall with a really long name.
- Select the `Linodes` tab and click the button to `Add Linodes to Firewall`.
- Observe the AddDeviceDrawer that opens and has a long title that overlaps the close icon. 
3. **How to verify changes?**
- Go to http://localhost:3000/firewalls and visit the details page for your new firewall with a really long name.
- Select the `Linodes` tab and click the button to `Add Linodes to Firewall`.
- Observe the AddDeviceDrawer that opens and has a long title that *does not* overlap the close icon.
- Check a few other drawers throughout the app to ensure there have been no unintended styling regressions from eslint reordering by comparing to prod. 
4. **How to run Unit or E2E tests?**
This was a styling regression.

2023-09-28 17:22 UTC, mjac0bs commented on packages/manager/src/components/Drawer.tsx
> -              position: 'absolute',
I removed this property because with a position of `absolute`: ["the element is removed from the normal document flow, and no space is created for the element in the page layout"](https://developer.mozilla.org/en-US/docs/Web/CSS/position), which is why the drawer title was overlapping the icon button -- as far as it was concerned, it didn't exist. By removing that positioning, we inherit `position: relative` and the icon button element is part of the document flow again. 

I don't see a reason to keep `position: absolute` here, but if we wanted to keep it, another way to address this issue would be to add some `paddingRight` to the `title`.

2023-09-28 17:22 UTC, mjac0bs commented on packages/manager/src/components/Drawer.tsx
> +      anchor="right"
Fixing eslinting warnings.

2023-09-28 20:27 UTC, hana-linode approved these changes
Just recently noticed this issue too, thanks for putting up the fix! Confirmed that long drawer titles are no longer overlapping the close icon. 🎉

2023-09-29 16:08 UTC, bnussman-akamai requested changes
Looks like some extra spacing is being added below all Drawer headers now. 

| `develop` | This PR |
|--------|-------|
|     ![Screenshot 2023-09-29 at 12 04 15 PM](https://github.com/linode/manager/assets/115251059/9d63a3dc-e3b2-44b4-bc96-403dedd7d5cd)   |   ![Screenshot 2023-09-29 at 12 04 32 PM](https://github.com/linode/manager/assets/115251059/3610e28c-84ba-4f18-bef8-789087c65b7b)    |

2023-10-04 14:44 UTC, mjac0bs commented on packages/manager/src/components/Drawer.tsx
> -              position: 'absolute',
Absolute positioning is useful for the icon button because it allows us to position it within the grid slightly offset to the upper right of the title, and does not take the icon button's spacing into account in the document layout. Spacing within icon button affects the bottom margin of the drawer header and was leading to additional spacing between the header and the rest of the drawer when the icon button was included in the document flow (`position: relative` used).

`position: relative`
![Screenshot 2023-10-03 at 9 01 40 PM](https://github.com/linode/manager/assets/114685994/b2b561a1-d2d7-4132-83e7-5dc4e2423db0)

`position: absolute`
![image](https://github.com/linode/manager/assets/114685994/4dd341d5-5f91-400b-ac6e-812a8f5971c6)

2023-10-04 14:44 UTC, mjac0bs commented
> Looks like some extra spacing is being added below all Drawer headers now.

@bnussman-akamai Should be addressed now.

I ended up reverting the change to remove absolute padding and added a right margin to the title to account for the icon button within the drawer header.

| Prod | This Branch |
| --- | --- |
| ![editvolume_prod](https://github.com/linode/manager/assets/114685994/34fb6b2f-c113-46b0-bd68-eca49f2e0d74) | ![editvolume_thisbranch](https://github.com/linode/manager/assets/114685994/b90ab5d5-85eb-437a-9579-f32fd5bfa7cb) |

2023-10-04 18:17 UTC, bnussman-akamai approved these changes
Looks good throughout the app! 🎉

2023-10-04 18:28 UTC, merged