feat: [M3-7185] - Add Drag and Drop support to the Rules Table
linode/manager pull request #9736
Opened 2023-09-29 17:31 UTC by cpathipa

## Description 📝
**Brief description explaining the purpose of the changes**

## Major Changes 🔄
**List highlighting major changes**
- Change #1
- Change #2

## Preview 📷
**Include a screenshot or screen recording of the change**

> **Note**: Use `<video src="" />` tag when including recordings in table

| Before  | After   |
| ------- | ------- |
| Content | Content |

## How to test 🧪
1. **How to setup test environment?**
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request

**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `style`: General styling changes. Does not change any functionality.
- `build`: Changes to the application build.
- `chore`: Other changes that do not impact production code.
- `ci`: Changes to the CI pipeline.
- `docs`: Changes to the documentation docs.
- `perf`: Performance changes.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `change`: Only use for something that doesn’t fit in any other category.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

2023-10-05 14:43 UTC, tyler-akamai commented
Does it make sense to only be able to drag the objects hovering over the drag icon and not the entire row?

Currently, you can move the row by clicking anywhere on the row and dragging it.

2023-10-05 14:51 UTC, tyler-akamai commented
It also seems like the 'Move Up' and 'Move Down'
https://github.com/linode/manager/assets/139489745/eef38917-1407-48cf-8c23-c6c61ebeba84

2023-10-05 14:57 UTC, tyler-akamai commented
Verified:
 - [ ] Drag and drop functionality works as expected
 - [ ] 'Move Up' and 'Move Down' functionality works as expected
 - [ ] Validated Put request integration for updateLoadbalancerRoute according to API spec
 - [ ] yarn test RulesTable Passed

2023-10-06 14:29 UTC, mjac0bs commented
> Should it be so that the user can only drag/drop the row by hovering over _only_ the drag icon and not anywhere in row?
> 
> Currently, you can move the row by clicking anywhere on the row and dragging it, which might defeat the purpose of having the drag icon all the way to the left.

@tyler-akamai I've always thought of the drag icon as an indicator that the row is drag and droppable, not an area to activate that behavior. We'll want this table's behavior to be consistent with Firewall rules, which are drag-n-droppable by clicking anywhere in the row:

Firewall Rules, for reference

https://github.com/linode/manager/assets/114685994/e5f9c522-feca-4f5d-92e4-9a18f86797f0

2023-10-06 15:38 UTC, tyler-akamai commented
> > Should it be so that the user can only drag/drop the row by hovering over _only_ the drag icon and not anywhere in row?
> > Currently, you can move the row by clicking anywhere on the row and dragging it, which might defeat the purpose of having the drag icon all the way to the left.
> 
> @tyler-akamai I've always thought of the drag icon as an indicator that the row is drag and droppable, not an area to activate that behavior. We'll want this table's behavior to be consistent with Firewall rules, which are drag-n-droppable by clicking anywhere in the row:
> 
> Firewall Rules, for reference
> 
>  Screen.Recording.2023-10-06.at.7.25.02.AM.mov

Awesome, thank you for the clarification

2023-10-06 16:02 UTC, mjac0bs requested changes
Nice work, this looks close!
- [X] Test Drag and drop functionality in Rules Table.
- [x] Confirm that Move up and Move down actions behaviors. -- I'm assuming that the weirdness with the `First` and `Last` label remaining unchanged, rather than following the rule when it is moved, is due to the mocks?
- [x] Validate Put request integration for updateLoadbalancerRoute according to API spec.
- [x] Tested drag and drop functionality with VoiceOver in Chrome for accessibility (see attached video) -- just want to note that we've had issues with the Firewall Rules drag and drop accessibility in the past with some browser/screen reader combinations, and we should be mindful of that here. I did not test other screen readers (e.g. JAWS) and browsers in this PR.

Changes requested:
- Fixing the Action button is slightly misaligned again in desktop view and gets very misaligned in mobile view when the table collapses.
- Using TextTooltip rather than a custom tooltip treatment.
- Fixing the alignment of the Service Target and Session Stickiness column. The other table columns have column headers that are left aligned. (See last screenshot.)

![Screenshot 2023-10-06 at 7 32 48 AM](https://github.com/linode/manager/assets/114685994/eb075c44-a61e-4352-8349-14bbe236eed7)

https://github.com/linode/manager/assets/114685994/f73308c8-b27f-4275-b9fe-748555adedc0

![Screenshot 2023-10-06 at 8 59 02 AM](https://github.com/linode/manager/assets/114685994/37a5a42b-1221-441a-9b88-53f8e78a3923)

2023-10-06 16:06 UTC, bnussman-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
> +                                </Tooltip>
I agree 100%

2023-10-06 16:56 UTC, tyler-akamai commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
> +    if (result.destination) {
I believe this if statement is unnecessary. 

Just have:
```js
  const onDragEnd = (result: DropResult) => {
    if (
      !result.destination ||
      result.destination.index === result.source.index
    ) {
      return;
    }

    handleRulesReorder(result.source.index, result.destination!.index);
  };
```

2023-10-06 16:57 UTC, tyler-akamai approved these changes

2023-10-06 17:42 UTC, cpathipa commented
TY @mjac0bs Great feedback. Addressed all the feedback items.

- Fixing the Action button is slightly misaligned again in desktop view and gets very misaligned in mobile view when the table collapses.
- Using TextTooltip rather than a custom tooltip treatment.
- Fixing the alignment of the Service Target and Session Stickiness column. The other table columns have column headers that are left aligned. (screenshot.)

![image](https://github.com/linode/manager/assets/119517080/380d286b-758e-4c8c-aae7-13d796f6630b)

![image](https://github.com/linode/manager/assets/119517080/a0aae34d-d430-4ebb-a599-3ede4da798a2)

2023-10-06 18:42 UTC, mjac0bs commented
@cpathipa - The one thing I'm still seeing is the Session Stickiness and Service Target alignment inconsistencies:

![Screenshot 2023-10-06 at 11 38 42 AM](https://github.com/linode/manager/assets/114685994/cf94797e-1603-419a-903b-43a6e2504c5d)

2023-10-06 19:37 UTC, cpathipa commented
@mjac0bs forgot to adjust the table data columns. 
![image](https://github.com/linode/manager/assets/119517080/8bb6a25c-8611-4371-8b9c-4341f2e0c57c)

2023-10-06 19:41 UTC, jdamore-linode requested changes
I'm getting test failures locally in `load-balancer-routes.spec.ts`. Hoping to circle back with an explanation or fix soon

2023-10-06 19:44 UTC, mjac0bs commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
> +                                sx={{ ...sxItemSpacing, width: '15%' }}
The other columns look great! But this adjustment did have an unintended impact on the Action menu column: 

![Screenshot 2023-10-06 at 12 43 31 PM](https://github.com/linode/manager/assets/114685994/1b25e2bb-e2fc-414e-9bd0-dd86801fc05c)

2023-10-06 19:59 UTC, cpathipa commented on packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
> +                                sx={{ ...sxItemSpacing, width: '15%' }}
Yes, Actually column and body were using only 95% width instead of 100%. So adjusted that in 
a595192
![image](https://github.com/linode/manager/assets/119517080/ff02048a-3f55-40b2-b80d-7af5b1685130)

2023-10-06 20:10 UTC, mjac0bs approved these changes
Thank you for addressed feedback! 🚀 

This looks good, assuming that e2e issue gets resolved.

2023-10-06 20:13 UTC, jdamore-linode commented
@cpathipa I'm not sure why it's different, but I think the test is failing because of the way errors are being displayed in the Add Rule drawer.

`develop`:
<img width="637" alt="Screenshot 2023-10-06 at 3 54 20 PM" src="https://github.com/linode/manager/assets/97627410/7b1e2828-5d6d-478a-9f19-cb2433652092">

`M3-7185`:
<img width="596" alt="Screenshot 2023-10-06 at 4 12 17 PM" src="https://github.com/linode/manager/assets/97627410/592b1354-5354-44de-b19c-2423bf150141">

My best guess is the factory change is playing a role, but I'm admittedly playing catch up on how all this works.

2023-10-09 14:54 UTC, jdamore-linode approved these changes
Thanks @bnussman-akamai, nice work @cpathipa!

Confirmed the test is passing, and manually tested the rules drag and drop (which is really slick!)

2023-10-09 18:29 UTC, merged