refactor: [M3-7230] - Migrate NodeBalancer Node Mode Select TextField to Autocomplete
linode/manager pull request #9754
Opened 2023-10-04 16:31 UTC by bnussman-akamai

## Description 📝

- Very similar PR to https://github.com/linode/manager/pull/9752
- In order to fix up our TextField component, we need to not allow it to be used as a select component. This PR replaces the TextField Select in the NodeBalancer config node component with a modern alternative like Autocomplete

## Major Changes 🔄
- Clean up `Remove` button styles
- Replace `<TextField select>...</TextField>` with an `<Autocomplete />`
- Removes some unused testing attributes

## Preview 📷

| Before  | After   |
| ------- | ------- |
| ![Screenshot 2023-10-04 at 12 28 13 PM](https://github.com/linode/manager/assets/115251059/ff9d7dba-1469-44b5-aa49-b7a68cdf13e1) | ![Screenshot 2023-10-04 at 12 27 57 PM](https://github.com/linode/manager/assets/115251059/0c988860-dc6b-4c48-971c-bf5d5239d1f7) |

## How to test 🧪
- Deploy a Linode with a private ipv4
- Go create a NodeBalancer in the same region as that Linode
- Add your Linode as a node and complete the NodeBalancer creation 
- Go to that NodeBalancer's config and test the `Mode` Select
  - Test styles 🎨
  - Test functionality  🎮

2023-10-05 21:06 UTC, hana-linode requested changes
Looks like removing a Backend Node broke 🤔

https://github.com/linode/manager/assets/115299789/4767f9c6-7acc-4135-a0b5-ce084c2c359b

2023-10-06 03:50 UTC, bnussman-akamai commented
@hana-linode Thank you! Fixed in eb9667a

2023-10-06 18:06 UTC, hana-linode approved these changes
Confirmed that the `Mode` select still looks and works as expected and that remove still works 🎉

2023-10-06 18:06 UTC, hana-linode commented on packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
> +    ];
We can move this outside of the component

2023-10-12 21:28 UTC, jdamore-linode approved these changes
Thanks @bnussman-akamai! Confirmed that the autocomplete field works/looks as expected and that I can add/remove nodes. Also confirmed that I can actually save the config changes

2023-10-12 21:32 UTC, merged