fix: [M3-7262] - Firewall Create Drawer opens in the same tab in the Linode Create Flow
linode/manager pull request #9785
Opened 2023-10-11 21:19 UTC by tyler-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps 
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ ] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [ ] 🔐 Removing all sensitive information from the code and PR description
- [ ] 🚩 Using a feature flag to protect the release
- [ ] 👣 Providing comprehensive reproduction steps
- [ ] 📑 Providing or updating our documentation
- [ ] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2023-10-11 21:23 UTC, tyler-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +    setDropdownValue({ label, value: id });
When the user creates a new Firewall, this code is responsible for setting the value of the dropdown to the recently created Firewall.

2023-10-12 13:53 UTC, tyler-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +          label="Additional Linodes (Optional)"
UX wanted to ensure the user:
- Wasnt looking for current Linode in the dropdown --> 'Additional'
- Knew that this input was optional --> '(Optional)'

2023-10-17 17:51 UTC, tyler-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +export const createFirewallLabel = 'Additional Linodes (Optional)';
UX wanted to ensure the user:
- Wasnt looking for current Linode in the dropdown --> 'Additional'
- Knew that the input was optional --> '(Optional)'

2023-10-18 17:19 UTC, mjac0bs reviewed
Thank you for this awesome testing checklist!

I verified:
- [x] The default Firewall is still 'None'
- [x]  When you choose a Firewall, the summary section at the bottom gets updated ('Firewall Assigned' gets added)
- [x]  When clicking on 'None', the 'Firewall Assigned' gets removed from the summary section
- [x]  When clicking on the 'Create Firewall' link, the Create Firewall Drawer appears in the same tab
- [X]  The Create Firewall Drawer has the text 'Additional Linodes (Optional)', while the Create Firewall Drawer from the Firewall Landing page has the text 'Linodes'
- [x]  Add an additional Linode and ensure it is added when the Firewall is created
- [x]  After creating a new Firewall, that Firewall is selected in the dropdown (in the firewall panel) and the summary section got updated
- [ ]  After creating the Linode, the Linode is properly assigned to the Firewall in the Firewall Landing page.

For the last item, I'm not seeing the linode in the create flow be assigned to the firewall -- just the "additional linode" is assigned. Based on your screencap of this branch and my understanding of the acceptance criteria, I would have expected to see both `longview-linode-do-not-delete` and `debian-us-sea` listed as assigned to firewall `testing123`, but `debian-us-sea` was not. Have you observed any issues with `handleFirewallChange`?

https://github.com/linode/manager/assets/114685994/bf81fe52-ea62-471d-a712-1d760ca9d99b

2023-10-18 21:40 UTC, tyler-akamai commented
> Thank you for this awesome testing checklist!
> 
> I verified:
> 
> * [x]  The default Firewall is still 'None'
> * [x]   When you choose a Firewall, the summary section at the bottom gets updated ('Firewall Assigned' gets added)
> * [x]   When clicking on 'None', the 'Firewall Assigned' gets removed from the summary section
> * [x]   When clicking on the 'Create Firewall' link, the Create Firewall Drawer appears in the same tab
> * [x]   The Create Firewall Drawer has the text 'Additional Linodes (Optional)', while the Create Firewall Drawer from the Firewall Landing page has the text 'Linodes'
> * [x]   Add an additional Linode and ensure it is added when the Firewall is created
> * [x]   After creating a new Firewall, that Firewall is selected in the dropdown (in the firewall panel) and the summary section got updated
> * [ ]   After creating the Linode, the Linode is properly assigned to the Firewall in the Firewall Landing page.
> 
> For the last item, I'm not seeing the linode in the create flow be assigned to the firewall -- just the "additional linode" is assigned. Based on your screencap of this branch and my understanding of the acceptance criteria, I would have expected to see both `longview-linode-do-not-delete` and `debian-us-sea` listed as assigned to firewall `testing123`, but `debian-us-sea` was not. Have you observed any issues with `handleFirewallChange`?
> 
>  Screen.Recording.2023-10-18.at.10.07.57.AM.mov

Good catch! I had to ask @dwiley-akamai on this one. From my understanding this functionality is blocked by an API feature flag. You can test this in `develop` since the feature flag is turned on, but it is not turned on in prod yet.

2023-10-19 15:22 UTC, bnussman-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +  }>(firewallsDropdownOptions[0]);
I feel like we shouldn't have to do:
```ts
  firewallsDropdownOptions.unshift({
    label: 'None',
    value: -1,
  });
```
It should be okay for the dropdown to default to a `value` of `null`.

2023-10-19 15:22 UTC, bnussman-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
>          <Select
I think we should go ahead and switch this to a `Autocomplete`, it should be close to a drop-in replacement.

2023-10-20 13:11 UTC, jaalah-akamai commented
I verified the checklist above and the last item as well. This works in dev, not locally though.

<img width="1326" alt="Screenshot 2023-10-20 at 9 11 03 AM" src="https://github.com/linode/manager/assets/125309814/209f6cb5-32c8-405a-945f-1f0dbf40935f">

2023-10-20 13:15 UTC, jaalah-akamai approved these changes
Looks good pending changes requested from @bnussman-akamai

2023-10-20 18:51 UTC, bnussman-akamai requested changes

2023-10-20 18:51 UTC, bnussman-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +  } | null>(null);
I just realized, we shouldn't need state here. We should have a prop on this component called `selectedFirewallId: number` which we should be using in place of the state

```suggestion
```

2023-10-20 19:04 UTC, mjac0bs approved these changes
- [x]  After creating the Linode, the Linode is properly assigned to the Firewall in the Firewall Landing page.

Verified in `dev` environment, thanks for the clarification!

Functionality looks good. You caught the commented code I was about to note. Other than Banks' feedback and my earlier changelog suggestion, this LGTM.

2023-10-20 20:48 UTC, bnussman-akamai approved these changes
Thanks for addressing the feedback! Great change!

2023-10-20 20:48 UTC, bnussman-akamai commented on packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
> +          noOptionsText="Create a Firewall to assign to this Linode."
Non-bocking feedback: 

This copy feels a bit weird to me. It makes it should like there should be a call to action but there isn't one in the select component.

2023-10-20 20:48 UTC, bnussman-akamai commented on packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
> +    if (this.props.firewallId != null && this.props.firewallId !== -1) {
we probably want to use `!==` and maybe check for undefined too?

2023-10-23 15:27 UTC, merged