fix: [M3-7313] - Migrated Linode dropdown to Autocomplete in Firewall Landing > Create Firewall drawer
linode/manager pull request #9837
Opened 2023-10-24 18:20 UTC by tyler-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
- Migrated Linode Dropdown from LinodeSelect to the Autocomplete component
- Fixed NodeBalancer dropdown incorrect highlighted options
- Added successful toast notification for firewall creation

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- Checkout the feature branch (feature/firewall-nodebalancer)

### Reproduction steps
(How to reproduce the issue, if applicable)
- Navigate to http://localhost:3000/firewalls/create
- Select a NodeBalancer, the correct NodeBalancer is created, but all of the options are highlighted as if they were chosen.
- Create the firewall, there should not be a successful toast notification

### Verification steps 
(How to verify changes)
- Navigate to http://localhost:3000/firewalls/create
- Ensure the Linode dropdown and NodeBalancer dropdown are consistent
- Ensure the dropdowns work as expected
- Ensure there is a successful toast notification when the Firewall is created
- Ensure the firewall is assigned to the selected NodeBalancers and Linodes

## As an Author I have considered 🤔

*Check all that apply*

- [ ] 👀 Doing a self review
- [ ] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [x] 🤏 Splitting feature into small PRs
- [ ] ➕ Adding a changeset
- [ ] 🧪 Providing/Improving test coverage
- [x] 🔐 Removing all sensitive information from the code and PR description
- [x] 🚩 Using a feature flag to protect the release
- [x] 👣 Providing comprehensive reproduction steps
- [x] 📑 Providing or updating our documentation
- [x] 🕛 Scheduling a pair reviewing session
- [ ] 📱 Providing mobile support
- [ ] ♿  Providing accessibility support

2023-10-24 18:29 UTC, tyler-akamai commented on packages/manager/.changeset/pr-9785-fixed-1697059201989.md
> +Firewall Create Drawer opening in a new tab in the Linode Create Flow ([#9785](https://github.com/linode/manager/pull/9785))
@mjac0bs made a good suggestion with the changeset message on my [last PR](https://github.com/linode/manager/pull/9785/files#r1364165448), but I forgot to fix it.

2023-10-24 18:32 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const {
This query was called in the LinodeSelect component but now since we are using the universal Autocomplete component, we need to call it in this component instead.

2023-10-24 18:33 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const optionsFilter = (
I updated this optionsFilter function to filter NodeBalancer **_and_** Linodes

2023-10-25 16:17 UTC, carrillo-erik commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const optionsFilter = (
Sweet!

2023-10-25 16:26 UTC, carrillo-erik commented
Looks great and the NodeBalancer selection bug has been addressed as well. Nice job ✅

2023-10-25 16:27 UTC, carrillo-erik approved these changes

2023-10-25 16:34 UTC, carrillo-erik approved these changes

2023-10-26 16:10 UTC, hana-linode reviewed
Functionality LGTM, noticed one small thing. The selected linodes don't get cleared after clicking cancel

https://github.com/linode/manager/assets/115299789/35ac5391-65ce-4fcd-bee5-f350438f6c43

2023-10-26 18:47 UTC, tyler-akamai commented
> Functionality LGTM, noticed one small thing. The selected linodes don't get cleared after clicking cancel
> 
>  Screen.Recording.2023-10-26.at.12.06.11.PM.mov

Good catch! just fixed

2023-10-26 20:35 UTC, bnussman-akamai requested changes

2023-10-26 20:35 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const [selectedLinodes, setSelectedLinodes] = React.useState<Linode[]>([]);
This seems like duplicate state. We have this data stored in formik so we probably don't want it duplicated here.

2023-10-30 13:33 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const [selectedLinodes, setSelectedLinodes] = React.useState<Linode[]>([]);
I like the filter idea!

2023-10-30 14:39 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const linodeIdSet = new Set(values?.devices?.linodes);
If we use two lists, Big O would be O(n*m) where n is the number of linodes for a given account and m is the number that is selected from that list of linodes

By converting the values.devices.linodes (selectedLinodes) array into a Set, Big O goes from O(n*m) to just O(n)

2023-10-30 14:55 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +          : values.devices?.linodes || [];
I think this logic is backwards. Also, should we even be filtering out selected options? I think the Autocomplete component should still have selected items in the `options` props

2023-10-30 15:02 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +          : values.devices?.linodes || [];
yeah looking at this again, this code can just be removed.

2023-10-30 16:27 UTC, bnussman-akamai approved these changes
Functionality looks good!

2023-10-30 16:27 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const nodebalancerIdSet = new Set(values?.devices?.nodebalancers);
I wonder how expensive it is to create these `Sets` on every render?

2023-10-30 16:27 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> -            helperText={FIREWALL_HELPER_TEXT}
Are we loosing this helper text?

2023-10-30 16:27 UTC, bnussman-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> -          <LinodeSelect
I personally like the `LinodeSelect` abstraction as opposed to using `Autcompelete`s directly, but I don't want to block this work. 

This may need a cafe discussion

2023-10-30 16:42 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> -            helperText={FIREWALL_HELPER_TEXT}
yeah I compared it to the mockups, and realized the mockups dont have it.

2023-10-30 17:18 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> -          <LinodeSelect
Yeah this is a good topic, I will add it to the agenda.

2023-10-30 18:42 UTC, tyler-akamai commented on packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
> +    const nodebalancerIdSet = new Set(values?.devices?.nodebalancers);
Just did some research. Sets are relatively inexpensive if we put it behind a `useMemo` and only update it if the user selects or deselects a Linode/NodeBalancer.

However, I was comparing using a List vs a Set and it seems like a Set is a better option if the list is continuously changing and a List is better if there are not many changes or its a one-off change. Since the user would most likely be either selecting limited number of Linodes/NodeBalancers at once, or hitting the Select All button, I think the usage better aligns with a List instead of a Set.

2023-10-30 19:27 UTC, hana-linode approved these changes
- [x] Ensure the Linode dropdown and NodeBalancer dropdown are consistent
- [x] Ensure the dropdowns work as expected
- [x] Ensure there is a successful toast notification when the Firewall is created
- [x] Ensure the firewall is assigned to the selected NodeBalancers and Linodes

2023-10-30 19:29 UTC, merged